### ISSUE TITLE
C# Dev kit Fails to load on Mac OS

### ISSUE THREAD

**Issue by loldot** [microsoft/vscode-dotnettools#1002]
Type: <b>Bug</b>

When opening a folder containing a .net 8 csproj and solution, dev kit fails to load with what appears to be a certifcate validation error. 

Output from the extension:

```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "/opt/homebrew/Cellar/dotnet/8.0.1/libexec/dotnet"
.NET server STDERR: Failed to load /opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib, error: dlopen(/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' (code signature in <D9F7F506-1864-386E-9591-E9805FDE7F6C> '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' (no such file), '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' (code signature in <D9F7F506-1864-386E-9591-E9805FDE7F6C> '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
The library libhostfxr.dylib was found, but loading it from /opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

Extension version: 1.4.29
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 6, 6|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|. --crash-reporter-id 7395aa72-be27-4975-9cab-e249a90c7add|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
7ghi1836:30988842

```

</details>

**Comment by loldot** [comment]
There's a lot of log files in that directory, this is the content of `20240318T140206/window4/exthost/output_logging_20240318T144408/3-.NET Runtime.log` 

```
ms-dotnettools.csdevkit requested to download the .NET Runtime.
Downloading .NET version(s) 8.0.3~arm64 .......... Done!
.NET 8.0.3~arm64 executable path: /Users/lorentz/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64/dotnet
```

**Comment by rspears74** [comment]
Getting the same error. I have .NET 8.0.1 installed via homebrew as well.

**Comment by nagilson** [comment]
Thank you for the log and sorry for my delay. Based on the log the install was successful. This indeed appears to be a problem with the signatures, I will contact the runtime team about this.

**Comment by neisburak** [comment]
@nagilson Are there any update with the issue?

**Comment by nagilson** [comment]
Still waiting to hear back.

**Comment by nagilson** [comment]
Chatted with them and we think there is indeed a signature issue so made an issue on the runtime side to track.

**Comment by nagilson** [comment]
Is your failing install coming from homebrew or is it being downloaded by the .NET Install Tool from the '.NET Runtime' output tab?

**Comment by rspears74** [comment]
Mine is using the homebrew version.

**Comment by loldot** [comment]
I have installed the dotnet runtime via homebrew, but dev kit does not use that version it seems. VS code was updated now, and it appears to launch the downloaded runtime without problem:

```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/Users/lorentz/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64/dotnet"
.NET server started and IPC established in 22182ms
Completed Spawn .NET server (25750ms)
Completed Clear environment (27132ms)
Completed Open a solution with environment service (27235ms)
Starting Restore solution...
Completed Open a solution (27242ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore <solution> --interactive...
Completed command: "dotnet" restore <solution> --interactive (11099ms)
Completed NuGet restore.
Completed Restore solution (11101ms)
```

**Comment by merkithuseyin** [comment]
also encountered this problem with dotnet installed via brew ("brew install dotnet")
following [this suggestion](https://github.com/Homebrew/homebrew-core/issues/168205#issuecomment-2041465259), reinstalling it with --cask flag fixed it for me:

1. "brew uninstall dotnet"
2. "brew install --cask dotnet-sdk"
3. re-install "C# Dev Kit" extension on VSCode

**Comment by rspears74** [comment]
Thank you @merkithuseyin, this worked for me!

**Comment by emilbratt** [comment]
> also encountered this problem with dotnet installed via brew ("brew install dotnet") following [this suggestion](https://github.com/Homebrew/homebrew-core/issues/168205#issuecomment-2041465259), reinstalling it with --cask flag fixed it for me:
> 
>     1. "brew uninstall dotnet"
> 
>     2. "brew install --cask dotnet-sdk"
> 
>     3. re-install "C# Dev Kit" extension on VSCode

Worked for me! Thanks!

**Comment by LamMinFight** [comment]
> also encountered this problem with dotnet installed via brew ("brew install dotnet") following [this suggestion](https://github.com/Homebrew/homebrew-core/issues/168205#issuecomment-2041465259), reinstalling it with --cask flag fixed it for me:
> 
> 1. "brew uninstall dotnet"
> 2. "brew install --cask dotnet-sdk"
> 3. re-install "C# Dev Kit" extension on VSCode

wow, it worked for me. Thanks!

**Comment by 101v** [comment]
> also encountered this problem with dotnet installed via brew ("brew install dotnet") following [this suggestion](https://github.com/Homebrew/homebrew-core/issues/168205#issuecomment-2041465259), reinstalling it with --cask flag fixed it for me:
> 
> 1. "brew uninstall dotnet"
> 2. "brew install --cask dotnet-sdk"
> 3. re-install "C# Dev Kit" extension on VSCode

Thanks a ton. It worked like a charm.

**Comment by nagilson** [comment]
We think this issue has been resolved, if you experience it again please let us know. The workaround above should work and it will re-trigger the installation with the fix.

**Comment by jaraco** [comment]
I ran into this issue today. I'm setting up C# development for the first time. Is there a reason this is closed? At the very least, if the workaround is the official "solution", shouldn't the error message include a pointer to official guidance on how to install dotnet in a compatible way? Better would be for the brew-installed version to be compatible and not require installation from cask.

**Comment by nagilson** [comment]
Was your exact issue invalid team ids? This is due to an invalid runtime that was shipped. The workaround is for people to uninstall the bad shipped file then reinstall it.

**Comment by jpda** [comment]
> a process that is signed with one Apple Code Signing Identity cannot load libraries that are signed by a different team, or in this case, no team (ad-hoc).

This also prevents using daily sdk builds from [here](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md#table) - in the absence of signed nightly sdks, is there a way to make this configurable? Or a pre-rel devkit extension that can set `com.apple.security.cs.disable-library-validation`?

For example, I need a [fix](https://github.com/dotnet/announcements/issues/324) that's in net9.0-rc.2, which isn't out yet, but which is in nightlies.

**Comment by akindo** [comment]
> also encountered this problem with dotnet installed via brew ("brew install dotnet") following [this suggestion](https://github.com/Homebrew/homebrew-core/issues/168205#issuecomment-2041465259), reinstalling it with --cask flag fixed it for me:
> 
>     1. "brew uninstall dotnet"
> 
>     2. "brew install --cask dotnet-sdk"
> 
>     3. re-install "C# Dev Kit" extension on VSCode

Still the fix in December, 2024. :grin:
