### ISSUE TITLE
[BUG] Can't select debug target on macOS and debug MAUI app using VSCode

### ISSUE THREAD

**Issue by Serotonindude** [microsoft/vscode-dotnettools#1004]
### Describe the Issue

Hi, 
when I open an XAML or CS file and click on the curly braces in the bottom right corner of vscode to select my debug target, there's no option there to do so: 

<img width="189" alt="grafik" src="https://github.com/microsoft/vscode-dotnettools/assets/36316983/68656064-f555-4184-a4df-4bb4d589d6fb">

If I do CMD+Shift+P  > .NET MAUI: Pick macOS Device ... nothing happens. 

If I start debugging with F5 or Debug menu on the left, I get an endless progress bar running, but nothing happens:

<img width="224" alt="grafik" src="https://github.com/microsoft/vscode-dotnettools/assets/36316983/be6d4840-ffcc-4d1b-bba6-9b1882077c96">

If I do right-click on the project > Debug > Start new instance it builds and then I get an error: 

```
 *  Executing task: dotnet: build /Users/trick/Projects/Work/MyMauiApp/MyMauiApp.csproj 

dotnet build /Users/trick/Projects/Work/MyMauiApp/MyMauiApp.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
MSBuild-Version 17.9.4+90725d08d für .NET
  Wiederherzustellende Projekte werden ermittelt...
  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
  Detected signing identity:
          
    Bundle Id: com.companyname.mymauiapp
    App Id: com.companyname.mymauiapp
  MyMauiApp -> /Users/trick/Projects/Work/MyMauiApp/bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/MyMauiApp.dll
  Das Optimieren der Assembly für die Größe kann das Verhalten der App ändern. Stellen Sie sicher, dass nach der Veröffentlichung Tests durchgeführt werden. Informationen finden Sie unter https://aka.ms/dotnet-illink.
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
 
<img width="381" alt="grafik" src="https://github.com/microsoft/vscode-dotnettools/assets/36316983/f864176f-4c41-49e9-ba99-88c9774cdfb0">

If i compile and run it on the commandline using ```dotnet build -t:Run -f net8.0-maccatalyst``` it works just fine...

my launch.json:
```
"version": "0.2.0",
    "configurations": [
        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }
    ]
```

Relevant other issues might be: #938, #925

### Steps To Reproduce

I don't know... I did the steps to setup my mac for .net 8 and maui and it works on command line but not in vs code...

### Expected Behavior

Should let me select the debug target and debug the MAUI app.

### Environment Information

- OS: macOS 14.4 (23E214)
- relevant VSCode extensions: .NET MAUI v0.9.7, C# v2.22.3, C# Dev Kit v1.4.29
- Xcode Version 15.3 (15E204a)

**Comment by mauroa** [comment]
Hi @Serotonindude, could you pelase share the content of the .NET MAUI output pane? Also, does it make any difference if you remove the launch.json? You shouldn't need to define it for MAUI apps.
Finally, debugging from right click in the project is still not supported for MAUI, so for now please use F5 and select ".NET MAUI" as the debug option.

**Comment by Serotonindude** [comment]
Sorry, completely forgot about this one. 
There's nothing in the output pane if I start debugging (F5), since nothing happens if I do so.
Right clicking and debug gives at least: 

```
 *  Executing task: dotnet: build /Users/trick/Projects/Work/MyMauiApp/MyMauiApp.csproj 

dotnet build /Users/trick/Projects/Work/MyMauiApp/MyMauiApp.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
MSBuild-Version 17.9.4+90725d08d für .NET
  Wiederherzustellende Projekte werden ermittelt...
  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
  Detected signing identity:
          
    Bundle Id: com.companyname.mymauiapp
    App Id: com.companyname.mymauiapp
  MyMauiApp -> /Users/trick/Projects/Work/MyMauiApp/bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/MyMauiApp.dll
  Das Optimieren der Assembly für die Größe kann das Verhalten der App ändern. Stellen Sie sicher, dass nach der Veröffentlichung Tests durchgeführt werden. Informationen finden Sie unter https://aka.ms/dotnet-illink.
 *  Terminal will be reused by tasks, press any key to close it. 
```

If I remove the launch.json, I do not have a .NET MAUI debug option...

**Comment by Serotonindude** [comment]
Not sure if it got something to do with the following problem when I open up VSCode:

<img width="378" alt="grafik" src="https://github.com/microsoft/vscode-dotnettools/assets/36316983/767ef5d2-be7d-43c2-90fb-171463a39fa2">

```
=====================
3/27/2024 7:16:40 PM
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
===================
```

**Comment by evgenygunko** [comment]
I have the same issue. I've created a new MAUI project (not Blazor) from template and trying to run it on MacOS with VS Code. I can compile it, but can't run with F5. Nothing happens. When I click on "{}" there is only one option "MauiApp1
Startup Project". There is no any message in ".NET MAUI" window. And I can run the process if I run the command "dotnet build -t:Run -f net8.0-maccatalyst".

I have older mac which can only upgrade to Ventura, so my XCode is v 15.0.1.

What I'd like to get: start debugger with F5

**Comment by magnatronus** [comment]
Possibly the same issue here.

- Mac silicon(M2)
- Followed getting started for .NET Maui
- No issues in install or setup

Cannot get app running from within VSC, but if I run ```dotnet build -t:Run -f net8.0-maccatalyst```. from  a terminal it will run with issue. Looks like I am missing a step/setup for VSC?

**Comment by sraabh3ko** [comment]
Had the same Problem and also was stuck on "Xcode: verifying environment" after starting VS Code.

This solved it for me: https://github.com/microsoft/vscode-dotnettools/issues/1148#issuecomment-2135643716.
Maybe this helps anyone as well.

**Comment by evgenygunko** [comment]
@sraabh3ko thanks a lot! Apparently I also had a lot of simulators, some files dated back to 2017. After deleting them and restating Mac, I see now "macOS: My Mac" as a debug target and can start a debug session with F5.
![Screenshot 2024-06-05 at 21 44 58](https://github.com/microsoft/vscode-dotnettools/assets/24902639/34bcb993-7deb-48d9-95e5-577a7477e900)

**Comment by mauroa** [comment]
This issue has been fixed on latest .NET MAUI release version. Please ensure to also update C# and C# DevKit to latest pre-release versions as well. Thanks
