### ISSUE TITLE
Allow the bottom pane to collapse

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1009]
Type: <b>Feature Request</b>

It would be nice if the pane at the bottom could collapse and expand similar to Visual Studio.  Basically auto hide unless you click on it or if you run the project.  There isn't a real reason for it to take up screen real estate while you're coding.  Currently, you just have the ability to close it.

Extension version: 1.4.29
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by timheuer** [comment]
should we move this to microsoft/vscode?
