### ISSUE TITLE
[SUGGESTION] C# Dev Kit should not edit/create settings.json for single-solution repos

### ISSUE THREAD

**Issue by martincostello** [microsoft/vscode-dotnettools#101]
### Describe the feature you'd like

Since installing the new C# Dev Kit, every time I open a project in VS Code I get a change to commit in Git to add a `.vscode/settings.json` file (or edit an existing one) with a `dotnet.defaultSolution` property.

All of my projects only have one `.sln` file in them, so it would be preferrable for the Dev Kit to assume it as the default and not require me to commit a change to the repo.

**Comment by lifengl** [comment]
The reason behind this is that we have to scan the entire folder cone to conform there is only a single .sln file, which is a performance punishment that we don't want every time when you reopen the workspace. Maybe the scan should stop if there is a single .sln file on the root, or some adjustments there to reduce the need of caching this setting.

**Comment by mjrist** [comment]
I set the `dotnet.defaultSolution` property in my remote container settings. When I open vscode it loads that default as expected.

However, it seems that every time you select a solution using the `.NET Open Solution` command it updates the value of `dotnet.defaultSolution` in the workspace settings file `.vscode/settings.json`.

This doesn't make sense to me. I'm not trying to change the default and I also don't want this setting change committed. I'm just trying to temporarily load a different solution.

**Comment by lifengl** [comment]
we will separate this setting, and store extension solution state into extension workspaceState, which should address both problems.

**Comment by lifengl** [comment]
this should have been fixed.
