### ISSUE TITLE
[BUG] <Unable to attach the Unity Debugger>

### ISSUE THREAD

**Issue by Sijie-Yan** [microsoft/vscode-dotnettools#1010]
### Describe the Issue

After I press F5 to debug, here comes the issue
![微信图片_20240321134440](https://github.com/microsoft/vscode-dotnettools/assets/82753877/c7caf93a-dedc-4ce9-8d10-ddf8830898cc)
And Here are the extensions I have
![微信图片_20240321134548](https://github.com/microsoft/vscode-dotnettools/assets/82753877/9288126a-a238-452d-9495-607ade67d44b)
The Dotnet info
![微信图片_20240321134516](https://github.com/microsoft/vscode-dotnettools/assets/82753877/603cba69-5254-45af-a4d1-3651f9d197e4)
And also I have the debugLog says the error should be NullReferenceException
![微信图片_20240321134533](https://github.com/microsoft/vscode-dotnettools/assets/82753877/a2c71622-e653-46e2-80d3-8e115d7f5296)

### Steps To Reproduce

Please help me with this issue which troubles me 2 days. I don't know if it's my problem or not...

**Comment by jbevain** [comment]
Hi @Sijie-Yan,

Could you share the content of your `.vscode/launch.json` file?

What debug configuration is currently selected in the debug view?

<img width="405" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/f6b9915e-9f9f-4b16-b4a8-7105d88a569a">

**Comment by isiki0710** [comment]
I got the same error.

{
	"folders": [
		{
			"path": "Assets"
		}
	],
	"settings": {
		"files.associations": {
			"*.lua.txt": "lua"
		},
		"files.exclude": {
			"**/.git": true,
			"**/.svn": true,
			"**/.hg": true,
            "**/*.png": true,
            "**/*.mat": true,
			"**/CVS": true,
			"**/.DS_Store": true,
			"**/*.bytes": true,

			"**/*.meta":true,
			"*.rsp":true,
			"*.xml":true,

			".vscode/":true,
			"luaIde/readMe.txt":true,
			"Demigiant/":true,
			"Effects/":true,
            "Audios/":true,
			"Plugins/":true,
			"Presets/":true,
			"Scenes/":true,
			"Spine/":true,
			"Test/":true,
			"TextMesh Pro/":true,
			"XLua/":true,
            "Materials/":true,
            "UI":true,
			"Scripts/EncryptLua/":true
		},
		"editor.snippetSuggestions": "bottom",
		"editor.renderControlCharacters": true,
	},
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"type": "emmylua_new",
				"request": "launch",
				"name": "EmmyLua Debug",
				"host": "localhost",
				"port": 9967,
				"ext": [
					".lua",
					".lua.txt",
					".lua.bytes"
				],
				"ideConnectDebugger": true
			},
			{
				"type": "LuaHelper-Debug",
				"request": "launch",
				"name": "LuaHelper-Attach",
				"description": "通用模式,通常调试项目请选择此模式",
				"cwd": "${workspaceFolder}/Scripts/LuaRaw",
				"luaFileExtension": ".lua",
				"connectionPort": 8818,
				"stopOnEntry": true,
				"useCHook": true,
				"autoPathMode": true
			},
			{
				"name": "Unity Editor",
				"type": "vstuc",
				"request": "attach",
				"endPoint": "127.0.0.1:56736"
			}
		]
	}
}

**Comment by Sijie-Yan** [comment]
Hi@jbevain 
![微信图片_20240326131002](https://github.com/microsoft/vscode-dotnettools/assets/82753877/8deb267a-9c16-4eed-9258-ec30be31ddc4)
![微信图片_20240326131128](https://github.com/microsoft/vscode-dotnettools/assets/82753877/bdef818a-d0ac-4b9e-9c8f-41dc86f8e540)
i notice that your vscode UI is different, do you use any extensions? I want to change to your UI style haha

**Comment by Sijie-Yan** [comment]
@jbevain 
![微信图片_20240327125209](https://github.com/microsoft/vscode-dotnettools/assets/82753877/23357ff7-f878-4ee2-a8f7-0cc82acd2e30)
![微信图片_20240327125217](https://github.com/microsoft/vscode-dotnettools/assets/82753877/cc5a89f8-e967-400e-a5aa-3199dce8f944)
![微信图片_20240327125252](https://github.com/microsoft/vscode-dotnettools/assets/82753877/2ed9bc0d-8941-4036-9566-3eefc678c084)
1. I can't see the debugger icon in Unity. The Unity version is 2019.4.40f1c1.
2. I've checked the firewall, they are all closed.
3. The Unity output just says the error is "read error", I don't know what it means.
4. The visual code is the newiest version.

**Comment by jbevain** [comment]
Thanks for providing all the information. We're working on a build that will have more logging that you can try. We'll get back to you shortly.

**Comment by jbevain** [comment]
@Sijie-Yan hello! Could you reach out to vstusp@microsoft.com, we'd like to share a build of the Unity extension with more logging to help us figure out what's going on. Thank you!

**Comment by Sijie-Yan** [comment]
@jbevain 
I updated my Unity Editor version to 2022.3.17f1c1 and the problem solved. The problem should be something about the old version one. Thanks !
