### ISSUE TITLE
[SUGGESTION] Unity: Moving Scripts on VS Code Should Update .meta Files on Unity

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-dotnettools#1016]
### Describe the feature you'd like

Currently, when moving scripts on VS Code's File Explorer, it doesn't update the `.meta` files on Unity's side. This results in broken script references on prefabs as the `.meta` file is regenerated. On a lot of prefabs, this is a chore to fix. For reference, JetBrains Rider already does this automatically.

Suggestion: Automatically update the relevant `.meta` files on Unity's side when moving them in VS Code's explorer.

### Alternatives considered

Switching over to the Unity editor and moving the scripts there instead of VS Code properly updates the `.meta` file. However, it would be preferable to do this on the code editor instead like in Rider.

### Environment Information

- OS: Windows
- VS Code Version: 1.87.2
- Extension Version: 1.0.0

**Comment by jbevain** [comment]
@nscimerical curious, that should already be the case, we do monitor the workspace for files being moved/renamed to rename their corresponding `.meta` files. Maybe we're missing something, but I've tested things locally and things work as expected. Could you walk-us through an example that doesn't work? Thank you!
