### ISSUE TITLE
[BUG] Dev Kit is not working as expected

### ISSUE THREAD

**Issue by soyhanbeyazit** [microsoft/vscode-dotnettools#1023]
### Describe the Issue

When I open a .NET / C# project on my VS code on Macbook M1 chip, 

I receive such a message on the output of C# Dev Kit

Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/usr/local/share/dotnet/dotnet"
.NET server STDERR: Failed to load /usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib, 0x0001): tried: '/usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib' (no such file), '/usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
     
     
My settings.json has this following 

```
"dotnetAcquisitionExtension.existingDotnetPath": [
    {
      "extensionId": "ms-dotnettools.csharp",
      "path": "/usr/local/share/dotnet/dotnet"
    },
    {
      "extensionId": "ms-dotnettools.csdevkit",
      "path": "/usr/local/share/dotnet/dotnet"
    }
  ] 
```

### Environment Information

- OS: MacOS Sonoma 14.4
- VS Code Version: 1.86.0 Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937

dotnet info output looks like this

```
➜  dotnet dotnet --info    
.NET SDK:
 Version:           8.0.203
 Commit:            5e1ceea679
 Workload version:  8.0.200-manifests.4e94be9c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.203/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: arm64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.420 [/usr/local/share/dotnet/sdk]
  8.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  DOTNET_ROOT       [/Users/soyhanbeyazit/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by AbhitejJohn** [comment]
@tmeschter : Would you know if we'd want to involve the runtime team for this? Curious what the next steps for this are.

**Comment by yuxiaomin** [comment]
I ran into exactly the same issue on macOS M2 chip machine.

**Comment by arkalyanms** [comment]
@tmeschter fyi. This is marked as high-pri

**Comment by kvenkatrajan** [comment]
@arkalyanms - this is likely an aquisition/cps issue.


+ @nagilson, @lifengl   can you have a look please?
_The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/8.0.3/libhostfxr.dylib failed_

**Comment by Michael-Eng** [comment]
@nagilson Can you help? What would cause this?  Could it be DOTNET_ROOT pointing to an incorrect directory?

**Comment by nagilson** [comment]
This user has a custom install of .NET they managed on their own. It looks like they need a 64 bit .NET which is why its failing to load, in this architecture it is installed in a different folder than the one they gave, so it is an incorrect path. I would recommend to instead set the path setting as `/usr/local/share/dotnet/x64`, if that was installed. 

They can also try `export DOTNET_ROOT=/usr/local/share/dotnet/x64`

**Comment by Michael-Eng** [comment]
Please also confirm you are using the x64 version of C# and C# Dev Kit. VSCode will detect Apple Silicon and will install the ARM64 version of the extensions. 

If you must use x64 you should explicitly download the x64 version of the extension by going to the marketplace in the browser and installing the vsixes directly.

![image](https://github.com/microsoft/vscode-dotnettools/assets/18017073/e76af169-627e-4bd4-8afa-7ae36f783aec)

**Comment by lifengl** [comment]
Make sure that you install the macOS Apple Silicon version of the C# Dev Kit. The macOS Intel version extension would not work on M1/M2/.. mac machine.

**Comment by arkalyanms** [comment]
This is a known vscode marketplace bug tracked by https://github.com/microsoft/vscode/issues/185218

**Comment by davidortinau** [comment]
fwiw - I encounter this error when installing un-signed/un-notarized builds of .NET after clearing the installer from quarantine in "Privacy & Security". Downloading and installing the correct architecture that is notarized for macOS arm64 resolved the error for me on an M1 MacBook.

**Comment by nagilson** [comment]
We believe this issue has been fixed, let us know if you encounter it again.
