### ISSUE TITLE
[SUGGESTION] Add ability to open solution filters

### ISSUE THREAD

**Issue by levimatheri** [microsoft/vscode-dotnettools#103]
### Describe the feature you'd like

With Visual Studio 2022, we are able to setup and use solution filters (*.slnf), which allows us to only load certain projects and not the entire solution. This would be really nice with C# dev kit to be able to do the same in VS Code

### Alternatives considered

N/A

### Environment Information

N/A

**Comment by mattleibow** [comment]
This is quite a high priority for project that are semi-complex. I am working on the maui repository and I can't get anything to work as the restore fails right at the beginning.

The solution has a whole collection of platform-specific projects, and when I am running on macOS all my Windows/WPF/WinForms project just stop everything.

I have a set of solution filters that I use today in main VS and also to build on the CLI. The only part that is missing is the solution filters.

My current workaround is to add a new solution that is the same as a solution filter just for VSCode, but it is not the best as thing go out of sync. And the sln file format is not like anything amazing to even touch. So nightmares entail when trying to sync manually.

**Comment by ZacharyPatten** [comment]
Not only would it be nice to support `.slnf` files, but right now there is actually a bug. If you manually set an `.slnf` file in the `settings.json` such as `"dotnet.defaultSolution": "dotnet-console-games.slnf"`, then the "Open Solution" button that appears in the Solution Explorer will be unresponsive. You have to manually remove the `.slnf` file in the `settings.json` and restart the extension and/or Visual Studio code for it to become responsive again.

**Comment by fforjan** [comment]
Same request for us, we have one solution which contains everything, some C++, some C# with .net472 and some asp.net core with .net 6.
We already have a set of solution filters available to use for Visual Studio to only work in some area.

it would be awesome to allow us to only use the asp.net core / net 6 part without all the rests.

**Comment by jchappell-cordel** [comment]
+1 from my team, we've got a fairly large legacy mono-repo with ~15 `.slnf` files that help to reduce the amount of projects that we target with our overall `.sln` file.

**Comment by stefc** [comment]
I would also like this feature inside C# Dev Kit. The slnf help us a lot on a huge solution with speed up development cycle ;)

**Comment by flensrocker** [comment]
Same here.

In my mono repo the slnf-files are in the same folder as the main sln-file. When I open that folder I want to choose, which solution(-filter) I want to open.

Thank you!

**Comment by mlancione** [comment]
Any progress on this issue? It's a very important feature for large multi-platform solutions.

**Comment by fforjan** [comment]
With the latest version, I can now open the solution filter in vscode.
BUT this is still broken in term of workflow
```
dotnet build MySolution.sln /target:Common\MyProject /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
MSBuild version 17.9.8+b34f75857 for .NET
wix311.ca.sdk.targets(59,5): error MSB4062: The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\WiX Toolset v3.11\bin\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [Installer.csproj]
wix311.ca.sdk.targets(59,5): error MSB4062: The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\WiX Toolset v3.11\bin\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [OtherInstaller.csproj]
```
The intent of the solution filter is to work on projects which work in VSCode, but skip the others.
In our case, we have a full solution which contains everything, including an installer.
I would like to use VSCode for a subpart of the solution, but this is still trying to load/parse everything and in this scenario, it is a bit useless unfortunately :(

**Comment by fforjan** [comment]
not only that but any dotnet action still work on the full solution, for example even after hacking the readregistry tasks, I can see that dotnet restore is invoke on ALL projects into the solution ?

**Comment by webreidi** [comment]
You can now use the ".NET: Open Solution" command and select a .slnf file for it to open and it works. If you are still unable to open solution filters, please reopen this issue.
