### ISSUE TITLE
Policy: DevKit should not take a required dependency on `.200+` SDK features

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#1033]
From vscode-csharp created by [richlander](https://github.com/richlander): dotnet/vscode-csharp#7006  

_This came from a discussion of possible new features taking a dependency on feature-band SDK capabilities_

Linux distros that offer .NET (as a general rule) only offer `.1xx` feature band SDK versions. We've put a lot of effort into making Linux distros successful with source build. Source build is `.1xx` only. We want people to be happy and satisfied with using the .NET that is available in RHEL, Ubuntu, and friends.

As a result, we need a policy that any DevKit features that rely on `.2xx+` functionality fail gracefully when using a `.1xx` SDK.

**Comment by jebriede** [comment]
Is the ask to not depend on .NET SDK or to fail gracefully when the required version is not installed?

Currently, we fail gracefully if the required .NET SDK version is not installed on the user's machine, and we offer guidance on what version is required and how to install it.

**Comment by timheuer** [comment]
The impact here in having a strong dependency is that with the new changes to certain Linux distros, the acquisition ofr a .2xx SDK will not be intuitive, nor does the SDK acquisition pack handle these any more. So it will be a manual step to get that SDK, and has potential to impact the user's machine in other ways as we've seen.

The goal would be to prevent this.  If "fail gracefully" means that nobody gets NuGet commands, that feels bad.

**Comment by richlander** [comment]
https://devblogs.microsoft.com/dotnet/whats-new-for-dotnet-in-ubuntu-2404/

**Comment by jebriede** [comment]
Team Triage: Thanks for the feedback. We believe this will be addressed when this work is completed: https://github.com/microsoft/vscode-dotnettools/issues/1140.
