### ISSUE TITLE
Support new VS Code code coverage adapter/UI

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#1035]
### Describe the feature you'd like

VS Code is providing new surface area for showing code coverage: https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/testing.md#test-coverage
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/ee2073d2-7198-4c98-8fba-571057815813)

The test adapter in the C# Dev Kit hould enhance to include coverage information that is provided to this new experience for C# developers.

### Alternatives considered

Coverage Gutters is a provider that provides coverlet reading and gutter highlighting. But does not integrate with this new pattern

**Comment by ChristoWolf** [comment]
This is already tracked in #554.

**Comment by jmlane** [comment]
Looking forward to this addition!

**Comment by webreidi** [comment]
This is underway. In the most recent release, you can now view a coverage report with C# Dev Kit.

**Comment by ChristoWolf** [comment]
Hi @webreidi!

How do I view a coverage report?
Simply by opening it in VS Code?

And which report formats are supported?
I just quickly tried it with Visual Studio's `.coveragexml`, but that doesn't seem to work, as the file is only opened as an XML file.

**Comment by webreidi** [comment]
If you use the ":NET: Open Coverage Report" command from the command palette, you can open a previously generated coverage report (dotnet test --collect "Code Coverage"). The tool is planned to accept coverage, cobertura, and xml formats, but is currently only accepting coverage reports at this time.  We are also working on generating the coverage reports when you run tests in C# Dev Kit, but that feature has not finished yet.

**Comment by ChristoWolf** [comment]
Thanks for clarifying @webreidi!

**Comment by raz789** [comment]
I've been using a task.json file to run "${command:csdevkit.openCoverageReport}".
Is it possible to pass in a directory rather than use the quick pick menu?

I suppose this won't be an issue when the run tests and generate the coverage report is done.

**Comment by webreidi** [comment]
This is now available in v1.10.16

**Comment by ChristoWolf** [comment]
Hi @webreidi!

That's great news!

Unfortunately, when I install v1.10.16 of the C# Dev Kit, it neither shows this addition in the changelog nor is the coverage shown in the Test Coverage hierarchy.
What am I missing here?

**Comment by ChristoWolf** [comment]
Thanks for the quick feedback @webreidi!

Yes, the option shows and executing it leads to the following:
- The C# Dev Kit - Code Coverage output reads:
  ```
  Created Coverage Controller
  CodeCoverage: Report generated: <redacted>
  ```
- The C# Dev Kit - Test Explorer output reads:
  ```
  Using custom runsettings file at: <redacted>
  ========== Starting test run ==========
  MSTest Executor: Test Parallelization enabled for 
  <redacted> (Workers: 24, Scope: MethodLevel).
  ========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 150.4 ms ==========
  ```
- So nothing unusual so far I'd say.
- However, only 0% are shown for all covered files:
  <img width="51" alt="image" src="https://github.com/user-attachments/assets/44e014bf-39f5-443e-8400-34cf7a4312b5">

Could it have something to do with the coverage collector that I am using (`<PackageVersion Include="coverlet.collector" Version="6.0.0" />`)?

**Comment by webreidi** [comment]
@fhnaseer can you look at the above? Could the collector being used cause it to not accurately present the covered files?

**Comment by jgangel** [comment]
Thank you for this feature @webreidi! Does this support branch and function coverage or statement coverage only? If branch and function coverage are supported, how do I set them up? I have tried using execution from Test Explorer and with the `.NET: Open Coverage Report...` option using a cobertura file that holds this extra information of coverage

**Comment by fhnaseer** [comment]
@jgangel Right now we support only statement level coverage. Branch coverage is also supported but only for .coverage files.
