### ISSUE TITLE
Newly added Nuget support does not work if .NET 9.0 sdk is installed or project created with .NET 9.0

### ISSUE THREAD

**Issue by TanvirArjel** [microsoft/vscode-dotnettools#1036]
### Describe the Issue

Adding, updating, and removing Nuget packages do not work if .NET 9.0 SDK is installed in the machine or project created with .NET 9.0.

### Steps To Reproduce

1. Install .NET 9.0 latest sdk
2. Create a project with .NET 9.0
3. Try to add a nuget package
4. It will show "Package not found."

### Expected Behavior

It should work as it is working without .NET 9.0 installed.

### Environment Information

OS: MacOS - 14.4.1
VsCode Version: 1.87.2
Extension Version: v1.5.8 (pre-release)

**Comment by TanvirArjel** [comment]
@jebriede Last time I tried with `SDK 9.0.100-preview.2` Not sure whether it still persists with `SDK 9.0.100-preview.3`

**Comment by jebriede** [comment]
Thanks @TanvirArjel! I suspect I may know why this is happening, but to be sure, can you please let me know what you are seeing in the Output Pane under the NuGet output channel? Please be sure to redact and remove any personal information (if there is any) before providing it here. What I'm looking for is what general error message may be logged to the Output pane. Thanks!

**Comment by TanvirArjel** [comment]
I see the issue has been fixed in the latest version of the extension.
