### ISSUE TITLE
[SUGGESTION] Solution-wide analysis

### ISSUE THREAD

**Issue by segln** [microsoft/vscode-dotnettools#104]
### Describe the feature you'd like

Currently C# Dev Kit reports errors/warnings about opened files.
Can it automatically report solution-wide errors/warnings?

**Comment by ivanjx** [comment]
for now you can try to build the projects from the solution explorer and it will show the errors

**Comment by arkalyanms** [comment]
Moved to Roslyn - https://github.com/dotnet/roslyn/issues/68553
