### ISSUE TITLE
Picking up error resolution is really slow

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1040]
Type: <b>Performance Issue</b>

Often, it takes a really long time (30 seconds to a minute) for errors to go away in the editors or in the 'Problems' tab.  Simple things, for example, an interface method isn't implemented because I changed the method.  Change the interface and the error stays there for quite a bit.  Even if I do a build.

Also, when I break something.  Like say changing an interface, I often have to do a build for the errors to show up.  Even then, I have to expand the directory where the broken file is to get it to turn red.

I really don't think my computer is the issue.  I'm running an M3 Max with 96 GB.

Not exactly the same issue, I don't think, but I also often have to actually run the application to find errors.  Doing a build doesn't turn anything up, but I get a build failure when I actually try to run it.

Extension version: 1.4.29
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|16, 7, 6|
|Memory (System)|96.00GB (1.27GB free)|
|Process Argv|--crash-reporter-id 1618046c-b005-4c1a-89ae-cb627902572c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   57	   295	 93954	code main
    2	    98	 93957	   gpu-process
    0	     0	 93958	   utility-network-service
    0	   688	 93959	window [1] (UserSubscriptionResult.cs — D8.API)
    0	   295	 93960	window [2] (launchSettings.json — E-Comm)
    0	    98	 93971	ptyHost
    0	     0	 68463	     /bin/zsh -il
    0	     0	 71993	     /bin/zsh -il
    0	     0	 73999	     /bin/zsh -il
    0	     0	 85808	     /bin/zsh -il
    0	     0	 85809	     /usr/local/bin/pwsh -noexit -command . "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1"
    0	    98	 93975	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ItemAttributeDropdowns.razor.cs — Ecommerce)
|  Window (UserSubscriptionMapper.cs — D8.Apps)
|  Window (launchSettings.json — E-Comm)
|  Window (UserSubscriptionResult.cs — D8.API)
|    Folder (Ecommerce): 2658 files
|      File types: cs(1024) dll(603) css(148) scss(92) razor(91) json(47)
|                  cache(28) pdb(14) props(11) so(9)
|      Conf files: csproj(5) launch.json(1) tasks.json(1) package.json(1)
|                  sln(1)
|      Launch Configs: coreclr(2)
|    Folder (D8.Apps): more than 20031 files
|      File types: xml(3671) dll(3221) png(2091) cs(953) class(762) java(637)
|                  txt(479) cache(323) arm64(266) stamp(248)
|      Conf files: csproj(5) launch.json(2) sln(1)
|      Launch Configs: maui
|    Folder (E-Comm): 2726 files
|      File types: gz(787) cs(663) dll(643) css(105) razor(66) json(42)
|                  cache(25) pdb(17) js(11) props(11)
|      Conf files: csproj(4) sln(1)
|    Folder (D8.API): 2152 files
|      File types: cs(1022) dll(177) sql(157) json(61) cache(55) log(31)
|                  DS_Store(27) pdb(24) editorconfig(13) props(10)
|      Conf files: csproj(6) launch.json(1) tasks.json(1) sln(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonaic:30996667
7ghi1836:30988842
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by mmiller-d8** [comment]
It's more than just slow, it's broken, particularly for Maui apps.  

- Doing a build doesn't show you all of your errors.  You have to actually run the app.
- Running the app gives you _some_ of your errors.  If you make a breaking change, sometimes you have to run the app five, six, seven times just to get all of the errors.  Fix some, run it.  Fix some, run it.
- Fixing the errors _sometimes_ clears them out of your problem list.  Most times, it doesn't.  You have to re-run the app to see if you actually fixed it.
- Sometimes, even after fixing an error and re-running the app, the file still shows up as red in Solution Explorer.  And don't get me started on Solution Explorer.
- And then, once or twice a day, it stops showing my connected simulators so I can't even re-run the app to do a build.  I have to reboot my machine to get them to show up again.  That, or the VS Code UI starts freaking out with a stream of popups in the lower right corner saying everything has broken and then nothing works.
- Oh... and not related, but the debugger is horrible.  More times than not, it just disconnects from the debugger on a step-over.  I know you have the c# debugger in the works, but I would be surprised if that fixes this.

I really, really don't see how you guys are retiring VS for Mac in August.  I mean, VS for Mac is extremely buggy.  I see why you're killing it.  But the Maui extension is not even close to ready for prime time.  It's not even ready for preview.  No offense, but it feels like an Alpha release.  Funny that I was asked for feedback (from VS) before I had really used it much, and now I can't do the survey again.

Sorry.  End rant....

**Comment by kvenkatrajan** [comment]
Also, when I break something. Like say changing an interface, -> roslyn - FYI @arkalyanms 
MAUI apps build -> FYI - @mauroa

**Comment by arkalyanms** [comment]
For the error resolution issue in particular, this is tracked at https://github.com/dotnet/roslyn/issues/72811. So removing the area-roslyn label to tag the maui aspect.

**Comment by mauroa** [comment]
We've made lots of changes on the MAUI side that are being released soon, that should cover your mentioned issues (debugger, build errors, etc.).
We'll give you more instructions once the fixes are released in the corresponding extensions, since it includes more than only MAUI (also C# and C# DevKit).

Thanks for your feedback and patience.

**Comment by mauroa** [comment]
This issue has been fixed on latest .NET MAUI release version. Please ensure to also update C# and C# DevKit to latest pre-release versions as well. Thanks
