### ISSUE TITLE
Need a way to select platform in multi-architecture solution

### ISSUE THREAD

**Issue by jcoliz** [microsoft/vscode-dotnettools#1045]
Type: <b>Bug</b>

Given: A solution which targets x64 and ARM64 (e.g. https://github.com/jcoliz/Sample.Web.MultiArch.git
And: Running on an ARM64 machine
And: Having the solution open in VS Code, running C# dev kit
When: Right-click on solution in solution explorer, and choose build
Then: Solution builds as x64

This is wrong. We need a way to build the solution as ARM64.

If we're running in Visual Studio, we can use configuration manager to set this.
If we're running on command line, we can use `dotnet build -p:Platform=ARM64` and this will work.

Extension version: 1.4.29
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:30.612Z)
OS version: Windows_NT arm64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon Compute Platform (8 x 1440)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.41GB (20.88GB free)|
|Process Argv|. --crash-reporter-id 289141a4-38a3-496e-8316-aba44631e156|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571

```

</details>

**Comment by kvenkatrajan** [comment]
@Michael-Eng - similar to the build configuration request.

**Comment by lifengl** [comment]
configurations/platforms can now be selected, use the status bar item to make a choice.
