### ISSUE TITLE
Console/Debug output with useVSDbg=true

### ISSUE THREAD

**Issue by yaliashkevich** [microsoft/vscode-dotnettools#1064]
I've noticed following behaviour with useVSDbg=true flag while working on dotnet-ios/android app:

- Application output written by`Console.WriteLine` gets into **Terminal** window (same as build output).
- Application output written by `Debug.WriteLine` gets nowhere, atleast I can not find it.

Is it intended behavior?
Previously with useVSDbg=false all output above were shown at **DEBUG CONSOLE** window which has convenient controls to clear/filter.

**Comment by mauroa** [comment]
This is a duplicate of: https://github.com/microsoft/vscode-dotnettools/issues/685. Closing this, so please follow the status on the other ticket. Thanks
