### ISSUE TITLE
[BUG] MAUI does NOT WORK (BUILD or RUN) in Visual Studio Code (Both Mac and Windows)

### ISSUE THREAD

**Issue by alibad** [microsoft/vscode-dotnettools#1065]
### Describe the Issue

It's been a while since I worked on the Microsoft Stack. I discovered MAUI and thought this is pretty interesting work to see. The path looked very welcoming for Mac and Visual Studio Code users.

I went ahead and installed it, and good luck....

Several hours later, both on a Mac and a Windows device, I can't get it to build and run without issues.. As a last resort, I installed Visual Studio 2022 on Windows. Everything worked like a charm...

Rolling developer experiences like this IS NOT OK!! I value my time and I don't think it should have been wasted that way., because I did not learn anything useful on this lost time. I wonder how many other people faced the same issues.

**Comment by mauroa** [comment]
Hi @alibad. Thanks for your feedback. 
We would like to help you troubleshooting your issues and detecting if there's any bug in the .NET MAUI extension, however it's not clear what's the real issue you are having.

Without repro steps and extra information, it's hard for us to help you accordingly.

Just for verification, do you have C#, C# DevKit and .NET MAUI installed in VS Code? If so, could you share the content of the C#, C# DevKit and .NET MAUI output panes?

Finally, how are you building your projects/solution? Right now, .NET MAUI doesn't support right click > build, so you can either do F5 (after selecting the startup project and debug target from the '{}' at the bottom right of VS Code), or you can select a "build only" target from '{}', and then do F5. That will just build your project and not launch/debug it.

Thake into account that for showing '{}', VS Code needs you to open a code file like .cs, .xaml, etc.

We are working on adding support for right click > build, together with other features and improvements, so we'll keep you posted on them.

Please let me know how that goes.
Thanks for your help.
