### ISSUE TITLE
ms-dotnettools.csdevkit and escape-node-job.exe

### ISSUE THREAD

**Issue by minoseah629** [microsoft/vscode-dotnettools#1068]
Hello,
I was going through my task manager and I saw this oddly named process escape-node-job.exe and got me concerned to look if there was some kind of malicious activity on my machine. Then i located the file specifically and saw it lived in ms-dotnettools.csdevkit vs code extension. 

Please provide the purpose of this executable.

**Comment by AArnott** [comment]
Node.js spawns child processes within a [Windows "job"](https://learn.microsoft.com/en-us/windows/win32/procthread/job-objects) that has a flag that prevents Watson Error Reporting from collecting telemetry when processes crash. The `escape-node-job.exe` process is a stub process we use to 'escape' that Windows job and spawn a child process that doesn't have that flag so we can better find and fix bugs in the VS Code extension.
