### ISSUE TITLE
[BUG] Cannot Run Debug on Ubuntu 22.04

### ISSUE THREAD

**Issue by aprilesalvatore** [microsoft/vscode-dotnettools#1073]
### Describe the Issue

I installed dotnet 8 sdk and vscode with c# Dev Kit on Ubuntu 22.04. The project compile and run correctly but the debug cannot attach because it not found a .net Runtime.

attached img:

![image](https://github.com/microsoft/vscode-dotnettools/assets/13586739/813b73b0-263d-47a2-9339-14a6c7ae65a6)

**Comment by aprilesalvatore** [comment]
this is my dotnet config

![image](https://github.com/microsoft/vscode-dotnettools/assets/13586739/e128e1ec-2116-47db-80fc-5064ef85cae5)

and the output console:

![image](https://github.com/microsoft/vscode-dotnettools/assets/13586739/ea220bf2-3153-46ac-aec7-2e33734a1232)

**Comment by WardenGnaw** [comment]
Could you share how you are starting the debug session? Are you right clicking the solution explorer and using Debug -> Start Debugging? Are you using F5 and using the C# Debugger?

**Comment by aprilesalvatore** [comment]
In both way. At the end i formatted my pc and reinstall ubunto. The debug
run successfully. Probably there are some softwares that s conflicted with
it

Aprile Salvatore
*Cloud Azure Solution Architect *
*Microsoft Certified: Azure Solutions Architect Expert*
*Microsoft Certified: Azure Security Engineer Associate*

*Microsoft Certified: Azure Iot Developer Specialty*
*Microsoft Certified: Azure AI Engineer Associate*
*Microsoft Certified: Azure AI Fundamentals*
*Microsoft Certified: Azure Data Fundamentals*
*MCPD .Net Framework 4.0 Azure*
*MCPD .Net Framework 4.0 Web Application*
*MCTS .Net Framework 4.0 Web Application*
*MCTS .Net Framework 4.0 Data Access*
*MCTS .Net Framework 4.0 WCF*
Linkedin: http://it.linkedin.com/pub/salvatore-aprile/b/98/b
Twitter: @SalvoAprile
Cell: +39 3335852949





Il giorno ven 19 apr 2024 alle 23:52 Andrew Wang ***@***.***>
ha scritto:

**Comment by WardenGnaw** [comment]
Closing the issue as it seems you have resolved the issue. Feel free to re-open if you encounter this again.
