### ISSUE TITLE
Doesn't run with VSCODE_EXTENSIONS

### ISSUE THREAD

**Issue by Magendanz** [microsoft/vscode-dotnettools#1078]
Type: <b>Bug</b>

If VSCODE_EXTENSIONS environment variable is set to allow system-wide extensions, we always receive "Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server." on launch.

Extension version: 1.4.29
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.70GB (13.56GB free)|
|Process Argv|--crash-reporter-id 6f2f0439-175e-4d05-af55-692b6ad61a6c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
945dj816:31013170
pythoncenvptcf:31022791

```

</details>

**Comment by Magendanz** [comment]
Problem seems to be with creating directories without admin access:

```
Installing Razor Telemetry Version = 7.0.0-preview.24168.4...
Platform: win32, x86_64

Failed at stage: touchBeginFile
Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Microsoft VS Code\extensions\ms-dotnettools.csharp-2.23.15-win32-x64\.razortelemetry'

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
[ERROR] Failed to activate 'ms-dotnettools.csdevkit'
[Error - 12:31:30 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: EPERM: operation not permitted, mkdir 'c:\Program Files\Microsoft VS Code\extensions\ms-dotnettools.csdevkit-1.4.29-win32-x64\cache'
```

**Comment by dibarbet** [comment]
> [Error - 12:31:30 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: EPERM: operation not permitted, mkdir 'c:\Program Files\Microsoft VS Code\extensions\ms-dotnettools.csdevkit-1.4.29-win32-x64\cache'

Looks like Roslyn is failing to start because the C# devkit extension is failing to activate.  Removing the Roslyn label here - should be tracked under extension management.

**Comment by ryzngard** [comment]
I'm going to close this as a dupe against dotnet/razor#10262 . Thank you for filing!
