### ISSUE TITLE
[BUG] Xaml intellisence not working using MAUI

### ISSUE THREAD

**Issue by charleypeng** [microsoft/vscode-dotnettools#1082]
### Describe the Issue

os: macos 14.4 m1 pro
platform: dotnet8.0.204/ vscode 1.88.1 / maui  v0.10.61/ c# dev kit v1.4.29

xaml intellisense not working at all. 

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2049886">2049886</a>

**Comment by emaf** [comment]
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/565
