### ISSUE TITLE
May Iteration Plan

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#1085]
Below is the list of items being worked on during May 2024 sprint. Not all items listed below will finish and release in May.

- https://github.com/microsoft/vscode-dotnettools/issues/1089
- https://github.com/microsoft/vscode-dotnettools/issues/1078
- https://github.com/microsoft/vscode-dotnettools/issues/1076
- https://github.com/microsoft/vscode-dotnettools/issues/1055
- https://github.com/microsoft/vscode-dotnettools/issues/1050
- https://github.com/microsoft/vscode-dotnettools/issues/1046
- https://github.com/microsoft/vscode-dotnettools/issues/1011
- https://github.com/microsoft/vscode-dotnettools/issues/967
- https://github.com/microsoft/vscode-dotnettools/issues/928
- https://github.com/microsoft/vscode-dotnettools/issues/884
- https://github.com/microsoft/vscode-dotnettools/issues/836
- https://github.com/microsoft/vscode-dotnettools/issues/828
- https://github.com/microsoft/vscode-dotnettools/issues/767
- https://github.com/microsoft/vscode-dotnettools/issues/716
- https://github.com/microsoft/vscode-dotnettools/issues/714
- https://github.com/microsoft/vscode-dotnettools/issues/695
- https://github.com/microsoft/vscode-dotnettools/issues/684
- https://github.com/microsoft/vscode-dotnettools/issues/682
- https://github.com/microsoft/vscode-dotnettools/issues/674
- https://github.com/microsoft/vscode-dotnettools/issues/666
- https://github.com/microsoft/vscode-dotnettools/issues/611
- https://github.com/microsoft/vscode-dotnettools/issues/550
- https://github.com/microsoft/vscode-dotnettools/issues/544
- https://github.com/microsoft/vscode-dotnettools/issues/542
- https://github.com/microsoft/vscode-dotnettools/issues/540
- https://github.com/microsoft/vscode-dotnettools/issues/500
- https://github.com/microsoft/vscode-dotnettools/issues/473
- https://github.com/microsoft/vscode-dotnettools/issues/425
- https://github.com/microsoft/vscode-dotnettools/issues/404
- https://github.com/microsoft/vscode-dotnettools/issues/132
- https://github.com/microsoft/vscode-dotnettools/issues/128
- https://github.com/microsoft/vscode-dotnettools/issues/105
- https://github.com/microsoft/vscode-dotnettools/issues/83

See also, [C# extension April 2024 Iteration Plan](https://github.com/dotnet/vscode-csharp/milestone/44)

**Comment by MateuszLas421** [comment]
What progress has been made on synchronizing Storyboards and xib files? Especially considering the lack of support for .NET 8 in VS for Mac and its planned discontinuation on August 31, 2024?  https://github.com/microsoft/vscode-dotnettools/issues/571
