### ISSUE TITLE
Cannot use the extension to create a project or to open the current one

### ISSUE THREAD

**Issue by dimysa** [microsoft/vscode-dotnettools#1092]
Type: <b>Bug</b>

Install the extension
Open a project
Expected behavior : the project will open without errors
Current behavior: `Failed at 'command: "dotnet" restore /Users/dkravchuk/Desktop/console/console.sln --interactive' (1ms) with error: Error: spawn ELOOP`

Full C# Dev Kit Output log:
```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/usr/local/share/dotnet/dotnet"
.NET server started and IPC established in 1630ms
Completed Spawn .NET server (2653ms)
Completed Clear environment (2851ms)
Completed Open a solution with environment service (2873ms)
Starting Restore solution...
Completed Open a solution (2884ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /Users/dkravchuk/Desktop/console/console.sln --interactive...
Failed at 'command: "dotnet" restore /Users/dkravchuk/Desktop/console/console.sln --interactive' (1ms) with error: Error: spawn ELOOP
Completed NuGet restore with error: DotnetCommandRestoreError: spawn ELOOP
Completed Restore solution (2ms)
```
I tried using both .NET Tool Installer and local path to .NET, the result is the same.

Extension version: 1.4.29
VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|23, 11, 4|
|Memory (System)|16.00GB (2.66GB free)|
|Process Argv|. --crash-reporter-id 691b5fa6-70d8-47e0-96ac-b4747cb07779|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by tmeschter** [comment]
@dimysa Can you open the terminal in VS Code, run `dotnet --info`, and paste the output here?

**Comment by tmeschter** [comment]
Also, do you get the exact same error when trying to create a new project, or is it different? E.g. does it fail on the `dotnet new` or the `dotnet restore` like above?

**Comment by dimysa** [comment]
Everything works fine through the terminal

```
dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.1f2e3bea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.204/

.NET workloads installed:
 [maui-ios]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.200
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8053/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net6]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.4/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.net6/8.0.4/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.4
  Architecture: arm64
  Commit:       2d7eea2529

.NET SDKs installed:
  6.0.421 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.29 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
```

**Comment by dimysa** [comment]
If I try to create a new project through VS Code, I get the same error.

<img width="389" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/14176511/8517b105-4fd6-4e3f-89f0-f1c88cca5b9d">

**Comment by Guy--L** [comment]
I encounter the same problem.

`.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.204/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: arm64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.203 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
`
Here's the c# dev kit console output

`
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/Users/guy/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.4~arm64/dotnet"
.NET server started and IPC established in 524ms
Completed Spawn .NET server (1135ms)
Completed Clear environment (1261ms)
Completed Open a solution with environment service (1317ms)
Starting Restore solution...
Completed Open a solution (1324ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /Users/guy/dev/Solution.sln --interactive...
Failed at 'command: "dotnet" restore /Users/guy/dev/Solution.sln --interactive' (1ms) with error: Error: spawn ELOOP
Completed NuGet restore with error: DotnetCommandRestoreError: spawn ELOOP
Completed Restore solution (2ms)
`

**Comment by lifengl** [comment]
can you try to execute the command in a zsh window to see whether it works?
dotnet restore /Users/guy/dev/Solution.sln --interactive

spawn ELOOP usually means there is one or more symbol links in the system to form a loop. not sure what it is.

**Comment by Guy--L** [comment]
I've looked for symlinks in the file system.  

Using your command:

**Comment by dimysa** [comment]
Looks like it was about the wrong symlink. After removing it, everything worked
I guess we can close the issue.

**Comment by dimysa** [comment]
I don't know, but I don't have a problem anymore.
I had a symbolic link for `dotnet` in the `/usr/local/bin` folder, but it seems to be broken. I just deleted it and everything worked after that

**Comment by Guy--L** [comment]
Yes.  Close this.  I followed your solution and it worked also.
