### ISSUE TITLE
[BUG] GTD and GTI not available during solution load

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#1097]
### Describe the Issue

We are receiving many reports that Go to Definition and Go to Implementation are not working and it seems that it is a matter of the fact that these features are not available during solution load. You cannot successfully navigate until the projects have completely loaded and you see a number of projects loaded: 
![image](https://github.com/microsoft/vscode-dotnettools/assets/55603905/e0acd9f5-bc23-40b7-88b1-dc2d8fdd9338)

Can we speed up solution load to make this less of an issue?
Can we make awareness better that the Project load indicator is important to having LSP features fully working?

Verbatims from surveys:
I think it is missing caching, loading whole project takes a lot of time and sometimes it doesn't succeed. Stuff like go to definition doesn't work at this point.

**Comment by dibarbet** [comment]
> Can we speed up solution load to make this less of an issue?
Can we make awareness better that the Project load indicator is important to having LSP features fully working?

From the C# extension perspective, the main possible things we could do here is have some indication that the file is not loaded, possibly a project context display as in https://github.com/dotnet/vscode-csharp/issues/5788 ?  I'm not sure exactly what this indicator would look like.

For speeding up project load, this likely needs to be driven by the project side.  Possibly a feature like O#'s load projects on demand would help, see https://github.com/dotnet/vscode-csharp/issues/6008 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2005174 (internal)

**Comment by webreidi** [comment]
Status bar changes for awareness are now live
