### ISSUE TITLE
[BUG] IntelliSense doesn't work well with folders with multiple .sln files

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#1098]
### Describe the Issue

Report from survey verbatims is that IntelliSense doesn't work well with folders with multiple .sln files. They get an inconsistent experience. Is there a way to make it more clear which .sln file has been loaded in the Solution Explorer? Or is the customer not aware of the Solution Explorer to see which solution has loaded?

**Comment by arkalyanms** [comment]
@webreidi any thoughts on an experience tweak that can help in showing the user which solution file has been picked up and what to expect?

cc: @Michael-Eng / @lifengl
