### ISSUE TITLE
Tracking devkit releases

### ISSUE THREAD

**Issue by webczat** [microsoft/vscode-dotnettools#110]
I have the following question: where can I track devkit extension releases?
I mean, extensions will auto-upgrade, however they don't open release notes. I would like to know when new extension versions are released and what changed, to be able to track progress. Is there anything like that?

**Comment by webreidi** [comment]
We are publishing a Changelog with every release of C# Dev Kit. You can find it on Extension description page on the CHANGELOG tab.
