### ISSUE TITLE
[BUG] Unity analyzers

### ISSUE THREAD

**Issue by marcospgp** [microsoft/vscode-dotnettools#1101]
Is there a plan to support https://github.com/microsoft/Microsoft.Unity.Analyzers?

note this repo was linked to from this page: https://marketplace.visualstudio.com/items?itemName=VisualStudioToolsForUnity.vstuc

**Comment by jbevain** [comment]
Hi @marcospgp,

The Unity extension for Visual Studio Code ships with the Unity analyzers in the box, so yes, that's supported.
