### ISSUE TITLE
SDK cannot be located error

### ISSUE THREAD

**Issue by Duplo-nikv** [microsoft/vscode-dotnettools#1109]
### Describe the Issue

After installation of SDK through vs code and reloading vscode. Following error is thrown The .NET Core SDK cannot be located: Error running dotnet --info: Error: Command failed: dotnet --info /bin/sh: dotnet: command not found /bin/sh: dotnet: command not found . .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

**Comment by timheuer** [comment]
@Duplo-nikv can you restart VSCode and see if found?

**Comment by baronfel** [comment]
In addition, any information you could give about your OS and architecture would be helpful. If you can also provide the results of `dotnet --info` in your VSCode Terminal that would be great.

**Comment by Duplo-nikv** [comment]
dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.204/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: arm64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by nagilson** [comment]
Is that installation of .NET on your PATH environment variable? I'm curious how you installed it, if not. If you are able to use the SDK installer on the walkthrough, this will configure the PATH for you when it does an install.

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
