### ISSUE TITLE
[BUG] `override` auto completion no longer works

### ISSUE THREAD

**Issue by ivanjx** [microsoft/vscode-dotnettools#111]
### Describe the Issue

i cant auto complete `override` anymore. i believe it is because the vscode is updated a few days ago.

### Steps To Reproduce

https://github.com/microsoft/vscode-dotnettools/assets/12814796/46af6372-b575-413c-b183-8c23b57a49c1

### Expected Behavior

able to auto complete the `override` methods

### Environment Information

- OS: Ubuntu 23.04
- VSCode: 1.79.0
- Extension: v2.0.206

**Comment by arkalyanms** [comment]
Dup of https://github.com/dotnet/vscode-csharp/issues/6011. @genlu note evidence of this being a regression from the vscode update.
