### ISSUE TITLE
Extension doesn´t work on Ubuntu

### ISSUE THREAD

**Issue by jagp2097** [microsoft/vscode-dotnettools#1114]
Type: <b>Bug</b>

When I start VS Code just the extention can´t start.

I am running VS Code on Ubuntu 22.04.4 LTS.

This is the error output:

Using dotnet configured on PATH
Dotnet path: /snap/dotnet-sdk/241/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stderr] Failed to load /snap/dotnet-sdk/241/shared/Microsoft.NETCore.App/8.0.4/libcoreclr.so, error: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/core20/current/lib/x86_64-linux-gnu/librt.so.1)
Language server process exited with null
[Error - 4:16:31 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Client cound not connect to server via named pipe
	at z.<anonymous> (/home/d/.vscode/extensions/ms-dotnettools.csharp-2.28.11-linux-x64/dist/extension.js:2:1293822)
	at Generator.next (<anonymous>)
	at s (/home/d/.vscode/extensions/ms-dotnettools.csharp-2.28.11-linux-x64/dist/extension.js:2:1283111)

Extension version: 1.5.20
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.5.0-28-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics (4 x 2179)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|6.67GB (3.58GB free)|
|Process Argv|--crash-reporter-id 0b81b738-934b-402d-b8e5-fca6e849d9de|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31043157
dwnewjupyter:31039675

```

</details>

**Comment by arkalyanms** [comment]
@jagp2097 would you try uninstalling the Intellicode extension if it solves the problem?

**Comment by jagp2097** [comment]
I already tried that but it didn't work. I also tried use the pre release version of the extension and it's the same, the extension don't work well.

**Comment by jagp2097** [comment]
I already tried that but it didn't work. I also tried to use the extension in its pre release version but it's the same, the extension don't work well.

**Comment by jagp2097** [comment]
I already tried that but it didn't work. I also tried to use the extension in its pre release version but it's the same, the extension don't work well.

**Comment by sandersn** [comment]
Very likely related to https://github.com/dotnet/sdk/issues/40272

**Comment by nagilson** [comment]
Is there a reason you need to use the snap installs? We have an automated install button that should install and configure the SDK for you on Ubuntu in the walkthrough page, and this installs through a different method which is preferred over the snap installs.

**Comment by arkalyanms** [comment]
Related to snap installs and tracked at https://github.com/dotnet/sdk/issues/40272

**Comment by Avinash-Vadlamudi** [comment]
Finally, I made VS Code work with the .Net in **Ubuntu 24.10** by following below instructions 

First uninstall  snap version using `sudo snap remove dotnet-sdk` and then follow info in this link - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.403-linux-x64-binaries .. don't forget to add dotnet to your system path ie.,

```
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-8.0.403-linux-x64.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

**Comment by anasmostafa23** [comment]
> Finally, I made VS Code work with the .Net in **Ubuntu 24.10** by following below instructions
> 
> First uninstall snap version using `sudo snap remove dotnet-sdk` and then follow info in this link - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.403-linux-x64-binaries .. don't forget to add dotnet to your system path ie.,
> 
> ```
> mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-8.0.403-linux-x64.tar.gz -C $HOME/dotnet
> export DOTNET_ROOT=$HOME/dotnet
> export PATH=$PATH:$HOME/dotnet
> ```
> 
> Here's the Output of the Terminal in VS Code
> 
> ![Image](https://github.com/user-attachments/assets/80fa5c54-9f98-422b-a74c-62c5b4b77344)

thank you so much that's exactly what I needed , it works!

**Comment by Avinash-Vadlamudi** [comment]
@anasmostafa23 glad to know it helped you to resolve the issue :)

Cheers,
Avi
