### ISSUE TITLE
[SUGGESTION] 'Implement interface' quick fix generates the code with NotImplementedException

### ISSUE THREAD

**Issue by nicholasyin** [microsoft/vscode-dotnettools#1116]
### Describe the feature you'd like

When using the 'Implement interface' quick fix on a missing interface property, the generated code declares the property with both getter and setter throwing NotImplementedException.

### Alternatives considered

 In most cases, it'd be more common to declare the property simply with `{get;set;}`.

**Comment by dibarbet** [comment]
tracking on C# ext side - https://github.com/dotnet/vscode-csharp/issues/7640
