### ISSUE TITLE
[BUG] Track Active Item feature should be disabled when not in Explorer Panel

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#1117]
### Describe the Issue

When looking through your changes in the "Source Control" tab, the track active item feature switches back to the Solution Explorer each time you select an item. Very annoying when you quickly want to look through all git changes

**Comment by leksts** [comment]
Also when working in Zen Mode, the Side Bar pops up on 'Go to definition' (F12).

It would be great if `dotnet.automaticallySyncWithActiveItem` works like the regular workspace file tree. Select the appropriate file, but do not set focus to it.

**Comment by Jxwoon** [comment]
A fix has been made in 1.9.53 - Prerelease. Please try it out and let us know of any feedback!

**Comment by CasperBr** [comment]
works like a charm! I can now quickly view my git changes without it switching to another tab.
