### ISSUE TITLE
.net not geting install in vscode

### ISSUE THREAD

**Issue by Zen980** [microsoft/vscode-dotnettools#1118]
### Describe the Issue

.net SDK file is frequently showing Error
Failed to download .NET 8.0.204-global:
.NET Acquisition Failed: undefined what should I do

**Comment by baronfel** [comment]
Any information you could give about your OS and architecture would be helpful. If you can also provide the results of `dotnet --info` in your VSCode Terminal that would be great.

**Comment by nagilson** [comment]
Please attach log file(s) here if you have any.

Our log files are located alongside VS Code logs. If you want to find them manually, navigate here:
Linux: ~/.config/Code/logs
Mac: ~/Library/Application Support/Code/logs/
Windows: c:\Users\USER\AppData\Roaming\Code\logs\

Then find the folder created at the time you experienced the bug in the logs folder.
From there, go to window1 -> exthost -> ms-dotnettools.vscode-dotnet-runtime. The log file should be located in this folder.

Note: The window folder may change depending on how many VS Code windows you have open; if our extension is running in the 2nd window, it'd be in a folder called window2.

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
