### ISSUE TITLE
[SUGGESTION] Split it up

### ISSUE THREAD

**Issue by Ghostbird** [microsoft/vscode-dotnettools#112]
### Describe the feature you'd like

I think it's great that Microsoft is making this functionality, I'm sure you've evaluated this internally, and I'm aware that this is still a preview. However as a user, I'd like to tell you that I'd strongly prefer if the different features of the dev kit were implemented as separate extensions. VSCode has great support for extension packs, so the people who want the full package can still easily install it.

Personally I've always hated the Solution View in Visual Studio, and I don't want to see it in VSCode. I thought one of the great advantages VSCode was that it gives you an unadulterated file-system view, that you can customise if necessary on a workspace-settings level. I understand the advantages of a high-level abstraction over the workspace files, and of course direct access to the file-system is an absolute must. But the Solution View of Visual Studio to me is a hybrid that has all the disadvantages of both, and is rather arbitrary in which things it abstracts and which not.

A good test UI for VSCode is one of the things currently sorely lacking, and now I install the Dev Kit basically for this specific feature alone. If I could install that as a separate extension, I'd much prefer that.

I was pleased that this is already done for the Intellicode C# Dev Kit. I immediately uninstalled it. If someone advertises something with the word "AI", I'll be _much_ less likely to install it, and will investigate closely before deciding on whether to use it. The fact that it clearly states that the model for IntelliCode runs entirely locally makes me much happier about this already. I may reinstall it at some point.

In summary, thanks for investing in Visual Studio Code, but please don't make it Visual Studio. One of the best things of VSCode in my opinion is that it threw out the convoluted monolithic and largely unnecessary (G)UI of Visual Studio.

### Alternatives considered

The alternative is worst case that VSCode becomes a new Visual Studio. Visual Studio can do everything you want it to do, but it can also do a lot of stuff you don't want, or that you use so rarely, that it mainly is dead weight.

### Environment Information

This applies to all platforms, as it's about the modularity of the design. However my particular environment is:
Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.0-0.deb11.7-amd64

**Comment by timheuer** [comment]
Similar to #23 

Thanks for this note.  We are considering (and as you observed) what is separate and what is core. The SE view is a small view added to the core that you can hide as well, but this entry-point is one of the key aspects of the Dev Kit (not the base language) experience.

**Comment by Ghostbird** [comment]
Apologies, I missed #23. Thank you for you prompt reply. I'll close this in favour of #23.
