### ISSUE TITLE
.net sdk wont detect

### ISSUE THREAD

**Issue by plsworkvisualstidion** [microsoft/vscode-dotnettools#1121]
### Describe the Issue

I've installed the .net sdk about 3 times and it wont work.

### Steps To Reproduce

1. install .net sdk
2. wont detect

### Expected Behavior

it will detect and work

### Environment Information

 I am using mac 14.4.1 on visual studio code.

**Comment by nagilson** [comment]
@plsworkvisualstidion May you please put here the output of the PATH environment variable in your vscode terminal? Are you still facing this issue?
