### ISSUE TITLE
[BUG] Unable to create new project

### ISSUE THREAD

**Issue by c-sleanshot** [microsoft/vscode-dotnettools#1125]
### Describe the Issue

I'm unable to create an Android Java Library Binding project due to an error that VS Code throws when doing so:
`Error running command csdevkit.addNewProject: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'). This is likely caused by the extension that contributes csdevkit.addNewProject.`

### Steps To Reproduce

1. Create a new .NET MAUI App project using the quick start tutorial.
2. Try to create a new Android Java Library Binding project.

### Expected Behavior

An error shouldn't be thrown, and the project should be created.

### Environment Information

MacOS 14.2.1 (23C71)
VS Code Version: 1.89.1
C# Dev Kit v1.5.20

**Comment by smitpatel** [comment]
@c-sleanshot - I am not able to reproduce this on version 1.6.8. Can you try on latest version of all C# related extension and try again?

**Comment by c-sleanshot** [comment]
Hi @smitpatel, the issue seems to be resolved in the latest version. Thanks!
