### ISSUE TITLE
Solution explorer does not appear when existing folder with .sln is open

### ISSUE THREAD

**Issue by ibobak** [microsoft/vscode-dotnettools#1133]
Type: <b>Bug</b>

I have  a previously created and fully working solution (made in Jetbrains Rider) with several projects.  
Now I have VS code, I installed C# Dev Kit and I want to manage my solution with it.  
But solution explorer is not appearing:

![image](https://github.com/microsoft/vscode-dotnettools/assets/8807043/f8c33e16-cfcb-451e-911e-72b4370b67d8)
![image](https://github.com/microsoft/vscode-dotnettools/assets/8807043/bb6761d3-f085-4e34-99a3-ba4211763900)
![image](https://github.com/microsoft/vscode-dotnettools/assets/8807043/f56cef2f-647d-444e-9471-ef2d90f85164)
![image](https://github.com/microsoft/vscode-dotnettools/assets/8807043/de83aeff-dd7e-4faa-be72-dff90083bfa1)

Extension version: 1.5.20
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 4209)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|46.95GB (27.46GB free)|
|Process Argv|--crash-reporter-id d91c5c25-2c49-4af3-80cb-302636dde5af|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492cf:30256860
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvptcf:31049071
a69g1124:31046351
dvdeprecationcf:31052040
pythonprc:31047982
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by ibobak** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/8807043/e4881310-c024-473e-9b3d-64a552c42588)

**Comment by ibobak** [comment]
I closed my test solution, and then opened a folder - it opens it fine and solution appears. 

This is the contents of the newly created solution with a console project:
```
﻿
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ConsoleApp1", "ConsoleApp1\ConsoleApp1.csproj", "{A696C075-05FE-4389-93D2-2E6C551DB49B}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{A696C075-05FE-4389-93D2-2E6C551DB49B}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{A696C075-05FE-4389-93D2-2E6C551DB49B}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{A696C075-05FE-4389-93D2-2E6C551DB49B}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{A696C075-05FE-4389-93D2-2E6C551DB49B}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

And this is the contents of my previous solution file (made by Jetbrains Rider):
```
﻿
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "RMMLLib", "RMMLLib\RMMLLib.csproj", "{030804EB-13B4-42A1-9C2A-CF7EA0BC6FAD}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "IntegrationTesting", "IntegrationTesting\IntegrationTesting.csproj", "{B4967D61-B9C5-4668-9B30-4C11C7354FF7}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "RMMLCallerExample", "RMMLCallerExample\RMMLCallerExample.csproj", "{93D668C1-2632-48F3-A94C-DC4027F7FBE2}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{030804EB-13B4-42A1-9C2A-CF7EA0BC6FAD}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{030804EB-13B4-42A1-9C2A-CF7EA0BC6FAD}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{030804EB-13B4-42A1-9C2A-CF7EA0BC6FAD}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{030804EB-13B4-42A1-9C2A-CF7EA0BC6FAD}.Release|Any CPU.Build.0 = Release|Any CPU
		{B4967D61-B9C5-4668-9B30-4C11C7354FF7}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B4967D61-B9C5-4668-9B30-4C11C7354FF7}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B4967D61-B9C5-4668-9B30-4C11C7354FF7}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{B4967D61-B9C5-4668-9B30-4C11C7354FF7}.Release|Any CPU.Build.0 = Release|Any CPU
		{93D668C1-2632-48F3-A94C-DC4027F7FBE2}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{93D668C1-2632-48F3-A94C-DC4027F7FBE2}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{93D668C1-2632-48F3-A94C-DC4027F7FBE2}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{93D668C1-2632-48F3-A94C-DC4027F7FBE2}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

I see some differences. But the question is:  what might be wrong?

**Comment by ibobak** [comment]
If some additional info is needed from me - just let me know.  This bug is critical: I can't open my existing projects.

**Comment by nagilson** [comment]
cc @tmeschter for this issue

**Comment by mwkcoding** [comment]
I too am having this problem with a bigger solution originally created in Visual Studio a long time ago.

**Comment by richardstanton** [comment]
Looking at your solution file, it appears to be valid. I was able to make a copy and open it in C# DevKit. It doesn't have some of the optional property values like MinimumVisualStudioVersion, but that shouldn't prevent it from loading.
The solution explorer doesn't display if the workspace doesn't contain any .csproj files. Since the solution contains references to several .csproj files, it seems like that wouldn't be the case, but just confirming that the workspace does contain .csproj files?
C# DevKit may not open a solution if it finds multiple solution files, in which case it should prompt to pick one.

Can you manually open the solution using the command palette command: ".NET: Open Solution"?
If so, making a simple change to the solution like adding and removing a solution folder would resave the solution file.

**Comment by ibobak** [comment]
it works for me now, no matter how I open it:  using "open a folder containing .net solution"  or using ".NET: Open Solution".
