### ISSUE TITLE
[HATA] <başlık> Failed to create CoreCLR, HRESULT: 0x8007000C

### ISSUE THREAD

**Issue by areezganiyev** [microsoft/vscode-dotnettools#1134]
### Describe the Issue

I installed .net SDK and runtimes on my Macbook Air M1 computer. When I check it from the terminal, it shows that it is installed, but when I type dotnet --version, I get this error "Failed to create CoreCLR, HRESULT: 0x8007000C". I get the same error when I want to create a project. I deleted and reinstalled it a few times, but the error does not go away.

**Comment by nagilson** [comment]
This appears to be an issue with the signature of .NET that was installed. I believe this should be fixed. If you still encounter it, please let us know.
