### ISSUE TITLE
[BUG] Can't run .Net: New Project. Command is not Found

### ISSUE THREAD

**Issue by hs1955** [microsoft/vscode-dotnettools#1136]
### Describe the Issue

Hello to VSCode dotnet tools team!

I am unable to run the .Net New Project command, much like in this issue: https://github.com/microsoft/vscode-dotnettools/issues/693
But the solution in that issue did not work for me:

I've tried re-installling the dev kit, but that didn't work.
Then I tried re-installing vscode, but that didn't fix it either.
Then I tried deleting all my extensions, then re-installing VSCode, restarting my laptop, but none of this solved my issue.

I did update my Kubuntu version recently and also did a fresh re-install of dotnet beforehand from the Ubuntu repositories rather than the latest Microsoft ones, but I really don't think either are a factor in this problem. I was trying to keep my system updated, and ensure dotnet is using files from only 1 repo and not a mix.

Anyways I'm quite stumped at how is this even possible haha. This all started when I wasn't able to stop at breakpoints with C# Godot. I was able to run C# code, just not debug. Then I worked all the way back, and it seems that either my C# extension is broken. Or maybe my system is broken somewhere.

I've tried running this command on a different Windows computer with the same extensions and that worked, so something is wrong with my setup on this machine, but I don't know what it could be.

![image](https://github.com/microsoft/vscode-dotnettools/assets/92299208/3f7469a8-f214-407d-accb-36cb68f50710)

### Steps To Reproduce

I just installed the C# dev kit extension, and tried to run the .NET New Project command, and that always failed, regardless of what I tried.

### Expected Behavior

I was expecting the command to ask for the settings/name of the new project, or similar, but the command did not run at all.

### Environment Information

---
Here's my VSCode details:
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-31-generic snap

---
And OS information:
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8365U CPU @ 1.60GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: HP
Product Name: HP ProBook 640 G5

---

**Comment by smitpatel** [comment]
cc: @webreidi

**Comment by webreidi** [comment]
https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_why-isnt-c-dev-kit-activating-c-dev-kit-commands-are-not-found explains the reasons why an extension might not activate and ways to correct the issue.

**Comment by smitpatel** [comment]
@hs1955 - Please check FAQ shared above and verify that you have those settings correct and still unable to get commands running.

**Comment by hs1955** [comment]
Yep, it seems FAQ (2) `dotnet.preferCSharpExtension` was enabled when it shouldn't have been, and I was using a vscode workspace.

Thank you all for helping me out with this one, my problem is fixed now. Though I'm surprised that I missed the docs for that haha. I'll close this issue now
