### ISSUE TITLE
[BUG] My .NET 6 Project Solution Couldn't Load

### ISSUE THREAD

**Issue by serkanparlak** [microsoft/vscode-dotnettools#1139]
### Describe the Issue

My .NET 6 Project Solution Couldn't Load after 1.5.20 version and later

### Environment Information

- OS: Windows
- VS Code Version: 1.89.1
- Extension Version: 1.5.20

**Comment by tmeschter** [comment]
@serkanparlak After attempting to open your solution, can you open the Terminal in VS Code, run `dotnet --info`, and paste the output of that command? It is important that you run it from the Terminal in VS Code.

**Comment by serkanparlak** [comment]
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.415
 Commit:    6963d2d1e0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.415\

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  6.0.415 [C:\Program Files\dotnet\sdk]
  7.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Users\obo13002\Projects\rmd\ms-banking\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by serkanparlak** [comment]
> @serkanparlak After attempting to open your solution, can you open the Terminal in VS Code, run `dotnet --info`, and paste the output of that command? It is important that you run it from the Terminal in VS Code.

PS C:\Users\Serkan\Projects\rmd\ms-banking> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.415
 Commit:    6963d2d1e0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.415\

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  6.0.415 [C:\Program Files\dotnet\sdk]
  7.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Users\Serkan\Projects\rmd\ms-banking\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by tmeschter** [comment]
@serkanparlak Thank you for that information; it is very helpful. This may be fixed in the latest pre-release version of C# Dev Kit, 1.7.4. Could you try that version and let me know if it works?

If not, the next thing to look at are the extension logs. After opening your solution, open the command palette and run "Developer: Open Extension Logs Folder", and then zip up and send along the ms-dotnettools.csdevkit folder.

Thank you!

**Comment by serkanparlak** [comment]
@tmeschter Thanks for your guidance, i tried that version and everything looks good now
