### ISSUE TITLE
[BUG] Variable $(SolutionDir) is *Undefined* during build events

### ISSUE THREAD

**Issue by hcv-pkuerzinger** [microsoft/vscode-dotnettools#114]
### Describe the Issue

The variable $(SolutionDir) that normally is available during BuildEvents and such, is resolving to *Undefined*.

### Steps To Reproduce

Create for example a PostBuildEvent which uses the $(SolutionDir) variable (echo it, or do a xcopy to copy files from solution dir)

### Expected Behavior

The variable should resolve to the directory path of the current solution

**Comment by Michael-Eng** [comment]
@Erarndt One more build issue for you to look at
