### ISSUE TITLE
[BUG] No project could be resolved in order to launch the application for debugging

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [microsoft/vscode-dotnettools#1146]
### Describe the Issue

When I try to run the ``launch.json`` configuration below, then I get this error:
```
No project could be resolved in order to launch the application for debugging
``` 

![image](https://github.com/microsoft/vscode-dotnettools/assets/130459814/04c8ad79-62e2-46ba-a9f8-00c745bd51db)

This only started happening with the latest release version of the .NET MAUI v0.11.96

My ``launch.json`` configuration:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[DEBUG] BioSnap",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "BioSnap",
            "configuration": "Debug"
        }
    ]
}
```

### Steps To Reproduce

1. Create a new .NET MAUI app
2. Create a launch configuration like the one below, where you specify the "project" to be launched
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[DEBUG] MAUI APP",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "BioSnap",
            "configuration": "Debug"
        }
    ]
}
```
3. Run the configuration
4. Configuration not being able to launch

### Expected Behavior

That the specified project will be launched with the configuration.

### Environment Information

- OS: MacOS (14.4.1 (23E224))
- VSCode: 1.89.1 (Universal)
- .NET MAUI Extension: 0.11.96
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2067525">2067525</a>

**Comment by vhugogarcia** [comment]
I'm facing this issue as well. 

The builtin variables such as ${workspaceFolder} do **not** work, returning the same error shown above from our friend @MLB-BIOMETRIC 

As a quick workaround @MLB-BIOMETRIC use the full path on the project property, and it will solve the issue _(for example: /Users/demo/Projects/helloworld/src/helloworld/helloworld.csproj)_, I know it is not ideal, but just a temporary solution, while the team is giving us a hand fixing the issue. 😃

**Comment by MLB-BIOMETRIC** [comment]
Looks like it doesn't recognise the ``configuration`` parameter in ``launch.json``. @mauroa 

```
        {
            "name": "[RELEASE] BioSnap",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "BioSnap", <--- (not working, as described in this issue)
            "configuration": "Release" <------ (not recognised. Still builds in Debug)
        },
```

**Comment by mauroa** [comment]
Hi everyone.

C# DevKit has released a new feature that allows you to select the desired solution configuration to use for building/debugging, so you don't need to make usage of the launch.json as you do today for MAUI.

You can still define your custom configurations as you do today, but you should select the right configuration in the VS code UI instead of manually adding it to the launch.json.

Find below a screenshot of the new feature:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2921919/887d9658-55db-43c0-85af-1c8f81dc6519)

Please ensure to update C#, C# DevKit and .NET MAUI to latest pre-release versions and give it a try. It should also fix this issue as a side effect.

I'll mark it as resolved, please let us know if you still find any problems that requires to reopen it.
Thanks for your feedback and help.

**Comment by vhugogarcia** [comment]
Hello @mauroa,

I have tested this new feature and it worked fantastic on my personal applications when testing on VS Code. I have two minor questions: 
- Is it possible to prevent to reload the window every time I change the configuration?
- Is it possible to add a C# Dev Kit setting that allow us to select the color of the selected configuration in the bottom bar? So we can set a color and get the selected configuration highlighted, so we don't miss it between so many text in the bottom bar. (not for this release but for future release)

Thanks in advance for solving this issue. 😃
