### ISSUE TITLE
The .NET Install Tool returned an unexpected result. Please view the 'Output' -> '.NET Install Tool' window for more info.

### ISSUE THREAD

**Issue by Dalwack1** [microsoft/vscode-dotnettools#1152]

**Comment by AbhitejJohn** [comment]
@Dalwack1 : Thanks for taking the time to report this. Any chance you have the output from the ".NET Install Tool" window, from the message that you can share with us?

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
