### ISSUE TITLE
 [BUG] Problem with .NET: New Project

### ISSUE THREAD

**Issue by kvenkatrajan** [microsoft/vscode-dotnettools#1153]
### Describe the Issue

https://github.com/dotnet/website-feedback/issues/147

Error while trying to run hello world tutorial
URL : https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create

### Steps To Reproduce

Following the tutorial resulted in the following error

![image](https://github.com/microsoft/vscode-dotnettools/assets/102772054/f12b9a3e-d364-4f72-9d74-9b47026a3f4b)

### Environment Information

Operating system
windows

More information about your system
Operating System: 64-bit operating system, x64-based processor

Edition: Windows 10 Pro Education
Version: 22H2
OS Build: 19045.4412
Experience: Windows Feature Experience Pack 1000.19056.1000.0

Description
DOTNET,

dotnet --info
.NET SDK:

Version: 8.0.300
Commit: 326f6e68b2
Workload version: 8.0.300-manifests.c1c70047
MSBuild version: 17.10.4+10fbfbf2e

Runtime Environment:

OS Name: Windows
OS Version: 10.0.19045
OS Platform: Windows
RID: win-x64
Base Path: C:\Program Files\dotnet\sdk\8.0.300\

Installed .NET Workloads:
No workloads installed to display.
Host:

Version: 8.0.5
Architecture: x64
Commit: 087e15321b
.NET SDKs installed:

8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
None

Environment variables:
Not set

global.json file:
Not found

**Comment by smitpatel** [comment]
Fixed in version 1.9.55
