### ISSUE TITLE
[SUGGESTION] do not steal focus when activating extension

### ISSUE THREAD

**Issue by stewartadam** [microsoft/vscode-dotnettools#1154]
### Describe the feature you'd like

The extension often steals focus from the active terminal or open file, particularly when a razor binary update is available - which is annoying for devcontainers as extensions start in the background so about a minute into using the devcontainer, your focus is stolen and the output window changes tabs:

```
Installing Razor Telemetry Version = 7.0.0-preview.24178.4...
Platform: linux, arm64, name=debian, version=12

Downloading package 'Razor Language Server Telemetry (Linux ARM64)' (9370 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'Razor Language Server Telemetry (Linux ARM64)'

Finished
```

This is on top of a toast notification "Downloading Razor telemetry package..." that appears.

Neither is particularly actionable for the user, just log that it's happening but there's no need to steal focus.

**Comment by phil-allen-msft** [comment]
For that specific message, this issue (https://github.com/dotnet/razor/issues/10262) will very likely remove the message from ever being displayed.

**Comment by phil-allen-msft** [comment]
In addition, it's possible that toggling the setting suggested at https://github.com/microsoft/vscode-dotnettools/issues/722#issuecomment-2126269970 will also help you with getting the behavior you want.

**Comment by ryzngard** [comment]
I'm going to close this since it's linked to the issue in dotnet/razor. Thank you for filing this suggestion!

**Comment by stewartadam** [comment]
I gave the `"dotnet.server.suppressLspErrorToasts": true,` setting a try but unfortunately the output pane still steals focus. Is there away to disable the output focus grabbing, not just the toast notifications?
