### ISSUE TITLE
[BUG] Error finding .NET SDK even though it is installed.

### ISSUE THREAD

**Issue by Topmen4099** [microsoft/vscode-dotnettools#1161]
### Describe the Issue

Why can't my .NET SDK install? I keep getting a message saying no .NET SDK was found, but I installed it like 600 times. WHY ISN'T IT WORKING?!

**Comment by AbhitejJohn** [comment]
Tagging @nagilson and @marcpopMSFT for thoughts.

**Comment by nagilson** [comment]
Are you trying to install the SDK via DevKit? It would be helpful if you can provide some more context and info.

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
