### ISSUE TITLE
No Intellisense on Linux

### ISSUE THREAD

**Issue by benupsavs** [microsoft/vscode-dotnettools#1170]
Type: <b>Bug</b>

On Linux (amd64)
Install Unity
Install Visual Studio Code
Install required extensions in vscode
Configure Unity to use vscode
Regenerate C# project

No Intellisense on Linux. Following these same instructions on Windows or Mac OS, Intellisense works out of the box.

This hasn't worked since the "use global mono" option was removed. Since Microsoft maintains both of the C# and Unity extensions, and this previously worked before Microsoft removed a feature, the fault likely likes with an extension maintained by Microsoft.

Extension version: 1.0.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.9.2-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1280P (20 x 1364)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|31.03GB (16.98GB free)|
|Process Argv|/home/ben/src/hex-client-unity -g /home/ben/src/hex-client-unity/Assets/Scripts/Unity/GameController.cs:1:0 --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --crash-reporter-id 420599b8-c7e0-4085-b61f-f05edefd52fa|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|sway|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|sway|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31066414
chatpanelt:31048053
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by arkalyanms** [comment]
The repro steps to this repo (C# Dev Kit's issue filing repo) do not match. @jbevain would you pull to unity side when you get a chance?

**Comment by jbevain** [comment]
Unfortunately our team is not reproducing the issue, and we're able to use the Unity extension on Linux, this makes me think there's a setup issue.

@benupsavs, please make sure in Unity your “Visual Studio Package” Unity Package is up to date in Unity's Package Manager.

**Comment by benupsavs** [comment]
> Unfortunately our team is not reproducing the issue, and we're able to use the Unity extension on Linux, this makes me think there's a setup issue.
> 
> @benupsavs, please make sure in Unity your “Visual Studio Package” Unity Package is up to date in Unity's Package Manager.

@jbevain I think that you misunderstood my bug report. I am able to use the Unity extension in Linux. In fact, I can attach the debugger, set breakpoints and inspect variables, etc. Therefore, there is no need to check whether the Unity extension works on Linux.

What doesn't work is Intellisense while using this setup. Only basic Intellisense for the current file is functional. Reference counts don't work properly. Documentation doesn't work properly (hover over any Unity class or other class from a different file in the project). Jumping to linked files doesn't work. Method completion doesn't work. Please try some of these features.

Note that there are many bug reports about this on the internet, which usually involve users trying to downgrade their C# plugins: [example](https://forum.unity.com/threads/intellisense-not-working-for-visual-studio-code.812040/)

**Comment by benupsavs** [comment]
Also, I would like to thank you for trying to figure this out, and if I can help to diagnose the issue in any way, please let me know.

**Comment by benupsavs** [comment]
This *seems* to be the issue, though I'm not certain:

- Intellisense for Unity projects on Linux only ever worked properly with Omnisharp and the global mono installation.
- The "use omnisharp" feature previously worked alongside the Unity extension, as a workaround to the problem.
- Now, "use omnisharp" no longer works because it is ignored while the C# Dev Kit is enabled.
- The C# Dev Kit can't be disabled without also disabling the Unity extension.

**Comment by jbevain** [comment]
@benupsavs now I'm pretty sure I understand :) There are multiple parts to the experience. I'm glad debugging works. To be able to get code completion and code navigation, the C# projects need to be generated in a way that the C# Dev Kit understands (the Unity extension relies on the C# Dev Kit for code completion and code navigation). And the C# Dev Kit needs to be able to run .NET code through a local .NET installation.

With an up to date Unity extension and C# Dev Kit, there's no Omnisharp or Mono needed required.

We need to verify sure that you have a proper setup for things to work. Again, please double check that the “Visual Studio Editor” package in the Unity Package Manager is up to date (2.0.22). This is what generates the projects that the C# Dev Kit understands. You can also attach the `Assembly-CSharp.csproj` so we can check that things look good.

You can also attach the logs for the C# and C# Dev Kit pane of Visual Studio Code's Output Window so we can check if things are loading properly.

You can also attach a screenshot of Visual Studio Code so we can check that projects are properly loaded.

**Comment by benupsavs** [comment]
@jbevain I re-read your comment and realized that you were asking about the Unity Package Manager. Yes, sorry. Actually, I had upgraded that package to the latest before I attempted any of this. It's version 2.0.22. I also removed the obsolete Visual Studio Code Editor package. I had followed the docs in the extension and tried everything before I reported this.

As a temporary test, I disabled the C# Dev Kit, and enabled Omnisharp, and straight away, everything worked again. Intellisense etc. But it does disable the Unity plugin, and I realize that it's not a good solution for several reasons.

So, now, I have re-enabled the C# Dev kit, I have disabled *every* vscode plugin except the C# and Unity ones. I'll try to give you all of the debugging info that I can. I see an error in the dev kit logs (below):

.NET SDK:
```
$ dotnet --version
8.0.106
$ which dotnet
/usr/bin/dotnet
```

C# Dev Kit logs:
```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "/usr/share/dotnet/dotnet"
.NET server started and IPC established in 998ms
Completed Spawn .NET server (1202ms)
Completed Clear environment (1572ms)
Completed Open a solution with environment service (1658ms)
Starting Restore solution...
Selected configuration: null, active configuration: Debug|Any CPU
Completed Open a solution (1670ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /home/ben/src/hex-client-unity/hex-client-unity.sln --interactive...
Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.
Completed command: "dotnet" restore /home/ben/src/hex-client-unity/hex-client-unity.sln --interactive (1430ms)
Completed NuGet restore.
Completed Restore solution (1431ms)
```

C# Logs:
```
Using dotnet configured on PATH
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/6bc3d298.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 11:55:39 AM] [Program] Language server initialized
```

Requested project file:
[proj.txt](https://github.com/user-attachments/files/15743934/proj.txt)

**Comment by jbevain** [comment]
Thanks @benupsavs!

@arkalyanms hey Arun, we've verified the generated project is a good SDK style Unity generated project. The issue seems to come from the C# Dev Kit:

> Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.

What could @benupsavs do to provide more information to help you investigate this?

Thanks!

**Comment by benupsavs** [comment]
I tried to install the latest dotnet using the install script instead of the system one. I exported DOTNET_ROOT to be at the installation path (~/.dotnet) and also set my path there at the beginning of the PATH environment. It seems to have worked. I have Intellisense support now. It doesn't really explain why a system-wide installed one wouldn't work, and some extra error logging would be nice, but I appreciate you giving me enough info to create a workaround to the problem. Thanks.

```bash
$ dotnet --version
8.0.301
$ which dotnet
/home/ben/.dotnet/dotnet
```

**Comment by arkalyanms** [comment]
> It doesn't really explain why a system-wide installed one wouldn't work, and some extra error logging would be nice

Assigning to both @nagilson and @lifengl based on this.

**Comment by nagilson** [comment]
> It doesn't really explain why a system-wide installed one wouldn't work, and some extra error logging would be nice

> Assigning to both @nagilson and @lifengl based on this.

Thanks @arkalyanms for the ping on this. My first question is how the system-wide install was done. If it was done on Ubuntu using `snap` installs, I would not be surprised by this behavior. But in this case, the user has an arch distro, and the most consistent way to get .net running on arch is via the install script and not using a system-wide install, to my knowledge.

Regarding DOTNET_ROOT, there is the environment that the system is running on and the environment that VS Code has, which can sometimes differ. It's possible it was not set in the VS Code environment. We have an installer that sets both of those automatically, but it doesn't support Arch at the moment, so it's a bit tough to give the user any further actionable items.

**Comment by benupsavs** [comment]
@nagilson I installed the .NET SDK through the `extra/dotnet-sdk` package. I realize that you don't directly support this setup, but I believe that things could still be a little better.

1. When there is no .NET SDK found, the C# Dev kit only shows the user a message that the `PATH` variable needs to be set. It doesn't say anything about `DOTNET_ROOT`.
2. Requiring `PATH` isn't a good experience for users. As you mentioned yourself, it's not something that's consistently applied, and often not easily modifiable
3. Every other language that I've tried in vscode supports easily setting an SDK location, or even selecting one from the list through the UI. It's a little ironic that the technology that's developed by the same custodian of the IDE has one of the worst experiences for managing multiple SDKs in the IDE.
4. There is no logging to explain the specific failure reason when the ProjectInitializationStatusService tries to start. Hopefully it's not so difficult to add a simple log message explaining what the error was.

I understand if you're not interested in trying to improve the situation based on this bug report because it's not a supported setup, but I am here to help debug things if you want to.

**Comment by nagilson** [comment]
cc @lifeng for #1, and #4, these seem like reasonable changes, but the use of `DOTNET_ROOT` is pretty nuanced, some I'm not actually sure how much we want to instruct users to edit it, as it could get them into a bad state pretty easily.

For #2, I think you raise a good point. I'm not sure what other alternatives we have except for #3, which I think is a good idea. We do our best to manage the PATH for the user if they use our installation feature, but obviously it's not available on arch. Technically we have the functionality to invoke the install script and install the SDK that way automatically as well, but that feature is a bit buggy as it never saw broad adoption/investment.

For #3, I think this is a great point. It would definitely require some investment into writing a global.json which may be why it hasn't been implemented at this time. I'll cc our PM's on this one @baronfel @webreidi

**Comment by lifengl** [comment]
I don't expect the extension depends on DOTNET_ROOT is set. If it is the case, it would be certainly a bug in the product. (The extension actually overrides DOTNET_ROOT, and the environment set by the user would only be expected, if the user application (built from a project) depends on it. So setting this environment is totally unexpected. @benupsavs : are you sure this environment variable is essential for you to fix the problem?

2 -- using PATH is actually by design, and this is being discussed internally. A part of that is many of our internal repo has its own initial script to install its private version SDK, and manipulate PATH environment, so both VS/VSCode session must start within the private environment to work with the repo. That usage pattern somehow affects the design here.  And also the logic behind it is the extension would build project exactly the same way when the developer runs dotnet build in a terminal window in the vscode, as many developers heavily use scripts in the repo and command line tools, so it is a balance between the need from different developers.  This would have to have some agreements before anything can be done.
 I do think in some scenarios like remote Linux usage, PATH is hard to set for different workspaces differently.

3 -- I feel that makes sense, as well as the developer can manage it and know the expectation.

4 -- I agree this is an important area to improve. Currently, it is likely failure messages could be found in one of the extension log file, but it is hard for developers who are using the extension to find out. A part of the problem is that this code tries to connect to a 3rd level child process in a chain of activation logic, so there are many failure points. But it should make it easier to identify common problems.

@benupsavs : to find out why the global SDK didn't work for you, use vscode command to open the extension log folder, and under C# DevKit/serviceHub. It is likely something can be found inside one of the log file

*-Microsoft.VisualStudio.ProjectSystem.CompositionService-*-*-1.log
*-Microsoft.VisualStudio.Code.ServiceHost-*-*-1.log
*-hubController-*-*-1.log

It is unfortunately that there are many processes boundaries, and they wrote own log files. When it went wrong, it might be failing inside, or the process failed to start.

**Comment by benupsavs** [comment]
@lifengl You're right that `DOTNET_ROOT` is not necessary. I only did it because it mentions it many times in the [installation instructions](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install).

My vscode was just pushed an update to both the C# and C# Dev Kit extensions, and after that, Intellisense with the system-wide SDK works now. So, there's nothing to debug anymore.

It would be nice to have some kind of popup when the C# Intellisense doesn't all wire up successfully. Having to look in multiple log files isn't so great. At the moment, it seems as if the IDE is oblivious to the fact that anything went wrong at all.

While it's probably not my place to say so, I disagree on the points about the `PATH` environment variable. The terminal doesn't always match the path of the IDE anyway, since it can be modified in settings. Also, in the case of Python virtual environments, the env is activated by the terminal, to match what the project sees. Maybe something similar can be done for C#. Anyway, apologies if this is overstepping or off topic. Thanks for the great IDE.
