### ISSUE TITLE
[BUG] Remove info logs from notifications

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#1172]
### Describe the Issue

Please remove this from a notification toast -- this is infolog-level information, the notification is not actionable.

![Image](https://github.com/microsoft/vscode-dotnettools/assets/4821/039a7c6e-cb38-4211-9e22-b584abc67b0d)

### Expected Behavior

System Info-only information is okay in logs, not in notifications

**Comment by phil-allen-msft** [comment]
This particular item is now a notification because it enables it to be cancelled.  This should go away with https://github.com/dotnet/razor/issues/10262.

**Comment by ryzngard** [comment]
Closing as fixed
