### ISSUE TITLE
June Iteration Plan

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#1173]
Below is the list of items being worked on during June 2024 sprint. Not all items listed below will finish and release in June.

- https://github.com/microsoft/vscode-dotnettools/issues/1035
- https://github.com/microsoft/vscode-dotnettools/issues/1195
- https://github.com/microsoft/vscode-dotnettools/issues/1114
- https://github.com/microsoft/vscode-dotnettools/issues/1105
- https://github.com/microsoft/vscode-dotnettools/issues/1097
- https://github.com/microsoft/vscode-dotnettools/issues/1083
- https://github.com/microsoft/vscode-dotnettools/issues/1063
- https://github.com/microsoft/vscode-dotnettools/issues/1055
- https://github.com/microsoft/vscode-dotnettools/issues/1042
- https://github.com/microsoft/vscode-dotnettools/issues/1030
- https://github.com/microsoft/vscode-dotnettools/issues/1028
- https://github.com/microsoft/vscode-dotnettools/issues/996
- https://github.com/microsoft/vscode-dotnettools/issues/963
- https://github.com/microsoft/vscode-dotnettools/issues/950
- https://github.com/microsoft/vscode-dotnettools/issues/947
- https://github.com/microsoft/vscode-dotnettools/issues/946
- https://github.com/microsoft/vscode-dotnettools/issues/928
- https://github.com/microsoft/vscode-dotnettools/issues/915
- https://github.com/microsoft/vscode-dotnettools/issues/854
- https://github.com/microsoft/vscode-dotnettools/issues/853
- https://github.com/microsoft/vscode-dotnettools/issues/840
- https://github.com/microsoft/vscode-dotnettools/issues/825
- https://github.com/microsoft/vscode-dotnettools/issues/791
- https://github.com/microsoft/vscode-dotnettools/issues/772
- https://github.com/microsoft/vscode-dotnettools/issues/758
- https://github.com/microsoft/vscode-dotnettools/issues/757
- https://github.com/microsoft/vscode-dotnettools/issues/724
- https://github.com/microsoft/vscode-dotnettools/issues/722
- https://github.com/microsoft/vscode-dotnettools/issues/714
- https://github.com/microsoft/vscode-dotnettools/issues/682
- https://github.com/microsoft/vscode-dotnettools/issues/674
- https://github.com/microsoft/vscode-dotnettools/issues/611
- https://github.com/microsoft/vscode-dotnettools/issues/605
- https://github.com/microsoft/vscode-dotnettools/issues/599
- https://github.com/microsoft/vscode-dotnettools/issues/542
- https://github.com/microsoft/vscode-dotnettools/issues/540
- https://github.com/microsoft/vscode-dotnettools/issues/517
- https://github.com/microsoft/vscode-dotnettools/issues/500
- https://github.com/microsoft/vscode-dotnettools/issues/473
- https://github.com/microsoft/vscode-dotnettools/issues/425
- https://github.com/microsoft/vscode-dotnettools/issues/402
- https://github.com/microsoft/vscode-dotnettools/issues/149
- https://github.com/microsoft/vscode-dotnettools/issues/132
- https://github.com/microsoft/vscode-dotnettools/issues/128
- https://github.com/microsoft/vscode-dotnettools/issues/105
- https://github.com/microsoft/vscode-dotnettools/issues/72

See also, [C# extension June 2024 Iteration Plan](https://github.com/dotnet/vscode-csharp/milestone/45)

**Comment by ggbtvs** [comment]
@webreidi  Still NO mention of Storyboard / xib syncing. Getting very very concerned here.  August 31 is NOT very far away.  What are we supposed to do after?  There's no way in hell I'm moving to Maui.net.  Looks like I will have to use Rider.
