### ISSUE TITLE
[BUG] Can't install latest .NET

### ISSUE THREAD

**Issue by programming-hampter** [microsoft/vscode-dotnettools#1178]
### Describe the Issue

I followed the instructions on https://learn.microsoft.com/ru-ru/training/modules/install-configure-visual-studio-code/6-exercise-install-dotnet, but I got an error after trying to download the latest .NET

### Steps To Reproduce

1. Go to View -> Command pallete -> Install New .NET SDK
2. Click Install .NET SDK (8.0.301)

### Expected Behavior

Expected to install the new version of .NET SDK, got an error instead.

### Environment Information

OS: Windows 10
VS code version: 1.90.0

**Comment by webreidi** [comment]
@programming-hampter can you provide the error you received as well as the output from ".NET Install Tool" please?

**Comment by nagilson** [comment]
@programming-hampter bumping this to see if you still have this issue?

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
