### ISSUE TITLE
MAUI app has exited with code -1073741189 (0xc000027b)

### ISSUE THREAD

**Issue by olivier-net** [microsoft/vscode-dotnettools#1179]
## Issue Description ##
I have the MAUI extension. When I launch my MAUI/BlazorHybrid app from VSCode I get this error: The program '[1234] XXX.exe' has exited with code -1073741189 (0xc000027b).

My target is Windows Local Machine. I can launch the app with Visual Studio without any issue.

## Steps to Reproduce ##

Launch the App with F5.

## Expected Behavior ##

See my MAUI GUI like when I launch it via Visual Studio

## Actual Behavior ##

The app immediatly exit

### C# log ###
<details>------------------------------------------------------------------------------
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Private.CoreLib.dll'. Symbols loaded.
Breakpoint warning: A copy of App.xaml.cs was found in CPAT.dll, but the current source code is different from the version built into CPAT.dll.
To allow this breakpoint to be hit: Add '"requireExactSource": false' to launch.json and restart debugging. - d:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\App.xaml.cs:6
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\CPAT.dll'. Symbols loaded.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Runtime.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\WinRT.Runtime.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Runtime.InteropServices.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Collections.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Collections.Concurrent.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Threading.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.WinUI.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Runtime.CompilerServices.Unsafe.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Private.Uri.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.ObjectModel.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.ComponentModel.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Numerics.Vectors.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Windows.SDK.NET.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Security.Cryptography.Algorithms.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Security.Cryptography.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Linq.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Memory.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.InteractiveExperiences.Projection.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Linq.Expressions.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Reflection.Emit.dll'. Cannot find or open the PDB file.
Loaded 'Snippets'.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Essentials.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Controls.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.DependencyInjection.Abstractions.dll'. Symbols loaded.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Controls.Xaml.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.AspNetCore.Components.WebView.Maui.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\CPAT.Core.dll'. Symbols loaded.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Http.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Logging.Abstractions.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Logging.Debug.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Configuration.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Configuration.Abstractions.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Primitives.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Xml.ReaderWriter.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Private.Xml.dll'. Symbols loaded.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Graphics.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Net.Primitives.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.AspNetCore.Components.WebView.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Logging.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.JSInterop.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.AspNetCore.Components.dll'. Symbols loaded.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.AspNetCore.Components.Web.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Options.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.Diagnostics.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Net.Http.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Diagnostics.DiagnosticSource.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Extensions.DependencyInjection.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Diagnostics.Tracing.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Threading.ThreadPool.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Controls.Compatibility.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.Runtime.Loader.dll'. Cannot find or open the PDB file.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\System.ComponentModel.TypeConverter.dll'. Cannot find or open the PDB file.
Loaded 'D:\SVN\CPAT_Dev\Logiciel\CPAT_Mobile_Blazor\Blazor\CPAT\CPAT\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\CPAT.Blazor.dll'. Symbols loaded.
The program '[67240] CPAT.exe' has exited with code -1073741189 (0xc000027b).
</details>

## Environment information ##

**VSCode version**: 1.89.1
**C# Extension**: 2.31.19
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.6751eab7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

.NET workloads installed:
 [maui]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.21/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.21\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.9.34728.123
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.9.34728.123
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: VS 17.9.34728.123
   Manifest Version:    8.0.21/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.21\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.9.34728.123
   Manifest Version:    34.0.95/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.95\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|asp-net-core-switcher|adrianwilczynski|2.0.2|adrianwilczynski.asp-net-core-switcher-2.0.2|
|csdevkit|ms-dotnettools|1.6.8|ms-dotnettools.csdevkit-1.6.8-win32-x64|
|csharp|ms-dotnettools|2.31.19|ms-dotnettools.csharp-2.31.19-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|dotnet-maui|ms-dotnettools|0.11.96|ms-dotnettools.dotnet-maui-0.11.96-win32-x64|
|escape-string|cvbge|1.1.0|cvbge.escape-string-1.1.0|
|gitignore|michelemelluso|1.0.1|michelemelluso.gitignore-1.0.1|
|gitlens|eamodio|15.0.4|eamodio.gitlens-15.0.4|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-ssh|ms-vscode-remote|0.110.1|ms-vscode-remote.remote-ssh-0.110.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|svn-scm|johnstoncode|2.17.0|johnstoncode.svn-scm-2.17.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.5|ms-dotnettools.vscode-dotnet-runtime-2.0.5|
|vscode-xml|redhat|0.27.1|redhat.vscode-xml-0.27.1-win32-x64|;

</details>

**Comment by mauroa** [comment]
Thanks for your feedback.

We are not able to reproduce the issue you reported, could you share the application that is failing? 
Otherwise, does this happen with every MAUI application?

Thanks for your help

**Comment by mauroa** [comment]
We are unable to continue the investigation without the required information.
Feel free to request a reopening if you still experience any issue after updating to latest C#, C# DevKit and .NET MAUI versions and also please provide the information requested above.
Thanks for your help and feedback.

**Comment by dota-devy** [comment]
My app was also receiving this error when launching a run and debug profile in vscode.

The generated launch.json was trying to execute MyApp.dll when it should have been launching the .exe file

I changed .dll to .exe in the launch.json "configuration/program" field and now my app launches correctly.
