### ISSUE TITLE
.NET SDK not found VS CODE after installing 

### ISSUE THREAD

**Issue by Nahian9678** [microsoft/vscode-dotnettools#1180]
### Describe the Issue

![Capture](https://github.com/microsoft/vscode-dotnettools/assets/55135020/49967f33-44ed-4f7b-848c-94c8757b4324)
After installing .NET SDK it's still showing to download the file again, when I reload it appears again and again not found SDK file

**Comment by webreidi** [comment]
@Nahian9678 Is there an error when you install the SDK? If so can you provide that? Can you please try to run dotnet --version command from the Terminal and provide me with the results? I'd like to see if the SDK is actually there and the page just isn't disappearing, or if there is a problem with the SDK acquisition.

**Comment by nagilson** [comment]
Bump @Nahian9678  for more info about this issue and if its working for you or not.

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.

**Comment by Shubhankar525** [comment]
@webreidi I had this same problem, do you have the solution?

**Comment by webreidi** [comment]
@Shubhankar525 there are different solutions depending on details of how the SDK was installed. I see you opened an issue for your case. Reply there with the details and we'll get it working for you.
