### ISSUE TITLE
[BUG] .NET Acquisition Failed: Validation of .dotnet installation for version 8.0.6x64 failed

### ISSUE THREAD

**Issue by aminaatik** [microsoft/vscode-dotnettools#1183]
### Describe the Issue

each time I try opening a file and running the file; i get an error message: 
Error
Failed to download .NET 8.0:
.NET Acquisition Failed: Validation of .dotnet installation for version 8.0.6~x64 failed: Expected executable does not exist at "/Users/mohamedsmayow/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.6~x64/dotnet"

### Steps To Reproduce

In this environment I receive an error message: Error
Failed to download .NET 8.0:
.NET Acquisition Failed: Validation of .dotnet installation for version 8.0.6~x64 failed: Expected executable does not exist at "/Users/mohamedsmayow/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.6~x64/dotnet"

### Environment Information

macOs

**Comment by nagilson** [comment]
May you attach a log please so we can further investigate?

Our log files are located alongside VS Code logs. If you want to find them manually, navigate here:
Linux: ~/.config/Code/logs
Mac: ~/Library/Application Support/Code/logs/
Windows: c:\Users\USER\AppData\Roaming\Code\logs\

Then find the folder created at the time you experienced the bug in the logs folder.
From there, go to window1 -> exthost -> ms-dotnettools.vscode-dotnet-runtime. The log file should be located in this folder.

Note: The window folder may change depending on how many VS Code windows you have open; if our extension is running in the 2nd window, it'd be in a folder called window2.

**Comment by nagilson** [comment]
@aminaatik  what's the output of ` which dotnet` ?

**Comment by nagilson** [comment]
If you are still facing this issue, please add the requested information so we can help you.
