### ISSUE TITLE
Wrong UI element is xaml hot reloading

### ISSUE THREAD

**Issue by davidortinau** [microsoft/vscode-dotnettools#1186]
Type: <b>Bug</b>

I'm updating properties on a Button, but a different Button in the UI is getting the updates.

https://github.com/microsoft/vscode-dotnettools/assets/41873/a249af27-1485-4714-a8cd-896da354749c

Extension version: 0.12.42
VS Code version: Code - Insiders 1.91.0-insider (6facfe23b300eb448c35d07291cad7ad98625302, 2024-06-07T08:38:32.379Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
nb_pkg_only:31057982
26j00206:31048877
nativerepl1:31063927
refactort:31067743

```

</details>

**Comment by BretJohnson** [comment]
@davidortinau - have you seen this happen recently? repro steps would be very helpful, if can find some; thanks

**Comment by BretJohnson** [comment]
@davidortinau - I wasn't able to repro this. Have you seen it recently? If not, let's just close & can reopen if see it again. Thanks.

**Comment by BretJohnson** [comment]
Closing since can't repro. If we see this happen again, let's reopen or create a new issue.
