### ISSUE TITLE
XAML Hot Reload stops succeeding

### ISSUE THREAD

**Issue by davidortinau** [microsoft/vscode-dotnettools#1190]
Type: <b>Bug</b>

In a session XAML hot reload was working, and then stopped. In the .NET Hot Reload output panel I now see these messages which don't make sense to me, but might explain what's going wrong:

15:38:16 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: App
15:38:17 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MainPage
15:38:20 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: FilterView
15:38:20 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: ShoppingPage
15:38:20 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MonoProductListItem
15:38:20 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MonoProductListItem
15:38:20 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MonoProductListItem
15:38:23 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MonoProductListItem
15:38:23 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MonoProductListItem
15:38:55 [⚠] [XAML] ChildIndex <= -1, Parent: Null Child: MonoProductListItem

Extension version: 0.12.42
VS Code version: Code - Insiders 1.91.0-insider (21decd9342dd2e14f2a7cd2883f84e6ff43ea0df, 2024-06-11T05:51:04.314Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|. --crash-reporter-id fc80353a-ef2a-479f-83ff-be5b061d3542|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
nb_pkg_only:31057982
26j00206:31048877
nativerepl1:31071684
refactort:31067743

```

</details>

**Comment by BretJohnson** [comment]
@davidortinau - have you seen this happen recently? repro steps would be very helpful, if can find some; thanks

**Comment by BretJohnson** [comment]
Closing. I wasn't able to repro this when it was first reported. The ChildIndex log messages are benign and have since been removed.
