### ISSUE TITLE
[BUG] Error running dotnet --info: Error: Command failed: dotnet --info /bin/sh: dotnet: command not found /bin/sh: dotnet: command not found 

### ISSUE THREAD

**Issue by GitHanDong** [microsoft/vscode-dotnettools#1192]
### Describe the Issue

找不到 .NET Core SDK 的位置：Error running dotnet --info: Error: Command failed: dotnet --info /bin/sh: dotnet: command not found /bin/sh: dotnet: command not found 。将不会启用 .NET Core 调试。请确保已安装 .NET Core SDK 且该 SDK 位于路径上。

<img width="468" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/16949634/ef9e3223-02c7-4dad-9263-445c46a8cec7">

<img width="446" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/16949634/1a817e25-51d0-48c9-b595-262ef71bab01">

### Visual Studio Code 
版本: 1.90.0 (Universal)
提交: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
日期: 2024-06-04T19:34:44.157Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
### macOS Sonoma 14.5 
CPU: M2

**Comment by nagilson** [comment]
Thank you for your report. Have you tried to install the .NET SDK via the Walkthrough / Getting Started Page?

**Comment by GitHanDong** [comment]
> Thank you for your report. Have you tried to install the .NET SDK via the Walkthrough / Getting Started Page?

Yes I tried reinstalling the SDK and tried installing a different version. As you can see below I installed three versions. And I guess it might be that vscode's default console does not match my local console configuration, try to set vscode's console to match my local one (ZSH). But that didn't solve the problem either.
![image](https://github.com/user-attachments/assets/121cc879-aa32-439e-bc77-f21cef0da5ab)

**Comment by nagilson** [comment]
Thank you for following up. This is most likely a PATH issue. If you try to print the PATH environment variable in Vs Code, what do you get, and is it different from your terminal? I would suspect if you can add the .NET to the PATH in VS Code, it would work.

We do edit the PATH in 3 different ways so I'm surprised it's not working for you, this is unfortunate. If you mind sharing some logs, then that could be helpful. 

Our log files are located alongside VS Code logs. If you want to find them manually, navigate here:
Linux: ~/.config/Code/logs
Mac: ~/Library/Application Support/Code/logs/
Windows: c:\Users\USER\AppData\Roaming\Code\logs\

Then find the folder created at the time you experienced the bug in the logs folder.
From there, go to window1 -> exthost -> ms-dotnettools.vscode-dotnet-runtime. The log file should be located in this folder.

Note: The window folder may change depending on how many VS Code windows you have open; if our extension is running in the 2nd window, it'd be in a folder called window2.

**Comment by linv2** [comment]
I'm using code-server having this problem too, and the same thing is that I'm using the arm architecture too!


```
code-server
code-server: v4.91.1
Code: 1.91.1
Commit: 1962f48b7f71772dc2c060dbaa5a6b4c0792a549
Date: 2024-07-15T17:58:33.007Z (4 days ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

```


```
ubuntu@instance-20240508-1435:/$ dotnet --info
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /home/ubuntu/.dotnet/sdk/8.0.303/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.7
  Architecture: arm64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [/home/ubuntu/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/home/ubuntu/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/home/ubuntu/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download```

**Comment by linv2** [comment]
when i exec 
```
sudo ln -s /home/ubuntu/.dotnet/dotnet /usr/local/bin/
```
the extension looks working.

**Comment by nagilson** [comment]
For @linv2 issue, this is an issue with snap installs that is being tracked by canonical and they are working on fixing it. https://github.com/canonical/dotnet-snap/issues/13#issuecomment-2243859468 

For the above issue, if you are still facing it, please follow up with the requested information so we can help you. This is a separate issue from linv2's issue.

**Comment by xarthurx** [comment]
For macOS, this problem still exist.
Need to do:

```
sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/
```
manually to resolve it.
