### ISSUE TITLE
[BUG] In version 1.7.25, the "Debug > Start new instance" command is broken

### ISSUE THREAD

**Issue by denvifer** [microsoft/vscode-dotnettools#1195]
### Describe the Issue

After the latest update, it's not possible to use the "Debug > Start new instance" command.

![csharp1](https://github.com/microsoft/vscode-dotnettools/assets/19556520/645c4058-387f-4b13-9c7d-930a065e277c)

```
error MSB4057: The target "<App Name>" does not exist in the project.
/Users/...csproj : error MSB4057: The target "<App Name>" does not exist in the project.
```

Rebuild command works normally.
"Debug > Start new instance" works normally in the version 1.6.x.

### Steps To Reproduce

1. Select a project
2. Choose "Debug > Start new instance"

### Expected Behavior

The command works normally.

### Environment Information

- OS: macOS
- VSCode version: 1.90.0
- Extension version: 1.7.25

**Comment by arkalyanms** [comment]
@WardenGnaw this seems to be a regression.

@denvifer any chance of a reproable project we could pick up from you? We tried it a few times on a mac and did not hit an issue.

**Comment by kostapetan** [comment]
I am hitting the same issue when running in Codespaces (so not on Mac). Seems to be a regression, any workaround?

**Comment by WardenGnaw** [comment]
@kostapetan Do you have any special characters or spaces in your AppName? I believe the bug is that non-simple project names fail to build.

E.g. ConsoleApplication1 should succeeed, however if you have something like `Console App 1.csproj` it will fail.

**Comment by jmrpineda** [comment]
same issue here,
my case is:
- sample.sln
|- webapi\sample.api.url\sample.api.url.csproj
|- other.app.manager\other.app.manager.csproj

if I try to launch projects in webapi folder, I get the issue
but, if I try to launch other.app.manager project, I don't get the issue

Any workaround? any idea?
My launch-task that fails:

{
    "name": "C#: API URL-Shortener Debug",
    "type": "dotnet",
    "request": "launch",
    "projectPath": "${workspaceFolder}/webapi/sample.api.url/sample.api.url.csproj"
}

the command that the launch exec:
dotnet build /[...]/sample.sln /target:sample_api_url /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU"

If I remove the /target:sample_api_url the issue doesn't appear

**Comment by shv07** [comment]
I am facing the same issue with exactly same code and launch setting files. 

I have projects of format - My.Simple.Project

I noticed earlier the debug option would run this command
```
dotnet build /path/to/My.Simple.Project.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="AnyCPU" 
```

But now, possibly after extension updates, it uses sln file and `/target` parameter and replaces dot with underscore.
The error message is same `...error MSB4057: The target "My_Simple_Project" does not exist in the project`
:-
```
dotnet build path/to/sln-file.sln /target:My_Simple_Project /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
```

**Comment by denvifer** [comment]
@arkalyanms @shv07 Yes indeed, I also have dots in my project name. It seems that unexpectedly replacing them with underscores is causing the problem.

**Comment by SciammarellaB** [comment]
Same problem, I have my API name "Application.Api" and it is mistaken the "." with "_" in Debug.
Running "dotnet run" in terminal the project works fine.

**Comment by rysweet** [comment]
same issue, no special chars in target name.

**Comment by onionhammer** [comment]
I am also getting this, it happens if the solution is more than 1 directory removed from the projects, here's a repro:

https://github.com/onionhammer/repro-devkit

**Comment by WardenGnaw** [comment]
@onionhammer Thanks for giving a repro project, however I'm unable to access https://github.com/onionhammer/repro-devkit .

Was the repository set to private?

**Comment by onionhammer** [comment]
> @onionhammer Thanks for giving a repro project, however I'm unable to access https://github.com/onionhammer/repro-devkit .
> 
> Was the repository set to private?

Oops, apologies. I used the publish within VS code and chose public, so maybe thats a separate bug :D

The repo should be public now

**Comment by Dv-Wx** [comment]
Also encountering issue where dots in project name are replaced by underscores. I'm running v1.7.25 on Windows 11.

Switching back to v1.6.8 (I'm not running pre-release versions) seems to be a workaround.

**Comment by jmrpineda** [comment]
**Temporary solution**, may be it is obvious for you guys, but, I want to share the solution I found,

The issue face under this versions:

Visual Studio Code Version: 1.90.1
Extensions:
**C# dev kit v1.7.25**
c# v.2.33.17

Downgrade the extension C# dev kits to v.1.6.8
thats all, I hope this help you

Now I can launch the debug as used to do!

**Comment by a-magdy** [comment]
@jmrpineda just came in to write the same
I tried everything and was following an issue elsewhere, until I figured the downgrading it is the temp solution 

Adding screenshots

![Screenshot 2024-06-13 at 23 06 22](https://github.com/dotnet/vscode-dotnet-runtime/assets/14139855/01e64090-4d77-4596-8aaf-577f87acb04c)

![Screenshot 2024-06-13 at 23 06 34](https://github.com/dotnet/vscode-dotnet-runtime/assets/14139855/5f6fd1e7-b67e-4700-b35c-21cdb93abe0f)

**Comment by a-magdy** [comment]
Also I noticed that when I run the project from the terminal then I do a (.Net core Attach) and select the process it works

Using default settings for it in .vscode/launch.json

```json
{
"name": ".NET Core Attach",
"type": "coreclr",
"request": "attach"
},
```


So the problem appears only when I try to launch using VSCode

```
{
"name": "C#: Debug",
"type": "dotnet",
"request": "launch",
"projectPath": "${workspaceFolder}/Source/Functions/<Project>.csproj"
},
```

**Comment by Clockwork-Muse** [comment]
I believe I'm hitting this as well, however my project does **not** contain any periods (so no period->underscore replacement is happening).

**Comment by andreakarasho** [comment]
Same issue, gonna rollback

**Comment by NoelFB** [comment]
I'm also getting this same issue in both pre-release `v1.8.2` and stable `v1.7.25`. Switching to an older version (`v1.6.8`) resolves the problem for me.

```
dotnet build PATH/PROJECT_NAME.sln /target:Editor /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
PATH/Source/Standalone/Desktop/Desktop.csproj : error MSB4057: The target "Editor" does not exist in the project.
PATH/Source/World/World.csproj : error MSB4057: The target "Editor" does not exist in the project.
PATH/Source/FMOD/FMODCS.csproj : error MSB4057: The target "Editor" does not exist in the project.
PATH/Source/Standalone/Desktop.Aot/Desktop.Aot.csproj : error MSB4057: The target "Editor" does not exist in the project.
PATH/Source/Game/Game.csproj : error MSB4057: The target "Editor" does not exist in the project.
PATH/Source/Utility/SourceGen/SourceGen.csproj : error MSB4057: The target "Editor" does not exist in the project.
PATH/Source/Editor/Editor.csproj : error MSB4057: The target "Editor" does not exist in the project.
```

**Comment by jmrpineda** [comment]
> @jmrpineda just came in to write the same I tried everything and was following an issue elsewhere, until I figured the downgrading it is the temp solution
> 
> Adding screenshots
> 
> ![Screenshot 2024-06-13 at 23 06 22](https://private-user-images.githubusercontent.com/14139855/339553541-01e64090-4d77-4596-8aaf-577f87acb04c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTQ5MTEsIm5iZiI6MTcxODM1NDYxMSwicGF0aCI6Ii8xNDEzOTg1NS8zMzk1NTM1NDEtMDFlNjQwOTAtNGQ3Ny00NTk2LThhYWYtNTc3Zjg3YWNiMDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA4NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjUyMDRiZjI1Yzc0ZDdhYzhhNGE3MWM2Y2FmN2E3ZTA4ZTBjMzI5MzVmN2M3ZTZmMzlmZTcwZTBlNzYzMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tq7NTnnjvNkr3iuFc9sdocY4Ts2mEA8IrW9qC_PpF8c)
> 
> ![Screenshot 2024-06-13 at 23 06 34](https://private-user-images.githubusercontent.com/14139855/339553525-5f6fd1e7-b67e-4700-b35c-21cdb93abe0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTQ5MTEsIm5iZiI6MTcxODM1NDYxMSwicGF0aCI6Ii8xNDEzOTg1NS8zMzk1NTM1MjUtNWY2ZmQxZTctYjY3ZS00NzAwLWIzNWMtMjFjZGI5M2FiZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA4NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZWI0ZjQ4ZGQxZGQ5ZDU3ZmRlMzM1OGRlY2U4YTYxNmM0NDI2MjQyN2YwYWNhNmFlNzdiOWY2ZTY1M2I5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Goj37U9ClLQk-N4BdBUOTruxYuMsWclsGzD8ThrE_Ho)

nice, that's ensures that the "solution" is valid, at least for most of us!

**Comment by WardenGnaw** [comment]
For folks impacted by this issue, please update the C# Dev Kit extension to either the v1.7.27 release or v1.8.6 prerelease.

**Comment by arcmoonstudios** [comment]
Thanks fellas
