### ISSUE TITLE
[BUG] Aspire stops debugging after any project stops

### ISSUE THREAD

**Issue by onionhammer** [microsoft/vscode-dotnettools#1196]
### Describe the Issue

If you follow the guide [here](https://learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations#create-the-migration-service), it has you create an EF Core migrations project which calls  `hostApplicationLifetime.StopApplication();` when the migrations complete.

If you launch a debugger with C# dev kit on Aspire, the entire aspire project will stop debugging once this happens.

### Steps To Reproduce

1. Create an aspire app and follow the guide linked above
2. Launch the debugger on the aspire app
3. The debugger stops and aspire quits as soon as the migrations are done

### Expected Behavior

The migrations process should quit, but any other attached processes should be left running

### Environment Information

- OS: Windows 11
- VS Code 1.90.0
- Dev kit 1.6.8 (due to #

**Comment by jhancock-taxa** [comment]
Confirmed, happens here too.

**Comment by sliekens** [comment]
+1, tried with both stable and pre-release versions of the extensions.

As a workaround, I keep the application running in Development.

``` csharp
// IHostEnvironment env
if (!env.IsDevelopment())
{
    logger.LogInformation("Stopping application...");
    hostApplicationLifetime.StopApplication();
}
```

**Comment by burtonrodman** [comment]
btw, works as expected in Visual Studio

**Comment by WardenGnaw** [comment]
This should be resolved in the last version of the C# Extension v2.45.20 and on 

https://github.com/dotnet/vscode-csharp/releases/tag/v2.45.20
