### ISSUE TITLE
[BUG] Working without admin rights

### ISSUE THREAD

**Issue by KaFa3103** [microsoft/vscode-dotnettools#1207]
### Describe the Issue

this is a company laptop and i do not have admin rights.

**Comment by nagilson** [comment]
You can follow the steps to install the .NET SDK locally using the install scripts, which, when the PATH is set, should allow use of the .NET SDK. https://github.com/dotnet/core/blob/main/release-notes/8.0/install.md. We may add automation for this in the future, which is already implemented, just not leveraged.

@webreidi @baronfel For awareness.
