### ISSUE TITLE
[SUGGESTION] Ability to configure the Unity project path for the debugger

### ISSUE THREAD

**Issue by PokiFOX** [microsoft/vscode-dotnettools#1208]
### Describe the Issue

I encountered an issue while using the Unity v1.0.2 extension in VSCode. My solution includes not only the Unity project but also other projects, and I don't want to open a separate VSCode instance for each project. So, I tried to configure the unity.projectPath in the .vscode/launch.json. The launch.json looks something like this:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach to Unity",
			"type": "vstuc",
			"request": "attach",
			"projectPath": "${workspaceFolder}/platform/",
		}
	]
}
```

My Unity3D editor is opened to "${workspaceFolder}/platform/" and the project can start normally. However, when I try to attach to Unity in VSCode, I get an error message:

"Unity is not running for the current project."

How can I resolve this issue?

### Environment Information

os: macos sonoma 14.4
vscode version: 1.90.1
extension version: Unityv1.0.2

**Comment by jbevain** [comment]
Thanks for filing this. At the moment, the debugger expects that the workspace folder is the Unity project path, so that it can look for Unity specific files.

As a workaround, you can launch the debugger using the `Attach Unity Debugger` command in the command palette, and this should work.

**Comment by PokiFOX** [comment]
How should I use the projectPath in launch.json? Could you provide a newer version that supports this directory change?

**Comment by jbevain** [comment]
> How should I use the projectPath in launch.json?

At the moment, `projectPath` is not a supported property for the `vstuc` debugger. As a workaround, please use the `Attach Unity Debugger` command to start the debugger.

> Could you provide a newer version that supports this directory change?

We've added this to our backlog and will look at adding support for this scenario in a future version.

**Comment by PokiFOX** [comment]
thanks for the explanation.

**Comment by jbevain** [comment]
Setting the `projectPath` property is now supported in the Unity extension for Visual Studio Code version `1.0.3`.
