### ISSUE TITLE
[BUG] <VS code setting>

### ISSUE THREAD

**Issue by Himanshuraaj** [microsoft/vscode-dotnettools#1221]
### Describe the Issue

![Screenshot 2024-06-19 110251](https://github.com/microsoft/vscode-dotnettools/assets/103298918/b726b4f3-0268-4513-92b8-3e88e7275f39)

**Comment by AbhitejJohn** [comment]
@Himanshuraaj : Can you add more details on what the bug here is?

**Comment by AbhitejJohn** [comment]
Closing this out for now. Please feel free to create a new issue with more details.
