### ISSUE TITLE
[BUG] IntelliSense goes haywire

### ISSUE THREAD

**Issue by Zode** [microsoft/vscode-dotnettools#1223]
Type: <b>Bug</b>

C# devkit IntelliSense seems to go a bit haywire once a plugin project is added by the user onto a Flax game project, and it starts to yell about things not existing in the current context, and how classes intended to be extended from are inaccessible due to their protection level.

This should not be the case, and does not happen under VS on Windows, or competitor products on Linux or Windows.

**Linux is required to reproduce this issue**, as Flax Engine generates VS solution files in place of VSCode workspace/project files on Windows.

#### Steps to reproduce
1. Install [Flax Engine](https://github.com/FlaxEngine/FlaxEngine/)
2. Clone [demo project repo](https://github.com/Zode/vscode-bug-demo)
3. Open project in Flax
5. Open solution in VSCode 
6. Receive CS0122 and CS0103 errors
7. Close VSCode and Flax
8. Move `vscodetest/Plugins/DemoPlugin` folder to somewhere.
9. Edit `vscodetest/vscodetest.flaxproj` and remove the plugin reference (it is a json file, there is currently no way to remove a plugin from the editor GUI)
10. Open project in flax
11. Hit the menu option: `File` -> `Generate scripts project files` in Flax
12. Open solution in VSCode 
13. Watch in amazement as CS0122 and CS0103 errors disappear

If you wish to reset the demo project, return the plugin folder and re-add the reference to the `vscodetest/vscodetest.flaxproj`, and clear out the cache/binaries folders. Once flax is open again run the `File` -> `Generate scripts project files` command. Or alternatively just nuke the demo project and clone it from git again. 

#### Reproduction demo video:

https://github.com/microsoft/vscode-dotnettools/assets/9205294/15839094-b0a6-442d-8281-831e7e3dc862

If this is not a IntelliSense bug but rather how the sln/csproj are set up, please do tell since I can't see anything wrong with them when manually inspecting, and this has been an issue for multiple users.

Extension version: 1.7.27
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:02:43.666Z)
OS version: Linux x64 6.9.3-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3723)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.71GB (42.72GB free)|
|Process Argv|/mnt/hdd1/Projects/flax/vscodetest/vscodetest.code-workspace -g /mnt/hdd1/Projects/flax/vscodetest/Plugins/DemoPlugin/Source/DemoPluginEditor/DemoActor.cs:1 --crash-reporter-id 561932b3-3cc0-44e3-8e08-d5e747d004e9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by Zode** [comment]
Tested again after noticing an update to VSCode itself (1.90.1 -> 1.90.2), just for pure chance it would fix itself.
IntelliSense does seem to behave correctly now instead of yelling about nonexistent CS0122 and CS0103 errors, though it takes a noticeable while to solve the entire project upon first load, however that is a non-issue in my books. 

Extension version: 1.7.27
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:33:48.698Z)
OS version: Linux x64 6.9.5-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3682)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|62.71GB (41.67GB free)|
|Process Argv|/mnt/hdd1/Projects/flax/boomshoot/boomshoot.code-workspace -g /mnt/hdd1/Projects/flax/boomshoot/Plugins/CraftyCSG/Source/CraftyCSGEditor/Brush.cs:1 --crash-reporter-id 561932b3-3cc0-44e3-8e08-d5e747d004e9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31082723

```

</details>

**Comment by smitpatel** [comment]
I tried out cloning the repo and open it in C# dev kit. I didn't see any errors. 6 project failed to load. Either they were wrong type (not SDK style C# project) or the csproj file is not found on disk. This seems like a bug in flax engine to generate csproj files.

**Comment by smitpatel** [comment]
@Zode - I am not able to reproduce this issue in C# dev kit itself. Can you share a repro solution which doesn't work in C# dev kit?

**Comment by Zode** [comment]
> @Zode - I am not able to reproduce this issue in C# dev kit itself. Can you share a repro solution which doesn't work in C# dev kit?

[https://github.com/Zode/vscode-bug-demo](https://github.com/Zode/vscode-bug-demo) is what i used to reproduce the bug in the inital report (+ in the video), but as i mentioned a few messages up the issue fixed itself after a minor update to VSCode so i really don't have an idea if it was VSC's doings or C# devkit's doings, or maybe something on my system gone wrong in some cache?

**Comment by smitpatel** [comment]
@Zode - The repo didn't reproduce error for me. Are you still facing any issues?

**Comment by Zode** [comment]
> @Zode - The repo didn't reproduce error for me. Are you still facing any issues?
No i'm not, updated VSCode from 1.90.1 -> 1.90.2 (as stated few messages back) and that solved the issue.
i'm fairly confident now that it was just some really obscure space ray :tm: problem that specifically affected 1.90.1 versions even through reboots and restarts :joy:
