### ISSUE TITLE
the create .net project doesnt work 

### ISSUE THREAD

**Issue by zeyadahmed43** [microsoft/vscode-dotnettools#1227]
hallo i new to c# and when i click in create new .net project it doesnt work i even doesnt give me and any command iam using vs code in windows

**Comment by zeyadahmed43** [comment]
when i write dotnet --info it give me this 
![Screenshot 2024-06-21 021527](https://github.com/microsoft/vscode-dotnettools/assets/154952343/2ca2f6eb-37b7-4e5d-bc21-f68a8d80fafe)

is there any thing wrong ?

**Comment by smitpatel** [comment]
Can you share output from C# dev kit tab in output window?

**Comment by zeyadahmed43** [comment]
https://github.com/microsoft/vscode-dotnettools/assets/154952343/83b340d4-7101-4212-b120-99fd2ffb6fcf

there is nothing in output

**Comment by smitpatel** [comment]
@zeyadahmed43 - Thanks for sharing the video. In the output pane, there is dropdown menu which has Tasks selected in the video, if you look into that there should be an entry for C# dev kit which will contain output from C# dev kit extension.

**Comment by zeyadahmed43** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/154952343/48541b39-75dc-4666-98ec-7a02e2922d03)
 
that thing pop up

 iam alittle bit busy cuase i have my 3 senoir finals so i will be late for responding

**Comment by smitpatel** [comment]
Can you share logs from extension log folder?
You can access it via command palette.
![image](https://github.com/microsoft/vscode-dotnettools/assets/1528107/7cea25b5-bd1e-4837-bbd7-56ac3ce24167)
We would need the content of `ms-dotnettools.csdevkit` folder from extension logs.

**Comment by zeyadahmed43** [comment]
i find the problem and now its run  thank you
