### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Astropsyc** [microsoft/vscode-dotnettools#1228]
### Describe the Issue

i installed latest sdk in visual studio code but no sdk found message in terminal or command promt

### Environment Information

windows 11 home
latest vs code

**Comment by AbhitejJohn** [comment]
@Astropsyc : Could you add more details on the error message please? How did you install the sdk?

**Comment by nagilson** [comment]
If you are still experiencing this issue, please let us know so we can help you.
