### ISSUE TITLE
How to navigate the prev/next method overloads in the hovering quickinfo popup?

### ISSUE THREAD

**Issue by pinkli** [microsoft/vscode-dotnettools#1229]
I'm using vscode 1.90.0 with C# Dev Kit extension on a Mac. How can I cycle through all the overloads in the hovering popup? as the screenshot, when I hover on a C# method, the popup  does not have a prev/next to allow me navigate to another overload. Is there any setting to enable this?
![image](https://github.com/microsoft/vscode-dotnettools/assets/1488256/9c5eab34-a88f-4f50-88e1-f2aa3ead8b37)

**Comment by webreidi** [comment]
@mikadumont Can you answer this question?

**Comment by webreidi** [comment]
@pinkli I haven't been able to find a way to navigate once it is already typed but while typing, and IntelliSense comes up, press "(" and it will prompt you for the overloads. You can then navigate through the overloads using the arrow. 

https://github.com/user-attachments/assets/8b40d549-9d82-4836-ad85-fbe7c0ab0e50

@arkalyanms is there any way to navigate the overloads once it is already typed?

**Comment by pinkli** [comment]
yes, we can nagivate through while typing the code, but can not once it's done. I guess it'll be much helping if we can do it, greately help to understand and review the writen codes.

**Comment by webreidi** [comment]
Agreed, that would be of great help. We'll look into what options we have available for doing that with VS Code libraries.

**Comment by dibarbet** [comment]
tracking on the C# ext side - https://github.com/dotnet/vscode-csharp/issues/7641

Note - this is also not supported in VS Windows.
