### ISSUE TITLE
Problems to install .NET SDK

### ISSUE THREAD

**Issue by DaniePieters** [microsoft/vscode-dotnettools#1232]
### Describe the Issue

I just installed the  .NET SDK on my laptop, but when I start Visual Studio Code and type dotnet --version in a new terminal window, it replies:

The command could not be loaded, possibly because:
  * You intended to execute a .NET application:   
      The application '--version' does not exist. 
  * You intended to execute a .NET SDK command:   
      No .NET SDKs were found.
It therefore appears that Visual Studio Code does not detect the .NET SDK which is needed to run C# code.

Can somebody please assist me?

Thank you!

**Comment by nagilson** [comment]
Can you follow the walkthrough page and try installing the SDK thru it to see if it helps
?

**Comment by DaniePieters** [comment]
Thank you for your advice, Noah. I shall try it.

 

Regards

D

**Comment by nagilson** [comment]
Thank you, are you still experiencing any issues or is there something I can help with? :)

**Comment by DaniePieters** [comment]
Thank you for your enquiry Noah.

No, I came right and I am not experiencing any issue any more.

Kind regards
Danie Pieters

**Comment by nagilson** [comment]
Closing since the user has reported it as resolved! Thank you.
