### ISSUE TITLE
[BUG] C# Dev Kit not working well

### ISSUE THREAD

**Issue by elir-castro** [microsoft/vscode-dotnettools#1240]
### Describe the Issue

since 14/06/2024 i'm having a lot of issues running .net aplications in vscode using the dev kit c# v1.7.27

some time my imports just apear like is not being used

![image](https://github.com/microsoft/vscode-dotnettools/assets/63364180/03109fe0-f331-4c65-b10c-21ff9023d177)

I can't see definitions anymore
![image](https://github.com/microsoft/vscode-dotnettools/assets/63364180/e7972556-fc42-4840-b0ad-e17b73d7c930)

and i'm having a lot of problem to build the project. there was some update that just break everything, is just me?

### Steps To Reproduce

just instal vscode 1.90.2 and C# Dev Kitv1.7.27 and try to write some code in a project, everything just not work :D

### Expected Behavior

the same it was in 1.6.8 devkit

**Comment by SimonLindgren1** [comment]
I'm having same problem. Been a struggle to get the imports to work correctly last couple of days.

**Comment by elir-castro** [comment]
I Had to downgrade c# extension and .Net extension to 1 month ago, to resolve.

.Net Install Tool 2.0.5
C# 2.30.28 

After you downgrade open some c# code and wait a couple of time to it work again, I hope you solve too, this problem is soo annoying, lost 3 days work solving this...

**Comment by tmeschter** [comment]
@elir-castro When you say you have problems building the project, how are you starting the build, and can you provide more details on what is going wrong?

Also, if you see this issue again, could you please provide the contents of the "Project" and "Nuget" output windows?

**Comment by elir-castro** [comment]
i am not having problem running the aplication, my bad. it's a intelisense problem. but it solved downgrade c# and .net install tool.
