### ISSUE TITLE
The **XAML Hot Reload** feature does not work when debugging on Android devices.

### ISSUE THREAD

**Issue by Calichi** [microsoft/vscode-dotnettools#1241]
Type: <b>Bug</b>

**The changes are not applied after editing and saving a XAML file**, even when pressing the "Fire" button. The `.NET Hot Reload` **output** displays **_No changes were found._**

Extension version: 1.0.6
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.94GB free)|
|Process Argv|--crash-reporter-id 19165560-5fd2-482a-994e-35e72cd32781|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31082723

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2113764">2113764</a>

**Comment by BretJohnson** [comment]
@Calichi - FYI, XAML Hot Reload should work as you type. Saving the file shouldn't be necessary. And the "No changes were found" message actually refers to C# changes, not XAML changes, though we're working on improving that message to make it more explicit. FYI on all that.

As for the core issue here, can you provide more info. If you create a new, simple MAUI project (bring up the command palette / .NET: New Project... / .NET MAUI) does Hot Reload work there? Does it fail for all pages in your app or just some? When it fails, can you please share the contents of the `.NET Hot Reload` output pane and the `Debug Console` app output, especially searching for Hot Reload related errors (look for `Hot Reload`) in the app output.

Thanks. I would like to get this issue tracked down & working, both for you and for others who may run into the same problem, whatever it is.

**Comment by Calichi** [comment]
I am attaching a video divided into two parts of the entire process. **The overlay of the mobile device screen is not synchronized with the video, but it was recorded during the demonstration**.

https://github.com/microsoft/vscode-dotnettools/assets/45352964/2a88cbe2-6891-43d2-aae6-425da68cdb23


https://github.com/microsoft/vscode-dotnettools/assets/45352964/d67c5dc1-54ea-4f1d-ac5c-5bb681e69abb

**Comment by BretJohnson** [comment]
> @BretJohnson - Note also, there is an instruction: ‘_Start sdb and execute…_’ What is `sdb`? Could there have been a typo when trying to write `adb`, or is it some tool that I am unfamiliar with? I have already conducted a search, but I cannot find anything related to it

Where do you see that message? Can you paste the full message or a screenshot maybe?
And thank you for the videos - they are indeed helpful.

**Comment by Calichi** [comment]
@BretJohnson - The message is located in the yellow-highlighted area, but it is in **Spanish**.
![Bug_start_sdb](https://github.com/microsoft/vscode-dotnettools/assets/45352964/558b3537-991b-4500-b764-9bc0fe47335d)

**Comment by BretJohnson** [comment]
> @BretJohnson - The message is located in the yellow-highlighted area, but it is in **Spanish**. ![Bug_start_sdb](https://private-user-images.githubusercontent.com/45352964/344845346-558b3537-991b-4500-b764-9bc0fe47335d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODM3OTEsIm5iZiI6MTcxOTg4MzQ5MSwicGF0aCI6Ii80NTM1Mjk2NC8zNDQ4NDUzNDYtNTU4YjM1MzctOTkxYi00NTAwLWI3NjQtOWJjMGZlNDczMzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxMjQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNGViOTk4M2FhZjkyNTllYmMyMTdiNmIxZmFiZjE1YWY3NWY5ZWU1NzUwMTcxYjEyZmQwNjYzY2EwMzBiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36OmleYVoUFRtACFt8M5yvDCi2fgof0vMkVe_i5_qVc)

Ah, gotcha. Below is the English version of that UI. `sdb` isn't a typo, it refers to Android debugger technology. Though as I read that message it does seem confusing, it kind of reads like an instruction to the user on something they should do rather than an explanation of what the build/launch process is doing automatically to connect the debugger. I'll create a bug on that, suggesting the message improved. Thanks for pointing it out.

![image](https://github.com/microsoft/vscode-dotnettools/assets/245892/ad3b3613-b976-40ef-9228-dc244ce91d6f)

**Comment by BretJohnson** [comment]
But as for your issue, the `Hot Reload initialization error: No HotReload connection specified` message in the app launch output indicates a problem. XAML Hot Reload won't work if that message shows up. Now to figure out why - what's going wrong that triggers that.

Can you please try this:
1. `cd "C:\Program Files (x86)\Android\android-sdk\platform-tools"` (assuming your android sdk is installed there, which it normally is)
2. See what the output of `.\adb.exe shell ls -l /data/local/tmp` is. There should be an `ide-launchenv.txt` file in that directory, which is how environment variables, like the one used for the HotReload connect info, get passed to the Android app at launch time. If something went wrong creating that file - perhaps a permission issue with the Android device/emulator in question - that would cause the symptoms you see.

**Comment by BretJohnson** [comment]
And what kind of Android device is this? It's a physical Android device, not an emulator, right?
Can you try with an emulator image, like say a Pixel 7 emulator, and see if that works.
My guess is that there's some security issue (or possibly a non security device specific issue) that causes using adb to create the `/data/local/tmp/ide-launch-env.txt` file to fail on that device. If that's the case, I'd like us to handle that scenario better, though I'm not sure how yet. In any case, let's see what you find with the above checks & go from there. Thanks for your help tracking this down.

![image](https://github.com/microsoft/vscode-dotnettools/assets/245892/7e59f1ce-a31e-422d-892d-bddb809c5848)

**Comment by Calichi** [comment]
Indeed, **I am using a physical mobile device** to debug my applications, and **I have no intention of doing so on an emulator**. For the same reason, I am seeking assistance. Perhaps you could explain how executing on the emulator could help resolve the issue with the physical device? Or what is their relationship?

It’s worth mentioning that I have debugged on the `Windows` target, and `Hot Reload` works perfectly.

Perhaps it’s not relevant, but I usually work with `Visual Studio Community`, and everything works perfectly there. I wanted to bring my project to `VS Code` because I heard that it now supports `Hot Reload` on `Android` devices, and honestly, it’s more convenient for me to work in `VS Code`.

### _Finally, I am fully willing to provide any information you need to help resolve this issue._

**Comment by Calichi** [comment]
**This is the result** of executing the mentioned command, **but on the physical device**, not on an emulator. As you can see, **the mentioned file appears** `ide-launch-env.txt`.

![Captura de pantalla 2024-07-02 180438](https://github.com/microsoft/vscode-dotnettools/assets/45352964/649afc86-3763-48dc-ab37-945197ac80f6)

**Comment by BretJohnson** [comment]
@Calichi - Thanks for that info. Can you also share the results of running this adb command (with the physical device connected): `.\adb.exe shell cat /data/local/tmp/ide-launchenv.txt` 
And the file name looks correct for you - it should indeed be `ide-launchenv.txt`. The issue must be something else.

As for running on an emulator, I only mentioned that to better understand what scenarios do & don't work for you, as a troubleshooting step. But you don't need to do it - the adb output above is the most useful. And indeed my goal, as is yours, is figure out why this isn't working for you, with your device, and fix things so it does (probably by making some change in our code, though maybe there's a workaround in advance of that).

Thanks again for your help tracking this down. We're getting closer.

**Comment by Calichi** [comment]
## Here's requested execution's result for the given command:

<br/>

![Captura de pantalla 2024-07-02 212011](https://github.com/microsoft/vscode-dotnettools/assets/45352964/42f00e2e-7b45-4150-a445-15c8f8d1d8cf)

**Comment by BretJohnson** [comment]
@Calichi Thanks. That looks valid. As the next check do you think you can add a little code to your app to get the value of the `RuntimeInformation.OSDescription` property, running that on your Android device (like in the debugger) and see what it returns. The current code checks if `RuntimeInformation.OSDescription.Contains("android")` in order to determine if it's an Android device - if that check returned false for some reason, it would result in the behavior you see. That check may not be exactly right, for all devices, and need to be updated - but we'll see, based on what your device reports. Thanks again.

**Comment by Calichi** [comment]
@BretJohnson 

## Here's the result.

![Captura de pantalla 2024-07-02 215019](https://github.com/microsoft/vscode-dotnettools/assets/45352964/8a222054-76bd-4b74-af33-6402927c84c9)

**Comment by Calichi** [comment]
@BretJohnson 

## More information.
![Captura de pantalla 2024-07-02 221051](https://github.com/microsoft/vscode-dotnettools/assets/45352964/906fa394-3a65-41b1-9f57-9ede6b64c737)

**Comment by BretJohnson** [comment]
Thanks. So that's the issue. And this device is an OPPO A15 (https://www.oppo.com/en/smartphones/series-a/a15/specs/), right? It looks like the OS there is `ColorOS 7.2 based on Android 10`, so Android with some customizations. In any case, I'll look to update the code for a better check on whether running on Android, avoiding RuntimeInformation.OSDescription. In the meantime, I can't think of any good workarounds, other than say using an emulator temporarily for Hot Reload. But I'll fix it. We publish weekly pre-release channel updates of the extension. Once the bug here is noted as fix, look for an update published to pre-release there that contains the fix. So you shouldn't have to wait too long. Thanks again very much for your help tracking this down.

**Comment by Calichi** [comment]
# You’re welcome! Thank you for your attention and follow-up. I’ll wait for the update

**Comment by BretJohnson** [comment]
I'll update this issue to mark it fixed, once we have a fix in place & we'll close the issue after the fix is released publicly.

**Comment by Calichi** [comment]
Ok.

I can post another bug about debugging `MAUI apps` on my `Android` device, but this one occurs in both `VS Code` and `VS Community`.

**Comment by BretJohnson** [comment]
> @BretJohnson
> 
> Ok.
> 
> I can post another bug about debugging `MAUI apps` on my `Android` device, but this one occurs in both `VS Code` and `VS Community`.

Sounds good. For issues that happen in both VS Windows and VS Code, I'd suggest reproducing it in VS Windows, then create a feedback ticket (Help / Send Feedback / Report a Problem). Feedback tickets include logs which sometimes help. And note on the feedback ticket that you also see it on VS Code. Reporting a separate VS Code bug here, in addition to the VS Windows feedback ticket, shouldn't normally be necessary, but on the other hand it couldn't hurt and will raise visibility so feel free to do that if you'd prefer.

**Comment by Calichi** [comment]
# Once again, thank you very much!

**Comment by ziomek64** [comment]
For me XAML hot reload works in emulator but doesn't in real device too

**Comment by BretJohnson** [comment]
This is fixed, in C# extension version 2.39 (and later), currently published to the pre-release channel.
@Calichi - After updating to the latest prerelease version of the C# extension, if you still see any problems let us know.
@ziomek64 - Same for you. Thanks.

**Comment by BretJohnson** [comment]
This is fixed, in C# extension version 2.39 (and later), currently published to the pre-release channel.
@Calichi - After updating to the latest prerelease version of the C# extension, if you still see any problems let us know.
@ziomek64 - Same for you. Thanks.

**Comment by BretJohnson** [comment]
This is fixed, in C# extension version 2.39 (and later), currently published to the pre-release channel.
@Calichi - After updating to the latest prerelease version of the C# extension, if you still see any problems let us know.
@ziomek64 - Same for you. Thanks.

**Comment by Calichi** [comment]
@BretJohnson 

This issue seems to be resolved because I’ve been able to debug on the device. However, **hot reload** doesn’t load on various occasions **_during the start of debugging_**, and it shows me these messages:

**Hot Reload initialization error: Launch environment file was last updated 141 seconds ago and is expired**
**Hot Reload initialization error: No HotReload connection specified**

**Comment by Calichi** [comment]
@BretJohnson

I understand, it took me a while to realize. Would it be possible to **add this parameter to the MAUI configuration in VSCode** so that one can set their own timeout, Since the compilation process **sometimes takes more than 200 seconds**. I apologize for the issues.

### Postscript
    "I’ll be upgrading my dinosaur soon"
