### ISSUE TITLE
[BUG] Can't debug on physical device twice

### ISSUE THREAD

**Issue by softlion** [microsoft/vscode-dotnettools#1249]
### Describe the Issue

I'm having trouble starting debugging on a physical device twice.  
I have to delete the app from the device and then start debugging again.  
This works but breakpoints are not hit - which may be another issue.

However, if the app is already deployed and I start debugging, the app builds and deploys again, starts with the splash screen, then waits before being killed by iOS after 12 seconds.

This issue occurs both on a Mac with VS Code and on Windows with Visual Studio and a Mac agent. My device is an iPad Pro connected via Wi-Fi.

I've also tried forcing the IP and port with the following code in the csproj file:
```xml
<PropertyGroup Condition="'$(TargetFramework)'=='net8.0-ios' AND '$(Configuration)' == 'Debug'">
    <MtouchExtraArgs>--server=192.168.10.101:9000</MtouchExtraArgs>
    <IOSDebuggerPort>9000</IOSDebuggerPort>
</PropertyGroup>
```

I've also created a new default maui iOS app with `dotnet new` and experienced the exact same behavior.

### Steps To Reproduce

1. Create a maui app: `dotnet new mauiapp -ap eu.yourcompany.deploybug -tp Ios -o DeployBug20240627`
2. Open VS Windows and connect it to a mac agent (using the latest stable versions of MacOS and xcode)
3. Start debugging, interact with the app
4. stop debugging
5. Start debugging again.
6. Observe

### Expected Behavior

6. you can interact with the app

Instead the app is killed after being 12s on the splash screen.

### Environment Information

- Windows 11 and MacOS
- sdk 8.0.302
- maui 8.0.61
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2137257">2137257</a>

**Comment by emaf** [comment]
@softlion are you still able to reproduce this using the latest version of C# Dev Kit (v.1.10.18) and .NET MAUI (v1.3.29) extensions?

If you are facing this issue from Visual Studio, please report it from inside VS.
