### ISSUE TITLE
unity extension failing to register itself with unity as a script editor

### ISSUE THREAD

**Issue by alanbork** [microsoft/vscode-dotnettools#1253]
Type: <b>Bug</b>

Following the instructions to enable it breaks down at the stage of telling unity 2022.3.33f1 to use the installed copy of vscode as the external script editor; it's simply not listed as an option in the drop down menu in unity. 

Extension version: 1.0.2
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4350 Quad-Core Processor             (4 x 4214)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.20GB free)|
|Process Argv|H:\\unity\\cube maze\\Assets\\Scripts\\PlayerMovementController.cs --crash-reporter-id abc2e3a1-6858-4133-b94e-3838d4b737ea|
|Screen Reader|no|
|VM|44%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

**Comment by alanbork** [comment]
I figure it out - I had installed vs code in a nonstandard location, not realizing that the unity extension just uses hard coded paths rather than environment variables or path to find the VS code install - which I think counts as a bug. For future reference, you can add your own hard coded location on line 151 of VisualStudioCodeInstallation.cs of the visualstudio unity package, eg:

			foreach (var basePath in new[] {localAppPath, programFiles, "c:/apps/"})

**Comment by jbevain** [comment]
Glad to hear you've found a way to make it work! For non standard installations you can also manually browse to the code.exe and then the package will remember the location. Thanks!
