### ISSUE TITLE
[Question] C# dev kit License

### ISSUE THREAD

**Issue by IgnaJoe** [microsoft/vscode-dotnettools#1258]
Hi, I'm Ignajoe.

I have a question regarding the license for the C# Dev Kit in VSCode.

I currently have a license for Visual Studio Professional 2019, but since it does not support .NET 6 development, I am considering using the C# Dev Kit in VSCode for development.

I checked the license policy, and it seems that for company use, a Professional or higher license is required.

However, there is no specific version indicated, so I am asking for clarification.

Can we legally use the C# Dev Kit in VSCode for commercial purposes with a VS2019 Professional license?

For your reference, our company has over 100 employees and records more than $10 million in revenue.

Thank you.

**Comment by BretJohnson** [comment]
cc @webreidi

**Comment by timheuer** [comment]
@IgnaJoe The license you will need given your company circumstances is the subscription license. If you only have a perpetual license (meaning you have basically purchased a non-subscription license only for one version) that does not apply per our license terms.  https://marketplace.visualstudio.com/items/ms-dotnettools.csdevkit/license and the eligible entitlements: https://aka.ms/vs/eligible-entitlements
