### ISSUE TITLE
String interpolation Null Reference Exception when debugging in VS Code MacOS

### ISSUE THREAD

**Issue by Jomontalvo** [microsoft/vscode-dotnettools#1260]
Type: <b>Bug</b>

1. Start Api project c# en debug mode.
2. In Class Library set a breakpoint before the sentence:
var str = $"file{name}{id}.txt";
3. When press step by step button throws an exception:
System.NullReferenceException: Object reference not set to an instance of an object. 

Extension version: 1.7.27
VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.00GB free)|
|Process Argv|--crash-reporter-id 5f0d65fa-44fa-4c71-8413-1332b7c18d03|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by WardenGnaw** [comment]
@Jomontalvo Can you share a snippet of the function that you are trying to set the breakpoint in?

**Comment by WardenGnaw** [comment]
I am going to close this for now as there has been no additional info. Feel free to re-open if you have an example thats hitting this issue.
