### ISSUE TITLE
Failed to install MSI package 0x80070643

### ISSUE THREAD

**Issue by chunx1ng** [microsoft/vscode-dotnettools#1263]

**Comment by webreidi** [comment]
@chunx1ng can you please provide more details about what you were doing when you received this message? Is this on extension install or were you doing something else?

**Comment by chunx1ng** [comment]
Sorry, I did not notice that I added this bug issue feedback in this site. 
The problem is that when I use the dotnet installation package extension in VS code to install the .NET framework, it always come up an error 0x80070643 and the installation is failed. Finally, I had to go to the official site of .NET framework to download and install it manually. Then it succeeded and no error come up this time.

**Comment by nagilson** [comment]
Thank you for reporting this issue. May you please provide your .NET Installer log (scrub any personal data you do not want to share from it), which can be found at %temp%.
The file has a name like 'Microsoft_.NET_SDK*.log and should appear in recent files. The version you were trying to install will also be in the log name.

**Comment by nagilson** [comment]
@chunx1ng If you're still facing this issue, please attach the above log so we can help you.
