### ISSUE TITLE
Unable to see selected launch configuration from launchSettings.json in the UI

### ISSUE THREAD

**Issue by nlykkei** [microsoft/vscode-dotnettools#1264]
### Describe the feature you'd like

I would like to see the selected launch configuration in the UI after selecting one in `Properties/launchSettings.json` using `.NET: Select Launch Configuration` command in VS Code:

![image](https://github.com/microsoft/vscode-dotnettools/assets/14088508/fc6e893a-9ec8-4eb4-8dfa-cab2300dc672)

### Environment Information

VS Code: 1.91.0
C# Dev Kit: v1.8.12 (pre-release)

**Comment by smitpatel** [comment]
@nlykkei - You can see currently selected launch configuration in status bar like this
![Image](https://github.com/user-attachments/assets/ad8505af-5f24-4719-b090-47bc7b0f04f1)
