### ISSUE TITLE
Cannot select other projects after having selected a launch configuration for one of them in a solution

### ISSUE THREAD

**Issue by nlykkei** [microsoft/vscode-dotnettools#1265]
### Describe the Issue

I'm using a solution with multiple projects.

After having selected a launch configuration in `Properties/launchSettings.json` for one of the projects using `.NET: Select Launch Configuration` command in VS Code, I'm not able to change my selection to other projects. The selected seems locked, in that I can only choose launch configurations for the project initially selected:

![image](https://github.com/microsoft/vscode-dotnettools/assets/14088508/fc6e893a-9ec8-4eb4-8dfa-cab2300dc672)

Where does VS Code store the selected project and launch configuration? I cannot find it locally

**Comment by smitpatel** [comment]
Select Launch Configuration command allows you to select launch configuration for current startup project. If you want to change the project itself, use Select C# Startup Project command.
