### ISSUE TITLE
[BUG] .NET Core SDK cannot be located

### ISSUE THREAD

**Issue by Mamoun-M** [microsoft/vscode-dotnettools#1270]
### Describe the Issue

The .NET Core SDK cannot be located: Error running dotnet --info: Error: Command failed: dotnet --info /bin/sh: dotnet: command not found /bin/sh: dotnet: command not found . .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path

**Comment by webreidi** [comment]
@Mamoun-M can you ensure you've installed the .NET SDK. You can use the command palette (Ctrl+Option+P) and type .NET, you should see ".NET: Install New .NET SDK" as an option. This will bring up a new window that will allow you to install the latest version of the SDK.

**Comment by nagilson** [comment]
Let us know if you still have this issue.
