### ISSUE TITLE
[BUG] Default option `Use Controllers = true` does not work when creating API project.

### ISSUE THREAD

**Issue by TanvirArjel** [microsoft/vscode-dotnettools#1277]
### Describe the Issue

The default option `Use Controllers = true` does not work when creating API project. We need to change it to `false` and then again `true`. Then it works.

![image](https://github.com/microsoft/vscode-dotnettools/assets/14342773/37c5b738-09c5-4249-a9a6-a83ffc3fdc7c)

### Steps To Reproduce

Just create an API project with the default settings.

### Expected Behavior

As the default option is `Use Controllers = true` so, It should create a project with controllers.

### Environment Information

- OS: MacOS 14.5
- VS Code : Version: 1.91.0 (Universal)
- C# Dev Kit: v1.9.2 (pre-release)

**Comment by smitpatel** [comment]
@TanvirArjel - Thank you for reporting this bug.

**Comment by smitpatel** [comment]
The default value for some of the option which inverts the parameter from template wasn't correct.
After fixing it, this is how what default options are
![image](https://github.com/user-attachments/assets/88797717-4885-4b0e-8f2e-a00bdb0959e5)

**Comment by smitpatel** [comment]
Fixed in version 1.9.55
