### ISSUE TITLE
[SUGGESTION] Add a "Attach" option to the list of default debugging configurations for C#

### ISSUE THREAD

**Issue by dellis1972** [microsoft/vscode-dotnettools#1284]
### Describe the feature you'd like

Because you cannot use the launch.json as well as the default debug configurations at the same time. There should be an option to attach to an existing process in additon to the list of projects which is presented. 

Projects I work on are now deleting the launch.json in favor of this new defaults system. As a result I keep having to re-create the launch.json just so I can attach to an existing process. It is really incovinient. There are many senarios where attaching to an existing process is needed. If the plan is for people to not need a launch.json then that option should be provided.

To reproduce
* Open a C# project
* go to the Debugging tab
* Select default debug configurations
* Select C#
* See a list of available projects. No attach option is presented.

### Alternatives considered

You can work around by creating your own launch.json, but as mentioned some projects are now not allowing people to use that. 

### Environment Information

- OS : Mac/Windows/Linux
- v1.8.14

**Comment by WardenGnaw** [comment]
Attach can be found in the Command Palette by searching for `Debug: Attach to a .NET 5+ or .NET Core Process`

![image](https://github.com/user-attachments/assets/4aa75c4e-adbb-468c-8790-f5a9f9ad7bf2)

**Comment by dellis1972** [comment]
Ok good to know, Thansk for the clarification.
