### ISSUE TITLE
[BUG] Don't see solution explorer in dev container

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-dotnettools#129]
### Describe the Issue

When using the C# Dev Kit in a .NET dev container, I don't see the solution explorer [shown in docs](https://code.visualstudio.com/docs/csharp/debugging#_debug-with-solution-explorer).

### Steps To Reproduce

- Start with empty folder in VS Code Insiders
- Run command "Dev Containers: New Dev Container"
- Choose .NET template, latest .NET image (7.0)
- Build and reopen in container
- Install C# Dev Kit, switch to pre-release C# extension
- In container, run: ".NET: New Project", choose Console App
- New project files are added to File Explorer, but I don't see the Solution Explorer

![image](https://github.com/microsoft/vscode-dotnettools/assets/25310137/ef829ef5-3cf4-49cd-bba6-bb873073c903)

### Expected Behavior

To see the Solution Explorer shown in docs.

### Environment Information

VS Code:

Version: 1.80.0-insider (user setup)
Commit: 79c4092768e41b16fd823e80c874dbfafdc08f55
Date: 2023-06-13T05:21:23.732Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25387

OS: Windows 11 Insiders

**Comment by adrianvmsft** [comment]
@bamurtaugh I got it working, I had to install both C# and C# Dev Kit to the Dev Container (similar to screenshot above). Besides that:
- I added both to devcontainer,json using right click on the extension -> Add to devcontainer.json.
- I have them also installed locally
I am not sure if all these steps are needed though.

**Comment by Rajesh35hsp** [comment]
I am facing the same issue, tried relaod window as well as adding mentioned extensions to Dev container. please help.
