### ISSUE TITLE
[BUG] Does not load the project references

### ISSUE THREAD

**Issue by AndresGMD** [microsoft/vscode-dotnettools#1293]
### Describe the Issue

When I open if solution in VS code `code . -n` does not load the references, they remain inactive.

![image](https://github.com/user-attachments/assets/00d7fd88-67f2-4051-a5be-557a0fd1a58f)

### Steps To Reproduce

1. open power shell
2. cd path_to_solution
3. execute `code . -n`
4. Open any file

I always have to solve it in the following way every time I open the project:

1. open powershell
2. cd path_to_solution
3. execute `dotnet clean`
5. execute `code . -n`
6. in VS code terminal execute `dotnet build "path_to_solution/solution.sln --interactive"`

### Expected Behavior

When I execute  `code . -n`  all references are loaded automatically in VS code without restart it.

### Environment Information

**VS code:**
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Extension Version:**
C# Dev Kit V. 1.8.14

**Comment by smitpatel** [comment]
@AndresGMD - Can you share a repro solution?

**Comment by smitpatel** [comment]
Closing the issue as requested information is not provided and we are unable to investigate further.
