### ISSUE TITLE
[BUG] Microsoft.VisualStudio.Code.ServiceHost extremely high memory consumption [1.9.8]

### ISSUE THREAD

**Issue by MihaPro-CarX** [microsoft/vscode-dotnettools#1295]
### Describe the Issue

I'm working with a large Unity project. The solution contains from 129 to 301 projects, depending on the settings.
When upgrading to C# Dev Kit 1.9.8 (pre-release), the memory consumption of the Microsoft.VisualStudio.Code.ServiceHost process increased sharply:
![изображение](https://github.com/user-attachments/assets/7cdf6afa-91df-40f2-9c31-523ce3752289)

In the previous version 1.9.2 (pre-release) there was no such memory consumption:
![изображение](https://github.com/user-attachments/assets/229c864f-0d07-4f2d-8ffa-87d07efd5b3d)

### Steps To Reproduce

1) Open a large project via Unity in VSCode
2) Wait for all projects to be parsed
3) View the memory consumption of the Microsoft.VisualStudio.Code.ServiceHost process in Process Explorer

### Expected Behavior

The process does not consume gigabytes of memory.

### Environment Information

- OS: Windows 10
- VSCode: 1.91.1
- C#: v2.39.28 (pre-release)
- C# Dev Kit: v1.9.8 (pre-release)

**Comment by arkalyanms** [comment]
@AArnott is this different from https://github.com/microsoft/vscode/issues/192043?

**Comment by AArnott** [comment]
@arkalyanms I don't see any correlation between that issue and this one.
@MihaPro-CarX opened this bug at my request over at https://github.com/microsoft/vscode-dotnettools/issues/731#issuecomment-2240394392.

**Comment by MihaPro-CarX** [comment]
Version 1.10.4 still consumes a lot of memory
![изображение](https://github.com/user-attachments/assets/92ee395a-4401-4c6a-a692-c2351be202df)

**Comment by justonia** [comment]
Mem usage on a large Unity C# project:
![image](https://github.com/user-attachments/assets/94c8d6c2-d387-434d-a9a3-89bd4e68a651)

It's gotten bad enough that I upgraded to 96gb of RAM to cope.

**Comment by ookuro19** [comment]
I turned off the automatic updates for the plugins and VSCode, then rolled back the version, and it seems to be working temporarily.

vscode: 1.90.2
C#: v2.33.17
C# Dev Kit: v1.7.25
.NET Install Tool: v2.0.6
![img_v3_02dn_0b0c8eaf-06e2-4fe1-b71e-beb23bea0b7g](https://github.com/user-attachments/assets/5deafacc-06d4-470c-b865-458b98a7c7a0)

Before rolling back, it almost used up the entire 32GB of memory.

**Comment by MihaPro-CarX** [comment]
I only have the C# Dev Kit extension rolled back to 1.9.2, the rest of the extensions are the latest versions. Then there is no such memory consumption and I can work normally.

**Comment by MihaPro-CarX** [comment]
C# Dev Kit version 1.10.6 does not have such memory consumption! It seems the problem has been resolved.

**Comment by alexeygritsenko** [comment]
> C# Dev Kit version 1.10.6 does not have such memory consumption! It seems the problem has been resolved.

Sorry, but it is not so. Today I have the same problem on the C# Dev Kit version 1.16.6

![Image](https://github.com/user-attachments/assets/5b35f599-0aa1-44bc-bb32-9cc208a557bf)
