### ISSUE TITLE
[BUG] dotnet.exe child processes leak after closing VSCode

### ISSUE THREAD

**Issue by MihaPro-CarX** [microsoft/vscode-dotnettools#1296]
### Describe the Issue

When opening a project in VSCode, 8 dotnet.exe child processes are created. Moreover, 4 of them soon find themselves without a parent. And the other 4 remain children of the process: Microsoft.VisualStudio.Code.ServiceHost:

![изображение](https://github.com/user-attachments/assets/51c85cca-25c2-4b61-ab32-6a455d3cf759)

When I close VSCode, all 8 dotnet.exe processes remain in memory without their parent processes:
![изображение](https://github.com/user-attachments/assets/19837678-6068-4d14-89db-e835a184027a)

### Steps To Reproduce

1. Open C# porject in VSCode
2. Look in Process Explorer
3. When parsing projects is complete, close VSCode
4. Make sure there are eight dotnet.exe processes left in memory

### Expected Behavior

After closing VSCode, all child processes are closed and none remain in memory.

### Environment Information

- OS: Windows 10
- VSCode: 1.19.1
- C#: v2.39.28 (pre-release)
- C# Dev Kit: v1.9.2 (pre-release)

**Comment by arkalyanms** [comment]
This seems like a dup of https://github.com/dotnet/msbuild/issues/9922
