### ISSUE TITLE
[BUG] Unable to attach to debugger. Windows / Unity6

### ISSUE THREAD

**Issue by friken0** [microsoft/vscode-dotnettools#1297]
### Describe the Issue

trying to attach do debugger does nothing. It tries for a fraction of a sec, I see a little popup in upper right that vanishes. I tried adding the logfile to the launch.json but no file is ever created in workspace. Tried specific dir too and nothing is created so wherever that logging happens it's after the attempt gives up.. or never starts trying? Ideas of what to try?

### Steps To Reproduce

f5/run or "Attach to Unity" from command pallette.
split sec of progress bar and a popup that vanishes in upper right
nothing ever happens 

### Expected Behavior

It to work :) 

### Environment Information

Windows 11
Unity6 -- package Visual Studio, newest
VSCode newest version
VSCode Unity extension installed (which installs c# and C#devkit too). Set C# and C#Devkit to pre-release (tried release too)

**Comment by nlsdvl** [comment]
Out of curiosity, do you have the issue with Unity 2022 ? 

I have the debugger working fine with this config on Mac OS 14.0 (23A344):
- VSCode Version: 1.90.2 (Universal) - (is that 'newest' on your end ?) 
- VSCode Unity v1.0.2 - (is that 'newest' on your end ?)
- VSCode C# Dev Kit v1.9.55
- VSCode C# v2.39.29
- Unity 2022.3.34.f1

**Comment by jbevain** [comment]
@friken0 sorry for the delay processing this. Are you still hitting the issue?

Given that no log is produced, it sounds like an issue in how our debugger backend is started.

Is there any output in the `Unity` output panel?

<img width="718" alt="Screenshot 2024-08-12 at 2 01 40 PM" src="https://github.com/user-attachments/assets/36781b37-0e1c-4c17-944a-9134cb823008">

**Comment by jbevain** [comment]
Haven't heard back, closing this. Feel free to open a new issue if you're still having issues. Thank you!
