### ISSUE TITLE
[BUG] Improve C# Dev Kit Debugging Walkthrough

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-dotnettools#130]
### Describe the Issue

Following the steps in the [doc](https://code.visualstudio.com/docs/csharp/debugging#_debug-with-dynamic-inmemory-launch-configurations), I'm unclear if I should use the Run and Debug view or not when I'm using the C# Dev Kit.

I was thinking yes as it's mentioned in docs and in the getting started walkthrough:

![image](https://github.com/microsoft/vscode-dotnettools/assets/25310137/0af5dd72-f1bf-4927-8fc4-0efe2ad0fd50)

But based on the results and [some other info in docs](https://code.visualstudio.com/docs/csharp/debugging#_debug-with-launchjson), I'm not sure.

### Steps To Reproduce

1. Open Run and Debug view, see I don't have any launch configurations
2. Follow [steps in doc](https://code.visualstudio.com/docs/csharp/debugging#_no-launchjson) to select a C# launch config
3. Try using Run and Debug
4. I don't see the output of my console app

![image](https://github.com/microsoft/vscode-dotnettools/assets/25310137/a15a8667-c6b7-429d-8765-a650a1940499)

### Expected Behavior

I expected to see my console app's "Hello, World!" output in the terminal the same way I see the output when I use F5.

### Environment Information

I'm using a .NET dev container with the latest VS Code Insiders on Windows 11 Insiders.

Version: 1.80.0-insider (user setup)
Commit: 79c4092768e41b16fd823e80c874dbfafdc08f55
Date: 2023-06-13T05:21:23.732Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25387

**Comment by WardenGnaw** [comment]
Do you see the output in the `Debug Console` tab?

By default, the settings for output is set to the `internalConsole`. You can change this option in your User Settings.
See https://code.visualstudio.com/docs/csharp/debugging#_user-settings

**Comment by bamurtaugh** [comment]
Ah yes, I see it if I go to the Debug Console, thank you!

I think it'd be helpful to highlight that in the walkthrough and/or an FAQ section of the debug doc. Right now the walkthrough points me to docs and to open the Run and Debug, and just opening Run and Debug isn't sufficient to see my output.

![image](https://github.com/microsoft/vscode-dotnettools/assets/25310137/d7153a02-7588-4d75-9d8c-6b1c3fe628c5)

**Comment by WardenGnaw** [comment]
Ideally VS Code should focus on Debug Console if the `console` type is set to `internalConsole` or focus on `Terminal` if set to `integratedTerminal` or with `externalWindow` a popup for the output should show. But I can improve the docs on the walk through .

**Comment by bamurtaugh** [comment]
> Ideally VS Code should focus on Debug Console if the console type is set to internalConsole or focus on Terminal if set to integratedTerminal or with externalWindow a popup for the output should show.

@tyriar @connor4312 would this be a feature request for VS Code core? (tagging you both for the terminal and debugging aspect)

**Comment by WardenGnaw** [comment]
Added notes, `console` is our launch.json configuration option, but VS Code should get a `runInTerminal` request if we set it to `integratedTerminal`. If not it should default to showing the `Debug Console`.

**Comment by connor4312** [comment]
> VS Code should focus on Debug Console if the console type is set to internalConsole or focus on Terminal if set to integratedTerminal or with externalWindow a popup for the output should show.

This is already the case, but is configurable by users.

**Comment by bamurtaugh** [comment]
> This is already the case, and is configurable by users.

The original issue I filed is because VS Code stayed focused on the integrated terminal, though the output was set to Debug Console. I could manually change my focus to the Debug Console to see the output, which I didn't expect since I thought other extensions automatically changed my focus to the expected spot. But perhaps this is expected?

**Comment by Tyriar** [comment]
@bamurtaugh it's controlled by`debug.internalConsoleOptions`, I have it set to `"neverOpen"` so I'm just assuming it still works.

**Comment by bamurtaugh** [comment]
Thanks @Tyriar. Looks like mine is `openOnFirstSessionStart`, so maybe what happened is:

- I ran once and debug console opened
- I tried running again, and debug console didn't open because it wasn't my first session

**Comment by WardenGnaw** [comment]
In a newer version of C# Extension, you should be able to input ReadLine/Read with the Debug Console.

See https://github.com/dotnet/vscode-csharp/pull/6569
