### ISSUE TITLE
Control list not show properly in right-side at the control selection page

### ISSUE THREAD

**Issue by ValanArockiyaKiraswin** [microsoft/vscode-dotnettools#1300]
### Describe the Issue

I am using React in VS Code. I have a set of controls, and on the controls page, I want to display the names of the selected controls in a list on the right side of the page. The first control selection updates correctly, but when I add more controls, the list does not update properly. It only updates correctly when I navigate to the next or previous page. I need the right side to update correctly with the selected controls immediately after selection on the same page.

### Steps To Reproduce

I have a set of controls that include names, icons, descriptions, etc., which I want to display on the left side page. When a control is selected from the list on the left side, the selected control's name should be properly updated on the right side. This update should happen correctly each time a control is selected or unselected.

### Expected Behavior

I need the selected control names list to update correctly on the right side of the control page immediately after selecting a control.

### Environment Information

OS: Windows 11
VS code version : 1.91.1

**Comment by arkalyanms** [comment]
@ValanArockiyaKiraswin would you add some screenshots showing the problem?

**Comment by ValanArockiyaKiraswin** [comment]
![Controls namelist not update properly in right side](https://github.com/user-attachments/assets/f1243bbe-a94b-4bee-bdfe-c9df6fedab4e)


The checkbox should function as shown in the image. When a checkbox is checked, the selected control name should be updated on the right side. When the checkbox is unchecked, the control name should be removed from the right side. Additionally, when the "x" mark on the right side is clicked, the corresponding checkbox on the left side should also be unchecked.

**Comment by ValanArockiyaKiraswin** [comment]
The checkbox should function as shown in the image. Here are the detailed steps for its behavior:

1. **Checking the Checkbox:**
   - When a checkbox on the left side is checked, the name of the selected control should be added to the list on the right side.
   - The right side should update immediately to reflect the addition of the selected control name.

2. **Unchecking the Checkbox:**
   - When a checkbox on the left side is unchecked, the corresponding control name should be removed from the list on the right side.
   - The right side should update immediately to reflect the removal of the control name.

3. **Clicking the "X" Mark on the Right Side:**
   - When the "X" mark next to a control name on the right side is clicked, the corresponding checkbox on the left side should be unchecked.
   - The right side should update immediately to reflect the removal of the control name from the list.
   - Simultaneously, the left side should reflect the checkbox as unchecked.

This functionality ensures that the control names displayed on the right side are always synchronized with the checkbox selections on the left side, providing a solution for my requirement.

**Comment by phil-allen-msft** [comment]
@ValanArockiyaKiraswin , I believe I understand what functionality you are describing.  However, I'm not certain at what layer you are describing.  Are you looking to use React in VS Code to build an application (webpage or otherwise) that has this functionality?  Is that application built using C# or some other language?  Alternatively, is the application you are trying to build an extension for VS Code itself?

**Comment by ValanArockiyaKiraswin** [comment]
We have resolved this issue on our end, so we are closing this task now.
