### ISSUE TITLE
[BUG] .NET SDK Install failure

### ISSUE THREAD

**Issue by Brenda-ug** [microsoft/vscode-dotnettools#1304]
### Describe the Issue

failed to instal .net sdk

### Environment Information

Error : (DotnetCommandFailed)
Failed to download .NET 8.0.303-global~x64:
.NET Acquisition Failed: {"isError":true,"error":{"eventType":"DotnetNonZeroInstallerExitCodeError"},"install":{"installId":"8.0.303-global~x64","version":"8.0.303","architecture":"x64","isGlobal":true,"installMode":"sdk"},"type":5,"eventName":"DotnetNonZeroInstallerExitCodeError"}

**Comment by nagilson** [comment]
This is an error that occurs when the .NET Installer itself fails. When the error is reported, there should be an exit code with a message in the '.NET Install Tool' tab for VS Code in the bottom terminal. It also may ask you to collect an installer log file. May you please add some more info here?

**Comment by nagilson** [comment]
Please add the requested info if you still need help.
