### ISSUE TITLE
[BUG] Failed to download .NET

### ISSUE THREAD

**Issue by NabilEsprit** [microsoft/vscode-dotnettools#1306]

**Comment by tmeschter** [comment]
@NabilEsprit Could you update the title and description with the issue you are experiencing?

**Comment by webreidi** [comment]
Error : (WebRequestError) Failed to download .NET undefined: TIMEOUT: The request to https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/8.0/releases.json timed out at 600000 ms. This only occurs if your internet or the url are experiencing connection difficulties; not if the server is being slow to respond. Check your connection, the url, and or increase the timeout value here: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts

**Comment by nagilson** [comment]
Do you happen to have an unconventional proxy setup? If so, I'd follow the above link to see if it can be remedied by using the custom proxy setting.

**Comment by nagilson** [comment]
Please add the requested info if you still need help.

**Comment by hansarh** [comment]
I'm getting the same error. I'm using WSL Ubuntu 22.04 LTS but haven't done any additional proxy setup. Have internet connectivity from terminal and things like source control with remote github repos work

**Comment by nagilson** [comment]
May you file an issue on https://github.com/dotnet/vscode-dotnet-runtime? If we had a log file that would help figure out what's going wrong, potentially. You can also try to increase the timeout time as a workaround.
