### ISSUE TITLE
Second enum value added to list added as default

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1308]
Type: <b>Bug</b>

Okay...  This is completely bizarre.  

This is .net Maui on iOS.

**This issue does not occur in Visual Studio for Mac.  Only in VS Code**

I have three if statements checking for boolean values.  On each of those, I insert an Enum into a typed list.  The second enum value always inserts as the default value no matter which enum it is.  

I take the same code, switch the order of the if statements (along with the add) and the second one is always 0.

I'm attaching two screenshots.  The only difference between the two is the order of the if statements.  In both cases, the second value inserted into the list is 0 - which you can see in the popup.  I'm also printing the values of the boolean values and the integer equivalents of the enum values so that you can see which If statements are hitting and the values that should actually be inserted.

Nothing is being written to the console and there is no exception.  

UPDATE:  I updated to the latest version of the c# extension (v2.39.29) and the issue is still occurring.

![Screenshot 2024-07-24 at 1 11 13 PM](https://github.com/user-attachments/assets/7f6dab46-85fe-421d-83d0-1a03c93c11fb)
![Screenshot 2024-07-24 at 1 08 59 PM](https://github.com/user-attachments/assets/70f72d5c-efc2-4202-86e2-ac6d064a2497)

This is Visual Studio:

![Screenshot 2024-07-25 at 6 13 48 AM](https://github.com/user-attachments/assets/10d56197-7f85-4131-95d3-2a5d01f01fa3)

Extension version: 1.2.3
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:46.768Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|96.00GB (3.42GB free)|
|Process Argv|--crash-reporter-id 1618046c-b005-4c1a-89ae-cb627902572c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31082724

```

</details>

**Comment by emaf** [comment]
Hi, could you try updating to the latest version of the C# Dev Kit and .NET MAUI extensions?

Also, is VS Dbg enabled? You can check this from `Settings -> Extensions -> .NET MAUI -> Use VSDbg`

**Comment by emaf** [comment]
We are unable to investigate this issue further without the additional information requested. If you are able to provide more information, you can request the issue to be reactivated below.
