### ISSUE TITLE
[BUG] Solution Explorer does not show up

### ISSUE THREAD

**Issue by mwkcoding** [microsoft/vscode-dotnettools#1311]
### Describe the Issue

Related to #1133. This still does not work for me. Same case: existing solution does not show. If I create a new .NET project within vscode, it works. Only difference is that existing solution was made with VS2017

Solution header:
```sln
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.3.32929.385
MinimumVisualStudioVersion = 10.0.40219.1
```

### Steps To Reproduce

It's hard to make repro steps since VS2017 is no longer officially available for download. But I suppose the following _would_ do it

1. Create new solution in VS2017
2. Create any type of project (console app or web app)
3. Save project
4. Open folder in vscode
5. See "Solution Explorer" tab never shows up

### Expected Behavior

I expect, especially now that VS for Mac is being discontinued, that vscode is able to open **ANY** existing solution, no matter where it was created.

### Environment Information

- OS: Windows 11 Pro (23H2 22631.3880)
- VSCode:
> Version: 1.91.1 (system setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
- Extension version: `v2.1.1` (C# Dev Kit: `v1.8.14`, C#: `v2.39.29`)

**Comment by Michael-Eng** [comment]
@mwkcoding what kind of project is in the solution? Is it .NET Framework or .NET Core?

**Comment by mwkcoding** [comment]
@Michael-Eng There are a bunch of projects. All are upgraded to .NET Core from Framework. There was one that wasn't upgraded, but I have "deleted" it through VS which just removes it as a project in the solution, folder is still there though.

**Comment by mwkcoding** [comment]
After I had created the issue yesterday, I experienced that the Solution Explorer has started showing up, sometimes. All I did was reinstall (which I had done many times before which didn't work) and restart vscode 5 times.

**Comment by Michael-Eng** [comment]
The solution explorer should always show up (but it's at the bottom so not always easy to see it). 

Note that we do not show any .NET Framework projects in the solution explorer for C# Dev Kit.

**Comment by mwkcoding** [comment]
Noted.

After using the setup today, I think I have concluded that this was a weird bug that was fixed with a reinstall and a few restarts of vscode.
