### ISSUE TITLE
[SUGGESTION] Markdown in XML/Documentation Comments for tooltips

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode-dotnettools#1312]
### Describe the feature you'd like

Currently, tooltips on references to members, don't process Markdown in the comment being rendered, nor HTML elements like `<ul>`. This effectively doesn't provide minimal typography options for technical or legal text.

The following would be fixed by supporting Markdown, but for completeness. Also, currently, `<br />` is required for adding new lines.

### Environment Information

- OS: Win10
- VS Code Version 1.89.1
- Extension Version 1.3.6

**Comment by dibarbet** [comment]
Documentation comment syntax is defined by the language.  This suggestion is covered by https://github.com/dotnet/csharplang/discussions/891 / https://github.com/dotnet/csharplang/issues/2394
