### ISSUE TITLE
[SUGGESTION] Support C# Dev Kit install on Winget/Winget configuration files

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#1313]
### Describe the feature you'd like

Ability install C# Dev Kit using Winget. Having commands like `winget install vscode-csharp-devkit` and ability to add C# Dev Kit into a Winget configuration file

**Comment by AArnott** [comment]
Please file this issue as feedback for VS Code. There is absolutely nothing unique about the C# Dev Kit extension to warrant creating winget support for it except as a general purpose VS Code feature.
