### ISSUE TITLE
[BUG] customRequest stackTrace does not return correct value

### ISSUE THREAD

**Issue by K0IN** [microsoft/vscode-dotnettools#1316]
### Describe the Issue

Calling `debug.activeDebugSession.customRequest('stackTrace')` fails with ```message =
'Incorrect format of stacktrace message.'
name =
'CodeExpectedError'```

![image](https://github.com/user-attachments/assets/d668946b-73e9-474b-af74-6a4cd8c94178)

Left - example extension that wants to request the stack trace 
Right - example code to debug.

1. 

### Steps To Reproduce

1. Start a debug session
2. Inside an extension, use debug.activeDebugSession.customRequest('stackTrace', [...])
3. Error gets thrown.

Example Extension code:

```typescript
export function activate(context: ExtensionContext) {
  debug.onDidChangeActiveStackItem(async () => {
    try {
      const stack = await debug.activeDebugSession?.customRequest('stackTrace', { threadId: debug.activeStackItem?.threadId ?? 1 });
      console.log(stack);
    } catch (error: any) {
      window.showErrorMessage("Error " + error);
    }
  });
}
```

### Expected Behavior

I can query the stack trace without issues.

### Environment Information

Windows (wsl/ubuntu and native)

**Comment by WardenGnaw** [comment]
Moving to vscode-csharp as this is an issue with the debugger DAP request.
