### ISSUE TITLE
ERROR WHILE INSTALLING .NET (SDK) extension for VS CODE

### ISSUE THREAD

**Issue by ARIST69** [microsoft/vscode-dotnettools#1319]
### Describe the Issue

ERROR WHILE INSTALLING .NET (SDK) extension for VS CODE

### Steps To Reproduce

Windows 11

### Environment Information

Windows 11

VS code version 7.0.410

.NET SDK version 8.0.303

**Comment by nagilson** [comment]
Hey @ARIST69, which error are you running into? May you please paste the results of the terminal / failure in here?
