### ISSUE TITLE
Create controller file

### ISSUE THREAD

**Issue by thomasluizon** [microsoft/vscode-dotnettools#132]
Type: <b>Feature Request</b>

On the solution explorer, when i click create file it shows a lot of templates like MVC Razor component, Class, Interface, etc. But it doesn't show the Controller and API Controller option, and it's a very useful template, please create the Controller and API Controller template.

Extension version: 0.1.83
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by donsn** [comment]
+1 for this please

**Comment by smitpatel** [comment]
Fixed in version 1.9.55
