### ISSUE TITLE
Cannot start MAUI app on dotnet 8

### ISSUE THREAD

**Issue by achobanov** [microsoft/vscode-dotnettools#1324]
I have an existing project that I'm able to run from VS Code running on Windows, but not on MacOS. After a whole day of wrestling with MAUI stuff on dotnet 7, I've updated all projects to target net8 and now the project builds successfully, however it still fails to startup:

>launch: program '<project-path>/bin/Debug/net8.0-maccatalyst/App' does not exist. 

I'm pretty sure VS Code is looking at the wrong path, because the projects targets `maccatalyst`, which has subcategories. In this case the actual path where you can find the dlls is:
```
<project-path>/bin/Debug/net8.0-maccatalyst/maccatalyst-x64
```

I'm able to startup a fresh template MAUI solution no problem.

**Comment by emaf** [comment]
Do you have a launch.json file in your workspace?

Also, could you share the terminal output?

**Comment by achobanov** [comment]
@emaf I eventually got it to work. There were some leftover build errors, which aren't very obvious in VS Code so it took me a while to resolve all of them.
