### ISSUE TITLE
[BUG] .NET MAUI extension does not respect configuration param from launch.json

### ISSUE THREAD

**Issue by awattar** [microsoft/vscode-dotnettools#1326]
### Describe the Issue

Configuration param from launch.json is. not honoured - configuration is always `-p:Configuration=Release` as selected in the VSCode active configuration.

It also seems that `-p:AndroidAttachDebugger=true` is always added to the command line.

* For Debug configuration following command is run in terminal:
`*  Executing task: dotnet build -t:Run -p:Configuration=Release -f net8.0-android34.0 -p:AdbTarget=-s%20emulator-5554 -p:AndroidAttachDebugger=true` ...
* For Release configuration following command is run in terminal:
`*  Executing task: dotnet build -t:Run -p:Configuration=Release -f net8.0-android34.0 -p:AdbTarget=-s%20emulator-5554 -p:AndroidAttachDebugger=true`...

Related to https://github.com/microsoft/vscode-dotnettools/issues/1325 as app is killed immediately for Release config in emulator.

Also related to https://github.com/microsoft/vscode-dotnettools/issues/732

### Steps To Reproduce

1. Create new Maui app.
2. Create launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[Debug] .NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        },
        {
            "name": "[Release] .NET MAUI",
            "type": "maui",
            "request": "launch",
            "configuration": "Release",
            "preLaunchTask": "maui: Build",
        }
    ]
}
```

4. Select target device:
![image](https://github.com/user-attachments/assets/25a59ba2-c8d2-4197-b4dc-c8604a25c4c8)
5. Select Relese as active config:
![image](https://github.com/user-attachments/assets/52dd9b65-6b9f-490c-ab26-084a45c2485b)
6. Open Debug view.
7. Select '[Debug] .NET MAUI' from Dropdown.

### Expected Behavior

App is deployed to emulator with proper configuration.

### Environment Information

Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0

**Comment by mauroa** [comment]
Hi @awattar.
This is by design, since C# DevKit recently included the feature to select active configurations via UI.
From .NET MAUI, we disabled by default the usage of launch.json to specify configuration names, since we want the user to use the recommended way.
If you want to still use launch.json, you can go to the .NET MAUI settings in VS Code and enable this option:

![image](https://github.com/user-attachments/assets/ef06795e-33f0-41c5-b32d-6d6638a90c03)

Thanks

**Comment by awattar** [comment]
Fair enough. Thx.

Wouldn't touch this if the Release would work on Android emulator - https://github.com/microsoft/vscode-dotnettools/issues/732 - but it seems it will be also quickly sorted out.

**Comment by awattar** [comment]
@mauroa any chances to also have ability to pass runtime and platform arguments to address https://github.com/microsoft/vscode-dotnettools/issues/744 where RuntimeIdentifier csproj is ignored for non Maui apps.
