### ISSUE TITLE
[BUG] Setting "Automatically Sync With Active Item" should not switch panel

### ISSUE THREAD

**Issue by Elias-Graf** [microsoft/vscode-dotnettools#1333]
### Describe the Issue

I find the setting "Automatically Sync With Active Item" quite useful to create classes etc. at my current location. This is especially true given the lack of a "Focus Active File In Solution Explorer" command :stuck_out_tongue: .
But it is not useable, since it doesn't just apply when the explorer panel is open. Let's say I'm reviewing my files before committing them in the "Source Control" panel. This leads to the explorer panel being focused, for every file I try to view. The same thing happens, when clicking through Tests in the "Testing" panel.

### Steps To Reproduce

1. Open any panel that can reveal files in the editor, for example the "Source Control" panel.
2. Focus on an item.

### Expected Behavior

The "Explorer" panel should **not** be focused.

### Environment Information

- OS: `NixOS 24.11.20240727.b74`
- VS Code Version: `1.91.1`
- C# Dev Kit Version: `v1.8.14`

**Comment by Jxwoon** [comment]
A fix has been made to C# Dev Kit v1.9.55 - Release. Please try it out and let us know if the issue still persists

**Comment by Elias-Graf** [comment]
it seems to work as expected now, Thank you very much :)
