### ISSUE TITLE
[BUG] Error when trying to add a new C# file with a hotkey

### ISSUE THREAD

**Issue by schoenlDikon** [microsoft/vscode-dotnettools#1334]
### Describe the Issue

Hello,

Maybe i am doing something wrong or need to setup something but when i open the solution Explorer and then select a folder i am unable to add a new file using the Hotkey assignet to that function.

This is the error message
![image](https://github.com/user-attachments/assets/a753d48c-5609-44b2-938d-50731da8c429)

This is a problem because i am Using the Extension vim-motions to not use the mouse while coding. Its slowing down my workflow when i have to grab the mouse everytime i want to create a new file.

### Steps To Reproduce

0. If not done already assign a Hotkey to the following command: **.Net: Add New File..**
1. Open Solution Explorer 
2. Click on an Folder
3. Try to create a File with the hotkey

### Expected Behavior

The Create a file popup opens just like when clicking on the Button "create new file".

### Environment Information

Windows 11
VS Code Version: 1.92.0
C# DevKit Version 1.9.53 (pre-release) but that Problem also occurs in the current Release Version

**Comment by smitpatel** [comment]
When you right click in solution explorer and click "Add New File" command, vscode passes in the node information on which the command was called on. The extension you are using to set hotkey is skipping the node information on which command was invoked hence Add New File fails since it is not able to get the node information.
Is "Add New File" working when you right click on solution explorer node?

**Comment by schoenlDikon** [comment]
Yes Add New File is working on right click in the Solution Explorer. 

> The extension you are using to set hotkey is skipping the node information on which command was invoked hence Add New File fails since it is not able to get the node information.

I have the Hotkey defined in the Hotkeys Configuration of VSCode. I did not create a Hotkey for this in the Vim-Motion extension. I am not sure but there was a hotkey set for this in default and even that didnt work.

I disabled the Vim Extension and it still does not work and i get the same Exception

**Comment by smitpatel** [comment]
Looks like setting a keybinding vscode invokes the command without context. We added functionality to invoke add new file from command palette so keybinding would show same behavior once it is released.

**Comment by smitpatel** [comment]
This bug is fixed but not available in Aug release. Moving milestone.

**Comment by webreidi** [comment]
This is now available in v1.10.16
