### ISSUE TITLE
Ability to debug Unity app running on Android over USB 

### ISSUE THREAD

**Issue by nlsdvl** [microsoft/vscode-dotnettools#1339]
### Describe the feature you'd like

Debugging a Unity app in the editor or standalone player is working well for me, but I'm currently targeting Android and struggling with the workflow. When I run the 'Attach Unity Debugger' command, I don't see the android device being listed. It's otherwise showing up using adb, or in the Unity editor, and connected on USB. 

I resorted to using debugging over the air and configuring the device IP and port. However this solution has several shortcomings and is pretty frustrating:
- the port for debugging changes every time I restart my app, requiring me to manually update my launch.json
- the debugging over the air is proving unreliable. I suppose it would be more stable, but that might just be a different issue.
- when using a VPN (eg. in a country where internet is restricted, ...) the VPN has to be disabled for this solution to work. 

I feel I looked hard for it, maybe I missed some instructions in the VSCode Unity extension documentation, let me know if that's the case.

I'm developing on Mac currently, and happy VSCode user for several languages. Given that Visual Studio for Mac is being retired, I find this extension becomes quite essential to develop Unity apps on a Mac.

### Alternatives considered

Switching to another editor so that I can debug the app

### Environment Information

- OS: Mac OS 14.0 (Apple silicon)
- VSCode: 1.90.2 (Universal) 
- Unity extension: v1.0.2

**Comment by nlsdvl** [comment]
Thanks a lot for sharing this @tyler-s-hatch . That command is what I was trying to figure out after opening the issue and I can now effectively debug with the extension.

**Comment by jbevain** [comment]
Nice workaround. We'll definitely look at adding support for it natively though :)

**Comment by sailro** [comment]
Hello @nlsdvl and @tyler-s-hatch, we just released a new `1.0.3` version with built-in support for debugging Android players over USB on Windows, MacOS and Linux.

![Screenshot 2024-08-19 094100](https://github.com/user-attachments/assets/19f3bb4c-3cb2-4403-8543-234791cd2c6b)

**Comment by detzt** [comment]
Is there anything I need to configure for that new 1.0.3 feature to work?

The port forwarding workaround from tyler-s-hatch works for me. My launch.json therefore looks the same as his.
But when I start the regular debugging it does not ask "Select Unity Instance" and it does not find the AndroidPlayer (USB) instance.

**Comment by tyler-s-hatch** [comment]
@sailro Out of curiosity, would you be able share the approach that the extension uses to determine the port to forward? 

My workaround grepped the logcat log for the unity log line that contained the port, which felt like a hack, but I didn't know how else to do it. Just would be nice to have the more "correct" way to do that in my back pocket, if there is one.

**Comment by detzt** [comment]
Thanks for the response. Looking a bit deeper I found the "Attach Unity Debugger" command that is listed when you press Ctrl+Shift+P and this opens the Select Unity Instance dialog, where my Android device is listed successfully.
I expected it to show up in the "Run and Debug" view of VS Code. Is it not intended to be accessible from there?


In comparison to the workaround, the extension way of finding Unity processes is definitely more robust, since the "Starting Managed Debugger" line is often not included in the `adb logcat -d` output when the app is already running for some time.

**Comment by sailro** [comment]
> @sailro Out of curiosity, would you be able share the approach that the extension uses to determine the port to forward? Just pointing me to the relevant source file that implements that would be helpful, if it is publicly available.
> 
> My workaround grepped the logcat log for the unity log line that contained the port, which felt like a hack, but I didn't know how else to do it. Just would be nice to have the more "correct" way to do that in my back pocket, if there is one.

We `cat` `/proc/net/tcp` and we consider all running processes with a port >=56000 and <=57000 to be unity players.

You'll get something like this:
```
	  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
	   0: 00000000:C35B 00000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 29659 1 0000000000000000 99 0 0 10 0                      
	   1: 00000000:A8FB 00000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 29572 1 0000000000000000 99 0 0 10 0                      
	   2: 00000000:A95D 00000000:0000 8A 00000000:00000000 00:00000000 00000000  1001        0 29576 1 0000000000000000 99 0 0 10 0                      
```

We then use `adb` to forward the port like you do (but keeping the original one, so that you can have several devices/processes).

We are using this approach since 2018 for Tools for Unity running in Visual Studio.

**Comment by sailro** [comment]
> Thanks for the response. Looking a bit deeper I found the "Attach Unity Debugger" command that is listed when you press Ctrl+Shift+P and this opens the Select Unity Instance dialog, where my Android device is listed successfully. I expected it to show up in the "Run and Debug" view of VS Code. Is it not intended to be accessible from there?
> 
> In comparison to the workaround, the extension way of finding Unity processes is definitely more robust, since the "Starting Managed Debugger" line is often not included in the `adb logcat -d` output when the app is already running for some time.

We kept the same logic as in Visual Studio: F5 is for quick-attaching to the related **Editor** instance. For all other scenarios (local or remote players, misc.), we offer to use `Attach Unity Debugger`.

**Comment by detzt** [comment]
Okay, thank you for clearing that up :)
