### ISSUE TITLE
[SUGGESTION] Improve license details (subscription) in README

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-dotnettools#134]
### Describe the feature you'd like

Hi,

I would like to suggest a clarification about the licensing/subscription model of this extension to be available in the README file. Something similar to the one used in the extension’s announcement (https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/).

> Given C# Dev Kit builds on the same foundations as Visual Studio for some of its functionality, it uses the same license model as Visual Studio. This means it’s free for individuals, as well as academia and open-source development, the same terms that apply to Visual Studio Community. For organizations, the C# Dev Kit is included with Visual Studio Professional and Enterprise subscriptions, as well as [GitHub Codespaces](https://github.com/features/codespaces). For additional details see the [license terms](https://aka.ms/vs/csdevkit/license).

Sure, the user can simply look at the `License` link in the marketplace, but since the majority of extensions in the VS Code marketplace are free and/or open source, the peculiarity of this extension is important to address.

Thank you

### Alternatives considered

The marketplace could have a `subscription` or `paid` pricing, but unfortunately, only has `Free` available today. Similar request were already made both for VS Code and VS Marketplace repos

* https://github.com/microsoft/vscode/issues/90648
* https://github.com/microsoft/vsmarketplace/issues/21

### Environment Information

- OS: Windows/MacOS
- VS Code: 1.79
- Extension Version: 0.1.83

**Comment by timheuer** [comment]
FYI @webreidi we probably could close this as the README now bumps up the License section with a link to full terms as well.
