### ISSUE TITLE
[BUG] Test discovery fails for dotnet/roslyn

### ISSUE THREAD

**Issue by jaredpar** [microsoft/vscode-dotnettools#1342]
### Describe the Issue

Test discovery fails and the window is empty when using dotnet/roslyn. 

![image](https://github.com/user-attachments/assets/2348e6a1-245a-4f70-886c-eefab51842c8)

Automatic discovery is disabled in this repo because of the [testhost locking behavior](#1089). Even an explicit refresh (hit refresh button on test discovery) results in the window remaining empty. 

### Steps To Reproduce

1. Open dotnet/roslyn in the provided Dev Container
2. Observe Test Discovery is empty 
3. Explicitly refresh and notice it remains empty 

### Expected Behavior

Test list is populated.

**Comment by peterwald** [comment]
This has been fixed and will ship in the next pre-release after 1.10.4
