### ISSUE TITLE
[BUG] Test Discovery does not use a build from tasks.json

### ISSUE THREAD

**Issue by jaredpar** [microsoft/vscode-dotnettools#1343]
### Describe the Issue

When you click the _refresh_ button on the test discovery window it will run effectively 

```cmd
> dotnet build thesolution.sln
```

That means it effectively ignores any build task that you've setup in `tasks.json`. This is a problem because builds often need to customized to the current environment. Test discovery is essentially ignoring that configuration and assuming the default `dotnet build` is going to work. 

Consider dotnet/roslyn as an example. The solution, `Roslyn.sln`, includes a number of projects that are Windows only or .NET framework specific. Neither of these are supported when the VS Code environment is opened on Linux. This is generally fine because our `tasks.json` special cases Linux for build, ends up deferring to `Compilers.slnf` which has less Windows specific components. But Test Discovery can't be configured to use this and hence we end up building test assets that have no chance of executing on Linux. 

### Steps To Reproduce

1. Clone dotnet/roslyn
2. Open the Test Window
3. Hit Refresh

### Expected Behavior

The expected behavior is that it uses on of the build targets from tasks.json.

**Comment by peterwald** [comment]
We don't have a great way to trigger a build from tasks.json. In lieu of this, we've added two new experimental options `dotnet.testWindow.disableBuildOnRun` and `dotnet.testWindow.disableBuildOnRefresh`. If either these options are set to `true`, then the test window will not trigger a build when running or refreshing tests respectively. 

These settings delegates responsibility to the user to kick off a build when necessary so you can launch a custom build task, or whatever. I don't think this is an ideal solution, but it does provide flexibility to opt out of the project system build if it is getting in the way.

This feature will ship in the next pre-release after 1.10.4
