### ISSUE TITLE
[BUG] Blazor is not supported

### ISSUE THREAD

**Issue by wisamidris7** [microsoft/vscode-dotnettools#1348]
### Describe the Issue

Blazor is required for working in dotnet specially web

So It has to be supported what is this

![image](https://github.com/user-attachments/assets/e64bb98a-80a2-4de4-b7f0-5184496794d7)

And colors are not adjusted

![image](https://github.com/user-attachments/assets/5f081faa-89f4-4505-97ee-9b482a6f5811)

And partial c# to razors say there no OnInitialization And OnAfterRender
So It still not suppored and i was using visual studio 2022 but the problem it's very very slow
So I used vscode and it was fast but razor pages were not compiled

**Comment by wisamidris7** [comment]
I Installed these extensions

![image](https://github.com/user-attachments/assets/ad69022c-b2fa-4faa-ad6d-f122cf811658)

Also tired with this

![image](https://github.com/user-attachments/assets/b578ded0-ef08-4753-812f-409bae68939f)

**Comment by wisamidris7** [comment]
Try opening a big application like this https://github.com/neozhu/CleanArchitectureWithBlazorServer

Or Masa.Blazor library issues everywhere so so so laggy

**Comment by davidwengier** [comment]
Thanks for the report @wisamidris7, you definitely found the right extensions with the C# and C# Dev Kit, and Blazor is definitely supported in general, but obviously you're running into some issues. Would it be possible for you to attach the logs from the Razor tooling so we can investigate? In fact, if you run the "Report a Razor issue" command it should capture them for you, and include instructions for increasing the log level so we get as much info as possible.

![image](https://github.com/user-attachments/assets/7457ec55-0ff4-415a-809e-9404ef566eeb)

**Comment by wisamidris7** [comment]
Thanks but I came back for visual studio 2022 with laggy issues but it's my only way cause

IDE vs extension
Can't be compared
