### ISSUE TITLE
[BUG]  'Attach to .NET Core Process' will always fail until you open the debugger tab

### ISSUE THREAD

**Issue by nagilson** [microsoft/vscode-dotnettools#1350]
### Describe the Issue

I was trying to debug a .NET application using C# DevKit since I needed to debug on OSX. On Visual Studio, you can easily attach to a process with the process Id. 

The first time I opened DevKit, it failed to attach to the language server. I waited about 20 seconds and it started working. When I tried the command pallet command to do this in VS Code, I was easily able to find it which was good! Googling around led to this document. But using it was not so good.

https://code.visualstudio.com/docs/csharp/debugging#_attaching-to-a-process

When I hit enter, it does not ask me to enter / select from a set of process ids. That would be ideal. Instead, it just immediately fails with 'Must specify either processId or processName'

Ok, so cool. It brings me to the `launch.json` file. I try to set the `processId` and try again. It doesn't work. I try to set it in configuration. It doesn't work. I try to type in attach to process and it auto-populates this thing, which doesn't have processId, but I filled out some of the stuff it was asking for, then added a PID... still didn't work. This is not documented anywhere. For me to learn what I am supposed to do, I should not need to look at the code of the extension.

![image](https://github.com/user-attachments/assets/9022353c-3e99-4e8a-bd3f-757da73a01e8)

![image](https://github.com/user-attachments/assets/deba9eb1-a16d-4a82-9594-284413e28ae2)

I still don't know how I'm supposed to use this feature. I think improving the UX to allow entering the PID in the drop down or selecting from all .NET PIDS / typing your own would be awesome :)

### Environment Information

macOS, DevKit latest internal build.

**Comment by WardenGnaw** [comment]
@nagilson Can you share a gif of what is happening? There once you select the `Debug: Attach to a .NET 5+ or .NET Core Process` it should show a process listing like:
![image](https://github.com/user-attachments/assets/4e33b687-74c4-4e3e-b3a1-bd1b0a568dbf)


With the command palette you should not have to create a `launch.json`.

**Comment by nagilson** [comment]
Thanks @WardenGnaw! That would make a lot more sense and that looks great. That never shows up for me (I'm not pressing enter or anything like that.) Hopefully my comments weren't too scathing because that seems to stem from a confusion, haha.

Here's the vid... btw, the first time is slow, but the 2nd time I think it shows it better than it really doesn't ever pop up a diagloue.



https://github.com/user-attachments/assets/0b6e21c9-ed33-49f8-840e-b96a5eeb2b88

**Comment by WardenGnaw** [comment]
It seems like something is causing the process listing to hang. Can you run the following in your terminal and see it complete? 

```
ps axww -o pid=,flags=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c
```

**Comment by nagilson** [comment]
This command does complete and list all of the PIDs and such.

**Comment by nagilson** [comment]
So, this command palette only works if you use the launch debugger first. If you don't use it, it will always fail.
