### ISSUE TITLE
[SUGGESTION] Unity debugger: Debug decompiled code

### ISSUE THREAD

**Issue by rhys-vdw** [microsoft/vscode-dotnettools#1359]
### Describe the feature you'd like

I would like to be able to set breakpoints in code that is not from my project's Assets folder.

It seems there is an option `justMyCode` that would be disabled usually, but it is not supported by Unity debugger launch options.

### Alternatives considered

Rider

### Environment Information

Windows 11
VSCode 1.91
visualstudiotoolsforunity.vstuc 1.0.2

**Comment by rhys-vdw** [comment]
Oh... Okay, maybe I just don't understand how to do it. I do "go to definition" from a method and it shows a decompiled view of the file and any added breakpoints are "unverified" and don't catch.

Also, frustratingly, "go to definition" does not work _within_ this decompiled view, greatly limiting its usefulness. This was never an issue historically before recent tooling changes.

Does it sound like I have something wrong in my setup?

**Comment by jbevain** [comment]
Got it. No I think your setup is correct, but the Unity debugger doesn't support putting breakpoints in decompiled sources at the moment.

By Packages I thought you meant "Unity Packages" that are usually distributed with the source.

**Comment by jbevain** [comment]
@rhys-vdw also I'd encourage you to please file a bug at https://github.com/dotnet/vscode-csharp/ about the scenario where you want to be able to do `Go To Definition` in decompiled sources.

**Comment by rhys-vdw** [comment]
> By Packages I thought you meant "Unity Packages" that are usually distributed with the source.

Ah yes, I did not have csproj generation for packages enabled in Unity's "preferences > external tools", hence why "go to definition" was decompiling instead of taking me to the package cache.

Silly me!

**Comment by jbevain** [comment]
At this point the plan is to support debugging decompiled code when Unity moves to CoreCLR. Closing this for now as OP is able to debug package code which was the original intent.
