### ISSUE TITLE
Test Explorer not honoring rollForward

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-dotnettools#1372]
Type: <b>Bug</b>

Last week, a change was made to the test explorer to start honoring the version specified in the user's global.json. Unfortunately, it's not honoring `rollForward`, so if you don't have the exact version specified in the global.json installed, then you get the following error:

```
Created Test Controller
platform: linux arch: x64
unable to create test controller for c# extension: Error: SDK version 8.0.101 not found.
```

In my case, our global.json looks like this:

```json
{
  "tools": {
    "dotnet": "8.0.101",
    "runtimes": {
      "dotnet": [
        "2.1.30",
        "$(MicrosoftNETCoreBrowserDebugHostTransportPackageVersion)",
        "3.1.30"
      ]
    },
    "vs": {
      "version": "17.2",
      "components": [
        "Microsoft.VisualStudio.Component.VSSDK"
      ]
    }
  },
  "sdk": {
    "version": "8.0.101",
    "allowPrerelease": false,
    "rollForward": "latestPatch"
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "8.0.0-beta.24321.3",
    "Microsoft.Build.NoTargets": "3.7.0"
  }
}
```

And I had the following SDKs installed:

```
➜ dotnet --list-sdks
6.0.100 [/home/fred/.dotnet/sdk]
6.0.419 [/home/fred/.dotnet/sdk]
6.0.424 [/home/fred/.dotnet/sdk]
7.0.406 [/home/fred/.dotnet/sdk]
8.0.100 [/home/fred/.dotnet/sdk]
8.0.102 [/home/fred/.dotnet/sdk]
8.0.104 [/home/fred/.dotnet/sdk]
8.0.200 [/home/fred/.dotnet/sdk]
8.0.302 [/home/fred/.dotnet/sdk]
9.0.100-preview.3.24204.13 [/home/fred/.dotnet/sdk]
9.0.100-preview.5.24229.2 [/home/fred/.dotnet/sdk]
9.0.100-preview.5.24307.3 [/home/fred/.dotnet/sdk]
```

Extension version: 1.10.6
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 5.15.0-117-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3630)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|62.70GB (43.59GB free)|
|Process Argv|--crash-reporter-id c9f05a69-d019-464b-b1f2-b43e5fb75046|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571

```

</details>

**Comment by ocallesp** [comment]
Closing this issue as it is a dup of https://github.com/microsoft/vscode-dotnettools/issues/1436
