### ISSUE TITLE
[BUG] <title>Error : (DotnetCommandFailed) Failed to download .NET 8.0.401-global~x64: .NET Acquisition Failed: undefined

### ISSUE THREAD

**Issue by dzulfikarizqi** [microsoft/vscode-dotnettools#1376]

**Comment by AbhitejJohn** [comment]
@dzulfikarizqi : Could you please share what version of the extension you are seeing this error on?

**Comment by nagilson** [comment]
This should be fixed in version 2.1.5 of the .NET Install tool.
