### ISSUE TITLE
Test discovery broken in current pre-release build 1.10.6

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode-dotnettools#1378]
Type: <b>Bug</b>

1.  click "Switch to Pre-release" -- 1.10.6 (pre-release) is installed
2.  reload Window
3.  tests are not discovered

4.  click "Switch to Release Version" -- 1.9.55 is installed
5.  reload Windows
6.  test are discovered as expected

Extension version: 1.10.6
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (12.49GB free)|
|Process Argv|--folder-uri file:///d%3A/source/2010solutions/VisitingAngels/VisitingAngelsCorporateFrontend --crash-reporter-id c8e3650d-a133-42e9-901c-3aa8e8465629|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31118571

```

</details>

**Comment by AbhitejJohn** [comment]
@ocallesp : Could you please take a look?

**Comment by ocallesp** [comment]
@burtonrodman I was not able to repro it on my Windows machine.

Could you tell me if the issue reproes using latest pre-release v1.10.10 ?

**Comment by burtonrodman** [comment]
Release (1.9.55):
- error spam after razor file diff: yes
- C# xunit test discovery: working

Pre-release (1.10.10)
- error spam after razor file diff: NO errors (yay!)
- C# xunit test discovery: STILL BROKEN

![image](https://github.com/user-attachments/assets/481c56a3-3368-49b4-826e-074b1aef2755)

**Comment by burtonrodman** [comment]
`dotnet test` output:

  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\8.0.400-preview.0.24324.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https
://aka.ms/dotnet-support-policy [D:\source\MyCompany\MyProject\MyProjectCorporateFrontend\MyProjectCorporateFrontend.Tests\MyProjectCorporateFrontend.Tests.csproj]
  MyProjectCorporateFrontend.Domain -> D:\source\MyCompany\MyProject\MyProjectCorporateFrontend\MyProjectCorporateFrontend.Domain\bin\Debug\net8.0\MyProjectCorporateFrontend.Domain.dll
  MyProjectCorporateFrontend.Tests -> D:\source\MyCompany\MyProject\MyProjectCorporateFrontend\MyProjectCorporateFrontend.Tests\bin\Debug\net8.0\MyProjectCorporateFrontend.Tests.dll
Test run for D:\source\MyCompany\MyProject\MyProjectCorporateFrontend\MyProjectCorporateFrontend.Tests\bin\Debug\net8.0\MyProjectCorporateFrontend.Tests.dll (.NETCoreApp,Version=v8.0)
VSTest version 17.11.0-preview-24320-06 (x64)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - MyProjectCorporateFrontend.Tests.dll (net8.0)

**Comment by burtonrodman** [comment]
TESTING view in Release -- discovery takes less than 15 seconds
![image](https://github.com/user-attachments/assets/df293fd5-1086-41b9-9d4f-055b07f34ba4)

**Comment by burtonrodman** [comment]
@ocallesp if you can tell me how to collect any additional logs / useful information, I'd be happy to share.

**Comment by burtonrodman** [comment]
Note that I have a Workspace that spans 7 repositories each with 2-10 projects.

While the active solution is NOT in the repository containing the test project, the test project IS a part of the active solution:

![image](https://github.com/user-attachments/assets/a88245ac-d4f8-466d-9ac8-c569a6887bb7)

each solution folder above contains projects from the associated repository.  not all projects in each repository are a part of the solution -- this solutions references those projects required to make Aspire work across all web projects.

**Comment by ocallesp** [comment]
@burtonrodman could you provide the log at menu 'View' | 'Output' | 'C# Dev Kit - Test Explorer' for the scenario that is failing to detect tests ?

**Comment by burtonrodman** [comment]
```
Created Test Controller
platform: win32 arch: x64
unable to create test controller for c# extension: Error: SDK version 8.0.200 not found.
```

output of dotnet --list-sdks:
```
6.0.425 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
```

global.json:
```
{
  "sdk": {
    "version": "8.0.200",
    "rollForward": "latestMinor"
  }
}
```

**Comment by burtonrodman** [comment]
if i delete global.json, it discovers tests.  (for reference, I require global.json to select the SDK version for my Pipeline)

this makes me think that since I only have a pre-release version of the 8.0 SDK (not sure why... I've updated VS recently) that the global.json not allowing pre-release is preventing the selection of a suitable SDK version.

I'm installing 8.0.401 now and will update after reboot.

**Comment by burtonrodman** [comment]
The SDK version selection in the Test Explorer seems to be broken.  I have tried 8.0.200 with rollForward of latestFeature or latestMinor and neither works.

If I understand the docs correctly, 8.0.200 with latestFeature should select any non-prerelease higher feature band... this is NOT happening.

```
<html>
<body>
<!--StartFragment-->
latestFeature | Uses the highest installed feature band and patch level that matches the requested major and minor with a feature band and patch level that's greater than or equal to the specified value.If not found, fails.
-- | --


<!--EndFragment-->
</body>
</html>
```

**Comment by burtonrodman** [comment]
```
6.0.425 [C:\Program Files\dotnet\sdk]
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
8.0.401 [C:\Program Files\dotnet\sdk]
```

```
{
  "sdk": {
    "version": "8.0.200",
    "rollForward": "latestFeature"
  }
}
```

```
Created Test Controller
platform: win32 arch: x64
unable to create test controller for c# extension: Error: SDK version 8.0.200 not found.
```

**Comment by burtonrodman** [comment]
![image](https://github.com/user-attachments/assets/6ccc97d1-5c9c-4f8d-b0cb-3ac41c080eab)

**Comment by ocallesp** [comment]
If your issue is related to global.json, we are working on a fix for global.json.

The global.json issues was originally reported here -> https://github.com/microsoft/vscode-dotnettools/issues/1372

**Comment by burtonrodman** [comment]
i believe we can close this issue then.  thanks!
