### ISSUE TITLE
[BUG] .net install

### ISSUE THREAD

**Issue by mutho-knee** [microsoft/vscode-dotnettools#1383]
### Describe the Issue

I'm having trouble downloading .net 8

**Comment by AbhitejJohn** [comment]
@mutho-knee : Thanks for logging. Could you please share more details? Are you trying to use C# Dev Kit? It would be very helpful if you could share what your setup is and how you are trying to install .NET 8.

**Comment by nagilson** [comment]
Please let us know if you still face this issue. The newest version has a lot of improvements which has fixed issues.
