### ISSUE TITLE
Cannot go to symbol from decompiled code

### ISSUE THREAD

**Issue by nlykkei** [microsoft/vscode-dotnettools#1385]
### Describe the feature you'd like

It's possible to go to symbols in external code through decompilation **once**, but from there it's not possible to navigate further, neither to symbols in the same assembly or others.

It seems like C# Dev Kit is not processing these decompiled files.

<img width="1228" alt="image" src="https://github.com/user-attachments/assets/ad9e7333-3389-4684-93a2-bea807d850cd">

How can I navigate between decompiled assemblies?

### Environment Information

- VS Code 1.92.2 (macOS/arm64)
- C# Dev Kit v1.9.55

**Comment by dibarbet** [comment]
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5787, should be resolved in 2.41.26 prerelease or higher.
