### ISSUE TITLE
The setting dotnet.defaultSolution path is automatically updated with OS specific directory separators

### ISSUE THREAD

**Issue by bernhardschuller** [microsoft/vscode-dotnettools#139]
Type: <b>Bug</b>

The `dotnet.defaultSolution` setting is automatically changed without user intervention to using the current OS' specific directory separator.

There is no side effect from this, and the Solution gets loaded just fine. However, using Git, you get a change in the working directory which is not intended.

After setting this in Linux, and then opening in Windows, you get the following change in .vscode/settings.json automatically:
```
-  "dotnet.defaultSolution": "myProject/Project.sln",
+  "dotnet.defaultSolution": "myProject\\Project.sln",
```

Expected Behaviour is to leave the directory separator as is, or unifying the settings across different file systems, since VS Code apparently can already handle this being either `/` or `\\`.

Extension version: 0.1.83
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by alexrp** [comment]
In relation to #31, this modification shouldn't even be done if the workspace has no solution file.

**Comment by lifengl** [comment]
this should have been fixed a while ago.
