### ISSUE TITLE
[BUG] <title>in my own computer virus put me as a guest  and I can not download .net sdk in vscode 

### ISSUE THREAD

**Issue by Zel425** [microsoft/vscode-dotnettools#1390]

**Comment by AbhitejJohn** [comment]
@Zel425 : Thanks, could you share a little more on how we can help? It sounds like you are having issues with admin rights on your system which might not be tied to the install of .NET.

**Comment by nagilson** [comment]
Please let us know if you still face this issue. The newest version has a lot of improvements which has fixed issues.
