### ISSUE TITLE
[BUG] <title> Cannot create new project

### ISSUE THREAD

**Issue by uno2112** [microsoft/vscode-dotnettools#1396]
### Describe the Issue

When I try to create a new project, I get the error message "No installed .NET SDK was found on the computer." If it is installed, make sure it can be found through the PATH environment variable. C# Dev Kit does not work without a supported version of SDK. After installing the SDK, you need to restart the VS Code session or the computer. "
When i try to install the SDK it says hat its already installed

### Expected Behavior

New project tab opens

**Comment by smitpatel** [comment]
Can you run `dotnet --info` command in terminal window in VS code and share output of it? This error happens when we are unable to find the dotnet on path variable. Even if .NET SDK is installed but if it is not on path, C# dev kit won't function correctly.

**Comment by uno2112** [comment]
PS C:\Users\edwar> dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x86
  Commit:       5a400c212a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\
Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\
Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\
Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\
Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
PS C:\Users\edwar>

**Comment by smitpatel** [comment]
@uno2112 - As output says, there are no SDK installed on the machine. You only have .NET runtime installed. Please download and install .NET SDK and try again.

**Comment by smitpatel** [comment]
Closing as requested information not provided and we are not able to investigate further.
