### ISSUE TITLE
[BUG] I downloaded .net file but still its not showing up

### ISSUE THREAD

**Issue by Avarnsir** [microsoft/vscode-dotnettools#1398]
### Describe the Issue

I have downloaded it many time even did in some path clearance I have still the issue. I done everything with chatgpt and reddit, many more sites but still haven't solved that issue.

### Environment Information

macOS M3Pro

**Comment by nagilson** [comment]
May you provide the output from the terminal tab '.NET Install Tool' and 'C# DevKit'?

**Comment by Avarnsir** [comment]
I solved it it was lacking some packages when I reinstall by removing the previous package then it worked
