### ISSUE TITLE
VSCode says no projects are loaded when they are after a fresh project is created

### ISSUE THREAD

**Issue by mattleibow** [microsoft/vscode-dotnettools#1399]
Type: <b>Bug</b>

1. Create git repo on GitHub
2. Clone into folder
3. Open in VSCode
4. Create .NET project using command thingy
5. Try to run
6. Says there are no projects, but the UI says otherwise  
  ![image](https://github.com/user-attachments/assets/7d216df6-ce2a-4e42-bca2-b7f420836360)
7. Reloading windows fixed it

Extension version: 1.10.10
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13800H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.83GB (30.68GB free)|
|Process Argv|D:\\GitHub\\scorecard-day-nft-marketplace --crash-reporter-id 23da67c6-76b0-4059-9da1-43adf798610b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
fje88620:31121564

```

</details>

**Comment by emaf** [comment]
Fixed in the latest prereleae and release versions of both C# Dev Kit (1.11.4 or 1.10.16) and MAUI Dev Kit (1.3.26 or 1.3.29).
