### ISSUE TITLE
C# and XAML Hot Reloads don't work well when both enabled

### ISSUE THREAD

**Issue by mattleibow** [microsoft/vscode-dotnettools#1401]
Type: <b>Bug</b>

Working on a new maui app with 2 pages and Shell.

1. I was working on some XAML in a page (all good)
2. I decided I needed some C# changes, so enabled the C# hot realod and restart the app
3. Made some C# and XAML edits (still all good)
4. Accidentally pressed Ctrl+S in my XAML and the whole page just vanished and nothing I did could get it back
5. Restarted the app and all was good again, until I pressed Ctrl+S again in the XAML page
6. Disabled C# hot reload, but not all the hot reloads failed
7. Restarted the whole VSCode application to get it to work

Observations
* I think pressing save in a XAML page triggers something new as this is the new line that appears in the logs only if both hot reloads are enabled:  
  > XAML: MAUI full page reload: File changed: (`<project-name>`, `<page-name>.xaml`)
* Sometimes disabling the C# hot reload breaks all the hot reloads
* There are no logs to show the XAML agent is started/ready (only the C# agent says 'starting') so it was hard to know if things were working until the XAML page finally changed

Extension version: 1.10.10
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13800H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.83GB (27.08GB free)|
|Process Argv|--crash-reporter-id 23da67c6-76b0-4059-9da1-43adf798610b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564

```

</details>

**Comment by BretJohnson** [comment]
@mattleibow What is Ctrl-C mapped to for you? Something other than copy?

**Comment by mattleibow** [comment]
My bad again, Ctrl+S (save document)

**Comment by spadapet** [comment]
@mattleibow, the Ctrl-S triggers a full page reload of the XAML, to understand why it was blank when reloaded, I'd need to have a copy of your project (or just relevant XAML + C# files).

Did you have a mostly empty XAML file, but build up all of the UI in the class constructor? Since the constructor isn't re-run during a full page reload (it just reloads the XAML) that's one way for the UI to be blank after Ctrl-S.

**Comment by mattleibow** [comment]
Sorry, forgot to paste the url https://github.com/mattleibow/scorecard-day-nft-marketplace/tree/issues%2Fcsharp-hotreload

**Comment by spadapet** [comment]
I can't repro a bug here, I'd need exact repro steps if there is still a bug.
I tried:
* Opening up that project:
    *  https://github.com/mattleibow/scorecard-day-nft-marketplace/tree/issues%2Fcsharp-hotreload
* Build and debug on Windows
* Edit C# code for the main page, along with XAML
* Save changes, click hot reload button, make more XAML changes, etc.
* The incremental XAML hot reload and full page hot reload always worked, the page didn't disappear
