### ISSUE TITLE
[SUGGESTION] Suppress terminal when running tests

### ISSUE THREAD

**Issue by UPIMMUNITY** [microsoft/vscode-dotnettools#142]
### Describe the feature you'd like

When running any test, a new terminal was launched, it would be better if it were hidden.
And adding waiting animation may be even better.

### Environment Information

- Windows
- Visual studio code 1.79.1
- ms-dotnettools.csdevkit 0.1.83

**Comment by timheuer** [comment]
This might need to go to /microsoft/vscode?

**Comment by UPIMMUNITY** [comment]
[`Test Runner for Java`](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) done it well without starting a new terminal. So it may not a vscode issue, there probably have a way to suppress it.

**Comment by peterwald** [comment]
@UPIMMUNITY This behavior can be controlled by making a change to your build task.

1. Run the tests (or build) once to be sure the tasks have been created.
1. Ctrl + Shift + P -> Select "Tasks: Run Task". This will show a list of the most recently executed build tasks. Your test project should show up near the top of that list. 
1. Press the "configure task" ("gear" icon) button next to the build task in the list. This will add a snippet to tasks.json so the behavior of the task can be customized.
2. At the bottom of the list, add an entry for "presentation". Intellisense will autocomplete the snippet with some default properties.
3. Change the value of "reveal" in the list to "silent". 
4. Close the terminal panel. Now the build terminal will only be shown when there are build errors. 

If there are multiple build commands, then each would need to be customized in this way.

[Here is a link to the vscode documentation that provides more details.](https://code.visualstudio.com/api/references/vscode-api#TaskPresentationOptions)

Image showing the setting in the task.json file.
![image](https://github.com/microsoft/vscode-dotnettools/assets/5578/a97e84fc-f54d-4938-aa09-242bb22bc61d)

**Comment by peterwald** [comment]
Closing for now pending the collection of more feedback.
