### ISSUE TITLE
[BUG] .NET Acquisition Failed: Command failed

### ISSUE THREAD

**Issue by aiman-962** [microsoft/vscode-dotnettools#1429]
### Describe the Issue

Downloading .NET version(s) 8.0.401-global~x64 ...................................................
Error : (DotnetCommandFailed)
Failed to download .NET 8.0.401-global~x64:
.NET Acquisition Failed: Command failed: c:\Users\Mohammed Ayan Khan\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.5\dist\installers\a4cb8cd85f2f69d4eb835ceff2915e7469d4a9c9e6f024e444f6eef6ba11eec0\dotnet-sdk-8.0.401-win-x64.exe /passive /install /norestart
'c:\Users\Mohammed' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ArtemVolsh** [comment]
having space in your username probably causes the issue
try to either install it to a different folder, or create a new user, but now with mohammed-ayan-khan name

so your path will be valid: c:\Users\mohammed-ayan-khan.vscode and so on.

**Comment by nagilson** [comment]
Ah. Looks like I forgot to add " " around the PATH. Ill make a PR to fix this. Sorry for the problem and the workaround above is correct.
