### ISSUE TITLE
[BUG] Debug Output Windows / Visual Studio Experience

### ISSUE THREAD

**Issue by tpitman** [microsoft/vscode-dotnettools#1431]
### Describe the Issue

I am not 100% sure where to post this. I am a MAUI mobile app developer who develops on a Mac. I was using Visual Studio 2022 for Mac and loving it. As we all know that got discontinued. I do not begrudge Microsoft making that decision even though it affects me greatly.

I also know that the VSCode team and extension teams are working hard to take up the slack. I also know there are work arounds to develop for iOS on Windows using Visual Studio. That is great, but they don't work very well, in my opinion.

So that leaves me with trying really, really hard to get used to VSCode with the extensions being provide. I really appreciate the efforts.

The bug I am reporting could be considered not to be a bug, but since the effort is to try to replace my VS 2022 experience with something comproable, I am going to report it as a bug.

This same thing has been reported elsewhere and even is said to be fixed, but it still doesn't work for me.

I use Console.WriteLine as a quick way to detect flow or logic issues in my mobile apps because my app doesn't need a full fledge logging system and often I am working with Bluetooth devices which do not lend themselves to single step or break point debugging. So I add some Console.Writeline messages in the code to try to determine what is happening. I call this poor man's debugging. It works really well.

For whatever reasons, Visual Studio just outputs those messages to the "Application Output" window when I debug. If I run the app on a phone in release mode those same messages can be viewed in the Mac Console application.

I have come to rely on these messages and this method of "debugging".

I have seen mixed results in VSCode and the many extensions that are supposed to replace or at least give as similar as possible experience when doing MAUI development.

It used to be that iOS output would show up, but not Android. Now the Android messages show up, but not iOS.

Can someone please tell me how to see these messages for both iOS and Android?

### Steps To Reproduce

1. Create MAUI app
2. Add Console.Writeline("hello"); somewhere that will execute
3. Debug on iOS device
4. Notice you cannot see any output from the writeline
5. Debug on Android device
6. Notice you can see the output in the Debug Output window

### Expected Behavior

I would expect to see the Console.Writeilne output in the Debug Output no matter what platform I am running the app on.

### Environment Information

OS: MacOS (dev machine)
iOS or Android target
VSCode for Mac, latest version
MAUI plugin from Microsoft with all dependencies and properly set up

**Comment by emaf** [comment]
@tpitman Could you share the following information:
- C# Dev Kit version
- MAUI Dev Kit version
- Framework your project is targeting (i.e., net8.0-ios)
- .NET SDK version you are using to build your project
- .NET iOS workload version you are using to build your project

**Comment by tpitman** [comment]
C# Dev Kit version - 1.11.4
MAUI Dev Kit version - 1.3.29
Framework your project is targeting (i.e., net8.0-ios) - net8.0-ios
.NET SDK version you are using to build your project - 8.0.302
.NET iOS workload version you are using to build your project - 8.0.40

I think those are the right version. If they don't make sense please give the exact command to get the version you want because there are so many different ways to get that type of information.

**Comment by emaf** [comment]
Thanks, @tpitman! All those look good, except for the iOS workload version. You can get it by running `dotnet workload list`.

If you have more than one .NET SDK installed, please run that command from inside the directory that contains your project (assuming you are using a global.json).

Alternatively, you could share a build binary log by changing the MAUI Debug Verbosity to detailed (`Settings -> Extensions -> .NET MAUI`). After building, a file named `msbuild.binlog` will be generated next to your solution file. This will show all the .NET versions that are involved in building your project.

**Comment by tpitman** [comment]
maui                       8.0.40/8.0.100        SDK 8.0.300

When was the fix for the console output pushed out?

**Comment by emaf** [comment]
@tpitman The fixes were introduced in May, and you seem to have all the right versions. 

As you are not using the latest stable version of the SDK, and there are also debugger components in it, could you try installing the latest .NET 8 SDK version (8.0.401)?

**Comment by tpitman** [comment]
I will have to see. I tend to lag behind in order to let SDKs stabilize. We are constantly in the middle of coordinating the release of mobile apps with our hardware and can't delay things because of software build issues, so we have to be careful.

If there is another way to verify this without just jumping to installing the latest SDK, please let me know.

**Comment by emaf** [comment]
I just tried to install the exact same versions you have, and it still worked for me with a new MAUI app, so I'm a bit confused.

This is what I have:
- C#: 2.46.32
- C# Dev Kit: 1.11.4
- .NET MAUI Dev Kit: 1.3.29
- .NET SDK: 8.0.302
- .NET MAUI workload: 8.0.3/8.0.100 (this is slightly different than what you have)
- .NET iOS workload: 17.0.8478

Maybe the build binary log I mentioned before can help understand the exact version of the .NET iOS workload you are using.

**Comment by tpitman** [comment]
Today I updated the the latest .net SDK 8.0.401 and updated my workloads. I am still not seeing Console.WriteLine in the debug output window.

I changed the build verbosity to Detailed and have the msbuild.binlog file. I don't know how to read it.

I don't want to post it here in a public forum. Can I send it to you to check out for me?

**Comment by emaf** [comment]
@tpitman yes, please send it to [emafern@microsoft.com](mailto:emafern@microsoft.com).

**Comment by tpitman** [comment]
Yea. Debug.WriteLine goes to the debug output window, but Console.WriteLine does not.

**Comment by emaf** [comment]
Could you share the debug console output after reproducing this?

**Comment by tpitman** [comment]
I am sorry. I would love to continue to help fix this, but at this point my work around is good enough for me. I have an #if DEBUG and use Debug.WriteLine or Console.WriteLine depending on that flag.

Since this seems to be something isolate to my computer I am going to leave it at that.

If you ever find something that could fix this, please reach out.

**Comment by emaf** [comment]
We will close this as there is no more information we can use to investigate this issue. We'll reopen this if necessary.
