### ISSUE TITLE
[BUG] Exception on Razor pages

### ISSUE THREAD

**Issue by skleg** [microsoft/vscode-dotnettools#1443]
### Describe the Issue

[Error - 14:15:27] Request textDocument/implementation failed.
  Message: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
  Code: -32004 
[object Object]

### Steps To Reproduce

This often happens when working with Razor pages. It could be also connected to the size of the solution, which is became much bigger now and I have to close the solution or VS Code to get the Intellisense to work again.

### Environment Information

MacOS Sonoma
VS Code v. 1.93.0

**Comment by phil-allen-msft** [comment]
I definitely see this with C# 2.45.20 and C# Dev Kit 1.11.4

**Comment by Fludem** [comment]
> Fixed by [#1443](https://github.com/microsoft/vscode-dotnettools/issues/1443)

Hey, which PR sorry?

**Comment by ryzngard** [comment]
Oh woops, paste error on my part. https://github.com/dotnet/razor/pull/11003 is the PR and https://github.com/dotnet/vscode-csharp/pull/7667 is when it merged into vscode. It should be in the next prerelease
