### ISSUE TITLE
[BUG] Fix going to definition or implementation

### ISSUE THREAD

**Issue by petro2050** [microsoft/vscode-dotnettools#1444]
### Describe the Issue

I frequently get "no definition found for" or "no implementation found for" errors when I right click a type and try to go to definition or implementation. I have a mono repo with 30+ projects. I'm not sure if this is because VSCode cannot scale or Dev Kit / language server is just bad. This is a very poor development experience.

**Comment by jmrpineda** [comment]
I faced this issue too, using C# dev kit v.1.10.16,
The fix was to downgrade the dev kit to v.1.9.55, and... there is! thats works for me.

please, confirm this fix your issue, at least until dev-team can fix that.

**Comment by phil-allen-msft** [comment]
@petro2050 , in order to help us route this issue, can you let us know what file extensions you are seeing the errors in "go to implementation" and "go to definition"?

**Comment by petro2050** [comment]
They are happening in `.cs` files. The issue frequently happens when I save changes in a file or when I rename a file. I also lose keyword highlighting in the editor.

**Comment by dibarbet** [comment]
The next time you hit this issue:
1.  Could you collect the 'C#' output window logs as described here - https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#collecting-general-logs
2.  Could you verify that the file you have open is recognized as part of the solution?  See https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#project-loading-problems for how to check
