### ISSUE TITLE
Randomly unable to debug MAUI project

### ISSUE THREAD

**Issue by davidortinau** [microsoft/vscode-dotnettools#1449]
Type: <b>Bug</b>

After several successfully debugging sessions I will occasionally be unable to debug after hitting F5 or the debug button. I'm presented with a modal stating "could not find the task `maui : BUILD`". 

<img width="307" alt="Screenshot 2024-09-07 at 8 21 19 AM" src="https://github.com/user-attachments/assets/afeb1480-f6f3-4a2d-b026-7f8bd28b1851">

If I reload the window, I can once again debug. Sometimes I can F5 repeatedly (closing the modal) and the issue also seems to resolve itself. 

Extension version: 1.3.29
VS Code version: Code - Insiders 1.93.0-insider (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:13:15.344Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id fc80353a-ef2a-479f-83ff-be5b061d3542|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pkg_only:31057982
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31111988
jh802675:31132134
e80f6927:31120813
ei213698:31121563

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2245110">2245110</a>

**Comment by davidortinau** [comment]
@emaf I wonder if this might happen when the editor doesn't have focus when I hit F5, or whatever does have focus isn't the right thing.

**Comment by davidortinau** [comment]
> @davidortinau are you using a launch json file?
> 
> But I think you raised a good point, when you face this again, could you try hitting F5 from a `.cs` and a `.xaml` file? Both go through different code paths so it would be interesting to see if that makes any difference.

No, no launch.json file is there. 

I'll keep an eye on what has focus when this happens next time.

**Comment by lcapka** [comment]
Hi, this is happening to me consistently for 2 last ours (all day today). Totally no idea how to run the MAUI project. Hitting F5 repeatedly solves nothing.

I used to use launch.json, removed it completely, tried to add some tasks.json; yet result is always the same. No error visible anywhere, except this dialog.

**Comment by lcapka** [comment]
By the way when I hit 'Debug Anyway' it says "Error processing launch options at field: program". At this point I'm don't have launch.json file at all so it has to be something internal/default.

**Comment by lcapka** [comment]
One more thing I just found which may or may not relate to this issues - in the Extensions Host windows, there is an exception in the dotnet-maui:

2024-09-17 11:44:18.782 [error] Error: Error writing JSON RPC Message: MessagePackSerializationException: Failed to serialize System.Exception value.
    at ~/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653025
    at ne (~/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653319)
    at ~/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648103
    at Immediate.<anonymous> (~/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648123)
    at processImmediate (node:internal/timers:478:21)

**Comment by churchs19** [comment]
I am also seeing this issue. 

```
Version: 1.94.0-insider (Universal)
Commit: c4efe1dc9eec4914f3076b2d954fe4fe174a5820
Date: 2024-09-17T05:03:51.290Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
```

**Comment by emaf** [comment]
> One more thing I just found which may or may not relate to this issues - in the Extensions Host windows, there is an exception in the dotnet-maui:
> 
> 2024-09-17 11:44:18.782 [error] Error: Error writing JSON RPC Message: MessagePackSerializationException: Failed to serialize System.Exception value. at .vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653025 at ne (.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653319) at .vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648103 at Immediate. (.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648123) at processImmediate (node:internal/timers:478:21)

If you restat VS Code, do you see the same error?

**Comment by lcapka** [comment]
> If you restat VS Code, do you see the same error?

@emaf Yes. Would be great to see what is the serialized exception...

> 2024-09-18 09:05:10.236 [error] Error: Error writing JSON RPC Message: MessagePackSerializationException: Failed to serialize System.Exception value.
>     at /Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653025
>     at ne (/Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653319)
>     at /Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648103
>     at Immediate.<anonymous> (/Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648123)
>     at processImmediate (node:internal/timers:478:21)
> 2024-09-18 09:05:13.556 [error] Error: Error writing JSON RPC Message: MessagePackSerializationException: Failed to serialize System.Exception value.
>     at /Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653025
>     at ne (/Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:653319)
>     at /Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648103
>     at Immediate.<anonymous> (/Users/user/.vscode/extensions/ms-dotnettools.dotnet-maui-1.3.29-darwin-arm64/dist/extension.js:2:648123)
>     at processImmediate (node:internal/timers:478:21)

**Comment by Matadin75** [comment]
Any news on this error? Its really frustrating :(

**Comment by emaf** [comment]
We haven't been able to reproduce this yet, so we need you to answer a few questions:
1. Do you all see the same error @lcapka posted in [this comment](https://github.com/microsoft/vscode-dotnettools/issues/1449#issuecomment-2355081346)?
2. Could you share the .NET MAUI output and the Terminal content (after trying to run your project)?
3. Could you share your host OS version, C# Dev Kit and .NET MAUI extension versions?

**Comment by StefanW2015** [comment]
Happens to me as well after upgrading to macOS Sequoia 15.0.

I get the same error posted by @davidortinau every time I try to run our MAUI project. We have no custom launch or task profiles set up and everything was running fine before upgrading macOS. 

I use 
MAUI 8.0.40/8.0.100       SDK 8.0.300  
MAUI Extension v1.3.29
C# DevKit v1.10.18

There is no attempt to start anything in the .NET MAUI terminal output. I immedietaly receive 'Could not find the task 'maui: Build'.' 

Building the solution without running it still works.

**Comment by emaf** [comment]
@StefanW2015 could you confirm if there is any output in the .NET MAUI output panel (not the Terminal)?

**Comment by StefanW2015** [comment]
> @StefanW2015 could you confirm if there is any output in the .NET MAUI output panel (not the Terminal)?

I meant the Output panel, sorry. 

It's just the information that the SDKs were found after opening the project. Nothing new after trying to run / debug the app.

```
...
Xcode:
	- Path: /Applications/Xcode.app
	- Discovered from: xcode-select -p
	- Installed: true
```

**Comment by lcapka** [comment]
I have exactly the same status as @StefanW2015 wrote above - nothing in .NET MAUI Output panel except loaded versions. By the way all the extensions are latest (as can be downloaded):

VSCode Extensions:

- .NET MAUI v1.3.29
- C# v2.45.25
- C# Dev Kit v1.10.18

OS: macOS Version 15.0 (24A335)

Android components:
	- Java SDK: installed version '11.0.16.1'
 
	Android SDK recommended required components:
	- platforms/android-34: installed version '3'
	- build-tools/34.0.0: installed version '34.0.0'
	- platform-tools: installed version '35.0.2'
	- cmdline-tools/11.0: installed version '16.0'

**Comment by Matadin75** [comment]
> I have exactly the same status as @StefanW2015 wrote above - nothing in .NET MAUI Output panel except loaded versions. By the way all the extensions are latest (as can be downloaded):
> 
> VSCode Extensions:
> 
> * .NET MAUI v1.3.29
> * C# v2.45.25
> * C# Dev Kit v1.10.18
> 
> OS: macOS Version 15.0 (24A335)
> 
> Android components: - Java SDK: installed version '11.0.16.1'
> 
> ```
> Android SDK recommended required components:
> - platforms/android-34: installed version '3'
> - build-tools/34.0.0: installed version '34.0.0'
> - platform-tools: installed version '35.0.2'
> - cmdline-tools/11.0: installed version '16.0'
> ```

All is the same for me
It was working a few months back but it's now not 😅

**Comment by rolfbjarne** [comment]
This might be related to Xcode 16: https://github.com/xamarin/xamarin-macios/issues/20802#issuecomment-2359001113

**Comment by rolfbjarne** [comment]
> This might be related to Xcode 16: [xamarin/xamarin-macios#20802 (comment)](https://github.com/xamarin/xamarin-macios/issues/20802#issuecomment-2359001113)

NVM, I can repro with Xcode 15.4 as well (but I'm on Sequoia)

**Comment by rolfbjarne** [comment]
> > This might be related to Xcode 16: [xamarin/xamarin-macios#20802 (comment)](https://github.com/xamarin/xamarin-macios/issues/20802#issuecomment-2359001113)
> 
> NVM, I can repro with Xcode 15.4 as well (but I'm on Sequoia)

I can't repro on Sonoma, but that's also a different machine, so there may be any number of other differences as well.

**Comment by vhugogarcia** [comment]
Thanks @rolfbjarne for reference this issue. 

I'm also facing the same issue, I'm sharing my post with details here: https://github.com/xamarin/xamarin-macios/issues/20802#issuecomment-2356678452
![image](https://github.com/user-attachments/assets/6e807a7a-af27-459e-a80a-ac5134523829)
![image](https://github.com/user-attachments/assets/074a2f00-4f82-4bca-8efd-58dca75af5b7)


I'm on macOS Sequoia with XCode 15.4

If there is any fix or workaround, please let us know.

In addition, I'm using the .NET MAUI latest stable version at this moment 1.3.29.

**Comment by BretJohnson** [comment]
For folks that see this, can you also look in the `C#` output panel. There may be more clues there, as the brokered service in question here is calling from the MAUI extension process to the `C#` process (the same one that hosts Roslyn).

**Comment by BretJohnson** [comment]
Also, for folks that see this, can you try disabling XAML Hot Reload and see if the problem goes away. Uncheck the user preferences checkbox shown here. Assuming that makes the issue stop, that can be a temporary workaround until we get a fix in place.

![image](https://github.com/user-attachments/assets/57aab28e-0a7d-46e6-876c-5bee7a357fa4)

**Comment by kimbirkelund** [comment]
> Also, for folks that see this, can you try disabling XAML Hot Reload and see if the problem goes away. Uncheck the user preferences checkbox shown here. Assuming that makes the issue stop, that can be a temporary workaround until we get a fix in place.
> 
> ![image](https://private-user-images.githubusercontent.com/245892/368771056-57aab28e-0a7d-46e6-876c-5bee7a357fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjUwNDEsIm5iZiI6MTcyNjcyNDc0MSwicGF0aCI6Ii8yNDU4OTIvMzY4NzcxMDU2LTU3YWFiMjhlLTBhN2QtNDZlNi04NzZjLTViZWU3YTM1N2ZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNTQ1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzM3NzlhYWVhNzczYWZmNzcyYTJjYzk2MmUwZmNhMzAwMGU1ZDU2MjFjOTg1ZWMxZGYyMzI1ODdkNTU4NjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Db9pPaCcqaf1x3Fa6xqQJuuGk0du0FI-pzzR8p3rzi8)

This workaround seems to work for me, at least for a brand new MAUI project. Enable Hot Reload again returns the "could not find the task maui : BUILD" error.

**Comment by janusw** [comment]
> This workaround seems to work for me, at least for a brand new MAUI project. Enable Hot Reload again returns the "could not find the task maui : BUILD" error.

I can confirm that this workaround also helps for more complex projects :+1:

**Comment by churchs19** [comment]
Cobbling together some pieces from both this thread and [https://github.com/xamarin/xamarin-macios/issues/20802](https://github.com/xamarin/xamarin-macios/issues/20802), these are the steps that got me working again on Mac OS Sequoia 15.0:

1. Install  XCode 16.
2. Reinstall XCode 15.4 from the Apple Developer Portal downloads side-by-side with XCode 16
  - ⁠[Software Downloads - Apple Developer](https://developer.apple.com/download/applications/)
  - Extract the XCode 15.4 xip file and then rename to XCode-15 before moving it to your Applications folder.
3. Set XCode 15.4 as the default XCode.
  1. Open XCode 15.4 with the following command line. It will tell you it is not supported on Sequoia if you try to open it from the icon in Launchpad.
  `/Applications/XCode-15.app/Contents/MacOS/Xcode &`  
  2. Open Settings -> Locations and choose Xcode-15 15.4 (15F31d) from the Command Line Tools drop down.
      <img width="942" alt="image" src="https://github.com/user-attachments/assets/a7f380b2-4e9e-41b0-8aad-6672b0581cc5">
4. Make sure that iOS 17.5 is available in the Platforms section of the XCode 15.4 settings
    <img width="942" alt="image" src="https://github.com/user-attachments/assets/7350294c-e6e4-49f1-b0d4-c430f4e8f08a">
5. Open Visual Studio Code Settings -> Extensions -> .NET MAUI and ensure that Dotnet > Debug: Hot Reload XAML is unchecked.
    <img width="1204" alt="image" src="https://github.com/user-attachments/assets/63bc5f5a-f63f-4439-b40c-b45bf16273bc">

After following these steps, you will be able to build and debug MAUI applications, with or without a launch.json file, through VS Code on Mac OS Sequoia 15.0.

**Comment by vhugogarcia** [comment]
Thanks @BretJohnson, and all who helped me to solve my issue. I can confirm the workaround you shared worked very good and I can continue debugging/developing mobile apps in .NET MAUI using:

- Visual Studio Code + .NET MAUI extension
- macOS Sequioa
- XCode 16 + XCode 15.4 _(installed both side by side)_

I also went ahead and created a blog post article where I share my experience, I hope it helps others as well. 
https://dev.to/vhugogarcia/solving-net-maui-issues-on-macos-sequoia-with-visual-studio-code-and-xcode-16-3ljd

**Comment by danardelean** [comment]
@vhugogarcia  You don't need XCode 16 + XCode 15.4 (installed both side by side). Having Xcode 15.4 is enough to make it work. Installing Xcode 16 is more confusing because you will have to pay attention to the location of Command Line Tools

**Comment by vhugogarcia** [comment]
Thanks @danardelean for the feedback.

**Comment by drasticactions** [comment]
Here's a mini RCA for why the task fails in Sequoia:

https://github.com/dotnet/announcements/issues/324
https://github.com/dotnet/runtime/issues/106775

The MAUI XAML Hot Reload extension uses a TCP Pipeline with a self-signed certificate for handling actions to and from your application and VSCode. There was an issue with Sequoia and the runtime that caused certificates in general to throw exceptions, which is what's happening here. 

The exception here should have been handled and logged, but the exception itself (`{Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.`) that is thrown in the Language server code fails to be deserialized back to the (Typescript) VSCode extension with a MessagePack error. So basically, what should have been "Hot Reload fails to start and we tell you that it didn't load" became "Hot Reload breaks the build because the task can't complete due to unhandled exception because the actual exception couldn't be serialized"

So the key fixes are that XAML Hot Reload should never break the build if anything within the language server process or its part of the extension fails. The actual exception being thrown is a Runtime bug and so, in this state, XAML Hot Reload could not work unless SSL was disabled (which for security reasons is undesirable to allow here) until that was fixed. There is a PR in flight for the extension for wrapping the offending code here, letting it fail, and telling you that XAML Hot Reload failed to load in the log output.

Once the underlying .NET Runtime code is released, and the C# Extension is updated to use it, the underlying certificate issue should be resolved.

If you want to work around this without turning off XAML Hot Reload on Sequoia, you can:

- Download a [nightly .NET build](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#daily-builds-table) for .NET 8 or 9 (You do not need to install it globally, it's only necessary for the Language Server process, so the tar.gz is fine)
- Change the LSP to use this version of dotnet

<img width="863" alt="image" src="https://github.com/user-attachments/assets/d87bd206-dba1-49c5-b253-d1a149965e56">

Which you can do by going into your VSCode extension settings, and searching for `dotnet: Dotnet Path` and pointing it to your local checkout of the nightly dotnet build.

Save, restart VSCode, and you should now be able to deploy your MAUI app with XAML Hot Reload enabled (Or at least, it shouldn't fail to deploy now with that setting enabled.)

**Comment by maonaoda** [comment]
I have been using this
https://github.com/JaneySprings/DotNet.Meteor

**Comment by hflexgrig** [comment]
> Also, for folks that see this, can you try disabling XAML Hot Reload and see if the problem goes away. Uncheck the user preferences checkbox shown here. Assuming that makes the issue stop, that can be a temporary workaround until we get a fix in place.
> 
> ![image](https://private-user-images.githubusercontent.com/245892/368771056-57aab28e-0a7d-46e6-876c-5bee7a357fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzcwMDksIm5iZiI6MTcyNzk3NjcwOSwicGF0aCI6Ii8yNDU4OTIvMzY4NzcxMDU2LTU3YWFiMjhlLTBhN2QtNDZlNi04NzZjLTViZWU3YTM1N2ZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNzMxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTk0NmExZTc2NTExNmJlYzA5M2IzNDgyNmYzOTczZjIwZWE3Y2NmZjYzNjhlYTliNzI5YzYxMzc3NTRiZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z1jiswB_BdWG3jKkBUwm7l1V9AuTJXiOPa7NrklEToU)

Helped me as well :)

**Comment by drasticactions** [comment]
> Any news regarding the issue of hot reload not working? I tested @drasticactions suggestion, but after allowing the files to run it throws "Microsoft.NETCore.App.app is damaged and cant open". Other work arounds without using DotNet.Meteor?
> 
> BR, Sindre

Nightly .NET builds are not signed. So you probably need to clear the Apple Quarantine on the .NET folder for it to make a clean build.

`xattr -rd com.apple.quarantine /path/to/dotnet/folder`

Otherwise, there's not much else you can do without both the underlying runtime fix being released, and the extension picking it up and using it. The exception not being caught issue I mentioned above is fixed in the extensions Main branch, and that should at least let the build through and deploy. I don't know when that will be published yet though, I assume whenever the next MAUI VSCode Extension preview is out. But hot reload won't work without the underlying runtime fix being published; the only other way to work around it would be to disable SSL and that would introduce security risks that I want to avoid.

**Comment by sindrevr** [comment]
Thanks @drasticactions , working like a charm 👍

**Comment by BretJohnson** [comment]
.NET 8.0.10 is now released, which fixes this issue. Here's the latest status:

* For an immediate workaround to make XAML Hot Reload work on Sequioa, install 8.0.10 from https://dotnet.microsoft.com/en-us/download. The VS Code LSP (Language Server Process) process uses the latest stable version of .NET installed, so no additional config should be necessary - once you update, it should work.
* We're changing the C# extension to update to 8.0.10 automatically (https://github.com/dotnet/vscode-csharp/pull/7651), which will likely be included in next week's prerelease update. After that, manually updating .NET won't be needed.

**Comment by BretJohnson** [comment]
@dibarbet - I added you as an assignee, as you are making the final fix for this with https://github.com/dotnet/vscode-csharp/pull/7651. Thx.

**Comment by nicholasyin** [comment]
so what's the status of this? We need to wait for the release before upgrading XCode and/or Sequoia?

**Comment by BretJohnson** [comment]
@nicholasyin That's technically correct, but this fix was published to prerelease in late October and then to the release channel in (I believe) mid November. If you have version 2.54.24 or later of the `C#` extension in VS Code, it should just work. So if you are still seeing any problems on Sequia, please let us know (ideally creating a new bug, but also feel free to comment here on this one), as it may well be a different issue.

**Comment by nicholasyin** [comment]
> [@nicholasyin](https://github.com/nicholasyin) That's technically correct, but this fix was published to prerelease in mid October and then to the release channel in (I believe) early November. If you have version 2.54.24 or later of the `C#` extension in VS Code, it should just work. So if you are still seeing any problems on Sequia, please let us know (ideally creating a new bug, but also feel free to comment here on this one), as it may well be a different issue.

thanks for the reply. already upgraded and working fine so far.

**Comment by ruffinToptal** [comment]
@nicholasyin Not sure if this counts, but I'm getting it now on 26.2.

launch.json looks like:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }
    ]
}
```

Output in the terminal looks... okay?

```
 *  Executing task: dotnet build -t:Build -p:Configuration=Debug -f net10.0-ios -r iossimulator-arm64 -p:CustomAfterMicrosoftCSharpTargets=/Users/myfreakinname/.vscode/extensions/ms-dotnettools.dotnet-maui-1.12.15-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets -p:MauiVSCodeBuildOutputFile=/var/folders/ry/9v79xg1j7n9fzdfygqmb4q180000gp/T/dotnet-maui/maui-vsc-59578cb4-21d5-4288-808b-aa5beb81d30f.json -p:MauiTargetProject=/Users/myfreakinname/projects/MauiApp1/MauiApp1/MauiApp1.csproj -p:XamlTools=/Users/myfreakinname/.vscode/extensions/ms-dotnettools.csharp-2.110.4-darwin-arm64/.xamlTools -p:EnableDiagnostics=True -p:EnableMauiXamlDiagnostics=True /Users/myfreakinname/projects/MauiApp1/MauiApp1/MauiApp1.csproj 

  MauiApp1 net10.0-ios iossimulator-arm64 succeeded (10.2s) → MauiApp1/bin/Debug/net10.0-ios/iossimulator-arm64/MauiApp1.dll

Build succeeded in 10.5s
 *  Terminal will be reused by tasks, press any key to close it. 
```

but the result is

<img width="292" height="256" alt="Image" src="https://github.com/user-attachments/assets/1076504a-01d0-43d5-8506-4db190173d8d" />
