### ISSUE TITLE
[BUG] Adding a project to a solution from the CLI does not reload solution explorer

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-dotnettools#145]
### Describe the Issue

See title

### Steps To Reproduce

1. Create a solution with a project in it.
2. Open the solution in vscode.
3. From the command line, create a new project.
4. From the command line, add the project to the solution via `dotnet sln add <path to 3>`

### Expected Behavior

Solution explorer is refreshed with the new solution.

**Comment by jasonmalinowski** [comment]
@333fred Was this with or without DevKit?

**Comment by 333fred** [comment]
We don't have a solution explorer without devkit 🙂

**Comment by jasonmalinowski** [comment]
Ah, I missed the "explorer" bit, because I think we still have a bug this wouldn't work in Blue only either.

**Comment by tmeschter** [comment]
Moving to "area-project-cps" as this is not specific to the .NET Project System

**Comment by timheuer** [comment]
Weird, I've been using this a lot -- @333fred OS?

![2023-06-16_07-38-45](https://github.com/microsoft/vscode-dotnettools/assets/4821/36d5ae0b-0067-4506-8330-a8440876cf37)
