### ISSUE TITLE
Razor Language Server Crashes Repeatedly in VS Code on Ubuntu

### ISSUE THREAD

**Issue by codebrain22** [microsoft/vscode-dotnettools#1453]
### Describe the Issue

The Razor Language Server crashes repeatedly with the error: "The Razor Language Server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information." This occurs when using the C# Dev Kit extension in Visual Studio Code on an Ubuntu environment.

### Steps To Reproduce

1. Open Visual Studio Code (ensure the C# Dev Kit extension is installed).
2. Monitor the notification bar—observe that the error appears multiple times (up to 5 times).

**Comment by ryzngard** [comment]
I'm not able to reproduce this on my Ubuntu setup. Are you still hitting this? Tested with `v2.50.25`
