### ISSUE TITLE
Fix: To change the avatar icon in Brave

### ISSUE THREAD

**Issue by 11844** [microsoft/vscode-dotnettools#1460]
Please somebody do this as it is confuses me as I have the same thing on my second account. 
![image](https://github.com/user-attachments/assets/fbf01f6d-7b68-42f9-b6c2-31bc011ce5bc)

**Comment by phil-allen-msft** [comment]
@11844 , I'm not sure what you mean by "Brave".  Can you elaborate a bit more?
