### ISSUE TITLE
Keeps repeating asking for a startup project

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#1464]
Type: <b>Bug</b>

Each time I open existing workspaces it keeps asking for what startup project to select.

![Image](https://github.com/user-attachments/assets/4966d84a-9b28-40aa-9b8c-4369c91b7f91)

Extension version: 1.11.6
VS Code version: Code - Insiders 1.94.0-insider (6e9d8a281003211220a6732ec538a28c483ff78b, 2024-09-11T05:04:03.124Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.92GB (99.67GB free)|
|Process Argv|--crash-reporter-id 961e68ed-cec6-437f-8e5f-e44a8abbf88f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31111988
jh802675:31132134
e80f6927:31120813
fje88620:31121564

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2242095">2242095</a>

**Comment by smitpatel** [comment]
@tmeschter - Do we persist startup project information or we ask user on first occurrence in a session?

**Comment by tmeschter** [comment]
After you have selected a startup path we persist it. However, if it isn't we shouldn't ask for it when opening the workspace, only when trying to launch.

**Comment by timheuer** [comment]
It doesn't feel persisting to me...video:
https://github.com/user-attachments/assets/4f9e54d4-bb9d-4224-aafa-f39c7f4e7e06

**Comment by smitpatel** [comment]
@timheuer - I was testing out this. I am able to get repro of this when .NET MAUI extension is enabled. In the absence of that extension, I don't see it. Can you please try out the same and see if issue goes away when .NET MAUI extension is not installed (or disabled). That will help us narrow down issue.

**Comment by Juarrow** [comment]
> [@timheuer](https://github.com/timheuer) - I was testing out this. I am able to get repro of this when .NET MAUI extension is enabled. In the absence of that extension, I don't see it. Can you please try out the same and see if issue goes away when .NET MAUI extension is not installed (or disabled). That will help us narrow down issue.

I am not @timheuer, but I have the same problem and can confirm, that disabling the ".NET MAUI"-extensions resolves this issue - for me, at least.

**Comment by timheuer** [comment]
> Can you please try out the same and see if issue goes away when .NET MAUI extension is not installed (or disabled). That will help us narrow down issue.

Also can confirm, disabling MAUI removes this notification.

**Comment by emaf** [comment]
We are working on a fix for this and it will be released soon.

**Comment by AllenD-MSFT** [comment]
This was fixed recently. Please try the latest update and it should behavior better in this regard.
