### ISSUE TITLE
[BUG] <Removes the word after the cursor when period is pressed after a keyword.>

### ISSUE THREAD

**Issue by tfritzy** [microsoft/vscode-dotnettools#147]
### Describe the Issue

https://github.com/microsoft/vscode-dotnettools/assets/23142109/457db546-b1e9-4791-9a38-6e657e6c87b7

**Comment by timheuer** [comment]
I believe a dupe of https://github.com/dotnet/vscode-csharp/issues/5777 /cc @genlu

**Comment by genlu** [comment]
@timheuer Yes, this is a duplicate of https://github.com/dotnet/vscode-csharp/issues/5777
