### ISSUE TITLE
[SUGGESTION] <Add a seperate .EditorConfig Template that follows the Unity Style Guide>

### ISSUE THREAD

**Issue by KenzKD** [microsoft/vscode-dotnettools#1478]
### Describe the feature you'd like

When Creating a New file, we get the option using the Solution Explorer we get the option to add a .editorconfig file that appears to have a Template to follow Microsoft's Style Guide. I would like an additional Template option that follows the Unity Style Guide.

The Unity Style Guides that I am referring to: 
- https://unity.com/how-to/naming-and-code-style-tips-c-scripting-unity
- https://unity.com/how-to/formatting-best-practices-c-scripting-unity

This will be a nice Jumping off point for Anyone looking to Implement an .editorconfig for Unity.

![image](https://github.com/user-attachments/assets/532b49db-1cbe-46c5-8afe-b9d06dd6f287)

### Environment Information

- OS: Windows 11
- VS Code Version : 1.93.1
- Extension Version: Unity 1.0.3

**Comment by smitpatel** [comment]
We don't own any templates in VS Code itself, rather we light up templates installed on user machine.
The editorconfig template exists in https://github.com/dotnet/sdk repo here https://github.com/dotnet/sdk/tree/main/template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig
Perhaps a unity specific template in .NET SDK may not be right.

We also light up custom templates in UI so if you create your own template for unity or unity ships one, then once that template is installed on machine, you should be able to see it in C# dev kit too. Here is documentation for creating new item template https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template

**Comment by KenzKD** [comment]
Thanks for the Response and for Providing these resources. I'll Close the Request here.
