### ISSUE TITLE
[BUG] <title> DotnetCommandFailed

### ISSUE THREAD

**Issue by kilekunnod** [microsoft/vscode-dotnettools#1483]
### Describe the Issue

Error : (DotnetCommandFailed)
Failed to download .NET 8.0.401-global~x64:
.NET Acquisition Failed: Command failed: c:\Users\kilekun pc\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.5\dist\installers\a4cb8cd85f2f69d4eb835ceff2915e7469d4a9c9e6f024e444f6eef6ba11eec0\dotnet-sdk-8.0.401-win-x64.exe /passive /install /norestart
'c:\Users\kilekun' is not recognized as an internal or external command,
operable program or batch file.

### Expected Behavior

I was taking a C# course with Microsoft, and the instructions from the documentation were to install the .NET SDK, and it returned that error, even after asking me if i'd allow it make some changes on my PC.

### Environment Information

VS Code as IDE

**Comment by AbhitejJohn** [comment]
@kilekunnod : Thanks for logging this. Could you share a little more detail on the repro steps please? It would also be interesting to know what Environment you are seeing this on.

**Comment by kilekunnod** [comment]
Describe the Issue
Error : (DotnetCommandFailed)
Failed to download .NET 8.0.401-global~x64:
.NET Acquisition Failed: Command failed: c:\Users\kilekun pc.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-2.1.5\dist\installers\a4cb8cd85f2f69d4eb835ceff2915e7469d4a9c9e6f024e444f6eef6ba11eec0\dotnet-sdk-8.0.401-win-x64.exe /passive /install /norestart
'c:\Users\kilekun' is not recognized as an internal or external command,
operable program or batch file.

Steps To Reproduce
No response

Expected Behavior
I was taking a C# course with Microsoft, and the instructions from the documentation were to install the .NET SDK, and it returned that error, even after asking me if i'd allow it make some changes on my PC.

Environment Information
VS Code as IDE

**Comment by kilekunnod** [comment]
Can my issue be fixed?

**Comment by nagilson** [comment]
This was a bug and should be fixed now. Please let me know if you still experience it.
