### ISSUE TITLE
[BUG] Debug for Unity The breakpoint identifier “***” is out of range when using VSCode.

### ISSUE THREAD

**Issue by Hoper-Q** [microsoft/vscode-dotnettools#1498]
Debug for Unity The breakpoint identifier “***” is out of range when using VSCode.

I’m sure there is a value inside, because there are judgments made using its value later on, and the log can also print it out, but I just can’t see it.

### Environment Information

![image](https://github.com/user-attachments/assets/49226106-3d61-4bd7-b434-7b099c12cd2c)
![image](https://github.com/user-attachments/assets/b9df57e2-63ef-4c52-91e6-a69eb8a26e86)
![image](https://github.com/user-attachments/assets/11550cc6-92a0-416c-9a06-47ffae405fc3)

**Comment by jbevain** [comment]
Hello,

Thanks for reaching out!

I'm not 100% sure I understand what's going wrong.

Could you post a screenshot or a video and explain:

1) What you're doing
2) What you're expecting to happen
3) What's happening instead

Thanks!

**Comment by jbevain** [comment]
Hi @Hoper-Q,

Gentle reminder that we need some more information to investigate the issue.

Thanks!

**Comment by jbevain** [comment]
Closing this as we don't have enough information to investigate. Feel free to add more information for us to look into this, thanks!
