### ISSUE TITLE
[BUG] Backticks in doc comments are not escaped when converting to markdown for quick info.

### ISSUE THREAD

**Issue by mhutch** [microsoft/vscode-dotnettools#1499]
### Describe the Issue

I have a doc comment that contains a `<c>` code span with  backtick: ``<c>A`1[B,C]</c>`` 

When the LSP converts the doc comment to markdown for the quick info, it does not appear to be escaping the backtick, resulting in malformed output: 

![Screenshot 2024-09-30 at 12 00 12 PM](https://github.com/user-attachments/assets/ef51616c-4f59-4a40-9c5a-c92c081fe75b)

### Steps To Reproduce

1. Create a member with a doc comment summary that contains ``<c>A`1[B,C]</c>`` 
2. Hover over the member and look at the quick info
3. It is rendered as follows: `A`1[B,C]\`

### Expected Behavior

It is rendered as ``A`1[B,C]``

**Comment by JoeRobich** [comment]
Thank @mhutch! The fix should be in the next prerelease.
