### ISSUE TITLE
.NET 8 SDK/runtime not fully supported

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#15]
C# Dev Kit is validated against released versions of .NET and may encounter issues with .NET 8. We will be actively working to support that in future updates.

**Comment by timheuer** [comment]
> That's very unfortunate since it hit exactly your early adopters the most.

We're not saying we aren't working on it -- and .NET 8 is still in preview as well. It's just a point in time. We prioritized the latest supported SDK releases.  .NET 8 support is something we of course will have.

**Comment by Michael-Eng** [comment]
Note that earlier versions of .NET 8 had an incompatibility but versions 8.0.400+ should be fixed.
