### ISSUE TITLE
Unexpected Error Denoting "Predefined type is not defined or imported"

### ISSUE THREAD

**Issue by CodeAX2** [microsoft/vscode-dotnettools#150]
Type: <b>Bug</b>

When opening existing solution, many files contain an error of the format:
"Predefined type \<TYPE\> is not defined or imported"

Typically the \<TYPE\> denoted in the error seems relatively unrelated to the associated statement. For example, below are screenshots of a code snippet from my project and the associated errors.

![image](https://github.com/microsoft/vscode-dotnettools/assets/45527167/32e0cff4-3afa-460c-9e50-f16aa35c2acc)
![image](https://github.com/microsoft/vscode-dotnettools/assets/45527167/9c9cfc68-bba0-476a-92bf-72a9a8407abe)
![image](https://github.com/microsoft/vscode-dotnettools/assets/45527167/72ddd629-691d-4801-a96e-c362495429b9)
![image](https://github.com/microsoft/vscode-dotnettools/assets/45527167/097ff8ab-abd3-4b4b-a8ae-f5ac3dc732cb)

Unfortunately, the code base is private, so I am unable to share the repository.

The solution is comprised of multiple C# projects, many of which depend on each other. The project also depends on the Monogame Nuget package.

The project compiles and runs fine, and the errors disappear when the Dev Kit extension is disabled, and only the base C# extension is used.

I am happy to provide any other information I am able to. Thank you!

Extension version: 0.1.103
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.47GB free)|
|Process Argv|--crash-reporter-id 4181c454-4ee1-4930-aa0a-dce040806d26|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by ProTip** [comment]
Getting the same thing in files using namespaces from another project in the same solution.

**Comment by arkalyanms** [comment]
Seems like a project system issue. Note the comment around removing CDK and the squiggles going away with the base extension.

**Comment by stasnocap** [comment]
also seems like 'dotnet build --force' do the magic

**Comment by stasnocap** [comment]
'dotnet clean' works

**Comment by webreidi** [comment]
Closing as we have made several improvements in this area and haven't heard any more issues on this. Please reopen if you are still experiencing this issue.
