### ISSUE TITLE
[BUG] <SDK Can't be installed in the VSCode app>

### ISSUE THREAD

**Issue by semana-divin** [microsoft/vscode-dotnettools#1502]
### Describe the Issue

After installing the .NET SDK, my system does not seem to recognize it, as if the installation didn't occur. Running dotnet commands in the terminal returns an error or indicates that .NET is not installed.

### Environment Information

OS: Windows 11
VSCode Version: 1.93.1

**Comment by nagilson** [comment]
Thanks for reporting this issue. Do you experience the issue upon reloading vscode? If you use the VSCode terminal and type echo %PATH%, what does it return (make sure to remove any personal data)

**Comment by semana-divin** [comment]
It returns '%PATH%'

**Comment by semana-divin** [comment]
When VSCode is reloaded the notification that appear is "The .NET core SDK cannot be located...."

In the terminal echo %PATH% returns "%PATH%

**Comment by nagilson** [comment]
Thank you. How did you install the .NET SDK? And what about `$env:path`? Looks like your terminal may be powershell and not a cmd. Whichever terminal you have, please use the appropriate method to print the environment variable.

**Comment by semana-divin** [comment]
To install the SDK i used the installer downloaded on official Microsoft dotnet website ([https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.402-windows-x64-installer?journey=vs-code](url): For refernce)

It was powershell and for CMD below is what it returns:
C:\Program Files\Google\Chrome\Application;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Users\seman\AppData\Local\Microsoft\WindowsApps;

`$env:path` where and how to execute it?

**Comment by nagilson** [comment]
Thank you. What you returned is helpful enough.

@joeloff The .NET Installer should add dotnet to the PATH, right? Any idea why this user is not seeing this?

**Comment by nagilson** [comment]
Btw, to confirm -- when you enter that in the CMD to print the PATH variable, did you enter it in the vscode terminal or a new cmd window? And is there any difference between trying the two of those?

A workaround to get things working for you should be to add the dotnet executable (usually C:\\Program Files\\dotnet) to your PATH env variable. But do that after trying the above please!

**Comment by semana-divin** [comment]
In the VSCode terminal the path of dotnet executable is not there, but in the CMD window the path is seen.

I'm also wondering if the .NET SDK is installled it doesn't add itself in the env?

**Comment by nagilson** [comment]
There are some situations where VS Code does not seem to pick up the same environment as the system, which I would consider to be a bug with VS Code, which is what's causing this to not work. I will have to look into this as I dont fully understand how VS Code is having this functionality

**Comment by nagilson** [comment]
Can you confirm if launching vscode from a terminal with dotnet on the PATH works? And if it does -- how are you normally launching vscode?
