### ISSUE TITLE
[BUG] Creating new project asks for project location twice

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#1507]
### Steps To Reproduce

1. Open VS Code 
2. Create new project through the command palette
3. Select console app 
4. Select any location on your device and give it any name
5. A drop down appears that makes me select "Create project" <- I'm not sure why this additional click exists when I've just specified the location. 

### Expected Behavior

The app gets created in the location that was just specified without asking me to click another button to create it

**Comment by smitpatel** [comment]
cc: @webreidi - Someone from PM team needs to look at this. After asking for name, we show user dropdown which allows them to create project or go into configuring project options.

**Comment by webreidi** [comment]
The create project option is not the only option in the last step. For most project types, the user has the ability to select project configurations at this point, or select the default and just create the project. But skipping this step would be a take-back and a step back in experience for many users.
