### ISSUE TITLE
[BUG] "Go to Definition" (F12) is missing on Mac when right click

### ISSUE THREAD

**Issue by DevOtts** [microsoft/vscode-dotnettools#151]
### Describe the Issue

On mac it seems that the Code Navigation has problems with the [Go To Definition](https://code.visualstudio.com/docs/csharp/navigate-edit#_go-to-definition), [Peek Definition](https://code.visualstudio.com/docs/csharp/navigate-edit#_peek-definition) and Find All References commands.

As you can see in the screenshot, these options don't appear when we right-click with the mouse, these options don't appear. Also, the F12 shortcut doesn't work.

![Screen Shot 2023-06-15 at 13 22 38](https://github.com/microsoft/vscode-dotnettools/assets/851664/fe03b284-3c44-4a38-96b0-07b5a516f9e9)

### Steps To Reproduce

1. Open a .net core solution
2. Go to a variable that you want to go to the definition ("Customer" model in my example)
3. the options don't appear

### Expected Behavior

It should show all options like is presented here: https://code.visualstudio.com/docs/csharp/navigate-edit

![Screen Shot 2023-06-15 at 13 36 06](https://github.com/microsoft/vscode-dotnettools/assets/851664/1922bba9-a78c-46d1-8b9b-83133f07b9e7)

### Environment Information

- macOS Monterey (version 12.4)
- Visual Studio Code 
- `Version: 1.79.1 (Universal)
Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215
Date: 2023-06-12T16:16:49.215Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.5.0`

![Screen Shot 2023-06-15 at 13 27 58](https://github.com/microsoft/vscode-dotnettools/assets/851664/3aa54fb1-66fa-44e0-ac31-aa8bc1cede6a)
![Screen Shot 2023-06-15 at 13 28 18](https://github.com/microsoft/vscode-dotnettools/assets/851664/4bb90cb6-2a15-477c-ae73-d3102a6ac043)
![Screen Shot 2023-06-15 at 13 28 39](https://github.com/microsoft/vscode-dotnettools/assets/851664/765bccb4-9e29-4b1c-adb2-aeb9f62aae18)
![Screen Shot 2023-06-15 at 13 28 55](https://github.com/microsoft/vscode-dotnettools/assets/851664/f8e300ae-429c-46e5-aa91-800b62806ec1)

**Comment by tbalaternotnow** [comment]
same issue on ubuntu.

**Comment by arkalyanms** [comment]
Specific to C# Dev Kit and related to metadata references I believe. Starting with project. This may already have been fixed.

**Comment by kvenkatrajan** [comment]
@tbalaternotnow @DevOtts can you confirm if you are still experiecing the issue with the latest version of C# dev kit? Thanks!

**Comment by kvenkatrajan** [comment]
Closing ticket due to inactivity. Please feel free to reopen incase still an issue.

**Comment by tbalaternotnow** [comment]
> @tbalaternotnow @DevOtts can you confirm if you are still experiecing the issue with the latest version of C# dev kit? Thanks!

can no longer confirm. I dumped C# development on Ubuntu all together.  Windows and VS only now.

**Comment by DevOtts** [comment]
@kvenkatrajan sorry for the delay. I'm no longer having this issue. You can close it. Thank you
