### ISSUE TITLE
Solution Explorer not opening solution

### ISSUE THREAD

**Issue by hbabar-uc** [microsoft/vscode-dotnettools#152]
Type: <b>Bug</b>

I have opened the root folder containing the solution file, however, in the Solution Explorer tab, it's just showing the `Open Solution` button and clicking on it is not loading the solution and it's not prompting or asking a question to open or load solution/project

I'm using the latest build
- C# Dev Kit v0.1.103 preview build
- VS Code Version: 1.79.1
- OS Version: Windows 10 22H2 build 19045.3086

Extension version: 0.1.103
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900HK (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (2.20GB free)|
|Process Argv|--crash-reporter-id 7d0307fe-df66-4a51-8e5d-e731c68e2805|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by hbabar-uc** [comment]
https://1.gravatar.com/userimage/236471393/a096c8d64228468e9bf17777d8f81d8d?size=original

**Comment by timheuer** [comment]
@hbabar-uc is there anything helpful in the C# or C# Dev Kit output logs in VS Code? -- can you confirm what version of the C# extension you have? Should be 2.0.x pre-release

**Comment by hbabar-uc** [comment]
Hi @timheuer, The C# extension build is  v2.0.212 Pre-Release, Nothing in the output tab and so is problems tab not reporting any errors. However, opening the developer tool is showing below screenshot.
![image](https://github.com/microsoft/vscode-dotnettools/assets/93679401/dced61a2-776c-485d-af63-28327351ad2b)

**Comment by lifengl** [comment]
@hbabar-uc : it is likely that you haven't installed any NET Core SDK on the machine, or dotnet cannot be found through $PATH environment variable. Make sure you install SDK from https://dotnet.microsoft.com/en-us/download and the machine might need be rebooted after the installation

**Comment by tamerkamal** [comment]
The opening solution feature in solution explorer for .NET projects suddenly stopped working in Vs Code insiders, and no way to fix it until now.
**Note**: that the solution opens on the vs code normal version but not on VS Code Insiders version

**Comment by timheuer** [comment]
@tamerkamal are you experiencing this now? Can you open a new bug from Report an Issue to get version numbers and your specific repro steps. 

If this is happening for you in prerelease we want to validate. I’m not seeing this

**Comment by doggiehell** [comment]
Can confirm, Open Solution button does nothing when pressed. (vscode insiders)
