### ISSUE TITLE
x ndk-bundle: not installed

### ISSUE THREAD

**Issue by HobDev** [microsoft/vscode-dotnettools#1534]
Type: <b>Bug</b>

The following error in Android Configuration in both Windows and Mac Machines:
x ndk-bundle: not installed

When I try to debug on Android getting following error in the terminal:

C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.138\tools\Xamarin.Android.Tooling.targets(70,5): error XA5300: The Java SDK directory could not be found. Install the Java
 SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk [C:\Users\spara\source\repos\Dome-backend\Player\Player.csproj::TargetFramework=net8.0-android]
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.138\tools\Xamarin.Android.Tooling.targets(70,5): error XA5300: To use a custom JDK path for a command line build, set the  
'JavaSdkDirectory' MSBuild property to the custom path. [C:\Users\spara\source\repos\Dome-backend\Player\Player.csproj::TargetFramework=net8.0-android]

I have the Java installed and set the path in the Visual studio code at:

c:\Program Files\Microsoft\microsoft-jdk-17.0.12-windows-x64\jdk-17.0.12+7

Also note I installed Android studio and all the required components are installed and recognize by Visual Studio Code including the latest version of NDK.  

Extension version: 1.3.29
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600XT 6-Core Processor             (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.69GB free)|
|Process Argv|--crash-reporter-id cf5b8c68-8be2-475e-b301-197515634cb4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2285281">2285281</a>

**Comment by HobDev** [comment]
Do I need to switch to latest prerelease of the .NET Maui Extension or the latest prerelease of Visual Studio Code.

**Comment by emaf** [comment]
@HobDev Allen was referring to the .NET MAUI extensions. The improvements were also shipped to the release channel yesterday, so if you update to the latest version of the release channel (v1.4.36) you will get them.

**Comment by HobDev** [comment]
The issue still exists in the latest release version v1.4.36 .

**Comment by HobDev** [comment]
Today I able to run the app on Android emulator inspite of the `x ndk-bundle: not installed` issue. Although an error window pops up with the following message:

Debugging can fail: Android SDK required components need to be installed.

But the debugging was successful.

The debugging is only possible if I run the Emulator in advance from Android Studio. The Visual Studio don't able to start the Emulator. Should I open new issue for Emulator not starting from VS Code problem.

**Comment by HobDev** [comment]
> Today I able to run the app on Android emulator inspite of the `x ndk-bundle: not installed` issue. Although an error window pops up with the following message:
> 
> Debugging can fail: Android SDK required components need to be installed.
> 
> But the debugging was successful.
> 
> The debugging is only possible if I run the Emulator in advance from Android Studio. The Visual Studio don't able to start the Emulator. Should I open new issue for Emulator not starting from VS Code problem.

I can debug on Mac but the original issue exists on Windows. It's not possible to debug on Windows

**Comment by HobDev** [comment]
This is a big hurdle in adopting VS Code for Maui development. When this is expected to be fixed.

**Comment by Cryptoc1** [comment]
Am experiencing this with MAUI extension `v1.12.15`.

I've installed multiple versions of the NDK via Android Studio, and have followed the suggested resolution from the MAUI Output pane of manually invoking `sdkmanager "ndk-bundle"` via cmdline-tools.
