### ISSUE TITLE
[BUG] ms-dotnettools.csharp extension has corrupt changelog when viewed in VSCode

### ISSUE THREAD

**Issue by rjgotten** [microsoft/vscode-dotnettools#1538]
### Describe the Issue

When opening the changelog for the `ms-dotnettools.csharp` extension in VSCode, there is a corruption in the section for version 2.50.x which causes the entirety of the remainder of the file to be misformatted:

![Image](https://github.com/user-attachments/assets/23c7e2ad-3980-474c-a451-44f98c76f375)

Looks like the solved issues have their PR titles pasted in verbatim, without proper escaping and there's one with a `<code>` tag there:
https://github.com/dotnet/roslyn/pull/75215

### Steps To Reproduce

1. Open `ms-dotnettools.csharp` extension in VSCode Extensions panel
2. Switch to changelog tab

### Expected Behavior

Normal formatted changelog

### Environment Information

- OS: Windows
- VSCode version: 1.94.2
- Extension version: 2.50.27

**Comment by AbhitejJohn** [comment]
Thanks for letting us know @rjgotten . Tagging @webreidi for thoughts on this. I do not know if the changelogs are updated through automation or if this is done manually.

**Comment by webreidi** [comment]
Tagging @dibarbet since this is referring to the C# extension.
