### ISSUE TITLE
[SUGGESTION] Consider changing certificate notification to modal right away

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#1542]
### Describe the Issue

When creating a Blazor web app and selecting the https launch configuration, you get a pop up in the bottom right corner that suggests creating a trusted self-signed certificate. The options provided are Yes, Not Now, and More Information. 
![Image](https://github.com/user-attachments/assets/eb280945-8215-4e98-b164-9bc960f77827)

Since the user cannot launch the app without doing this and the popups in the bottom right are easy to miss or click X on because of other repeated notifications, I would recommend changing this notification to a modal right away. Since there is a modal right after this anyway, it could also be an opportunity to have one message only and reduce the flow by one click for users. 
![Image](https://github.com/user-attachments/assets/5ac9fa2a-aa44-4a91-a71a-7c47731a4186) 

### Steps To Reproduce

1. Follow the blazor tutorial but in VS Code https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
2. Select the https launch config when asked instead of the default 

### Expected Behavior

For a modal dialog to be popped up instead of a notification. This allows the user to go down a path of failure more easily as it seems more optional than required in order to move forward. Plus notifications can be hard to see and X'd out easily

**Comment by WardenGnaw** [comment]
This will be fixed in the next C# Extension Release.
