### ISSUE TITLE
How to set environment variables in launch.json?

### ISSUE THREAD

**Issue by lucasmsoares96** [microsoft/vscode-dotnettools#1544]
I'm having a problem with this launch.json below.

#### launch.json

```
{
    "configurations": [
        {
            "name": "C#: csharp-semantic-kernel [Default Configuration]",
            "type": "dotnet",
            "request": "launch",
            "projectPath": "${workspaceFolder}/csharp-semantic-kernel.csproj",
            "env": {
                "API_KEY": "",
            }
        }
    ]
}
```

#### Warning
```
Property env is not allowed.
```

What is the right way to do this?

**Comment by WardenGnaw** [comment]
You will want to set environment variables in your `launchSettings.json`.

See https://code.visualstudio.com/docs/csharp/debugger-settings#_environment-variables

**Comment by WardenGnaw** [comment]
It should, if you have the same environment variables defined in `launchSettings.json` will be used in the VS Code development/debugging scenario and the came environment variables listed in docker-compose it should be spun up with those environment variables in the App.

**Comment by lucasmsoares96** [comment]
It works fine! Thank you @WardenGnaw.
