### ISSUE TITLE
[BUG] Walkthrough fails to launch on mac

### ISSUE THREAD

**Issue by katiesavage** [microsoft/vscode-dotnettools#155]
### Describe the Issue

Get started walkthrough failing to launch on Mac. 

There are separate image files for Windows and Mac within the walkthrough, so there are duplicate walkthroughs: one intended for Mac users and one for non-Mac users. The non-Mac walkthrough works as expected.

Here are the images: 
[cs-walkthrough-images-themed.zip](https://github.com/microsoft/vscode-dotnettools/files/11763597/cs-walkthrough-images-themed.zip)

### Environment Information

- macOS

**Comment by timheuer** [comment]
FYI I think there are two problems here.  The `id` for the walkthrough I think actually has to be unique regardless of the conditional on the OS.  So adding a `Mac` onto the ID made it show up for me.  Secondarily, the media assets for macOS seem to be invalid -- the windows ones are fine but the SVG for mac look like binary?  So even though I could get the walkthrough on macOS the images were broken. /cc @katiesavage

**Comment by timheuer** [comment]
@katiesavage do we know if this was fixed and is working correctly now?

**Comment by katiesavage** [comment]
Currently working with @webreidi to find an engineering owner on the CDK team.
