### ISSUE TITLE
[BUG] Negative exception filter for "All Exceptions" does not work

### ISSUE THREAD

**Issue by guusw** [microsoft/vscode-dotnettools#1552]
### Describe the Issue

No exceptions will be caught at all when the "All Exceptions" breakpoint has a negative condition
(I'm using the unity tools extension)

### Steps To Reproduce

1. Use Unity
2. Set a filter for All Exceptions, e.g. !System.Net.WebSockets.WebSocketException
3. Throw that exception and also some other exception in the code
4. Notice that no exceptions are being caught

### Expected Behavior

Exceptions will trigger except for the specified exception types, as explained by https://code.visualstudio.com/docs/csharp/debugging#_exception-conditions

### Environment Information

Extension: v1.0.4
Unity: 2022.3.47f1

**Comment by jbevain** [comment]
Thanks for reporting this!

**Comment by jbevain** [comment]
Fixed in `1.0.5`. Thanks again!
