### ISSUE TITLE
[BUG] Running the project occasionally results in an error: "Microsoft.Maui.Controls.InvalidNavigationException"

### ISSUE THREAD

**Issue by Jay-57blocks** [microsoft/vscode-dotnettools#1557]
### Describe the Issue

Hi,

When I run the project on M2 macpro, sometimes I get the error, "Microsoft.Maui.Controls.InvalidNavigationException", but when I rebuild it the project runs successfully, I haven't encountered this problem on Vs2022, I just switched to I've just switched to Vscode to develop Maui App, and this issue is affecting our development work, I don't know how to solve it? And it appears from time to time, which is strange

Running the project occasionally results in an error: "Microsoft.Maui.Controls.InvalidNavigationException"

![Image](https://github.com/user-attachments/assets/1c9f5cbb-d325-4650-8c54-e98f950fbd61)

### Steps To Reproduce

I don't know how to reproduce this problem, he only appears when starting the project and not every time, when this problem occurs I just try to rebuild a couple of times and he disappears, looks like a bug in the Vscode maui plugin!

### Expected Behavior

I expect to start the maui project normally

### Environment Information

![Image](https://github.com/user-attachments/assets/4fa988fd-1f73-4805-9388-30b4776aea62)
![Image](https://github.com/user-attachments/assets/f8bf24e6-3f4e-44e7-bfd2-4f05248b6ec0)
![Image](https://github.com/user-attachments/assets/df7add0d-8fb8-4360-acff-aa5a61740db8)

**Comment by emaf** [comment]
@Jay-57blocks this looks like a runtime issue, could you report this in the .NET MAUI repo? https://github.com/dotnet/maui

Here we track issues for the .NET MAUI VS Code extension.
