### ISSUE TITLE
[Blue][NETSDKE2E] [Loc] the documentation for methods and for parameters is not localized.

### ISSUE THREAD

**Issue by yinjiehe01** [microsoft/vscode-dotnettools#1558]
### Describe the Issue

The documentation for methods and for parameters is not localized. 
Repro on Simple Chinese, Japanese, German and Turkish.
![Image](https://github.com/user-attachments/assets/b85c3fd0-58cf-42c9-a97e-9fa7461e3ed8)

### Steps To Reproduce

1.Install VS Code from [Download Visual Studio Code - Mac, Linux, Windows](https://code.visualstudio.com/download#)
2.Install C# and CDK.
3.Create a console app and open it.
4.Check the documentation for methods and for parameters.

### Expected Behavior

The documentation for methods and for parameters.

### Environment Information

C# 2.54.10: https://dev.azure.com/dnceng/internal/_build/results?buildId=2567569&view=results
C# Devkit 1.12.34: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=10448324&view=results
OS: Linux
VS Code:1.42.2
.NET install tool:2.2.1

**Comment by Cosifne** [comment]
This is not a bug now. I believe these strings are directly fetched from the xml file generated by the compilation.
It directly shows the content the developer typed in the code, which most likely would be English.
