### ISSUE TITLE
Add possibility to provide settings to define .runsettings or arguments for unit test execution with C# Dev Kit

### ISSUE THREAD

**Issue by evilbaschdi** [microsoft/vscode-dotnettools#156]
### Describe the feature you'd like

Since some of our unit tests require special environment variables to be set before test execution we decided adding a ".runsettings" file containing some RunConfigurations which is working fine with visual studio and azure devops agents.

So it would be very nice if we had the possibility to define the path of that file do be considered while execution.
OR
Add the possibility to define arguments added to the "dotnet test" execution.

(Target: dotnet test -s .runsettings)

**Comment by evilbaschdi** [comment]
...or is there any workaround for the moment to get things running?
maybe providing an "*.env" file containing environment variable?

**Comment by peterwald** [comment]
Related to #554

**Comment by broomstick73** [comment]
I think I'm running into the same issue, VS Code w/ C# Dev Kit extension with a c# dotnet core project and the "dotnet.unitTests.runSettingsPath" within settings.json seems to be ignored if I set it. What am I doing wrong? the runsettings file doesn't show up in the terminal window when I using the UI to execute tests.

**Comment by peterwald** [comment]
C# Dev Kit has been updated to support .runsettings files using the same setting that C# uses. `dotnet.unitTests.runSettingsPath`

**Comment by evilbaschdi** [comment]
I'll accept that as a solution once it's working ;-)
We have the following structure:

- Main Folder
  - .vscode Folder
    - settings.json
  - Dummy.sln
  - .runsettings
  - Dummy.Core Folder
    - Dummy.Core.csproj
  - Dummy.Core.Tests Folder
    - Dummy.Core.Tests.csproj
  - Dummy.Spec Folder
    - Dummy.Spec.csproj
  - Dummy.Spec.Tests Folder
    - Dummy.Spec.Tests.csproj

Inside that settings.json I'v already defined

`{
    "dotnet.defaultSolution": "Dummy.sln",
    "dotnet.unitTests.runSettingsPath": ".runsettings"
}`

And I also played around with variations of defining thet runSettingsPath. None of them got my tests working.

I'm currently running on C# Dev Kit v1.1.14
What exactly to I do wrong? :-)

**Comment by peterwald** [comment]
@evilbaschdi my apologies. The fix is not included in v1.1.14. I must have just missed the cutoff. It should be in the next prerelease.

**Comment by evilbaschdi** [comment]
I found time to test it again today. it's working now! great stuff 👍

**Comment by broomstick73** [comment]
did this make it to the release yet?

**Comment by peterwald** [comment]
> did this make it to the release yet?

I believe it is in the prerelease version as of right now.

**Comment by MikeSchulze** [comment]
This took my days to find out why my `.runsetting` was not load!
Please add this tho the official documentation, but I'm happy now I get it running.

**Comment by CricutMike** [comment]
> did this make it to the release yet?

Seems like this is still only in the Pre-Release version. I could not get it to work with v1.1.16 of the Release version, but it is working with v1.2.5 of the Pre-Release version.

**Comment by dgtvan** [comment]
I am sorry guys,

I just jumped into runSettings things. How can I tell that C# Dev Kit executes unit test cases with a custom runSettings loaded? Is there any message output somewhere? I couldn't find it.

I was not sure the runSettings was wrong or C# Dev Kit just ignored the runSettings.

Here is my project structure and the runSettings file.
![image](https://github.com/microsoft/vscode-dotnettools/assets/20492454/7db2d21d-5959-4f68-9811-a55ee0f35dea)

`<?xml version="1.0" encoding="utf-8"?>

<RunSettings>
  <RunConfiguration>
     <ResultsDirectory>.\VanTestResults</ResultsDirectory>
  </RunConfiguration>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <CodeCoverage>
            
            

            

            
            <ModulePaths>
              <Include>
                <ModulePath>.*\.dll$</ModulePath>
              </Include>
              <Exclude>
                <ModulePath>.*\\[^\\]*(DataProvider|Contract|Entities|Eml|NUnit|Test)[^\\]*\.dll</ModulePath>
              </Exclude>
            </ModulePaths>

			<Sources>
				<Exclude>
					<Source>.*cshtml.*</Source>
					
				</Exclude>
			</Sources>

            

            
            <UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>
            
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
            
            <CollectFromChildProcesses>True</CollectFromChildProcesses>
            
            <CollectAspDotNet>False</CollectAspDotNet>

          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
`

Was that `dotnet.unitTests.runSettingsPath` configured the wrong way?

**Comment by ChristoWolf** [comment]
I am also still not fully sure how it works with this extension in VS Code, but I usually use the `ResultsDirectory` as a reference to see if the `.runsettings` were correctly applied.

**Comment by peterwald** [comment]
@dgtvan There should be a log entry in the "C# Dev Kit - Test Explorer" pane that shows what run settings file is being used (if any).

![image](https://github.com/microsoft/vscode-dotnettools/assets/5578/21f33ef0-ce96-49af-8a0b-16abcd8c9c85)

**Comment by ChristoWolf** [comment]
@peterwald: Yeah I completely forgot to check that again, thanks for the hint!
