### ISSUE TITLE
[BUG] C# Dev kit - File Permanently Deleted When Moved to Same Directory

### ISSUE THREAD

**Issue by vanasis** [microsoft/vscode-dotnettools#1572]
### Describe the Issue
When attempting to move a file to the same directory in the C# Dev Kit, the file is deleted permanently instead of remaining in place. This unexpected behavior leads to data loss if the action is unintentional.

### Steps To Reproduce

Drag and drop a file within the same directory in the C# Dev Kit.
Observe that the file is deleted permanently.

### Expected Behavior

The file should remain in the same directory without being deleted.

### Environment Information

C# Dev Kit version: [v1.11.14]
OS: [Windows server 2019]

**Comment by webreidi** [comment]
@Jxwoon can you take a look at this please?

**Comment by Jxwoon** [comment]
Thanks for reporting this issue. A fix has been made in the pre-release version 1.14.8. Please try it out and let me know if you continue to experience any issues!
