### ISSUE TITLE
[BUG] No output recorded after unit testing using xUnit

### ISSUE THREAD

**Issue by sharpchen** [microsoft/vscode-dotnettools#159]
### Describe the Issue

No output recorded after unit testing.

### Steps To Reproduce

1. I'm using xUnit.
2. example code
```csharp
using Xunit;
using Xunit.Abstractions;

interface IAdapteeCannotImpl
{
    string DoWork();
}
sealed class Adaptee
{
    public string DoSpecialWork() =>
        $"Hello from {this.GetType().Name}!";
}
class Adapter : IAdapteeCannotImpl
{
    private readonly Adaptee _adaptee = new();
    public string DoWork() => _adaptee.DoSpecialWork();
}
static class ExistingImpl
{
    public static string DoWorkWith(IAdapteeCannotImpl obj) => obj?.DoWork()!;
}

public class AdapterTest
{
    private readonly ITestOutputHelper? _helper;
    public AdapterTest(ITestOutputHelper testOutputHelper) => _helper = testOutputHelper;

    [Fact]
    public void Test()
    {
        Adapter adapter = new();
        _helper!.WriteLine(ExistingImpl.DoWorkWith(adapter));
    }
}
```

3. Run the test, no output recorded.
![image](https://github.com/microsoft/vscode-dotnettools/assets/77432836/4f7574bd-6c86-498e-82dd-a7db92573f25)

### Expected Behavior

This test works fine in Visual Studio.

### Environment Information

- Windows 10
- Visual Studio Code 1.79.2
- Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 0.1.103
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit

**Comment by lucky51** [comment]
The output is displayed when the test fails.

![image](https://github.com/microsoft/vscode-dotnettools/assets/27793729/c87bdd73-b009-4fdb-8a49-8762792255cd)

**Comment by NebulousPsychology** [comment]
Seconded. my attempts to view output text from `ITestOutputHelper` have so far led me to three or four config-ways including .runsettings, and launch/task shenanigans. None are quite as basic as I'd hoped, and some are ignored or conflict with others. Simplest was a competing test explorer extension that allows direct access to the arguments of `dotnet test`.

**Comment by lucky51** [comment]
Is there any news about this?

**Comment by yedajiang44** [comment]
No progress or reply

**Comment by NebulousPsychology** [comment]
I have observed that output is currently logged and viewable **when a test fails**, but I'm still interested in an option to force output that doesn't alter the expressed logic of the test

**Comment by ocallesp** [comment]
##989 should fix this issue

**Comment by yedajiang44** [comment]
> Check the `C# Dev Kit - Test Explorer` output as xUnit may log it there.

I don't see any output from `ITestOutputHelper`

**Comment by timheuer** [comment]
@AbhitejJohn as we mentioned in chat, let's use this as the main tracking issue -- as output doesn't seem to be showing even in error conditions and/or for MSTest or other frameworks.

**Comment by peterwald** [comment]
This is now fixed and will be in an upcoming pre-release.

**Comment by timheuer** [comment]
Related after playing with test output:

- https://github.com/microsoft/vscode/issues/214287
- https://github.com/microsoft/vscode/issues/214286

**Comment by yedajiang44** [comment]
> Related after playing with test output:
> 
> * [Standard output appended to test results disappears when selecting test run vscode#214287](https://github.com/microsoft/vscode/issues/214287)
> * [Test output not visible in test results tab in light mode vscode#214286](https://github.com/microsoft/vscode/issues/214286)

Thank you!I was just about to update it. I think I'll have to wait for a suitable version

**Comment by timheuer** [comment]
@yedajiang44 check out the pre-release version now (1.8.8) 

https://github.com/user-attachments/assets/53fc2dd8-9535-4e2f-b66a-06c15813ee6f
