### ISSUE TITLE
[Green][NETSDKE2E] [Loc] "Add .NET Aspire Orchestration (Preview)" does not localize.

### ISSUE THREAD

**Issue by yinjiehe01** [microsoft/vscode-dotnettools#1594]
### Describe the Issue

"Add .NET Aspire Orchestration (Preview)" does not localize
![Image](https://github.com/user-attachments/assets/54adf567-5a68-41b4-84e8-47a4f9d04e69)

### Steps To Reproduce

1.Install VS Code from [Download Visual Studio Code - Mac, Linux, Windows](https://code.visualstudio.com/download#)
2.Install C# and CDK.
3.Create a project and open it in VS Code.
4.Right click the project in solution explorer.

### Expected Behavior

"Add .NET Aspire Orchestration (Preview)" should be localized.

### Environment Information

C# 2.56.15: https://dev.azure.com/dnceng/internal/_build/results?buildId=2577025&view=results
C# Devkit 1.13.8: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=10524583&view=results
OS: Linux
VS Code:1.95.2
.NET install tool:2.2.2
Affect language: TK JP SC DE

**Comment by AbhitejJohn** [comment]
@yinjiehe01 : Could you please log this issue here instead: https://github.com/dotnet/aspire/issues?

**Comment by yinjiehe01** [comment]
@AbhitejJohn I have reported the issue instead
https://github.com/dotnet/aspire/issues/6647
