### ISSUE TITLE
[BUG] Publishing MAUI App to the Store - The newly created provisioning profile is not listed, but the old ones are, and the "Download manual profiles" process has been done from Xcode.

### ISSUE THREAD

**Issue by Raul-fc** [microsoft/vscode-dotnettools#1595]
### Describe the Issue

I am trying to publish my MAUI app, but the newly created provisioning profile is not showing up, although the old ones that are about to expire are listed. I have Xcode 16, Visual Studio 2022, and Visual Studio Code installed.

I followed the process of 'Request a certificate from a certificate authority' from Keychain Access, then created the distribution certificate, identifier, provisioning profile, and created the app in App Store Connect.

Then, from Xcode, I linked my account and performed the "download manual profiles" process.

I created a MAUI project in Visual Studio 2022 and another one in Visual Studio Code using the '.NET MAUI - Archive / Publish tool' extension, and added 'ApplicationTitle', 'ApplicationId', and 'ApplicationGuid' in the .csproj file.

Then, from Visual Studio 2022, in the properties under iOS, Bundle Signing, I tried adding the 'Signing Identity', but the created provisioning profile does not show up in the Provisioning Profile section.
![Image](https://github.com/user-attachments/assets/bd1d957e-6d43-4b34-a9d6-ba030a109359)

In VSCode using the '.NET MAUI-Archive/Publish tool' extension, after running 'Maui Archive: Publish iOS', selecting the .csproj, and choosing a signing identity, the newly created provisioning profile is also not shown.

![Image](https://github.com/user-attachments/assets/2a1b6f7a-d3d5-4971-a9f6-47851e9febfb)

**Comment by AllenD-MSFT** [comment]
Publishing operations in Visual Studio aren't covered here in this issue list. Instead one should use the Feedback mechanism in Visual Studio to report issues there. This problem of downloading profiles is a known issue I believe and a fix should be made available as an update to Visual Studio soon I hope.
