### ISSUE TITLE
Top Known Issues

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#16]
See [C# Dev Kit FAQ](https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_project-system) for updated list of issues and workarounds.

**Comment by katiesavage** [comment]
Adding Walkthrough fails to launch on mac #155

**Comment by Phantom-thought** [comment]
C# dev kit is not getting installed in vs code

**Comment by timheuer** [comment]
> C# dev kit is not getting installed in vs code

Can you please provide more info on a new issue? @Phantom-thought

**Comment by timheuer** [comment]
Unpinning and closing generic issue here. FAQ and other issues/iteration plans should track better now.

**Comment by Phantom-thought** [comment]
> > C# dev kit is not getting installed in vs code
> 
> Can you please provide more info on a new issue? @Phantom-thought

The issue has got fixed
But I can't run another C# in the same workspace

**Comment by timheuer** [comment]
> But I can't run another C# in the same workspace

I don't know what this means @Phantom-thought -- please open a new issue regarding this with more detail?
