### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by srivastavdevika764** [microsoft/vscode-dotnettools#1602]
### Describe the Issue

Unable to install SDK in my vscode.

**Comment by AbhitejJohn** [comment]
Please share a few more details on the error you are running into and your environment information. It will also help to understand how the SDK is being installed.

**Comment by AbhitejJohn** [comment]
Closing for now but please feel free to create a new issue with more details when you have them. We'd love to be able to get this working for you.
