### ISSUE TITLE
[BUG] C# DevKit not loading after installing 9.0.100

### ISSUE THREAD

**Issue by rachelkang** [microsoft/vscode-dotnettools#1606]
### Describe the Issue

After installing .NET 9.0.100, I've been having trouble with the following:

- Creating a new .NET project - the command appears in command palette and the Explorer, but clicking on it fails to do anything
- Loading an existing .NET project - solution explorer, launch menu, and other C# Dev Kit things do not load, and I can't load/run any projects that were previously successful

This admittedly may be unrelated, but I have been having issues regardless. 

### Expected Behavior

C# Dev Kit loads, .NET projects can be created and loaded, and everything works as usual

### Environment Information

Tried on both the latest release and prerelease versions

**Comment by Michael-Eng** [comment]
@rachelkang can you please share more context - did you install .NET9 runtime or .NET9 SDK? What do you see in the output window?

**Comment by rachelkang** [comment]
Hello - I am no longer experiencing this issue after deleting all my workloads and reinstalling just 9.0.100.

For context, it turned out to be caused by installing an internal version of 9.0.100 prior to public release - something got wonky there and made it incompatible with C# Dev Kit. This was from a Mac Sequoia 15.1.

**Comment by Michael-Eng** [comment]
Thanks for the response. Internal versions of .NET require you to turn on workingWithTestSignedSdk in VS Code to allow you to use prerelease versions of .NET.

**Comment by rachelkang** [comment]
good to know for future context! thanks for the info
