### ISSUE TITLE
C#DevKit runs dotnet restore continuously

### ISSUE THREAD

**Issue by scottbeech** [microsoft/vscode-dotnettools#1609]
Type: <b>Bug</b>

Open any solution in VSCode with C#DevKit. It repeatedly/continuously runs dotnet restore.  As soon as it finishes running, it runs it again immediately: It takes about 2 seconds to run, and then it immediately runs again, even though no code changes have been made.

Extension version: 1.13.9
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin x64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 8, 8|
|Memory (System)|64.00GB (10.23GB free)|
|Process Argv|--crash-reporter-id 96445813-7d03-4baa-a200-86e55f86b512|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by scottbeech** [comment]
After updating a few packages that were issuing warnings/errors, it was still re-running the restore over and over.

After a few restarts of VSCode, it seems to have settled down.  I'm thinking that there is some state getting set when a restore error occurs, that isn't getting reset.

At a minimum, it would be nice to have a way to turn off this auto-running of restore. it doesn't add any value for me — I'd prefer the restore only happen when I explicitly ask for it. A bulky IDE/OS that is running processes in the background and taxing my CPU is the reason I use avoid VS/Windows, and use VSCode/Mac.  I'm worries that C#DevKit is recreating that bulk within VSCode.

Please turn down the frequency of the restore auto- execution, or let us adjust the frequency (including turning it off entirely).  And this would go for any background processing. Please keep the C#DevKit as minimally invasive as possible.

**Comment by scottbeech** [comment]
This is happening again. No errors on the NuGet restore. If I open the solution, then choose Build from the solution explorer, C#DevKit starts running restore repeatedly.

How do I make it stop?

**Comment by kartheekp-ms** [comment]
Given that dotnet restore is caused by an external component, I am removing the `area-nuget` label from this issue. If my understanding is correct, BuildHost.dll is managed by the Roslyn team. Hence, I have added the `area-roslyn` label to this issue.

**Comment by dibarbet** [comment]
@scottbeech can you attach the 'C#' trace logs here (see https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#collecting-general-logs)

The build host should only ever run when C# Dev Kit is not enabled, unless you have some component using MSBuildWorkspace as a tool.

**Comment by kitingChris** [comment]
This issue still persists. Why is there no option to disable auto restore? 
I have a project which I code on locally but the nuget feed is behind authentication and I just dont want to get anoyed by the restore topic since I dont need the nuget packages at the time I work with the project (devops topics not dotnet coding)
