### ISSUE TITLE
[BUG] Aspire 9 on macOS 15.1 won't launch due to "The JSON-RPC connection with the remote party was lost before the request could complete."

### ISSUE THREAD

**Issue by quoctuancqt** [microsoft/vscode-dotnettools#1626]
### Describe the Issue

This is the same as with this issue [https://github.com/dotnet/aspire/issues/6701](https://github.com/dotnet/aspire/issues/6701).

### Steps To Reproduce

1. macOS 15.1
2. updated aspire templates
3. dotnet 9.0.1
4. mkdir aspire-starter-test
5. cd aspire-starter-test
6. dotnet new aspire-starter
7. VS Code with C# DevKit v1.13.9
8. Right click on .AppHost project and select Debug -> Start New Instance

### Expected Behavior

On F5 the AppHost and related projects will start successfully without an error of "The JSON-RPC connection with the remote party was lost before the request could complete."

**Comment by quoctuancqt** [comment]
> Running into the same issue. I'm also unable get more details or logs on what's going on.

I found a workaround to resolve this problem by installing the latest .Net 8 SDK and Runtime. By the way, I only want to focus on .Net 9 without .Net 8 SDK/Runtime

**Comment by JeffreyM** [comment]
> > Running into the same issue. I'm also unable get more details or logs on what's going on.
> 
> I found a workaround to resolve this problem by installing the latest .Net 8 SDK and Runtime. By the way, I only want to focus on .Net 9 without .Net 8 SDK/Runtime

I can confirm the same worked for me.

**Comment by WardenGnaw** [comment]
This was an issue with a certificate within the Aspire system.

See https://github.com/dotnet/aspire/issues/5860
