### ISSUE TITLE
[BUG] Warning about nullable despite Nunit.Analyzers

### ISSUE THREAD

**Issue by eraserix** [microsoft/vscode-dotnettools#1637]
### Describe the Issue

In a unit test class that sets up members during "[SetUp]", VS Code displays the warning CS8618 (must contain non-null value). The code works as expected (dotnet format, dotnet test). Rider does not show this warning for the same test class.

### Steps To Reproduce

1. Add a field with an object inside a test class
2. Add reference to Nunit analyzers through Directory.Packages.props, Directory.Test.props
3. Initialize the field inside the [SetUp] Method.

### Expected Behavior

The Nunit.Analyzers contain a [suppressor rule](https://docs.nunit.org/articles/nunit-analyzers/NUnit3002.html) that should suppress that warning about null if field is initialized in [SetUp].

### Environment Information

- OS: Linux, Ubuntu 22.04
- dotnet 8.0.404 (unpacked tar.gz, available on $PATH through direnv)
- VS Code 1.95.3
- C# Dev Kit 1.13.9

**Comment by dibarbet** [comment]
@eraserix there was an issue with suppressors that we fixed in 2.59.14 (prerelease) - would you mind trying it and let me know if it fixes the issue?

**Comment by eraserix** [comment]
@dibarbet  Yep, problem is fixed by using v2.59.14 (pre-release). THX!
