### ISSUE TITLE
[BUG] .net new iOS project does not support debugging

### ISSUE THREAD

**Issue by GregHDC** [microsoft/vscode-dotnettools#1654]
### Describe the Issue

When creating a new .net iOS application project in vscode, the resulting project does not support debugging within vs code.

### Steps To Reproduce

In vscode on a Mac, with .net 9 installed, and c# devkit extension installed.

In command pallete choose .net new project...
Then choose iOS Application
Specify a project name and a folder
Create the project

Attempt to launch the project.   No launch config created.

Select main.cs and choose "Debug project associated with this file"

Vs code displays some output in terminal then creates this error:
'/Users/gregh/ios2/iOSApp1/iOSApp1.csproj' does not support debugging. No launchable target found.

(note that `dotnet run` in a terminal launches the app. It appears this is a devkit issue not a .net installation issue) 

### Expected Behavior

I expected a debuggable project to be created.   Preferably with a launch.json as we're using a vscode extension. 

### Environment Information

MacOs Sequoia 15.1.1

VS Code
> Version: 1.95.3 (Universal)
> Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
> Date: 2024-11-13T14:50:04.152Z
> Electron: 32.2.1
> ElectronBuildId: 10427718
> Chromium: 128.0.6613.186
> Node.js: 20.18.0
> V8: 12.8.374.38-electron.0
> OS: Darwin arm64 24.1.0
> 

C# devkit extension Version: v1.13.9

**Comment by mauroa** [comment]
Hi @GregHDC, can you confirm if you have the .NET MAUI extension installed? To work with .NET iOS and also MAUI projects, you need this extension and not only the C# DevKit one.
Thanks

**Comment by GregHDC** [comment]
Thank you @mauroa , I did not have the .NET MAUI extension installed.

Installing the extension, and the work around from https://github.com/xamarin/xamarin-macios/issues/20813 has allowed me to progress.
