### ISSUE TITLE
Ability to manage and run android devices

### ISSUE THREAD

**Issue by thomak-dev** [microsoft/vscode-dotnettools#1661]
Type: <b>Feature Request</b>

They should also run automatically when you have a Android device emulator target selected and press F5

Currently you get "error XA0010: Selected device is not running." when you try that

Extension version: 1.5.34
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by mauroa** [comment]
Assigning to @tondat to take a first look
