### ISSUE TITLE
[BUG] Method parameters are not indented

### ISSUE THREAD

**Issue by eraserix** [microsoft/vscode-dotnettools#1664]
### Describe the Issue

Method parameters on multiple lines don't seem to be properly indented. Indenting works as expected inside of a method.

### Steps To Reproduce

The following code is not changed by the formatter (Ctrl+Shift+P -> Format Document or "dotnet format")

```csharp
Console.WriteLine("Hello, World!");
Blup("a", "b");

static void Blup(string a,
 string b)
{
    Console.WriteLine($"{a}");
    Console.WriteLine($"{b}");
}
```

### Expected Behavior

I would expect that the parameter is indented by one level to my defined indent (so 4 spaces in this example).

So the code should be indented to:

```csharp
Console.WriteLine("Hello, World!");
Blup("a", "b");

static void Blup(string a,
    string b)
{
    Console.WriteLine(a);
    Console.WriteLine(b);
}
```

### Environment Information

- OS: Linux
- VS Code: 1.95.3
- C# Dev Kit: 1.14.18 (pre-release)
- C#: 2.59.14 (pre-release)

**Comment by dibarbet** [comment]
Closing as duplicate.  Related issues on the roslyn side:
https://github.com/dotnet/roslyn/issues/33872
https://github.com/dotnet/roslyn/issues/72208
https://github.com/dotnet/roslyn/issues/53464
