### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by ritheeshkumar17** [microsoft/vscode-dotnettools#1666]
### Describe the Issue

tomuch time takan

**Comment by phil-allen-msft** [comment]
We're sorry you are hitting an issue.  From a look, there don't seem to be the steps or "expected vs actual" we would need to investigate this issue.  @ritheeshkumar17 , can you add details by editing the description or posting a comment so that we can investigate.

**Comment by AbhitejJohn** [comment]
Closing this issue out for now but please do share a little more detail on what you are running into and we'd love to investigate.
