### ISSUE TITLE
[BUG] Debugger stops when stepping through unity code

### ISSUE THREAD

**Issue by guusw** [microsoft/vscode-dotnettools#1672]
### Describe the Issue

Sometimes randomly and seemingly consistently when stepping really fast, the debugger will just randomly detach from unity

### Steps To Reproduce

- Have a long function and put a breakpoint at the start
- Hold F10/F11
- Unity output will show:
```
2024-12-09 14:46:03.654 [error] DebugAdapterTracker: Error: read error
2024-12-09 14:46:03.657 [error] DebugAdapterTracker: Error: write EPIPE
```
- Then debugger will detach

### Environment Information

Unity version: 6000.0.25f1
Unity Extension: v1.0.5

**Comment by jbevain** [comment]
Thanks for reporting this.

Which OS are you running? So far I've been unable to reproduce this on macOS with our extension `1.0.5`, and I've kept F10 pressed a loooong time.

Does this repro for all projects or one project in particular?

**Comment by jbevain** [comment]
Also, if you reproduce easily, could you turn logging on in your launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Unity",
            "type": "vstuc",
            "request": "attach",
            "logFile": "${workspaceFolder}/debug.log"
        }
     ]
}
```

And see if there are exceptions at the end of the debug log file? Thanks!
