### ISSUE TITLE
[BUG] VSCode does not recognize Unity assemblies in Unity framework testing.

### ISSUE THREAD

**Issue by jauntyjocularjay** [microsoft/vscode-dotnettools#1673]
### Describe the Issue

This threw me for a loop, fortunately I have a built-in script inspector so that I didn't go chasing my tail too much.

1. I set up the test via the workflow laid out here: https://docs.unity3d.com/Packages/com.unity.test-framework@1.4/manual/workflow-create-test-assembly.html
1. I set up an assembly definition in the folder that holds the scripts to be tested.
1. Only then will Unity recognize my scripts.

However, even though I have demonstrated that this is working properly in Unity, VSCode is still not recognizing my scripts. 

### Steps To Reproduce

1. Open project in `Unity 6000.0.27f1` 
1. Open VSCode with the Microsoft  extensions installed
    1. Unity
    2. C#
    3. C# Dev Kit
    4. .NET Install Tool 
1. Follow Test setup [instructions](https://docs.unity3d.com/Packages/com.unity.test-framework@1.4/manual/workflow-create-test-assembly.html).
1. Set up an assembly definition in your Scripts folder.
1. Confirm they are working by running tests in Unity
1. Observe when returning to VSCode, the scripts still appear to be missing.
![Image](https://github.com/user-attachments/assets/ea2cfb37-e9ba-4e9b-8c3c-7765f29c1ce6)

`console:`
```
The name 'Radians' does not exist in the current context[CS0103](https://msdn.microsoft.com/query/roslyn.query?appId=roslyn&k=k(CS0103))
``` 

Below I have my working setup attached. Drag and drop it into the "Assets" folder of a new project and you should be good to go.
[ExtractToAssets.zip](https://github.com/user-attachments/files/18062993/ExtractToAssets.zip)

### Expected Behavior

VSCode should not indicate an error where there is no error.

### Environment Information

- Windows 11
- VSCode 1.95.3
- Extensions
  - .NET Install Tool v2.2.3
  - C# v2.55.29
  - C# Dev Kit v1.14.14
  - Unity v1.0.5

**Comment by jbevain** [comment]
Hi there,

Thanks for reaching out.

I must be missing on something as I've been unable to reproduce the issue. Here's what I've done:

1. Create new project in Unity 6
2. Create a Test Assembly in folder Tests
3. Create a "Scripts" folder
4. Add a Box.asmdef containing:
```json
{
	"name": "Box"
}
```
5. Add a Box.cs
6. Reference assembly Box in Tests' asmdef
7. Create a TestBox script in Tests
8. Use Box in TestBox

At this point, I can use Box in TestBox without any problem.

The only thing to remember is that for the code completion to work, the `csproj` files must be generated to reflect the changes in Unity. That's usually done when adding or modifying `.cs` or `.asmdef` files.

Let me know what I'm missing here!

**Comment by jauntyjocularjay** [comment]
Hey thanks for getting back to me so quickly!

So this is weird. After I posted this, I had closed Unity and VSCode, opened them up half an hour later. The problem was gone. Then I closed it again, and the problem was back. It's been over an hour now, and the problem is gone. I have no idea what is happening here.

**Comment by jauntyjocularjay** [comment]
Update:

And now it is doing it with the Assert class, even though it works just fine in the function below it.
![Image](https://github.com/user-attachments/assets/28f99581-e727-48d3-9082-1936c741ba28)
