### ISSUE TITLE
Code highlighting and coloring disappears

### ISSUE THREAD

**Issue by DionKllokoqi** [microsoft/vscode-dotnettools#168]
Type: <b>Bug</b>

After installing the extension and re-opening vs code with a solution, the code highlighting and coloring are missing.

Extension version: 0.1.103
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'wsl+Ubuntu' could not be established
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (8.50GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/noidk/projects/hendrick/product-finder-service --remote=wsl+Ubuntu --crash-reporter-id 00c2181a-455c-4c8e-a23a-a747d5ed5f8c|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+Ubuntu' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|15.49GB (9.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythondjangots:30768919

```

</details>

**Comment by phil-allen-msft** [comment]
@DionKllokoqi , we're sorry you are running into this.  What type of file did you see this in?
