### ISSUE TITLE
Folder path not found

### ISSUE THREAD

**Issue by BlaiseForrester** [microsoft/vscode-dotnettools#1685]
Can anybody please tell me how to assign a folder path to a variable in a dotnet Maui project? Have a folder called names containing txt files each of which is a list of names. Moved the names folder into the project folder. Like to use this folder as data source for my app. Created the console based version of this project already and I did it as follows below:
// declare a variable to store the path of the names folder
string dirPath = Path.Combine(Directory.GetCurrentDirectory(), "names");
// declare an array to store the names of the txt files in the names folder
string[] fileNames = Directory.GetFiles(dirPath, "*.txt");
Only trouble is it is not working in the Maui project saying that it cannot find the source.

**Comment by AbhitejJohn** [comment]
@BlaiseForrester : Thanks for reaching out. Could you also share how you configure the source? 
/cc: @AllenD-MSFT

**Comment by emaf** [comment]
Hi, the MAUI SDK team will be able to assist you with this problem if you report it in https://github.com/dotnet/maui/issues.

Thanks!
