### ISSUE TITLE
[BUG] C# Dev Kit in not installable with VS Code version 1.70.0

### ISSUE THREAD

**Issue by TSAVogt** [microsoft/vscode-dotnettools#169]
### Describe the Issue

I wanted to install C# Dev Kit in VS Code and got the following dialog:
![image](https://github.com/microsoft/vscode-dotnettools/assets/88434473/cf09fe44-a74e-4150-9160-bf85e8d1141f)

### Steps To Reproduce

1. search plugin
2. Click install
3. Dialog from above appears

**Comment by timheuer** [comment]
@TSAVogt that is correct, we require minimum VS Code 1.76.0.

**Comment by TSAVogt** [comment]
Yes, sorry thought that I have kept VS Code up-to-date by chocolaty. But this was not the case!
