### ISSUE TITLE
[BUG] Remove repo link on VS Code marketplace page

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-dotnettools#17]
### Describe the Issue

On the [marketplace page](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit) we should not show the `repo` link since it goes to an internal page

You should just be able to remove `repository` in the `package.json` to update this

**Comment by mjbvz** [comment]
Also needed for https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp

**Comment by AArnott** [comment]
This has been fixed for the next csdevkit release.

**Comment by tmeschter** [comment]
Removing "area-project" as this is unrelated to the project system or Solution Explorer.

**Comment by lacomc** [comment]
This has also been fixed for the next IntelliCode for C# Dev Kit release! Thanks
