### ISSUE TITLE
[BUG] C# debugger not working in Release Configuration 

### ISSUE THREAD

**Issue by byIbrahimAli** [microsoft/vscode-dotnettools#1703]
### Describe the Issue

https://github.com/user-attachments/assets/7208b703-ebc3-44a4-8bf1-1e3f055e0b45

I'm using the C# Dev Kit extension. I've opened a new command line project and am trying to hit a breakpoint. Following https://code.visualstudio.com/docs/csharp/debugging it should be as simple as setting the breakpoint and selecting 'Run and Debug'. But it isn't. 

I've reran the code with different text to make sure it isn't running on an old save file or something, it runs with the latest changes. 

The objective is to hit that breakpoint in the video. 

### Steps To Reproduce

1. On MacOS 15.1.1 (24B91) with VS Code 1.96.2 open a new VS Code window
2. Start a new .net project selecting the command line preset
3. Add code around the console.write statement
4. Set a breakpoint on the console.write statement
5. Run and debug the code

**Comment by WardenGnaw** [comment]
It looks like you are trying to debug a `Release` configuration. This makes it difficult for the debugger to map source line information to assembly. Do you see this behavior when you are in the `Debug` configuration?

In the status bar at the bottom, the configuration is set to ![Image](https://github.com/user-attachments/assets/07256630-874d-4574-88b3-715c84f14369)

**Comment by byIbrahimAli** [comment]
Funny now I've recreated the same project I don't see Release at the bottom and the debugger works fine. Sorry! I have no idea what I did to get that to appear (or what that even does). 

User error, debugger working smooth and chugging along 🚂
