### ISSUE TITLE
[BUG] Using the C# extension pre-release looses semantics colors

### ISSUE THREAD

**Issue by Samuel-Therrien-Beslogic** [microsoft/vscode-dotnettools#183]
### Describe the Issue

Current stable version:
![image](https://github.com/microsoft/vscode-dotnettools/assets/84519004/c5a756c9-4611-4fc9-bc5c-174a71d5e4a4)

Pre-release version (needed for C# dev kit):
![image](https://github.com/microsoft/vscode-dotnettools/assets/84519004/93c878b3-0a49-43b0-af4f-e62ac1d26127)

### Steps To Reproduce

1. Install C# language support extension, non-prerelease, see colored code
2. Install C# Dev Kit and C# (prerelease) extensions
3. Reload window, see colored code for a second
4. Most of the code looses its semantic colors

### Expected Behavior

As before

### Environment Information

- OS: 10.0.22621 Build 22621
- VSCode: 1.76.1 (user setup)
- ms-dotnettools.csharp: v2.0.212
- ms-dotnettools.csdevkit: v0.1.103
- ms-dotnettools.vscodeintellicode-csharp: v0.1.9
- ms-dotnettools.vscode-dotnet-runtime: v1.6.0

VSCode settings:
```jsonc
{
  "[csharp]": {
    "editor.defaultFormatter": "ms-dotnettools.csharp"
  },
  "csharp.format.enable": false,
  "csharp.referencesCodeLens.enabled": true,
  "csharp.semanticHighlighting.enabled": true,
  "omnisharp.autoStart": true,
  // Should be disabled for Unity
  "omnisharp.useModernNet": false,
  "omnisharp.enableEditorConfigSupport": true,
  "omnisharp.enableRoslynAnalyzers": true,
  "omnisharp.organizeImportsOnFormat": true,
  "dotnet.implementType.insertionBehavior": "atTheEnd",
  // Must be disabled if using the C# Dev Kit
  "dotnet.server.useOmnisharp": false
}
```

**Comment by tmeschter** [comment]
Moving to "area-roslyn" for the initial investigation.

**Comment by dibarbet** [comment]
Transferred to https://github.com/dotnet/vscode-csharp/issues/5849
