### ISSUE TITLE
[BUG] It breaks CodeLens settings

### ISSUE THREAD

**Issue by hbenvenutti** [microsoft/vscode-dotnettools#185]
### Describe the Issue

It shows the reference count even if the counter is turned off in the c# extension.

![image](https://github.com/microsoft/vscode-dotnettools/assets/37757152/3efc8299-71b2-4488-82c3-11bcdd16a460)

![image](https://github.com/microsoft/vscode-dotnettools/assets/37757152/a6b7f337-38d2-4c18-a778-cbc26b477e7c)

I don't know if the cause is the dev kit, or the pre-release C# extension used by it.

### Steps To Reproduce

1 - It happens as soon as the dev kit extension is enabled.

### Expected Behavior

Not to turn on the reference count in code lens.

### Environment Information

OS: Ubuntu 22.04

VSCode: v1.79.2 

Dev Kit:  v0.1.103

**Comment by damian-kos** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/106775028/717e2cba-2f22-4463-82b3-419a7346d14b)
For me it doesn't show other references for fields.

Windows 11

VSCode: v1.81.0

Dev Kit: v0.3.21

**Comment by yangmingxian** [comment]
> ![图像](https://user-images.githubusercontent.com/106775028/258245952-717e2cba-2f22-4463-82b3-419a7346d14b.png) 对我来说，它没有显示字段的其他参考。
> 
> 视窗11
> 
> VSCode：v1.81.0
> 
> 开发套件：v0.3.21

same issue here...

**Comment by webreidi** [comment]
This seems to be fixed. If you are still experiencing this issue, please reopen this issue.
