### ISSUE TITLE
[BUG] Add new file class doesn't pick up the correct class name

### ISSUE THREAD

**Issue by fiqriismail** [microsoft/vscode-dotnettools#188]
### Describe the Issue

When you add a new class to the project it doesn't pick up the given file name as the class name.  

Example: 

File name: CalculatorService. cs 
Generated class name: Class

### Steps To Reproduce

See the video 

https://youtu.be/rIv09VlojW0?t=38 

### Expected Behavior

Should generate the correct class name corresponding the file name. 

CalculatorService.cs 

```
public class CalculatorService
{}
```

### Environment Information

- Ubuntu 22.04
- VS Code 1.79.2
-  C# Dev Kit v0.1.103 Preview

**Comment by smitpatel** [comment]
C# class templates were added in SDK version 7.0.2xx. When using SDK below that version, then we insert default content for user where user would have to edit namespace and class name (which is still better than writing out everything).

**Comment by timheuer** [comment]
It would be good to confirm your SDK versions @fiqriismail -- I tried this in a devcontainer (Ubuntu) and the class name is emitted in the template.  I remember earlier we had an issue with templates + linux but that may have been the SDK aspect that @smitpatel is referring to.  `dotnet --info` would be good additional info for this report

**Comment by smitpatel** [comment]
@fiqriismail - Can you upgrade SDK to version 7.0.200 or higher and see if you get class name specified?

**Comment by webreidi** [comment]
This should be working as long as you have SDK version 7.0.200 or higher. Please reopen this issue if you have upgraded the SDK and you are still experiencing this issue.
