### ISSUE TITLE
[BUG] Tests doesn't show under Test Explorer

### ISSUE THREAD

**Issue by fiqriismail** [microsoft/vscode-dotnettools#189]
### Describe the Issue

Unit tests (xUnit) doesn't show in the Tests Explorer. Tried building / rebuilding the projects and the solution didn't work. But when you restart VS Code tests are shown in the Text Explorer.

### Steps To Reproduce

See video 

https://youtu.be/rIv09VlojW0?t=235 

### Expected Behavior

Unit tests should show after building / rebuilding the tests project.

### Environment Information

- Ubuntu 22.04
- VS Code 1.79.2
- C# Dev Kit 0.1.103

**Comment by ivanjx** [comment]
did you try to click the run tests button (second from left)? for me it shows all the tests immediately after clicking that button.
![image](https://github.com/microsoft/vscode-dotnettools/assets/12814796/27441b7d-9083-4394-a9aa-755454bb6141)

**Comment by AbhitejJohn** [comment]
It seems like this is working fine in windows but is failing in this version of ubuntu.

**Comment by peterwald** [comment]
There is a hang in the project system that is causing the test explorer to not receive notifications for the new project. Investigating.

/cc @lifengl

**Comment by peterwald** [comment]
After further testing, in the latest prerelease versions of the extension (C# Dev Kit v0.3.18), this is now working in native Ubuntu, and in WSL using a remote connection.

The hang I was referring to above is only when opening a WSL mounted volume directly from Windows and is being tracked separately.
