### ISSUE TITLE
[BUG] Doesn't support Xunit [Theory]

### ISSUE THREAD

**Issue by lilith** [microsoft/vscode-dotnettools#193]
### Describe the Issue

`dotnet test` passes, but the test pane fails with `System.InvalidOperationException : The test method expected 1 parameter value, but 0 parameter values were provided.`

```
[Theory]
    [InlineData(DeploymentEnvironment.Production)]
    [InlineData(DeploymentEnvironment.Development)]
    [InlineData(DeploymentEnvironment.Staging)]
    public void TestComputedOptions(DeploymentEnvironment environment){}
```

### Steps To Reproduce

Try to run the provided xunit stub method

### Expected Behavior

It should execute properly.

### Environment Information

Using 6/14/2023, 14:57:38 build (not pre-release)

Version: 1.80.0-insider (user setup)
Commit: 636dbcff557af8aa088ae118b1a094dce6632ce7
Date: 2023-06-21T08:26:26.328Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by timheuer** [comment]
Hi @lilith -- I have an xUnit project with `Theory` that is working -- would you mind giving this solution a try to see if there is any diff?: https://github.com/timheuer/TestSolution/blob/main/TestXUnit/MathTests.cs#L5

**Comment by lilith** [comment]
I got "'int' does not contain a definition for 'Should' and no accessible extension method 'Should' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)" 

I then swapped it for Assert.Equals, and it passed - as did the exact code that I posted above that was failing. I verified the VSCode version and xunit version hadn't changed.

I did notice that the extension "last released" date is Last released
6/21/2023, 11:11:00, and I posted this at 10:28am that day... so perhaps it updated in the background between then and now?

**Comment by timheuer** [comment]
> I did notice that the extension "last released" date is Last released 6/21/2023, 11:11:00, and I posted this at 10:28am that day... so perhaps it updated in the background between then and now?

I don't think related, as my test solution is what I've been using for a while.  But I'm glad it's working now.  If you can confirm repeatable success for you now, we can close this out and just watch for any regressions.

**Comment by lilith** [comment]
Maybe it's just VSCode insider being flaky.

**Comment by timheuer** [comment]
> Maybe it's just VSCode insider being flaky.

Could be? Okay to close for now?

**Comment by lilith** [comment]
Yes, thank you

**Comment by timheuer** [comment]
Thanks! Closing as no longer repro for now. Thanks for reporting!
