### ISSUE TITLE
[BUG] spelling error on license popup window

### ISSUE THREAD

**Issue by brianloss** [microsoft/vscode-dotnettools#208]
### Describe the Issue

On the license popup, there is a spelling error...
![image](https://github.com/microsoft/vscode-dotnettools/assets/5400335/b2acfea1-faab-4211-bbe1-6e0e0a45a9ba)
Note that it says "Visual Stutio" and not "Visual Studio"

### Steps To Reproduce

1. Click on the "C#" icon at the bottom of the window

**Comment by timheuer** [comment]
This was fixed in latest pre-release.  Thanks for pointing it out!
