### ISSUE TITLE
[BUG] "Command not found"

### ISSUE THREAD

**Issue by JVimes** [microsoft/vscode-dotnettools#21]
### Describe the Issue

I don't see devkit in the VSCode UI (welcome screen, solution explorer, etc.) and commands via palette give "command not found":

> command 'csdevkit.openSolution' not found
> command 'csdevkit.addNewProject' not found

### Steps To Reproduce

1. Install csdevkit 0.1.83
2. Open a "hello world" .NET 6 console app from VS

### Expected Behavior

Solution explorer shown

### Environment Information

- OS: Windows 10 22H2 (OS Build 19045.3031)
- VSCode: 1.78.2
- Extension: 0.1.83

**Comment by JVimes** [comment]
If I switch C# extension to pre-release version (v2.0.206) then the error is gone. C# Dev Kit seems to install with v1.25.9 of the C# extension.

**Comment by timheuer** [comment]
> If I switch C# extension to pre-release version (v2.0.206) then the error is gone. C# Dev Kit seems to install the v1.25.9 of the C# extension. Dependency config issue?

Glad you found this -- currently this is a point in time while C# v2 is still pre-release. We show a prompt that pre-release is needed but perhaps that got dismissed quickly.  Apologies and we're working quickly to get the v2 of C# out of pre-release.  

I'm closing this as resolved as this is the current state.

**Comment by JVimes** [comment]
Thanks! Where does the prompt appear? I just remove and re-installed and still missed it.

**Comment by tkoenig89** [comment]
Same here. I installed everything as described. Latest Pre-Release but none of the new commands work. For example signin for devkit:
![image](https://github.com/microsoft/vscode-dotnettools/assets/1177652/dd20c4e9-366e-445a-9908-2b4f7db3ef58)

Same issue with VS Code and VS Code Insider

Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302

Version: 1.79.0-insider (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302

Date: 2023-06-07T14:26:54.152Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23471

**Comment by tkoenig89** [comment]
Pretty strange is, that i switched to my other computer (above is my surface studio laptop) and here everything works on first try. Installed everything the same way.

SystemInfo:

Version: 1.79.0 (system setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

The only difference i can see really is, that on the laptop vs code has lots more extensions, but thats why i tried the VS Insider version where i only installed C# Pre-Release and DevKit.
