### ISSUE TITLE
Build Task output in "Output" in stead of "Terminal"

### ISSUE THREAD

**Issue by ohopstad** [microsoft/vscode-dotnettools#213]
Type: <b>Feature Request</b>

when I start a dotnet build by right-clicking a project/solution and clicking "build", the output now comes in the "Terminal". I feel like the "Output" tab would be a more logical place for the output.

Thank you for taking the time to read this, no problem if you can't get to it. 

Extension version: 0.1.103
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by lifengl** [comment]
@adrianvmsft : i wonder the tool should not use shell/terminal to build, which can be sensitive to specific shell user wants to use.

**Comment by adrianvmsft** [comment]
Thank you for the suggestion, I am considering whether the build should stop using the shell integration because of other issues. That may address this as well.

**Comment by lifengl** [comment]
this has been fixed
