### ISSUE TITLE
IDE asked to report a "Project system ran into an unexpected problem" issue

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode-dotnettools#215]
Type: <b>Bug</b>

This is the file vscode-insiders opened when I agreed to report the issue

```log
=====================
30/06/2023 14:58:17
LimitedFunctionality
System.AggregateException: Project system data flow 'DataflowBlockSlim (ActionBlockSlimSync`1 : 18082393)' closed because of an exception: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The JSON-RPC connection with the remote party was lost before the request could complete.)))))))))))))))). (The JSON-RPC connection with the remote party was lost before the request could complete.)
---> (Inner Exception #0) StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type expectedResultType, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.Server.BuildManagerServerAdapter.Microsoft.VisualStudio.ProjectServices.IBuildManager.ExecuteBuildRequestAsync(BuildRequestData buildRequestData)
<--- (Inner Exception #0) 
===================

```

Extension version: 0.1.103
VS Code version: Code - Insiders 1.80.0-insider (7406a9bdfca18f82a3977ba5eac908d41df7ccac, 2023-06-30T05:37:52.506Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 4833a52a-ed11-4d5d-b549-6ace2400b2b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30780429
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30779712
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by solrevdev** [comment]
![Screenshot 2023-06-30 at 14 58 30](https://github.com/microsoft/vscode-dotnettools/assets/374863/b9219df0-ca92-4500-a75b-44b197bfa6dc)

**Comment by lifengl** [comment]
@solrevdev : can you try your scenario with a recent update (pre-release) C# Dev Kit to see whether it still runs into the problem.  We noticed some NuGet packages will crash the design time build hosting process when it did in-proc build, when it sets to build everything out of proc, the problem disappeared. This could be the issue you saw earlier.

**Comment by solrevdev** [comment]
Hi @lifengl

Actually, to be honest I've not seen that issue for a while now, so as far as I am concerned this issue is closed. Thank you so much for looking into this and fixing it. Much appreciated.

Thanks
John
