### ISSUE TITLE
Test Explorer displaying duplicate tests

### ISSUE THREAD

**Issue by Anderus14** [microsoft/vscode-dotnettools#217]
Type: <b>Bug</b>

1. Open VS Code
2. Install extension C# Dev Kit
3. Open Test Explorer

Test project structure and execution are unusual (forced by company policy), there are 2 projects in single solution with 3 classes each. All classes contain the same set of tests which are executed in modules.

Actual result:
Tests in Test Explorer are duplicated with 2 tests each, first test works properly but the second one is erroring with a message: "An error occurred attempting to run tests: Error: The given key 'c:\Users\user\AutomatedTests\TestProject\bin\Debug\TestProject.dll' was not present in the dictionary.". 
In case of using 'Go to Test' in Test Explorer, it takes user to the same test method for both correctly working test and duplicate.
When trying to run all tests the message above is displayed everytime and it's not executed.

Expected result:
Tests in Test Explorer are correctly displayed as 1 each test and there's no error message while running them.

Extension version: 0.1.103
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (45.02GB free)|
|Process Argv|--crash-reporter-id 0ec2544d-b708-4e11-8c77-d6f2cd4ae29c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxptcf:30772540
pythonnocebcf:30776496

```

</details>

**Comment by AbhitejJohn** [comment]
@Anderus14 : Thank you for reporting this to us. Any chance you have a sharable sample that repros this problem for us?

**Comment by Anderus14** [comment]
@AbhitejJohn: Hi, it's not possible to for me to share it directly as it's closed repository. Could you please tell me if there's a way to do it without sharing sample of it? Or what sample could I deliver to let your progress with fixing it?

**Comment by AbhitejJohn** [comment]
I'm trying to see if we can replicate this correctly - "there are 2 projects in single solution with 3 classes each. All classes contain the same set of tests which are executed in modules.". If we have a solution with a similar structure as the closed source code (without any of the business logic) that would be fantastic.  The things I'm trying to answer with that info are:
- What do the projects themselves contain? Project properties, build configuration etc.
- What does this entail exactly - "All classes contain the same set of tests which are executed in modules."?

**Comment by Anderus14** [comment]
> * What do the projects themselves contain? Project properties, build configuration etc.
What is the easiest way to share it?
Framework: .net 7.0

> * What does this entail exactly - "All classes contain the same set of tests which are executed in modules."?
There are classes with test cases where test's steps are implemented, then there are at least 3 classes where each test is used, for example, test case is implemented in method called WebLoginCases() in LoginTestCases.cs. This test is used in RegressionTest.cs, MobileTest.cs, ParallelTests.cs where are directly executed.

I'm wondering if the issue is caused by recent updated from .net framework 4.8 to .net 7.0.

If it's not enough info please let me know if there's anything I can do.

**Comment by Anderus14** [comment]
@AbhitejJohn: I'm closer to figuring out what is going on. I have made Test Explorer to show 4 test references instead of 2 like it was in the beginning. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/12641983/35d4f4b4-70a3-43f1-9600-9f3f81d23e74)

Only one reference can be executed and the rest of the shows the same error message when run but for each of there's different path.

![image](https://github.com/microsoft/vscode-dotnettools/assets/12641983/8de21634-80c5-4019-b35b-23eca91201a3)

I did that by updating Base output path in project's properties (I have used Visual Studio 2022), then I have build it and restored it to default path.

![image](https://github.com/microsoft/vscode-dotnettools/assets/12641983/442db273-15ac-4c0a-9141-cda2e835ebad)

**Comment by Anderus14** [comment]
Updated reproduction steps:
1. Open Visual Studio 2022
2. Rebuild project
3. Go into project's properties
4. Go into Build -> Output
5. Change Base output path to any new directory
6. Save and rebuild project
7. Open Visual Studio Code and display Test Explorer

It can be repeated infinite number of times (right now for me it's 6 instances of the same test). Going back to default Base output path doesn't fix and duplicate tests rows are still visible.

**Comment by LynxWall** [comment]
I'm seeing the same issue if I build and test using one target, for example net6.0, and then switch to another target, like net7.0. When I open Test Explorer it's showing tests from the net6.0 build. When I build with net7.0 duplicate tests show up. 

When attempting to run or debug a test if I hit the wrong one it throws an exception that it can't find the assembly under Debug/net6.0/.... Once that happens all tests fail with the same error.

If I run/debug the correct one from my net7.0 build it works. However, even after a successful run if I hit one of the "bad" tests they all start failing again trying to find the assembly under a "net6.0" folder.

I tried deleting bin and obj folders from all builds. If I target the original framework, net6.0, everything works and no duplicates. As soon as I change to another target, doesn't matter what target, I see duplicates and errors.

It looks like the Dev Kit is caching the test assembly reference and hangs on to it for dear life :) 
I've tried clearing Code caches under AppSettings/Roaming ... tried starting with a clean solution. Regardless of what I do, the first build is locked in stone and tests insist on looking for that very first build under the original target folder in the build output, which doesn't exist and throws errors.

Other than this issue I really Love the features with this extension and hope testing issues can be stabilized ASAP. Thanks!

**Comment by LynxWall** [comment]
Follow up from attempting to get past this. I found very similar issues throughout issues listed on this project and they all seem to point back to workspaceStorage  data not being refreshed correctly and the extension holding on to stale/bad data.

I was able to finally get the duplicates removed and tests are running correctly on new target. However, the only way to do that is to close all instances of vscode. Find the testStore in AppData/Roaming/Code/User/workspaceStorage and delete the folder. The DevKit output shows where it's loading the testStore during startup as shown below. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/5261586/3cbd474a-3cc4-49de-82d9-d68f724b10c0)

After deleting the testStore folder, when you open vscode again it will reload the testStore and all is good.

From what I'm seeing in bugs this is a common issue with a lot of different bugs. Data in the workspaceStorage is not being managed correctly and any change to project/solution structure, build targets, etc. all start experience errors and exceptions. The only way to resolve these errors is to delete the testStore folder under workspaceStorage.

Hopefully this is helpful. Thanks!

**Comment by peterwald** [comment]
Changing the target while VSCode is open seems to be handled properly, however if I shut down VSCode, change the target framework and reopen VSCode then I see the duplicate tests.

**Comment by peterwald** [comment]
The fix for this issue has been merged.
