### ISSUE TITLE
[BUG] Razor Formatting no longer works?

### ISSUE THREAD

**Issue by seangwright** [microsoft/vscode-dotnettools#218]
### Describe the Issue

Should Razor formatting be working? It definitely worked _before_ I switched to the new DevKit.

Here's a video reproducing the issue

[vscode-razor-formatting-not-working.webm](https://github.com/microsoft/vscode-dotnettools/assets/1382768/d391f995-e764-4e69-b1fb-bb6d4a395003)

Here are my relevant VS Code workspace settings:

```json
"editor.formatOnSave": true,
"emmet.includeLanguages": {
    "aspnetcorerazor": "html"
  },
  "[csharp]": {
    "editor.defaultFormatter": "ms-dotnettools.csharp"
  },
  "[aspnetcorerazor]": {
    "editor.defaultFormatter": "ms-dotnettools.csharp"
  }
```

I hope I'm logging this issue in the correct repository, but as a related note, I now have a _really_ difficult time understanding which parts of the tooling is controlled by each repository

- https://github.com/dotnet/vscode-csharp/
- https://github.com/microsoft/vscode-dotnettools/
- https://github.com/dotnet/razor
- https://github.com/OmniSharp/omnisharp-roslyn

Maybe it would be a good opportunity for a ASPNET Core Community standup episode for someone to explain all of these for the community. 🤔

### Steps To Reproduce

1. Create a Razor file
2. Author some C# and HTML that should be formattable
3. Format the document
4. See nothing happens

### Expected Behavior

The HTML, Razor and C# is all formatted correctly

### Environment Information

- OS - Windows 11 Pro
- `ms-dotnettools.csharp` - `2.0.248`
- `ms-dotnettools.csdevkit` - `0.2.99`
- VS Code - `1.79.2`
- .NET SDK installed - `8.0.0-preview.5.23280.8`
- `global.json` 
    ```json
    	{
		  "sdk": {
		    "version": "6.0.403",
		    "rollForward": "latestMajor",
		    "allowPrerelease": false
		  }
		}
     ```
- .NET SDK in use `7.0.305`

**Comment by leandro-regis** [comment]
I'm facing the exact same problem, but in my case I notice if I cut the line @model <expected-model-type> and try the formatting command, it works.
It also works if I comment the @model line and run the formatting command, then after formatting I uncomment the line.
So now when I have a .cshtml file and I want to format I cut the line and re-past it, or I comment the @model line and after formatting I uncomment.

Environment Information
- OS - Windows 11 Pro
- ms-dotnettools.csharp - v2.0.328 
- ms-dotnettools.csdevkit - v0.3.21 
- VS Code - 1.81.0
- ..NET SDK in use - 7.0.304

**Comment by allisonchou** [comment]
@webreidi This issue is fixed pending release via https://github.com/dotnet/vscode-csharp/pull/6236, however I don't have permissions to close this issue. Could you do it on my behalf? Thanks!

**Comment by seangwright** [comment]
@allisonchou which extension gets the fix and which version is it fixed in? Is this something I can test in my code today?

**Comment by allisonchou** [comment]
@seangwright The fix should be in today's C# extension release (2.0.436). Could you try the new version and let us know if you still see the problem? Thanks!

**Comment by seangwright** [comment]
Everything looks good now! I can format Razor views and even my `_ViewImports.cshtml` which would completely break after a format previously.

Thanks so much!
