### ISSUE TITLE
[BUG] Type definitions missing on first file open

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode-dotnettools#219]
### Describe the Issue

When a file is first open, some of the type definitions are not known. This causes classes to be syntax highlighted in the wrong color, go to definition to not work, and intellisense to not work.

Possibly related: #30, #151, #210

### Steps To Reproduce

1. `dotnet new mvc -o Repro`
2. In VS Code, open the folder `Repro`.
3. Open `HomeController.cs`. Notice that for a fraction of the second `ILogger` on line 9 shows in the color for a known type, but then changes to the color for an unknown type. Notice that you can't go to its definition.
4. Close `HomeController.cs`.
5. Open `HomeController.cs`. Notice this time, `ILogger` does show in the color for a known type and you can go to its definition.

### Expected Behavior

`ILogger` always shows as a known type, or if its type hasn't been determined yet, it is initially unknown and then quickly becomes known. It should never switch from known to unknown.

### Environment Information

- OS: macOS
- VS Code version: 1.79.2
- C# Dev Kit version: 0.2.99

**Comment by arkalyanms** [comment]
This is a dup of https://github.com/microsoft/vscode-dotnettools/issues/210
