### ISSUE TITLE
.net: New project command produces an error

### ISSUE THREAD

**Issue by saitejam447** [microsoft/vscode-dotnettools#220]
Type: <b>Bug</b>

I'm currently using the C# Dev Kit extension version 0.1.103. When I attempt to create a .net project with an empty folder open in VS Code using the command pallet (Cmd+Shift+P) -> ".net: New Project" command, I get a message box saying that the command produced an error. This happens every time I do it.

Extension version: 0.1.103
VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin x64 19.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 26519d2c-768a-4365-9922-58926ed188da|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxptcf:30772540
pythonnocebcf:30776496

```

</details>

**Comment by timheuer** [comment]
Hi @saitejam447 can you share the error message you are getting?

Also, can you switch to the pre-release version and see if it changes anything?

**Comment by saitejam447** [comment]
Hi,
When I attempt to create a project using the command pallet, I get an error
similar to the following as shown in the screenshot below.
Upgrading to the latest pre-release version did resolve the issue, but
created new ones, the most prominent of which is that once the project is
created or opened, I see in the VS Code status bar that the project failed
to load.

**Comment by saitejam447** [comment]
Hi, it appears that this issue is now fixed in the GA release of the C# Dev Kit extension. Thank you for fixing this issue.
