### ISSUE TITLE
[BUG] Intellisense intermittently breaks when pasting code

### ISSUE THREAD

**Issue by jonathaneckman** [microsoft/vscode-dotnettools#221]
### Describe the Issue

Intellisense intermittently breaks when pasting code.

### Steps To Reproduce

1. Enable C# DevKit, C#, and IntelliCode for C# extensions.
2. Write C# code. In my case, in a .NET 7 Web API, Class Library, or Console App project.
3. Copy paste code. It doesnt matter where its from - a website, your own code base, a notepad.
4. Suddenly blue warning underlines, red error underlines, and intellisense stop working.

   ![2023-07-02_08-17-22](https://github.com/microsoft/vscode-dotnettools/assets/11893200/8c571a60-ee6d-4c7a-af7b-7c8376a14173)

5. Restart the .NET Language Server. No change.
6. Restart Visual Studio Code. All functionality restored.

   ![2023-07-02_08-17-55](https://github.com/microsoft/vscode-dotnettools/assets/11893200/bc816933-6567-4e1b-a4d3-7e0b6b931c3c)

7. Repeat like 30 times a day.

### Expected Behavior

1. The warnings, errors, and intellisense do not break when pasting code. 
2. Alternatively, there is a workaround to "reset" something with the command palette so I dont have to restart VS Code.

### Environment Information

- OS MacOS Ventura 13.3.1 (a)
- VS Code 1.79.2
- Extensions
   - IntelliCode for C# Dev Kit 0.1.23
   - C# 2.0.248
   - C# Dev Kit 0.2.99

**Comment by tmeschter** [comment]
Possibly related to #210.

**Comment by arkalyanms** [comment]
Screenshot suggests metadata references go missing.

**Comment by jonathaneckman** [comment]
I haven't been able to reproduce this since #210 was fixed. I'll close it.
