### ISSUE TITLE
C# DevKit language server does not recognise a method that omnisharp does

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode-dotnettools#224]
Type: <b>Bug</b>

In the normal VS Code I run the normal C# extension that uses OmniSharp and in VS Code Insiders I am trying out the pre-release C# extension that uses the C# Dev Kit Language Extension. 

The C# Dev Kit language server does not recognise a method that the normal C# OmniSharp version does. So ones says 0 references and other correctly 1 reference.

Also, the OmniSharp version is finding empty blank lines that can be removed, methods that can be made static and various other refactoring items that appear in my problems tab that can be resolved whereas the new dev kit lang server version does not.  

I have restarted the dev server, restarted the IDE but same result.

Will upload some screenshots to highlight.

Extension version: 0.1.103
VS Code version: Code - Insiders 1.80.0-insider (5b7440441bbd2548a862f7321cafdfa1597132e5, 2023-06-30T21:17:11.593Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-r . --crash-reporter-id 4833a52a-ed11-4d5d-b549-6ace2400b2b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30780429
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30779712
dsvsc013:30777762
dsvsc014:30777825

```

</details>

<details>
<summary>Extra info that may be useful</summary>

```bash
▲ solution.projectname [master] dotnet --version
7.0.305
▲ solution.projectname [master] dotnet --info
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: arm64
  Commit:       4b0550942d

.NET SDKs installed:
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/solrevdev/Projects/solution.projectname/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
▲ solution.projectname [master] dotnet --list-sdks
7.0.305 [/usr/local/share/dotnet/sdk]
▲ solution.projectname [master] dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
▲ solution.projectname [master] computer_info
solrevdev@macmini-2020.local
----------------------------
OS: macOS 13.4.1 22F82 arm64
Host: Macmini9,1
Kernel: 22.5.0
Uptime: 1 hour, 57 mins
Packages: 358 (brew)
Shell: zsh 5.9
Resolution: 2560x1440, 2560x1440
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: CascadiaMonoPL-Regular 16
CPU: Apple M1
GPU: Apple M1
Memory: 3059MiB / 16384MiB

▲ solution.projectname [master] cat global.json
{
    "sdk": {
        "allowPrerelease": false
    }
}
```
</details>

**Comment by solrevdev** [comment]
**VS Code Insiders with C# Dev Kit:**

0 references however I expect 1 reference so not correct.

![vscode-insiders-csharp-devkit](https://github.com/microsoft/vscode-dotnettools/assets/374863/f78e561b-596e-4601-9cb0-e329375d11e7)

**VS Code with C# OmniSharp:**

1 references and I expect 1 references so correct.

![vscode-omnisharp](https://github.com/microsoft/vscode-dotnettools/assets/374863/4947db08-4223-4cfd-8a74-6c73355b03db)

**VS Code with C# OmniSharp showing items in problems tab (C# Dev kit's problems tab is empty):**

This is correct, I expect this however the VSCode Insiders C# Dev Kit with language server version is empty. It should look like this:

![vscode-omnisharp-problems-tab](https://github.com/microsoft/vscode-dotnettools/assets/374863/ca2a24dc-c570-4202-8780-d740fcca08e4)

**Comment by ckming102** [comment]
Having the same issue as well.

**Comment by dibarbet** [comment]
> **VS Code Insiders with C# Dev Kit:**
> 
> 0 references however I expect 1 reference so not correct.
> 
> ![vscode-insiders-csharp-devkit](https://user-images.githubusercontent.com/374863/250858301-f78e561b-596e-4601-9cb0-e329375d11e7.jpg)
> 
@solrevdev
I see in your screenshot that the server restarted (from the output window log).  Unfortunately there is currently a bug where when the C# server restarts, its not able to get the project information again from Devkit.  The workaround here is to reload the window instead of restarting the language server itself.  Bug tracking this - https://github.com/dotnet/vscode-csharp/issues/5882

If you're hitting this on a first start though, that indicates an unknown bug.  Could you let me know if that is the case?

**Comment by webreidi** [comment]
@solrevdev @ckming102 We have made lots of improvements in the C# Dev Kit and the C# extension over the past month. Please update the latest version and reopen this issue if you are still experiencing this problem.

**Comment by solrevdev** [comment]
@webreidi Apologies for not replying sooner, a bit swamped at the moment. If this bug reappears I'll reopen otherwise thank you very much for fixing it. Much appreciated 🙏🏼️
