### ISSUE TITLE
[LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode-dotnettools#226]
Type: <b>Bug</b>

I get the warning notification (I'll upload a screenshot as comment next): 

"Intellicode for C# Dev Kit will not show line completions because copilot is enabled"

I also get the following error in the C# output window:

```bash
Dotnet path: /Users/solrevdev/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.8/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
[Error - 12:26:57] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136

```

Extension version: 0.1.103
VS Code version: Code - Insiders 1.80.0-insider (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T11:01:44.989Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-r . --crash-reporter-id 4833a52a-ed11-4d5d-b549-6ace2400b2b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30780429
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30779712
dsvsc013:30777762
dsvsc014:30777825

```

</details>

<details>
<summary>Extra info</summary>

```bash
▲ solutionname.projectname [master] clear
▲ solutionname.projectname [master] dotnet --version
7.0.305
▲ solutionname.projectname [master] dotnet --info
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: arm64
  Commit:       4b0550942d

.NET SDKs installed:
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/solrevdev/Projects/solutionname.projectname/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
▲ solutionname.projectname [master] dotnet --list-sdks
7.0.305 [/usr/local/share/dotnet/sdk]
▲ solutionname.projectname [master] dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
▲ solutionname.projectname [master] cat global.json
{
    "sdk": {
        "allowPrerelease": false
    }
}
▲ solutionname.projectname [master] computer_info
solrevdev@macmini-2020.local
----------------------------
OS: macOS 13.4.1 22F82 arm64
Host: Macmini9,1
Kernel: 22.5.0
Uptime: 3 hours, 24 mins
Packages: 358 (brew)
Shell: zsh 5.9
Resolution: 2560x1440, 2560x1440
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: CascadiaMonoPL-Regular 16
CPU: Apple M1
GPU: Apple M1
Memory: 2915MiB / 16384MiB
▲ solutionname.projectname [master]
```
</details>

**Comment by happysammy** [comment]
I encountered the same issue on M1 chip Mac.
![activateerror](https://github.com/microsoft/vscode-dotnettools/assets/6129408/91f8243f-ba2e-4dcf-8935-005c78f3d977)

**Comment by dibarbet** [comment]
If anyone is encountering this issue I could use some additional information:
1.  Set the `dotnet.server.trace` setting to `Trace`
2.  Reproduce the issue
3.  Zip up the contents of the extension log directory (can be found by running the vscode command 'Open Extension Logs Folder') and attach them here (or send to my Microsoft email, linked in my github bio if you don't feel comfortable sharing them publicly).

**Comment by dibarbet** [comment]
And 1 more request as well (particularly to anyone who hit this recently, e.g. @happysammy ) - please let me know what version of CDK you're using.

**Comment by yoieh** [comment]
Getting this popup too.
![image](https://github.com/microsoft/vscode-dotnettools/assets/5743837/15fcc78c-3121-4254-8de2-3311e551bad3)

Here are the logs:
[exthost.zip](https://github.com/microsoft/vscode-dotnettools/files/12244541/exthost.zip)

Not sure of the sdk version that the project would be trying to use it's a Unity project.
But here's the output from dotnet --info.
```
PS> dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by austincrft** [comment]
I am seeing this error, but I am still getting autocomplete suggestions and copilot suggestions. I've just been ignoring the error

**vscode version:** v1.80.2
**c# extension version:** v2.0.328
**cdk extension version:** v0.3.21

**Comment by webreidi** [comment]
The pop-up related to disabling of IntelliCode's line completions is an expected message. It lets you know that we are prioritizing Copilot's line completions, instead of IntelliCode's line completions as we've found them to be more helpful in most cases. 

For those experiencing the language server host error, please update to the latest version of the C# extension and C# Dev Kit and then:

1. Set the dotnet.server.trace setting to Trace
2. Reproduce the issue
3. Zip up the contents of the extension log directory (can be found by running the vscode command 'Open Extension Logs Folder') and attach them here (or send to my Microsoft email, linked in my github bio if you don't feel comfortable sharing them publicly).

**Comment by arkalyanms** [comment]
The LS restart issue is tracked at https://github.com/microsoft/vscode-dotnettools/issues/238. I understand this is slightly older, but that issue has more specifics on the action items being taken to solve this. So planning to dup this to that.

**Comment by solrevdev** [comment]
> If anyone is encountering this issue I could use some additional information:
> 
> 1. Set the `dotnet.server.trace` setting to `Trace`
> 2. Reproduce the issue
> 3. Zip up the contents of the extension log directory (can be found by running the vscode command 'Open Extension Logs Folder') and attach them here (or send to my Microsoft email, linked in my github bio if you don't feel comfortable sharing them publicly).


Sorry for the delay but have just emailed you my log directory plus the contents of the C# output tab as a seperate .txt file (via the email linked to in my github bio)

**Comment by EthanSK** [comment]
i have this issue
