### ISSUE TITLE
[SUGGESTION] Add refactorings: extract interface and implement interface

### ISSUE THREAD

**Issue by Casimodo72** [microsoft/vscode-dotnettools#227]
### Describe the feature you'd like

"Extract interface" and "implement interface" are in my list of every day's top refactorings in VS 2022, so it would be great to have those in VS Code too.

If you consider to add those refactoring helpers: please add an option to disable alphabetical sorting of members.

Althouth I find those refactorings and options quite important, VS 2022 seems to have only half-hearted support for this: for "implement interface" there is an obscure option in VS to disable alphabetical sorting. For "extract interface" there is no option in VS 2022 that I'm aware of. I'm using ChatGPT for the latter due to this fact nowadays (the chat guy must already be annoyed with me)).

**Comment by tmeschter** [comment]
Moving to area-roslyn.
