### ISSUE TITLE
[BUG] c# dev kit - high memory usage

### ISSUE THREAD

**Issue by romaluca** [microsoft/vscode-dotnettools#229]
### Describe the Issue

If i open a my solution with 100 projects in Visual Studio 2022, the memory usage is about 1.2GB
If i open the same solution with vs code, the memory usage is about 4GB

**Comment by Wavesolid** [comment]
waiting for this solution aswell

**Comment by lifengl** [comment]
move to the Roslyn side.  I opened Roslyn solution in C# Dev Kit, the project system process memory usage reaches 650M, then it reduces below 300M after some GC.  At the same time, the language server process started with 7.7G memory usage, and later falls to 4G.  Based on that, the project system is using similar amount of memory as it was in VS, but the language service seems to use way more than expected.

**Comment by ivanjx** [comment]
my project is around 150kloc and i get around 4-7gb of memory use (linux)
