### ISSUE TITLE
Hyphen in email address breaks subscription validation regex

### ISSUE THREAD

**Issue by theAeon** [microsoft/vscode-dotnettools#231]
Type: <b>Bug</b>

The extension seems to be reporting that it can't find a visual studio subscription at "robbins@outlook.com" which, while probably correct, is not the email address I linked. "andrew-robbins@outlook.com" *does* have a community subscription and the regex seems to be dropping everything hyphen and prior.

Extension version: 0.1.103
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.56GB free)|
|Process Argv|--crash-reporter-id 5c3b85fe-7fd0-4556-8acc-f6b2913fe254|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by timheuer** [comment]
@theAeon Can you confirm the message you are seeing? After logging in are you seeing something that says "No subscription" found? -- any snapshot of what you are seeing is helpful.  We had a bug where the message indicating a valid _personal_ license made it seem there was no valid license found.  That was fixed...but I want to make sure where you are seeing this trimmed text we can look at.

**Comment by theAeon** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/9099529/79836de7-6cde-4e43-bbcb-1a3750699cf8)


Likely a pure visual bug now.

**Comment by theAeon** [comment]
Unsure when this was fixed, but it appears to be working now (as of 0.5.150 at least)
