### ISSUE TITLE
Spaces and special chars in user profile/home path cause load issues

### ISSUE THREAD

**Issue by umitkara** [microsoft/vscode-dotnettools#24]
Type: <b>Bug</b>

Paths with special characters do not work.
[info] Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-c:\Users\├£mit does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Extension version: 0.1.83
VS Code version: Code - Insiders 1.79.0-insider (aee52551e25d98391f9064996196cd83a9fc8669, 2023-06-06T15:00:13.166Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.39GB free)|
|Process Argv|--crash-reporter-id cb2318ba-c2fe-427d-8f0d-166dfc258bc2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263cf:30754470
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887
pythonnosmt12:30757129

```

</details>

**Comment by timheuer** [comment]
Hi @umitkara just confirming this is the error message you get *because* you have special characters in path, correct?  Do you have an example of the path characters?

**Comment by thomaslevesque** [comment]
I have the exact same error, but I don't have special characters in the path.

```
2023-06-06 21:46:49.321 [info] Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-c:\Users\Thomas does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

2023-06-06 21:46:51.325 [info] Project system initialization finished. 0 project(s) are loaded, and 2 failed to load.
```
Note that my actual profile folder is "C:\Users\Thomas Levesque", which is truncated in the error text above (but even if it wasn't, it still wouldn't make sense...)

**Comment by timheuer** [comment]
@thomaslevesque and to confirm you merely were opening a folder? or trying to execute a specific command?

**Comment by timheuer** [comment]
@thomaslevesque @umitkara I tried a path with spaces and an umlaut but I'm on en-US and everything worked fine.  I'm curious:
- Any specific locale OS
- Any specific language/region settings?

**Comment by arkalyanms** [comment]
Its likely the SDK install path that is sensitive to the space or special characters. A straight forward solution folder with special chars does not repro. 

The first dotnet command in question that is falling over here might be the restore thats triggered as a part of the load.

Since its Dev Kit project load failing, starting with @Michael-Eng

**Comment by arkalyanms** [comment]
Sidenote: @timheuer might be easier to give me access to this repo. We need to add a new label for area-projectsystem and a new milestone for CDK Preview 2.

**Comment by timheuer** [comment]
@arkalyanms done -- you should have already been there with the roslyn team, but added directly -- also have `area-project` already which I added the tag.

**Comment by thomaslevesque** [comment]
> and to confirm you merely were opening a folder? or trying to execute a specific command?

Yes, just opening the folder

> Any other characters in your path other than a space?

No, no special chars beside that space

> Language on the system?

en-US (but with fr-FR regional format)

**Comment by thomaslevesque** [comment]
Looks like there's a pattern here... we all have a space in our profile folder name.

**Comment by timheuer** [comment]
> Looks like there's a pattern here... we all have a space in our profile folder name.

Yeah it's weird a space in just the path (e.g. project name) has no issue for me...spinning up some new windows profiles now ;-)

**Comment by timheuer** [comment]
Okay, also was able to repro -- space in _profile_ seems to be the key here (not anywhere in the path oddly).  Just created a new profile with the same and see the same issue here now.

**Comment by thomaslevesque** [comment]
Ah, I just did the same test
Created two new profiles:
- "John Doe" => same error
- "JaneDoe" => works fine

**Comment by y-chen** [comment]
I am getting the same error and I have a dot in my profile folder. But that should be fine right? .Net projects always had dots in the project names like `ProjectName.Api`, `ProjectName.Database` etc.

If it can be useful, I am using MacOS in English with EN keyboard. Brand new VSCode (insider) installation.

**Comment by thomaslevesque** [comment]
@timheuer any news about this? Is a fix coming soon?

**Comment by timheuer** [comment]
I believe @Jxwoon is looking at it.

**Comment by thomaslevesque** [comment]
Thanks for the update @Jxwoon!

**Comment by Chizaruu** [comment]
Greats news!

**Comment by Jxwoon** [comment]
An update to the extension was released. Please let me know if the issue persists.

**Comment by thomaslevesque** [comment]
Works for me. Thanks!

**Comment by y-chen** [comment]
I have updated C# Dev Kit extension to v0.2.7 and reloaded vscode.

When I try to open a project in the solution explorer section, I get the error `A compatible .Net SDK was not found`. In the output tab I get the following logs:

```
2023-06-21 19:48:21.213 [info] Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/y.chen/.vscode-insiders/extensions/ms-dotnettools.csdevkit-0.2.70-darwin-arm64/components/CPS/platforms/darwin-arm64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-arm64/Microsoft.VisualStudio.ProjectSystem.Server.BuildHost.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/y.chen/.vscode-insiders/extensions/ms-dotnettools.csdevkit-0.2.70-darwin-arm64/components/CPS/platforms/darwin-arm64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-arm64/Microsoft.VisualStudio.ProjectSystem.Server.BuildHost.dll'

2023-06-21 19:48:39.133 [info] Project system initialization finished. 0 project(s) are loaded, and 19 failed to load.
```

The repo is in my user folder (`y.chen`).

The solution opens with other IDEs.

Am I missing something?

**Comment by Michael-Eng** [comment]
@y-chen your issue appears different. I would log a separate issue, but I would ask you to confirm you have .NET 7 installed and can run dotnet.exe successfully from a terminal to confirm it's working.

**Comment by umitkara** [comment]
Hi all. 
@Michael-Eng @Jxwoon it seems like the issue has resolved. The extension can restore the solutions now.
Thanks for help and all your efforts.
👏

**Comment by Chizaruu** [comment]
It doesn't work for me, sadly 😢 

```
2023-06-22 05:18:26.617 [info] Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-a:\Users\Abdul does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

2023-06-22 05:18:28.496 [info] Project system initialization finished. 0 project(s) are loaded, and 16 failed to load.
```

**Comment by y-chen** [comment]
@Michael-Eng ah okay. I was searching for the error message I got and I ended in this thread.

No, I actually don't have .Net 7.0 installed, but .Net 6.0 as my project is using the LTS version.

**Comment by Jxwoon** [comment]
Closing this issue because C# Dev Kit pre-release v0.2.70 addresses spaces and special characters in the user profile/home path. For other issues, please log a separate bug. Thanks!
