### ISSUE TITLE
[BUG] C# Dev Kit - Test Explorer Testhost process for source exited with error: A fatal error occurred, the required library hostfxr.dll could not be found

### ISSUE THREAD

**Issue by shyamasndr** [microsoft/vscode-dotnettools#240]
### Describe the Issue

When I open a solution with xunit tests, the test explorer fails to discover the tests and the output log shows below error. I have DOTNET_ROOT environment variable pointing to the folder C:\Softwares\Dev\dotnet where the .net sdk's  6.0.411, 7.0.305 are installed. 

```shell
Created Test Controller
Using vstest from dotnet sdk in [C:\Softwares\Dev\dotnet\sdk\7.0.305].
Initialized Test Explorer Server [4816]
Test Store Folder: c:\Softwares\Dev\code\data\user-data\User\workspaceStorage\a5aefa17c132965f8e46758b1e6d449d\ms-dotnettools.csdevkit
Test data store opened in 0.152 sec.
Initialized project system provider.
2 projects added, 0 changed, 0 removed.
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process for source(s) 'c:\src\MyApp\Tests\MyApp.Application.Test\bin\Debug\net6.0\MyApp.Application.Test.dll' exited with error: A fatal error occurred, the required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [c:\src\MyApp\Tests\MyApp.Application.Test\bin\Debug\net6.0\].
If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(IEnumerable`1 sources, Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process for source(s) 'c:\src\MyApp\Tests\MyApp.Application.Hosting.WebApi.Tests\bin\Debug\net6.0\MyApp.Application.Hosting.WebApi.Tests.dll' exited with error: A fatal error occurred, the required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [c:\src\MyApp\Tests\MyApp.Application.Hosting.WebApi.Tests\bin\Debug\net6.0\].
If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(IEnumerable`1 sources, Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
========== Test discovery aborted: 0 Tests found in 1.1 sec ==========
0 tests discovered from  in 1065.4897 ms

``` 

### Steps To Reproduce

Open a solution with xunit tests. 

### Environment Information

- Project .net target version : 6.0
- Installed .net Sdks:  6.0.411, 7.0.305
- vs code version: 1.80.0
- C# dev Kit: v0.1.103

**Comment by seesharprun** [comment]
I was able to resolve this on my local machine by deleting the runtimes in the `AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet` folder.

**Comment by shyamasndr** [comment]
After the deletion, the same problem persists. The C# dev kit has a dependency on the extension ".Net Install Tool for Extension Authors," which downloads back the runtime while opening the VS Code to the folder "ms-dotnettools.vscode-dotnet-runtime.dotnet." However, I do not have .NET Core and VS Code installed in the "C:\Program Files" directory; instead, I have them in separate folders.

Despite the error message suggesting to "use the DOTNET_ROOT environment variable to specify the runtime location," I guess the extension does not respect the DOTNET_ROOT environment variable and instead looks for the .NET Core runtime in "C:\Program Files\dotnet."

**Comment by peterwald** [comment]
Removing from the GA milestone since this is an uncommon setup, with the SDK being installed in a non-standard location without any default SDKs available. We will continue to work with this customer to see if this scenario can be supported long term.

**Comment by lifengl** [comment]
@peterwald :  CDK will set a different DOTNET_ROOT so it can start its processes, but the original user setting will be preserved in DOTNET_ROOT_USER (a special value EMPTY is used, if it is not set earlier).  Before starting any user process, we should recover the user setting to DOTNET_ROOT to prevent tooling environment to corrupt user application setting.

**Comment by peterwald** [comment]
Thanks @lifengl, I have a fix in the works.

**Comment by peterwald** [comment]
A fix has been merged and will be available in the next pre-release build.
