### ISSUE TITLE
Iteration Plan for July 2023

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#242]
Below is the list of items being worked on during July 2023 sprint. Not all items listed below will finish and release in August. 

- [x] https://github.com/microsoft/vscode-dotnettools/issues/90
- [x] https://github.com/microsoft/vscode-dotnettools/issues/134
- [x] https://github.com/microsoft/vscode-dotnettools/issues/228
- [x] https://github.com/microsoft/vscode-dotnettools/issues/110
- [ ] https://github.com/microsoft/vscode-dotnettools/issues/192
- [x] https://github.com/microsoft/vscode-dotnettools/issues/209
- [x] https://github.com/microsoft/vscode-dotnettools/issues/210
- [ ] https://github.com/microsoft/vscode-dotnettools/issues/47

See also, [C# extension July 2023 Iteration Plan](https://github.com/dotnet/vscode-csharp/milestone/30)

**Comment by ivanjx** [comment]
what is the release cycle of the c# extension (pre-release)? i am waiting for [this bug](https://github.com/dotnet/vscode-csharp/pull/5868) that is already fixed to be released. thanks.

**Comment by webreidi** [comment]
@ivanjx We are shooting to release prerelease updates to C# extension on a weekly basis. That particular fix was released in v2.0.249 published on Wednesday, July 12.
