### ISSUE TITLE
[BUG] Unable to start debugging a fresh MAUI project on MacOS

### ISSUE THREAD

**Issue by veler** [microsoft/vscode-dotnettools#244]
### Describe the Issue

I started using the .NET Maui extension. I created a new MAUI project. I can't start it on MacOS.

### Steps To Reproduce

1. On MacOS, after following indications here: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code#macos
1. Create a solution using `dotnet new sln`
1. Open the solution in VS Code.
1. Create a new .NET MAUI project or .NET MAUI Blazor project.
1. Using command palette, `.NET MAUI: Pick macOS Device` and select the first one
![image](https://github.com/microsoft/vscode-dotnettools/assets/3747805/57c266a5-3fb1-4dca-92fb-76b1f487c267)
1. In Solution Explorer, right click on the project, Debug > Start New Instance
1. Wait for the build, and get the following error from "C# Dev Kit (Extension)": `Unable to convert launch target to a vscode debug configuration.`
![image](https://github.com/microsoft/vscode-dotnettools/assets/3747805/b780e48b-b168-4105-a60e-be55eb94b909)
1. The app doesn't start at all :(

### Environment Information

- OS: MacOS
- VS Code Version: 1.80.0
- .NET Version 7.0.306

CPUs	Apple M1 (8 x 24)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg)	4, 6, 6
Memory (System)	8.00GB (0.08GB free)
Process Argv	--crash-reporter-id 2e90b136-1b22-4724-886c-469884facd58
Screen Reader	no
VM	0%
 
Extension	Author (truncated)	Version
path-intellisense	chr	2.8.4
xml	Dot	2.5.1
gitlens	eam	14.0.1
EditorConfig	Edi	0.16.4
copilot	Git	1.95.233
vscode-pull-request-github	Git	0.68.0
aspnetcorerazor-html-css-class-completion	kev	1.0.3
azure-pipelines	ms-	1.208.0
csdevkit	ms-	0.2.99
csharp	ms-	2.0.248
dotnet-maui	ms-	0.1.34
vscode-dotnet-runtime	ms-	1.6.0
vscodeintellicode-csharp	ms-	0.1.26
azure-account	ms-	0.11.5
msbuild-project-tools	tin	0.4.9
vscode-icons	vsc	12.4.0

**Comment by tmeschter** [comment]
Moving to area-maui for initial investigation.

**Comment by maddymontaquila** [comment]
Hi there! If you go into the run/debug menu (the play button with the bug emoji) and select "Run and Debug" from there, does it pop up a list of options for the debugger to choose? Make sure you're selecting ".NET MAUI" and not "C#" - we're still working on integrating with the solution explorer better so I'm wondering if Debug > Start New Instance tries to use the C# debugger and not the MAUI one.

**Comment by veler** [comment]
Hi @maddymontaquila ,

Thanks for your answer here too :) .

> If you go into the run/debug menu (the play button with the bug emoji) and select "Run and Debug" from there, does it pop up a list of options for the debugger to choose?

Yes it does! I selected ".NET MAUI" as your recommended and it works well. I can now debug the project!

Starting the debugger from Solution Explorer is still broken though. I understand this is a work in progress then :)
Good luck with it! :D
