### ISSUE TITLE
[BUG] Building and Starting DevToys 2.0 (MAUI) on MacOS works, but Debugger doesn't attach to it.

### ISSUE THREAD

**Issue by veler** [microsoft/vscode-dotnettools#245]
### Describe the Issue

I'm working on DevToys 2.0 (https://github.com/veler/DevToys).
I'm porting the app on MacOS using MAUI Blazor.
Developing the app using VS for Mac works fine. I gave a try at the .NET MAUI extension for VS Code but I wasn't able to debug it.

### Steps To Reproduce

1. Make sure your machine is running on macOS Ventura 13.1 or later.
1. Follow the instructions to setup .NET MAUI on Mac: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code#macos
1. Make sure .NET SDK `7.0.306` is installed.
1. Install [Node.js](https://nodejs.org/).
If you're using an [Mac computer with Apple silicon processor](https://support.apple.com/en-us/HT211814), install [Rosetta 2](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment) using the following command in a Terminal:
`softwareupdate --install-rosetta`
1. I recommend to restart the computer at this point
1. Clone `DevToys` repository: https://github.com/veler/DevToys
1. Switch to `dev/2.0` branch
1. Run `sh init.sh` in a Terminal.
1. Open the solution [/src/DevToys.MacOS.sln](https://github.com/veler/DevToys/blob/dev/2.0/src/DevToys-MacOS.sln) in VS Code.
1. Using command palette, `.NET MAUI: Pick macOS Device` and select the first one
![image](https://github.com/microsoft/vscode-dotnettools/assets/3747805/57c266a5-3fb1-4dca-92fb-76b1f487c267)
1. In Solution Explorer, right click on the project `app/dev/platforms/desktop/DevToys.MacOS`, `Debug > Start New Instance`.
1. Wait for successful build.
1. DevToys app will successfully start on Mac, but the debugger will fail to work. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/3747805/59ed3fd5-5b49-4128-bf52-1f31e45b1618)

### Expected Behavior

Debugger should be attached, and I should be able to set a breakpoint.

This development environment works fine with Visual Studio for Mac 17.5.5.

### Environment Information

- OS: MacOS
- VS Code Version: 1.80.0
- .NET Version 7.0.306

CPUs Apple M1 (8 x 24)
GPU Status 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) 4, 6, 6
Memory (System) 8.00GB (0.08GB free)
Process Argv --crash-reporter-id 2e90b136-1b22-4724-886c-469884facd58
Screen Reader no
VM 0%

Extension Author (truncated) Version
path-intellisense chr 2.8.4
xml Dot 2.5.1
gitlens eam 14.0.1
EditorConfig Edi 0.16.4
copilot Git 1.95.233
vscode-pull-request-github Git 0.68.0
aspnetcorerazor-html-css-class-completion kev 1.0.3
azure-pipelines ms- 1.208.0
csdevkit ms- 0.2.99
csharp ms- 2.0.248
dotnet-maui ms- 0.1.34
vscode-dotnet-runtime ms- 1.6.0
vscodeintellicode-csharp ms- 0.1.26
azure-account ms- 0.11.5
msbuild-project-tools tin 0.4.9
vscode-icons vsc 12.4.0

> VS bug [#1861167](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1861167)

**Comment by maddymontaquila** [comment]
Thanks for reporting this bug - very interesting. If you build and deploy from the command line does it debug fine? `dotnet build -t:Run -f net7.0-maccatalyst`

**Comment by veler** [comment]
Hi @maddymontaquila,

Thanks for your answer. Yes, using `dotnet build -t:Run -f net7.0-maccatalyst` in the Terminal of VS Code works. The app builds and run. It does not "debug" however. Attaching the process to VS Code doesn't seem to work well either in the manner that it fails to set a breakpoint (it doesn't find symbols).

Again, building, running and debugging work fine in VS for Mac.

**Comment by maddymontaquila** [comment]
Thank you so much for the update @veler this is really helpful! The self contained thing is a known issue, but it shouldn't be blocking the build/deploy/debug. @dalexsoto @rolfbjarne @redth any ideas on why it wouldnt be launching?

**Comment by veler** [comment]
Hi @Redth,

Thanks for looking into this issue. Here is the build log in the Terminal

```
Executing task: dotnet build -t:Build -p:Configuration=Debug -f net7.0-maccatalyst -r maccatalyst-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/etiennebaudoux/.vscode/extensions/ms-dotnettools.dotnet-maui-0.1.34-darwin-arm64/dist/resources/maui/MauiVSCodeBuild.targets" -p:MauiVSCodeBuildOutputFile=/var/folders/bs/q_rs7fzx0ns6576ygy0rszkm0000gn/T/dotnet-maui/maui-vsc-0a905d95-e159-4a28-aa4e-e84c176e9f03.json /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/platforms/desktop/DevToys.MacOS/DevToys.MacOS.csproj 

MSBuild version 17.6.8+c70978d4d for .NET
  Determining projects to restore...
  Restored /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Api/DevToys.Api.csproj (in 134 ms).
  Restored /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Core/DevToys.Core.csproj (in 134 ms).
  Restored /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Business/DevToys.Business.csproj (in 134 ms).
  Restored /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Localization/DevToys.Localization.csproj (in 133 ms).
  Restored /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/DevToys.Blazor.csproj (in 134 ms).
  Restored /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/platforms/desktop/DevToys.MacOS/DevToys.MacOS.csproj (in 134 ms).
/usr/local/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1156,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/platforms/desktop/DevToys.MacOS/DevToys.MacOS.csproj]
/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Api/Tool/GUI/Components/IUIButton.cs(125,32): warning CS0067: The event 'UIButton.IsHyperlinkChanged' is never used [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Api/DevToys.Api.csproj::TargetFramework=net7.0]
  DevToys.Api -> /Users/etiennebaudoux/RiderProjects/DevToys/bin/Debug/AnyCPU/DevToys.Api/net7.0/DevToys.Api.dll
  DevToys.Localization -> /Users/etiennebaudoux/RiderProjects/DevToys/bin/Debug/AnyCPU/DevToys.Localization/net7.0/DevToys.Localization.dll
  DevToys.Core -> /Users/etiennebaudoux/RiderProjects/DevToys/bin/Debug/AnyCPU/DevToys.Core/net7.0/DevToys.Core.dll
  DevToys.Business -> /Users/etiennebaudoux/RiderProjects/DevToys/bin/Debug/AnyCPU/DevToys.Business/net7.0/DevToys.Business.dll
  Generating CSS and JavaScript...
  [18:18:52] Using gulpfile ~/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/gulpfile.js
  [18:18:52] Starting 'devtoysJavaScript'...
  The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
  The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
  end
  [18:18:52] Finished 'devtoysJavaScript' after 117 ms
  [18:18:53] Using gulpfile ~/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/gulpfile.js
  [18:18:53] Starting 'devtoysSass'...
  [18:18:53] Finished 'devtoysSass' after 739 ms
/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/Pages/SubPages/ToolGroup.razor.cs(38,18): warning CA1822: Member 'OnSuggestToolIdeaClick' does not access instance data and can be marked as static [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/DevToys.Blazor.csproj]
/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/Pages/SubPages/ToolGroup.razor.cs(33,18): warning CA1822: Member 'OnOpenInNewWindow' does not access instance data and can be marked as static [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/DevToys.Blazor.csproj]
  DevToys.Blazor -> /Users/etiennebaudoux/RiderProjects/DevToys/bin/Debug/AnyCPU/DevToys.Blazor/net7.0/DevToys.Blazor.dll
  Detected signing identity:
          
    Bundle Id: com.etiennebaudoux.devtoys
    App Id: com.etiennebaudoux.devtoys

Build succeeded.

/usr/local/share/dotnet/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1156,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/platforms/desktop/DevToys.MacOS/DevToys.MacOS.csproj]
/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Api/Tool/GUI/Components/IUIButton.cs(125,32): warning CS0067: The event 'UIButton.IsHyperlinkChanged' is never used [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Api/DevToys.Api.csproj::TargetFramework=net7.0]
/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/Pages/SubPages/ToolGroup.razor.cs(38,18): warning CA1822: Member 'OnSuggestToolIdeaClick' does not access instance data and can be marked as static [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/DevToys.Blazor.csproj]
/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/Pages/SubPages/ToolGroup.razor.cs(33,18): warning CA1822: Member 'OnOpenInNewWindow' does not access instance data and can be marked as static [/Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/DevToys.Blazor/DevToys.Blazor.csproj]
    4 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.62
 *  Terminal will be reused by tasks, press any key to close it.
```

I looked up for the file `/var/folders/bs/q_rs7fzx0ns6576ygy0rszkm0000gn/T/dotnet-maui/maui-vsc-0a905d95-e159-4a28-aa4e-e84c176e9f03.json` but it's empty.

This time, I also noticed the following log in the `Debug Console` in VS Code:

```
SDB 127.0.0.1:49333S -> [DevToys.MacOS (maccatalyst)] /Users/etiennebaudoux/RiderProjects/DevToys/src/app/dev/platforms/desktop/DevToys.MacOS/DevToys.MacOS.csproj
Debugger is ready and listening...
zsh:1: unmatched "
```

> Also do you have any other extensions installed which may be duplicating some of this functionality? Meteor?, Uno?, Comet?

I don't have the ones you mentioned but I have the following:

path-intellisense chr 2.8.4
xml Dot 2.5.1
gitlens eam 14.0.1
EditorConfig Edi 0.16.4
copilot Git 1.95.233
vscode-pull-request-github Git 0.68.0
aspnetcorerazor-html-css-class-completion kev 1.0.3
azure-pipelines ms- 1.208.0
csdevkit ms- 0.2.99
csharp ms- 2.0.248
dotnet-maui ms- 0.1.34
vscode-dotnet-runtime ms- 1.6.0
vscodeintellicode-csharp ms- 0.1.26
azure-account ms- 0.11.5
msbuild-project-tools tin 0.4.9
vscode-icons vsc 12.4.0

I tried disabling every extensions except `IntelliCode for C# Dev Kit`, `C# Dev Kit`, `C#`, `.NET MAUI`, `.NET Install Tool for Extension Authors` but it didn't help.

Please let me know if you need anything else, and think you for helping here. Feel free to reach out on Teams if needed.

**Comment by Redth** [comment]
Ok, so what seems to be happening is that the build target is actually skipped from running because `$(_InvalidConfigurationWarning)` is evaluating to true, which appears to be due to your Directory.Build.props file setting a value for `$(Platform)` when it's expected to not be set.

Platform is an older concept and you should basically avoid it for MAUI.

Try removing this line: https://github.com/veler/DevToys/blob/3f0e0f8bfe3064fb12b5af3608c3903b19f15e4b/src/Directory.Build.props#L19C49-L19C49

**Comment by veler** [comment]
Hi @Redth ,

Thanks for sharing this information. I tried removing the use of Platform, cleaning the `bin` and `obj`, closing the solution and re-open it, build, and start debugging from VS Code. Unfortunately, the result is the same as before. VS Code enters in Debug mode but the app doesn't start at all. The logs in the Terminal and Debug Console are the same than before too.

Here is what I changed:

![image](https://github.com/microsoft/vscode-dotnettools/assets/3747805/7637d2dd-8bf6-40e9-ba2b-817b263684a1)

**Comment by veler** [comment]
Hi,
I keep hitting this issue, which is still preventing me from using VS Code + .NET MAUI extension at full time and I have to rely on VS for Mac (which won't be reliable in a few months). Could we please try to unblock this?

**Comment by AllenD-MSFT** [comment]
@veler , we've recently made improvement to debugging when targeting .NET 8. If you are able to target .NET 8, can you tell us if this issue is resolved? If you can't move to .NET 8, can you check the latest to see if this is still a problem? TIA

**Comment by mauroa** [comment]
Hi @veler, I tried with the latest DevToys main (which I saw it already contained the targeting for net8), but I realized that the project was targeting macos instead of maccatalyst. We support MacCatalyst in .NET MAUI.
I tried re-targeting it, but then I got some build errors about `ResxHelperGenerator.dll`.

As mentioned above, we did many improvements for net8 around debugging, so I encourage you to try with latest .NET MAUI pre-release and see if your issues go away. 
I'm being able to launch and debug maccatalyst apps correctly, so I'll consider this as fixed.

Feel free to re-open it in case you still experience issues, so we can walk through them and see what the problem is.

Thanks for your help and feedback.
