### ISSUE TITLE
[BUG] MAUI: Android license has to be accepted on every restart

### ISSUE THREAD

**Issue by DDHSchmidt** [microsoft/vscode-dotnettools#249]
### Describe the Issue

When reopening my Visual Studio code on MacOS 13.4.1 I'm akes every time to accept the Android licenses. the extension can't seem to remember that I have accepted the license countless times already...

### Steps To Reproduce

1. Start Visual Studio code with an open MAUI solution
2. Accept Android License agreement
3. Restart & The nagscreen about accepting the licenses will reappear

### Expected Behavior

The extension should memorize once I have accepted the license

### Environment Information

- OS: Macos 13.4.1
- VS Code 1.80
- .Net MAUI Extension 0.1.34
- C# Dev Kit Extension 0.1.103
- C# Extension 2.0.248

> VS bug [#1862487](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1862487)

**Comment by timheuer** [comment]
Same, I'm getting this:


https://github.com/microsoft/vscode-dotnettools/assets/4821/1256b8b9-2ca6-4c00-a530-fb4d3d9823f3

**Comment by mcumming** [comment]
If your Android SDK is located in a location that requires elevated permissions, like Program Files, then you will have to run the command from an elevated command prompt. See https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code#theres-an-error-that-android-licenses-arent-accepted for more information

**Comment by maddymontaquila** [comment]
Michael already linked the doc but I'll reiterate the best thing to do might be to navigate to your Android SDK install location and use `sdkmanager --licenses` to manually accept them that way

**Comment by mcumming** [comment]
We've made some enhancements here that should clarify what needs to happen in the Prerelease channel

**Comment by Ghostbird** [comment]
> Insufficient privileges: Please try accepting licenses again after running VS Code as administrator. Alternatively, you can try opening a Terminal as administrator and running: /usr/lib/android-sdk/cmdline-tools/latest\bin\sdkmanager --licenses

Whenevery I run `sudo /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses` it'll tell me:

> All SDK package licenses accepted.

But I can still not build anything as the extension will keep complaining about unaccepted licenses.

**Comment by kazo0** [comment]
I'm having the same issue, this should be reopened as running `sudo /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses` makes no difference

**Comment by Ghostbird** [comment]
I managed to get it working, but I don't know what I did that fixed it. 😢

**Comment by artyomszasa** [comment]
This might help someone:

For me the solution was to remove everything from `~/Android/Sdk/licenses` (or whereever sdk manager stores already accepted licenses) and **then** run `sdkmanager --licenses` and accept everything.

After that everything works as intended...

**Comment by kazo0** [comment]
@artyomszasa you are the true MVP, it seems that having everything accepted prior to the first run of the plugin causes it report as a failure when it attempts to accept the licenses

**Comment by timheuer** [comment]
> @artyomszasa you are the true MVP, it seems that having everything accepted prior to the first run of the plugin causes it to report as a failure when it attempts to accept the licenses

Interesting -- /cc @mcumming wonder if this is something we could validate and harden

**Comment by kazo0** [comment]
Yeah was just a random guess, but it did seem like it wasn't properly checking the exit code of `sdkmanager --licenses`. I'd see it run successfully in the log and then a popup would appear in VS Code telling me an error occurred while trying to accept licenses without any other info. It wouldn't always be the "insufficient privileges" message

**Comment by mcumming** [comment]
@emaf + @tondat

**Comment by policchio** [comment]
In my case, opening VS Code as Administrator (as the error recommended), even though I had accepted all the licenses, it kept giving me the error of accepting the licenses. But then I tried to open VS Code as a normal user and the error disappeared.
