### ISSUE TITLE
[BUG] Project References Using MSBuild Properties Not Recognised

### ISSUE THREAD

**Issue by sbmw** [microsoft/vscode-dotnettools#251]
### Describe the Issue

Project references using MSBuild properties such as `$(MSBuildStartupDirectory)` are not recognised / result in "namespace could not be found" errors.

For example:

```
<ProjectReference Include="$(MSBuildStartupDirectory)\Source\FancyTestClassLib\FancyTestClassLib.csproj" />
```

will build correctly via `dotnet build` and omnisharp, but not with the new LSP.

### Steps To Reproduce

Simple reproduction solution here: https://github.com/sbmw/TestSolutionProjectReference 

Open TestConsole/Program.cs

![image](https://github.com/microsoft/vscode-dotnettools/assets/30099628/f8b94e8a-7c82-4922-af41-52f5cbe1da53)

### Expected Behavior

References are recognised and processed. 

### Environment Information

 - OS: Linux
 - VS Code Version: 1.80.0
 - C# Extension: v2.0.249
 - C# Dev Kit Extension: v0.3.2
 - .NET: 7.0.306 / 7.0.9 (set via "dotnet.dotnetPath")

**Comment by sbmw** [comment]
Edit to add: 

Possibly related to https://github.com/microsoft/vscode-dotnettools/issues/93

Of course the easy workaround is to simplify project references to relative links.  For us the actual use case is to create project templates with generic starter csproj files that contain references such as this in a unit test project:

```
<ProjectReference Include="$(MSBuildStartupDirectory)/Source/$(MSBuildProjectName.Replace('.Tests', ''))/$(MSBuildProjectName.Replace('.Tests', '')).csproj" />
```

Love the new / updated extensions though and we're excited for the new tooling options.

**Comment by tmeschter** [comment]
Moving to area-project-cps as this may have to do with how we run `dotnet build` to build a project or solution.

**Comment by sbmw** [comment]
Thanks @tmeschter, this is great to know.  You're right, `$(MSBuildStartupDirectory)` is unnecessary and we've been getting lucky.  In my real world example  `$(MSBuildProjectName) ` is far more important to our use case and this DOES work as expected!  So I'll go ahead and remove StartupDirectory and close this issue.  Thanks for pointing me in the right direction!
