### ISSUE TITLE
C# Dev Kit does not run tests in any test projects.

### ISSUE THREAD

**Issue by tacosontitan** [microsoft/vscode-dotnettools#253]
Type: <b>Bug</b>

## Steps to Reproduce

1. Open a functional solution with test projects using XUnit.
  a. Locally, my projects are targeting .NET Framework 4.8 in SDK format.
  b. Updating to a new .NET version is not an option.
2. Open the test view.
3. Right click the test project in question.
4. Choose "Run Tests".

## Results

1. New bash terminal opens to represent the task.
2. The following command is executed:
```bash
dotnet build <path_to_repository>\test\project_folder\project.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
```
3. The MSBuild version is printed (`MSBuild version 17.5.1+f6fdcf537 for .NET`).
4. **MSB1009** is encountered saying the project doesn't exist, giving a path with no backslashes present:

```txt
c:UsersMyUsernamesourcereposGlitter.ExtensionstestGlitter.Extensions.TestsGlitter.Extensions.Tests.csproj
```

### Screenshot
![image](https://github.com/microsoft/vscode-dotnettools/assets/65432314/25110d67-6b5d-4904-8675-e8c7ac5105bd)

## Important Notes
I'm currently using `C# Dev Kit v0.2.100`, but I've also tried this with the pre-release and got the same result. My tests were executing just fine earlier this week. I have not explicitly updated versions for anything, but I believe my setup automatically installs updates, IIRC.

Also, running my tests through `dotnet test` works as expected.

## Additional Information

Extension version: 0.3.2
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22624
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (13.25GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/USERNAME/source/repos/github/tacosontitan/Glitter.Extensions --crash-reporter-id 548eac59-3efe-404d-9228-4145b3b1c1ff|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200

```

</details>

**Comment by tacosontitan** [comment]
The repository used to create this issue is [one of my personal projects](https://github.com/tacosontitan/Glitter.Extensions). However, I've verified this same result across all of my repositories.

**Comment by tmeschter** [comment]
@tacosontitan Any chance `<path_to_repository>` (the blacked-out part in the screenshot) contains spaces?

**Comment by tacosontitan** [comment]
That's a negative.

**Comment by tacosontitan** [comment]
That's what has me concerned; I'm not doing anything special and this was working earlier this week, though I can't attest for certain that it didn't always look that way, so it doesn't rule out a visual bug at this point.

**Comment by WileyCorning** [comment]
I have the same issue but found a workaround. My default terminal had been set to Git Bash; after setting the default terminal to Powershell, the build command was executed properly and tests could be run.

My guess is that the extension uses the default terminal to run these commands, but writes path strings using Windows path formatting that is not interpreted properly by Unix-oriented terminals.

---

### Additional Information
Extension version: 0.3.2
VS Code version: 1.80.1
OS version: Windows_NT x64 10.0.22621

**Comment by tacosontitan** [comment]
@WileyCorning,
> after setting the default terminal to Powershell, the build command was executed properly and tests could be run.

Can confirm, the same is true for me; awesome find!

***Note**: I think it's imperative to keep in mind that I previously had no issues with my default terminal being set to Git Bash.*

**Comment by tacosontitan** [comment]
@tmeschter does this still need more info?

**Comment by AbhitejJohn** [comment]
Perhaps there's a better error message/configuration change suggestions we can pop up here.
/cc: @tmeschter

**Comment by jesperkristensen** [comment]
I found a workaround:

In the terminal I see that the task that C# Dev Kit runs is named "dotnet: build". 
In the New Terminal (plus icon) dropdown menu I select Configure Tasks.
In the prompt i select the "dotnet: build" task.
It creates an entry in tasks.json.
I adjust the entry according to https://code.visualstudio.com/docs/editor/tasks#_can-a-task-use-a-different-shell-than-the-one-specified-for-the-integrated-terminal


Or the short version is I added this to my tasks list in `tasks.json`:

```
        {
            "type": "dotnet",
            "task": "build",
            "options": {
                "shell": {
                    "executable": "cmd.exe",
                    "args": [
                        "/d", "/c"
                    ]
                }
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": "build",
            "label": "dotnet: build"
        }
```

And now it works for me.

**Comment by tmeschter** [comment]
@tacosontitan Just to confirm: even after setting the default terminal to PowerShell, you are still unable to run unit tests?

**Comment by duyn9uyen** [comment]
> I'm using git bash as the default terminal on Windows and was having the same issue as OP.
> 
> I ended up adding this to my vscode settings.json:
> 
> ```
>     "terminal.integrated.automationProfile.windows": {
>         "path": "cmd.exe"
>     }
> ```
> 
> Now it works!

This works great and I can still default my terminal to `gitbash`! Thanks.
