### ISSUE TITLE
[BUG] Extensions are not activated

### ISSUE THREAD

**Issue by JotaRata** [microsoft/vscode-dotnettools#254]
### Describe the Issue

With the latest update (C# Dev Kit v0.2.100 and C# v2.0.249) everything has stopped working; the extension seems to be disabled and executing commands like restarting the language server produces an error similar to #225 

vscode apparently is not even aware the extensions are installed because they don't show up neither in the console or thesettings page.

I tried installing .NET SDK 6.0 and 7.0 and didn't work.

### Steps To Reproduce

* Have C# Dev kit version 0.2.100 and C# extension version 2.0.249
* Have .NET SDK version 6 installed
* Have compatibility packages installed in Visual Studio installer
* Have .NET Framework SDK 4.6 installed
* Open a project

### Expected Behavior

Extensions should load normally like before the update

### Environment Information

OS  Windows 11 Home Single Language 22H2
OS Version 22621.1992
Experiencia	Windows Feature Experience Pack 1000.22644.1000.0

.NET 3.5 and 4.8.1 Update for WIndows 11 22H2 (KB5028851)

**Comment by JotaRata** [comment]
Regarding the title:

![imagen](https://github.com/microsoft/vscode-dotnettools/assets/36273501/8d85c67b-b434-4c0d-bfc5-e97a2253b3b5)

**Comment by JotaRata** [comment]
Regarding the title:


(it says version v2.0.248 but that's because I tried rolling back when I took the screenshot but the same result was seen in .249(
![imagen](https://github.com/microsoft/vscode-dotnettools/assets/36273501/c652fc00-109a-441e-b7b3-573d09b79931)

**Comment by JotaRata** [comment]
I don't know if this is related:
![imagen](https://github.com/microsoft/vscode-dotnettools/assets/36273501/d2c6a5ea-693f-40e4-adb5-cfb3915ca0aa)

**Comment by timheuer** [comment]
If you do a full uninstall of the extensions from your environment and reload VSCode and install same errors?  If so, can you share the extension host logs?

**Comment by JotaRata** [comment]
Extension Host logs mentioned a file named "workbench.desktop.main.js" that couldn't be accessed.

I'm currently doing a full reinstall of vscode so the logs were deleted

**Comment by timheuer** [comment]
> Extension Host logs mentioned a file named "workbench.desktop.main.js" that couldn't be accessed.

Yikes.  Hopefully a full install will help get you sorted.

**Comment by JotaRata** [comment]
Clean installing vscode worked now the extensions are running normally!

PS: I wonder what would happen if I sync my old settings back on..

**Comment by JotaRata** [comment]
Whatever it was it seemed related to my install of vscode that's because rolling back to the previous version didn't work but a clean install did.

I don't know if this issue should be closed yet because there was an error after all that may affect more users

**Comment by timheuer** [comment]
I think without a repeatable thing we can look at it isn't something we can triage well.  I'm going to close it for now. The errors you saw were really pre-activation even for us. so something with the host seemed messed up.  We'll close this now that you're working and at least we have retained the error.

If you do choose to sync and that gets you back in this state, let's grab the full extension host logs and re-activate.

**Comment by JotaRata** [comment]
Everything is working properly now. Thanks!
