### ISSUE TITLE
[BUG] <Can't run debug>

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#258]
Can't run debug until `Program.cs` file is not open. So if all scripts are closed and pressing `Ctrl+F5` or `F5` the drop down window does not contains `C#` option:

![01](https://github.com/microsoft/vscode-dotnettools/assets/38082501/6425e5d6-91e0-4fbd-a3ec-814af7ecb4df)

Only `C#` option needed to run debug:

![02](https://github.com/microsoft/vscode-dotnettools/assets/38082501/d0a7c4f7-0b9d-4996-85c1-96851959d173)

**Comment by Michael-Eng** [comment]
What versions of the extensions do you have installed? What OS? Are you able to create a new project?

**Comment by BachiMjavanadze** [comment]
@Michael-Eng 

- OS: Windows 11 Home, 22H2, build: 22621.1848
- CPU: Intel Core i5-10210U
- VSCode version: 1.80.1
- C# Dev Kit Extension version: 0.3.5
- C# Extension version: 2.0.251

I think problem is caused because of debugger behavior: it launches current project. current project is taken from opened script.

**Comment by Michael-Eng** [comment]
Seeing as how you're able to create projects I think this sounds more like a debugger issue so I'm changing to that area.

**Comment by WardenGnaw** [comment]
This is how VS Code handles `dynamic` configurations. It requries a specific language file to be in focus. 

We can look into seeing activating dynamic providers without having a language in focus.

**Comment by WardenGnaw** [comment]
This is an external issue.

Related: https://github.com/microsoft/vscode/issues/193828
