### ISSUE TITLE
[BUG] Integrated / External terminal debug issue

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#260]
My setting in `settings.json` is:

`"csharp.debug.console": "externalTerminal"`

But when I run debug (`ctrl+F5` or `F5`) built in terminal still reveals (tested on `Console`, `WEB API` and `Blazor` apps):

![244603656-cb285346-3359-4a25-98b0-90707da85c32](https://github.com/microsoft/vscode-dotnettools/assets/38082501/2861d207-3661-448c-bcc8-4005eeb9eb35)

Please fix this. Prevent the built-in terminal from being revealed.

**Comment by WardenGnaw** [comment]
Moving to `area-project` as we call the built in build task to build the project before debugging.

@adrianvmsft Is there a way to make the internal build take not make the `terminal` take focus during build?

**Comment by tmeschter** [comment]
Moving to "area-project-cps".

**Comment by webreidi** [comment]
This has been fixed in v0.3.21. Please update to the latest version and reopen providing more details if you are still experiencing issues.
