### ISSUE TITLE
[BUG] Code text color issue

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#264]
There are no colors in the code text. Changing theme (dark, light) does not helps:

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/37afdb15-3a9f-49c4-983d-71ef6163e806)

After rebooting the VSCode, sometimes the colors come back but I can't catch the logic.

**Comment by timheuer** [comment]
Dupe of #211

**Comment by BachiMjavanadze** [comment]
closed because of dupe
