### ISSUE TITLE
[BUG] Run all tests in file in multi-targeted project builds entire solution

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-dotnettools#265]
### Steps To Reproduce

1. Clone dotnet/razor (or any repo with multi-targeted test projects and other, unrelated projects).
2. Do a build of a test project to get test explorer info.
3. Open a test file, and invoke `Run All Tests` on either the class, or a specific test in the class.

### Expected Behavior

Only the test project is built.

### Actual

The entire solution is built.

### Environment Information

CPUs | Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 4900)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 8, 4, 2
Memory (System) | 62.57GB (28.43GB free)
Process Argv | --no-sandbox . --crash-reporter-id 43eefd67-e97f-4f18-b0d4-472657c3e98a
Screen Reader | no
VM | 0%

**Comment by AbhitejJohn** [comment]
This can be addressed by possibly checking if the test file maps to the same project (in case of multi-targeting)

**Comment by peterwald** [comment]
Fix has been merged on the Test Explorer side.
