### ISSUE TITLE
No application is associated with the specified file for this operation error building any .net 6 or 7 solution

### ISSUE THREAD

**Issue by acrigney** [microsoft/vscode-dotnettools#267]
Guys I am trying to get a .net 6 c# solution I built in VS2022 to run in VSCode so I can hook it to the Colab environment.
I have installled all the required extensions and the .net 6 and 7 sdks but I am not able to build my solution and also I can not even get a simple console to build either. This is the error I am getting. I have the latest VSCode installed.
Program 'dotnet' failed to run: No application is associated with the specified file for this operationAt 
line:1 char:1
+ dotnet new console --framework net6.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ dotnet new console --framework net6.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by timheuer** [comment]
@acrigney are you saying that even in just a terminal window (outside of VSCode) you are seeing this issue?  Can you show a screenshot of where you are seeing this and the steps you are using to build?

**Comment by acrigney** [comment]
Thanks mate so sorry I should have said outside of VSCode everything works fine and has for ages.

**Comment by Michael-Eng** [comment]
We use your path to find dotnet.exe. We use that for creating projects, building, etc. Can you confirm dotnet.exe exists on your path? What does dotnet.exe --list-sdks show from the terminal inside VS Code?

**Comment by acrigney** [comment]
Thanks heaps mate!
PS F:\Projects\VSCodeTest> dotnet.exe --list-sdks
1.0.4 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.509 [C:\Program Files\dotnet\sdk]
2.1.516 [C:\Program Files\dotnet\sdk]
2.1.517 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.107 [C:\Program Files\dotnet\sdk]
3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
3.1.102 [C:\Program Files\dotnet\sdk]
5.0.100-preview.5.20279.10 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.412 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.300-preview.23179.2 [C:\Program Files\dotnet\sdk]
7.0.306 [C:\Program Files\dotnet\sdk]

Ah but it does't show 6.0.412 and this project is .net 6, I will try with 7.

**Comment by acrigney** [comment]
No luck with .net 7 either same error
PS F:\Projects\LinkCrawler\LinkCrawler> dotnet build
Program 'dotnet' failed to run: No application is associated with the specified file for this operationAt 
line:1 char:1
+ dotnet build
+ ~~~~~~~~~~~~.
At line:1 char:1
+ dotnet build
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by GaryHarrisa** [comment]
whiteguy2c@gmail.com

**Comment by GaryHarrisa** [comment]
[]([setup-node-3.8.1.tar.gz](https://github.com/microsoft/vscode-dotnettools/files/13483279/setup-node-3.8.1.tar.gz))
[gh-es-3.11.0.zip](https://github.com/microsoft/vscode-dotnettools/files/13483280/gh-es-3.11.0.zip)

**Comment by lifengl** [comment]
it is likely your local installation is corrupted. Uninstall all them, and reinstall to see whether it fixes the problem.  Lots of old SDKs there are outdated, and no longer supported.

**Comment by acrigney** [comment]
OK mate this was so long ago and I had to give up on vs code. I am very
busy now sp I don't know when I will get to this.

**Comment by Michael-Eng** [comment]
Closing this issue
