### ISSUE TITLE
Getting started instructions should include restart device 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#268]
### Describe the Issue

I am getting started on a new device and _thought_ I was running into an issue. 
When getting to the 'Set up your environment' section, I kept getting an error of _dotnet not recognized_ despite the command working in a normal terminal 
![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/6ee2494a-9138-4c78-840e-7e676bb75a38)

### Steps To Reproduce

1. Install VS Code on a brand new device
2. Install .NET SDK per the 'Getting Started' instructions
3. Click 'Create a new terminal' in the 'Set up your environment' tab
4. Run 'dotnet --version' 
5. You get an error - _dotnet not recognized_
6. Restarting VS Code / reloading window does not solve this problem, it required a device restart (despite dotnet --version working in a normal terminal) 

### Expected Behavior

For the instructions to tell the user to restart their device otherwise they will continue to see "errors" in the VS Code terminal and blocking them from moving forward

**Comment by timheuer** [comment]
I think @baronfel and @nagilson this has to do with local install and DOTNET_ROOT?

**Comment by baronfel** [comment]
The acquisition experience that @leslierichardson95 has been working on does add this call-out for this very reason! The SDK Acquisition extension should set any required environment variables already, but despite that we have heard feedback that it doesn't 'take' for whatever reason, so the documented reload is the way to go.

It is very odd that the terminal restart/vscode reload/etc didn't work for @claudiaregio - I'd expect any of those to just work.

**Comment by claudiaregio** [comment]
@timheuer @baronfel Are there any updates on this? I can submit a PR if I get permissions to if that helps? I remember this being pretty frustrating since it was working fine in a normal terminal.

**Comment by timheuer** [comment]
/cc @webreidi 

I think we're just asking for the getting started steps to say something like After installing restart VS code (not reload as that does not appear to be enough)?

**Comment by webreidi** [comment]
I've made a PR on the walkthrough to add this wording. Waiting approval. I missed this week's snap, so will hopefully make it into next week's prerelease.

**Comment by claudiaregio** [comment]
Thanks Wendy! I'm not sure how many other people use the 'Welcome' walkthrough in VS Code, are there any ways to trouble shoot the overall underlying problem? (Whether it be a .NET issue or vs code issue?)

**Comment by webreidi** [comment]
Yes, we are working on improvements to the SDK acquisition process, hopefully that will address the underlying problem and work more smoothly in the future.

**Comment by timheuer** [comment]
> I've made a PR on the walkthrough to add this wording. Waiting approval. I missed this week's snap, so will hopefully make it into next week's prerelease.

In my experience the device didn't need to be restarted, but VSCode did (a reload window was not enough)
