### ISSUE TITLE
[BUG] NET MAUI SDK: not found

### ISSUE THREAD

**Issue by maurobernal** [microsoft/vscode-dotnettools#269]
### Describe the Issue

When open the solution i have this error:
".NET MAUI SDK: not found"

### Steps To Reproduce

Open with VSCODE (in WSL or Native WIN) and receive the error ".NET MAUI SDK: not found".

I reinstall workloads ("dotnet workload install maui")

### Expected Behavior

Open Maui's Project with VSCODE

### Environment Information

Enviroment:
**wsl --version**
Versión de WSL: 1.2.5.0
Versión de kernel: 5.15.90.1
Versión de WSLg: 1.0.51
Versión de MSRDC: 1.2.3770
Versión de Direct3D: 1.608.2-61064218
Versión DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versión de Windows: 10.0.22621.1992

**vscode**
version 1.80.1

** SO **
Win 11 Version 22H2 (22621)

**dotnet --info**
SDK DE .NET:
 Version:   8.0.100-preview.4.23260.5
 Commit:    2268e7b15c

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.4.23260.5\

.NET workloads installed:
 [maui]
   Origen de la instalación: SDK 8.0.100-preview.4
   Versión del manifiesto:    8.0.0-preview.4.8333/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.maui\WorkloadManifest.json
   Tipo de instalación:              Msi
 [maui-windows]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    8.0.0-preview.4.8333/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.maui\WorkloadManifest.json
   Tipo de instalación:              Msi
 [maui-android]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    8.0.0-preview.4.8333/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.maui\WorkloadManifest.json
   Tipo de instalación:              Msi
 [maui-maccatalyst]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    8.0.0-preview.4.8333/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.maui\WorkloadManifest.json
   Tipo de instalación:              Msi
 [maccatalyst]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    16.4.8377-net8-p4/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.maccatalyst\WorkloadManifest.json
   Tipo de instalación:              Msi
 [android]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    34.0.0-preview.4.273/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.android\WorkloadManifest.json
   Tipo de instalación:              Msi
 [maui-ios]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    8.0.0-preview.4.8333/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.maui\WorkloadManifest.json
   Tipo de instalación:              Msi
 [ios]
   Origen de la instalación: VS 17.7.33906.173, VS 17.6.33829.357
   Versión del manifiesto:    16.4.8377-net8-p4/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.sdk.ios\WorkloadManifest.json
   Tipo de instalación:              Msi
 [wasm-tools]
   Origen de la instalación: VS 17.6.33829.357
   Versión del manifiesto:    8.0.0-preview.4.23259.5/8.0.100-preview.4
   Ruta de acceso del manifiesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100-preview.4\microsoft.net.workload.mono.toolchain.current\WorkloadManifest.json
   Tipo de instalación:              Msi

Host:
  Version:      8.0.0-preview.4.23259.5
  Architecture: x64
  Commit:       84a3d0e37e

.NET SDKs installed:
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.315 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]
  6.0.412 [C:\Program Files\dotnet\sdk]
  7.0.109 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.4.23260.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23260.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

> VS bug [#1862128](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1862128)

**Comment by Voxel07** [comment]
I had the same issue. I got my existing Windows App, as well as a new Maui template to work, by selecting the Windows Device local, and then debugging the app as usual.

When I open the project, I get the same error every time, but if I select the target and then start the debugging, it starts the app just fine. Some UI elements are not looking the same when I open the app in Visual Studio, but for the most part its fine.

**Comment by maurobernal** [comment]
@Voxel07 and how select the target in vs code?

**Comment by Voxel07** [comment]
@maurobernal simply via the command palette. Default Key binding is Ctrl+Shift+P. Then simply type maui to get all possible commands, including the build target.

**Comment by maurobernal** [comment]
@Voxel07 
I have this option and 
![image](https://github.com/microsoft/vscode-dotnettools/assets/1904416/2755695c-622e-4d12-8b8b-95f11f204a54)

And I was already entering one by one. Then when running (f5) I get the same error
![image](https://github.com/microsoft/vscode-dotnettools/assets/1904416/93811895-8c5d-4be2-9115-5fce5bfb216e)
![image](https://github.com/microsoft/vscode-dotnettools/assets/1904416/1c843033-fc85-4c63-bc56-64c0a3ad8ada)

**Comment by Voxel07** [comment]
After you have satisfied all prerequisites, it should work by selecting Windows -> Local ->
![image](https://github.com/microsoft/vscode-dotnettools/assets/63250128/4a71dcb7-fe95-491d-8c1d-0440ff7cad40)
 F5 -> Maui
![image](https://github.com/microsoft/vscode-dotnettools/assets/63250128/ae54bf02-609c-4d0b-8f7d-f17fc0cac22d)
Then it should compile and start the app. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/63250128/4ec7f15c-7b7f-4bbf-8710-1caa29eaa1c3)

I just tested it on my personal machine with a new maui project created with dotnet new maui

**Comment by mcumming** [comment]
@maurobernal Can you provide the contents of the .NET MAUI output window?

**Comment by mcumming** [comment]
@maurobernal Can you provide the contents of the .NET MAUI output window?

**Comment by emaf** [comment]
@maurobernal Are you still facing this problem? 

If so, could you switch to the pre-release version of the .NET MAUI extension (v0.2.12), open your solution and then provide the content of the .NET MAUI output window?

**Comment by maurobernal** [comment]
@emaf :

.NET MAUI SDK verification failed with an unexpected error: Could not find an active target framework for 'metroin.app-trabajador'. Please make sure you've selected a valid debug target and its platform is present in the TargetFrameworks or TargetFramework properties.
If you cannot solve this problem, please report an issue from the Help menu.
 
user preferred path: c:\Program Files\Microsoft\jdk-11.0.12.7-hotspot
JAVA_HOME: C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot
Java SDK: shared with Visual Studio [installed]
Android service Java SDK found: C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot
user preferred path: c:\Program Files (x86)\Android\android-sdk
Android SDK: shared with Visual Studio [installed]
Android service Android SDK found: c:\Program Files (x86)\Android\android-sdk
Android SDK recommended required components:
	platform-tools  installed
	cmdline-tools  installed
Debugging canceled: MAUI SDK not found.

**Comment by emaf** [comment]
@maurobernal Thanks! I have a few more questions for you:
1. Could you check in the NuGet output window if the restore process succeeded? It is executed right after the solution is opened, but if it fails we might not get all the information we need from the project.
2. If you open a cs file, do you see the `{ }` icon on the right side of the status bar? And if you do and click on it, do you get the `Startup project` and `Debug target` options? 
![image](https://github.com/microsoft/vscode-dotnettools/assets/3286258/52ea2988-bbe3-456c-b06c-0dc0d908f4f2)

**Comment by emaf** [comment]
Did that change make any difference in the .NET MAUI output or does it still show the same error about the active target framework?

**Comment by maurobernal** [comment]
Not. I have the  same error:

Maui output
Debugging canceled: MAUI SDK not found.

**Comment by emaf** [comment]
This is now fixed in the prerelease channel (v0.3.1)

**Comment by borrmann** [comment]
@emaf I still have this issue with a solution that builds fine on VS Mac and VS Windows. I tried to use latest stable and version  v0.5.48

**Comment by Meerownymous** [comment]
I wanted to try out MAUI on MacOS and have the same issue with a MAUI project that I have created with the MAUI templates.

**Comment by Meerownymous** [comment]
I had tried the 0.5.50 version and then switched to the prerelease 0.6.19. Both give me the error right away when I open the folder. You are right that I see two .sln files in the failing solution folder.

I have now installed the MAUI extension in VS 2022, and created a solution from there. It is only one solution file in it, and this solution can be opened without problems in VS Code.

**Comment by emaf** [comment]
@borrmann @Meerownymous as the extenison can fail to find the MAUI SDK because of different reasons, having a single issue tracking all of them makes it difficult to track each scenario, so please do open a new issue so we can properly track the problems you are facing. Also, including the content of the .NET MAUI output window in the issue helps us investigate the problem. Thanks!

**Comment by WisJamison** [comment]
I ran into the same issue on my mac and the root cause is only .Net SDK 8.0.100 has been installed without any .net 8 maui workloads. So the issue fixed by installing .Net8 maui workload.

**Comment by okerider** [comment]
There is a guide here for setup, both on windows and Mac and for VS and VS Code

https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code
