### ISSUE TITLE
[SUGGESTION] Some improvements for debugging MAUI

### ISSUE THREAD

**Issue by JaneySprings** [microsoft/vscode-dotnettools#273]
### Describe the feature you'd like

Hello! Thanks for the new MAUI extension for VSCode! I have seen some videos from Gerald Versluis on YouTube and want to suggest some improvements. 

I think, this extension uses the same codebase for debugging Mono projects as your [Mono Debug extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug) for VSCode. I haven't compared them via ILSpy but they are very similar 😊. I also use this approach in my [.NET Meteor](https://marketplace.visualstudio.com/items?itemName=nromanov.dotnet-meteor) extension. 

I noticed that when breakpoint is triggered, it takes a very long time to get the `Locals` scope. This is because the plugin for MAUI uses the `Flatten hierarchy` option to get the object model. This forces the debugger to get information about all the properties of all the base classes.

<img width="752" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/48021947/db18181a-3b65-4e38-9cda-647df48f8cd2">

https://github.com/mono/debugger-libs/blob/01705a004b10f68c296a0e615bbf8e2bc0a8a14a/Mono.Debugging/Mono.Debugging.Client/EvaluationOptions.cs#L47

I can advise against using this property. Then you will get a view like in VS for Mac (each child node will be processed separately).
<img width="353" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/48021947/489898d7-719f-47ed-99e3-836e236b337b">

We at **DevExpress** faced a problem when, due to the `flatten hierarchy`, the debugger could fall and terminate the process. This happened when VSCode was trying to get the object model of `Android.Context`.

Anyway, thanks for your work!

> VS bug [#1862691](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1862691)

**Comment by Redth** [comment]
@JaneySprings nice catch!  Thanks for the suggestion, we'll test it out and make the change here :)

**Comment by mcumming** [comment]
This has been fixed and is now in the Prerelease channel
