### ISSUE TITLE
VScode Forgets about MAUI

### ISSUE THREAD

**Issue by ModxVoldHunter** [microsoft/vscode-dotnettools#274]
Type: <b>Bug</b>

When Running an app VSCode with .NET MAUI. it runs once then forgets launch when running an Application like Console.

Open VSCode
Start a new Project (Console Application) [Requires .NET MAUI]
then type something simple like a hello in code.

Run the app

VSCode Run config will go back to default VScode with No run Config (don't worry though it shows that the code is working but vscode doesn't like .net maui much)

Extension version: 0.1.34
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.21GB free)|
|Process Argv|--crash-reporter-id 0cb91915-e012-4764-aff8-cc9d1d140f1a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013:30789517

```

</details>

**Comment by mauroa** [comment]
Hi @ModxVoldHunter.
We are trying to re-activate old issues related to the VS Code MAUI extension that were left unattended or into "Need More Info" state and didn't get a response in a while.
I would like to know if you continued working with MAUI projects in VS Code and if you still have any issue related to this ticket.
We will proceed to close this ticket in case we don't get a new response in a few days.
Thanks in advanced.

**Comment by ModxVoldHunter** [comment]
Im gonna retest it and see if its still a bug and let you know.

**Comment by ModxVoldHunter** [comment]
So when .NET MEUI is installed as an extension. when trying to click the "Create New Project" under .NET, VSCode will sometimes forget that .NET exist and the button will not show to create a project at all sometimes resulting in someone installing the .NET SDK 6/7/8/9 (Preview) and creating a new Project through the command line. also i've noticed another bug with the .NET extension after using VS Studio 2022 Community where vscode will simpily forget that its a .NET project inside of a vscode when Importing it.

**Comment by mauroa** [comment]
@ModxVoldHunter I still don't fully get the big picture of your issues, especially because in the description you mention things like creating a console app requires .NET MAUI, where in fact you just need C# and C# DevKit to use console apps, not .NET MAUI)

Could you share a recording of you experience so we understand better and determine if the issue is related to .NET MAUI or with other extensions like C# DevKit?

We need to understand what's your real issue and your repro steps, so we can define an action item. With the provided information, it's not very clear about what's going wrong with your VS Code usage, and if you are working with MAUI projects or with which type of projects.

Thanks for your help.

**Comment by mauroa** [comment]
We are unable to continue the investigation without the required information. 
Feel free to request a reopening if you still experience any issue after updating to latest C#, C# DevKit and .NET MAUI versions and also please provide the information requested above.
Thanks for your help and feedback.
