### ISSUE TITLE
[BUG] `free(): invalid pointer`

### ISSUE THREAD

**Issue by enihcam** [microsoft/vscode-dotnettools#275]
### Describe the Issue

```
2023-07-20 09:54:16.238 [info] free(): invalid pointer

2023-07-20 09:54:36.431 [info] Project system initialization finished. 0 project(s) are loaded, and 16 failed to load.
```

### Steps To Reproduce

open solution from `https://github.com/Azure/Bridge-To-Kubernetes.git`

### Expected Behavior

all projects are loaded correctly.

### Environment Information

Linux
1.80.1
v0.2.100

**Comment by timheuer** [comment]
Hi @enihcam can you try on v0.2.238 (C#) and v0.3.5 (C# Dev Kit) -- both updated yesterday in pre-release.  I just opened the all.sln in this repo and no errors.

**Comment by enihcam** [comment]
> Hi @enihcam can you try on v0.2.238 (C#) and v0.3.5 (C# Dev Kit) -- both updated yesterday in pre-release. I just opened the all.sln in this repo and no errors.

There is no errors but the loading icon keeps spining infinitely.
![image](https://github.com/microsoft/vscode-dotnettools/assets/7010097/d95740d9-4532-4565-93c4-20da545ca1a2)

**Comment by enihcam** [comment]
Root cause located: Instead of glibc standard malloc, I'm using Microsoft [mimalloc](https://github.com/microsoft/mimalloc) as my memory allocator.

```bash
~ $ cat /etc/ld.so.preload 
/usr/lib/libmimalloc.so
```

after reverting back to glibc, the projects can be successfully loaded.

**Comment by Michael-Eng** [comment]
Thanks for the explanation. Closing this item on our side based on your investigation.
