### ISSUE TITLE
A button is not displayed correctly

### ISSUE THREAD

**Issue by dsp1965** [microsoft/vscode-dotnettools#279]
Type: <b>Bug</b>

When opening visual studio when the explorer says "There is no folder open" where a button should appear that says "Create .NET project" two lines of text appear [Create .NET project] and (command:csdevkit.addNewProject)

Extension version: 0.2.100
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6500B APU with Radeon(tm) HD Graphics    (4 x 3491)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|14.94GB (10.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dsp1965** [comment]
![Captura de pantalla 2023-07-21 151237](https://github.com/microsoft/vscode-dotnettools/assets/140199604/a3c00d34-cbcb-4580-b437-881ee57bb950)

**Comment by Michael-Eng** [comment]
@richardstanton is this missing localizaion?

**Comment by richardstanton** [comment]
Thanks for reporting this bug, we found the cause and are working on a fix. As a workaround you can run the command from the command pallet, ".NET: New Project"

**Comment by dsp1965** [comment]
Thanks to you, I really appreciate the speed with which you respond. Greetings from Buenos Aires, Argentina

**Comment by Michael-Eng** [comment]
Confirmed fix in v1.5.16 (pre-release)
