### ISSUE TITLE
Test Explorer Not Working for projects with alternate outputs specified

### ISSUE THREAD

**Issue by terryaney** [microsoft/vscode-dotnettools#28]
Type: <b>Bug</b>

I've opened a workspace that has a minimal api project, test project, and one 'library' project.  The test explorer doesn't find any tests.  

I've built the web api and the test project and still the refresh returns no tests.

I've restarted VS Code.

This test project used to function correctly when I used the '.net core test project explorer' extension (I think that was name, I've uninstalled it after installing Dev Kit), so I'm pretty sure everything should be in place.

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (44.65GB free)|
|Process Argv|--crash-reporter-id 3a73b254-9ee7-4cb6-b1eb-57f9149a1430|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705
pythonnosmt12:30757131

```

</details>

**Comment by timheuer** [comment]
@terryaney thanks for the bug! When you removed the .NET Core test project explorer, did you also have the 'test adapter converter' installed? Which test framework are you using? And by chance is the solution any public one?

**Comment by terryaney** [comment]
I don't recall seeing 'test adapter converter' installed (I just did a purge after installing Dev Kit.  I could install it again and see if it work.

I use XUnit.

Unfortunately, not a public repository.

I just re-installed the old add-in and this is what I see.  Any logs or anything I can send you given my repo is company hosted on their own TFS?

![image](https://github.com/microsoft/vscode-dotnettools/assets/6237247/445b9fa8-c737-4987-b33a-f0e02031374d)

**Comment by timheuer** [comment]
Odd @terryaney here is my result:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/f6423176-84a7-400a-9e3f-4eedc7da1a0c)

Repo: https://github.com/timheuer/TestSolution

Would be curious if this solution works for you to maybe eliminate anything.  In the Output though there is a "C# Test Explorer" category.

**Comment by timheuer** [comment]
> I have the same issue, I was able to find out that if the project output path is not default (like in my case all projects copying artifacts to $(SolutionDir)/Build/Tests) - then this issue happens. As soon as I removed OutputPath from my csproj - tests got discovered. Is path used to discover tests somehow configurable?

Good callout -- @terryaney is yours similar?

@RomanBadiornyi not configurable yet -- let's see if @terryaney is same issue and we can retitile this one for discovery and maybe log a second issue for configuring the location.

**Comment by terryaney** [comment]
@timheuer, I'm not understanding this comment.

> In the Output though there is a "C# Test Explorer" category.

However, your test solution worked correctly with buth Dev Kit and .Net Test Explorer.

![image](https://github.com/microsoft/vscode-dotnettools/assets/6237247/25e622bb-5f62-4850-a98d-7756e4e61597)

For my web api, here are my workspace settings.  Is the issue that I am working from a workspace and not a .sln or folder?

![image](https://github.com/microsoft/vscode-dotnettools/assets/6237247/b52d01d0-5596-4366-bd46-8d3268cd3355)

And here is my file structure for the web api project:

![image](https://github.com/microsoft/vscode-dotnettools/assets/6237247/e84bff66-2b50-4704-925c-22ebc4ce88e3)

**Comment by peterwald** [comment]
@terryaney In the Output pane there is a drop down to select the test explorer logs. It is labelled "C# Dev Kit - Test Explorer". Those logs may provide some insights into what is happening.

![image](https://github.com/microsoft/vscode-dotnettools/assets/5578/64e1ad03-6d7d-4ab2-b818-68a69aba16c5)

On a different, but related note... There is a known issue where if your test binaries are outside of the workspace that you have opened, then the test explorer will not see changes after build/clean, etc... We are working on a fix for this.

**Comment by hcv-pkuerzinger** [comment]
Is the issue with the missing $(SolutionDir) tracked @timheuer? Having a similar issue as @RomanBadiornyi, but in my normal build process, as I'm doing a xcopy from solutiondir as a PostBuildEvent.

**Comment by timheuer** [comment]
> Is the issue with the missing $(SolutionDir) tracked @timheuer? Having a similar issue as @RomanBadiornyi, but in my normal build process, as I'm doing a xcopy from solutiondir as a PostBuildEvent.

I think this really is the tracking issue for alternate outputs @hcv-pkuerzinger

**Comment by peterwald** [comment]
@RomanBadiornyi @hcv-pkuerzinger 

Are you still seeing this problem with the latest bits? The expected behavior is that the tests will be detected in the location where the project output is built. They will be run from that same location. This would not find tests if the output binaries are moved, but if they are copied it should still work.

**Comment by peterwald** [comment]
> @peterwald, I have tried with version 0.2.99 and unfortunately no luck, see only test project with default OutputPath.

Can you give an example of how your OutputPath is being modified in the project files?

**Comment by RomanBadiornyi** [comment]
@peterwald 
sure:
`<OutputPath>$(SolutionDir)Build\Tests\</OutputPath>`

**Comment by peterwald** [comment]
Confirming that this is a problem with resolution of `$(SolutionDir)` in design-time builds.

**Comment by peterwald** [comment]
The fix for this issue has been merged.
