### ISSUE TITLE
[BUG] C# devkit locks files, not able to move/rename/delete, etc

### ISSUE THREAD

**Issue by EelcoLos** [microsoft/vscode-dotnettools#281]
### Describe the Issue

I'd like to move some folders in a solution, which is opened by C# devkit. Upon moving and/or renaming the files (and i'm certain this will also happen with deleting), which are opened with the C# devkit extension, I get an error message:

> Error: EPERM: operation not permitted, rename `<source dir>` -> `<target dir>`

### Steps To Reproduce

1. Open a .net solution folder in vscode
1. use the C# devkit tool to open the solution as well
1. try and move/rename the folder
1. the error shows:
> Error: EPERM: operation not permitted, rename `<your original solution directory>` -> `<target directory>`

### Expected Behavior

The extension should notice the move and update the solution accordingly.
If that is a feature request, the expected behaviour is: allow the move to happen; the extension shouldn't lock the files.

### Environment Information

- OS: Windows
- VSCode version: 1.80.1
- C# Devkit version: v0.2.100

**Comment by ekaradzha-qb** [comment]
Does it have that feature at all? I cannot move/copy/drag-and-drop files with devkit at all?

**Comment by EelcoLos** [comment]
vscode has the ability to move files, the extension blocks it

**Comment by EelcoLos** [comment]
Seen today as well, permission persists

**Comment by jtsom** [comment]
Just noticed this today also. Created a new folder and attempted to rearrange the project by moving some files in the Solution Explorer. Cannot move the files.

I can move the files using just the original Explorer view.

**Comment by jtsom** [comment]
Still happens in latest Insiders Build.

**Comment by vanasis** [comment]
cant move files nor rename it
![image](https://github.com/microsoft/vscode-dotnettools/assets/2195153/8674e980-8c4f-43d0-a0c4-6dda5df2b1f4)

**Comment by vanasis** [comment]
same issue https://github.com/microsoft/vscode-dotnettools/issues/445

**Comment by GrigoriyPlotnikov** [comment]
Same issue, file system locks happen randomly at dotnet build, npm install and ng serve. It started to happen since update from very old stable dev kit, reproduced at every version at least since 1.50.51 (tried to downgrade). Good thing locked folders disappear after the extension is disabled.
