### ISSUE TITLE
[BUG] .NET MAUI curly braces not showing in status bar

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/vscode-dotnettools#283]
### Describe the Issue

The curly braces {} next to C# or XAML in the status bar is not showing when a .NET MAUI project is open.

### Steps To Reproduce

1. Install the .NET MAUI extension (The [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) and [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit) extensions will automatically be installed as dependencies)
2. (a) Open a folder/workspace that contains a .NET MAUI project or solution (.csproj or .sln),
OR
(b) Use the Solution Explorer's "Create .NET Project" button or Command Palette's ".NET: New Project.." and choose a .NET MAUI project type
3. Select your debug target by hovering over the curly braces {} next to C# or XAML in the status bar, then hit F5!
4. The curly braces are not showing.
<img width="90" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/4465616/31ab040c-64d8-42f8-89bd-52f7b458dc47">

### Expected Behavior

The curly braces are showing and you can switch your target.

### Environment Information

- OS: Mac
- VS Code: 1.80.1 
- .NET MAUI Extension: v0.1.34
- C# Dev Kit Extension: v0.2.100

**Comment by scottkuhl** [comment]
> Do you have a C# or XAML file open? it won't show up if you don't have any files open!

Yes.  I've tried with both.

**Comment by scottkuhl** [comment]
Using the comman pallete works, it's really just a matter of that icon missing to change it from the status bar.

**Comment by scottkuhl** [comment]
Using the comman pallete works, its really just a matter of that icon missing to change it from the status bar.

<img width="733" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/4465616/89eaf8d6-0e71-4dba-9052-b2a04121832a">

**Comment by mcumming** [comment]
Hi @scottkuhl 
This is what you should be seeing if you have a C# or csproj file open in the editor
![image](https://github.com/microsoft/vscode-dotnettools/assets/20541227/9f5770e6-e0f4-4073-96e9-176b71630ae4)
The symbol we are referring to is the C# without any decoration surrounding it, the curly braces should show up to the left of that.

**Comment by scottkuhl** [comment]
@mcumming 

I do not see the { } C# indicator even when I have a MAUI solution loaded and a C# file open.  This is what I see:

<img width="438" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/4465616/6321f434-44b5-405c-8101-24d9bdfba228">
 
If you look at my previous screenshot you can see what I have hidden, and I don't see it there either.  I know I have seen it, and I have used in the past, so I don't know if a VS Code update or extension update has broken it, but I don't see it anymore.

**Comment by scottkuhl** [comment]
I think I found the issue, Editor Language Status was not shown.

**Comment by scottkuhl** [comment]
I think I found the issue, Editor Language Status was not shown.
