### ISSUE TITLE
Release version requires pre-release version of C# extension; nothing seems to work

### ISSUE THREAD

**Issue by kjkrum** [microsoft/vscode-dotnettools#285]
### Describe the Issue

I just installed VSCode from .deb on Pop! OS (an Ubuntu derivative). I installed the C# and C# Dev Kit plugins and created a new solution with the default "Hello, World!" template.

The release version of C# Dev Kit says it requires the pre-release version of C#. With the release version of C#, syntax errors are highlighted and appear in in the error list. With the pre-release version of C#, there is no syntax highlighting of .cs files and errors do not appear in the error list.

With either version of C#, pressing F5 asks you to select a debugger, then nothing. There is no output and no error anywhere that I can see. Breakpoints are not hit. I added `Console.ReadLine();` to the template in case a console window was appearing and closing immediately. Still nothing.

Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.6-76060206-generic

**Comment by tmeschter** [comment]
@kjkrum Would you be able to provide the version numbers of the installed C# and C# Dev Kit extensions?

@timheuer Does anything about this installation stand out to you as being wrong or problematic?

**Comment by webreidi** [comment]
The C# Dev Kit no longer requires a pre-release version of the C# extension. Please update to the latest versions of both C# and C# Dev Kit and re-open the ticket if you are still experiencing problems and provide details about the issues you are experiencing.
