### ISSUE TITLE
C# DevKit suggests refactorings that break build/don't compile

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode-dotnettools#289]
Type: <b>Bug</b>

C# Dev Kit suggests refactorings that break the build/does not compile after.

I'm going to have to go back to omnisharp for a bit until I see some movement on my issues. Happy to try again though. 

I installed .NET 6 so that I have both .NET 6 and .NET 7 sdk's on my machine in case that was an issue (perhaps it needs the LTS installed to work properly) 

I've also disabled GitHub CoPilot. 

1st Screenshot shows the current code compiling with using statements being suggested that they can be removed as not needed. (also shows I have copilot disabled)

![vscode-good](https://github.com/microsoft/vscode-dotnettools/assets/374863/73d4403b-d365-44c0-b75b-140b42fa0f90)

2nd screenshot shows the suggestion to remove the using statements

![vscode-suggestion](https://github.com/microsoft/vscode-dotnettools/assets/374863/3ed9bfa8-3a97-4847-9fab-3afed2a76464)

3rd Screenshot shows the refactored code not compiling after removing the suggested using statements.

![vscode-bad](https://github.com/microsoft/vscode-dotnettools/assets/374863/49ebcf66-c62d-496c-a097-6cd632eb0cfe)

Extension version: 0.2.100
VS Code version: Code - Insiders 1.81.0-insider (862fa13002d8018c328931ee1edccfd4ca76447d, 2023-07-26T05:37:20.666Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 4833a52a-ed11-4d5d-b549-6ace2400b2b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
a9j8j154:30646983
showlangstatbar:30737417
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214
h0f32768:30792099
asynctok:30795849
dsvsc013:30777762
dsvsc014:30777825
diffeditorv1:30786205

```

</details>

<details>
<summary>System Info</summary>

```bash
Last login: Wed Jul 26 09:16:59 on ttys000
▲ ~ dotnet --list-sdks
6.0.412 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
▲ ~ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
▲ ~ computer_info
solrevdev@macmini-2020.local 
---------------------------- 
OS: macOS 13.4.1 22F82 arm64 
Host: Macmini9,1 
Kernel: 22.5.0 
Uptime: 2 hours, 17 mins 
Packages: 359 (brew) 
Shell: zsh 5.9 
Resolution: 2560x1440, 2560x1440 
DE: Aqua 
WM: Quartz Compositor 
WM Theme: Blue (Light) 
Terminal: Apple_Terminal 
Terminal Font: SFMono-Regular 
CPU: Apple M1 
GPU: Apple M1 
Memory: 3153MiB / 16384MiB 
▲ ~ 
```

</details>

**Comment by timheuer** [comment]
Hi @solrevdev thanks for the report. I'm not able to try to emulate this using some of the data you provided. Any chance you have a project that you can share here that you see this in so we can see what other references are feeding the Roslyn workspace?

**Comment by jasonmalinowski** [comment]
@solrevdev While you were seeing this issue, were you still impacted by https://github.com/microsoft/vscode-dotnettools/issues/226 or had you uninstalled IntelliCode at that point? The failure in that bug would also mean we don't get project information which could also lead to these symptoms too.

If you had already worked around that other bug though, then what might also help would be a memory dump of the Microsoft.CodeAnalysis.LanguageServer process which is a background process of VS Code. You could use https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump to create the dump, but you'd have to upload it somewhere to some cloud storage since it's likely to be quite large. You should also share that dump privately, but my Microsoft email address is available on my GitHub profile you can email to.

**Comment by solrevdev** [comment]
thanks @jasonmalinowski and @timheuer for replying.

@jasonmalinowski In terms of #226 I had already disabled GitHub Copilot on my vscode-insiders/c# dev kit environment. I'm back in the office tomorrow so happy to do a memory dump of the Microsoft.CodeAnalysis.LanguageServer. I'll find somewhere to store it and email you. 

@timheuer Its a private project and I've carried on developing using vscode and omnisharp but I did take a branch at the point of the issue so I'll see what I can do to get a public repo from that branch that will demo the issue. I'll link to the repo here. 

Again thanks both for taking a look much appreciated

**Comment by solrevdev** [comment]
It looks like the latest version of the C# extension has fixed this issue!. 

I'm going to switch back to using my VSCode Insiders / C# DevKit setup again and see how I get on. 

Same branch that caused the issue but with extensions updated and now all good:

![Screenshot 2023-07-28 at 11 07 37](https://github.com/microsoft/vscode-dotnettools/assets/374863/38c1dd0e-04c7-481b-9378-580cd07e5c24)

The C# version I have installed:

![Screenshot 2023-07-28 at 11 06 33](https://github.com/microsoft/vscode-dotnettools/assets/374863/6e73e162-c6da-4e1f-a23c-f6d40f33c80d)

I'm going to close the issue, but if it returns would you rather I re-open this one or create a new one and link this one?

Thanks @jasonmalinowski and @timheuer

**Comment by timheuer** [comment]
Excellent to hear on this one @solrevdev -- if it happens to resurface feel free to re-open this particular one (has history) or a new one...providing any updated versions/repro information would just be what would be helpful if that becomes the case.

Thanks for reporting back!
