### ISSUE TITLE
[BUG] Renaming folders via explorer "folders" panel fails

### ISSUE THREAD

**Issue by StringEpsilon** [microsoft/vscode-dotnettools#290]
### Describe the Issue

When I try to rename a folder via the "Folders" explorer panel while C# Dev Kit is installed , the operation hangs for a solid minute or two while the status bar at the bottom says "Renaming `<currentName>` to `<newName>`".

Eventually I get an error popup saying
`Error: EPERM: operation not permitted, rename '<folderPath> -> '<newPath>'`

Renaming via the Solution Explorer works. 

Additional note: Renaming files works just fine.

### Steps To Reproduce

1. Open any C# solution in VS Code.
2. In the regular "Folders" explorer panel go to a folder that contains at least one .cs file.
3. Right click that folder and click "rename" (or hit F2)
4. Type in the new name
5. Hit enter

### Expected Behavior

I expect that I can use either the regular "Folders" panel or the "Solution Explorer" panel to rename folders. C# Dev Kit should not override or hinder baseline VS Code functionality.

### Environment Information

OS: Windows
C# Dev Kit version: v0.2.100 
VS Code Version: 1.80.1 (user setup)

**Comment by timheuer** [comment]
Hi @StringEpsilon can you install `v0.3.18` pre-release and see if this still repros for you -- just tried your steps and I'm able to rename.

**Comment by timheuer** [comment]
Good additional info, I can repro now. /cc @Michael-Eng 

https://github.com/microsoft/vscode-dotnettools/assets/4821/1e6d58ec-4388-4f7b-94d7-cee73620fd0b

**Comment by Michael-Eng** [comment]
@Erarndt can you work with Lifeng on this?

**Comment by Erarndt** [comment]
@StringEpsilon, I'm currently looking into this, and it looks like this might be caused because we have a file/project open that is preventing the folder from being moved or renamed. This is at the OS level, and you can verify that by trying to delete/rename the folder in the windows file explorer (you'll get an access issue). I'll post an update once I have some more news to share.

**Comment by webreidi** [comment]
I can no longer repro this issue. Please reopen the issue if you are still experiencing the issue with the latest version of C# Dev Kit.
