### ISSUE TITLE
[BUG] Output window auto-opens on solution opening

### ISSUE THREAD

**Issue by trolleyman** [microsoft/vscode-dotnettools#291]
### Describe the Issue

I'm not sure that this should be happening - it's a bit frustrating, especially as it happens sometimes when typing in the terminal. I think it might be the same issue as here (different extension, but C# dev kit may be calling the VS Code API in the same way https://github.com/microsoft/vscode/issues/82226)

Also see https://github.com/felixfbecker/vscode-php-intellisense/issues/65

### Steps To Reproduce

1. Open a solution
2. Output window is opened and auto-focused (NuGet)

### Expected Behavior
The Output window shouldn't be auto-focused, it is a bit annoying when it is, I have to keep on closing it.

### Environment Information
- Windows
- VS Code 1.80.1
- C# Dev Kit v0.2.100

**Comment by webreidi** [comment]
This was fixed in v0.3.21. Please update to the latest version. If you are still experiencing problems, please reopen and provide updated details.

**Comment by trolleyman** [comment]
@webreidi Thanks very much! Not experiencing this any more, but I'll let you know if I do :)
