### ISSUE TITLE
[BUG] Breakpoints not hit on MAUI Blazor on Mac

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/vscode-dotnettools#292]
### Describe the Issue

If you put a breakpoint on the default template's Counter.razor IncrementCount method, it will not be hit while debugging.

### Steps To Reproduce

1. Create a new MAUI Blazor Hybrid application on Mac.
2. Put a breakpoint on the currentCount++; line in Counter.razor
3. Run the app in debug mode with MacOS or IOS as a target.
4. Navigate to the Counter page.
5. Click the button.
6. The breakpoint is not hit.

### Expected Behavior

The breakpoint should be it.

### Environment Information

- OS: MacOS Ventura 13.4.1 (c) 
- VS Code: 1.80.1 (Universal)
- C# Dev Kit: v0.2.100
- MAUI Dev Kit: v0.1.34

### Workarounds

- Open the solution in Visual Studio for Mac and the breakpoint will be hit.
- Debug the solution using the .NET Meteor extension for VS Code and the breakpoint will be hit.
- [UPDATE] Move the code into a partial code behind class.

> VS bug [#1862129](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1862129)

**Comment by JaneySprings** [comment]
Hi! In .NET Meteor, there was also such a problem in the first versions. This is very easy to fix. You need to add a `.razor` string to this array:
<img width="624" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/48021947/d00c310c-bf7e-4709-908d-ed42ba4660e4">

https://github.com/microsoft/vscode-mono-debug/blob/4e3ac42a2367dca94bd452e63d7899d228b55c5f/src/csharp/MonoDebugSession.cs#L19-L25

I think **Microsoft** will fix it soon 😉
P.S. In the latest versions of .NET Meteor, I completely removed this check as unnecessary

**Comment by scottkuhl** [comment]
I can confirm that this is a razor file issue.  Switching to partial classes and moving the code into the code behind file will hit the breakpoints.  Thanks @JaneySprings for pointing out the issue is in razor files only.

**Comment by scottkuhl** [comment]
I see that this was closed but I don’t see any code attached for a fix.  Was this fixed here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1862129
