### ISSUE TITLE
[BUG] Documentation comments do not continue comments when adding new lines

### ISSUE THREAD

**Issue by glektarssza** [microsoft/vscode-dotnettools#296]
### Describe the Issue

When formatting documentation comments, if a user adds new lines between certain types of tags, the triple slash directives are not automatically added.

### Steps To Reproduce

1. Create a new C# project.
2. Add the following code to a new `.cs` file:
```csharp
namespace Test;

/// <summary>
/// A test class.
/// </summary>
public class Test {
    /// <summary>
    /// Create a new instance.
    /// </summary>
    /// <param name="result"></param>
    public Test(bool result) {
        // TODO
    }
}
```
3. Place the cursor between the start of closing `</param>` tag and the end of the opening `<param>` tag.
4. Press enter twice to insert two new lines.
5. Observe that the two presses of enter results in the following code:
```csharp
namespace Test;

/// <summary>
/// A test class.
/// </summary>
public class Test {
    /// <summary>
    /// Create a new instance.
    /// </summary>
    /// <param name="result">
    
    </param>
    public Test(bool result) {
        // TODO
    }
}

```

### Expected Behavior

The two presses of enter results in the following code:

```csharp
namespace Test;

/// <summary>
/// A test class.
/// </summary>
public class Test {
    /// <summary>
    /// Create a new instance.
    /// </summary>
    /// <param name="result">
    /// 
    /// </param>
    public Test(bool result) {
        // TODO
    }
}

```

### Environment Information

* Visual Studio Code: 1.81.0-insider (user setup)
* Operating System: Windows_NT x64 10.0.22621
* Extension: v0.3.18

**Comment by timheuer** [comment]
Also note the pattern of using:
```csharp
/* start of some comment
*
*
* expect cr to also keep the '*' going doesn't work
* /
```

**Comment by arkalyanms** [comment]
This should have been fixed in more recent builds of the C# extension (below is on v2.0.376)

![comments](https://github.com/microsoft/vscode-dotnettools/assets/60013978/519588f1-44df-44cb-b65f-025fa6de2440)
