### ISSUE TITLE
[BUG] Solution Explorer is gone

### ISSUE THREAD

**Issue by wV-software** [microsoft/vscode-dotnettools#300]
### Describe the Issue

I tried to uninstall and re-install C# Dev Kit, hoping to resolve any of the bugs. The solution explorer disappeared along with its command.

**Comment by timheuer** [comment]
Hi @wV-software can you provide a bit more information? What versions are now installed? Is a workspace open with a .csproj or .sln in the tree? Any errors in the output logs for Extension Host or the specific extensions?
