### ISSUE TITLE
[BUG] .NET MAUI SDK Workload Installation Failures

### ISSUE THREAD

**Issue by kbruckman** [microsoft/vscode-dotnettools#303]
### Describe the Issue

I'm receiving errors when attempting to install the .NET MAUI SDK to be used with VS Code:

Failed to update the advertising manifest microsoft.net.sdk.android: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.sdk.ios: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.sdk.macos: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.sdk.maui: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.sdk.tvos: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain.net6: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain.net7: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.workload.emscripten.net6: No NuGet sources are defined or enabled.
Failed to update the advertising manifest microsoft.net.workload.emscripten.net7: No NuGet sources are defined or enabled.
The machine has a pending reboot. Installation will continue, but you may need to restart.
Downloading Microsoft.Maui.Core.Ref.android.Msi.x64 (7.0.49)
Workload installation failed. Rolling back installed packs...
Workload installation failed: One or more errors occurred. (No NuGet sources are defined or enabled)

### Steps To Reproduce

1. I installed the .NET MAUI extension for VS Code.
2. I'm walking through the "Get Started with .NET MAUI" page.
3. On the "Set up your .NET MAUI environment" step, I ran "dotnet workload install maui" in the VS Code terminal.

### Expected Behavior

It was expected that the .NET MAUI SDK would be installed for use in VS Code.

### Environment Information

- OS: Windows 10
- VS Code version: 1.80.2
- Extension version: v0.1.34
- I do not have access to Visual Studio

**Comment by emaf** [comment]
@kbruckman which version of dotnet are you using? You can get it by running `dotnet --version`

**Comment by lubertRoft** [comment]
I just experienced the same problem, what helped was configuring NuGet by adding a source using:

`dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org`

found here: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source

**Comment by bradykelly** [comment]
I'm on Windows 11 using Rider, no VS, and using the `-source` parameter doesn't change anything, and using `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` tells me the source is already included.

**Comment by mauroa** [comment]
Hi @bradykelly, could you please let us know the detailed steps you did? Also, the dotnet version you are using and how did you install it? Thanks

**Comment by Quaybe** [comment]
@kbruckman , what fixed this for you?
