### ISSUE TITLE
[SUGGESTION] support Solution Explorer: Auto Reveal

### ISSUE THREAD

**Issue by yingpanwang** [microsoft/vscode-dotnettools#304]
### Describe the feature you'd like

support  Solution Explorer: Auto Reveal like  VSCode Explorer: Auto Reveal

### Environment Information

- Windows 12
- Visual Studio Code 1.80.2
- v0.3.18 preview

**Comment by timheuer** [comment]
Hi @yingpanwang thanks for the suggestion, i'm going to close this as a duplicate of #180 we are tracking this suggestion there.
