### ISSUE TITLE
[SUGGESTION] Explorer file nesting settings do not apply to solution explorer.

### ISSUE THREAD

**Issue by dzhukovsky** [microsoft/vscode-dotnettools#306]
### Describe the feature you'd like

Explorer `explorer.fileNesting` settings do not apply to solution explorer.

Screen from native explorer:
![image](https://github.com/microsoft/vscode-dotnettools/assets/136100876/521522c6-7560-4675-87df-047622f89fe0)

Screen from Solution explorer:
![image](https://github.com/microsoft/vscode-dotnettools/assets/136100876/9b4c8da4-07f0-4685-b25a-6838fafe7bb1)

It looks like we need to fix this.

**Comment by dzhukovsky** [comment]
@timheuer
I use the same version, nesting started working after restarting VS Code

**Comment by timheuer** [comment]
Ok, closing this since it's working, if it resurfaces, please feel free to reopen with new details.

**Comment by ThaDaVos** [comment]
Can this be re-opened please?
It does not work for me - Solution Explorer:
![afbeelding](https://github.com/microsoft/vscode-dotnettools/assets/5251028/8758b435-c1f6-49eb-809d-7849bce3fd20)
File Explorer:
![afbeelding](https://github.com/microsoft/vscode-dotnettools/assets/5251028/c8327cde-fd6b-472f-a0a6-813064b1b771)

File Explorer used the following:
```JSON
...
"*": "${basename}.${extname}.map, ${basename}.*.${extname}, ${basename}.*.${extname}.map"
...
```

**Comment by syko9000** [comment]
@timheuer 
> and this is the only setting I have for .json in my explorer nesting settings: 

If it was working it should have the .dockerignore under the Dockerfile, but it doesn't. I think there is special code for appsettings.*, but not general usage of the file nesting settings. Should be re-opened.

**Comment by khadden-compline** [comment]
100% the .net "Solution Explorer" should read and use `explorer.fileNesting.patterns` from settings.json in the .vscode folder of the project, and from your global settings. 
We don't need to have our nesting dictated by the extension developers.
