### ISSUE TITLE
Can't hit tab on empty line without a completion.

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode-dotnettools#308]
Type: <b>Bug</b>

This is VERY frustrating.  I just want to go to an empty line, hit Tab and start typing code without an autocompletion getting in the way.

Steps:
1. open a C# code file
2. place cursor at the begging of an empty line within a method body.
3. hit Tab -- whatever complete IntelliCode dreamed up is applied.

I then have to undo the change, hit escape, use spaces to tab into where I was wanting to type code.

Extension version: 0.2.100
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (7.04GB free)|
|Process Argv|--crash-reporter-id 24452be9-7e87-49ef-aeb5-c1b3aefe6bde|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofb:30797622
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by burtonrodman** [comment]
![C# Eager Autocomplete](https://github.com/microsoft/vscode-dotnettools/assets/7658657/62f1f590-caed-4be5-aa73-fca0a88c4b78)

**Comment by timheuer** [comment]
Hi @burtonrodman This looks like IntelliCode and/or Copilot offerings as tab is a completion keystroke for those.  Do you have Copilot enabled?

**Comment by burtonrodman** [comment]
no, i do not have Copilot enabled.

**Comment by timheuer** [comment]
@burtonrodman An updated version of IntelliCode extension was released yesterday. I'm not sure if you are still using it, but give it a try?

**Comment by epinter** [comment]
I'm using IntelliCode extension 1.3.1, I also have this problem. This behaviour is very very annoying.

**Comment by burtonrodman** [comment]
closing, seems to be fixed.

**Comment by MathieuGirard** [comment]
I also reproduce this. This is the most annoying bug of vscode...

Hit enter on a line try to reindent to start coding and it keep trying to insert stupid suggestions...
