### ISSUE TITLE
Can i specify the .NET sdk location

### ISSUE THREAD

**Issue by C0HERENCE** [microsoft/vscode-dotnettools#314]
Type: <b>Bug</b>

I have right dotnet sdk installed, but the extension keeps downloading new .NET version and installed to %APPDATA%/Roamin/Code/User/globalStorage..

Extension version: 0.3.18
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.23506
Modes:

**Comment by BertusGreeff** [comment]
+1

I'm trying to use this with CoreXT, a custom msbuild based build environment.  C# DevKit, C# extension etc. should allow overriding the location of the .NET SDK through environment variables.  Possibly the solution is to honor the already documented way to sepcify this.  From [https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_msbuild_sdk_resolver_](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_msbuild_sdk_resolver_)  

DOTNET_MSBUILD_SDK_RESOLVER_*
These are overrides that are used to force the resolved SDK tasks and targets to come from a given base directory and report a given version to MSBuild, which may be null if unknown. One key use case for this is to test SDK tasks and targets without deploying them by using the .NET Core SDK.

DOTNET_MSBUILD_SDK_RESOLVER_SDKS_DIR: Overrides the .NET SDK directory.
DOTNET_MSBUILD_SDK_RESOLVER_SDKS_VER: Overrides the .NET SDK version.
DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR: Overrides the dotnet.exe directory path.

**Comment by timheuer** [comment]
Can you try setting this:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/db111b02-2bb4-44bb-b6c8-c65df2da02e3)

**Comment by BertusGreeff** [comment]
I added the following to my settings.json:

"dotnetAcquisitionExtension.existingDotnetPath": [
        "T:\\CxCache\\.A\\DotNetSDK.jnWDo0nKvCHf52nWxPhAxg"
    ],

dotnet.exe is in that path.  (6.0.408).  I also tried with T:\\CxCache\\.A\\DotNetSDK.jnWDo0nKvCHf52nWxPhAxg\\dotnet.exe

Results are the same.  From the C# extension output:

Dotnet path: c:\Users\bgreeff\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...

**Comment by nagilson** [comment]
You must include the extension id for that setting to be used, such as https://github.com/microsoft/vscode-dotnettools/issues/138#issuecomment-1592764664. Let us know if that does not work.
