### ISSUE TITLE
August 2023 Iteration Plan

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#315]
Below is the list of items being worked on during August 2023 sprint. Not all items listed below will finish and release in August. 

- [x] https://github.com/microsoft/vscode-dotnettools/issues/192
- [ ] https://github.com/microsoft/vscode-dotnettools/issues/259
- [x] https://github.com/microsoft/vscode-dotnettools/issues/265
- [x] https://github.com/microsoft/vscode-dotnettools/issues/28
- [x] https://github.com/microsoft/vscode-dotnettools/issues/217
- [x] https://github.com/microsoft/vscode-dotnettools/issues/155
- [x] https://github.com/microsoft/vscode-dotnettools/issues/396
- [x] https://github.com/microsoft/vscode-dotnettools/issues/394
- [x] https://github.com/microsoft/vscode-dotnettools/issues/318
- [x] https://github.com/microsoft/vscode-dotnettools/issues/252
- [x] https://github.com/microsoft/vscode-dotnettools/issues/240

See also, [C# extension August 2023 Iteration Plan](https://github.com/dotnet/vscode-csharp/milestone/32)

**Comment by pedro-gilmora** [comment]
Would be nice to include [source generators output](https://github.com/microsoft/vscode-dotnettools/issues/362) for next releases

**Comment by timheuer** [comment]
Are we closing these out after the milestone passed? @webreidi
