### ISSUE TITLE
Cant open project

### ISSUE THREAD

**Issue by newUser483** [microsoft/vscode-dotnettools#326]
Type: <b>Bug</b>

Describe the Issue:
Actual results: vscode has failed to open project, it keeps processing workspace in background.
Expected results: vscode opens c# project and loads IntelliSense.
Tried with both 2021 and 2022 editors.

Steps To Reproduce: 
1. install vscode with version 1.79.2
2. follow the guide on https://code.visualstudio.com/docs/other/unity
3. install .net sdk 7.0.306
4. create a new empty 3D project in unity
5. upgrade the visual studio package 
6. create a new script
7. regenerate project files
8. open c# project

Extension version: 0.9.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by sailro** [comment]
Hello,

Could you make sure that:
* Your C# and C# Dev Kit extensions are upgraded to the latest version:
  * C# (v2.0.320)
  * C# Dev Kit (v0.4.2)
* You've restarted VS Code, just in case.

**Comment by sailro** [comment]
Also from #333 we've learned that having the Unity Package `Netcode for Entities` crashes the Language Server Protocol providing code completion. Are you using this package in your project?

**Comment by sobczyk** [comment]
I have the exact same problem, I created an empty net6.0 project.
I run
VS Code 1.81.0
C# v2.0.328
C# Dev Kit v0.4.2
IntelliCode for C# Dev Kit v0.1.26

on Ubuntu 23.04
and run dotnet 6.0.120 from apt pakcages

**Comment by jbevain** [comment]
Hi,

At this point we believe the `C#` and `C# Dev Kit` have pushed a fix for the loading issue, so we're going to close this issue. Please make sure both extensions are up to date and you've followed the README of the `Unity extension`:

* In Unity, you need to upgrade the `Visual Studio Editor` package to 2.0.20 or above (the latest is 2.0.21)
* Select Visual Studio Code as the External Editor.
* Regenerate Project Files

If you hit more loading issues please open a new one.

Thank you!
