### ISSUE TITLE
[BUG] Unity Package `Netcode for Entities` crashes the LanguageServerHost 

### ISSUE THREAD

**Issue by 976047167** [microsoft/vscode-dotnettools#333]
### Describe the Issue

![image](https://github.com/microsoft/vscode-dotnettools/assets/29335242/fd9b4696-e36d-4a79-b56a-22c7792676af)
My unity project requires the "net code for entities" package. When I import it, the vscdoe spell checking is not working. And it starts reporting errors

### Steps To Reproduce

1、create a unity project
2、choose "window/package manager"
3、import "Netcode for Entities"
4、run vscode

### Environment Information

-VS code: 
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25217

- Unity: 2022.3.4f1
   Netcode for Entities: 1.0.12

**Comment by jbevain** [comment]
Hi @976047167,

Thanks a lot for reporting this. I can reproduce the issue. We'll look into it and get back to you.

**Comment by arkalyanms** [comment]
Keeping on dotnettools for now since we are not sure if this could be a RPC issue yet. @beccamc feel free to move when ready.

**Comment by SoprachevAK** [comment]
Do you have any progress on fixing this issue? Can you share the estimated finish time?

**Comment by 976047167** [comment]
> Do you have any progress on fixing this issue? Can you share the estimated finish time?

Chose JetBrains Rider instead of VSC

**Comment by d-bucur** [comment]
Same issue on Ubuntu 22.04, just no errors in the C# logs. On a project without Entities it does work.

**Comment by jbevain** [comment]
Good news folks, our LSP folks have identified the issue and have a fix that is being reviewed. Hopefully the fix lands soon, we'll close the issue when it does.

**Comment by SoprachevAK** [comment]
Roslyn pipe server stream was merged and fixing this error doesn’t block anything. What are the next steps?

**Comment by jbevain** [comment]
@SoprachevAK the fix has been merged but it hasn't shipped yet.

**Comment by dibarbet** [comment]
We just released version 2.3.27 of the C# extension which contains the fix.  

If you're still having problems please open a *new* issue.
