### ISSUE TITLE
[BUG] Autocomplete doesn't insert suggestion when overriding parent methods

### ISSUE THREAD

**Issue by RokkoEffe** [microsoft/vscode-dotnettools#334]
### Describe the Issue

I am trying to accept suggestion for overriding parent method, but right after I press Tab or Enter, suggestion windows just disappears and no suggestion is inserted. All other types of suggestions are working - the problem is only with overriding methods.

First screenshot: I typed "override" and then suggestion window pops up. I scroll to "SomeMethod()", which I want to be autocompleted
![image](https://github.com/microsoft/vscode-dotnettools/assets/26933036/1d58e3ed-f5d4-4b79-b4ce-ddfa4e3d3f31)

Second screenshot: Just after I pressed Tab, no suggestion was inserted
![image](https://github.com/microsoft/vscode-dotnettools/assets/26933036/5eb76c3e-953b-454c-be2f-32732cf54ada)

### Steps To Reproduce

1. Have a parent class with virtual method and a child class, that extends parent
2. In child class, type "override" and wait for suggestions window to pop up
3. Select method from parent class and press "Tab" or any button used to accept suggestions

### Expected Behavior

Suggestion is inserted, as it works with any other type of suggestions

### Environment Information

- OS: Windows 11
- VSCode version: 1.81.0

- C# devkit extension: 0.4.2
- Unity VSCode extension: 0.9.0
- Unity Visual Studio Editor package: 2.0.20

**Comment by arkalyanms** [comment]
Tracked at https://github.com/dotnet/vscode-csharp/issues/6011
