### ISSUE TITLE
[BUG] namespace intellisense not working

### ISSUE THREAD

**Issue by andyrub18** [microsoft/vscode-dotnettools#34]
### Describe the Issue

When I create a new c# class, the namespace intellisence does not kick in. It just write the root folder of the project

### Steps To Reproduce

create a new class with c# dev kit in a nested folder and watch the auto generated namespace name

### Expected Behavior

A namespace with the nested folder structure folder1.folder2.folder3...

**Comment by andyrub18** [comment]
I hope I can have a solution soon

**Comment by smitpatel** [comment]
@andyrub18  - Can you share which SDK version are you using? Also if you can share content of generated file that will help us investigate.
