### ISSUE TITLE
[BUG] Cannot find contract with name "Microsoft.VisualStudio.ProjectSystem.Server.ProjectPackageSystem"

### ISSUE THREAD

**Issue by filipnavara** [microsoft/vscode-dotnettools#340]
### Describe the Issue

<img width="1029" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1764393/cc002cb4-10d8-4b3f-8399-5046adb818dc">

### Steps To Reproduce

1. Update C# Dev Kit to version v0.3.21
2. Open any project, in this case a one created with `dotnet new console` and observe that IntelliSense doesn't work

### Expected Behavior

Everything works; downgrade to 0.2.100 gets the functionality back

### Environment Information

- OS: macOS Sonoma beta 5
- VS Code 1.81.0 
- .NET MAUI extension v0.2.12

**Comment by LokiMidgard** [comment]
Same Problem on a 
### Environment Information

C# extension 
- Version: 2.0.357

VS Code About Information

- Version: 1.81.1 (user setup)
- Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
- Date: 2023-08-09T22:22:42.175Z
- Electron: 22.3.18
- ElectronBuildId: 22689846
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621

**Comment by Michael-Eng** [comment]
Dup of #318
