### ISSUE TITLE
Add the ability to debug using a custom ip and port

### ISSUE THREAD

**Issue by aldelaro5** [microsoft/vscode-dotnettools#341]
Type: <b>Feature Request</b>

Visual studio and rider provides this capability where you can debug over the network a player or even editor if you know its LAN ip and port. This extension doesn't provide it and it's something I happen to need a lot.

Extension version: 0.9.0
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:41:52.615Z)
OS version: Linux x64 6.4.7-arch1-1
Modes:

EDIT: to clarify, I am talking about the unity extension, the generated report didn't made it clear.

**Comment by jbevain** [comment]
Good news! Here's an extract from the [Unity's extension page on the marketplace](https://aka.ms/vscode-unity):

# Attaching the Unity debugger to a Unity player

By default, your Unity project will be setup with a debugger configuration to attach the Unity debugger to the Unity Editor instance opened on the project.

If you want to debug a Unity Player, the easiest way is to use the Attach Unity Debugger command.

Alternatively, you can modify the .vscode/launch.json file in your project and add a new debugger configuration for a IP endPoint you know of:

```json
    {
        "name": "Attach to Xbox",
        "type": "vstuc",
        "request": "attach",
        "endPoint": "127.0.0.1:56321"
    }
```

Then just use the dropdown menu of the Debug interface to select the configuration you want to debug:

<img width="204" alt="Attach to custom IP" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/ad4295e5-a766-4fcb-be67-eee81d770d04">
