### ISSUE TITLE
[SUGGESTION] Add a way to skip steps or ignore scripts while debugging with the Unity extension

### ISSUE THREAD

**Issue by burninester** [microsoft/vscode-dotnettools#342]
### Describe the feature you'd like

While I'm using the attached debugger from vscode's Unity extension and use the "Step Into" option, I run into certain scripts that are irrelevant to me such as "InputActionState.cs" and "DelegateHelper.cs". I would like to ignore these files while debugging, or to automatically skip them somehow.

### Alternatives considered

- I've tried to read the documentation but there's nothing that details about skipping or ignoring files while debugging: https://code.visualstudio.com/docs/other/unity
- Visual Studio already has this feature, but I prefer using Visual Studio Code: https://stackoverflow.com/questions/18308561/ignore-specific-file-when-debugging

### Environment Information

- Windows 10
- VSCode Version: 1.81.0
- Unity Extension Version: v0.9.0

**Comment by jbevain** [comment]
The Unity debugger supports the .NET attributes to control whether a method is stepped into or not `DebuggerStepThrough`, `DebuggerNonUserCode`, `DebuggerHidden`, but it doesn't support them at the class level.
