### ISSUE TITLE
Attaching Unity debugger fails

### ISSUE THREAD

**Issue by sgallouet** [microsoft/vscode-dotnettools#343]
Type: <b>Bug</b>

1/i have unity running. 
2/i execute "Attach Unity Debugger", it shows my unity instance with endpoint 127.0.0.1:56736. I select it.
3/Windows defender opened and asked me to allow which i did. (first run only)
4/Wait a bit then have a visual studio code popup just saying "Failed to attach debugger to 127.0.0.1:56736". Not finding any other explainantion or logs error.

Before migrating to this new Unity plugin i was able to attach debugger and debug with the depreciated plugin

Extension version: 0.9.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (8.91GB free)|
|Process Argv|D:\\BitBucket\\removed--crash-reporter-id e368b83b-c567-437d-886b-c77d9f382a58|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by jbevain** [comment]
Hi, Thanks for reaching out. The new Unity extension is a currently a preview so some bumps on the road are to be expected. Attaching the debugger, either by pressing `F5` or using the `Attach Unity Debugger` command should work though.

Most of the time, this is a result of a misconfiguration in the Windows Firewall. Please make sure that your Firewall allows Visual Studio Code and Unity to communicate over TCP for the current type of network you're connected to.

Sometimes also it's because Unity's server failed to bind the debugger on a TCP port or crashed, in that case you can simply restart Unity.

**Comment by sgallouet** [comment]
Hi, Thanks for your reply and for fixing the title.

I have disabled windows firewall and rebooted windows and still face same issue.
![image](https://github.com/microsoft/vscode-dotnettools/assets/41896688/efcbe437-6d03-4917-bbbb-069424fac9ef)
![image](https://github.com/microsoft/vscode-dotnettools/assets/41896688/be85ae81-8344-49f5-aa5e-e6588003855a)

Is there somewhere some logs we can read that could give more information? Or some commands to try to replicate the issue?

**Comment by sgallouet** [comment]
Working now after doing :

1. Moved to VSCODE insider (not sure if that was needed)
2. Downgraded C# Dev Kit extension from v0.4.2 (pre-release) to v0.3.21 (release)

**Comment by jbevain** [comment]
Happy to hear you got it working!

**Comment by JManikiza** [comment]
I specifically had to add:             "endPoint": "127.0.0.1:565656"
to the launch.json the attach to unity created
