### ISSUE TITLE
no definition found When use C# Dev Kit

### ISSUE THREAD

**Issue by cookgoing** [microsoft/vscode-dotnettools#344]
Type: <b>Bug</b>

When i install C# Dev Kit, 'go to definition ' is useless.  All is ok when i use Omnisharp previously Which can not use in C# Dev Kit.

C# output:
Dotnet path: c:\Users\sd\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...

dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.315 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

Extension version: 0.3.21
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (20.49GB free)|
|Process Argv|G:\\UnityProject\\TestUnity2022|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jdiekhoff-emerson** [comment]
Was a resolution found for this? I'm also experiencing this with C# Dev Kit and can't find any answers.

**Comment by marshalluous** [comment]
I am also experiencing this issue. Can't find any answer.

**Comment by thenullvoid** [comment]
Also having this error, can we please re-open the ticket until it is resolved?

**Comment by marshalluous** [comment]
Found a solution: The file which behaved like this, was in my Explorer view. But the project was actually not added to the solution (.sln). To add it to the solution I opened the Solution Explorer (at the bottom of the Explorer), listed all available Projects and added missing projects to the solution

**Comment by AntonAndev** [comment]
I have this problem too on macOS and Windows 11. Unity project.

**Comment by AntonAndev** [comment]
Found a solution: completely removed VS code with all temporary files (using cmd), reinstalled VS Code, Unity Extension with all dependencies. Got a new tab Solution Explorer. Now all is working as expected.

**Comment by thenullvoid** [comment]
My solution involved switching LInux distros, I was on fedora but through searching most issue resolves were on ubuntu. I switched to debian (ubuntu forks off debian) I followed instructions for installing unity, .net 7, mono, vscode, and c# integration for vscode extension, updated the "Visual Studio Editor" package (not visual studio code package) to 2.0.20 which I personally had to do manually through the manifest file (I was the only one with that particular issue) and lastly regenerating project files through unity preferences external tools making sure to checkmark "Embedded packages" "Local packages" "Registry packages" "Git packages" "Builtin packages"

**Comment by j1mmie** [comment]
Opening Command Palette and selecting ".NET: Open Solution" worked for me

**Comment by uponatime2019** [comment]
> Opening Command Palette and selecting ".NET: Open Solution" worked for me

It not working for me

**Comment by psulek** [comment]
> Opening Command Palette and selecting ".NET: Open Solution" worked for me

Strange but this helps me. I have only csproj file opened as folder so maybe that was a problem?

**Comment by ewilansky** [comment]
The only way around this for me is to ensure that all instances of VSCode are closed. Once I restart VSCode and wait for the C# Dev Kit to complete startup, I'm able to navigate to code definitions. Running OSX Sanoma 14.1.1 on Apple Silicon.

**Comment by uponatime2019** [comment]
This issue stop me from use VSCode for C#, still no solution to fix it

**Comment by psulek** [comment]
@uponatime2019 
- open folder which contains projector/solution
- press `F1` and select `.NET: Open Solution`

If you dont have `sln` file, create it via cmd/bash:
- create new sln -`dotnet new sln --name MySolution` 
- add csproj into sln - `dotnet sln add myproj.csproj`
- reopen folder, and exec `.NET: Open Solution`

**Comment by Voxar** [comment]
For me it was that I had not opened the solution in the "Solution Explorer". Apparently you can't just use the normal terminal shortcut (`code .`) for this (kind of makes sense but if you don't know you don't know)

**Comment by TheSimicSlaw** [comment]
>> Opening Command Palette and selecting ".NET: Open Solution" worked for me
Huh. Worked for me, but I had to restart VSCode first. It's odd though, since it appeared I already had a solution opened.
