### ISSUE TITLE
Remote extension host support

### ISSUE THREAD

**Issue by koliyo** [microsoft/vscode-dotnettools#346]
Type: <b>Bug</b>

I am running remote ssh and get this
```
Cannot activate the 'Unity' extension because it depends on the '.NET Install Tool for Extension Authors' extension which is disabled.
```

And the referenced extension says:

```
 This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'SSH: kWindows' to enable. Learn More
```

Extension version: 0.9.0
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Windows_NT x64 10.0.22621

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id f832144c-10c0-4611-ab59-f43dda688d68|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: kWindows|
|OS|Windows_NT x64 10.0.22621|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|Memory (System)|31.71GB (3.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by koliyo** [comment]
Using the new Unity extension, https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/

**Comment by koliyo** [comment]
This seems to have been resolved after deleting the `.vscode-remote` directory on the target machine and let VS code repopulate it

**Comment by jbevain** [comment]
Hi @koliyo, thanks for reaching out. Happy to see this seems to have been resolved!
