### ISSUE TITLE
C# DevKit -Test Explorer: Tests can't run on Windows when GitBash is configured as the default integrated shell

### ISSUE THREAD

**Issue by josh-hemphill** [microsoft/vscode-dotnettools#349]
Type: <b>Bug</b>

## Issue Description ##

Having tried changing the automation shell in the settings or setting a default build task with the shell specified, the test runner for c# will always use the `terminal.integrated.defaultProfile.windows` setting regardless.

When running on Windows with GitBash as the default shell, the C# test runner incorrectly still uses unescaped windows paths which result in the commands immediately failing.

## Expected Behavior ##

For the test explorer to correctly use the already configured vscode task/automation terminal, detect the running shell and use correct path formats, or provide a setting to explicitly set the shell used.

## Actual Behavior ##

Completely opaque about how the test tasks are being run or controlled, with no settings to control it, at least not anywhere in VSCode settings.

### C# Dev Kit - Test Explorer log ###
<details>Created Test Controller
Using vstest from dotnet sdk in [C:\Program Files\dotnet\sdk\7.0.306].
Initialized Test Explorer Server [44184]
Test Store Folder: c:\Users\j1rob\AppData\Roaming\Code\User\workspaceStorage\0ada4e6b6570cd1669fcad067a51102f\ms-dotnettools.csdevkit
Test data store opened in 0.016 sec.
Initialized project system provider.
1 projects added, 0 changed, 0 removed.
Scheduling discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\net7.0\SAN_Parser.Test.dll [0]
0 projects added, 0 changed, 0 removed.
Tests are available, running test discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\net7.0\SAN_Parser.Test.dll
Scheduling discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\net7.0\SAN_Parser.Test.dll [1691356914778]
========== Starting test discovery ==========
[xUnit.net 00:00:00.01] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.9)
[xUnit.net 00:00:02.05]   Discovering: SAN_Parser.Test
[xUnit.net 00:00:02.09]   Discovered:  SAN_Parser.Test
========== Test discovery finished: 1 Tests found in 3.6 sec ==========
1 tests discovered from e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\net7.0\SAN_Parser.Test.dll in 3648.8068 ms
0 projects added, 0 changed, 0 removed.
1 projects added, 0 changed, 1 removed.
Scheduling discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\SAN_Parser.Test.dll [0]
Tests are available, running test discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\SAN_Parser.Test.dll
Scheduling discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\SAN_Parser.Test.dll [1691357095564]
========== Starting test discovery ==========
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.9)
[xUnit.net 00:00:00.63]   Discovering: SAN_Parser.Test
[xUnit.net 00:00:00.66]   Discovered:  SAN_Parser.Test
========== Test discovery finished: 1 Tests found in 1.5 sec ==========
1 tests discovered from e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\SAN_Parser.Test.dll in 1522.1794 ms
0 projects added, 0 changed, 0 removed.
0 projects added, 0 changed, 0 removed.
0 projects added, 0 changed, 0 removed.
Error building your test projects. Please correct the build errors and try again.
Tests changed, running test discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\SAN_Parser.Test.dll
Scheduling discovery: e:\Share\dev\SAN_Parser\SAN_Parser.Test\bin\Debug\SAN_Parser.Test.dll [1691395485475]</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.328
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  5.0.416 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|better-comments|aaron-bond|3.0.2|aaron-bond.better-comments-3.0.2|
|code-runner|formulahendry|0.12.0|formulahendry.code-runner-0.12.0|
|code-spell-checker|streetsidesoftware|2.20.5|streetsidesoftware.code-spell-checker-2.20.5|
|color-highlight|naumovs|2.5.0|naumovs.color-highlight-2.5.0|
|crates|serayuzgur|0.6.0|serayuzgur.crates-0.6.0|
|csdevkit|ms-dotnettools|0.3.21|ms-dotnettools.csdevkit-0.3.21-win32-x64|
|csharp|ms-dotnettools|2.0.328|ms-dotnettools.csharp-2.0.328-win32-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|dotenv|mikestead|1.0.1|mikestead.dotenv-1.0.1|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|even-better-toml|tamasfe|0.19.2|tamasfe.even-better-toml-0.19.2|
|formate|MikeBovenlander|1.2.1|mikebovenlander.formate-1.2.1|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|gitlab-workflow|GitLab|3.72.3|gitlab.gitlab-workflow-3.72.3|
|gitlens|eamodio|14.2.0|eamodio.gitlens-14.2.0|
|goto-alias|antfu|0.1.2|antfu.goto-alias-0.1.2|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|highlight-string-code|iuyoy|0.4.5|iuyoy.highlight-string-code-0.4.5|
|i18n-ally|lokalise|2.10.0|lokalise.i18n-ally-2.10.0|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jupyter|ms-toolsai|2023.7.1002162226|ms-toolsai.jupyter-2023.7.1002162226-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|linux-desktop-file|nico-castell|0.0.21|nico-castell.linux-desktop-file-0.0.21|
|lit-html|bierner|1.11.1|bierner.lit-html-1.11.1|
|live-server|ms-vscode|0.4.9|ms-vscode.live-server-0.4.9|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|LogFileHighlighter|emilast|2.16.0|emilast.logfilehighlighter-2.16.0|
|lorem-ipsum|Tyriar|1.3.1|tyriar.lorem-ipsum-1.3.1|
|markdown-mermaid|bierner|1.19.0|bierner.markdown-mermaid-1.19.0|
|material-icon-theme|PKief|4.29.0|pkief.material-icon-theme-4.29.0|
|mssql|ms-mssql|1.20.0|ms-mssql.mssql-1.20.0|
|npm-intellisense|christian-kohler|1.4.4|christian-kohler.npm-intellisense-1.4.4|
|path-intellisense|christian-kohler|2.8.4|christian-kohler.path-intellisense-2.8.4|
|playwright|ms-playwright|1.0.15|ms-playwright.playwright-1.0.15|
|postcss|csstools|1.0.9|csstools.postcss-1.0.9|
|prisma|Prisma|5.1.0|prisma.prisma-5.1.0|
|python|ms-python|2023.14.0|ms-python.python-2023.14.0|
|rainbow-csv|mechatroner|3.7.0|mechatroner.rainbow-csv-3.7.0|
|remote-containers|ms-vscode-remote|0.304.0|ms-vscode-remote.remote-containers-0.304.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-ssh|ms-vscode-remote|0.102.0|ms-vscode-remote.remote-ssh-0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.81.0|ms-vscode-remote.remote-wsl-0.81.0|
|sass-indented|syler|1.8.27|syler.sass-indented-1.8.27|
|shell-format|foxundermoon|7.2.5|foxundermoon.shell-format-7.2.5|
|sonarlint-vscode|SonarSource|3.20.2|sonarsource.sonarlint-vscode-3.20.2-win32-x64|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.2.0|ms-mssql.sql-database-projects-vscode-1.2.0|
|svg|jock|1.5.3|jock.svg-1.5.3|
|synthwave-vscode|RobbOwen|0.1.15|robbowen.synthwave-vscode-0.1.15|
|vitest-explorer|ZixuanChen|0.2.42|zixuanchen.vitest-explorer-0.2.42|
|volar|Vue|1.8.8|vue.volar-1.8.8|
|vscode-conventional-commits|vivaxy|1.25.0|vivaxy.vscode-conventional-commits-1.25.0|
|vscode-counter|uctakeoff|3.2.1|uctakeoff.vscode-counter-3.2.1|
|vscode-coverage-gutters|ryanluker|2.11.0|ryanluker.vscode-coverage-gutters-2.11.0|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-drawio|hediet|1.6.6|hediet.vscode-drawio-1.6.6|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-firefox-debug|firefox-devtools|2.9.8|firefox-devtools.vscode-firefox-debug-2.9.8|
|vscode-html-css|ecmel|1.13.1|ecmel.vscode-html-css-1.13.1|
|vscode-json5|mrmlnc|1.0.0|mrmlnc.vscode-json5-1.0.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-markdownlint|DavidAnson|0.51.0|davidanson.vscode-markdownlint-0.51.0|
|vscode-nginx-conf|ahmadalli|0.1.3|ahmadalli.vscode-nginx-conf-0.1.3|
|vscode-pull-request-github|GitHub|0.70.0|github.vscode-pull-request-github-0.70.0|
|vscode-pylance|ms-python|2023.8.10|ms-python.vscode-pylance-2023.8.10|
|vscode-taskexplorer|spmeesseman|2.13.2|spmeesseman.vscode-taskexplorer-2.13.2|
|vscode-thunder-client|rangav|2.10.2|rangav.vscode-thunder-client-2.10.2|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-win32-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 0.3.21
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (36.08GB free)|
|Process Argv|--crash-reporter-id c0524e09-16f5-4dba-9837-8fc1a92ff23d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by osotorrio** [comment]
I have exactly the same issue. Any workaround in the meantime?

By the way, this seems related: https://github.com/microsoft/vscode-dotnettools/issues/253

**Comment by lifengl** [comment]
build is no longer depending on which shell is being used.
