### ISSUE TITLE
[BUG] IntelliSense for TypeScript stops working when using C# Dev Kit

### ISSUE THREAD

**Issue by bananashell** [microsoft/vscode-dotnettools#351]
### Describe the Issue

When activating C# Dev Kit, IntelliSense works just fine in C# projects but in TypeScript files it (.ts, .tsx) never stops loading. Navigation is affected too.

Uninstalling/disabling C# Dev Kit + reloading the IDE resolves the issue

<img width="399" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/15868581/ebc2a33b-7d4d-41c1-897f-fcdddce3546a">

### Environment Information

- OS: MacOS Ventura
- VSCode:  1.81.0
- TypeScript: 5.1.6
- C# Dev Kit: 0.3.21

**Comment by timheuer** [comment]
@bananashell Can you confirm these are .ts/tsx files in a C# project? or any, regardless of type of workspace?

**Comment by arkalyanms** [comment]
@jasonmalinowski would you confirm if there is any roslyn side involvement here? I would imagine this comes as miscellaneous file support in CPS?

**Comment by jasonmalinowski** [comment]
I wouldn't expect any involvement here.

**Comment by bananashell** [comment]
Just tried opening a Next.js project that has no C# code in it and I get the same result when I activate C# Dev Kit. To resolve it I uninstall C# Dev Kit, set useOmniSharp = true and restart vscode. Re-installing C# Dev Kit introduces the bug again - regardless of restarts

**Comment by timheuer** [comment]
> @timheuer Just tried opening a Next.js project that has no C# code in it and I get the same result when I activate C# Dev Kit. To resolve it I uninstall C# Dev Kit, set useOmniSharp = true and restart vscode. Re-installing C# Dev Kit introduces the bug again - regardless of restarts

This is really odd...is there a repo we can take a look at here? Or could you create a similar one? It feels odd that anything in our language server would be activating here and may be a project thing.  You mentioned "opening a Next.js project" -- do you actually have a esproj/ntvsproj file that you are opening? Or just opening a folder in the workspace.  And when doing so is there other C#/csproj files in the same workspace anywhere?

I think we need help better understanding your environment/setup/workspace a bit more.  Any example repo/repro would help.

**Comment by bananashell** [comment]
I'm unable to recreate the issue with a small setup so it might be connected to the sheer size of the monorepo I'm opening.

There are 336 .csproj files and 4 nextjs projects in the same folder structure were I'm using .NET Open Solution to only 'open' part of the backend domain at a time. With this folder structure

- root
  - apis
    - C# project #1
    - C# project #2
    - etc..
  - libs 
    - shared c# lib #1
    - shared c# lib #2
    - etc 
  - web
    - Typescript-web1
    - Typescript-web1
    - etc..
    
So you can go ahead and close the issue since I can't reproduce it with a small project :(

**Comment by timheuer** [comment]
Thanks for addigional @bananashell -- I'm wondering @jasonmalinowski if any logs might help us see if there is any conflicts here in competing processes that might be contributing?

**Comment by arkalyanms** [comment]
Tagging @lifengl instead since this is controlled by CPS.

**Comment by jasonmalinowski** [comment]
@bananashell Since you mentioned size, are our background processes consuming lots of CPU when you're trying get TypeScript completion? If you wait until we go idle, and then try it, does that work?

**Comment by Michael-Eng** [comment]
Closing since we can't repro and haven't heard back.
