### ISSUE TITLE
Project failed to load

### ISSUE THREAD

**Issue by Vini-002** [microsoft/vscode-dotnettools#352]
Type: <b>Bug</b>

When creating a new project with an older .NET version (in my case .NET 2.0), gives the error failed to restore solution `Starting command: "dotnet.exe" restore c:\mypath\myproject.sln --interactive...
MSBUILD : error MSB1001: Opção desconhecida. (unkown switch)
Opção: --interactive
`

Option `--interactive` was introduce in a later dotnet version. How could I workaround that?

Extension version: 0.3.21
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (5.73GB free)|
|Process Argv|--crash-reporter-id b1618cc4-3a1d-4e20-9b8c-e5d88003ef69|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
vscrpc:30673769
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by aortiz-msft** [comment]
Please install a supported version of .NET: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.

**Comment by Vini-002** [comment]
I knew it was an old version. As I am new to C#/.NET I misinterpreted the documentation of the package I was using and tought it was not compatible with newer .NET versions.
