### ISSUE TITLE
[BUG] xunit no any output

### ISSUE THREAD

**Issue by yedajiang44** [microsoft/vscode-dotnettools#354]
### Describe the Issue

no output any message

### Steps To Reproduce
```
public class UnitTest
{
    private readonly ITestOutputHelper outputHelper;

    public UnitTest(ITestOutputHelper outputHelper)
    {
        this.outputHelper = outputHelper;
    }
    [Fact(DisplayName = "output test")]
    public void Test()
    {
        outputHelper.WriteLine("Hello C# Dev Kit");
    }
}
```
### Expected Behavior

output "Hello C# Dev Kit"

### Environment Information

vscode: 1.81.0 (user setup)
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22624
C# Dev Kit: 0.3.21
xunit: 2.5.0

**Comment by christianfosli** [comment]
FYI the same error occurs in the open source vscode-dotnet-test-explorer (https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/94). That issue includes some more info about why that might be.

**Comment by yedajiang44** [comment]
> FYI the same issue is present in the open source vscode-dotnet-test-explorer ([formulahendry/vscode-dotnet-test-explorer#94](https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/94)). That issue includes some more info about why that might be.

but output message when i use `Test Explorer UI` and `.Net Core Test Explorer` without `C# Dev Kit` .

steps:

- uninstall `C# Dev Kit`
- set `dotnet.server.useOmnisharp: true` in `settings.json`
- install `Test Explorer UI`
- install `.Net Core Test Explorer`
- set `dotnet.server.useOmnisharp: true` in `settings.json`
- run test in vscode ui

now, fcous on outout view and select `.Net Test Log`, you can see some message.

unfortunately i don't know how to get then use `C# Dev Kit`, i need some help.

**Comment by AbhitejJohn** [comment]
While I can't speak for the linked extension, this seems very similar to #159 so resolving this against that. Thank you for sharing your feedback.
