### ISSUE TITLE
[BUG] Objects defined in XAML are shown as undefined in code behind

### ISSUE THREAD

**Issue by lhak** [microsoft/vscode-dotnettools#36]
### Describe the Issue

After upgrading the extension, objects defined in XAML via x:Name and also the InitializeComponent() method are shown as undefined in code behind. 

### Steps To Reproduce

1. Open a WindowsAppSDK project code behind file
2. Observe the shown errors

### Expected Behavior

Objects defined in XAML should be detected as defined in code behind

### Environment Information

-Windows 11
-VSCode 1.78.2
-C# extension v2.0.206

**Comment by arkalyanms** [comment]
Moved to https://github.com/microsoft/vscode-dotnettools/issues/65
