### ISSUE TITLE
[BUG] Could not resolve the dotnet path!

### ISSUE THREAD

**Issue by kant2002** [microsoft/vscode-dotnettools#366]
### Describe the Issue

```
[Error - 1:16:12 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
	at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/kant/.vscode/extensions/ms-dotnettools.csharp-2.0.328-linux-x64/dist/extension.js:2:1407951)
	at Generator.next (<anonymous>)
	at s (/home/kant/.vscode/extensions/ms-dotnettools.csharp-2.0.328-linux-x64/dist/extension.js:2:1406556)
```

```
$ which dotnet
/usr/bin/dotnet
```

Since I'm on Gentoo, I would appreciate if there way how I can troubleshoot this issue myself. Given that extension is minified and file is huge, finding what's going wrong would be painful. 

### Steps To Reproduce

Just open project

**Comment by arkalyanms** [comment]
@kant2002 would you be able to confirm if the latest update of the C# extension unblocks you?

**Comment by kant2002** [comment]
Seems to be. At least I do not see this error when I open my solution. I think I can close this. Will reopen if discover exact same error on same machine

**Comment by Jamespronger37** [comment]
yeah i don't know i wanted to create a batch file but the issue is that for some reason the inner shell of the application doesn't work so i can't create a security system in C#.
