### ISSUE TITLE
[BUG] When upgrading to dev kit the source generators no longer work.

### ISSUE THREAD

**Issue by michaelstaib** [microsoft/vscode-dotnettools#37]
### Describe the Issue

I have a project with a source generator which worked with Visual Studio full, Rider and VSCode omnisharp... after upgrading this no longer works. If I build with `dotnet build` I have no errors but the intellisense does not recognise generated code.

### Steps To Reproduce

1. `dotnet new install hotchocolate.templates`
2. `dotnet new graphql`
3. `dotnet build`
4. `code .`

In the program.cs the extension method `AddTypes` has squiggles. This method is created by the source generator.

### Expected Behavior

Source generators work like in the previous version.

### Environment Information

- OS macOS

**Comment by sailro** [comment]
I spotted as well that custom Roslyn Analyzers (in general I mean, not only source generators) are not always called in the context of the new C# extension + C# Dev Kit.

@mavasani do you think it can be something similar to what you fixed for diagnostic suppressors ?
https://github.com/dotnet/roslyn/pull/68270

cc @jbevain

**Comment by MarsonShine** [comment]
+1
same MacOS

**Comment by arkalyanms** [comment]
This is planned work that is oncoming.

**Comment by jasonmalinowski** [comment]
We do expect generators to be running; we don't quite have full support for generators yet. Other folks who commented on this issue (@sailro and @mvromer) are you also on macOS?

**Comment by MarsonShine** [comment]
Just now, I was running windows and everything was fine, recognizing `ISourceGenerator` and `GeneratorAttribute`

**Comment by jasonmalinowski** [comment]
@mvromer OK, thanks for confirming it's not just macOS!
