### ISSUE TITLE
[BUG] Plugin conflicts with ShaderlabVSCode

### ISSUE THREAD

**Issue by Yif1999** [microsoft/vscode-dotnettools#371]
### Describe the Issue

When I enable this plug-in and amlovey's ShaderlabVSCode plug-in in the workspace at the same time, this plug-in will invalidate the function of ShaderlabVSCode, and even cannot comment the shader code through shortcut keys ctrl-/ (currently testing .shader and .hlsl files cannot use code comments). The problem disappeared after trying to disable the Unity plugin.

### Steps To Reproduce

Enable this plug-in and amlovey's ShaderlabVSCode plug-in simultaneously.

### Expected Behavior

ShaderlabVSCode plug-in can work.

### Environment Information

OS：
macOS 13.5

VSCode：
Version: 1.81.0
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

Plugin：
Unity v0.9.0
ShaderlabVSCode v1.5.1

**Comment by jbevain** [comment]
Thanks for reporting this.

**Comment by sailro** [comment]
Could you try the following:

Edit your `.vscode/settings.json` to add a `"files.associations"` section like this:

```json 
{
  // ... [existing settings]
  "files.associations": {
    "*.shader": "shaderlab",
    "*.hlsl": "shaderlab"
    // ... [other extensions]
  }
}
```

This should instruct VSCode to use ShaderlabVSCode instead of our builtin grammars for those files.

**Comment by Yif1999** [comment]
> Could you try the following:
> 
> Edit your `.vscode/settings.json` to add a `"files.associations"` section like this:
> 
> ```js
> {
>   // ... [existing settings]
>   "files.associations": {
>     "*.shader": "shaderlab",
>     "*.hlsl": "shaderlab"
>     // ... [other extensions]
>   }
> }
> ```
> 
> This should instruct VSCode to use ShaderlabVSCode instead of our builtin grammars for those files.

Thank you, this method solved my problem! One possible suggestion would be to provide the option to turn off file associations in the Unity plugin settings, I think that would be more user friendly! ❤️
