### ISSUE TITLE
[BUG] Solution Explorer doesn't show files, only solution and projects

### ISSUE THREAD

**Issue by justintoth** [microsoft/vscode-dotnettools#375]
### Describe the Issue

After installing the C# Dev Kit and C# extensions in VS Code, the Solution Explorer shows on the left of VS Code but it only shows the solution and projects. If I expand a project, it shows this error message:

Expected 1 export(s) with contract name "Microsoft.VisualStudio.ProjectSystem.Server.ProjectSystemPackage" but found 0 after applying applicable constraints.

Not sure if it's related or not, but the C# extension also had trouble. When installing it in VS Code, it asked me to reload but then it showed a message about failing to start the language service for the C# extension and it was uninstalled again. I tried multiple times and a clean install of VS Code, to no avail. I was only able to get the C# extension to install by selecting the Pre-Release version.

<img width="1697" alt="Screenshot 2023-08-10 at 10 39 53 AM" src="https://github.com/microsoft/vscode-dotnettools/assets/1443831/7eab82e0-d459-4813-bfd1-d295d34a0f9b">

### Environment Information

Windows 11 Preview for ARM (within Parallels on a Macbook Pro)
VS Code 1.81.0

**Comment by timheuer** [comment]
Hi @justintoth do you have .NET 8 Preview 7 installed? (See #318)

**Comment by justintoth** [comment]
@timheuer Hi Tim, no I don't. We're on .NET 7.

**Comment by timheuer** [comment]
@justintoth Can you add the output of `dotnet --info` into this report from this machine?

**Comment by justintoth** [comment]
@timheuer I was mistaken, I do have .NET 8 Preview 7 installed. I didn't know because I had installed .NET 7, but a Visual Studio 2022 Preview for ARM update automatically updated me to .NET 8.

I took a look at [the issue](https://github.com/microsoft/vscode-dotnettools/issues/318) you referenced, and it seems like they were experiencing a different issue. Regardless, I switched over to the latest Insiders version of VS Code and that seemed to resolve my issues, I'm now able to install the plugin, view the contents of my projects in solution explorer, and build my .NET 7 projects. Thanks!

```
C:\Windows\System32>dotnet --info
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.23521
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: arm64
  Commit:       65b696cf5e
  RID:          win-arm64

.NET SDKs installed:
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet\x64]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by timheuer** [comment]
Thanks for confirming @justintoth
