### ISSUE TITLE
[BUG] Roslyn warnings not displayed a such

### ISSUE THREAD

**Issue by PythooonUser** [microsoft/vscode-dotnettools#376]
### Describe the Issue

Actually, I'm not sure about the severity of the issues displayed. They could be infos, warnings, or errors (I'm assuming they are warnings).

It would be great to get first-class support here in terms of red/yellow/blue squiggly lines, i.e. the language server could spit out diagnostics. They are also not shown in the problems/errors window.

![image](https://github.com/microsoft/vscode-dotnettools/assets/13063023/88d30e10-160b-4e36-bdfc-16221c788f19)

![image](https://github.com/microsoft/vscode-dotnettools/assets/13063023/84f24f4c-e8df-41bb-98a2-eaecf4beefcd)

![image](https://github.com/microsoft/vscode-dotnettools/assets/13063023/1448c6b6-37c0-49c6-b627-3c601c2cd2a4)

**Comment by jbevain** [comment]
Hey @PythooonUser, thanks for reaching out.

I'm not exactly sure I understand the issue.

The C# extension will give you red squiggles for errors:

<img width="100" alt="Screenshot 2023-08-12 at 4 08 16 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/739ecc2a-b88c-4e70-8d7a-9ddffebd7633">

Yellow squiggles for warnings:

<img width="206" alt="Screenshot 2023-08-12 at 4 08 57 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/abe07d01-a70e-44b4-8808-294586599b70">

And ... for suggestions:

<img width="197" alt="Screenshot 2023-08-12 at 4 09 15 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/549dfc99-38d8-45e1-8e3c-a26f13e2da3c">

Errors and Warnings are shown in the Problems window:

<img width="944" alt="Screenshot 2023-08-12 at 4 09 50 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/0f747c88-0baf-4e44-888c-57ab71e976cc">

What's the bug for you here?

**Comment by PythooonUser** [comment]
Take the second example, the warning (?) is "Unity message is empty".

I believe it's a warning at least. But there is no squiggly line shown.

There is also a suggestion of removing the method or adding a comment, i.e. quick fixes. But I believe that is not directly related to that diagnostic?

My point is, there is an error message displayed but it is hidden and only shown on hover. Does that make sense?

Every other language or linter I have used so far would have shown a squiggly line here.

**Comment by PythooonUser** [comment]
Maybe it's actually not necessary to show that message here, but only provide quick fixes?

**Comment by jbevain** [comment]
The `Unity message is empty` diagnostic is classified as a `Suggestion`, it comes from our [Microsoft.Unity.Analyzers](https://github.com/microsoft/microsoft.unity.analyzers) project.

The extensions built on top of the C# extension have little controls hover how the suggestions and warnings are displayed. Feel free to report an issue with the C# extension at [https://github.com/dotnet/vscode-csharp](https://github.com/dotnet/vscode-csharp), I know they were recently discussing how suggestions are displayed.

I'm going to close this as this is not something we can drive from here. Thanks again for reaching out!

**Comment by PythooonUser** [comment]
Alright, makes sense. It's probably a very subjective topic as well. Thanks for the explanation 🙂

**Comment by dibarbet** [comment]
@PythooonUser  Saw this issue while searching for a different one - just wanted to make a note that while we are not planning on changing the default display of `Suggestion` based analyzers in the C# extension, it is possible for you to configure the severity of various analyzers for your own project via an `.editorconfig`

For example, by creating a `.editorconfig` file in the root of my unity project with the following
```
[*.cs]
dotnet_diagnostic.IDE0005.severity = warning
dotnet_diagnostic.UNT0001.severity = warning
```
You should get this -
![image](https://github.com/microsoft/vscode-dotnettools/assets/5749229/68a1f6b5-0131-4866-ab87-b0da9e77c94f)

**Comment by PythooonUser** [comment]
That is awesome! Thanks for the suggestion 🙂
