### ISSUE TITLE
[BUG] Can't Access Definitions

### ISSUE THREAD

**Issue by PythooonUser** [microsoft/vscode-dotnettools#377]
### Describe the Issue

When hitting F12 to see the source of e.g. `MonoBehaviour` an error is displayed that the resource could not be resolved.

![image](https://github.com/microsoft/vscode-dotnettools/assets/13063023/ba01bce3-d187-4df2-a5d2-bf49bccce3ba)

However, when manually navigating to the path shown in the error message, the file exists:

![image](https://github.com/microsoft/vscode-dotnettools/assets/13063023/ff2b36e4-6c06-44be-9c29-1ebd07aff093)

### Steps To Reproduce

1. Open a Unity source file
2. Hit F12 on MonoBehaviour

### Expected Behavior

I expect to go to the definition of MonoBehaviour.

### Environment Information

- OS: Windows
- VSCode: 1.81.1
- Unity: 0.9.0
- C#:  2.0.346
- C# Dev Kit: 0.3.21

**Comment by alexrp** [comment]
Just for the record, this happens in regular .NET projects too, not just Unity. Seems to be a pretty significant regression.

**Comment by HanMoeHtet** [comment]
This is already tracked here. https://github.com/dotnet/vscode-csharp/issues/6098

For now, downgrading  extension `ms-dotnettools.csharp` to `v2.0.328` temporarily solve the issue.

**Comment by PythooonUser** [comment]
Thanks! Alright then. Closing.
