### ISSUE TITLE
Add setting to turn off prompts after file->new.

### ISSUE THREAD

**Issue by slowsigma** [microsoft/vscode-dotnettools#381]
Type: <b>Feature Request</b>

For some of us, these prompts are an amazing waste of time.

Extension version: 0.3.21
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by slowsigma** [comment]
It would be faster to just create a file with a generated name and then create some kind of watching logic that can derive the file name from the contents.

**Comment by timheuer** [comment]
Hi @slowsigma - can you specify which prompts? I think based on your notes, you're referring to adding a new file?
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/43b80733-76f6-41d6-b7aa-09edcdf92d56)
Is that the one?

**Comment by slowsigma** [comment]
That's the one.  However, I realize I can just work with the default (non-dev kit) explorer.  It would be pretty cool to not even have enter names on files and just have them renamed automatically according to the predominant declaration they contain.

**Comment by timheuer** [comment]
Great, thanks for confirming.  Yes the "add" from Dev Kit is meant to be a template entry point (notice the 'Custom file' option there which just let's you create anything).  Even in VS we have thought about how you can just add a file name and we interpret the template.  In fact VS2022 does this now. But if you just say Foo.cs we will assume it's a class and not an enum/iface/record/struct, etc. so you lose some fidelity.  

With this in mind would you want to keep this open knowing that your options for non-templated are: (1) use custom file from this view or (2) just use the default workspace?

**Comment by slowsigma** [comment]
I get the use case for templates, but as a touch typist I typically find it faster to just type everything out.  I close it with this comment.  Thanks.
