### ISSUE TITLE
Solution Explorer hangs when expanding project

### ISSUE THREAD

**Issue by mareich555** [microsoft/vscode-dotnettools#387]
Type: <b>Bug</b>

Press 'Create .Net Project'
Select Asp.Net WebApi
Select Folder
Select default project name
Navigate to Solution Explorer
Click > adjacent to C# <Project> name
A spinner appears and never completes

Extension version: 0.4.2
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 32, 23|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 248a802d-09cd-4a07-9326-883b4fd46d32|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Michael-Eng** [comment]
@mareich555 what version of .NET SDK do you have installed?

**Comment by mareich555** [comment]
6.0.413 [/usr/local/share/dotnet/sdk]
7.0.307 [/usr/local/share/dotnet/sdk]

**Comment by Michael-Eng** [comment]
@mareich555 we've made a bunch of fixes in the last few releases. can you please try again and let us know if things are working with the latest C# Dev Kit prerelease version?

**Comment by Michael-Eng** [comment]
Closing this issue
