### ISSUE TITLE
Excessive CPU on Solution Load, due to code analysis

### ISSUE THREAD

**Issue by RS2065** [microsoft/vscode-dotnettools#389]
Type: <b>Bug</b>

On the list of projects attached to the solution, I have 130 projects, of which over 20 are projects containing tests. When starting Visual Studio Code with the "C# Dev Kit" extension installed, the startup of all tests also begins. Due to their complexity, the tests take a long time to complete, consequently hindering the possibility of starting work. Furthermore, initiating the compilation of projects after a code change also triggers the start of all tests with the already known result. Is there a way to switch the test startup to manual mode or another method that would allow for work to proceed?

Extension version: 0.3.21
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (2.86GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/Git/soneta-enovadev|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by peterwald** [comment]
@RS2065 We don't automatically run tests on startup. Are you referring to test discovery, or test execution?

**Comment by peterwald** [comment]
@RS2065 This is baffling because we don't run tests on startup, nor do we run tests after compilation. There is no way to run tests other than triggering the Run Tests command. Is it possible that you have a build task in your task.json that is triggering this behavior? Or maybe another VS Code extension that is somehow auto-running tests?

If you are able to share the logs from the C# Dev Kit - Test Explorer output panel, that might provide some clue.

**Comment by peterwald** [comment]
Closing for now until we are able to get more information about the scenario.

**Comment by RS2065** [comment]
I analyzed the start of the project and, however, it is not an issue of testing, even though the vsconsole process itself starts. After disabling all add-ons in VSCode and unlocking only the C# Dev Kit add-on, the problem persists. The memory grows to 5-6MB, the processor almost boils. Probably the problem could be the code analyzer, which analyzes the structure of classes throughout the solution. 
There was a similar problem in an older add-on (OmniSharp), after some time a change was made to allow analyzing only the class structure in currently open files and not the entire soluition.
Hardly, executing the compilation of the project (with the msbuild command in the Terminal tab) causes the class analysis process to restart and disaster again.

Translated with www.DeepL.com/Translator (free version)

**Comment by peterwald** [comment]
Reopening and retargeting.

**Comment by mavasani** [comment]
@RS2065 We have recently added the below two background analysis scope options in the C# extension. Can you please check that both of these are set to `Open documents` for you?

![image](https://github.com/microsoft/vscode-dotnettools/assets/10605811/4a5f31bc-64ab-4a5b-9dd0-239fc1629a36)

**Comment by RS2065** [comment]
I have been absent for the past week and have only just read the message. In the configuration settings, both options are still set to _openFIles_. The current version of _VSCode_ is : **1.82.2**. 

Immediately after opening _VSCode_ (5 *.cs files active in the editor), **CPU** increases to about 75%, **Memory** for about 1-2 minutes increases to ~16,000 MB (screenshot below) .

![image](https://github.com/microsoft/vscode-dotnettools/assets/8100803/6a0ee6cc-63e1-4a74-adca-a841a50bfbd9)

Opening the same soluion in _Visual Studio 2022_ causes an initial increase in **CPU** to about 10% and **Memory** after the same time stabilizes at 3,700 MB (screenshot below).

![image](https://github.com/microsoft/vscode-dotnettools/assets/8100803/565cb1ab-e706-4aa6-a34b-c186060ac1d6)

Both _VSCode_ and _VS2022_ processes were not (!) fired simultaneously.

**Comment by LucianoBAF** [comment]
Probably related to https://github.com/dotnet/vscode-csharp/issues/5733
