### ISSUE TITLE
[BUG] C# Dev Kit  still Downloading the .NET Runtime when i Using configured 

### ISSUE THREAD

**Issue by ZhaoYuNing123** [microsoft/vscode-dotnettools#396]
```[tasklist]
### Tasks
```

**Comment by ZhaoYuNing123** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/34082513/9f283ad4-9550-405d-99c2-1b14c3b53d87)

**Comment by PyrateAkananto** [comment]
Potential workaround: https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1664353164

**Comment by ZhaoYuNing123** [comment]
> Microsoft 员工建议的临时解决方法：[dotnet/vscode-csharp#6004（评论）](https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1664353164)

![image](https://github.com/microsoft/vscode-dotnettools/assets/34082513/e97fd87f-4b76-4287-a2ac-f74022cf803e)
I have already set it up like this，it only works when i disenabled C# Dev Kit

**Comment by living2room** [comment]
+1
![Snipaste_2023-08-18_12-45-24](https://github.com/microsoft/vscode-dotnettools/assets/19966117/86fb6996-3314-4f3d-a333-1706d3acd14c)

**Comment by timheuer** [comment]
Hi @ZhaoYuNing123 @living2room -- can I ask where you are geographically located?

Please see: https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1664760326 -- is it possible you can provide the information from those steps from your environments?

**Comment by nagilson** [comment]
@ZhaoYuNing123 You need to set it for both C# and DevKit Extensions. The issue @timheuer  attached provides the id for C# and DevKit.

**Comment by baronfel** [comment]
It's also worth noting that other extensions like Unity and MAUI can also cause the Acquisition extension to attempt to download .NET - users would need to ensure that all extensions are configured with the path to .NET to prevent any out-of-band installations.  We're working on changes to the logging that will show the requesting extension ID to help users know which settings to adjust.

**Comment by nagilson** [comment]
This issue is resolved, the customer needs to set the dotnetPath for the csharp devkit id (which we now explain how to do on the runtime extension front page https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime, they only set it for the C# extension

**Comment by NihaoMonde** [comment]
I have set it up, however it still need DotNet runtime.
<img width="401" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/107738723/49a2dc5b-1057-4446-a083-064a213bedd2">

**Comment by nagilson** [comment]
> I have set it up, however it still need DotNet runtime. <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/107738723/304917372-49a2dc5b-1057-4446-a083-064a213bedd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMjQyODcsIm5iZiI6MTcwODAyMzk4NywicGF0aCI6Ii8xMDc3Mzg3MjMvMzA0OTE3MzcyLTQ5YTJkYzViLTEwNTctNDQ0Ni1hMDgzLTA2NGEyMTNiZWRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxOTA2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGFmY2M2MzdiY2Q5MDFiMjg3ZGU2NGFhMWNiNGZjYWRiYjUwNjFhOTVlMmUyZDM1N2ZjYWVhZjRhMWJmMjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dGNa4b_j3CiuvEyyJXEQWifDYJj8lg1fYKdWLzysd4o">

In this case, it requested a Runtime, but then we saw that you had one configured, so it didnt add or change anything.
