### ISSUE TITLE
[SUGGESTION] There should be a way to open a solution file and not update dotnet.defaultSolution

### ISSUE THREAD

**Issue by jasonmalinowski** [microsoft/vscode-dotnettools#399]
### Describe the feature you'd like

This is a request on behalf of @johannesergon due to their comment in https://github.com/dotnet/vscode-csharp/issues/6024#issuecomment-1676798603

If you're somebody who works with multiple solutions in a repository, you can pick different solutions but we'll update dotnet.defaultSolution to match that. But some repositories regularly need to switch between multiple solutions, so this means we're creating a file they have to avoid checking in.

**Comment by timheuer** [comment]
I believe we are changing this to be workspace specific isn't that right @lifengl ?

**Comment by lifengl** [comment]
yes, that was behavior of older version of the C# Dev Kit, now it does not set defaultSolution (except a code path to create the initial solution), the session state is now saved in extension related data outside of workspace. User can set defaultSolution by hand, which would take priority, and not be overwritten by the extension.

**Comment by Meligy** [comment]
Hello. Is this the right place to discuss / request setting multiple default solutions in a workspace?

One solution per workspace folder, chosen by the settings of this folder.

**Comment by jasonmalinowski** [comment]
@Meligy Right repository, but it'd be good to file a new bug on that!

**Comment by Meligy** [comment]
Thanks. Added https://github.com/microsoft/vscode-dotnettools/issues/494
