### ISSUE TITLE
C# Dev Kit for VS Code missing controller based API project template.

### ISSUE THREAD

**Issue by TanvirArjel** [microsoft/vscode-dotnettools#404]
### Describe the Issue

C# Dev Kit for Visual Studio code missing the controller-based Web API project while the default one is minimal API which nobody will use in production.

![image](https://github.com/microsoft/vscode-dotnettools/assets/14342773/b1b9fcb2-f653-40b5-8841-ee9d2f761fc3)

### Expected Behavior

C# Dev Kit should have a controller-based Web API project template along with minimal API.

### Environment Information

dotNET Version: 7.0 and 8.0
C# Dev Kit: 0.4.5

**Comment by Michael-Eng** [comment]
This project template requires additional parameters, and we were asked to limit to minimal for the initial release (1748634) so I'm adding the enhancement tag and removing the GA tag.

CC: @webreidi

**Comment by zwiglm** [comment]
I second this request. Also, I am not sure this - in a simple version - needs additional parameters. 
The minimal template produces all necessary code - only not in a controller.

**Comment by smitpatel** [comment]
While we work on fixing this issue, in the meantime you can use dotnet new on command like to create the project and then use add existing project functionality in C# dev kit to include that project in your solution.

**Comment by mwmcode** [comment]
The command line does not offer an option to spin off a controller-based api template. 

As you can see in the list above, there is only one `webapi` template, and it's controller-less.

**Comment by mwmcode** [comment]
`--use-controllers` flag does it like this `dotnet new webapi --use-controllers -o MyApi`

**Comment by smitpatel** [comment]
This issue has been fixed. The controller-based API project template should be available in latest release version of C# dev kit.

**Comment by janusqa** [comment]
@smitpatel  I do not see it.  Do i need to install the pre-release version to see it?

**Comment by smitpatel** [comment]
@janusqa - Apologies, we started showing MVC based Web App but for controller-based Web API project we will need parameter configuration. We have fix for this in review currently and should be available in pre-release channel in a week. I will update when it is in pre-release channel.

**Comment by smitpatel** [comment]
This is options shown for Web API project in new interface which will allow users to configure using controllers. This should be available in upcoming prerelease.
![image](https://github.com/microsoft/vscode-dotnettools/assets/1528107/5c1a200a-a08a-4a6d-a608-03f4306a1dfa)

**Comment by smitpatel** [comment]
This is available in v1.8.14
