### ISSUE TITLE
ShaderlabVscode 1.5.1 problem

### ISSUE THREAD

**Issue by FelixYoung1212** [microsoft/vscode-dotnettools#407]
### Describe the Issue

I found that this plugin cannot work with ShaderlabVscode 1.5.1. If the Unity plugin is enabled, the code prompts and code jumps for ShaderlabVscode 1.5.1 will not work properly

**Comment by sailro** [comment]
@FelixYoung1212 see how to solve this here:
https://github.com/microsoft/vscode-dotnettools/issues/371#issuecomment-1676050992
