### ISSUE TITLE
[BUG] .ts files do not appear in solution explorer with Microsoft.TypeScript.MSBuild

### ISSUE THREAD

**Issue by etkramer** [microsoft/vscode-dotnettools#412]
### Describe the Issue

I'm using Microsoft.TypeScript.MSBuild to compile and use TypeScript in my Blazor project, but am running into the problem where .ts files seem to be filtered out of the solution explorer entirely. Renaming to i.e. `.ts2` causes it to reappear, as does removing the reference to Microsoft.TypeScript.MSBuild, or using Visual Studio (not vscode)'s solution explorer.

### Steps To Reproduce

1. Create a new project of any type, and reference Microsoft.TypeScript.MSBuild (this issue does not occur without it)
2. Create a .ts file with any name and content
3. Observe how it disappears from vscode's solution explorer, but not vs's.

### Expected Behavior

.ts files should appear in the solution explorer, same as any other.

### Environment Information

OS: Windows (22621)
C# Dev Kit: 0.4.5

**Comment by lifengl** [comment]
can you try to add

<ItemGroup Condition="'$(BuildingInsideVisualStudio)'!='true'" >
  <AvailableItemName>TypeScriptCompile</AvailableItemName>
</ItemGroup>

to your project to see whether it resolves your problem.

MsBuild items can be random things, so something need declare certain item type describes files. It can be declared through msbuild itself like this (which can be done in the NuGet package), or by extension code in VS (which will allow it to describe additional properties showing in the property sheet window.)  I guess this package is created to work with VS.

if it works for you, we can contact the owner of the package to include it in the package itself.

**Comment by chaoserene** [comment]
@lifengl I don't think it's related to the compilation of the files from TS to JS, but showing them in the listing in the Solution Explorer. They simply don't show there, whereas they show in the File Explorer. I'm not sure if this is because of the new Dev Kit C# extension.

For instance, if you open the solution with Visual Studio, they properly show the .ts file (and the .js file nested).

I tried your proposed solution to add the config in the project, but it didn't compile (maybe because my dotnet is a bit older). Nonetheless, I've tried the following:

```
  <ItemGroup>
    <TypeScriptCompile Include="wwwroot\**\*.ts" />
  </ItemGroup>
```

But that didn't work either. Any thoughts? Thank you!

**Comment by lifengl** [comment]
we will fix this issue in an update next week. it would not need any change on your side.

just as it was mentioned earlier, the earlier extension missed a piece of metadata shipped with VS. If you need a workaround earlier than the update, the earlier workaround by adding AvailableItemName should work. If it causes compilation errors, it is likely it was added to a wrong location in the .csproj file (this has to be a child of the project root item).

don't add the extra globbing, which may cause problems.

**Comment by lifengl** [comment]
BTW, thanks to report this issue to us. It appears to be a gap nobody realized earlier.

**Comment by chaoserene** [comment]
Thanks for the quick reply. I think that, for me, and for whoever is facing this issue, you can still change the file using the "Explorer" session, so no biggie.

**Comment by lifengl** [comment]
the fix should be in the next pre-release, likely some time next week.

**Comment by lifengl** [comment]
> @lifengl I don't think it's related to the compilation of the files from TS to JS, but showing them in the listing in the Solution Explorer. They simply don't show there, whereas they show in the File Explorer. I'm not sure if this is because of the new Dev Kit C# extension.
> 
> For instance, if you open the solution with Visual Studio, they properly show the .ts file (and the .js file nested).
> 
> I tried your proposed solution to add the config in the project, but it didn't compile (maybe because my dotnet is a bit older). Nonetheless, I've tried the following:
> 
> ```
>   <ItemGroup>
>     <TypeScriptCompile Include="wwwroot\**\*.ts" />
>   </ItemGroup>
> ```
> 
> But that didn't work either. Any thoughts? Thank you!
> 
> OS: MacOS 13.5.1 (22G90) C# Dev Kit: 0.4.10

it was a gap in the earlier version of Dev Kit, and should be fixed now, and you should no longer need the earlier workaround.
