### ISSUE TITLE
[BUG] Unity projects use .NET Standard 2.0 instead of .NET Standard 2.1

### ISSUE THREAD

**Issue by NoTuxNoBux** [microsoft/vscode-dotnettools#416]
### Describe the Issue

[When using Unity 2021 and up](https://docs.unity3d.com/2021.2/Documentation/Manual/dotnetProfileSupport.html), Unity supports (a subset of) .NET Standard 2.1. The projects generated by this extension use .NET Standard 2.0, however.

This can result in issues when the generated projects are extended using user files to or used in combination with other NuGet packages that need at least .NET Standard 2.1.

### Steps To Reproduce

1. Let the plugin generate projects.
2. Open up a project file.
3. See the target framework being `netstandard2.0` instead of `netstandard2.1` .

### Expected Behavior

The generated target framework is .NET Standard 2.1, at least for the Unity versions using that target framework.

**Comment by tmeschter** [comment]
@jbevain This sounds like an issue in the Unity extension rather than the C# Dev Kit extension. Does that seem right to you?

**Comment by NoTuxNoBux** [comment]
@tmeschter Oh, you're right. I wasn't sure if it's the Unity visualstudio package doing the generation or this package doing the handling. I came here because of [the reference to the issue tracker](https://marketplace.visualstudio.com/items?itemName=visualstudiotoolsforunity.vstuc) on the VSCode Unity package, but if it's indeed the unity Visual Studio package generating the projects, it's not a bug here :slightly_smiling_face: .

**Comment by jbevain** [comment]
@NoTuxNoBux no worries you're in the right place.

Yeah today we're generating a `<TargetFramework>netstandard2.0</TargetFramework>` which is not quite technically correct, but works because Unity gives us the full list of assemblies to reference (and doesn't support NuGet being used in the generated `csproj` anyway).

Is this bug more for correctness or are you seeing something that is not working?

**Comment by NoTuxNoBux** [comment]
> Is this bug more for correctness or are you seeing something that is not working?

It's mostly the latter, but it's due to us having a perhaps somewhat out of the ordinary setup. We use a custom C# project to install a few Roslyn analyzers from NuGet (through `dotnet restore`) and then create a `.user` file to extend these automatically generated projects to reference that project so that the language server picks them up when analyzing our Unity code.

This works great, but we have a few analyzers in there that need .NET Standard 2.1, and they are currently failing to load because the generated projects are not compatible with it (only .NET Standard 2.0).

A workaround for us would be to try and backport to .NET Standard 2.0, but not all of the analyzers are under our control. Another workaround might be to use `.csproj.user` files to overrule all the `TargetFramework` directives, but this becomes unwieldy quickly because there are several generated `.csproj` files in a medium-sized project (and they also reference one another, so just doing some won't work from what I understand).

**Comment by sailro** [comment]
@NoTuxNoBux thank you for this report. 

Could you share the exact error message you are seeing with your analyzer? 

It is easy on your side to set the target framework for all projects by using the following `Editor` script in your project:
```csharp
using UnityEditor;

public class TargetFrameworkChanger : AssetPostprocessor
{
    public static string OnGeneratedCSProject(string path, string content)
    {
        return content.Replace("<TargetFramework>netstandard2.0</TargetFramework>", "<TargetFramework>netstandard2.1</TargetFramework>");
    }
}
```

Regenerate project files, and you should be set for `netstandard2.1`

**Comment by NoTuxNoBux** [comment]
@jbevain Sure:

[BugReproVSCode.zip](https://github.com/microsoft/vscode-dotnettools/files/12451429/BugReproVSCode.zip)

All that is required is creating a `.csproj.user` override for any generated C# project, and to reference a project needing .NET Standard 2.1 in there. In our case we have an actual external dependency doing this, but for the purposes of the test project I have just included a dummy `TestCsprojOfExternalProjectNeedingNETStandard21.csproj` that mimicks it.

In the case of my own projects the C# and Unity VSCode extensions actually show the error message in VSCode, but here it seems to fail before it can do that, but you can still see the error manually by running `dotnet restore Assembly-CSharp.csproj`:

```
Determining projects to restore...
/home/werk/Downloads/BugReproVSCode/Assembly-CSharp.csproj : error NU1201: Project TestCsprojOfExternalProjectNeedingNETStandard21 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project TestCsprojOfExternalProjectNeedingNETStandard21 supports: netstandard2.1 (.NETStandard,Version=v2.1)
  Failed to restore /home/werk/Downloads/BugReproVSCode/Assembly-CSharp.csproj (in 86 ms).
```

I will also try out the workaround suggested by @sailro soon.

**Comment by jbevain** [comment]
Got it, thanks. Yeah that's not a “common” scenario where something generated by Unity breaks.

But realistically I think we should switch to `netstandard 2.1` anyway, as it is closer to what Unity does and supports.

**Comment by jbevain** [comment]
The next version 2.0.21 of the `Visual Studio Editor Package` Unity Package will generate a `<TargetFramework>netstandard2.1</TargetFramework>`, we will close when it is available. Thanks!

**Comment by jbevain** [comment]
The `Visual Studio Editor Package` version `2.0.21` is now available and will generate projects targeting `netstandard2.1`. Thanks for reporting this!
