### ISSUE TITLE
Unity DOTS support

### ISSUE THREAD

**Issue by SoprachevAK** [microsoft/vscode-dotnettools#417]
Type: <b>Bug</b>

If i use DOTS in my Unity project, i have error:

```
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 02:54:36] [Program]Language server initialized
[Error - 02:54:43] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 02:54:43] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 02:54:43] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 02:54:43] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 02:54:43] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 02:54:45] Stopping server timed out
[Error - 02:54:45] Stopping server failed
```

Unity 2022.3.7f1
VSCode 1.81.1
Visual Studio Editor package 2.0.20

For classic GameObject setup works correctly

Extension version: 0.9.0
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (4.10GB free)|
|Process Argv|/Users/soprachev/Documents/Projects/project-gb/sharpTest -g /Users/soprachev/Documents/Projects/project-gb/sharpTest/Assets/Test.cs:1:0 --crash-reporter-id 257b9668-3667-4c60-baaf-15c48f602856|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by SoprachevAK** [comment]
I think similar #333 

I found it after I created the issue

**Comment by jbevain** [comment]
Hi @SoprachevAK. Agreed, it loos similar.

Which packages are you using in your project?

**Comment by SoprachevAK** [comment]
I think I can close issue as related to #333
