### ISSUE TITLE
[BUG] New project wizard won't create project

### ISSUE THREAD

**Issue by julioct** [microsoft/vscode-dotnettools#42]
### Describe the Issue

Using the .NET: New Project... dialog prompts me to select a project type, then it asks me for a project location and it gets stuck there. Never creates the project.

### Steps To Reproduce

1. Open command palette
2. Choose NET: New Project...
3. Choose Console App (I think this happens with any template really)
4. A Project Location dialog appears
5. Click Select Folder (which folder doesn't matter)
6. The Project Location dialog appears again
7. Click Select Folder (again)
8. The Project Location dialog appears again
9. Endless cycle

### Expected Behavior

A project should get created in the selected location.

### Environment Information

OS: Windows 11
VS Code Version: 1.78.2
Extension Version: 0.1.83

**Comment by tmeschter** [comment]
@smitpatel Should this be area-project or area-templates?

**Comment by richardstanton** [comment]
As a workaround, you can create an empty folder and select that folder.

**Comment by julioct** [comment]
Yes, if I have a folder already opened in VS Code, it works just fine.

To clarify (and before I forget), here's how to repro:

![Recording 2023-06-12 163913](https://github.com/microsoft/vscode-dotnettools/assets/2374270/464347e3-5ac0-44ba-9221-945b68c1fc31)

I think that should work.

**Comment by Michael-Eng** [comment]
This has been fixed and I verified the fix with the prerelease 0.4.5 C# Dev Kit
