### ISSUE TITLE
Ability to edit the project from the Solution Explorer

### ISSUE THREAD

**Issue by kblok** [microsoft/vscode-dotnettools#420]
Type: <b>Feature Request</b>

I know that you can edit the .csproj file from the file explorer. But it would be great to have the option to Right-click on a project and "Edit project file" as we have in VS For Mac.

Extension version: 0.4.5
VS Code version: Code - Insiders 1.82.0-insider (Universal) (501baeb5e07b5a404f862d922bacb93771d91331, 2023-08-18T05:34:38.929Z)
OS version: Darwin arm64 22.5.0
Modes:

**Comment by lifengl** [comment]
you can click the project and open the project file directly and edit it, so there is no need for an additional context menu. Can you try it in C# Dev Kit?

**Comment by kblok** [comment]
oh I missed that @lifengl. Thank you!
