### ISSUE TITLE
"Move type to new file" won't honor the current directory

### ISSUE THREAD

**Issue by kblok** [microsoft/vscode-dotnettools#423]
Type: <b>Feature Request</b>

"Move type to new file" will create a new file at the project's root level instead of the directory where that action is being made.
For instance, given this structure:

-PuppeteerSharp
  - Input
    - Mouse.cs

I'm getting a new file in "PuppeteerSharp" instead of "PuppeteerSharp/Input". This is the behavior on VS For mac.

<img width="398" alt="Screenshot 2023-08-22 at 17 43 44" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/7cf7e611-43ea-41e5-9bc3-e46c22714acb">

<img width="200" alt="Screenshot 2023-08-22 at 17 44 03" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/5eac7fb6-82c6-408b-997e-c9197ea47c12">

Extension version: 0.4.5
VS Code version: Code - Insiders 1.82.0-insider (Universal) (f125afbc800ec611f5a9ab1333c769832ce424b3, 2023-08-21T05:34:49.942Z)
OS version: Darwin arm64 22.5.0
Modes:

**Comment by arkalyanms** [comment]
Another one related to https://github.com/dotnet/vscode-csharp/issues/5735. Another fyi @akhera99
