### ISSUE TITLE
Reduce the number of steps to create a class on a new file

### ISSUE THREAD

**Issue by kblok** [microsoft/vscode-dotnettools#424]
Type: <b>Feature Request</b>

If I write this line:

```
public MouseTest test1;
```

I can create the `MouseTest` class in a new file in one step in VS for Mac.

<img width="816" alt="Screenshot 2023-08-22 at 17 42 04" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/690abd1a-51a0-4f3e-800e-5074dcc72e4d">

This same task requires two steps in VS Code:
 * Generate class
 * Move type to new file 

<img width="451" alt="Screenshot 2023-08-22 at 17 43 33" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/7d69b93b-fdf6-494d-8545-84fcc8c666c7">

<img width="398" alt="Screenshot 2023-08-22 at 17 43 44" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/6f65d7a1-992b-4b17-9132-78b7524d28cb">

Extension version: 0.4.5
VS Code version: Code - Insiders 1.82.0-insider (Universal) (f125afbc800ec611f5a9ab1333c769832ce424b3, 2023-08-21T05:34:49.942Z)
OS version: Darwin arm64 22.5.0
Modes:

**Comment by arkalyanms** [comment]
Should get covered via https://github.com/dotnet/vscode-csharp/issues/5735. @akhera99 fyi on a code action to add to the test suite.
