### ISSUE TITLE
New file should infer the namespace from the location

### ISSUE THREAD

**Issue by kblok** [microsoft/vscode-dotnettools#425]
Type: <b>Feature Request</b>

If I create a file inside `PuppeteerSharp/Input`, the namespace of the class/enum/whatever being generated should be `PuppeteerSharp.Input`.

<img width="357" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/d18b8c77-415c-42cf-a278-272551f17d8b">

<img width="532" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/a16d26d0-ae59-4f9e-a8c6-cd6b2642843a">

<img width="567" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/81942bbe-bc6e-4c48-89c8-b0f7b3e530e9">

<img width="448" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/2198466/78f7c639-d39d-4609-aeda-9f131e40c64e">

Extension version: 0.4.5
VS Code version: Code - Insiders 1.82.0-insider (Universal) (eccdef295e18aed53b9c9bad4f14517d086b9fd8, 2023-08-22T18:47:10.163Z)
OS version: Darwin arm64 22.5.0
Modes:

**Comment by xjose97x** [comment]
I agree. This is the default behavior in Visual Studio (both windows and Mac) and used to be the behavior with Omnisharp.
