### ISSUE TITLE
Сломанные подсказки кода

### ISSUE THREAD

**Issue by FALK7OLVE** [microsoft/vscode-dotnettools#426]
Type: <b>Bug</b>

Расширение Unity - ломает подсказки к коду при его наборе(например: при вводе gameO.... - не дает подсказки на gameObject)

Extension version: 0.9.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.98GB (21.53GB free)|
|Process Argv|D:\\UnityProject\\TestProject\\rts_proj|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sailro** [comment]
Please have a look here:
https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278
