### ISSUE TITLE
Can't find .NET MAUI SDK for Blazor Hybrid app

### ISSUE THREAD

**Issue by justinyoo** [microsoft/vscode-dotnettools#427]
Type: <b>Bug</b>

Hi, Team!

I followed instructions from this blog post: https://devblogs.microsoft.com/visualstudio/announcing-the-dotnet-maui-extension-for-visual-studio-code/

and this MS Learn page: https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code

It works fine when I open a .NET MAUI project. However, if I open a Blazor Hybrid project, it keeps saying .NET MAUI SDK not found. Here's the error message I got from the VS Code output window:

`.NET MAUI SDK verification failed with an unexpected error: Could not find an active target framework for '<MY_BLAZOR_HYBRID_APP_PROJECT>'. Please make sure you've selected a valid debug target and its platform is present in the TargetFrameworks or TargetFramework properties.`

I wonder what I am missing. The .NET MAUI extension version is v0.2.13.

Extension version: 0.2.13
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|24.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by justinyoo** [comment]
It turned out on Mac, I have to enable the moniker of `*-ios` and/or `*-maccatalyst`, regardless XCode is installed or not. Is it by design?

**Comment by justinyoo** [comment]
Another finding. I installed XCode.

If I create a .NET MAUI project using the `dotnet new maui` command, it's OK in Visual Studio Code. However, if I create a .NET MAUI Blazor project using the `dotnet new maui-blazor` command, it shows .NET MAUI SDK not found error. But it's like a trivial error - not consistently occurring.

**Comment by emaf** [comment]
@justinyoo I'm trying to understand the repro steps here:
- New MAUI Blazor project sometimes shows that error
- For your existent project, you had to add the iOS and MacCatalyst and install Xcode to make things work? What were you originally targeting?

Could you try switching to the pre-release version of the .NET MAUI extension? You can do that from the extensions tab after selecting the .NET MAUI extension.

**Comment by justinyoo** [comment]
@emaf Thanks for the response! Here's my screenshot I just took:

<img width="1470" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1538528/d20ce286-2569-47ea-9a7b-1a65fd059057">

I'm on MacBook Air M2. If I comment out the `-ios` and `-maccatalyst` moniker, it throws the error like the screenshot. It's the extension version of 0.2.13. If I uncomment it and build, then I should have XCode installed to get the build successful, which makes sense to me.

Now, I switched the extension to pre-release version of it - version 0.3.12, the error has gone. In other words, I don't need to target `-ios`/`-maccatalyst` on my MacBook to get the entire build successful.

But as I mentioned, the error is occasionally happening on Blazor Hybrid - MAUI project. I'll take more look.

**Comment by emaf** [comment]
@justinyoo thanks for confirming on the pre-release version you don't need to target ios and maccatalyst for this to work. 

When you ocassionally face the error now, does it always mention it could not find an active framework?

**Comment by janwiesemann** [comment]
I found a workaround for this issue. It's kind of known and mentioned at https://github.com/xamarin/xamarin-macios/issues/11172. A solution was mentioned by @rolfbjarne: https://github.com/xamarin/xamarin-macios/issues/11172#issuecomment-1422092279

1. add the following line to your `.zshrc` or `.bashrc` or `.whateverrc`:  
   ```
   export MD_APPLE_SDK_ROOT=/Applications/Xcode.app/ #sets the Xcode SDK-Path for .NET-MAUI
   ```
2. restart vs-code or ideally your whole system.

**Comment by mauroa** [comment]
Hi @justinyoo.
We are trying to re-activate or cleanup old issues related to the VS Code MAUI extension that were left unattended or into "Need More Info" state and didn't get a response in a while.
I would like to know if you continued working with MAUI projects in VS Code and if you still have any issue related to this ticket, after applying the workaround and comments mentioned above.
We will proceed to close this ticket in case we don't get a new response in a few days.
Thanks in advanced.

**Comment by justinyoo** [comment]
@mauroa Thanks for reaching out. You can close this now. Once I face the same issue, I'll create a new issue again.

**Comment by mauroa** [comment]
Thanks @justinyoo for the confirmation. Let us know if you experience any new or related issue.
