### ISSUE TITLE
Debugging with .NET 5 / Core option not working

### ISSUE THREAD

**Issue by leslierichardson95** [microsoft/vscode-dotnettools#428]
Type: <b>Bug</b>

I'm using Dev Kit to write a Blazor Webassembly project.  When I hit F5 to debug, Dev Kit recommends to use the .NET 5+ and .NET Core debugger.  However, nothing appears to happen / my application doesn't boot up when I select that option, and I don't receive any notification about why I can't start my application with this debugger.  Despite that, my app does successfully run when I select the C# debugger option, which wasn't recommended to me originally.

Extension version: 0.3.154-g0e888fa2a3
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (1.10GB free)|
|Process Argv|--crash-reporter-id 131dde13-5e39-4ec4-b299-a3388c8f412a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
9b8hh234:30694863
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by WardenGnaw** [comment]
@leslierichardson95 Did you have a C# file open when you initially hit F5?

**Comment by leslierichardson95** [comment]
@WardenGnaw yeah I did have a C# file open (sorry for the late reply btw!)

**Comment by WardenGnaw** [comment]
The .NET 5 / Core option has been removed if you use the latest C# Extension and VS Code

**Comment by Jimmy3139** [comment]
[thank](https://github.com/microsoft/vscode-dotnettools/issues/428#issuecomment-1775920102) @WardenGnaw 
I encountered the same issue. When I deleted the Dev Kit, the .NET 5/Core option returned to normal.
