### ISSUE TITLE
[BUG] Wrong DOTNET_ROOT inferring on OSTree-style .NET installations

### ISSUE THREAD

**Issue by GGG-KILLER** [microsoft/vscode-dotnettools#447]
### Describe the Issue

The `DOTNET_ROOT` env var is set incorrectly on Linux when .NET is installed in OSTree style (i.e. `dotnet` binary is inside a `bin` directory and not in the root of the .NET installation).

I have implemented [a fix](https://github.com/GGG-KILLER/nixos-configs/blob/1fb658e12e16ea2479722231efb9e4b6a66069bc/common/overlays/local/ms-dotnettools.csdevkit/default.nix#L68-L72) in the build script for my installation however this would be best solved upstream.

### Steps To Reproduce

1. Install a Linux distro where .NET is installed in OSTree style (e.g. NixOS)
2. Install the extension (and patch the binaries if you're on NixOS)
3. Configure the extension to use the installed .NET
4. Open a .NET project
5. Have the extension fail with ".NET is not installed"

### Expected Behavior

Extension detects that the `dotnet` binary is in the `bin` dir and goes up another directory to get `DOTNET_ROOT`.

### Environment Information

- OS: NixOS 23.11.20230825.5690c42
- VSCode Version: 1.81.1
- Extension Version: 0.4.6

**Comment by GGG-KILLER** [comment]
Seems like this has been solved by replacing `readlink` with `realpath` as was done in https://github.com/dotnet/vscode-csharp/pull/6230 as I've found out in https://github.com/dotnet/vscode-csharp/issues/6239.

**Comment by nagilson** [comment]
Thanks for reporting this is fixed in the other issue, closing now.
