### ISSUE TITLE
[BUG] C# Dev Kit clutters home folder on Linux instead of using proper XDG folders

### ISSUE THREAD

**Issue by NoTuxNoBux** [microsoft/vscode-dotnettools#455]
### Describe the Issue

On Linux, the C# Dev Kit seems to create folders inside the user's home folder:

* `csdevkit`, with crash dumps such as `dumps/dotnet.436722.dmp`
* `Library`, with `Application Support/Microsoft Visual Studio/prpbg.dat`

![afbeelding](https://github.com/microsoft/vscode-dotnettools/assets/73220431/cefb55b4-7863-4d1f-81aa-03e54f083458)

### Steps To Reproduce

1. Run on Linux.
2. Enable the plug-in.
3. Trigger a crash in the language server.

### Expected Behavior

Using the home folder (root) to store (any type of) application data is considered bad practice on Linux desktops. [XDG user directories should preferably be used for this](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/), which usually evaluate to (hidden) folders such as `~/.cache` or `~/.local/share`.

### Environment Information

- OS: Linux
- VSCode version: 1.81.0
- Dev Kit VSCode extension version: 0.4.8

**Comment by lifengl** [comment]
yes, i hit this problem as well, folders like Library may conflict with folders created by user for their own files, and especially bad.

**Comment by jvcdk** [comment]
Me too. Please don't clutter my homedir.

**Comment by jonathanjyi** [comment]
The prpbg.dat will no longer be created in the next prerelease version of C# Dev Kit. It was fixed here: https://github.com/microsoft/vscode-dotnettools/issues/118

Will have to reassign the *.dmp file creation question to Michael.

**Comment by MichaelMaio** [comment]
In the next pre-release, dumps on Linux will be moved to a hidden folder already in use by other Microsoft products.

**Comment by jonathanjyi** [comment]
Closing on behalf of @MichaelMaio's request.

**Comment by rafael-neri** [comment]
Switching to pre-release version works for me.
