### ISSUE TITLE
[BUG] Waning "not CLS-compliant" and multi project support

### ISSUE THREAD

**Issue by stnaw** [microsoft/vscode-dotnettools#464]
### Describe the Issue

1. When I open the second project, dev-kit will prompt that dotnet is not found.

2. There are multiple CS3001, CS3002, and CS3003 warnings in the project. I don't know what happened or how to disable these warnings. It works fine in Rider.

### Environment Information

- arm mac 13.5
- vscode 1.81.1
- extension unity 0.9.0
- extension c# devkit 0.4.10

**Comment by tmeschter** [comment]
@stnaw Can you tell us more about the project? Is is a web application, or a Unity project, or something else?

If it is a Unity project, is it using the newer SDK-style project format?

Also, can you provide the text of the "Projects" pane of the Output window?

**Comment by stnaw** [comment]
@tmeschter 

It is Unity project.

Version: Unity 2022.3.1f1 LTS,
Api Level: .Net Standard 2.1
IL2CPP Code Generation: Faster (smaller) builds

**For issue 1:**

**Some warnings:**
Argument type "vector2' is not CLS-compliant Roslyn(CS3001)
Return type of 'FooClass. FooMethod(string, string, bool, double, Vector2, Vector2, double)’ is not CLS-compliant Roslyn (CS3002)

**Projects Pane:**
 [info] Project system initialization finished. 5 project(s) are loaded, and 0 failed to load.

**For issue 2:**

**C# Dev Kit Pane:**
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/Users/xxxx/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet"
.NET server started and IPC established in 993ms
Completed Spawn .NET server (1000ms)
Completed Clear environment (1314ms)
Completed Open a solution with environment service (1394ms)
Starting Restore solution...
Completed Open a solution (1405ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /Users/xx/Projects/xxxxProject/xxxxProject.sln --interactive...
[object Object]
[object Object]

**C#  Pane:**
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
Error running dotnet --info: Error: Command failed: dotnet --info
/bin/sh: dotnet: command not found


/bin/sh: dotnet: command not found

Dotnet path: /Users/xxxx/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 9:36:11 AM] [Program]Language server initialized

**Source: C# Dev Kit (Extension) prompt**
No installed .NET SDK was found on the computer. If it is installed, make sure it can be found through the PATH environment variable. C# Dev Kit does not work without a supported version of SDK. After installing the SDK, you need restart the VS Code session, or the computer.

**Comment by jbevain** [comment]
@stnaw hi! Thanks for reaching out.

It's not something that we've seen previously.

Do you have something in your code (or in a third party library/package) that declares that your code is CLS compliant? You can search for a `[CLSCompliant(true)]` attribute. If that's the case you should be able to safely remove it as Unity's API is not CLS compliant.

**Comment by stnaw** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/9924068/038d26a6-35d4-47f3-988d-08c6c4d163b3)
There is no such attribute in my project, this is very strange.

**Comment by jbevain** [comment]
@stnaw could you make sure you're all up to date with the `C#` and `C# Dev Kit` extensions?

Can you reproduce the CLS warnings in a new Unity project?

**Comment by jbevain** [comment]
@stnaw I've been unable to reproduce this. Feel free to re-open if you have a way to reproduce the issue with the latest extensions. Thank you!
