### ISSUE TITLE
Intellisense or pretty much any error detection is not working in new Unity extension 

### ISSUE THREAD

**Issue by Tetraizor** [microsoft/vscode-dotnettools#466]
Type: <b>Bug</b>

I'm using Unity 2022.3.7f with Visual Studio Editor package version 2.0.20, I set my code editor to VSCode from preferences in Unity, but when I try to type anything, nothing comes up, as well as no error underlines or anything, as if it was just a text editor (even the standard C# code)  

Extension version: 0.9.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500X 6-Core Processor              (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.98GB free)|
|Process Argv|E:\\Personal\\Unity\\com.Tetraizor.Console\\Assets\\Scripts\\TestScript.cs --crash-reporter-id a4fc1d57-247c-4125-b60a-f785359c5080|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by jbevain** [comment]
Please see the following comment as a checklist for this kind of issues: https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278

**Comment by Tetraizor** [comment]
Ok, not sure what exactly fixed the issue but I restarted both VSCode and Unity, changed external editor to VS then back to VS Code, regenerated the project files, restarted the language server and seems like it's working without a problem. Thanks.
