### ISSUE TITLE
Android Licensing dialog box - slashes are going in the wrong direction

### ISSUE THREAD

**Issue by mprogers** [microsoft/vscode-dotnettools#468]
Type: <b>Bug</b>

When setting up VSC + .NET MAUI extension on a mac, I get this message:

Insufficient privileges: Please try accepting licenses again after running VS Code as administrator. Alternatively, you can try opening a Terminal as administrator and running: /Users/rogersm/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/7.0\bin\sdkmanager --licenses

Those last two slashes need to be forward slashes

Extension version: 0.2.13
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 5, 5|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id 3abec7f2-4e1c-42ac-bf3f-fb08241e5d41|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30823812
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

> VS bug [#1881384](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1881384)

**Comment by stefan89** [comment]
I have the same issue

**Comment by Ghostbird** [comment]
I have this issue too, which wouldn't matter that much, but it seems to point at a bigger underlying issue.

> Insufficient privileges: Please try accepting licenses again after running VS Code as administrator. Alternatively, you can try opening a Terminal as administrator and running: /usr/lib/android-sdk/cmdline-tools/latest\bin\sdkmanager --licenses

Whenevery I run `sudo /usr/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses` it'll tell me:

> All SDK package licenses accepted.

But I can still not build anything as the extension will keep complaining about unaccepted licenses.
