### ISSUE TITLE
Not sure where to start - basic project doesn't work

### ISSUE THREAD

**Issue by wallym** [microsoft/vscode-dotnettools#469]
### Describe the Issue

I have created a new maui project.  I have done a "dotnet new maui" project.  I have loaded it into vs code running on windows 11.  I have installed the maui vs code extension along with the c# extension.  I have run  dotnet build -t:InstallAndroidDependencies -f:net7.0-android -p:AndroidSdkDirectory="<<my sdk location>>" -p:AcceptAndroidSDKLicenses=True

My launch.json file looks like this:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        },
        {
            "type": "android",
            "request": "launch",
            "name": "Android launch",
            "appSrcRoot": "${workspaceRoot}/app/src/main",
            "apkFile": "${workspaceRoot}/app/build/outputs/apk/debug/app-debug.apk",
            "adbPort": 5037
        },
        {
            "type": "android",
            "request": "attach",
            "name": "Android attach",
            "appSrcRoot": "${workspaceRoot}/app/src/main",
            "adbPort": 5037,
            "processId": "${command:PickAndroidProcess}"
        }
    ]
}

I can get the debugger to launch the app in windows.  But, I'd like to see things come up in an Android emulator.  This, it does not do.  ![mauisettings](https://github.com/microsoft/vscode-dotnettools/assets/366611/190d12b0-76b3-40a9-861e-f4fd29d0601e)
I assume that this is a configuration issue, but I have no idea how to configure things to get an android emulator to come up.  I've played with the maui extension settings, but don't know if I am doing the right things.  Any ideas?  Any links to point me to?

The only feedback I am getting in VS Code is:
Source path error: ENOENT: no such file or directory, scandir 'C:\<<app dir>>/app/src/main\'
Check the "appSrcRoot" and "apkFile" entries in launch.json

### Expected Behavior

Would expect some info regarding what device/emulator to start, or to start a predefined device/emulator.  I'm just expecting an emulator session to start.  Then I would expect the application to start in the emulator.

### Environment Information

Windows 11.
Upto date vs code.
.net maui extension prerelease

**Comment by wallym** [comment]
I just noticed this, not sure why i missed it before.
I get the message below.  How do I set whether the app is self contained for not?

One of '--self-contained' or '--no-self-contained' options are required

**Comment by wallym** [comment]
I decided to load the project back up in VS 2022.  I found that the project would not start in the debugger there either.  I checked the configuration and the project was not set to deploy.  I set the project to deploy in the configuration and it deployed to the emulator.  I went back to VSCode, loaded things up, and then started the project again.  This time, something seemed to happen, but I still didn't have full success.  I got a message in VS Code that the Android SDK was analyzing.  Source: .NET Maui Extension.  Nothing seems to be happening now.  I've left it running for 10-15 minutes.

**Comment by mauroa** [comment]
Hi @wallym.
We are going through old and unattended tickets to see if they're still reproducible, so we can define the next actions.
I would like to confirm with you if you can still reproduce the issues you had, after updating to latest .NET MAUI pre-release, since we've made a lot of improvements around the debug experience, the Android configuration and also bug fixing in general.
I wait for your confirmation.
Thanks for your help and patience.

**Comment by mauroa** [comment]
We are unable to continue the investigation without the required information.
Feel free to request a reopening if you still experience any issue after updating to latest C#, C# DevKit and .NET MAUI versions and also please provide the information requested above.
Thanks for your help and feedback.
