### ISSUE TITLE
[SUGGESTION] Add Project References from vscode interface

### ISSUE THREAD

**Issue by Saverio-Angelicola** [microsoft/vscode-dotnettools#47]
### Describe the feature you'd like

It would be nice if it was possible to add project references from the interface like in visual studio and jetbrains rider when you right click on a project in the solution.

**Comment by arkalyanms** [comment]
I believe we have an internal tracking item for this that could be duped to this now.

**Comment by smitpatel** [comment]
This has been fixed in version 0.4.2
