### ISSUE TITLE
[BUG] Tests not detected in project on Linux

### ISSUE THREAD

**Issue by zorbathut** [microsoft/vscode-dotnettools#472]
### Describe the Issue

I can't get tests to show up in test explorer in a project of mine. `dotnet test` finds them without trouble, as does `dotnet test -t`. Adding a new NUnit test project to the solution *sometimes* works; it's intermittent and it's unclear why it's intermittent.

I'm running on Manjaro Linux; it does appear to work on Windows, but there's no diagnostic to explain what's going wrong.

### Steps To Reproduce

1. Check out https://github.com/zorbathut/dec
2. Open in VS Code
3. Observe that tests don't show up in the explorer, even after building
4. Open in Windows VS Studio
5. Observe that tests do show up in the explorer

### Expected Behavior

Tests should show up in the Test Explorer window.

### Environment Information

Linux (Manjaro 23.0)
VS Code 1.18.1
Tested with both C# Dev Kit 0.4.10 and 0.5.2

**Comment by lifengl** [comment]
there is one code path doesn't handle Linux file path correctly, which may affect this scenario. We made a fix which would be in the next pre-release. Can you help to give a try after the next pre-release update to see whether it is still a problem for you.

**Comment by zorbathut** [comment]
Happy to do so if you're willing to ping me when that update happens :)

**Comment by lifengl** [comment]
@zorbathut : that fix should be in the pre-release uploaded today. please let us know if it still doesn't resolve your problem.

**Comment by zorbathut** [comment]
@lifengl: No luck, I'm afraid - they still don't show up in the test panel. Is there any diagnostic info you'd like?

(Though I will note again that you can reproduce this by just grabbing the repo shown above.)

**Comment by zorbathut** [comment]
Still not working with 0.5.150. Still happy to do tests, and the repo listed above still exhibits the problem.

**Comment by AbhitejJohn** [comment]
Seems like this is still reproing on v1.0.14 and the problem still seems to be the paths. Output->Tests on the repo from above shows this:
```
Scheduling discovery: C:\git\dec\test\integration\bin\Debug 2.1\netcoreapp2.1\dec-test-integration.dll [0]
Scheduling discovery: C:\git\dec\test\unit\bin\Debug 2.1\netcoreapp2.1\dec-test-unit.dll [0]
Scheduling discovery: C:\git\dec\test\integration_unified\bin\Debug 2.1\netcoreapp2.1\dec-test-integration-unified.dll [0]
Scheduling discovery: C:\git\dec\util\decutillib\bin\Debug 2.1\netcoreapp2.1\decutillib.dll [0]
Scheduling discovery: C:\git\dec\extra\recorder_enumerator\test\bin\Debug 2.1\netcoreapp2.1\recorder_enumerator-test.dll [0]
```

However the build is dropping files under ...\bin\Debug 7.0\netcoreapp7.0. I dont know what is special in the solution that could cause this to only repro here though - Is it just multi-targeted projects that are a problem? 

Thoughts on this @lifengl ?
/cc: @peterwald

**Comment by zorbathut** [comment]
It is entirely plausible that I did something wrong, or at least nonstandard, in setting up the multiple build targeting; I kinda did something adhoc that worked for me.

**Comment by peterwald** [comment]
I believe the non-standard project files are confusing the build system. I was able to get the tests to be discovered on Linux by:

 1. Remove the `<Configurations/>` tag from each project 
 1. Remove the conditional `<PropertyGroup>`'s that set the `<TargetFramework>`
 1. Change your default `<TargetFramework>` property to something like this (Note the change to plural)
    ```xml
    <TargetFrameworks>netcoreapp2.1;netcoreapp3.1;net7</TargetFrameworks>
    ```
 1. Update the solution file to just the `Debug|Release` configurations.

**Comment by tmeschter** [comment]
@zorbathut: @peterwald is correct. `$(Configuration)` and `$(TargetFramework)` are generally treated as orthogonal concepts (that is, you might want a Debug or Release build of any given framework) and tying them toghet in this way risks confusing the tooling. It doesn't surprise me that this works in VS but not C# Dev Kit, as C# Dev Kit does not fully understand configurations at this point.

**Comment by peterwald** [comment]
Closing as a configuration issue. @zorbathut, reach out if you want help updating your project files.
