### ISSUE TITLE
New class file not adding the right namespace

### ISSUE THREAD

**Issue by TanvirArjel** [microsoft/vscode-dotnettools#473]
### Describe the Issue

When we add a new class file inside a folder, class template should add the namespace considering the folder structure. But it's only adding root project name as namespace as follows:

<img width="852" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/14342773/b5e9a82e-61d0-4c28-8378-89a28a9a54ce">

Actually namespace should have been `namespace ConsoleApp1.TestFolder;`

### Steps To Reproduce

Create a new class file inside a folder in the project.

### Environment Information

OS: Mac OS
VS Code Version: 1.81.1
C# Dev Kit Version: 0.5.2

**Comment by kvenkatrajan** [comment]
C# dev kit uses dotnet new class to generate the class template and this currently does not support folder in namespace generation. We have put in a request at : 
https://github.com/dotnet/templating/issues/6010#issuecomment-1591442631
