### ISSUE TITLE
[SUGGESTION] Include custom `dotnet new` templates in the Solution Explorer

### ISSUE THREAD

**Issue by tillig** [microsoft/vscode-dotnettools#48]
### Describe the feature you'd like

When you click the `+` to add a new project to your solution, the list of available templates appears to be only the default ones that come out of the box with C#. If you have any custom templates that show up in `dotnet new --list`, those custom templates do _not_ show up in the list of available project templates you can use.

Since we have some fairly common baseline templates for things (e.g,, "new standard microservice"), the ability to use any template available in `dotnet new --list` would be helpful.

### Alternatives considered

The only alternative right now is to not use the feature and use the `dotnet new` and `dotnet sln add` commands to add a new project to the solution.

### Environment Information

- OS: Mac OS X 13.4
- VS Code 1.78.2
- C# Dev Kit: 0.1.83
- Working with a solution that has all .NET 6 projects. The `global.json` also indicates .NET 6:

```json
{
  "sdk": {
    "rollForward": "latestFeature",
    "version": "6.0.406"
  }
}
```

I did notice that our `dotnet new` templates are, of course, installed under .NET 6 (as indicated by the `global.json`) but don't show up if I'm in a different folder tree using .NET 7. It might indicate that the list of templates is not obeying the `global.json` in the solution structure.

**Comment by smitpatel** [comment]
This should be available for add new project command in version 1.8.14
