### ISSUE TITLE
c# devkit:Microsoft.CodeAnalysis.LanguageServer consume a lot of memory

### ISSUE THREAD

**Issue by ahmeteid7** [microsoft/vscode-dotnettools#480]
Type: <b>Bug</b>

i don't know why it consume a lot of memory , that cause the pc to be high load noise fan and pc so slow every thing open late. i  go to task manger and found that: Microsoft.CodeAnalysis.LanguageServer reach to high ram

Extension version: 0.4.10
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 5.15.0-82-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 B95 Processor (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|5.29GB (1.98GB free)|
|Process Argv|--unity-launch /home/eid/Desktop/nineconsole --crash-reporter-id 682db7ef-1333-4804-85ef-283f5b925f8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin-os-lite|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|zorin-os-lite|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by arkalyanms** [comment]
Tracked at https://github.com/microsoft/vscode-dotnettools/issues/389
