### ISSUE TITLE
The Extension doesn't find the SDK but it's able to build

### ISSUE THREAD

**Issue by kblok** [microsoft/vscode-dotnettools#485]
Type: <b>Bug</b>

The extension is complaining that it not being able to find the SDK.

![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/28ccefe4-370a-4d19-82e7-511885611721)

It also says that it's not being able to restore the solution.

![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/39ae4eb7-070b-48de-bc53-0f267322c77f)

But the solution is there, but it doesn't find the SDKs

![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/71ed0b3b-43f7-445c-9366-fe51947fbbaa)

I'm able to build it.

![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/dec1eba6-d6ac-4296-b10d-623251016b72)
![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/46cf56ad-6037-45fd-bb67-b249bd4009b5)

But I don't see the tests.

![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/c4b66091-ec6e-4dc7-aee1-93ccd976bb7d)

I see the SDKs in the terminal

![image](https://github.com/microsoft/vscode-dotnettools/assets/2198466/2d92f05a-7c8b-4531-b032-7ea816ba8959)

This is a brand new Ubuntu machine. The setup is being made by an Ubuntu rookie, a.k.a Me.
Extension version: 0.4.10
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 6.2.0-31-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3467)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.31GB (11.12GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5e8dab64-b4d8-495a-90c8-6739c6af852e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30823813
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by lifengl** [comment]
if this is a newly installed machine, one possibility is that $PATH environment might be updated sometime after the vscode session started. The SDK is located through PATH environment, and if dotnet command cannot be resolved there, the extension would not work.  You might close VS code process (not only a window/workspace, restart the process), environment variables are captured once the process starts, and changes from later installation & machine updates would not impact the process.  -- except 'build', somehow, is implemented to run through a terminal window, which is basically spinning a new shell when the terminal window opens.  It was likely initialized later, and picked up updated environment settings, which might be a reason why you see this odd state.

**Comment by kblok** [comment]
Thank you @lifengl. I don't know if you can redirect this to the right team. It seems that the manual install:

```
sudo apt update
sudo apt upgrade dotnet-sdk-7.0
```

Updated the path. In contrast, installing .NET from Ubuntu's package manager didn't.
