### ISSUE TITLE
[SUGGESTION] How to build on release mode and archive for Android and iOS?

### ISSUE THREAD

**Issue by vhugogarcia** [microsoft/vscode-dotnettools#495]
### Describe the feature you'd like

Hello friends,

First, I would like to thank you for the efforts on this new VS Code .NET MAUI extension. I do love it. However, I could not find clear documentation or a guide on how to set the app on release mode so I can re-build the project and generate the archives for iOS and Android.

While reviewing the target device popup list I noticed there are 2 options that may be pointing to set release mode, but I would like your confirmation, please:

- Android (Build Only) - net7.0-android
- iOS (Build Only) - net7.0-ios

If those are the release mode target, I would like then to know how can I archive a project to a specific platform after they were built on release mode.

<img width="597" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1047398/b275768f-4da4-4281-bfad-b271f17f03dc">

Thanks in advance!

### Alternatives considered

None

### Environment Information

- OS: macOS Ventura 13.5.1
- .NET MAUI extension: v0.3.12
- Visual Studio Code: Version: 1.81.1

**Comment by emaf** [comment]
@vhugogarcia Thanks for your feedback!

Switching configurations is not yet supported, and the the Build Only entries are mostly intended to let you build for a specific platform, even if you don't have a device connected.

Regarding archiving, that's also not supported on VS Code, but you can do that from dotnet CLI. To create an archive you just need to build your project with `ArchiveOnBuild=true` and optionally pass the root Archives directory using `ArchiveBasePath`. If what you need is to produce and IPA file, you can just set `BuildIpa=true` instead.

cc @maddymontaquila

**Comment by vhugogarcia** [comment]
Thanks @emaf , I will give it a try and let you know the results. 

Looking forward for an UI easy way in future versions to set the target mode and archive it 🙂👍🏻

I don't have experience at all with VS Code extensions, but if there is anything I can help with, please let me know 🙂👍🏻

**Comment by harry-cpp** [comment]
Unless I'm mistaken, you can write your own launch.json config file and specify the configuration there:
```json
{
    "name": "Maui App (Debug)",
    "type": "maui",
    "request": "launch",
    "configuration": "Debug",
    "preLaunchTask": "maui: Build"
},
{
    "name": "Maui App (Release)",
    "type": "maui",
    "request": "launch",
    "configuration": "Release",
    "preLaunchTask": "maui: Build"
}
```

**Comment by vhugogarcia** [comment]
Thanks @harry-cpp for sharing the details about the launch settings json file. It worked very well for building the projects on release and debug mode. 

We just need the archive the build option. As right now, I am using the CLI as recommended. 

Thank you all for the support
