### ISSUE TITLE
Restart debugging doesn't rebuild the project

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode-dotnettools#496]
### Describe the Issue

When using in-memory debugger configurations (example: in a repo without a launch.json, hit F5 and select the 'C#' option), using the 'Restart' command from the debug toolbar doesn't rebuild the project. So changes aren't applied.

### Steps To Reproduce

1. Create a new .NET 7 console project (any version and any project type will do)
2. Do NOT create a launch.json
3. Set a breakpoint on the closing brace of main
4. Start debugging
5. Change the 'Hello World' text to something different
6. Hit Restart

### Expected Behavior

Project should rebuild so the new text is displayed

**Comment by gregg-miskelly** [comment]
CC @WardenGnaw

**Comment by softgandhi** [comment]
Hi,
I am also facing this situation. Restart debugging doesn't recompile.
After deprecation of VS for Mac, we moved to VS Code, but facing many basic issues.
Hope it will be stable soon.

**Comment by roblourens** [comment]
Does this just mean the preLaunch task isn't run? It would be the same for normal configs in launch.json right?

**Comment by WardenGnaw** [comment]
@roblourens We didnt have a `preLaunchTask` in this scenario. We have a solution now with the help you provided that will be added in a future release of C# Dev Kit.

**Comment by seahsky** [comment]
Faced this issue as well. Any workaround before the fix is released?

**Comment by gregg-miskelly** [comment]
@seahsky A fix for this issue has been implemented internally and will be released with the next version of C# Dev Kit, so I would suggest just doing the simple thing and stop debugging and then relaunching until it comes out.

**Comment by duc-cm** [comment]
Same problem in Java
https://github.com/microsoft/vscode-java-debug/issues/1399

**Comment by WardenGnaw** [comment]
This is fixed in v1.2.2

**Comment by gaby64** [comment]
Still not working for me in C/C++

**Comment by gaby64** [comment]
Same problem in C/C++
