### ISSUE TITLE
Add an easy way to launch & debug UI apps

### ISSUE THREAD

**Issue by Licantrop0** [microsoft/vscode-dotnettools#50]
Type: <b>Feature Request</b>

there is a configuration for launching and debugging a .NET console app, but not a UI APP (e.g. WPF). Please make it easier like the full Visual Studio, just pressing play on the command bar.

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Sandboxed: Yes

**Comment by tmeschter** [comment]
@Licantrop0 Console, WinForms, and WPF apps should generally launch the same way as in each case it is a matter of running the .exe produced by the build. That is, I would currently expect you to be able to launch a WPF app the same way you launch a console app. 

Regarding this:

> there is a configuration for launching and debugging a .NET console app,

Can you provide more details on what you are referring to?

**Comment by Licantrop0** [comment]
> there is a configuration for launching and debugging a .NET console app

I mean that when you click "add configuration", the menu explicitly shows ".NET core console app":

<img width="338" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/2388430/9e112268-c426-4628-be2e-a342c9391efe">

so it might be confusing for someone that doesn't know that "Console app" indication is not relevant, it would be for any .NET app.

Also, I was wondering if this extension would make automatic edits to this configuration file to launch & debug all the different projects inside the solution.

**Comment by WardenGnaw** [comment]
The `Add Configuration...` is part of the C# Extension. Moved to https://github.com/dotnet/vscode-csharp/issues/5738

WIth the C# Dev Kit, you should be able to launch your program with the Solution Explorer, Run and Debug, or `Debug: Select and Start Debugging` from the Command Pallette. See https://code.visualstudio.com/docs/csharp/debugging#_run-and-debug

**Comment by Licantrop0** [comment]
@WardenGnaw when i try to press F5 selecting a WinUI project, this is what I get:
<img width="1372" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/2388430/fdd1bd77-ead6-461a-ab80-332a89459e45">

**Comment by WardenGnaw** [comment]
@Licantrop0 I created https://github.com/microsoft/vscode-dotnettools/issues/98 to track WinUI debugging.
