### ISSUE TITLE
[SUGGESTION] Peek Unity documentation in editor

### ISSUE THREAD

**Issue by JaimeMitchell** [microsoft/vscode-dotnettools#502]
### Describe the feature you'd like

I'd like the documentation to work within Visual Studio Code but your instructions are not clear on this "command". The command line? In a JSON set as True? Can you please either make this feature something that can be set in VSC settings or just have it turned on automatically or have more clear instructions to turn it on, because this isn't adequate documentation and needs more details and hopefully a pic to show what you mean.

### Alternatives considered

Tried google search, tried running the command in project console in vsc, tried looking for it in settings in VSC, tried looking for it in Unity settings. Just please make it easier for the user.

**Comment by jbevain** [comment]
Hi @JaimeMitchell.

Is this about the Unity API reference?

In your code, highlight what you want to search in the Unity API reference:

<img width="460" alt="Highlight Code" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/1dbfe5da-b375-423c-80fe-3a9fbb774937">

Then open Visual Studio Code's `Command Palette` (CTRL+SHIFT+P on Windows, COMMAND+SHIFT+P on macOS) and type Unity:

<img width="659" alt="Command Palette" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/994b1b96-c934-4bff-9dd6-b088e063be6a">

Select Unity API Reference, and Visual Studio Code will search the Unity API Reference for what you've highlighted in a new browser window:

<img width="1354" alt="Unity API Reference" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/eeb6882e-8f5f-47b0-9041-413d0dc3432a">

**Comment by JaimeMitchell** [comment]
Hi, I was hoping it could give hints and define it within VSC instead of opening a whole new browser window. It would be nice to peek instead of being taken out of the environment and. Realized g the work flow. Thank you again!JaimeSent from my iPhone, enjoy the typos On Sep 10, 2023, at 10:44 PM, Jb Evain ***@***.***> wrote:﻿
Hi @JaimeMitchell.
Is this about the Unity API reference?
In your code, highlight what you want to search in the Unity API reference:

Then open Visual Studio Code's Command Palette (CTRL+SHIFT+P on Windows, COMMAND+SHIFT+P on macOS) and type Unity:

Select Unity API Reference, and Visual Studio Code will search the Unity API Reference for what you've highlighted in a new browser window:
