### ISSUE TITLE
Unable to load any solutions

### ISSUE THREAD

**Issue by mattleibow** [microsoft/vscode-dotnettools#504]
Type: <b>Bug</b>

I tried to open a solution, but no way to do that.
I don't have the open solution or solution explorer options at all.

Not sure what changed, maybe an extension/editor update that happened one night...

Extension version: 0.5.24
VS Code version: Code - Insiders 1.83.0-insider (Universal) (e073d674f38acbf855e6b2c0d8f4fe29cb2a8c83, 2023-09-08T09:09:03.905Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|40, 18, 10|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 6698d004-6faf-44a5-a725-f730c3f1de63|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
9b8hh234:30694863
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
asynctok:30821568
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttypecf:30823782
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809

```

</details>

**Comment by mattleibow** [comment]
I see this:

```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "/usr/local/share/dotnet/dotnet"
Using runtime installed in SDK because preferRuntimeFromSDK setting is set to true.
.NET server STDERR: Failed to load /usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib, 0x0001): tried: '/usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib' (code signature in <447EF902-6DE0-384B-8294-BFE4DB14DD3E> '/usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib' (no such file), '/usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib' (code signature in <447EF902-6DE0-384B-8294-BFE4DB14DD3E> '/usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/8.0.0-rc.1.23419.4/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

.NET server exited with 130
```

**Comment by mattleibow** [comment]
I am also opening a project that has a global json to the latest public build of net7 7.0.400

**Comment by tmeschter** [comment]
@mattleibow Is the "preferRuntimeFromSDK" setting turned on?

![image](https://github.com/microsoft/vscode-dotnettools/assets/10506730/1054df81-8beb-4dab-b7bc-1bc1036ff41d)

If so, can you turn it off for this workspace, close and reopen the workspace, and let us know if that helps?

**Comment by mattleibow** [comment]
It _was_ on. I turned it off and then restarted the whole editor (Quit and reopen) twice to be sure sure. But still the same:

<img width="1316" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1096616/e863b11d-51a7-42f8-8d7e-906716f0a82b">

**Comment by mattleibow** [comment]
That seems to have fixed it. Thanks!
