### ISSUE TITLE
.NET MAUI Extension: The preferred Android SDK/Java SDK directory was not used. 

### ISSUE THREAD

**Issue by Humbledonk** [microsoft/vscode-dotnettools#510]
I get this error from the .NET MAUI Extension: **The preferred Android SDK/Java SDK directory was not used.** 

I've manually edited the launch.json so that I can debug the Android app using the .NET MAUI extension. However I could not Generate Assets for Build and debug the usual way because the net8.0-android framework was not listed as an option there. It takes a while for this error to appear and the net8.0-android framework is listed as an option until this error appears.

Error Output:
user preferred path: c:\Program Files\Microsoft\jdk-11.0.20.101-hotspot
MSBuild JavaSdkDirectory: C:\Program Files\Microsoft\jdk-11.0.20.101-hotspot
JAVA_HOME: C:\Program Files\Microsoft\jdk-11.0.20.101-hotspot
Java SDK: shared with Visual Studio [installed]
Android service Java SDK found: C:\Program Files\Microsoft\jdk-11.0.20.101-hotspot
user preferred path: c:\Users\Admin\AppData\Local\Android\Sdk
MSBuild AndroidSdkDirectory: C:\Users\Admin\AppData\Local\Android\Sdk
ANDROID_HOME: C:\Users\Admin\AppData\Local\Android\Sdk
Android SDK: shared with Android Studio [installed]
Android service Android SDK found: C:\Users\Admin\AppData\Local\Android\Sdk
Android SDK recommended required components:
	platforms/android-34  installed
	build-tools/32.0.0  installed
	platform-tools  installed
	cmdline-tools/7.0  installed
Android SDK recommended optional components:
	emulator  installed
	system-images/android-34/google_apis/x86_64  installed

> VS bug [#1885082](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1885082)

**Comment by Pastajello** [comment]
Try pre-release version of maui extension, it may help if not using already.

**Comment by Humbledonk** [comment]
Hi and thanks for the reply.

I'm already running .NET MAUI v0.3.20 Pre-Release version.

Thanks

**Comment by wangzhen420** [comment]
This issue still repro on the below configuration:
*   VSCode: 1.83.0
*   .NET SDK: 7.0.402
*   MAUI: 7.0.96
*   Extension:

*   .NET MAUI: v0.4.9
*   C# Dev Kit: v0.5.150
*   C#: v2.5.30
*   IntelliCode for C# Dev Kit: v0.1.26
![image.png](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_apis/wit/attachments/da0143c8-f3fe-41bf-a7db-1ab2723329e0?fileName=image.png)
