### ISSUE TITLE
Name of debug provider confusing to users

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#512]
### Describe the Issue

When presented with debugger options the debug provider for C# Dev Kit is listed as "C#" causing confusion for users especially when placed next to other debuggers
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/fcc37d23-4812-43fc-bd3a-d8c72f3f6bf0)

### Expected Behavior

Something more descriptive of what this is

**Comment by WardenGnaw** [comment]
Instead of `C#` do you want `.NET`? 

The naming was similar to how VS Code does it for Javascript.
![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/02f8a987-cea4-4630-9eec-1e18282388a9)

**Comment by timheuer** [comment]
@webreidi what do you think on naming.  "C#" isn't awesome IMO -- if we merged all of them ideally we'd have one ".NET" listing and I think I'd be happy with that

**Comment by WardenGnaw** [comment]
I'm going to close this as this should be fixed with versions after [v2.3.27](https://github.com/dotnet/vscode-csharp/releases/tag/v2.3.27) of the C# Extension and using VS Code v1.83.0.
