### ISSUE TITLE
Rename built-in debug providers to remove 'Core'

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#513]
### Describe the Issue

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/46de687d-14e8-4433-b77f-c75f38655f52)
The included debug providers for .NET are listed as ".NET 5+ and .NET Core" -- .NET Core is not a name we use anymore and this is confusing as it is not referenced in learning materials and should be renamed.

We should consider how to align this with #512 as well so that we don't have two confusing choices

This terminology also shows up as names for created launch.json tasks:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/d36eaf48-07aa-4a4a-8965-f27190934f4c)

### Expected Behavior

Something that is current (.NET 5 is out of support as well) and uses current terminology.

**Comment by WardenGnaw** [comment]
This requires a VS Code change https://github.com/microsoft/vscode/issues/184457

**Comment by WardenGnaw** [comment]
What do we call the cross platform runtime/sdk for .NET 3?

**Comment by gregg-miskelly** [comment]
We use the same terminology in Visual Studio, so if we wanted to call this '.NET 5+' we should probably do the same in VS.

**Comment by gregg-miskelly** [comment]
It occurs to me that naming this well is even harder than I was first thinking -- the ".NET 5+ and .NET Core" entry is for CoreCLR, it will never work with mono. The entry currently called "C#" will hopefully eventually work for both (and .NET Framework if we ever wanted to support that too).

**Comment by WardenGnaw** [comment]
Closing as the Core debugger is now hidden.
