### ISSUE TITLE
[BUG] Solution Explorer -> Build shows unnecessary "Type to Filter Project" box

### ISSUE THREAD

**Issue by benday** [microsoft/vscode-dotnettools#515]
### Describe the Issue

When I go to Solution Explorer in VSCode on Mac with the intent to build the solution, when I right click the Build option from the context menu, I'm always prompted with a dialog that says "Type to Filter Project".

This seems like a bug. At a minimum, it's confusing. 

In order to get the Build to proceed, I have to click the "Type to Filter Project" box and press Esc twice.  

### Steps To Reproduce

Open a solution in VSCode
Expand the Solution Explorer panel
Right click the solution node and choose Build from the context menu

I've created a video of the problem: 
https://nday.be/go/buildsolutionbug

### Expected Behavior

When you choose the Build, Rebuild, or Clean option from the context menu, it should build the node that was clicked on.  If that node is the Solution, build the solution.  if the node is a Project, build that project.

### Environment Information

- OS: Mac
- VS Code Version: 1.82.2
- Extension Version: C# Dev Kit v0.4.10

> VS bug [#1886282](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1886282)

**Comment by Michael-Eng** [comment]
@chzuluag Is this us or VS Code?

**Comment by chzuluag** [comment]
@Michael-Eng This input box is coming from .Net Maui. FYI @tondat
