### ISSUE TITLE
try open Assembly-CSharp.csproj file, add new line value is net sdk you installed before ex:

### ISSUE THREAD

**Issue by SickoZ3b3** [microsoft/vscode-dotnettools#519]
try open Assembly-CSharp.csproj file, add new line value is net sdk you installed before ex:
` <TargetFramework>net7.0</TargetFramework>`
in below
`<TargetFrameworkVersion>v4.7.1</TargetFrameworkVersion>`

_Originally posted by @nguyenminhtri10061997 in https://github.com/microsoft/vscode-dotnettools/issues/271#issuecomment-1665364035_

**Comment by jbevain** [comment]
Hello,

Unfortunately I'm not quite sure what to make of this as there's nothing in there that is actionable, so I'm going to close the bug.

Please provide more details if you think we can help you, thanks!
