### ISSUE TITLE
Can not create new project on mac with c# dev kit

### ISSUE THREAD

**Issue by kelemenm** [microsoft/vscode-dotnettools#521]
Type: <b>Bug</b>

I did the following steps.

- Downloaded the arm64 vs code installation package
- .net 7 sdk installed
- Open vs code
- Install c# dev kit
- click on the Create new Project
- Select an empty folder
- NOTHING happens

When I install c# dev kit, I got the following error:
nstalling C# dependencies...
Platform: darwin, arm64

Downloading package '.NET Core Debugger (macOS / arm64)' (48985 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (macOS / arm64)'

Finished

Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (arm64) does not match the architecture of the extension (x64).
Dotnet path: /Users/username/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 01:14:59] [Program]Language server initialized

Extension version: 0.4.10
VS Code version: Code 1.82.1 (Universal) (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:49:32.930Z)
OS version: Darwin arm64 22.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 7|
|Memory (System)|16.00GB (1.01GB free)|
|Process Argv|--crash-reporter-id fdba697a-55dd-4ffe-84ed-96e8ca6c23d7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
962ge761:30835153
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746
pythonfb280951:30830810

```

</details>

**Comment by kelemenm** [comment]
@tmeschter You can find it below. 

.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.401/

Host:
  Version:      7.0.11
  Architecture: arm64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Michael-Eng** [comment]
@kelemenm can you try the prerelease version of C# Dev Kit? We took an update to msbuildlocator which should help us find the version of .NET

**Comment by lifengl** [comment]
based on the description here, it seems that vscode didn't have the same $PATH environment variable, as it cannot locate dotnet location there. if it is a machine with newly SDKs, it could be the vscode started earlier would not pick up later environment changes. my suggestion is to quit vscode completely, and restart it with the command environment you can run dotnet command  correctly to see whether it addresses the problem.

**Comment by lifengl** [comment]
another thing to check is to open the extension log folder in your vscode session, and find C# Dev Kit logging folder, inside ServiceHub folder, there should be two log files called **Composition*.log. Inside it, it would contains some logging including printing out $PATH environment variable captured in the process. Check whether it contains the path where dotnet command can be located.

**Comment by Michael-Eng** [comment]
We think this might be an issue where VS Code was launched without the environment variable set (maybe .NET SDK is installed) so we can't see dotnet.exe. Restarting VS Code might fix the issue.

**Comment by Michael-Eng** [comment]
I'm going to close this since we do not have any more information.

**Comment by matteobaldassarre** [comment]
Hi @Michael-Eng, 
I came across the same issue today, this is the output of my dotnet --info

.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Ambiente di runtime:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.304/

Host:
  Version:      7.0.7
  Architecture: arm64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.304 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Michael-Eng** [comment]
A few questions for you:

- What version of the C# Dev Kit are you using (can you try with the latest version? (some fixes were made)
- How did you install .NET? 
- Can you see dotnet.exe in the path in the terminal in VS Code?

FYI - There is one known issue we believe in VS Code where $PATH is incorrect on Mac in some scenarios.
