### ISSUE TITLE
Intellisence not apply to new file until i close vscode 

### ISSUE THREAD

**Issue by linger123** [microsoft/vscode-dotnettools#525]
Type: <b>Bug</b>

I have this message which appears when opening vscode and any addition of new .cs files the intellisence does not apply: <<The workspace is on a file system (or a remote share) which does not support file watchers. The project system experience may be degraded.>>

Extension version: 0.4.10
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:41:36.199Z)
OS version: Linux x64 6.2.0-32-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|12.62GB (4.10GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id b1fc8426-d5ea-4b5f-8853-eea3f39c7ff2|
|Screen Reader|no|
|VM|25%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30835153
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by tmeschter** [comment]
@linger123 Can you tell us more about the file system these files are on?

**Comment by Michael-Eng** [comment]
@chzuluag If they're not on a file system which supports file watchers, not sure if there's anything we can do?

**Comment by chzuluag** [comment]
@linger123 We have added the ability to enable the VS Code Native File System Watcher in C# Dev Kit throug a Workspace Setting. Then, you can create a watcher exclusion list in your settings using the `files.watcherExclude` property to work around the limitation Linux systems have on file watchers.

This will be available in our **next pre-release.** 

![image](https://github.com/microsoft/vscode-dotnettools/assets/49407227/4470635f-5975-4f73-a189-893c5b963886)

**Comment by linger123** [comment]
@chzuluag Great

**Comment by Smpse** [comment]
Console.WriteLine('Hello World!');
