### ISSUE TITLE
[BUG] SDK not found

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#527]
### Describe the Issue

Weird thing happened when I updated my VS Code and C# Dev Kit this morning. I have .NET 8 SDK installed. When I updated (it updated both C# Dev Kit and VS Code at the same time), projects failed to load because it couldn't find my SDK. Running dotnet --version in the terminal in VS Code couldn't see an SDK. I downloaded and installed the .NET 7 SDK and refreshed VS Code. Everything started working fine and running dotnet --version located my .NET 8 SDK.

2023-09-14 08:59:23.113 [info] No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

2023-09-14 08:59:23.124 [info] Additional information of .NET SDKs for diagnostic
Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-09-14 08:59:23.133 [info] Project system initialization finished. 0 project(s) are loaded, and 4 failed to load.

### Environment Information

Version: 1.83.0-insider (user setup)
Commit: 7b0ae6cf9d5a0c891ad1adc4da9c36c4dc453d4d
Date: 2023-09-14T05:33:44.297Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.25947
C# Dev Kit: v0.5.47
C#: v2.2.10

**Comment by nagilson** [comment]
I believe some changes were made to how CDK/C# load the SDKs on the machine in this version, @Michael-Eng do you know who would've been working on that change so we could have them take a look?

**Comment by Michael-Eng** [comment]
@webreidi what version of .NET 8 did you have installed? We know of one issue where .NET isn't signing some versions of .NET 8 which means they won't load for us. 

@lifengl  any ideas?

**Comment by webreidi** [comment]
@Michael-Eng / @lifengl  I had 8.0.100-preview.6.23330.14.

**Comment by Michael-Eng** [comment]
What version of the C# Dev Kit is installed? Can you confirm if the current prerelease build is working?

**Comment by Michael-Eng** [comment]
@Jxwoon can you take a look?

**Comment by Michael-Eng** [comment]
@Jxwoon Lifeng says that this could be a .NET or machine-setup issue. If dotnet.exe dosn't show any sdks it may be an issue in .NET and not CDK.

`.NET SDKs installed:
No SDKs were found.`

**Comment by Jxwoon** [comment]
Closing this issue. I believe this issue stems from machine set-up issues with the .NET SDK.
