### ISSUE TITLE
[BUG] `dotnet.dotnetpath` does not support relative paths (unlike omnisharp.dotnetpath)

### ISSUE THREAD

**Issue by sandyarmstrong** [microsoft/vscode-dotnettools#53]
### Describe the Issue

My repo provisions a repo-local installation of the .NET SDK. As such, my workspace settings previously had `"omnisharp.dotnetPath": "../.dotnet"`, which worked.

After upgrading to the prerelease version of the C# extension (v2.0.206), I adjusted this setting to `"dotnet.dotnetPath": "../.dotnet"`.

The language server now fails to start and my C# console output shows:

```
[Error - 11:20:17 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Cannot find dotnet path '../.dotnet/dotnet'
```

**Comment by sandyarmstrong** [comment]
If I work around this by using absolute paths, I start to hit https://github.com/microsoft/vscode-dotnettools/issues/63.

**Comment by EelcoLos** [comment]
Adding to OP:
when stored in git, other devs cannot use the absolute path. So I removed it, stating it should be somewhere in the root directory, just above the `.vscode` folder. This is not accepted as option, hence I cannot share this with other developers

**Comment by nagilson** [comment]
Is `dotnetPath` a setting in C#/CDK, which gets forwarded to the runtime `existingDotnetPath`? Or are they separate things? @arkalyanms @dibarbet

**Comment by dibarbet** [comment]
Closing to track on the C# extension side - https://github.com/dotnet/vscode-csharp/issues/6471
