### ISSUE TITLE
Android SDK Update

### ISSUE THREAD

**Issue by briankb** [microsoft/vscode-dotnettools#534]
Type: <b>Bug</b>

Fresh install from latest OpenJDK, sudo dotnet workload restore and still I cannot get a working C# .NET Maui environment to function on MacOS Silicon. 

Extension version: 0.3.22
VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.25GB free)|
|Process Argv|. --crash-reporter-id 4378fe5e-fb30-4a36-9381-8d4e24928443|
|Screen Reader|no|
|VM|0%|
</details>

> VS bug [#1888331](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1888331)

**Comment by jonpryor** [comment]
@briankb: by "latest OpenJDK", what do you mean?  OpenJDK 17, 21, 22, other?

A forthcoming .NET 7 service release will allow use of OpenJDK 17 by default, but in the meantime you can [set the `$(LatestSupportedJavaVersion)` MSBuild property to 17.0.99](https://github.com/xamarin/xamarin-android/issues/8304#issuecomment-1696004774) in order to use OpenJDK 17:

```xml
```

**Comment by jonpryor** [comment]
@briankb: what is the *exact* error message that you are getting?  Would you be able to provide a `.binlog` file, via e.g. `dotnet build -bl`?

**Comment by samhouts** [comment]
@briankb Since we have not received the requested information from you, we are unable to continue investigating this issue. If you have more to add, please open a new issue. Thanks!
