### ISSUE TITLE
[BUG] Razor page lists directives and functions as reference not found

### ISSUE THREAD

**Issue by chaoserene** [microsoft/vscode-dotnettools#536]
### Describe the Issue

I switched from Visual Studio for Mac to Visual Studio Code a few weeks ago and I've started facing this issue:

Whenever I open a Razor page file (CSHTML), it always shows errors in common directives such as `@using` and `@model`. This error seems to be only within OmniSharp since compiling the project doesn't give an error.

This doesn't interfere with my work, however, sometimes is hard to discern whether something is an actual error or this issue here.

![report_error](https://github.com/microsoft/vscode-dotnettools/assets/17412977/7fd39952-4c18-4bce-8444-0fc92767b132)

For example, in this image (sorry that I had to blur some things), I have a regular page open and:

- It outlines errors in # **1** (sorry there are two 1s - forgot to change to 2);

- There is also # **3** that is a call to `Url.Action("Method", "Controller")`, which doesn't seem to recognize the second parameter;

- They ended up showing as an error in the file in # **4**;

- Which results in an output from the tool in # **5**.

I'm not sure whether this is something I need to configure in my environment.

### Steps To Reproduce

1. Create an ASPNET MVC Project in Mac with .NET 5;
2. Try to edit a Razor page file, adding common directives;
3. Errors are shown in the Problems tab and file title tab, but not in compilation.

### Expected Behavior

No errors are to be shown.

### Environment Information

- OS: macOS Ventura 13.5.1 ARM;
- Editor: VS Code 1.82.2 x64;
- .NET: 5.0.408 x64;
- C# Dev Kit: v0.5.47;

**Comment by allisonchou** [comment]
Hi @chaoserene, thanks for the report! A few questions:

1) Does this issue repro when using a newer version of .NET? As far as I'm aware, .NET 5 has reached end of life and is no longer officially supported.
2) You mentioned you're on C# Dev Kit v0.5.47. Which version of the C# Extension do you have installed?
3) Can you share the contents of your Razor log? (Should be one of the dropdowns in the output tab)
