### ISSUE TITLE
Tests Started From Test Explorer Not Found Between Build and Start of Test

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/vscode-dotnettools#539]
Type: <b>Bug</b>

I work on a not small code base (https://github.com/microsoft/fhir-server) and have an intermittent issue where tests do not run or debug. Test discovery takes about 41 seconds on my solution. When I try to run a test, a rebuild is issued and it seems that the test is not found in time to actually launch the test for execution. I see that the test is not immediately available in the test explorer but appears after some time (~10 sec).

We are using XUnit ant the XUnit Visual Studio runner. Not sure if the issue is purely XUnit, purely the Dev Kit, or a combo of the two but due to XUnit usage worth bringing attention.

Error from the C# Dev Kit Test Explorer is:

System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest Default,/Users/<me>/source/fhir-server/test/Microsoft.Health.Fhir.R4.Tests.Integration/bin/Debug/net6.0/Microsoft.Health.Fhir.R4.Tests.Integration.dll,Microsoft.Health.Fhir.Shared.Tests.Integration.Features.Operations.FhirOperationDataStoreReindexTests(CosmosDb).GivenAMatchingReindexJob_WhenGettingById_ThenTheMatchingReindexJobShouldBeReturned,,:2c2119e7-f03a-50b9-93cd-07ec736d294d
   at Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   at Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.VisualStudio.TestStorage.TestStore.GetTestDetailsForNodes(Int32 viewId, IEnumerable`1 nodeIds, Int32 limit)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass54_0.<QueryTestDetailAsync>b__0()
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallWithCatchAsync[T](IInternalLogger log, Func`1 func, T defaultValue)

Extension version: 0.4.10
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|14, 11, 8|
|Memory (System)|64.00GB (3.63GB free)|
|Process Argv|--crash-reporter-id 7d8b54e8-b0d4-4f42-b8bb-d9dcb17366be --crash-reporter-id 7d8b54e8-b0d4-4f42-b8bb-d9dcb17366be|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by AbhitejJohn** [comment]
@peterwald : Could this be related to the bug fix we made in the product around this time?

**Comment by peterwald** [comment]
I tried to reproduce this, but was unable to. I believe this was fixed a month or so ago when we serialized the discovery and execution workflows to eliminate races. I'm going to close it out as fixed for now, but @mikaelweave please reopen or comment if you are still seeing this issue with the latest version.
