### ISSUE TITLE
[BUG] Problems tab has wrongly parsed, truncated errors after 'dotnet build'

### ISSUE THREAD

**Issue by jacekjarosz55** [microsoft/vscode-dotnettools#540]
### Describe the Issue

![image](https://github.com/microsoft/vscode-dotnettools/assets/72438686/5b9a4803-57ec-45d8-aa54-f392fa2eb44a)
Happens when working on a large project with long paths
Doesn't seem to happen on Linux, just Windows

### Steps To Reproduce

1. Open a project with long paths
2. Build

### Expected Behavior

Problems being parsed correctly

### Environment Information

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by flmontpetit** [comment]
I am also experiencing this : 

![vs-code-bug](https://github.com/microsoft/vscode-dotnettools/assets/4337528/ce8525de-e6d8-4dfa-8c26-41ba4a9008d5)

Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by adrianvmsft** [comment]
Rerouting to the Roslyn team for initial investigation as it owns most of the code involved in this scenario (including error deduplication).

**Comment by dibarbet** [comment]
Looking at the screenshots it appears to be using the old problem matcher (see the `cpp` codes) which we moved away from a while back.  I tried it out just now on some really long file paths and didn't encounter any issues.

Going to close this, feel free to re-open and ping me (ideally with an up to date screenshot) if you can reproduce this.
