### ISSUE TITLE
[BUG] Run .NET MAUI iOS APP in Release using VSCode .NET MAUI Build Tasks

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [microsoft/vscode-dotnettools#541]
### Describe the Issue

How can I use .NET MAUI build tasks to build and run in ``-p:Configuration=Release`` like I do in Visual Studio for Mac?

Below is how I run my .NET MAUI iOS app with Release configuration in Visual Studio for Mac
![image](https://github.com/microsoft/vscode-dotnettools/assets/130459814/287231e1-d087-4369-a192-2ad690652626)

My ``.vscode/tasks.json`` has the following configuration where ``maui: Build Release`` does not work;
```
        {
            "type": "maui",
            "configuration": "Debug",
            "project": "BioSnap",
            "problemMatcher": [
                "$msCompile"
            ],
            "label": "maui: Build Debug"
        },
        {
            "type": "maui",
            "configuration": "Release",
            "project": "BioSnap",
            "problemMatcher": [
                "$msCompile"
            ],
            "label": "maui: Build Release"
        }
```

My ``.vscode/launch.json`` looks like this and works for ``maui: Build Debug``:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[DEBUG] BioSnap IOS",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build Debug",
            "project": "BioSnap",
        },
    ]
}
```

Running the ``maui: Build Release`` task gives me this error;
![image](https://github.com/microsoft/vscode-dotnettools/assets/130459814/2bbc3518-0768-4e85-8348-8c4153a13bf0)

**How do I do this? and shouldn't the configuration option in the tasks.json also allow for "Release"?**

### Steps To Reproduce

1. Open a .NET MAUI Project with VSCode
2. Have .NET MAUI extension installed
3. Create a ``launch.json`` configuration that runs ``maui: Build Release`` as a ``preLaunchTask``.
4. Run the configuration

### Expected Behavior

That the terminal uses ``-p:Configuration=Release`` instead of ``-p:Configuration=Debug`` for its build command.

### Environment Information

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

ms-dotnettools.dotnet-maui v0.3.22

**Comment by xanril** [comment]
Hi, I was able to reproduce your issue. What worked for me was to specify the configuration in `launch.json` as well. I modified your example to match my setup.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[RELEASE] BioSnap IOS",
            "type": "maui",
            "request": "launch",
            "configuration": "Release",
            "preLaunchTask": "maui: Build Release",
        },
    ]
}
```

**Comment by MLB-BIOMETRIC** [comment]
@xanril Thanks for your comment.

**I still get this error:**
```
Error: The maui task detection didn't contribute a task for the following configuration:
{
    "type": "maui",
    "configuration": "Release",
    "project": "BioSnap",
    "problemMatcher": [
        "$msCompile"
    ],
    "label": "maui: Build Release"
}
```

With the following configuration:

``launch.json``:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[DEBUG] BioSnap IOS",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build Debug",
            "project": "BioSnap",
        },
        {
            "name": "[RELEASE] BioSnap IOS",
            "type": "maui",
            "request": "launch",
            "configuration": "Release",
            "preLaunchTask": "maui: Build Release",
            "project": "BioSnap",
        },
    ]
}
```

``tasks.json``:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "maui",
            "configuration": "Debug",
            "project": "BioSnap",
            "problemMatcher": [
                "$msCompile"
            ],
            "label": "maui: Build Debug"
        },
        {
            "type": "maui",
            "configuration": "Release",
            "project": "BioSnap",
            "problemMatcher": [
                "$msCompile"
            ],
            "label": "maui: Build Release"
        }
    ]
```

Did you make it work?

**Comment by xanril** [comment]
Yup, but I started with a blank project and I did not create `tasks.json`. I just used the default and added `configuration: Release` in `launch.json`. Maybe try stripping it down to the default first and try adding your configs one by one to pinpoint where it breaks.

**Comment by talhabera** [comment]
Onay need to add `"configuration": "Release"` line. Solves everything.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[Debug] BioSnap]",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        },
        {
            "name": "[Release] BioSnap",
            "type": "maui",
            "request": "launch",
            "configuration": "Release",
            "preLaunchTask": "maui: Build",
        },
    ]
}
```

**Comment by MLB-BIOMETRIC** [comment]
Thanks, it works.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[DEBUG] BioSnap",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "BioSnap",
            "configuration": "Debug"
        },
        {
            "name": "[DEBUG] Tests",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "Tests",
            "configuration": "Debug"
        },
        {
            "name": "[RELEASE] BioSnap",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "BioSnap",
            "configuration": "Release"
        },
        {
            "name": "[RELEASE] Tests",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "project": "Tests",
            "configuration": "Release"
        }
    ]
}
```

**Comment by flipper09112** [comment]
@MLB-BIOMETRIC Hi you know how do if we have a Maui app with a packageReference of a MauiLib?
Because i have a app with config "Mockup" but when i used this config i want the lib with Config "PP"

**Comment by devhls** [comment]
Could not find a task maui build
