### ISSUE TITLE
[BUG] Can't navigate to test on Test Explorer

### ISSUE THREAD

**Issue by Stanzarectah** [microsoft/vscode-dotnettools#543]
### Describe the Issue

I am using C# Dev Kit and I cannot see the icon to navigate to the test script nor do I see the option in menu.

![image](https://github.com/microsoft/vscode-dotnettools/assets/17443786/0df897be-41cd-4067-bb6a-95d8125b1df0)

I'm using .NET 6.0 with NUnit test framework

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Appium.WebDriver" Version="4.4.0" />
    <PackageReference Include="Azure.Identity" Version="1.8.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.15.1" />
    <PackageReference Include="BarcodeReader.ImageSharp" Version="2.0.1" />
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="7.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.2" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.12" />
  </ItemGroup>

</Project>
```

### Environment Information

-OS: Windows 10
-VSCode: Version: 1.82.2 (user setup)

**Comment by timheuer** [comment]
@Stanzarectah are you referring to `Go to Test` like it is in Visual Studio?

I think this will be in an upcoming version of VSCode (the test explorer and menus are provided by VSCode, not the C# Dev Kit):
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/c70686c9-3b5b-4cce-995c-f2ee06fd9211)

The above is a screenshot from the Insiders build (1.83).

**Comment by Stanzarectah** [comment]
@timheuer - yes I am. Turns out one of  my test functions had an invalid  parameter in the "TestName" attribute. This caused the function to be corrupted making the 'Go to Test' option not visible.

I corrected the function, did a dotnet build and all is working now.

Cheers,

Stanley

**Comment by Stanzarectah** [comment]
@timheuer - Turns out one of my test functions had an invalid parameter in the "TestName" attribute. This caused the function to be corrupted making the 'Go to Test' option not visible.

I corrected the function, did a dotnet build and all is working now.

Cheers,

Stanley
