### ISSUE TITLE
[BUG] Can't extract interface

### ISSUE THREAD

**Issue by julioct** [microsoft/vscode-dotnettools#545]
### Describe the Issue

Extracting an interface is an essential part of day-to-day coding activities, but with the latest C# extension version you can't do it.

In version 1.26.0:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/85f07db5-deda-4a6d-972f-9e4cb2c9c666)

In latest version:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/09c466fa-5421-40bd-a7fe-34be5d8c517e)

Can we get the Extract interface... context menu item back?

### Steps To Reproduce

1. Use the lightbulb to open the context menu item on any class
2. The extract interface... context menu item is not there

### Expected Behavior

The extract interface... context menu item should be there.

### Environment Information

- OS: Windows 11
- VS Code version: Code - Insiders 1.83.0-insider
- Extension version: 2.2.10

**Comment by timheuer** [comment]
@arkalyanms
