### ISSUE TITLE
[BUG] xUnit test with MemberData remains as "not yet run"

### ISSUE THREAD

**Issue by julioct** [microsoft/vscode-dotnettools#552]
### Describe the Issue

When you use MemberData attribute in an xUnit theory and you run the test, the VS Code UI indicators briefly show the test as passed (or failed) and then it reverts back to "not yet run"

https://github.com/microsoft/vscode-dotnettools/assets/2374270/efcba8d3-e4d7-451e-9daa-daa0c5468109

Any other test that does not have the MemverData attribute will show the test as passed/failed and remain with that state.

### Steps To Reproduce

1. Define an xUnit test method that uses MemberData:

```csharp
public class ErrorMapperTests
{
    [Theory]
    [MemberData(nameof(Data))]
    public void MapStatusCode_WhenCalled_ReturnsExpectedStatusCode(Exception exception, int expected)
    {
        // Arrange & Act
        int actual = ErrorMapper.MapStatusCode(exception);

        // Assert
        actual.Should().Be(expected);
    }

    public static IEnumerable<object[]> Data =>
        new List<object[]>
        {
            new object[] { new InvalidIpAddressException("1.2.3.4"), StatusCodes.Status400BadRequest },
            new object[] { new MatchNotReadyException("invalid"), StatusCodes.Status400BadRequest },
            new object[] { new Exception(), StatusCodes.Status500InternalServerError }
        };    
}
```

2. Build the project
3. Run the test
4. VS Code UI briefly shows the test as passed, then reverts it to "not yet run"

### Expected Behavior

The test should remain with the "passed" indicator as any other test.

### Environment Information

OS: Windows 11
VS Code version: Code - Insiders 1.83.0-insider
Extension version: 2.2.10

**Comment by knumat** [comment]
Could this be the same bug as #149 ?  Both seem to be describing the same scenario (Test Explorer sometimes doesn't display status properly for tests with MemberData/InlineData).

**Comment by AbhitejJohn** [comment]
It indeed is the same as #149. Thank you @knumat.
