### ISSUE TITLE
[BUG] confusing dialog when using preview runtime version

### ISSUE THREAD

**Issue by danmoseley** [microsoft/vscode-dotnettools#555]
### Describe the Issue

![image](https://github.com/microsoft/vscode-dotnettools/assets/6385855/aef883fa-3f8d-4f5f-9097-45ccc79ad4b4)

1. the wording is a bit clumsy and seems to assume the runtime is earlier than C# dev kit was designed for. in my case it's today's 8.0 rtm build so it's not. 

changing "with earlier released runtime" --> "with a preview runtime" would do it.

2. it's saying that the SDK is preview, and that to use a non-preview runtime, set 'prefer runtime from SDK'. that seems a contradiction.

### Environment Information

Windows 11
v1.82.2 vscode
v0.4.10 extension

**Comment by timheuer** [comment]
@webreidi feedback on wording.

**Comment by lifengl** [comment]
this message and the related setting has been removed.
