### ISSUE TITLE
Unable to add new class/interface to projects

### ISSUE THREAD

**Issue by KNajarro** [microsoft/vscode-dotnettools#556]
Type: <b>Bug</b>

Error happens any ime trying to create an interface/class from solution explorer: 

Error running command csdevkit.addNewFile: Failed with ExitCode(6) Details No se encontró ninguna plantilla que coincida con: 'interface' Para mostrar la lista de plantillas instaladas, ejecute: dotnet new --list Para buscar las plantillas en NuGet.org, ejecute: dotnet new interface --search . This is likely caused by the extension that contributes csdevkit.addNewFile.

Extension version: 0.4.10
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:51:20.981Z)
OS version: Linux x64 6.4.15-200.fc38.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 3299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|23.21GB (18.82GB free)|
|Process Argv|. --crash-reporter-id a534fb25-1aff-499b-b93e-0cf91d6900a7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by dileep-hegde** [comment]
looks like dup #500. As per smitpatel comment. It will be fixed in next release. Should be available in 0.5.*

**Comment by timheuer** [comment]
@smitpatel

**Comment by smitpatel** [comment]
@KNajarro - Can you try latest version and see if it is fixed?

**Comment by KNajarro** [comment]
> @KNajarro - Can you try latest version and see if it is fixed?

Hi, I gave it a try today, with a clean VS Code installation but keeps coming the same error.

**Comment by eben-siaw** [comment]
Please let them fix it asap

**Comment by smitpatel** [comment]
This has been fixed in GA release. If you are still facing the issue, then please share repro steps, and screenshots demonstrating the behavior you are seeing.
