### ISSUE TITLE
Unity removes entries from files.exclude

### ISSUE THREAD

**Issue by SorenPP** [microsoft/vscode-dotnettools#559]
Type: <b>Bug</b>

Unity version: 2022.3.9f1
Unity "Visusal Studio Editor" package version: 2.0.21
VS Code "Unity" package version: 0.9.1

1. Setup a new empty Unity project
2. Make sure the "Visusal Studio Editor" package is installed
3. Open the project in Visual Studio Code
4. Make sure the "Unity" package is installed
5. Update .vscode/settings.json with lines to hide \*.csproj and \*.sln files by adding the following to files.exclude:
        "\*.sln": true,
        "\*.csproj": true,
6. Make a file change in Unity for example add an empty folder
7. Notice how the lines added in 5. have been removed
    I expect it to not touch my settings after they have been created.

I am not sure if it is the "Unity" extension in VS Code or the "Visual Studio Editor" package in Unity that makes the changes.

Extension version: 0.9.1
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.42GB free)|
|Process Argv|D:\\PortaProjects\\Skattekisten|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jbevain** [comment]
Hi @SorenPP,

Thanks for reaching out!

The “Visual Studio Editor” Package version 2.0.21 will patch existing settings if the settings are going to prevent the extensions to work properly. If you exclude the `.csproj` and `.sln`, the `C#` and `C# Dev Kit` extensions might not work properly.

That being said, if you really want to do it, just create an empty text file `.vstupatchdisable` in your `.vscode` folder and the Package won't touch the settings.

**Comment by SorenPP** [comment]
Thank you for getting back so fast.

I was not aware "files.exclude" interfered with other extensions. I thought it was just for hiding files and folders.
That is mildly inconvenient with all the project files Unity creates bloating the file explorer.
