### ISSUE TITLE
[BUG] always request downloading .NET Runtime

### ISSUE THREAD

**Issue by imokoi** [microsoft/vscode-dotnettools#562]
### Describe the Issue

visualstudiotoolsforunity.vstuc requested to download the .NET Runtime.
Downloading .NET version(s) 7.0.11~arm64 ...

### Environment Information

macOS , VSCode

**Comment by anray156** [comment]
same issue

**Comment by jbevain** [comment]
@imokoi is this still happening on the latest versions of the C# and C# Dev Kit extensions?

**Comment by atship** [comment]
same issue occurs on windows 10 with the lastest version of VSCode
``Downloading .NET version(s) 7.0.12~x64`` now

**Comment by roymina** [comment]
btw, settings for windows users:
```json
"dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "visualstudiotoolsforunity.vstuc",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        }
    ],
```

**Comment by thomasbergersen** [comment]
Even if the path is set correctly, a.NET Runtime window message pops up every time you restart. How do I turn it off

**Comment by nagilson** [comment]
@zhengying Are you using the unity extension? If so, you also need to set it for the visualstudiotoolsforunity.vstuc extension id.

If the download is failing, it would be good to have logs from the failure. These logs would have already been deleted by this point, but when you see the failure, there should be an error in the bottom right corner like @thomasbergersen mentions. If you click to report an issue, it will take you to a github issue page and tell you were the log is you need to submit.

**Comment by lifengl** [comment]
C# Dev Kit would download dotnet runtime, if it cannot find NET 7 SDK installed on the machine, so installing NET 7 SDK, and ensure it to be resolvable through the PATH environment.  On Mac, also make sure that you do not turn on an option to work with ad-hoc/test version SDK. The extension will always download its own stable version of runtime, if this option is turned on. The option is only for a small set of developers who wok on daily SDK builds, and should not be turned on in common developing environment.

**Comment by Gonkers** [comment]
> C# Dev Kit would download dotnet runtime, if it cannot find NET 7 SDK installed on the machine, so installing NET 7 SDK, and ensure it to be resolvable through the PATH environment. On Mac, also make sure that you do not turn on an option to work with ad-hoc/test version SDK. The extension will always download its own stable version of runtime, if this option is turned on. The option is only for a small set of developers who wok on daily SDK builds, and should not be turned on in common developing environment.

This is quite annoying as I have the .NET 8 SDK installed. 🫤

**Comment by lifengl** [comment]
It doesn't have to be a full NET 7 SDK, I believe installing NET 7 runtime to the global location would be good enough. Installing SDK is just an easy way to ensure it is there. In any case, different versions of SDKs or runtimes can be installed side by side, so it should not affect the usage of NET 8 SDK.

On the other hand, once the auto-download code downloads one copy successfully, it should reuse it in the next session. However, it would download a new version every time an update comes in. This is not controlled by the extension. 

Most executables in the extensions are only tested against NET 7 runtime, and they are restricted to only run with NET 7 runtime, but not the NET 8 runtime. The problem here is that the SDK installed is to be used to build/run your application, but the C# extension itself is a NET Core application, which has its own runtime requirement.

 Although NET 8 runtime is mostly backward compatible to NET 7 runtime, some behaviors are different, so it is not guaranteed that things will work as expected with proper testing.

> 
> This is quite annoying as I have the .NET 8 SDK installed. 🫤

**Comment by alexandrearc** [comment]
Was this bug introduced recently ? I didn't have this issue few months ago but I am having now..

**Comment by Gonkers** [comment]
> It doesn't have to be a full NET 7 SDK, I believe installing NET 7 runtime to the global location would be good enough. Installing SDK is just an easy way to ensure it is there. In any case, different versions of SDKs or runtimes can be installed side by side, so it should not affect the usage of NET 8 SDK.
> 
> On the other hand, once the auto-download code downloads one copy successfully, it should reuse it in the next session. However, it would download a new version every time an update comes in. This is not controlled by the extension.
> 
> Most executables in the extensions are only tested against NET 7 runtime, and they are restricted to only run with NET 7 runtime, but not the NET 8 runtime. The problem here is that the SDK installed is to be used to build/run your application, but the C# extension itself is a NET Core application, which has its own runtime requirement.
> 
> Although NET 8 runtime is mostly backward compatible to NET 7 runtime, some behaviors are different, so it is not guaranteed that things will work as expected with proper testing.
> 
> > This is quite annoying as I have the .NET 8 SDK installed. 🫤

Thanks for the response, I understand. Nothing is ever as simple as it seems from the outside.

**Comment by IntelHeartPrime** [comment]
Thanks , I had fixed it 

`
    "dotnetAcquisitionExtension.existingDotnetPath": [

        {
            "extensionId": "msazurermtools.azurerm-vscode-tools",
            "path": "/usr/local/share/dotnet/dotnet"
        },
        {
            "extensionId": "visualstudiotoolsforunity.vstuc",
            "path": "/usr/local/share/dotnet/dotnet"
        }
    ]
}

`

**Comment by netcore-jroger** [comment]
I added the following code and got it to work:
```json
"dotnetAcquisitionExtension.existingDotnetPath": [
    {
        "extensionId": "tintoy.msbuild-project-tools",
        "path": "C:\\Program Files\\dotnet\\dotnet.exe"
    }
]
```

**Comment by usamino** [comment]
When I open it from the Unity project, an error occurs, but when I open the project from the vscode open button, it works fine.
Can you all try it?

**Comment by Zanbrachrissik** [comment]
> Thanks , I had fixed it
> 
> ```
> "dotnetAcquisitionExtension.existingDotnetPath": [
>     {
>         "extensionId": "msazurermtools.azurerm-vscode-tools",
>         "path": "/usr/local/share/dotnet/dotnet"
>     },
>     {
>         "extensionId": "visualstudiotoolsforunity.vstuc",
>         "path": "/usr/local/share/dotnet/dotnet"
>     }
> ]
> ```
> 
> **Add the " visualstudiotoolsforunity.vstuc " to config file**

This is what I need. And I figured out that the extensionId is the name of the package. So once you find some other packages keep requesting for downloading, add their name and it works like a charm.

**Comment by MichelGhaith** [comment]
i tried all your solutions and nothing work with me.

**Comment by nagilson** [comment]
@MichelGhaith  please submit a new issue with more details at https://github.com/dotnet/vscode-dotnet-runtime

**Comment by mawid6** [comment]
2024: This is still an issue, has been for years.
