### ISSUE TITLE
[BUG] I can install C# Dev Kit on windows 7 due to VS code version

### ISSUE THREAD

**Issue by Aladdin4u** [microsoft/vscode-dotnettools#568]
### Describe the Issue

select View > Command Palette and type ".NET" into the search box. From the list of commands, select the .NET: Generate Assets for Build and Debug command.
Error:
`Could not locate .NET Core project in TodoApi. Assets were not generated.`

-Try to install C# Dev Kit
`Unable to install extension 'ms-dotnettools.csdevkit' as it is not compatible with VS Code '1.70.3'.`

I'm new to C# any help please.

### Environment Information

OS: [Windows 7]
VScode Version: [1.70.3]

**Comment by timheuer** [comment]
@Aladdin4u can you upgrade to VS Code 1.80 or higher? VS Code is supported on Windows 10+ (https://code.visualstudio.com/docs/supporting/requirements#_platforms).

**Comment by Aladdin4u** [comment]
I can't upgrade because of my os version: windows 7

**Comment by timheuer** [comment]
> I can't upgrade because of my os version: windows 7

Oh no! Unfortunately our extensions require the newer VSCode engine for some APIs. How can we help you get off Windows 7? Is that a policy of employment or anything? As Windows 7 itself is long out of support itself.

**Comment by Aladdin4u** [comment]
Ok thanks
