### ISSUE TITLE
Blazorwasm Debugging is Broken

### ISSUE THREAD

**Issue by leslierichardson95** [microsoft/vscode-dotnettools#570]
Type: <b>Bug</b>

I'm currently writing a Blazor Webassembly App using C# Dev Kit and am trying to debug it (specfically a .cs file at the moment).  However, the debugging experience feels super buggy and broken.  Issues include the following:

-- Sometimes the attach to the default "Standalone Blazor Webassembly App" option works and sometimes it doesn't.  I get an "unable to attach to browser" popup with no explanation why.

-- The variables in the Variables table of the Run and Debug window sometimes disappear when I change focus to the Watch window and add new variables there.  I'm unable to get the Variables window to repopulate when this happens.

-- Sometimes when trying to step (specifically step over), I'm redirected to a dotnet.wasm file (which also takes too long to load).  I have no idea what triggers this file to show up.  What is this file and is it possible to turn off this redirect?  When this happens, I also don't know how I can get back to debugging MY code afterward without presumably restarting the session.

-- I can't evaluate certain variables in the Watch window despite them being in scope.  For example, I have a breakpoint that successfully gets hit inside a 'for' loop but I can't view the value of my 'i' iteration value.

At least one or more of these issues happens in every debugging attempt and it's left me feeling very unproductive and makes me want to swap to debugging in VS Win.  I can't do this however because I have to give some .NET Conf-related talks highlighting debugging with the C# Dev Kit...

Extension version: 0.5.127
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.32GB free)|
|Process Argv|--crash-reporter-id 131dde13-5e39-4ec4-b299-a3388c8f412a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
9b8hh234:30694863
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448

```

</details>

**Comment by WardenGnaw** [comment]
> -- Sometimes the attach to the default "Standalone Blazor Webassembly App" option works and sometimes it doesn't. I get an "unable to attach to browser" popup with no explanation why.

@phil-allen-msft FYI

> -- The variables in the Variables table of the Run and Debug window sometimes disappear when I change focus to the Watch window and add new variables there. I'm unable to get the Variables window to repopulate when this happens.

This issue would need to be filed on the VS Code team if the locals are disappearing. 

@leslierichardson95 Do you have a minimal repro or a project to test aganist?

Else can you enable logging in the settings page under `engineLogging` for times you are running into the debugging issues?
![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/2e53c7c0-da7f-4b76-ac4b-9fd08289648d)

**Comment by leslierichardson95** [comment]
@phil-allen-msft and @WardenGnaw First, super sorry for not responding to this issue and your repro question sooner!  Second, since enough time has passed since I posted this, every problem I listed above appears to be fixed so I'm going to close this issue.  Thanks!
