### ISSUE TITLE
C# Developement Kit for .NET Android and .NET IOS

### ISSUE THREAD

**Issue by Sheetalpr** [microsoft/vscode-dotnettools#575]
### Describe the Issue

Can we use the Visual Studio Code with C# Development  Kit for .NET-IOS and .NET-Android Solutions?

As of now , we are able to find only .NET-MAUI Project template in Visual Studio Code with latest c# development kit . Are there any plans to include .NET Android and .NET IOS project template in c# development kit for Visual Studio Code in near future?

Looking forward for the support and necessary information.

Thanks !!

**Comment by timheuer** [comment]
Hi @Sheetalpr -- the template list is fixed right now, but you can still use a terminal to create them (even the integrated terminal).  I recommend having the MAUI extension installed (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-maui) and the MAUI workload installed from the SDK, then you can `dotnet new ios` in the terminal and use the templates there in the VS code environment.

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/a20d2351-4c69-4cdb-b077-2da82727c23c)

**Comment by nitishb24** [comment]
@timheuer : Thank you for your response for suggesting the .NET MAUI extension. But we are actually developing native mobile applications using **.NET-Android** and **.NET-IOS** template in Visual Studio MAC and we are not using **.NET-MAUI** since it is used for developing cross platform mobile applications.

Since Visual Studio for MAC is getting deprecated in next year (i.e., August 31st, 2024), we got to know that we have to use **Visual Studio Code** with **C# developer Kit**. Therefore, we wanted to know if we can support native mobile applications (i.e., **.NET-IOS** and **.NET-Android**) using this particular kit.

Looking forward for your support. Thanks!!!

**Comment by timheuer** [comment]
@mauroa said it better than I :-) -- there are other issues that we are tracking about exposing more templates int he 'New Project' flow -- but for now you can still use the CLI to create them and C# Dev Kit will enable you to open them.

**Comment by nitishb24** [comment]
Thank you @timheuer and @mauroa for the explanation, it's clear to me on how to create .NET-Android and .NET-IOS projects using C# development kit in visual studio code.

However, we have some questions from the team which we need to get clarified before using this tool as follows:

1) How to open the Storyboards, Xib's(Designer Classes), Design Layouts and register outlets with .cs file in Xcode via Visual Studio Code.
2) How to open the Design Preview of Android axml file in Visual Studio Code.

**Comment by emaf** [comment]
The storyboards (or Xcode sync) support is tracked by https://github.com/microsoft/vscode-dotnettools/issues/571

**Comment by emaf** [comment]
cc @maddymontaquila

**Comment by jkapsouras** [comment]
Thanks for the update. We'll be waiting

**Comment by lbulegato** [comment]
I have been able to run a simple iOS app created by the command line.
But if I press the debug button it starts an iPad simulator, and I cant find the list of available simulators or real devices.
Plus if I want to run the app on the real device where can I find the bundle signing screen where I can provide the provisioning profile?
This is the Visual Studio screen

![image](https://github.com/microsoft/vscode-dotnettools/assets/9949032/73ffe8b5-a322-4aec-95d9-aa1a8c0b2988)


in general is there a guide on how to use Visual Studio code as a substitute for Visual Studio for .NET iOS / Android development?

**Comment by Sheetalpr** [comment]
I was using GMImagePicker in xamarin.ios solution to select multiple images from gallery. But while migrating the solution from xamarin.ios to net-ios I found that GMImagePicker(A third party plugin) is not supporting .net style project.  Can anyone please suggest me  good alternative for GMImagePicker , so that i can select multiple images in .net-ios solution. 

@jkapsouras 

Looking forward for support and necessary information. Thank you !!

**Comment by mcumming** [comment]
> I have been able to run a simple iOS app created by the command line. But if I press the debug button it starts a random iPAD simulator. Even if I select another device in the bottom line As you can see from screenshot:
> 
> * iphone 14 simulator selected
> * ipad 10th gen, started
>   ![image](https://private-user-images.githubusercontent.com/9949032/278687189-68e0a29c-b0b9-4044-8d35-a38176b95290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzYwNTcsIm5iZiI6MTcwMTE3NTc1NywicGF0aCI6Ii85OTQ5MDMyLzI3ODY4NzE4OS02OGUwYTI5Yy1iMGI5LTQwNDQtOGQzNS1hMzgxNzZiOTUyOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMTI0OTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDkzMDI3NWE3N2Q1ODY2NzIxNzU2YWQ1OWMxMGNmYTAzZTIxYmRkN2VjNmRjZDc2MmQ0ZTE2ZTUyNWUwM2E2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TyXXKAe1t0KvJSpy0xW6x-Y2IIOdRZ4BvdggC2dKr6I)
> 
> Plus if I want to run the app on the real device where can I find the bundle signing screen where I can provide the provisioning profile? This is the Visual Studio screen
> 
> ![image](https://private-user-images.githubusercontent.com/9949032/278670535-73ffe8b5-a322-4aec-95d9-aa1a8c0b2988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzYwNTcsIm5iZiI6MTcwMTE3NTc1NywicGF0aCI6Ii85OTQ5MDMyLzI3ODY3MDUzNS03M2ZmZThiNS1hMzIyLTRhZWMtOTVkOS1hYTFhOGMwYjI5ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMTI0OTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNhMTAwYWVkZjJkZWJkM2Q0YjNmODQ3ZTJiM2E5NDIwM2Y3MDI3YjYzYmJmOGQyMjE2M2Q1MmQ2MGMzNDMxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VqcaTRgjNSAQffJDWcoQvB8atueiWdLg8xfD7l6uIVc)
> 
> in general is there a guide on how to use Visual Studio code as a substitute for Visual Studio for .NET iOS / Android development, I can only find things for MAUI but not for old native xamarin iOS/Android
> 
> Sorry for adding all these questions here but tbh without finding a guide we are acting randomly.

Do you have either the Comet or Meteor extensions installed? Your screenshot leads to me believe that you do. The startup Project and Startup Device selection for the .NET MAUI extension is done via the `{}` Language popup on the right of the status bar.

We do not have a guide for using the extension for non-.NET MAUI development.

**Comment by lbulegato** [comment]
Hi @mcumming thanks a lot

> Do you have either the Comet or Meteor extensions installed? Your screenshot leads to me believe that you do.
Not really, these are the only extensions I have installed
![image](https://github.com/microsoft/vscode-dotnettools/assets/9949032/0321df1f-9c8e-4c45-85d1-0936338c5a50)
are the extensions you mentioned useful to debug to a real device?


> The startup Project and Startup Device selection for the .NET MAUI extension is done via the {} Language popup on the right of the status bar.
Got it, thanks even if it is not so great from a UI/UX perespective

> We do not have a guide for using the extension for non-.NET MAUI development.
Do you know if Visual studio code is really the preferred Microsft choice for .NET not Maui (old Xamarn.iOS/Android approach) development  on Mac?
With my team we need to understand if it makes sense to spend time here or if we need to move to Rider or to something else because it seems we are very far from something we can use every day as a production tool.

**Comment by mauroa** [comment]
I'm closing this issue since .NET iOS and .NET Android projects are currently supported by the .NET MAUI extensions. The additional feature requests have been tracked separately in enhancement tickets, so there's no more action items to do in this issue.
Thanks for your help and feedback.

**Comment by andres-gimenez** [comment]
Lo que está haciendo Microsof desde que creó MAUI es no dar soporte a Xamarin nativo. Cada vez hay menos documentación sobre Xamarin nativo. It feels like you don't want native Xamarin to be used.

**Comment by cosmin-stirbu-gl** [comment]
@mauroa - what is the ticket tracking the support for having code completion in Android .xml files? Also, is there one for the Android designer as well?
