### ISSUE TITLE
[BUG] It requires Visual Studio Editor 2.0.2 or greater

### ISSUE THREAD

**Issue by nightcourage** [microsoft/vscode-dotnettools#577]
Type: <b>Bug</b>

There is no version 2.0.2 in Unity Package Manager. And with this or another reason VS code provide 26 errors related to csproj files of my Unity project. It doesn't work with any of the namespaces, classes or methods at all.

My Unity version is 2022.3.9f1

Again, maybe I didn't understand something but there is no way to follow the requirements of this extension.

Requirements:
Unity 2019 LTS or greater. - DONE
Activated C# Dev Kit extension in Visual Studio Code. - DONE
.NET 7 SDK or greater, the C# Dev Kit will install it if required. - DONE
**Visual Studio Editor Unity package 2.0.20 or greater. - **IMPOSSIBLE****

Extension version: 0.9.1
VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T11:09:17.749Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 5|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id f971cc92-3022-4b54-b6fc-47af264c26aa|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by jbevain** [comment]
@nightcourage for things to work, you need the `Visual Studio Editor` Unity Package version `2.0.20` or above. Please make sure to follow the [getting started guide](https://marketplace.visualstudio.com/items?itemName=visualstudiotoolsforunity.vstuc) of the extension.

**Comment by nightcourage** [comment]
> @nightcourage for things to work, you need the `Visual Studio Editor` Unity Package version `2.0.20` or above. Please make sure to follow the [getting started guide](https://marketplace.visualstudio.com/items?itemName=visualstudiotoolsforunity.vstuc) of the extension.

And that is a problem. There is no 2.0.2 version in UNITY

**Comment by jbevain** [comment]
At this point in time the latest version of the package is `2.0.21` which in terms of version is above `2.0.20` so that meets the requirement:

<img width="912" alt="Screenshot 2023-10-03 at 4 03 59 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/a824d7fe-e3ba-4a35-84ff-867105359c58">

**Comment by nightcourage** [comment]
Nice! And what is your version of Unity?

> At this point in time the latest version of the package is `2.0.21` which in terms of version is above `2.0.20` so that meets the requirement:
> 
> <img alt="Screenshot 2023-10-03 at 4 03 59 PM" width="912" src="https://user-images.githubusercontent.com/79284/272418181-a824d7fe-e3ba-4a35-84ff-867105359c58.png">

Nice! What is your version of Unity? As you can see on my scree I don't have the possibility to upgrade my asset to the required version.

**Comment by jbevain** [comment]
As I said, you need to follow the [getting started guide](http://aka.ms/vscode-unity):

### Unity 2022 and Unity 2023

* Open Unity's Package Manager (Window / Package Manager).
* **Unlock** the Visual Studio Editor package.
* Go to the Version History tab of the Visual Studio Editor package.
* **Update** the Visual Studio Editor package to at least 2.0.20.

It's unfortunate that Unity's package manager makes us jump through those hoops, we're working with Unity on reducing the amount of setup work you need to do.

**Comment by nightcourage** [comment]
You are right. Thanks a lot!

**Comment by jbevain** [comment]
Happy to help!
