### ISSUE TITLE
[BUG] Configuring a logpoint including variables after a breakpoint breaks the debugging session

### ISSUE THREAD

**Issue by sebmenard** [microsoft/vscode-dotnettools#583]
### Describe the Issue

I wanted to configure a logpoint with interpolated variables after a breakpoint. However, when I clicked on "Step Into" several times after the breakpoint, and reached the logpoint, then the debugger would stop working.

The result of the logpoint is not displayed in the debugging console. If the logpoint is configured on a line such as `Console.WriteLine()`, the text passed to this method is not printed on any console (no matter if the `console` is configured to `internalConsole` or `integratedTerminal` in `launch.json`).

The debugging session can still be stopped or restarted but the bug happens again. However, at this point, it's not possible to continue clicking on "Step Into", because the debugger simply hangs.

I'm not sure if I'm posting in the right repository, but this bug does not happen on Visual Studio 2022, which makes me think it's a bug related to Visual Studio Code extensions for C#.

### Steps To Reproduce

1. Create a new C# console project. `dotnet new console` is fine.
2. Replace the contents of `Program.cs` with the following code:

```
int var1 = 0;
int var2 = 0;
int var3 = 0;
int var4 = 0;

var1 += 1;
var2 += 2;
var3 += 3;
var4 += 4;

Console.WriteLine("Logpoint");

Console.WriteLine("End of code");
```

3. Add a logpoint with the following content on line 2: `{var1}`
4. Add a normal breakpoint on line 6.
5. Add a logpoint with the following content on line 11: `{var2}`
6. Start a debugging session. You can use F5, the Run menu, or the Run and Debug view.
7. Notice the first logpoint displayed on the console with the value of `var1` as expected (`0`).
8. Click on "Step Into" several times until reaching the second logpoint on line 11.
9. The debugging session stops working correctly at this point. The content of the logpoint is not displayed on the Debug Console, but only an empty line is. The content of `Console.WriteLine()` is not displayed either.
10. Click on Step Into again. The Variables section on the left of the Run and Debug view is cleared. The Call Stack now displays an error.

### Expected Behavior

The debugging session should continue after the second logpoint, displaying the value of `var2` according to the logpoint and the value passed to the `Console.WriteLine()` method.

Changing the value of the second logpoint on line 11 to any normal text (such as `Logpoint value`) makes the debugging session continue normally.

### Environment Information

- OS: Windows 11
- VS Code version: 1.83.0
- Extension versions: C# Dev Kit 0.5.150, C# 2.5.30, IntelliCode for C# Dev Kit 0.1.26, .NET Runtime Install Tool 1.8.0
- .NET SDK version: 7.0.401
- .NET Runtime version: 7.0.11

**Comment by WardenGnaw** [comment]
This will be fixed in the next release of the C# Extension
