### ISSUE TITLE
[BUG] C# Dev Kit VSC - Console Project on Mac 

### ISSUE THREAD

**Issue by sigadore** [microsoft/vscode-dotnettools#587]
### Describe the Issue

I did a fresh install of C#DevKit extension to a fresh user on my M1 Mac Laptop.  Version 0.5.150, just released.  I walked through the Getting started panel.  During the Create of a new C# Console App, I used the name MyConsole and was confronted with "Run into errors while opening the solution: Error: Stream terminated before required bytes were read."

### Steps To Reproduce

After the above steps and error, I found that Exiting VSC and restarting at least showed a new .sln and Project created.  I did see the heading SOLUTION EXPLORER with only a button [Open Solution] which didn't perform an action when pressed, when I use the Command Prompt and say Open Solution, I get the above error message "Run into errors while opening the solution: Error: Stream terminated before required bytes were read."
Looking at the Generated Solution File:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```
It appears to be missing the reference to the Project.
In The Terminal, I issued and received 
```
% dotnet sln MyConsole.sln add MyConsole/MyConsole.csproj 
Project `MyConsole/MyConsole.csproj` added to the solution.
```

I selected the` Program.cs` file in the project and clicked the |> RUN/DEBUG icon I was provided with a launch.json file and no configurations (after I selected C#), Clicking on the Show all automatic debug configurations Resulted in a error similar to all of the other ones "Unable to provide debug configurations: Stream terminated before required bytes were read."

Clearly, I am missing something fundamental in either the C#DevKit or other dependent extensions (I recall the launch.json in .vscode comes from the C# extension itself), maybe something not right there.

I have uninstalled all extensions and reinstalled the C#DevKit one with identical results.  I am running an ARM Mac, just FYI, but didn't have problems in an earlier install just with the C# extension in a separate Mac User.

### Expected Behavior

I expect the proper files supporting a Console Project to be correctly populated and for one or more of the extensions to not have their Stream terminated before required bytes were read.
I was hoping to see
"Hello World" printed out as well.

### Environment Information

OS: Mac on an M1 Laptop running MacOS Sonoma 14.0 (23A344)
VS Code: version 1.83.0
C#DevKit v0.5.150
C# v2.5.30
.Net Runtime Install Tool v1.8.0
IntelliCode for C# Dev Kit v0.1.26
--
No other extensions
All are at their latest update available.

**Comment by sigadore** [comment]
After restarting VSC with the extension installed and enabled, I went looking through the Developer: Logs* and found the following which appears to be concerning / relevant to an unexpected Stream termination.  Hope it helps.
```
10/06/2023 21:31:41 Pacific Standard Time : Information : Local timezone is (UTC-08:00) Pacific Time (Los Angeles)
10/06/2023 21:31:41 Pacific Standard Time : Information : Starting hub controller '/Users/siggy/.vscode/extensions/ms-dotnettools.csdevkit-0.5.150-darwin-arm64/components/vs-green-server/platforms/darwin-arm64/node_modules/@microsoft/servicehub-controller-net60.darwin-arm64/Microsoft.ServiceHub.Controller 4fbf24b97d /ControllerCooldownTimeout:30000 "/TelemetrySession:{\"TelemetryLevel\":\"all\",\"IsOptedIn\":false,\"HostName\":\"Default\",\"AppInsightsInstrumentationKey\":null,\"AsimovInstrumentationKey\":null,\"CollectorApiKey\":\"0c6ae279ed8443289764825290e4f9e2-1a736e7c-1324-4338-be46-fc2a58ae4d14-7255\",\"AppId\":1010,\"UserId\":\"beb57540-0d16-474b-84d4-f2da421486a1\",\"Id\":\"b8696d06-6fd7-4cc5-848b-fdcaf72dff2c1696653100333\",\"ProcessStartTime\":133411267012304950,\"SkuName\":null,\"VSExeVersion\":null,\"BucketFiltersToEnableWatsonForFaults\":[],\"BucketFiltersToAddDumpsToFaults\":[]}"'
10/06/2023 21:31:41 Pacific Standard Time : Information : Setting environment variable 'ServiceHubClientProcessVersion' to '' in the "/Users/siggy/.vscode/extensions/ms-dotnettools.csdevkit-0.5.150-darwin-arm64/components/vs-green-server/platforms/darwin-arm64/node_modules/@microsoft/servicehub-controller-net60.darwin-arm64/Microsoft.ServiceHub.Controller" process.
10/06/2023 21:31:41 Pacific Standard Time : Warning : Controller terminated with exit code '134'. Signaling cancellation.
10/06/2023 21:31:41 Pacific Standard Time : Error : Error starting hub controller: Microsoft.ServiceHub.Client.ControllerConnectionException: Controller terminated before accepting connections. Exit code: 134. HResult='-2146233079' 
   at Microsoft.ServiceHub.Client.HubControllerClient.StartAsync(ServiceHubConfig config, String clientName, CancellationToken cancellationToken)
```

**Comment by tmeschter** [comment]
@sigadore Are you able to reproduce this problem? If so, could you provide the output of the "C#", "C# Dev Kit", and "Projects" output windows?

**Comment by sigadore** [comment]
I was just pushed .NET Runtime Install Tool  v1.8.1 as an update and after reload, the problems around Solution, etc. for the existing project have resolved and I am able to follow a simple Console Project in a Solution.  I just completed an upgrade to C# v2.6.24 complete its install.  I am still at the C#DevKit v0.5.150 level.

I will run a fresh test from scratch and verify that my problem is resolved, or I will post the info you (@tmeschter) mention above.

**Comment by sigadore** [comment]
Ok.  I have confirmed that with the latest updates to C# and .Net Runtime Extensions the original issues that I faced are gone.  It seems to not have been the *C# Dev Kit* extension, since that release did not change.
