### ISSUE TITLE
[BUG] [MAUI | Blazor Hybrid App] [VSC] Debugger doesn't launch the application

### ISSUE THREAD

**Issue by jmgalzate** [microsoft/vscode-dotnettools#589]
### Describe the Issue

The VS Code Debug doesn't launch the application package. 

It builds the application but the app is never launched. The output message is "No debug target available, skipping debugging."

I tried to look for information on the WEB and ask Copilot, but nothing has worked yet for me. 

These two could be related issues: 
#411 
#244 

This is the Copilot suggestion: 

To add the "program" key in the launch configuration, however, VSC rejects the suggestion indicating the "program" is not a valid parameter for this kind of configuration.

```
{
    "name": ".NET MAUI",
    "type": "maui",
    "request": "launch",
    "preLaunchTask": "maui: Build",
    "targetFramework": "net7.0-maccatalyst",
    "project": "${workspaceFolder}/DispatchesApp/DispatchesApp.csproj",
    "configuration": "Debug",
    "program": "${workspaceFolder}/DispatchesApp/bin/Debug/net7.0-maccatalyst/DispatchesApp.app/Contents/MacOS/DispatchesApp"
}
```

### Steps To Reproduce

1. Click on the Run and Debug icon (vsc)
2. Choosing the configuration (profile) created in the launch.json file
3. Click on Start Debugging (f5) button
4. The application is build

> <img width="1086" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/88916499/11602aec-5fa2-473b-94d9-14ffe2f609cc">

5. The application is not launched and the error message appears: "No debug target available, skipping debugging"

> <img width="1203" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/88916499/651c47fc-473a-4268-9fb0-7d91ae3d001d">

6. The process finishes. 

### Expected Behavior

The application is launched and the debugger receives my instructions for break in some steps. 

### Environment Information

- OS

> masOS Sonoma Version 14.0
> Chip Apple M2

- VSC version: 

> Version: 1.83.0 (Universal)
> Commit: e7e037083ff4455cf320e344325dacb480062c3c
> Date: 2023-10-03T16:13:15.449Z
> Electron: 25.8.4
> ElectronBuildId: 24154031
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Darwin arm64 23.0.0

- launch.json for VSCode 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "targetFramework": "net7.0-maccatalyst",
            "project": "${workspaceFolder}/DispatchesApp/DispatchesApp.csproj",
            "configuration": "Debug"
        }
    ]
}
```

**Comment by mauroa** [comment]
Assigning to @tondat for initial investigation/interaction since it looks like related to the launch profiles/configuration.

**Comment by Markz878** [comment]
Same problem here still, no upvotes on this and issue just sitting here.. What is going on? Is this VS Code extension already abandoned?

**Comment by mauroa** [comment]
Hi @Markz878 @jmgalzate, could you please confirm if you are selecting a debug target from the '{}' at the bottom right of VS Code? That's the entry point for the .NET MAUI extension to select debug target and startup project.

Also, for now .NET MAUI only supports debugging through F5 or Run > Start Debugging.

Finally, you can try removing your launch.json to see if it makes any difference, since you shouldn't need it unless you want to define custom configurations, which is not the case according to what's provided above.

Please let me know if after updating to latest .NET MAUI pre-release and following the recommendations above, you can get unblocked.

Thanks for your help.

**Comment by Markz878** [comment]
I got it working by using F5 or Run > Start Debugging. The Solution Explorer -> Right-click project -> Debug -> Start New Instance does not work, which was the initial problem. But at least it runs now.

Now we just need hot reload (also for Blazor Hybrid) and the extension will be usable.
Thanks!

**Comment by mauroa** [comment]
Thanks for the confirmation @Markz878. We are working on adding support for all of that, from build and debug support on right click to Hot Reload, we'll let users know when it's ready to give it a try.
Thanks for your feedback and help.
