### ISSUE TITLE
Cannot disable auto-injected launch

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vscode-dotnettools#590]
Type: <b>Bug</b>

I have a launch.json with my project. The C# Dev Kit is attempting to auto-inject a random suggestion into the list, which is (a) duplicated, (b) doesn't work, (c) unnecessary.

I cannot find any way to disable this behavior, which feels like a bug to me.

Extension version: 0.5.150
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (31.80GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+xunit/home/bradwilson/dev/xunit/xunit --remote=wsl+xunit --crash-reporter-id 94eb3f2c-b094-4674-8242-c6bb68f0703d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: xunit|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3700)|
|Memory (System)|31.30GB (22.68GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
pythonmpsinfo:30842941
dsvsc015:30845448

```

</details>

**Comment by bradwilson** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/16944/704ceec1-5e55-403b-b108-e06a48e4cd7d)

**Comment by bradwilson** [comment]
Source repository: https://github.com/xunit/xunit

Launch.json file: https://github.com/xunit/xunit/blob/04acf4405a74e1c5a91b096893daf26209b7116d/.vscode/launch.json

**Comment by tmeschter** [comment]
@bradwilson The C# Dev Kit launch/debug experience is meant to be closer to that of Visual Studio with broader support for launchSettings.json (and reasonable default behavior for projects that don't define that file). Most users should not need a launch.json at all--only if they need/want very fine control over launch.

That being said we're looking into future UX improvements that will cut down on the size of the list and make it easier to find what you care about.

**Comment by bradwilson** [comment]
@tmeschter So you're saying there's no way to disable the auto-injection today? Can this issue serve as the request to add that as a feature?

**Comment by gregg-miskelly** [comment]
There is no "auto injection" by which I mean an entry winding up in that list just because you have C# Dev Kit installed. 

VS Code has many gestures to start debugging, so this list might be incomplete, but here are the gestures that I know of that can add a dynamic configuration to your list of configurations:
1. Your workspace didn't have a launch.json at the time you tried to do a debug launch
-or-
2. The 'Debug: Select and Start Debugging' command was executed, and you picked the 'C#' project+launch profile.
-or-
3. From the debug configuration selector dropdown, you selected 'C#...' and then picked a project+launch profile

**Comment by bradwilson** [comment]
None of those things were true.

That said, while this was reliably reproducible for me, today when I launched Code against this solution, the C# Dev Kit downloaded new dependencies, and now it has stopped reproducing. So perhaps this was an issue that got fixed recently. I'll close this for now.
