### ISSUE TITLE
[BUG] Unity Extension: Debugging Editor Code Issue

### ISSUE THREAD

**Issue by Novack** [microsoft/vscode-dotnettools#592]
### Describe the Issue

With the debugger attached to Unity, during debugging sessions is common -although inconsistent- that pressing F5 in vscode to continue, ends up sending a "Play" command to Unity. This ends up starting a Play session in Unity.

However if I am debugging Editor code, an unnintended Play can be severe and result in the loss of data.

### Steps To Reproduce

I have been able to reproduce this on Unity 2019.1.31f1
Is inconsistent, but easy to reproduce:
-Have some editor code to debug.
-Set a breakpoint and run the code from a menu or editor button.
-When the breakpoint is reached, press F10 or step out.
-Press F5 or continue.

Often the Editor will start playing the game.

### Expected Behavior

Hitting "Continue" or pressing "F5" in vscode should not make the Unity Editor start a play session. Either the debugger needs to be smart enough to understand the context, or find a different way to unpause the Unity session.

### Environment Information

- Unity 2019.1.31f1

- VSCodium Version: 1.82.2
Release: 23257
Commit: a5004432af6600c99fa4f918a3f2f8df44df71e6
Date: 2023-09-14T18:43:58.720Z
Electron: 25.8.1
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

- Unity Extension v0.9.1

**Comment by jbevain** [comment]
![what](https://i.giphy.com/media/l3q2K5jinAlChoCLS/giphy.webp)

Now that's extremely curious. I don't think we have anything in the VSCode debugger that has the ability to tell Unity to enter “PlayMode” directly. So this must be a side effect of something (maybe evaluating something triggers Unity to enter Play Mode?).

If you can find a way to reliably reproduce this, I'd love to investigate.

**Comment by Novack** [comment]
Ok looks like I found the reason, but still not quite grasp the organic conditions for this to happen.
Seems like a focus issue: F10 in Unity opens the video recorder, which is in fact launching the play session.

Will pay more attention to detect why this happen sometimes during debugging but looks like if there is a stepped out line that takes some time, Unity will catch the next F10 during that time (and then start the recorder and thus init a play session).

Also worth mentioning, when the breakpoint is hit, the focus remains in Unity until you manually go to vscode.

All in all looks like this report is a negative @jbevain I will try to understand better the conditions for it to happen and create a new one. Thanks and sorry to bother with a false positive.

**Comment by jbevain** [comment]
Wow that is indeed pretty curious. Sounds good, thanks for iterating on this!
