### ISSUE TITLE
No Debug mode is too visually similar to debug mode

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#594]
### Describe the Issue

Hitting the "run project associated with this file" OR "run without debugging" from VS Code menu starts a debugging session instead of just running

![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/af478757-fb3a-4937-8269-505a662d34fc)

![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/2016c77e-2573-4d31-81b2-5d29da53f6e2)

### Steps To Reproduce

1. Create a simple console app
2. Have Program.cs file open 
3. Click "Run project associated with this file" in the menu in the top right

![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/21140c03-3360-4f50-85c3-cab703988ad1)

### Expected Behavior

I would expect this to behave the same way as if I were in the project folder in the terminal and ran "dotnet run". 
1. Project runs
2. No debug toolbar appears
3. Focus goes to "Terminal" not "Debug Console"

### Environment Information

- Windows 11
- C# Dev Kit: v0.5.150
- C#: v2.5.30

**Comment by gregg-miskelly** [comment]
This bug is incorrect - we aren't debugging. However, VS Code makes almost no distinction in the UI between debugging and not debugging. The only way you can tell:

1. The pause button does nothing in 'noDebug' mode
2. In 'noDebug' mode, the .NET debugger will not print modules to the debug console

Related issues:
* https://github.com/dotnet/vscode-csharp/issues/5704
* https://github.com/dotnet/vscode-csharp/issues/6516

**Comment by claudiaregio** [comment]
I wrote it under "expected behavior", but the expected experience is identical to what I'm seeing Python do here: https://code.visualstudio.com/docs/python/python-tutorial#_run-hello-world

**Comment by gregg-miskelly** [comment]
@claudiaregio Python has multiple ways to "Run without debugging". Some of their gestures just directly run the target script in the terminal, while others will use the VS Code APIs and would have the same problem as in this issue with there being very little distinction between run with and without debugging.

**Comment by gregg-miskelly** [comment]
I opened two more issues relating to this:
* https://github.com/microsoft/vscode-dotnettools/issues/606
* https://github.com/microsoft/vscode/issues/195417

I think once we have fixes for those two problems and https://github.com/dotnet/vscode-csharp/issues/6516, this scenario should be much better. So I am closing this issue.
