### ISSUE TITLE
[BUG] Microsoft.ServiceHub.Controller of wrong platform is selected at Raspberry Pi

### ISSUE THREAD

**Issue by prochan2** [microsoft/vscode-dotnettools#597]
### Describe the Issue

I'm running VS Code in Home Assistant on Raspberry Pi 4. (https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/)

After installing .NET 7 SDK and C# DevKit with all dependencies, the startup o C# DevKit fails:

```
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
Failed at 'Spawn .NET server' (15ms) with error: Error: ENOENT: no such file or directory, chmod '/data/vscode/extensions/ms-dotnettools.csdevkit-0.5.150/components/vs-green-server/platforms/win32-ia32/node_modules/@microsoft/servicehub-controller-net60.win32-ia32/Microsoft.ServiceHub.Controller'
Failed at 'Clear environment' (33ms) with error: Error: ENOENT: no such file or directory, chmod '/data/vscode/extensions/ms-dotnettools.csdevkit-0.5.150/components/vs-green-server/platforms/win32-ia32/node_modules/@microsoft/servicehub-controller-net60.win32-ia32/Microsoft.ServiceHub.Controller'
Failed at 'Open a solution with environment service' (34ms) with error: Error: ENOENT: no such file or directory, chmod '/data/vscode/extensions/ms-dotnettools.csdevkit-0.5.150/components/vs-green-server/platforms/win32-ia32/node_modules/@microsoft/servicehub-controller-net60.win32-ia32/Microsoft.ServiceHub.Controller'
Failed at 'Open a solution' (64ms) with error: SolutionOpenError: Run into errors while opening the solution: Error: ENOENT: no such file or directory, chmod '/data/vscode/extensions/ms-dotnettools.csdevkit-0.5.150/components/vs-green-server/platforms/win32-ia32/node_modules/@microsoft/servicehub-controller-net60.win32-ia32/Microsoft.ServiceHub.Controller'
Failed to open solution SolutionOpenError: Run into errors while opening the solution: Error: ENOENT: no such file or directory, chmod '/data/vscode/extensions/ms-dotnettools.csdevkit-0.5.150/components/vs-green-server/platforms/win32-ia32/node_modules/@microsoft/servicehub-controller-net60.win32-ia32/Microsoft.ServiceHub.Controller'
```

The extension installed is `ms-dotnettools.csdevkit-0.5.150@linux-arm64.vsix`, but, according to the log, the `win32-ia32` folder of  the `Microsoft.ServiceHub.Controller` is selected, instead of `linux-arm64`.

If this combination is difficult to investigate, is there at least a workaround, that would force the `linux-arm64` folder to be used?

### Steps To Reproduce

1. Have Home Assistant installed on Raspberry Pi 4: https://www.home-assistant.io/installation/raspberrypi
2. Install Studio Code Server add-on: https://github.com/hassio-addons/addon-vscode
3. Edit the Studio Code Server add-on configuration to have .NET 7 installed:

```yaml
packages: []
init_commands:
  - apt-get update
  - >-
    apt-get install -y apt-transport-https libunwind8 libunwind8-dev gettext
    libicu-dev libcurl4-openssl-dev libssl-dev uuid-dev
  - >-
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel
    7.0
  - echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.zshrc
  - echo 'export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools' >> ~/.zshrc
  - echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
  - echo 'export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools' >> ~/.bashrc
  - source ~/.bashrc
  - dotnet --info
  - dotnet --list-sdks
  - dotnet --list-runtimes
  - dotnet tool install -g JoySoftware.NetDaemon.HassModel.CodeGen
log_level: info
config_path: /
```

4. Open the VS Code within Home Assistant, and install C# DevKit extension.
5. Open any C# project.

### Expected Behavior

The C# DevKit should open the C# project/solution without errors. In the described step, the `linux-arm64` platform should be used.

### Environment Information

- Home Assistant 2023.10.1
- Studio Code Server add-on
- .NET SDK 7.0
- C# DevKit 0.5.150

**Comment by AArnott** [comment]
Sorry for the error, @prochan2. I'm trying to understand what would cause this. Could you try this command for me?

```
rm -Rf /data/vscode/extensions/ms-dotnettools.csdevkit-0.5.150/cache
```

This will remove a cache file and force C# Dev Kit to re-calculate where the appropriate files for your architecture are to load.
