### ISSUE TITLE
[SUGGESTION] Add option to build using csproj instead of solution (as it was)

### ISSUE THREAD

**Issue by gustavoale-saires** [microsoft/vscode-dotnettools#598]
### Describe the feature you'd like

In version 0.4.10 whenever I want to build a project or run an unit test the extension will use the following command to build:
`dotnet build <csproj file> /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary`
This was working fine, only the desired project and its dependencies were compiled. 

But now with version 0.5.150 the build command issued by C# Dev Kit is:
` dotnet build <solution file> /target:<project directory> /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary`

This command result in the **entire solution** to be compiled, not only the desired project. The first issue is the increase in the time to run unit tests, because now a bunch of unrelated code is compiled altogether every time a test in modified. The second issue is solutions may contain projects aimed to other platform/OS preventing the compilation of other projects inside the solution.

### Alternatives considered

Let the user decide if the compilation task uses the entire solution or a single project file. 

### Environment Information

- OS: Fedora Linux 38
- VSCode: 1.82.0
- Extension version: 0.5.150

**Comment by timheuer** [comment]
@gustavoale-saires are you initiating this from right-click Build on solution view? Are you actually seeing that both(all) projects being built? becuase the `/target:<proj>` should be directing to build the project only.

**Comment by gustavoale-saires** [comment]
Building from solution view or running from testing tab resulted in the entire solution to be built. But now something updated in my system and I cannot reproduce the issue anymore.. This issue haunted me for days.

**Comment by timheuer** [comment]
Interesting, the context of the command matters of course, right-click on Solution will build entire solution, but per-project will build with the target property passed in.  In my multi-solution, this only builds the targeted project when doing it that way.  If you are no longer seeing this, okay if we close it out for now, and if you get a solid repro back we can re-open and take a look (would be great if you capture it somehow as well)?

**Comment by gustavoale-saires** [comment]
Ok, I will close the issue. If the issue returns to occur I will re-open it and capture enough evidence and properly inform the lib/software versions. Thanks for your help
