### ISSUE TITLE
[BUG] Run all tests in a file

### ISSUE THREAD

**Issue by Greg-Uzelac** [microsoft/vscode-dotnettools#60]
### Describe the Issue

Per the release notes animated gifs (https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2023/06/csdevkit-testing-resized.gif), I should see run/debug icons to the right of the .cs test filenames. I don't see them.
![image](https://github.com/microsoft/vscode-dotnettools/assets/128492077/21338087-7410-45c7-9f5b-792fdfc37b01)
I do have run/debug icons for each test in the file. I just don't see a way to run all the tests in the file. Or all tests in the project (if that's even supported).

### Steps To Reproduce

Install C# Dev Kit extension
Wait for everything to upgrade
Restart VS Code
Open a .sln folder
Navigate to the Test project
See Run/Debug buttons inside the cs file, one per test
Don't see the ability to run all tests in a cs file

### Expected Behavior

See run/debug icons on each filename, to the right of the filename

### Environment Information

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19042 Build 19042
Processor	11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz, 2496 Mhz, 8 Core(s), 16 Logical Processor(s)
Secure Boot State	On
Windows Directory	C:\windows
System Directory	C:\windows\system32
Locale	United States
Installed Physical Memory (RAM)	32.0 GB

![image](https://github.com/microsoft/vscode-dotnettools/assets/128492077/9ffdd781-dee4-4f65-b5d0-796d37e75be5)

**Comment by Greg-Uzelac** [comment]
I just noticed that that project doesn't build in VS Code (it does build in VS):
DW.xaml.cs(33,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [SL.csproj]
DDW.xaml.cs(35,13): error CS0103: The name 'Description' does not exist in the current context [SL.csproj]
DDW.xaml.cs(36,13): error CS0103: The name 'Link' does not exist in the current context [SL.csproj]
IDW.xaml.cs(58,13): error CS0103: The name 'ProgressText' does not exist in the current context [SL.csproj]

I'll see if I can figure out why it doesn't build. in VS Code.

**Comment by timheuer** [comment]
@Greg-Uzelac your picture is the Solution Explorer view -- you need to use the Test Explorer view in VS Code and it will show discovered tests using the test platform:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/e3ceaf89-1ab3-4b3f-9315-b5164816fd3d)

**Comment by Greg-Uzelac** [comment]
Thank you, Tim
