### ISSUE TITLE
Doesn't support assemblies in solution explorer

### ISSUE THREAD

**Issue by drizztdourden08** [microsoft/vscode-dotnettools#602]
Edit: this is for the unity new extension. It doesn't look like it is specified here on github even though I chose it on the Vscode report.

Type: <b>Feature Request</b>

Hi,

The title pretty much says it all. Solution Explorer says "Not supported" on all of my assemblies. I have a lot of them for my game and it seems it doesn't detect any of them.

It would be a nice addition. It doesn't prevent it from working though as the normal explorer can do the job with just folder structure.

also, error message is:
`[warning] The project file 'D:\GameProjects\RTLD_2\Mono.Main.csproj' is in unsupported format (for example, a traditional .NET Framework project). It need be converted to new SDK style to work in C# Dev Kit.`

unity auto-generate those so not sure there's anything we can do about it right now.

thanks.

![image](https://github.com/microsoft/vscode-dotnettools/assets/36481532/5297c366-1840-4d0d-9e8f-9171a84001e0)

Extension version: 0.9.2
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by jbevain** [comment]
> unity auto-generate those so not sure there's anything we can do about it right now.

Based on the error, I'd say the projects are not properly generated by Unity, which is often the case when your Unity project is not properly configured.

Please make sure you follow the steps of the [Getting Started section of the extension](https://aka.ms/vscode-unity).

This will ensure your projects are properly generated.

**Comment by jbevain** [comment]
Closing this as it's very likely a setup issue. Let us know if despite setting up everything you're still seeing an issue. Thanks!
