### ISSUE TITLE
[BUG] Adding a folder deletes some project configurations

### ISSUE THREAD

**Issue by BrianCArnold** [microsoft/vscode-dotnettools#609]
### Describe the Issue

I opened my SLN with C# Dev Kit, and adding a single folder to my solution. 

The extension also inexplicably moved this down two lines
```
         Release|Any CPU = Release|Any CPU
         Release|x64 = Release|x64
```

And then promptly deleted every single project configuration for `Release|Any` and `Release|x64` across all 398 projects in the solution.

### Steps To Reproduce

1. Create empty directory
2. Create a file called `example.sln` with exactly these contents:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "example", "example.csproj", "{18D1E89D-EC88-4D32-8FFA-1F9FB5B0A4B9}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Long|x64 = Long|x64
		Longer|x64 = Longer|x64
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{18D1E89D-EC88-4D32-8FFA-1F9FB5B0A4B9}.Longer|x64.ActiveCfg = Longer|x64
		{18D1E89D-EC88-4D32-8FFA-1F9FB5B0A4B9}.Longer|x64.Build.0 = Longer|x64
		{18D1E89D-EC88-4D32-8FFA-1F9FB5B0A4B9}.Long|x64.ActiveCfg = Long|x64
		{18D1E89D-EC88-4D32-8FFA-1F9FB5B0A4B9}.Long|x64.Build.0 = Long|x64
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```
3. Create a file called `example.csproj` with exactly these contents:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
</Project>
```
4. Open the example.sln solution in the Solution Explorer with C# Dev Kit in Visual Studio Code 
5. Right Click on the solution (not the project) and click "New Solution Folder"
  * (alternate) Click on the folder icon next to the solution to create a new solution folder. ![image](https://github.com/microsoft/vscode-dotnettools/assets/38593283/f60610bd-2569-49f4-9922-ba08efb92f99)
6. Type any name for the solution folder and press enter

Now all of the project configurations for `Long` have been deleted entirely, leaving only the project configurations for `Longer`.

This only appears to occur when `longerName.StartsWith(shorterName)`

### Expected Behavior

It shouldn't delete all project configurations that are a substring of other project configurations.

### Environment Information

Name: VSCode
Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:11:49.843Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.6-arch2-1

Name: C#
Id: ms-dotnettools.csharp
Description: Base language support for C#
Version: 2.6.24
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 0.5.150
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit

**Comment by BrianCArnold** [comment]
Is there any plan on making the official C# Dev Kit not corrupt my entire solution configuration _every single time_ I try to do almost anything to the solution itself, like add solution folders, move projects into solution folders, etc?

**Comment by BrianCArnold** [comment]
I literally haven't been able to upgrade my C# extension for 7 months because of this bug, because it insists on destroying my entire solution every time I load it. Will 2.x branch of the C# extension ever have this fixed?

**Comment by richardstanton** [comment]
Hello Brian, sorry this bug slipped through the cracks, I am investigating it now.

**Comment by BrianCArnold** [comment]
Thanks, looking forward to upgrading to the 2.x version of the plugin.

**Comment by richardstanton** [comment]
The fix for the bug is complete and is expected to be in the next update of the extension. Thank you for the very comprehensive repro steps.

**Comment by richardstanton** [comment]
The fix is in the current version of the extension.
