### ISSUE TITLE
[BUG] Analyzers and code fixes not working in C# Dev Kit?

### ISSUE THREAD

**Issue by DaRosenberg** [microsoft/vscode-dotnettools#61]
### Describe the Issue

Not sure if this is exposing a bug or just a missing feature for now. Can you clarify whether analyzers and code fixes should be working yet or not?

### Steps To Reproduce

Works:
- Analyzers are run during build, and issues surfaced as problems (errors and warnings)

Does NOT work:
- Analyzers do not run automatically (neither for solution nor for open documents)
- No command to run analyzers imperatively either
- Detected issues are highlighted in source (squigglies) but no fixes appear 
- No settings to enable analyzers or control analysis behavior

### Expected Behavior

I expect analyzers functionality to be on par with Visual Studio, or at least on par with the previous OmniSharp-powered C# extension.

### Environment Information

- OS: macOS Ventura
- VS Code: 1.78.2
- Extension: C# Dev Kit v0.1.8

**Comment by timheuer** [comment]
Hi @DaRosenberg they should be working for you.  Can you share any screenshots?  Also can you confirm you are on the pre-release version of the C# extension as well?

**Comment by CyrusNajmabadi** [comment]
Can we port this to Roslyn?  I can't get to these issues in the MS org.

**Comment by karl-sjogren** [comment]
I'm seeing the same problem, also on macOS Ventura (on an Intel Mac). This is in a .NET 7.0 project running with SDK 7.0.302.

With "C# Dev Kit" and prerelease of "C#".

![image](https://github.com/microsoft/vscode-dotnettools/assets/875092/35c78a23-7cf3-4787-a268-85a7e11693de)

And if I disable "C# Dev Kit" and go back to the release version of "C#".

![image](https://github.com/microsoft/vscode-dotnettools/assets/875092/f520e933-bcf7-4eae-9dcd-281722349d10)

I also see this after loading a new project which isn't there with "C# Dev Kit" (though maybe i shouldn't be, I don't know).

![image](https://github.com/microsoft/vscode-dotnettools/assets/875092/590e7440-e7c3-4391-8f8f-789323fbedde)

I have the following analyzer packages in my solution (using `Directory.Build.props`).

```xml
<ItemGroup>
  <PackageReference Include="Roslynator.Analyzers" Version="4.3.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.3.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.6.0">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.6.0">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
  <PackageReference Include="Karls.Analyzers" Version="0.3.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
  </PackageReference>
</ItemGroup>
```

And then I'm enabling the analyzers through `.editorconfig`.

**Comment by karl-sjogren** [comment]
I checked this out on a windows machine as well and I have the same problem there with the above setup. I did however manage to get the analyzers working for a bit when I created a new .cs file though without any code fixes. If I close VS Code and open the same solution again though the new file doesn't have any warnings reported.

**Comment by ckasabula** [comment]
I am seeing the same. Problems view has nothing in it. Switching back to release version of C# extension restores them. Let me know if I can provide anything to help.

**Comment by CyrusNajmabadi** [comment]
Having trouble repro'ing this:

![image](https://github.com/microsoft/vscode-dotnettools/assets/4564579/636f94cf-87c9-4f2b-acb1-9117a14d3c76)

![image](https://github.com/microsoft/vscode-dotnettools/assets/4564579/a798e9ea-9e00-4a0d-8e13-2cc45018be32)

Continuing to investigate.

**Comment by karl-sjogren** [comment]
https://github.com/karl-sjogren/vscode-dotnettools-repro-61

That is a minimal repro where the analyzer RCS1046 from Roslynator works fine using the omnisharp extension but not using C# Dev Kit. The method `Program.WaitABit()` should have an "async" suffix according to the analyzer. I've included some screenshots in the repository that shows how it looks for me.

**Comment by karl-sjogren** [comment]
Hm, I left the code window open for several minutes in the background and when I looked back at it the analyzer had loaded with Dev Kit enabled. I then restarted Code to see if it would work again but after 5 minutes now nothing is showing. I am however seeing this in the output log for the C# extension with the above project.

> [Warn  - 10:52:54 PM] [LanguageServerHost]Ignoring diagnostics request for untracked document: file:///x:/Github/vscode-dotnettools-repro-61/Program.cs

If I create a new file and copy the code over to it, then analyzers work in that file, until I restart Code and then I get the same warning, bur for my new file..

> [Warn  - 10:54:44 PM] [LanguageServerHost]Ignoring diagnostics request for untracked document: file:///x:/Github/vscode-dotnettools-repro-61/OtherFile.cs

This is the whole log after restarting Code and opening both files.

```
Dotnet path: c:\Users\Karl\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.5\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
[Info  - 10:54:41 PM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\7.0.302
[Info  - 10:54:41 PM] [LanguageServerProjectSystem]Loading x:\Github\vscode-dotnettools-repro-61\vscode-dotnettools-repro-61.sln...
[Info  - 10:54:43 PM] [LanguageServerProjectSystem]Successfully completed load of x:\Github\vscode-dotnettools-repro-61\vscode-dotnettools-repro-61.csproj
[Info  - 10:54:43 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:01.3546912
[Warn  - 10:54:44 PM] [LanguageServerHost]Ignoring diagnostics request for untracked document: file:///x:/Github/vscode-dotnettools-repro-61/OtherFile.cs
[Warn  - 10:55:14 PM] [LanguageServerHost]Ignoring diagnostics request for untracked document: file:///x:/Github/vscode-dotnettools-repro-61/Program.cs
```

I've added `OtherFile.cs` to the sample repo as well.

**Comment by CyrusNajmabadi** [comment]
Thanks! pulling that down :)

**Comment by mavasani** [comment]
@karl-sjogren I am unable to reproduce the issue with your repro project, I get the errors as soon as I open the files.

I have C# extension _v2.0.248_ and C# dev kit _v0.1.103_ installed locally.

![image](https://github.com/microsoft/vscode-dotnettools/assets/10605811/b5faab95-06cb-4bd7-b754-5c131245a145)

**Comment by mavasani** [comment]
> I am seeing the same. Problems view has nothing in it. Switching back to release version of C# extension restores them. Let me know if I can provide anything to help.

@ckasabula If you are able to provide a repro project, that would be a great help. Thanks!

**Comment by karl-sjogren** [comment]
I just checked this again and now the analyzer seems to be working in my repro as you say.

I'll try working with the dev kit enabled in my main project today and see if it works as expected there as well.

**Comment by ckasabula** [comment]
@mavasani I checked this again and I now see output under problems view.
