### ISSUE TITLE
[BUG] Namespace defaults to base namespace when adding with C# DevKit

### ISSUE THREAD

**Issue by svdbrg** [microsoft/vscode-dotnettools#611]
### Describe the Issue

When creating a new class or interface file, the namespace of the created file does not reflect the folder structure, but rather just adds the base namespace of the app.

### Steps To Reproduce

1. In a dotnet app, right click a folder and choose "Add New File..."
2. Select Class and give it a random name
3. Namespace is "wrong"

### Expected Behavior

The namespace of the new file should reflect the folder structure it's been created in.

### Environment Information

- OS: Windows 11
- VS Code Version: 1.83.1
- Extension Version: v0.6.3

**Comment by kvenkatrajan** [comment]
Related request : https://github.com/dotnet/templating/issues/6010

**Comment by smitpatel** [comment]
Fixed in version 1.9.55
