### ISSUE TITLE
Impossible de démarrer le débogage MAUI

### ISSUE THREAD

**Issue by vngounou26** [microsoft/vscode-dotnettools#619]
Type: <b>Bug</b>

j'ai Crée un nouveau projet dotnet MAUI dans VSCode ave le C# dev kit. tout de suite je reçoi la notification comme quoi je doit accepter les licences androids. Je clique sur accepter et ça progresse sans jamais s'arreter. Et quand je lance le debogage on me demande d'accepter les licences Android

Extension version: 0.4.9
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (2.16GB free)|
|Process Argv|--crash-reporter-id 843e4381-e452-414c-8361-228427018c27|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448
pythonregdiag:30859691
pyreplss2:30858576
h48ei257:30860818

```

</details>

**Comment by emaf** [comment]
@vngounou26 Could you check if this works for you https://github.com/microsoft/vscode-dotnettools/issues/249#issuecomment-1752438222?

cc @tondat

**Comment by vngounou26** [comment]
> @vngounou26 Could you check if this works for you [#249 (comment)](https://github.com/microsoft/vscode-dotnettools/issues/249#issuecomment-1752438222)?
> 
> cc @tondat

yes it's work for me. Thank you
