### ISSUE TITLE
[SUGGESTION] Support Source Link with unit test debugging (or document how to set it up)

### ISSUE THREAD

**Issue by tillig** [microsoft/vscode-dotnettools#623]
### Describe the feature you'd like

While the `dotnet.unitTestDebuggingOptions` settings appear to allow for Source Link (to let me step into dependencies) they don't seem to be obeyed. I'd like to be able to step into source using Source Link during unit test debugging.

It is possible I'm just not configuring it properly. I'm on a Mac M1 and I'm using these settings:

```json
{
  "dotnet.unitTestDebuggingOptions": {
    "enableStepFiltering": false,
    "justMyCode": false,
    "requireExactSource": false,
    "sourceLinkOptions": {
      "*": {
        "enabled": true
      }
    },
    "suppressJITOptimizations": true,
    "symbolOptions": {
      "searchNuGetOrgSymbolServer": true
    },
    "targetArchitecture": "arm64"
  }
}
```

If this already works, providing some clear documentation showing how to set it up would be helpful. There's [nothing on the testing page](https://code.visualstudio.com/docs/csharp/testing). These are similarly-named to the options listed [on the debugger options page](https://code.visualstudio.com/docs/csharp/debugger-settings) for `launch.json` but for unit testing.

### Alternatives considered

- Switch back to OmniSharp - I recall this working in the OmniSharp version of C# when I last tried it.
- Create a launch configuration for unit testing - do an end-around the test explorer and execute `dotnet test` from `launch.json` instead.

### Environment Information

- OS: Mac OS 14.0 "Sonoma"
- VS Code Version: 1.83.1
- Extension Version: v0.5.150

**Comment by peterwald** [comment]
Support has been added to C# Dev Kit for the `dotnet.unitTestDebuggingOptions`. It works in the same way as the C#/OmniSharp extension did, by merging those options into the debug profile when debugging unit tests. They are the same options as what is supported by launch.json.

This will ship in the next preview release.
