### ISSUE TITLE
[BUG] dotnet run in terminal no longer launching external console

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#625]
### Steps To Reproduce

1. Have a console app
2. Run 'dotnet run' in the terminal 
3. Used to launch externally but now it is only in the integrated terminal

### Expected Behavior

For there to either be a setting to determine

**Comment by webreidi** [comment]
@claudiaregio what do you have for the setting for the C# extension > Csharp > Debug: Console?
![image](https://github.com/microsoft/vscode-dotnettools/assets/55603905/c42b6037-e612-4fe3-bba9-12aafbc66b41)

**Comment by claudiaregio** [comment]
@webreidi I have external which is why I'm a bit confused because and it used to work but now it doesn't despite me not having updated neither VS Code nor the extension. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/7b307ce4-c14a-4583-a408-fc9c4112d688)
![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/f1b69c80-4449-48a1-8c97-1e82d7b88d98)

**Comment by timheuer** [comment]
I kind of expect this is how it would work.  If you are starting the command from the integrated terminal, you're in that environment.  The `externalTerminal` setting is really related to VSCode 'shell' activities.  Using `dotnet run` from the integrated terminal I wouldn't expect it to spawn any new terminal.  That's not how CLI outside of VSCode happens either.  In fact I'd be surprised that ever happened as I wouldn't know what in `dotnet run` would trigger that.

**Comment by claudiaregio** [comment]
i see.. then I'm mega confused. I'm not sure why it would have worked a few days ago and now it stops. Extra bummer because this was the workaround I needed for the debug toolbar issue i opened

**Comment by timheuer** [comment]
Yeah I'm baffled that ever worked...I'm really trying to figure out how that would have happened. :-(

**Comment by webreidi** [comment]
As running from the Solution Explorer or any of the run buttons will launch the external Terminal if the setting is set, we do not plan to change how terminal-run commands will execute.
