### ISSUE TITLE
[BUG] Can't decompile external references

### ISSUE THREAD

**Issue by julioct** [microsoft/vscode-dotnettools#627]
### Describe the Issue

When using Omnisharp you used to be able to enable decompilation support:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/8de1b0b3-0e6e-4c62-9c9d-884f6b184caa)

I don't see how to do it with the C# Dev Kit, so when I try to Go To Definition of the builder.Build() method from ASP.NET Core, all I get is this:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/677e0742-86cd-4b09-95a9-c66edf419063)

How to enable decompilation support?

### Steps To Reproduce

1. Create a new web application
2. Open Program.cs
3. Hit F12 in the builder.Build() call:

```csharp
var app = builder.Build();
```

4. You are taken to the method metadata, not the actual source.

### Expected Behavior

I should be able to see the actual source as I can do in Visual Studio:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/1836b6bd-c451-4487-866e-ed7db60cae29)

### Environment Information

Extension version: 0.5.150
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621

**Comment by webreidi** [comment]
@mikadumont is this on the C# extension parity list?

**Comment by dibarbet** [comment]
Related to https://github.com/dotnet/roslyn/issues/24349

We generally don't decompile SDK references because we don't know where the actual implementation assembly is.  This is the same behavior as VS (without source link).

 O# had some workarounds for this to try and find it but I don't think we should necessarily spend a lot of time on that.  Instead we should focus on adding support for source link in C#/devkit which would allow go to definition to find the real source for SDK references.

**Comment by ischia-exigenter** [comment]
If I have two .csproj, let's say one is a main DLL library and the other is an Xunit test project, and my test project references the main library project, I used to be able to find all references in the test code and go directly to the source code in the main lib. If I install the 2.0 or higher version of C# for Visual Studio Code, I lose this important functionality, and instead, References takes me to some useless meta data file. I'm not sure who thought this would be a good idea, but you are off my xmas list.

**Comment by ProTip** [comment]
Is Source Link support on the roadmap? Currently a lot of Asp.Net code, particularly service extensions used for setup, is a black box in VSCode. I often open Rider just for the ability to jump into SDK source code..

**Comment by dibarbet** [comment]
Sourcelink is on the roadmap - will close this issue in favor of the issue tracking on the C# extension side - https://github.com/dotnet/vscode-csharp/issues/6784
