### ISSUE TITLE
Code action lightbulb covering code & hard to see

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#632]
### Describe the Issue

The lightbulb appears to be in the wrong spot (usually it's off to the left between the code and line numbers, yes?) and covering code and hard to see 

![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/45214855-d59c-441d-894a-89b8e10ce024)

**Comment by arkalyanms** [comment]
@claudiaregio do you happen to have a repro for this one?

**Comment by arkalyanms** [comment]
Would you please move to the vscode editor team, if this is not actionable on the Roslyn side?

**Comment by claudiaregio** [comment]
I've opened it here https://github.com/microsoft/vscode/issues/196312

**Comment by dibarbet** [comment]
Yeah, we don't control any lightbulb rendering on the extension side, so any fix would need to come from vscode.  It is easy to reproduce this on the vscode extension sample, for example:
![image](https://github.com/microsoft/vscode-dotnettools/assets/5749229/31033265-f616-4c56-899d-375ad993dd5e)

Thanks for moving it
