### ISSUE TITLE
[BUG] Test explorer froze and taking long time (on remote SSH session)

### ISSUE THREAD

**Issue by kimyu92** [microsoft/vscode-dotnettools#638]
### Describe the Issue

The primary issue is that debugging unit tests remotely (via ssh) by adding a breakpoint in large application has never completed successfully. Not only it doesn't stop at breakpoint but the kill button doesn't work.

When ssh to windows server, running unit tests from test explorer took longer time compared to rdp solution. 

### Steps To Reproduce

1. create a C# application with windows server and add a bunch of unit tests
2. connect to windows server virtual machine via remote ssh in VSCode
3. add a breakpoint
4. run test suites / run a single test

### Expected Behavior

Breakpoint stop, able to kill long running test, caching work like visual studio and better performance overall.

### Environment Information

- OS: Windows Server 2022
- VS Code Version: 1.83.1
- Extension Version: 1.0.4

**Comment by kimyu92** [comment]
It's both interesting and annoying to debug C#/.Net application on windows server as it seems subpar compared to linux distros and mac os according to source.

https://github.com/dotnet/vscode-csharp/blob/main/src/features/processPicker.ts#L298-L302
https://github.com/dotnet/vscode-csharp/blob/main/scripts/remoteProcessPickerScript

I thought the goal is to support cross platform and hope this is possible in near future.

**Comment by peterwald** [comment]
I've tested and verified that the basic functionality does work correctly. I established a connection to a remote Windows Server machine over SSH and opened the project on the remote machine using VS Code with a remote SSH session. I was able to run and debug tests, pause at breakpoints and cancel long running tests.

I'm curious if there is something different about your configuration that is causing problems....an unreliable or intermittent SSH connection for instance? 

For what it's worth, the remote SSH functionality is built-in to VS Code and the C# Dev Kit does not do anything differently for this remote scenario than it would for local operations, or for WSL, etc....

**Comment by kimyu92** [comment]
For my setup, everything in C# dev kit seems to work except debugging with remote windows server,

I have noticed every time when I connect to the terminal, it seems a new terminal "install" session is created and never clean up as shown below. Would that be a problem?
<img width="989" alt="terminal" src="https://github.com/microsoft/vscode-dotnettools/assets/2663509/741d6015-e2ca-4c80-9a1c-4630acb0b4cc">

When I peek the virtual machine via microsoft remote desktop, I can see those terminal is lingering around... not sure it's expected behavior. 

Maybe it's related to issue from me setting up SSH? Maybe it's not fully authorized via Kerberos
Here is how I setup ssh, if you have a better guide, please let me know.

```
# Automation 1: Install openssh client
# Install openssh via chocolatey
choco install openssh --pre --yes
Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1

# Post client installation setup
. "C:\Program Files\OpenSSH-Win64\install-sshd.ps1"

# Automation 2: Create necessary files, eg. sshd_config and authorized_keys
# Create sshd_config
Start-Service sshd
Stop-Service sshd

# Create authorized_keys
cd $env:USERPROFILE; mkdir .ssh; cd .ssh; New-Item authorized_keys; start .

# Automation 3: Update sshd_config
# Replacing the default sshd_config file
# Specify the path to your sshd_config file
$sshdConfigFilePath = "C:\ProgramData\ssh\sshd_config"

# Use Get-Content to read the file
$sshdConfig = Get-Content $sshdConfigFilePath

# Define the replacement strings
$replacementStrings = @(
    "#PasswordAuthentication" -> "PasswordAuthentication no",
    "#PubkeyAuthentication" -> "PubkeyAuthentication yes"
)

# Loop through each line and make replacements
foreach ($line in $sshdConfig) {
    foreach ($replacement in $replacementStrings) {
        if ($line -match [regex]::Escape($replacement.Key)) {
            $sshdConfig = $sshdConfig -replace [regex]::Escape($replacement.Key), $replacement.Value
        }
    }
}
# Lines to comment out
$linesToCommentOut = @(
    "Match Group administrators",
    "AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys"
)

# Comment out the specified lines
foreach ($lineToComment in $linesToCommentOut) {
    $sshdConfig = $sshdConfig -replace [regex]::Escape($lineToComment), "#$lineToComment"
}

# Write the modified content back to the file
$sshdConfig | Set-Content $sshdConfigFilePath
Make sure to replace $sshdConfigFilePath with the actual path to your sshd_config file. This script reads the file, performs the desired replacements, and then writes the modified content back to the file.


# After automation completed,

# For local machine
# Copy SSH Keys and replace C:\Users\<username>\.ssh\authorized_keys in vm
pbcopy < ~/.ssh/id_ed25519.pub

# Add <vmhost> hosts to ~/.ssh/config
Host <vmhost>
  HostName <vmhost>
  IdentityFile ~/.ssh/id_ed25519
  ServerAliveInterval 300
  TCPKeepAlive no

# Connect
# Connect to vm via microsoft remote desktop
# open powershell an run sshd in foreground
# NOTE: for some reason using Start-Service sshd will result in broken pipe when connecting via client

# verify connection to vm from local machine
ssh -l 'myorg\<username>' <vmhost>
# proceed with VS Code development
```

**Comment by peterwald** [comment]
Your setup seems pretty reasonable. If you can connect to the Windows SSH machine with `ssh <host>` on the command line, then it should work OK. I'm not sure how the user login mapping works in your example, that could be a potential problem.

I'm curious why you are using Chocolatey to install OpenSSH as there is a package that is included with Windows.  In Powershell you can run the following command to install OpenSSH server in a single step, and it will be integrated and updated with the OS.

```powershell
# In powershell
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
```

**Comment by kimyu92** [comment]
> I'm curious why you are using Chocolatey to install OpenSSH as there is a package that is included with Windows. In Powershell you can run the following command to install OpenSSH server in a single step, and it will be integrated and updated with the OS.

Unfortunately, by using `Add-WindowsCapability`, I still run into **OpenSSH install error (error code 0x800f0954)** error on windows server 2022 and there seems to be no automated way to fix it

https://stackoverflow.com/a/74947737
https://github.com/MicrosoftDocs/windowsserverdocs/issues/2074

**Comment by peterwald** [comment]
Closing for now until we get more clarity on the problem. Please re-open if you have more information.
