### ISSUE TITLE
No Solution Explorer view

### ISSUE THREAD

**Issue by ckasabula** [microsoft/vscode-dotnettools#64]
Type: <b>Bug</b>

Installed extension. Relaunch vscode for my solution. Already had omnisharp c# extension installed.

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (22.93GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+ubuntu-20.04__05/home/developer/code/foo/foo.bar --remote=wsl+ubuntu-20.04__05 --crash-reporter-id f7248f5e-e1d1-434b-8dee-4bc8afb3249a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu-20.04__05|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (14 x 2904)|
|Memory (System)|31.35GB (16.24GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpath:30739704

```

</details>

**Comment by timheuer** [comment]
> Already had omnisharp c# extension installed.

Hi @ckasabula you need to make sure you are on the pre-release version of the C# extension also.  You should have been prompted to switch to that.  It should be version `2.0.x`.  Can you confirm you also are on that pre-release.  If yes, please if you can provide more information about your solution?

**Comment by ckasabula** [comment]
Thanks @timheuer. I was not running a pre-release version of the C# extension. I switched and I can now see the solution explorer view.

I don't think I was prompted to switch. Possible I didn't notice the prompt?

**Comment by timheuer** [comment]
@ckasabula it's possible you didn't notice it, and easy to dismiss.  We're working to iron out a bunch of things to exit pre-release as soon as we can.  Will see if we can add some better info.  I'll close this now that you are solved.
