### ISSUE TITLE
[BUG] C# Dev Kit with .NET 8 RC2

### ISSUE THREAD

**Issue by justinyoo** [microsoft/vscode-dotnettools#641]
### Describe the Issue

In GitHub Codespaces, C# Dev Dit doesn't recognise .NET 8 RC2 yet in the solution explorer.

<img width="1865" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1538528/b00a66a7-8d88-43c3-ae95-3173d7db76d9">

Using dotnet CLI is fine like:

- dotnet restore
- dotnet build
- dotnet watch run

### Steps To Reproduce

1. Open GitHub Codespaces with .NET 8 RC2 SDK installed
2. Install C# Dev Kit extension
3. Run the following commands to create a new Blazor project
   ```bash
   dotnet new blazor -n MyBlazorApp1
   ```
4. Open Solution Explorer and select the Blazor project
5. Right click and select debug
6. The error message pops up

### Expected Behavior

Blazor web app runs successfully

### Environment Information

- OS: GitHub Codespace on Debian 12 with .NET 8 RC2
- GitHub Codespaces:
  - Version: 1.83.1
  - Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
  - Date: 2023-10-10T23:52:02.729Z
  - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.57
  - C# Dev Kit version: v0.5.150

**Comment by justinyoo** [comment]
Oh, I switched to the pre-release version of `v1.0.4` and it works fine.

I'll keep this issue open until someone confirms it.

**Comment by WardenGnaw** [comment]
If C# Dev Dit doesn't recognise .NET 8 RC2 yet in the solution explorer, then I'm guessing the project system is not providing any launch targets to use.

@tmeschter ?

**Comment by arkalyanms** [comment]
@webreidi has a repro and logs I believe.

**Comment by webreidi** [comment]
Here are the output from the C# and the Projects output windows. Let me know what else you'd like me to send.

[csharpOutputWindow.txt](https://github.com/microsoft/vscode-dotnettools/files/13074679/csharpOutputWindow.txt)
[projectsOutputWindow.txt](https://github.com/microsoft/vscode-dotnettools/files/13074681/projectsOutputWindow.txt)

**Comment by tmeschter** [comment]
@justinyoo Are you seeing the same errors in the Solution Explorer and "Projects" output window as @webreidi?

**Comment by justinyoo** [comment]
@tmeschter Oh, it's interesting.

I turned the C# Dev Kit version back from `v1.0.4` to `v0.5.150` and the error has disappeared. I'm not sure it's because of the GitHub Codespace thing or cache left in the devcontainer or something else.

I'll create another GH Codespace instance and get back to you.

**Comment by justinyoo** [comment]
I created a fresh/new GH Codespace instance with the C# Dev Kit (`v0.5.150`) installed. But I got no error any longer.

**Comment by webreidi** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/55603905/9c22c6d6-54e7-46ad-9a4c-e03496567e91)
 @tmeschter / @arkalyanms Do you need anything else from me on this?

**Comment by timheuer** [comment]
> I created a fresh/new GH Codespace instance with the C# Dev Kit (`v0.5.150`) installed. But I got no error any longer.

Would love to see the codespace definition.

**Comment by justinyoo** [comment]
> > I created a fresh/new GH Codespace instance with the C# Dev Kit (`v0.5.150`) installed. But I got no error any longer.
> 
> Would love to see the codespace definition.

Oh, here's the one: https://github.com/microsoft/dotnetconf-studentzone/tree/main/.devcontainer

**Comment by arkalyanms** [comment]
> ![image](https://user-images.githubusercontent.com/55603905/277801486-9c22c6d6-54e7-46ad-9a4c-e03496567e91.png) @tmeschter / @arkalyanms Do you need anything else from me on this?

@tmeschter do we need Wendy to file a separate bug for her repro? Her repro is not on github codespaces.

**Comment by webreidi** [comment]
FYI. I updated my version of VS (not VS Code) and when I returned to C# Dev Kit, my projects would now open successfully.
