### ISSUE TITLE
[BUG]  Missing the creation of .vscode folder (launch.json and tasks.json) if not available.

### ISSUE THREAD

**Issue by aboimpinto** [microsoft/vscode-dotnettools#642]
### Describe the Issue

I'm using Ubuntu + VSCode +.net7.0, and I wonder if this problem exists in other platforms.
When I created my project and opened it on VSCode, I was offered the option to make the .vscode folder with the necessary launch.json and tasks.json.
Now, the solution came with more and more projects and folders, and when I cloned it on another machine, that option wasn't offered to me.

With this extension, I can press F5 and choose the default configuration, the project that I want to start, but because this information is not persistent, I have to do that several times a day during my working time.

Or this information is persisted like the old way (in the .vscode folder in launch and tasks file) or in another setting. 
the way is now, is very annoying ... especially when you have several build ways (C# and Maui) and you always have to choose the one every time you have to compile the app.

thanks for the good work
Paulo Aboim Pinto

### Expected Behavior

I would expect to be prompted to create .vscode when the folder doesn't exists.exist

### Environment Information

OS: Ubuntu 23.04
VSCOde: 1.83.1
C# Extension: v2.7.25
C# Dev Kit: v0.5.150

I have the same  behavior when running with and without a DevContainer

**Comment by timheuer** [comment]
Hi @aboimpinto you can still create these manually if you'd like to use the launch/task approach for your repository.

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/0b270647-af64-443b-9075-086964b0ff8d)

**Comment by aboimpinto** [comment]
It's true ... I can create manually but I would like to have the automatic way .... is there a way to force it?

**Comment by timheuer** [comment]
If you launch the command pallette (CTRL + P) and type 'generate' you'll see this option:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/23d1745a-fa9d-4ca9-990b-c2ba1bc2d57e)

which will attempt to create them (if you have multiple projects you'll have to select).

**Comment by aboimpinto** [comment]
That is great ... thanks.
I don't know why VSCode stops asking for that ... but when it doesn't ask, I will be able to use this ... 

I would suggest to write this somewhere for people with the same issue be able to force the generation of the Build and Debug configuration.

Thanks a lot
Paulo Aboim Pinto
