### ISSUE TITLE
Install of Dev Kit unable to find SDK

### ISSUE THREAD

**Issue by wgrs** [microsoft/vscode-dotnettools#644]
Type: <b>Bug</b>

Ubuntu 23.04. 

Do a fresh install of .Net SDK 7.

Run dotnet --info
---
.NET SDK:
 Version:   7.0.402
 Commit:    791db8e2d8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /snap/dotnet-sdk/224/sdk/7.0.402/

Host:
  Version:      7.0.12
  Architecture: x64
  Commit:       4a824ef37c

.NET SDKs installed:
  7.0.402 [/snap/dotnet-sdk/224/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.12 [/snap/dotnet-sdk/224/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.12 [/snap/dotnet-sdk/224/shared/Microsoft.NETCore.App]

---

1. Delete .vscode file 
2. Install  C# Dev Kit
3. After install , following error immediately thrown:

 The .NET Core SDK cannot be located: Error running dotnet --info: Error: Command failed: dotnet --info
Aborted (core dumped)

Aborted (core dumped)
. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

Extension version: 0.5.150
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 6.2.0-35-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|6, 3, 2|
|Memory (System)|7.66GB (3.32GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30866406
pyreplss1:30865275
pythontbext0:30864172

```

</details>

**Comment by nagilson** [comment]
@wgrs Was the .NET SDK installed after opening VS Code, and does it work after restarting VS Code? Its possible it did not receive the update to your PATH if so. And what is the full path of the .vscode folder you are talking about, and why did you delete it?

@dibarbet Does this look familiar to the snap issue you were working on earlier? And does CDK create logs that include the more of the information it parsed from `dotnet --info`? If so, that might be helpful.

**Comment by wgrs** [comment]
On Ubuntu, the .vscode file holds all of the extensions. As I mentioned above, I deleted this file to give C# dev kit a fair chance at working. So there were no other extensions that could affect it. On a separate  topic ,there are multiple path errors thrown when installing .NET on Ubuntu depending on the package manager.

**Comment by nagilson** [comment]
I see you are talking about the .vscode folder on your project root, now that youve provided that information. You are right that snap uses symbolic links to patch up dotnet which makes it not function well. It is not recommended to install .net on ubuntu using snap, especially on 23.04, you can just use the dotnet sdk and runtimes provided via the built in package feeds following the instructions here https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2304 which will work a lot better.

**Comment by nagilson** [comment]
If you have problems with intellisense and themes with CDK, please create separate issues detailing the issues you are facing.

**Comment by wgrs** [comment]
I started off using the Microsoft feeds and also ended in SDK errors. If snap should not be used,  why is it given as an option in the docs? Speaking of which, the docs are very confusing and contradictory. These path errors have been around for about 3 years now and they have not been fixed. Why?

**Comment by wgrs** [comment]
> If you have problems with intellisense and themes with CDK, please create separate issues detailing the issues you are facing.

I opened the Github issues on CDK and noticed none of the issues raised recently are being addressed.  Most issues raised say that nothing works with the CDK and that has been my experience. I added a issue but have little confidence on it being addressed due to the high number of unaddressed tickets.

**Comment by nagilson** [comment]
Make sure you blow away all of the existing installs of .NET on the system, otherwise adding the Microsoft feeds will not work. Also, ubuntu 23.04 does not need the microsoft feeds, because dotnet is in the OS package manager itself. If you mix two of those feeds it will only make the situation worse and it will be totally broken. Probably you will need to uninstall the snap and microsoft feeds first. https://learn.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-linux

The docs for that version of ubuntu only mention snap as being an alternative way to install .NET with a script if you have an ARM 64 machine.

**Comment by wgrs** [comment]
> Make sure you blow away all of the existing installs of .NET on the system, otherwise adding the Microsoft feeds will not work. Also, ubuntu 23.04 does not need the microsoft feeds, because dotnet is in the OS package manager itself. If you mix two of those feeds it will only make the situation worse and it will be totally broken. Probably you will need to uninstall the snap and microsoft feeds first. https://learn.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-linux
> 
> The docs for that version of ubuntu only mention snap as being an alternative way to install .NET with a script if you have an ARM 64 machine.

I have probably tried a full reinstall about 20x using apt, snap, ms feed, Ubuntu feed. None work completely. As soon as you get to a state where you need to add tools, it blows up with can't find SDK. Once you get past those errors,  the CDK blows up. Why is this not being addressed. There are hundreds of posts on SO with people battling with vscode. Surely it makes sense to fix the causes?

**Comment by wgrs** [comment]
@nagilson Can you indicate if this issue is being fixed or can it be taken than .net development on Ubuntu is not a viable option?
