### ISSUE TITLE
[BUG] Cannot have ARM and X86 versions of .Net installed at the same time on an Apple M1 mac

### ISSUE THREAD

**Issue by AaronSaikovski** [microsoft/vscode-dotnettools#646]
### Describe the Issue

.NET SDK for X64 CPU may have been installed on an Apple computer with Apple CPU, which does not work with C# Dev Kit. Please uninstall it and reinstall SDK for ARM 64 platform before using C# Dev Kit. A reboot might be necessary after installing the new SDK.

### Environment Information

VS Code: 1.83.1
Mac OS Sonoma 14

**Comment by nagilson** [comment]
This is due to how .NET functions on OSX and linux, it is a limitation on the OS and package manager side, not really a problem with CDK. Youll need to install an ARM 64 SDK and uninstall the other one like it suggests.
