### ISSUE TITLE
[BUG] Projects are loaded, but solution explorer window doesn't appear

### ISSUE THREAD

**Issue by ahmednfwela** [microsoft/vscode-dotnettools#647]
### Describe the Issue

When opening a solution, the extension shows the correct number of loaded projects, but won't show the solution explorer view.

Primary sidebar where the solution explorer view should be visible:
![image](https://github.com/microsoft/vscode-dotnettools/assets/63286031/77beadf7-a9bc-4503-b70d-37c5df0defa9)

`Projects` output shows:
```
2023-10-24 17:58:46.738 [info] Project system initialization finished. 73 project(s) are loaded, and 0 failed to load.
```

Status bar also showing correct number of projects:
![image](https://github.com/microsoft/vscode-dotnettools/assets/63286031/6f2e43ad-fd08-453f-95ee-96df725924b1)

### Environment Information

- OS: Windows_NT x64 10.0.19045
- VS Code Version: 1.83.1 (system setup)
- Extension Version: v1.0.4 Pre-release

**Comment by webreidi** [comment]
@ahmednfwela does one or more of the projects target a .NET Framework project or something non-.NET?

**Comment by ahmednfwela** [comment]
Apparently it was there but hidden, I executed the following command and it appeared again:
```
View: Focus on Solution Explorer View
```
