### ISSUE TITLE
Allow Device Refresh

### ISSUE THREAD

**Issue by natedogg2020** [microsoft/vscode-dotnettools#648]
Type: <b>Feature Request</b>

This is in the .NET MAUI extension

I plugged in my iPad for the first time to deploy to my iPad, but it did not show up in the device list. In Visual Studio for Mac, it showed up. I opened the command palette and did Reload Window, and then my iPad shows up after a full re-initialization of VS Code. This should be a command, and automatically refresh when you open the device target option.

Extension version: 0.4.9
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:

> VS bug [#1910898](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1910898)

**Comment by jknaudt21** [comment]
Hello! We're working on actively listening for devices and refreshing the iOS device list when new device are added. 

However, as of version 0.6.54, you can run the command ".NET MAUI: Configure Apple" and select the "Refresh Apple environment" option

**Comment by mauroa** [comment]
This issue has already been fixed. Please install the latest .NET MAUI pre-release. Thanks for your feedback and help.
