### ISSUE TITLE
Solution Explorer not visible

### ISSUE THREAD

**Issue by Dokug** [microsoft/vscode-dotnettools#649]
Type: <b>Bug</b>

Without having changed anything, the C# dev kit extension does not show the solution explorer view since yesterday (24.10.2023).
This is true for all kinds of .Net projects (.NET MAUI, console, library, ...)

I have tried disabling/enabling the extension, reloading the workspace, signing out and back in for the extension.

Extension version: 0.5.150
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 5|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id e96b2583-cfa8-4b09-8d8f-f1c0bbfdb94a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
pythonmhint1:30842940
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by daneb** [comment]
Exact same problem, on a M2.

**Comment by Michael-Eng** [comment]
What version of .NET do you have installed? 

1. If you're using .NET 7 do you have 7.0.13 installed? This is issue https://github.com/dotnet/core/issues/8861
2. If you're using .NET 8 RC* builds do you have the option to use delay signed dlls?
![image](https://github.com/microsoft/vscode-dotnettools/assets/18017073/50a50db9-5347-4bf4-8bd4-a7e47355e67d)

What do you see in the output window? Can you attach the logs?

**Comment by Dokug** [comment]
I am only using .NET 8 RC* and I do have the option you mentioned, but this does not change anything in the VS Code UI.
Also, the required ".NET Runtime Install tool" keeps installing the 7.0.13 runtime, which is not something I want, but I have accepted it.
It does however not show up when running "dotnet --list-runtimes"

**Comment by Dokug** [comment]
The output window for the C# Dev Kit shows the following:

Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/dotnet"
Using runtime installed in SDK.
.NET server STDERR: Failed to load /Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib, error: dlopen(/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib, 0x0001): tried: '/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib' (code signature in <6F6D3D7A-7260-3671-9CA8-33B00B9431E6> '/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib' (no such file), '/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib' (code signature in <6F6D3D7A-7260-3671-9CA8-33B00B9431E6> '/Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
The library libhostfxr.dylib was found, but loading it from /Users/mathias/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~arm64/host/fxr/7.0.13/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

.NET server exited with 130

**Comment by nagilson** [comment]
Please try following the fix described in the workaround section here: https://github.com/dotnet/core/issues/8861

**Comment by Dokug** [comment]
That did fix the issue for me, thank you!
