### ISSUE TITLE
When using the debug button on the editor of a C# file in MAUI it fails

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#653]
### Describe the Issue

In VSC, when having a C# file open the run/debug icons show up in the editor:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/fcf9c34b-102f-4d05-b435-7c71dc2e83f9)

These allow you quick way to "run" but assume a wrong context for the MAUI scenario.

This runs using the C# debugger path and results in:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/9fafada9-94d8-4682-ad79-92a0cb7721ab)

### Steps To Reproduce

1. Create a .NET MAUI app
2. Open the MainPage.xaml.cs
3. Click the debug button on the editor

### Expected Behavior

It launches the right debugger (.NET MAUI) that understands the target

> VS bug [#1910899](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1910899)

**Comment by sibbl** [comment]
This issue still persists when trying to debug Azure Functions.

**Comment by emaf** [comment]
This is now fixed in the pre-release channel. Versionins needed for this to work:
- C# v2.29.11
- C# Dev kit v1.6.2
- .NET MAUI v0.11.87
