### ISSUE TITLE
[BUG] Solution explorer won't open with .net6

### ISSUE THREAD

**Issue by kboniadi** [microsoft/vscode-dotnettools#655]
### Describe the Issue

I have .net6 install on a mac. The cli tool is accessible and working in terminal. When opening vscode, non of the solutions are recognized. Even manually trying to open the solution results in nothing including no errors. 

I've tried installing .net7 and the extension does seem to work with that.

### Steps To Reproduce

1. install .net6 from MS website
2. open project containing solutions file(s) with vscode

### Expected Behavior

C# dev kit should work with .net6 instead of just .net7

### Environment Information

- macos
- C# dev kit extensino: v1.0.12
- vscode: 1.83.1

**Comment by timheuer** [comment]
Hi @kboniadi apologies for the delay here -- is this still an issue for you? Can you upgrade extension to pre-release and see if resolved.  If not, can you share more about your project workspace? and a `dotnet --info` as well?

**Comment by kboniadi** [comment]
Hi @timheuer. The issue seems to be resolved after I installed .Net8. I've also updated the extension to the nightly build.

**Comment by timheuer** [comment]
Ok, great, I'll go ahead and close this for now.  If any recurrence of this comes up, please log a new bug and also include the output from `dotnet --info`

Again, sorry for the delay.
