### ISSUE TITLE
[BUG] Could not detect any Unity instance at all

### ISSUE THREAD

**Issue by singletooon** [microsoft/vscode-dotnettools#656]
### Describe the Issue

The command "Attach Unity Debugger" can't find any instance all the time at all.

I'm using
VSCode v1.83.1 with Unity Extension v0.9.2
Unity 2022.3 with Visual Studio Editor 2.0.22 enabled
on macOS Sonoma with M2 Chip.

Thanks a lot.
![image](https://github.com/microsoft/vscode-dotnettools/assets/97838777/89049bbf-6638-4896-a424-ac6cf74d7d21)

**Comment by tmeschter** [comment]
Moving to "area-unity" as there is no reason at this point to suspect the project system is involved.

**Comment by jbevain** [comment]
Hi @singletooon,

We just published a new preview of the Unity extension `0.9.3`. Could you give it a try? What do you see in the `Unity` output panel of Visual Studio Code?

<img width="844" alt="Screenshot 2023-11-08 at 10 06 41 AM" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/6d053cf2-0557-4b84-876a-8b7cc89d8b1e">

**Comment by jbevain** [comment]
Closing this as we unfortunately don't have enough information to work on this. If you're still experiencing the issue, please open a new issue and submit the output of the Unity output panel. Thank you!
