### ISSUE TITLE
[BUG] Template for Maui app -- Don't know how to launch profile 'Windows Machine' in MauiApp1; the commandName 'MsixPackage' is not supported.

### ISSUE THREAD

**Issue by cicorias** [microsoft/vscode-dotnettools#66]
### Describe the Issue

start a brand new Maui app -- using .NET: New Project -- choose maui

launch debugger.

<img width="333" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1080406/059c65a6-3a40-4a26-80df-9d89c7b7aaa6">

The msix extension is installed for Visual Studio -- are there other steps?

https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

### Steps To Reproduce

1. in windows 11
2. new .NET Project
3. Choos Maui
4. Start debug from Solution Explorer window
5. error with 
Don't know how to launch profile 'Windows Machine' in MauiApp1; the commandName 'MsixPackage' is not supported.

### Expected Behavior

debug instance launces.

### Environment Information

- windows 11: Microsoft Windows [Version 10.0.22621.1778]
- vs code 
- [Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z (4 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

[Copy] [OK]

C# Dev Kit
v0.1.83

**Comment by maddymontaquila** [comment]
Hi there!!! If you grab the new [.NET MAUI extension](aka.ms/mauidevkit-marketplace) and then run it with the .NET MAUI debugger does that solve your problem?

**Comment by mauroa** [comment]
Hi @cicorias.
We are trying to re-activate or cleanup old issues related to the VS Code MAUI extension that were left into "Need More Info" state and didn't get a response in a while.
I would like to know if you continued working with MAUI projects in VS Code and if you still have any issue related to this ticket.
We will proceed to close this ticket in case we don't get a new response in a few days.
Thanks in advanced.

**Comment by sayedihashimi** [comment]
> Hi there!!! If you grab the new [.NET MAUI extension](aka.ms/mauidevkit-marketplace) and then run it with the .NET MAUI debugger does that solve your problem?

The link is messed up, the right link is https://aka.ms/mauidevkit-marketplace
