### ISSUE TITLE
[SUGGESTION] Sounds or alerts for events

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/vscode-dotnettools#660]
### Describe the feature you'd like

It'd be nice to have audio alert functionality. Similar to what is possible with Visual Studio audio events in Windows Sound.

![image](https://github.com/microsoft/vscode-dotnettools/assets/35783676/d3c69fa6-9ec0-4ac9-bb98-2c99c2dd6dc1)

**Comment by WardenGnaw** [comment]
You can set the sound settings within the VS Code editor by looking for `audio cues`.

![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/12069ec0-411d-48ba-97f5-eea0764ffa82)

As VS Code works in multiple platforms, the settings options will not be in the Windows Settings. If you would like to offer that suggestion to display there, I would open an issue at https://github.com/microsoft/vscode/issues
