### ISSUE TITLE
Debbugger doesn't connect to iPhone

### ISSUE THREAD

**Issue by Dreambound131** [microsoft/vscode-dotnettools#663]
Type: <b>Bug</b>

When trying to debug a simple MAUI project on iPhone, the debugger is able to install the application, but not to run it. 
It then tells "You can still launch the application manually by tapping on it.", but when I do this the debugger doesn't connect to my iPhone, so I can only run and not actually debug the application

Extension version: 0.4.9
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 12, 12|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 744684dd-5acb-46c4-a0a5-00f2858c68b1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet0:30874138
2e7ec940:30870395
pythontbext0:30864172

```

</details>

> VS bug [#1910903](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1910903)

**Comment by mauroa** [comment]
Hi @Dreambound131, we are reviewing bugs that has some time since they were reported, especially because we did some important changes around the debugging experience.
Could you please confirm if this is still an issue for you after installing the latest .NET MAUI pre-release? Ideally, you might want to have at least .NET SDK 8.0.200, to have an even better experience.
I'll wait for your confirmation.
Thanks for your help and feedback.

**Comment by Dreambound131** [comment]
> Hi @Dreambound131, we are reviewing bugs that has some time since they were reported, especially because we did some important changes around the debugging experience. Could you please confirm if this is still an issue for you after installing the latest .NET MAUI pre-release? Ideally, you might want to have at least .NET SDK 8.0.200, to have an even better experience. I'll wait for your confirmation. Thanks for your help and feedback.

@mauroa Yes, I confirm that now the debugger is working as expected, thank you!
