### ISSUE TITLE
[SUGGESTION]Make it possible to generate .xaml and .xaml.cs files

### ISSUE THREAD

**Issue by rogersm-uwosh** [microsoft/vscode-dotnettools#665]
### Describe the feature you'd like

I'm trying to use the VS extension with .NET MAUI - how do I make .xaml and .xaml.cs files? If this is supposed to be a replacement for Visual Studio Mac, it's going to need that.

### Alternatives considered

Just sticking with Visual Studio for Mac, because it's friendlier.

**Comment by vhugogarcia** [comment]
+1 😃

**Comment by emaf** [comment]
@rogersm-uwosh If you click on the "Add New File..." button you should get XAML listed as an option. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/3286258/3f2e9a82-b33a-43b8-a575-a1565768ee8b)
![image](https://github.com/microsoft/vscode-dotnettools/assets/3286258/9d5511ee-bc89-4d8d-abbe-f0e2e761dadd)

If that's not the case, could you share which version of the MAUI extension and SDK you are using, and the content of the .NET MAUI output page? 
Also, are debug targets listed for that project?

**Comment by rogersm-uwosh** [comment]
Hmmm, I even see SOLUTION EXPLORER, just EXPLORER. Besides that, I've got the latest version (I think, just checked now). I do not see the popup that you are showing, just an empty field where I can type in the name.

![Screenshot 2023-11-01 at 4 34 59 PM](https://github.com/microsoft/vscode-dotnettools/assets/91431120/302c7e05-3d9a-48ae-836d-225511a052b9)

I believe I am using the right version , this is what I see in the extensions pane:

Published
2023-07-11, 11:07:04
Last released
2023-11-01, 11:28:58
Last updated
2023-11-01, 16:31:46
Identifier
ms-dotnettools.dotnet-maui

I'm not sure what you mean by the .NET MAUI output page -- there's an output tab in Visual Studio Code, but it's empty when my Hello, World! app is running.

**Comment by rogersm-uwosh** [comment]
Oh, regarding .NET version, I have:

rogersm@N07RCXK9PG ~ % dotnet --info
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.410 [/usr/local/share/dotnet/sdk]
  6.0.413 [/usr/local/share/dotnet/sdk]
  6.0.414 [/usr/local/share/dotnet/sdk]
  6.0.415 [/usr/local/share/dotnet/sdk]
  6.0.416 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]
  7.0.307 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.24 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.24 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by emaf** [comment]
Just for context, the `Solution Explorer` panel is added by the C# Dev Kit extension, and the .NET MAUI extension is built on top of that one. 

In this case, it seems C# Dev Kit is not loading, so you are not getting any kind of tooling support for your project. Could you share the following?
- Version of C# Dev Kit extension
- Version of .NET MAUI extension
- Output from the C# Dev Kit extension. You can find this on `View -> Output`, Output tab, and then on the drop down list on the right side select `C# Dev Kit`

The version of each extension should be next to the extension name, once you click on it on the Extensions tab. For instance:
![image](https://github.com/microsoft/vscode-dotnettools/assets/3286258/a7520b28-9cea-4e5e-98a5-0ee58e7b264f)

**Comment by rogersm-uwosh** [comment]
Here you go, thanks for helping with this!

C# Dev Kit: v1.0.14
.NET MAUI v0.4.9

Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "/usr/local/share/dotnet/dotnet"
.NET server started and IPC established in 1304ms
Completed Spawn .NET server (2036ms)
Completed Clear environment (2269ms)
Completed Open a solution with environment service (2392ms)
Starting Restore solution...
Completed Open a solution (2397ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /Users/rogersm/Desktop/Expendable/Expendable.sln --interactive...
Completed command: "dotnet" restore /Users/rogersm/Desktop/Expendable/Expendable.sln --interactive (1067ms)
Completed NuGet restore.
Completed Restore solution (1068ms)

**Comment by emaf** [comment]
That's weird. From the C# Dev Kit output it seems it was able to load and restore the solution. 

Just to confirm, if you collapse all the panels in the Explorer tab, do you get the Solution Explorer one but it is empty or you don't get it at all? 

This is how the Explorer tab should look like, where I opened a root folder called MauiApp1, which contains a solution file named MauiApp1 too:
![image](https://github.com/microsoft/vscode-dotnettools/assets/3286258/bede9c14-fefb-4df1-8672-9398fdceb33a)

**Comment by rogersm-uwosh** [comment]
Ah, that was the problem! With the app open, Solution Explorer was pushed to the very bottom of the window , and since I had a New File button in Explorer (which did work: it created files), I didn't realize I needed to look for *another* New File in Solution Explorer.

Thanks for all your help, I do appreciate it

**Comment by rogersm-uwosh** [comment]
I'm going to close this, since emaf solved my problem!
