### ISSUE TITLE
Testing not support *.setting file

### ISSUE THREAD

**Issue by lerenhua** [microsoft/vscode-dotnettools#667]
Type: <b>Bug</b>

The *.setting file is not supported in Tests Run.

Extension version: 0.5.150
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.4.0-42-generic
Remote OS version: Linux x64 5.15.0-84-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.31GB (3.56GB free)|
|Process Argv|--crash-reporter-id 195cf56b-4f2f-4a56-b271-c00dce6db511|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.10.1.11-docker|
|OS|Linux x64 5.4.0-42-generic|
|CPUs|AMD EPYC 7T83 64-Core Processor (256 x 1762)|
|Memory (System)|2003.97GB (1858.36GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu-small|
|OS|Linux x64 5.15.0-84-generic|
|CPUs|AMD Ryzen 7 7735HS with Radeon Graphics (16 x 1600)|
|Memory (System)|28.13GB (9.16GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
2e7ec940:30870395
pythontbext0cf:30864173

```

</details>

**Comment by tmeschter** [comment]
Moving to "area-test".

**Comment by AbhitejJohn** [comment]
Thank you for sharing your feedback. This is similar to #156 . We would like add .runsettings support for our test experiences.
