### ISSUE TITLE
C# Hover Method with // (slash-slash) in constant shows incorrect IntelliSense / Help

### ISSUE THREAD

**Issue by iJungleboy** [microsoft/vscode-dotnettools#668]
### Describe the Issue

When code has `//` characters in the help text then IntelliSense looks broken.

![image](https://github.com/microsoft/vscode-dotnettools/assets/5321186/bf18e80a-b518-4ebd-a4b8-14205d5a9cfc)

### Steps To Reproduce

Create a `.cs` file like this:

```cs
public class VsCodeBug
{
  public void Test(string before, string problem = "see https://xyz.com", string after = null)
  {
    Test("before");
  }
}
```

Then over the call on `Test("before")` and you'll see the what's in the screenshot. 

### Expected Behavior

string literals should be self-closing and not bleed out into anything else. 

### Environment Information

VS Code 1.83.1

**Comment by tmeschter** [comment]
Moving to "area-roslyn" as this concerns colorization behavior.

**Comment by dibarbet** [comment]
Closing to track on the C# extension side - https://github.com/dotnet/vscode-csharp/issues/6654
