### ISSUE TITLE
[SUGGESTION] <Debugging Quick Watch Window>

### ISSUE THREAD

**Issue by lakani** [microsoft/vscode-dotnettools#669]
### Describe the feature you'd like

provide something that is similar to Quick Watch Window while debugging

**Comment by WardenGnaw** [comment]
@lakani You can find the `Watch` pane in the `Run and Debug` menu.
![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/d0cc270e-9ac5-4064-b9de-cc96215d080f)


See https://code.visualstudio.com/Docs/editor/debugging#_data-inspection

**Comment by lakani** [comment]
i know about it, and i'm actually use it, but its not as handy as Quick Watch in Visual Studio
