### ISSUE TITLE
[BUG] Is it able to choose a configuration for build/debug/run/test ?

### ISSUE THREAD

**Issue by ali50m** [microsoft/vscode-dotnettools#67]
### Describe the Issue

Question:
Is it able to choose/set a build configuration(**debug/release**) for build/debug/run/test in solution explorer/TestingTab?

It seems the project is always building with `dotnet build ${solutionfile} /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary` .

I tried to set something with tasks.json and launch.json, but no luck.

![image](https://github.com/microsoft/vscode-dotnettools/assets/9393831/befcc2e9-4bb4-4049-823b-818d427ebcb2)

![image](https://github.com/microsoft/vscode-dotnettools/assets/9393831/677804fe-f765-4ff6-a406-bde4d790dfed)

**Comment by kvenkatrajan** [comment]
Thanks for your inquiry. While the current extension does not have a user interface to to pick the configuration, release configuration is available through the terminal executing dotnet run at a project level.  Please use : https://learn.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio-code?pivots=dotnet-7-0#use-release-build-configuration

**Comment by simonferquel** [comment]
This is a show stopper for our internal usage of VS Code for C# projects at Unity unfortunately.
Please at least add a configuration setting for the plugin :)

**Comment by kvenkatrajan** [comment]
Thanks for your feedback and the perspective that its being widely used scenario for Unity. We are currently reviewing all incoming feature requests and are suring up the next list of features we are considering and appreciate your input. 

FYI -  @webreidi , @Michael-Eng , @sayedihashimi

**Comment by AlexeiNaabal** [comment]
> 

Would you please give me the link to manpage of the configuration that you mentioned?
It seems the c# dev kit extension (if you are reffering to this extension as the "plugin"?) does not have much config options on it's configuration panel (for vscode extension config id @ext:ms-dotnettools.csdevkit), I'm not sure if it is like adding a config file such as tasks.json or launch.json.

**Comment by jbevain** [comment]
We need to get this prioritized, it's pretty limiting for any project that uses more than the `Debug` or `Release` configurations.

Repro:

`dotnet new classlib`


Edit csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugiOS;DebugAndroid</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'DebugiOS' ">
    <DefineConstants>$(DefineConstants);IOS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'DebugAndroid' ">
    <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
  </PropertyGroup>

</Project>
```

Edit .cs:

```csharp
namespace BuildConfigurations;

public class Class
{
#if IOS
    public void DoiOS()
    {
    }
#elif ANDROID
    public void DoAndroid()
    {
    }
#else
    public void DoDefault()
    {
    }
#endif
}
```

There's no way to get code completion in the ANDROID or IOS code blocks that are simply greyed out.

**Comment by safield** [comment]
My solution has a custom build configuration to run tests. C# Dev Kit does not satisfy my use case until this issue is fixed.

**Comment by niguiecandy** [comment]
How long do we have to wait? This seems to be a very basic user scenario. I'm surprised to see that this wasn't considered important...

**Comment by AlexeiNaabal** [comment]
> How long do we have to wait? This seems to be a very basic user scenario. I'm surprised to see that this wasn't considered important...

I am too surprised by that, considering Visual Studio for MacOS is already announced stop support, let VSCode to be the officially supported C# development tool under such environment...
If the Code team not responding to this request even till the deadline, it will be very interesting. Does the MS and Code team trying to drive us to JetBrain or others?

**Comment by niguiecandy** [comment]
> Thanks for your feedback and the perspective that its being widely used scenario for Unity. We are currently reviewing all incoming feature requests and are suring up the next list of features we are considering and appreciate your input.
> 
> FYI - @webreidi , @Michael-Eng , @sayedihashimi

Apart from Unity game engine, changing active build configuration for C# solution is a **BASIC** user scenario. This issue should be regarded as urgent one, not as an Unity-related tiny inconvenience.

**Comment by sayedihashimi** [comment]
Having the ability to switch build configurations is pretty important, especially for apps which target more than one target framework or device. As C# Dev Kit matures, we should look to add improved support for settings such as the build configuration.

cc @kvenkatrajan @webreidi @Michael-Eng

**Comment by lifengl** [comment]
selecting solution configuration/platform is supported in CDK

**Comment by ylatuya** [comment]
Is there a link to the PR where support for selecting the active configuration has been added? I would like to know how to read the active configuration from a variable in launch.json to use it in the `program` path instead of hardcoding Debug or Release.
