### ISSUE TITLE
[SUGGESTION] <Create .Net project from 3rd party published .Net project templates>

### ISSUE THREAD

**Issue by r9guy** [microsoft/vscode-dotnettools#673]
### Describe the feature you'd like

extension is capable to Project Creation only from Microsoft's .net project templates.
it would be great to add in settings an option to create project from other publisher's templates as well.

![image](https://github.com/microsoft/vscode-dotnettools/assets/9428627/5f9660b5-e040-40eb-97df-2afb54236305)

### Alternatives considered

Avalonia project has created [.Net project template](https://github.com/AvaloniaUI/avalonia-dotnet-templates)s.
VS2022 works great with this ,however VS code doesn't.
to overcome this issue Avalonia team created button with their [extension ](https://github.com/AvaloniaUI/AvaloniaVSCode) which sits just below Microsoft's extension button.
as a result, we have 2 buttons. 
should Microsoft acknowledge 3rd party published extensions there will be no need for community members to create button extensions for project creation.

**Comment by smitpatel** [comment]
See https://github.com/microsoft/vscode-dotnettools/issues/48

**Comment by smitpatel** [comment]
This should be available for project in v1.8.14
