### ISSUE TITLE
[BUG] Running without debugger while default terminal profile uses zsh causes vsdbg to not be found

### ISSUE THREAD

**Issue by eyskog** [microsoft/vscode-dotnettools#678]
### Describe the Issue

Unless I change my default terminal profile to use Powershell, running a project without debugger attempts to execute a command which fails due to vsdbg not being found. The exe file is found with ls, but can not be run directly as the command attempts

### Steps To Reproduce

1. Set default profile to use zsh
2. Open a C# project, select a profile and press `ctrl + f5`
3. A command is printed to the integrated terminal and run (I replaced the actual username with [USERNAME]): `c:\\Users\\[USERNAME]\\.vscode\\extensions\\ms-dotnettools.csharp-2.9.20-win32-x64\\.debugger\\x86_64\\vsdbg.exe --interpreter=vscode --connection=a4bc2c5183b642199a00a455ab3d467f`
4. The output is `zsh: command not found: c:\Users\[USERNAME]\.vscode\extensions\ms-dotnettools.csharp-2.9.20-win32-x64\.debugger\x86_64\vsdbg.exe`

### Expected Behavior

The command should be runnable, either by making it work with zsh, by using the debug console, or by using Powershell if the OS is Windows

### Environment Information

- OS: Windows 11
- VS Code Version 1.84.0
- Extension Version 1.0.14

**Comment by WardenGnaw** [comment]
Moving to https://github.com/microsoft/vscode/issues/197253 as terminal profiles are handled by VS Code
