### ISSUE TITLE
[BUG] New version of C# devkit v1.0.14 constantly loads the processor, which leads to overheating of the laptop

### ISSUE THREAD

**Issue by timamus** [microsoft/vscode-dotnettools#680]
### Describe the Issue

New version of C# devkit v1.0.14 constantly loads the processor at 26%, which leads to overheating of the laptop on Windows 10. This leads to overheating and unexpected shutdown. This is not observed on the old version.

### Environment Information

- OS: Windows 10;
- VS Code v1.84.0;
- C# devkit v1.0.14.

**Comment by arkalyanms** [comment]
Tracked at https://github.com/dotnet/msbuild/issues/9922
