### ISSUE TITLE
[BUG] Creating new project does not do the same as dotnet new

### ISSUE THREAD

**Issue by eskility** [microsoft/vscode-dotnettools#684]
### Describe the Issue

If you try to create a new project using the gui you will not achieve the same result as dotnet new. An example of this is creating a new web core api, where you will basically miss the whole weatherapi example. I.e. no controllers folder. However, if you do dotnet new webapi you get the expected result.

### Steps To Reproduce

1. Create new project
2. select web api

### Expected Behavior

get the full starting point/example with the weather api.

**Comment by timheuer** [comment]
@eskility I think based on your comment you are expecting to see Controllers.  In current implementation, the templates exposed via the menus, use the minimal API pattern (`dotnet new webapi -minimal`) so the routes are in `Program.cs`

**Comment by smitpatel** [comment]
The improved Add New Project experience will allow users to configure parameters to template similar to how it is in dotnet new.
This is list of parameters shown for Web API
![image](https://github.com/microsoft/vscode-dotnettools/assets/1528107/b22a73dd-7daa-4655-881b-814fae02173b)

**Comment by smitpatel** [comment]
The fix is available in v1.8.14. User can configure parameters to get desired behavior.
