### ISSUE TITLE
Console.WriteLine Output does not appear in Debug Console 

### ISSUE THREAD

**Issue by ultra133** [microsoft/vscode-dotnettools#685]
Type: <b>Bug</b>

In Visual Studio (for Mac) you can use Console.Write to output certain variables or states in the Debug Console at runtime.
In VS Code these outputs (apparently) do not appear anywhere, which is a pity.

Extension version: 0.5.48
VS Code version: Code - Insiders 1.85.0-insider (Universal) (9aacac648821b5c9c1a7192ac9d44c50af6fe241, 2023-11-06T05:35:16.817Z)
OS version: Darwin arm64 23.1.0

> VS bug [#1914838](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1914838)

**Comment by timheuer** [comment]
@ultra133 can you tell us what you have in this setting: 
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/f9b4c25b-a322-41b7-bdab-d9df64a40c86)

**Comment by ultra133** [comment]
It is set to `internalConsole` (default).

I double checked every configuration and sat a breakpoint on `Console.WriteLine`.

When i debug the app on MacCatalyst or iOS Simulator or iOS physical device, the output does appear in the Debug Console.

It does **not** appear on Android simulator!

**Comment by timheuer** [comment]
Thanks for confirming more info @ultra133 .. FYI @maddymontaquila are we aware of MAUI + Android debugging weirdness with console?

**Comment by zwikk** [comment]
I have the same issue, and it seems to be related to the project configuration. When I run my MAUI project in ```Debug``` mode, all is good, logging appears in the output. When I switch to a custom ```Debug-Mock``` configuration with DEBUG enabled, no logging at all.

My Debug-Mock configuration looks like this:

```xml
<PropertyGroup Condition="'$(Configuration)' == 'Debug-Mock'">
  <DefineConstants>DEBUG;MOCK;</DefineConstants>
</PropertyGroup>
```

**Comment by ultra133** [comment]
No, I can replicate this with a simple `dotnet new maui` project, without any special configuration. 
Just add a `Console.WriteLine("Hello");` in `MauiProgram.cs`, set a breakpoint and run it on the Android simulator.

The 'Hello' does not show in Debug Console.

**Comment by zwikk** [comment]
You are right, Console.WriteLine doesn't work in Android in Debug mode. Have you tried Debug.WriteLine? That seems to work.

My problem seems to be another issue then, no logging at all (no assembly load, no Thread finished messages, etc), when running in a custom debug configuration.

**Comment by ultra133** [comment]
Yes, you are right, but the thing is that I use Console.WriteLine more for "debugging" the release build of an app, to monitor the program flow and the state of the variables. Debug.WriteLine will not work in the release build.

**Comment by TheSpydog** [comment]
I'm getting this same behavior with SDK 8.0.100 but with an iOS Device. `Console.WriteLine` works as expected in an iOS Simulator, but not when testing on a physical device. The only way I've found to see the WriteLine output is by opening up the `Console` app on my Mac and selecting my iPhone, then enabling message streaming and filtering for my application.

**Comment by AllenD-MSFT** [comment]
@ultra133 , we've recently made improvements in MAUI DevKit debugging specifically for targeting the latest .NET8 SDK. Can you update to the latest .NET SDK and the latest MAUI DevKit to determine if this issue is still occurring? TIA

**Comment by ultra133** [comment]
I'm on holiday, cannot check this before April 8th. Maybe someone else?

**Comment by ultra133** [comment]
Okay, I've tried it out. Whatever you changed, it had no effect on the issue described above. The bug is still there. There is no change.
If you have an interest in fixing the bug, maybe you should just try it yourself. it's very easy to reproduce.

**Comment by breakstring** [comment]
Last week, my VSC was still able to develop and debug MAUI programs on the Android emulator under Mac, but after I updated some components on my computer over the weekend, such as the .Net SDK and VSC, I could no longer see the debugging information in the Debug Console. At the same time, my Cursor IDE could no longer debug MAUI programs either.

After some attempts, I downgraded the .Net MAUI extension in VSC to v0.9.7, which is a version from a month ago, and now I can see the debugging information in the Debug Console again, and Cursor can also debug MAUI programs normally.

The above information is for reference.


BTW, I find it hard to believe that such a supposedly cross-platform framework as .Net MAUI would have such unprofessional developers at Microsoft now, who seem not to have tested it on any other platforms at all... It's just like the issue I encountered a few days ago where the hamburger icon could not be displayed in light theme on Android (because they hardcoded it to white in the default style.xml)... These are issues that have been around for a long time if you search through the GitHub Issues. I can only use the word SAD to describe my current feelings.

**Comment by emaf** [comment]
This is now fixed for iOS and Android in the `prerelease` channel.

You'll still face this with MacCatalyst, which is being tracked in https://github.com/microsoft/vscode-dotnettools/issues/1090.

**Comment by tpitman** [comment]
I am not able to see any debug output in the debug console from Console.WriteLine on iOS on a Mac. If this is fixed, how do I get the fix? I am using the latest release VSCode and all extensions. I also tried switching to the latest pre-release version. That didn't fix it.

When I debug for Android, I do get the console.writeline output. This seems backwards from what I read above, but still is an issue. Please advise.

**Comment by emaf** [comment]
@tpitman I just gave this a quick try using the latest prerelease version of the MAUI and C# Dev Kit extensions (1.3.24 and 1.10.12) and it worked for me.

Keep in mind that the console and debug outputs are printed differently. This is what I got (I have VSDbg enabled, `Settings -> Extensions -> .NET MAUI -> Use VSDbg`):
![image](https://github.com/user-attachments/assets/0cc69fca-a4b6-4cca-8bfd-350b751af5bd)

Please report a separate issue if the console output is still not showing up on the Debug Console for you, including the versions of the extensions and SDK you are using, as well as if you have VSDbg enabled.

**Comment by tpitman** [comment]
@emaf Not sure what to say. I also have the exact same versions and setting as you and Console.WriteLine does not.

I did post an issue here: https://github.com/microsoft/vscode-dotnettools/issues/1431
