### ISSUE TITLE
[BUG] No C# project is currently loaded. Please create a C# project in order to debug.

### ISSUE THREAD

**Issue by Dor-bl** [microsoft/vscode-dotnettools#687]
### Describe the Issue

Unable to debug C# projects on apple M2

### Steps To Reproduce

open a .cs file , hit the F5 button to debug and receive the error:
`No C# project is currently loaded. Please create a C# project in order to debug. `

### Expected Behavior

Been able to debug projects

### Environment Information

- OS: MacOS M2
- VS code: 1.84.0 (Universal)
- C# Dev kit : v1.1.5

More VS Code info:
Version: 1.84.0 (Universal)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:30:19.406Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

```[tasklist]
### Tasks
```

**Comment by timheuer** [comment]
@Dor-bl Do you have any csproj in the workspace?

**Comment by Dor-bl** [comment]
Correct

**Comment by timheuer** [comment]
@Dor-bl Thanks, is there any errors emitted when you open the workspace in the "C#" or "C# Dev Kit" output logs?

**Comment by Dor-bl** [comment]
I see this from "#C Dev Kit - Test Explorer"
```

Created Test Controller
Using vstest from dotnet sdk in [/usr/local/share/dotnet/sdk/7.0.403].
Initialized Test Explorer Server [89248]
Test Store Folder: /Users/blayzer/Library/Application Support/Code/User/workspaceStorage/b449b26b95a0e78d3ac0fa9651d9a0d1/ms-dotnettools.csdevkit
Test data store opened in 0.007 sec.
Initialized project system provider.
1 projects added, 0 changed, 0 removed.
Scheduling discovery: /Users/blayzer/workdir/dotnet-client/test/integration/bin/Debug/net48/Appium.Net.Integration.Tests.dll [1699276487104]
========== Starting test discovery ==========
System.IO.FileNotFoundException: Could not find 'mono' host. Make sure that 'mono' is installed on the machine and is available in PATH environment variable.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.DotnetHostHelper.GetMonoPath() in /_/src/Microsoft.TestPlatform.CoreUtilities/Helpers/DotnetHostHelper.cs:line 93
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DefaultTestHostManager.cs:line 217
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 226
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 149
========== Test discovery aborted: 0 Tests found in 75 ms ==========
0 tests discovered from  in 75.0184 ms

```

**Comment by Dor-bl** [comment]
@timheuer, I'll try installing 'mono' first and update if issue persist.

**Comment by WardenGnaw** [comment]
@Dor-bl `mono` should not be needed for the F5 scenario. 

@tmeschter Are there specific logs to see why the project system isn't registering the csproj?

**Comment by Dor-bl** [comment]
@WardenGnaw, after installing `mono` I'm able to run the unit tests.

**Comment by timheuer** [comment]
Thanks for confirming @Dor-bl.  @WardenGnaw I think this was happening because the unit test adapter being used here had unsatisfied dependencies.  @Dor-bl is this a Xamarin project?

**Comment by Dor-bl** [comment]
@timheuer, it is.

You can check out the project repository in case you need more info:
https://github.com/appium/dotnet-client

**Comment by timheuer** [comment]
Thanks, this makes sense -- Xamarin still relies on some mono aspects.

**Comment by Dor-bl** [comment]
So I guess I'll need to find the time and upgrade the project to MAUI 😬

**Comment by timheuer** [comment]
> So I guess I'll need to find the time and upgrade the project to MAUI 😬

https://aka.ms/dotnet-upgrade-assistant 😜

**Comment by Dor-bl** [comment]
@timheuer, what about this error I get when trying to debug my project?
`'/Users/blayzer/workdir/dotnet-client/test/integration/Appium.Net.Integration.Tests.csproj' does not support debugging. No launchable target found.`

**Comment by timheuer** [comment]
That I'm not sure of -- because this is mono-driven I wonder if this is an issue.  @peterwald anything known about this?

**Comment by peterwald** [comment]
> That I'm not sure of -- because this is mono-driven I wonder if this is an issue. @peterwald anything known about this?

I don't believe we have support for debugging mono projects at this time.

**Comment by Dor-bl** [comment]
So what are my options if I want to debug Mono projects on macOS?

**Comment by Dor-bl** [comment]
I ended up upgrading the project to `.NET 6`. It was easier than I thought actually.
I'm just missing the tests results summary with counters

**Comment by maiquitome** [comment]
I removed asdf and installed it directly from the microsoft website and it worked for me 🎉
