### ISSUE TITLE
[SUGGESTION] Selecting the suggested debugger for .NET MAUI

### ISSUE THREAD

**Issue by rogersm-uwosh** [microsoft/vscode-dotnettools#688]
### Describe the feature you'd like

Whenever I'm working on a .NET MAUI project and want to run it, it displays a list of debuggers, with .NET MAUI marked as suggested. Since that's what I want, and apparently it had some way of deducing that, is there anyway that it could *remember* that choice -- or let me set it -- rather than making me re-choose each time I run a project?

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1999730">1999730</a>

**Comment by emaf** [comment]
This is now fixed in the pre-release channel. Versionins needed for this to work:
- C# v2.29.11
- C# Dev Kit v1.6.2
- .NET MAUI v0.11.87

**Comment by mprogers** [comment]
Excellent! I'm going to be teaching .NET MAUI with VSC again this fall, so I'm looking forward to this. Just let me know that hot-reloading is coming and I will be one happy camper!
