### ISSUE TITLE
t:InstallAndroidDependencies does not work

### ISSUE THREAD

**Issue by durandt** [microsoft/vscode-dotnettools#689]
Type: <b>Bug</b>

Documentation is terrible if you are moving from VS for mac to VSCode and only assumes you have to install everything. So it's up to us finding out which steps may be skiped or not. 

One step (which consequences/need) is not really greatly documented is:
https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code#using-installandroiddependencies

When I run dotnet build -t:InstallAndroidDependencies i get the error:
```
MSBuild version 17.6.1+8ffc3fe3d for .NET
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```
Which is weird: I don't even know what I am trying to do but I guess this command will install the Android SDK ? Then why would it need a solution or project file?

Anyway, I give it a project file but it only gives the following error:
```
error MSB4057: The target "InstallAndroidDependencies" does not exist in the project.
```

Many people will be moving from existing MAUI projects and from VS for mac. Please take that into account when writing documentation, especially since few of us will make the move willfully with regard to VS for mac retirement. (Not that we are against VSCode, but it's always painfull to move from a working developing environment)

Extension version: 0.4.9
VS Code version: Code 1.84.1 (Universal) (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:37:18.666Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016:30880769
dsvsc017cf:30880893
aa_t_chat:30882232

```

</details>

> VS bug [#1914083](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1914083)

**Comment by mauroa** [comment]
Hi @durandt. It looks like you are missing some information in the command, like the target framework. There's an example of the full command in the macOS section of the docs, however the documentation could be clearer. See below:

```
If you'd like to debug to Android in Visual Studio Code, you also have to:
a) Install [Microsoft OpenJDK 11](https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-11).
b) Install the Android SDK. You can acquire the correct versions of the Android SDK and build tools by creating a new .NET MAUI project (dotnet new maui) and running the following command in your terminal:
dotnet build -t:InstallAndroidDependencies -f:net7.0-android -p:AndroidSdkDirectory="<ANDROID SDK DIRECTORY>" -p:AcceptAndroidSDKLicenses=True
On macOS, the suggested Android SDK directory value is $HOME/Library/Android/sdk.
```

We are working on improving the documentation in general so all the steps become easier and clearer.
Thanks.

**Comment by durandt** [comment]
Ok thank you. 

I there will be a VSCode extension in the future to help install and manage Android SDK. I'm all for command-line stuff usually but I've learned to like the GUIs in Android Studio/Visual Studio/Rider that help managing the cumbersome Android dependencies.

**Comment by emawby** [comment]
I run `dotnet build -t:InstallAndroidDependencies -f:net7.0-android -p:AndroidSdkDirectory="$HOME/Library/Android/sdk" -p:AcceptAndroidSDKLicenses=True` and it succeeds, but when I try to build I get 

> `error NETSDK1082: There was no runtime pack for Microsoft.Android available for the specified RuntimeIdentifier 'osx-x64'`
And 3 other similar errors. I have not found a workaround yet

**Comment by mauroa** [comment]
The docs for this have been updated, so I'm closing this issue. If it's still unclear for you, please let us know. Thanks for your feeback.
