### ISSUE TITLE
fail to debug

### ISSUE THREAD

**Issue by git1453** [microsoft/vscode-dotnettools#69]
Type: <b>Bug</b>

I create a new console,but i could not use the Debug in SOLUTIION EXPLPRER. And in terminal it tips: "executing task:dotnet build 'd:\Personal\Respo\C#DevKit\ConsoleApp1\ConsoleApp1.csproj' /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary  
Incorrect parameter format - Command".The Task has been running, no end, no build.And dotnet command is right , could work.

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.23471
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.33GB free)|
|Process Argv|--crash-reporter-id 20f01959-cb72-4355-a0e4-fe148d3fb74a --crash-reporter-id 20f01959-cb72-4355-a0e4-fe148d3fb74a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpath:30739704

```

</details>

```[tasklist]
### Tasks
```

**Comment by WardenGnaw** [comment]
Does right clicking on the solution explorer and running `Build` work?

Could you also share which  terminal application are you using? You can also share a screenshot by overing over the terminal task in the terminal pane of VS Code.
![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/d38529a2-1e44-40f7-bbe8-2637d33bbfe3)

**Comment by git1453** [comment]
Does right clicking on the solution explorer then Build or ReBuild, but task just running and could not stop




&nbsp;


..........
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrew ***@***.***&gt;; 
发送时间: 2023年6月9日(星期五) 凌晨1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode-dotnettools] fail to debug (Issue #69)






在解决方案资源管理器上单击右键并运行构建工作吗？

您能分享一下您使用的是哪个终端应用程序吗？您还可以通过覆盖VS Code的终端窗格中的终端任务来共享屏幕截图。


—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by git1453** [comment]
I maybe find the reason in the OUTPUT of C# Dev Kit. But Why the Build Action need network?&nbsp;



ConsoleApp1.csproj
```
<Project Sdk="Microsoft.NET.Sdk"&gt;

&nbsp; <PropertyGroup&gt;
&nbsp; &nbsp; <OutputType&gt;Exe</OutputType&gt;
&nbsp; &nbsp; <TargetFramework&gt;net7.0</TargetFramework&gt;
&nbsp; &nbsp; <ImplicitUsings&gt;enable</ImplicitUsings&gt;
&nbsp; &nbsp; <Nullable&gt;enable</Nullable&gt;
&nbsp; </PropertyGroup&gt;

</Project&gt;


```


My Environment





&nbsp;


..........
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrew ***@***.***&gt;; 
发送时间: 2023年6月9日(星期五) 凌晨1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode-dotnettools] fail to debug (Issue #69)






在解决方案资源管理器上单击右键并运行构建工作吗？

您能分享一下您使用的是哪个终端应用程序吗？您还可以通过覆盖VS Code的终端窗格中的终端任务来共享屏幕截图。


—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by WardenGnaw** [comment]
> Why the Build Action need network?

If you reference external packages in your project, it will use `dotnet restore` to download the packages.

**Comment by git1453** [comment]
I replied by email ,I didn't know the picture will be invisible. I'm sorry.
I add the pictures and reply with Github, hoping to  see the pictures.
<img width="1015" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/83624279/f740d61f-1677-4906-ad35-6429b66b9fdf">
The task will not  end unless I close it.
![image](https://github.com/microsoft/vscode-dotnettools/assets/83624279/c2152241-c4b1-4f26-91fb-6b23736ce519)
my environment
![image](https://github.com/microsoft/vscode-dotnettools/assets/83624279/465cc464-79da-4218-ab78-6571d78ad3e6)



> If you reference external packages in your project, it will use to download the packages.

But I didn't ,you can see the csproj and sln.

<img width="671" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/83624279/43745bf7-52c9-4bb5-bdc2-8c4418862ffa">

<img width="1094" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/83624279/356be500-44a0-4037-93d3-ffa88ee9a92c">

**Comment by WardenGnaw** [comment]
Adding area-project because it seems like the build is hanging.

**Comment by Michael-Eng** [comment]
@git1453 I can't repro this with the latest version of C# Dev Kit. can you confirm if this is working for you now?
