### ISSUE TITLE
Debugging canceled: MAUI SDK not found. 

### ISSUE THREAD

**Issue by durandt** [microsoft/vscode-dotnettools#690]
Type: <b>Bug</b>

After opening a .sln file from a .NET 7 MAUI Solution created one year ago with Visual Studio for mac, VS Code wrongfully shows the following error message:
```
MAUI SDK not found. 
```

Here is my `dotnet workload list`
```
$ dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-ios                   7.0.100/7.0.100        SDK 7.0.300        
maui-android               7.0.100/7.0.100        SDK 7.0.300        
maccatalyst                16.4.7124/7.0.100      SDK 7.0.300        
maui                       7.0.100/7.0.100        SDK 7.0.300        

Use `dotnet workload search` to find additional workloads to install.

Updates are available for the following workload(s): maui-ios maui-android maccatalyst maui. Run `dotnet workload update` to get the latest.
```

(No one knows why it says `Updates are available` although i just installed the workloads)

This is the output from the .NET MAUI extension when opening the project:
```
RROR ExitCode(1)
Details

.NET MAUI SDK verification failed with an unexpected error: Failed to retrieve the .NET SDK information.
If you cannot solve this problem, please report an issue from the Help menu.
 
user preferred path: /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home
JAVA_HOME: /Users/RAY_DACTED/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
Java SDK: custom [installed]
Android service Java SDK found: /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home
user preferred path: /Users/RAY_DACTED/Library/Developer/Xamarin/android-sdk-macosx
ANDROID_HOME: /Users/RAY_DACTED/Library/Developer/Xamarin/android-sdk-macosx
Android SDK: shared with Visual Studio [installed]
Android service Android SDK found: /Users/RAY_DACTED/Library/Developer/Xamarin/android-sdk-macosx
Android SDK recommended required components:
	platform-tools  installed
	cmdline-tools  installed
```

When creating a new project with `dotnet new maui` i get the same targetframeworks: 
```
<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
```
as in my existing project file but the newly created project file runs properly in VSCode with the MAUI extension when hitting debug. 

Creating a new issue since #523 was closed but this issue still persists to date. 

Extension version: 0.4.9
VS Code version: Code 1.84.1 (Universal) (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:37:18.666Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016:30880769
dsvsc017cf:30880893
aa_t_chat:30882232

```

</details>

**Comment by emaf** [comment]
@durandt as you mentioned https://github.com/microsoft/vscode-dotnettools/issues/523, do you have multiple files which extension end in _proj_ (i.e., *.csproj, *.proj, etc.) in the same folder?

I'm just trying to understand if this is a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/523, or if this is a different scenario.

**Comment by durandt** [comment]
@emaf here is my project structure:

```
./Liuapp.sln
./Liuapp.ios.sln
./Liuapp/Liuapp.csproj
./Liuapp/Liuapp.ios.csproj
```

I was going to answer "No, I only have two different solution files" but of course I also have two different csproj files so I will try the fix from #523 asap.

**Comment by emaf** [comment]
Yeah, then this is probably a dupe of #523 , but let's keep this one open until the fix is published to the prerelease channel and you can test it.

**Comment by durandt** [comment]
Hi, 

I tried removing the extra solution & project files and it works with the current MAUI extension. So I am pretty confident the prerelease will fix it, but I'll wait and try it. 
Thank you for your quick replies!

Best regards,

**Comment by emaf** [comment]
Hey @durandt, have you had a chance to try the 0.6.6 version available on the prerelease channel?

**Comment by durandt** [comment]
Hi @emaf, 

Apologies for the delayed reply: Yes 0.6.6 fixed the issue for me. Thanks!
