### ISSUE TITLE
Creating .NET MAUI projects

### ISSUE THREAD

**Issue by nikolavn** [microsoft/vscode-dotnettools#694]
### Describe the feature you'd like

This is not exactly a feature request rather I am looking for information about the appropriate approach for handling templates within Visual Studio Code, particularly concerning the creation of .NET MAUI projects. Presently, we are using templates to generate such projects in Visual Studio for Mac. However, as it will be retired soon, we aim to transition these processes to Visual Studio Code.

For the time being we are launching the dotnet process in the background and passing the requisite parameters. I'd appreciate it if you could share any recommended practices for the initiation of these templates within Visual Studio Code.

### Alternatives considered

While exploring alternatives, we examined the WindowsTemplateStudio (we are already using WebTemplateStudio for other projects) but it doesn't offer .NET MAUI templates. Furthermore, it appears that no equivalent to VisualStudio.TemplateEngine is available for Visual Studio Code.

### Environment Information

- OS: MacOS

**Comment by smitpatel** [comment]
You should be able to create MAUI projects in C# dev kit if you have MAUI workload installed and .NET Maui extension for VS Code installed. (Link to extension https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-maui)

Let us know if there is anything else missing from creating project perspective.

**Comment by nikolavn** [comment]
Thanks for getting back but my question is more from extenders' point. We have our own VS Code extension where would like to replicate to some extent the project creation experience, which you get using C# Dev Kit MAUI extension. 

So I'm more interested in any extension points we could use or any available APIs that would allow us to interact with the project system.

**Comment by smitpatel** [comment]
The project creation experience is powered by C# dev kit only. There is some interaction regarding, if MAUI extension/workload exists but MAUI extension is not contributing to the project creation experience. The project creation experience is not extensible atm but we are working towards making it depend on TemplateEngine which would provide some flexibility.

Can you tell us what exactly scenario you are trying to support? The project creation experience doesn't really interact with project system directly. So even in new experience, I don't see that changing.

**Comment by nikolavn** [comment]
We'd like to create a project using our own custom templates. What we do currently is pack the templates in a NuGet, then use the dotnet CLI within VS Code to install the templates and subsequently create a project. 

We are using the Web Template Studio with VS Code to create custom Blazor and ASP.NET Core projects and I was wondering whether there will be something similar for MAUI as running the CLI behind the scenes doesn't look like the best approach.

**Comment by smitpatel** [comment]
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/48?
We plan to add support for custom templates by picking up whatever templates are installed on user machine. It would allow to use custom templates from C# dev kit directly without having to run dotnet run. (You would still need to install those templates) Does that cover your scenario?

**Comment by nikolavn** [comment]
This looks like it will work out for us. 
Just one more thing, will the create new project experience be customizable? We have some custom parameters that we need to pass to the templates, and we'll need a way to do that.

**Comment by smitpatel** [comment]
Yes, when we show custom project templates in the template selection list, we would also light up the option template takes. Further these options can be customized (visibility/default value) just for C# dev kit.

**Comment by nikolavn** [comment]
Sounds great, thanks.
