### ISSUE TITLE
[BUG] Toggle Line Comment doesn't work on Shader files

### ISSUE THREAD

**Issue by wonkee-kim** [microsoft/vscode-dotnettools#702]
### Describe the Issue

After I install this extension, I can't Toggle Line Comment. (Both of shortcut (Cmd + /) or Command-Toggle Line Comment)
This still works on C# files.

### Steps To Reproduce

1. Open any shader file in Unity project
2. Select a line and Toggle Line Comment
3. Nothing happens.

### Expected Behavior

The line should toggle comment out.

### Environment Information

OS: [Mac Sonoma 14.0]
VS Code Version: [1.84.1]
Extension Version: [0.9.3]

**Comment by jbevain** [comment]
Thanks for reporting this issue. We have a fix that will ship in the next preview of the Unity extension.

**Comment by sailro** [comment]
Available in 0.9.4
