### ISSUE TITLE
Can't debug custom configuration in VS Code with net7.0-android project

### ISSUE THREAD

**Issue by stefan89** [microsoft/vscode-dotnettools#703]
How should a custom configuration look like to be able to debug in Visual Studio Code for a dotnet 7 Android project?

When I use the default Debug configuration, the debugger succesfully attaches. When I create a custom configuration which I also want to debug, the debugger never attaches.

I tried this so far:
```
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Different-Debug|AnyCPU' ">
        <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
	<DebugSymbols>true</DebugSymbols>
	<DebugType>full</DebugType>
	<Optimize>false</Optimize>
    </PropertyGroup>
```

**Comment by mauroa** [comment]
Hi @stefan89, do you have a launch.json to define your custom debug configuration? You also need to be sure to specify "maui" as the configuration type, in order to let MAUI call the right entry points. Find an example below:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Different-Debug",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "configuration": "Debug"
        }
    ]
}
```

**Comment by stefan89** [comment]
@mauroa yes I am using a custom launch.json

It looks like this:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Different-Debug",
            "configuration": "Different-Debug",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }
    ]
}`

On iOS the debugger just works fine for custom build configurations in VS Code.

**Comment by mauroa** [comment]
This should be fixed on latest .NET MAUI pre-release. Please give it a try and feel free to reopen the issue in case you still experience the same or similar problems.
Thanks for your feedback and help.
