### ISSUE TITLE
Incompatable dotnet use

### ISSUE THREAD

**Issue by Zxynine** [microsoft/vscode-dotnettools#706]
Type: <b>Bug</b>

It appears that C# dev kit keeps trying to use the x86 dotnet version on my computer, and will not work giving the error:
2023-11-09 18:49:14.046 [info] The .NET SDK installed on the machine is targeting a different platform (win10-x86) with the C# Dev Kit (visualstudio-projectsystem-buildhost.win32-x64), and are incompatible.

I have tried to remove the x86 dotnet, as I do have the x64 version installed in hopes it would switch to using it, but it does not, instead it says that no dot net version is found. I checked my system env variables and I only have one pointing to the x64 version. I have tried to uninstall all of the extensions relating to C# and re installing them, I get the same problem. 

Extension version: 1.0.14
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (6.96GB free)|
|Process Argv|D:\\GameDesign\\UnityProjects\\Masquerade -g D:/GameDesign/UnityProjects/Masquerade/./Packages/com.unity.ai.navigation@1.0.0-exp.4/Editor/WIP/NavigationWindow.cs:108:0 --crash-reporter-id a2fa294b-9642-49c9-8688-04bbdfd3c17f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30882109
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30879912
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30880770
aa_t_chat:30882232

```

</details>

**Comment by Jandriv** [comment]
I have the same problem, do you have any solutions yet?

**Comment by doodlebunnyhops** [comment]
Check your system/user environment variables - perhaps path still includes x86 or you don't have path set to x64. What do you get with windows cmd `where.exe dotnet`?

**Comment by mbk25** [comment]
çözümünü buldunmu

**Comment by Michael-Eng** [comment]
Closing this given the inactivity

**Comment by WilliamDormer** [comment]
I have the inverse problem. I want to use x86, and I have my SDK already downloaded and seemingly working with that, but the intellisense from the C# Dev Kit is trying to use x64 instead, not sure why. So then they conflict.

**Comment by xiaoyiwei199** [comment]
Same Problem

**Comment by abelbraaksma** [comment]
I've a SnapDragon Omnibook, which means it uses ARM-64. In my case, it is worse. My system should default to use ARM64, even though I also have x64 installed. While I can target the x64 myself, it appears that the vscode-dotnettools do not recognize the VSCode setting in  `.vscode/settings.json`:

```
"dotnet.server.path": "C:\\Program Files\\dotnet\\x64\\dotnet.exe"
```

I'll search for another workaround.
