### ISSUE TITLE
Add FAQ link to notification of project type support

### ISSUE THREAD

**Issue by rexkenley** [microsoft/vscode-dotnettools#710]
### Describe the feature you'd like

A question actually, does this extension allow us to work on .net framework 462 projects?

We primarily work with d365 plugins projects.

**Comment by kvenkatrajan** [comment]
While the C# dev kit extension currently doesnt support loading .NET framework projects, the solution could be directed to the C# extension for loading via the Prefer CSharp Extenson setting. Additional documentation can be found here :
https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_project-system

**Comment by fforjan** [comment]
It would work if your project are move to the csproj SDK type - i.e. move the SDK and the framework is net472 in our case.
Note it would use the dotnet  tool to build and not msbuild which means that some features would not be available - COM component or building C++ project.

**Comment by kvenkatrajan** [comment]
That is correct, C# dev kit only supports sdk style projects a the moment and is curently using dotnet build.

thanks for your feedback - Can you file another issue for tracking unable to build COM component or C++ project within sdk style projects? Thanks!

**Comment by louisik1** [comment]
It would be great if you folks could make it very obvious from the beginning, when VS Code recommends installing this extension, "At this time, C# Dev Kit does not support .NET Framework projects."   It should literally give some indication of this somewhere here 

![image](https://github.com/microsoft/vscode-dotnettools/assets/491335/c14d926c-0483-478b-851d-6cc7fde5f62e)

so other developers don't waste 30 minutes of their time trying to figure it out.

**Comment by timheuer** [comment]
@louisik1 the VS Code extension view gives limited space to put text -- we have this information in the documentation: https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_what-project-types-are-currently-supported -- we could better link to this from the README which displays in VS Code extension manager.

We do, however, give notification in these scenarios:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/c1f0a7b7-f1dc-4fdf-8763-d918e7a5037f)

Example of what you should have seen:

https://github.com/microsoft/vscode-dotnettools/assets/4821/33ea1261-03fb-4eaa-a1a6-5aba2b1db2a3

**Comment by louisik1** [comment]
I appreciate the response. I saw all the things you've included, but I have never heard the term "SDK Style" in regards to projects. That sounds like someone is building something like a Windows SDK extension. I keep an eye on Reddit and other places and I've never seen that phrase used. The standard terminology (in documentation, in Visual Studio, in community discussions) for the past ten years has been ".NET Core or .NET (not .NET Framework)"

"SDK Style" is completely ambiguous in the context of the images/workflow you've shown (which is what I and other devs are experiencing). I understand limited space and user interface, I deal with it on a daily basis as a developer, but the examples you've provided do have enough space for some clarity (or simply sticking with standard nomenclature).

Best wishes,
Louis


(via phone)
________________________________

**Comment by timheuer** [comment]
Thanks @louisik1 -- SDK Style is something we've talked about a lot in .NET Core, I'm surprised you hadn't come across it yet as it is in our documentation a lot...although as we've seen more adoption of .NET 5+ it certainly is fading to just refer to versions.  It's the default project structure for .NET Core, but a .NET Framework app _can_ be SDK style as well, hence the terminology. (see: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview)

What would help better here in that message for you? We wouldn't explicitly say Framework here given that you can have .NET Framework projects that are, in fact, SDK style. We discussed this warning message a bit on the team and felt this is the most accurate without explicitly saying Framework wasn't supported, which wouldn't be totally accurate.

Would a "Learn more..." link in that notification have helped taking you to the documentation https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_what-project-types-are-currently-supported

**Comment by louisik1** [comment]
Do you think you could make the two words "SDK-style" a link to the link you've provided? I would have clicked on that in a microsecond to understand what it meant.  Otherwise yes, a 'Learn more..' would be my second choice.

Either of those will save a lot of folks from going down a road they'll have to back track from.

I was really looking forward to trying the extension, it looks great.  We're still tied to 4.8 in VS and I occasionally take a look at what the experience would be like in VSC.  Unfortunately it hasn't hooked me in.  I look for things like the right-click menu in VS on solutions and projects.. 'build, rebuild, clean, publish, preview publish, add..., analyze, git..., project dependencies, set as startup, properties', etc.  I don't understand why all those seemingly required tasks have been obfuscated away.  So, alas, I keep returning to VS.  I know all of that is probably beyond your responsibility, but thanks for letting me vent.

Best wishes,
Louis


________________________________

**Comment by timheuer** [comment]
Thanks @louisik1 inwill convert this big to a better link/message in the notification. 

As to NETFX 4.8 the extension will only target SDK projects which are primarily NET6+. Maybe we can help you migrate ;-) https://aka.ms/dotnet-upgrade-assistant
