### ISSUE TITLE
[SUGGESTION] Allow integration of 3rd party CLI Project Templates inside VS Code Create .NET Project option

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/vscode-dotnettools#715]
### Describe the feature you'd like

Allow integration of 3rd party CLI Project Templates inside VS Code Create .NET Project option.

For now, only the Microsoft-provided templates are listed. Refer to the screenshot below.

A lot of useful templates are out there to work with .NET.

![image](https://github.com/microsoft/vscode-dotnettools/assets/81947404/57deacf3-7030-43f6-a997-f3e58f52d65d)

### Alternatives considered

Use the Terminal to create a project with CLI, which can be cumbersome.

### Environment Information

- OS: Windows 11 23H2 (10.0.22631.2506)
- VS Code: 1.84.2
- .NET: 8.0.100-rc.2.23502.2

**Comment by smitpatel** [comment]
Custom user installed project templates should be available in v1.8.14
