### ISSUE TITLE
Cannot find .NET framework

### ISSUE THREAD

**Issue by dmauro** [microsoft/vscode-dotnettools#720]
Type: <b>Bug</b>

I'm not sure how to reproduce this exactly because on one machine it works, and the other it doesn't. Same project files, same versions of extensions and .NET installed. I'm seeing this error in the Projects output:
```
[info] It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64

2023-11-14 13:45:22.237 [info] Project system initialization finished. 0 project(s) are loaded, and 16 failed to load.
```

Extension version: 1.0.14
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.94GB free)|
|Process Argv|--crash-reporter-id a3c9ce93-2481-41bd-8baf-1c1671adfb32|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by dmauro** [comment]
Some additional context: this is happening in a Unity projected which _is_ using v2.0.22 of the new VS integration to generate all of the project files (everything set up according to https://code.visualstudio.com/docs/other/unity).

**Comment by sailro** [comment]
cc @jbevain 

Context: https://forum.unity.com/threads/microsoft-previews-unity-extension-for-visual-studio-code.1468913/page-2#post-9473719

**Comment by sailro** [comment]
@dmauro we've discussed your issue and it's surprising to see a reference to `.net 6` in a Unity project. Do you have anything in particular like an `AssetProcessor` that would participate in project generation? Or direct reference to .net assemblies in your project?

I imagine that working machines simply have a .NET 6 SDK already installed. So if you install such an SDK yourself, it should work.

But could you share your generated C# projects with us (`.csproj` files only) so we can have a look ?

You can send everything to vstusp[at]microsoft[dot]com

Thanks!

**Comment by dmauro** [comment]
I did try installing various .NET 6.0 SDKs (including specifically the 6.0.0 it wants) to no effect. I will look into see if I can find any AssetProcessors that might be doing anything. Nothing comes to mind but perhaps there's something in there I wasn't aware of. In the meantime I'll regenerate those csproj files for VSCode and email some to you. Thank you!

**Comment by Michael-Eng** [comment]
@dmauro what does dotnet.exe --list-sdks show from the terminal inside VS Code? 

VS and VS Code are designed differently. VS (devenv.exe) uses .NET Framework while C# Dev Kit uses the .NET you installed - but we have to be able to find it. The most common problem is that .NET isn't installed to a place where we can find it (like on the path).

**Comment by dmauro** [comment]
```
6.0.417 [C:\Program Files\dotnet\sdk]
6.0.417 [C:\Program Files\dotnet\sdk]
7.0.403 [C:\Program Files\dotnet\sdk]
7.0.403 [C:\Program Files\dotnet\sdk]
```

**Comment by Michael-Eng** [comment]
@dmauro Is dotnet.exe in your path and available in the terminal window from VS Code? How did you install .NET?

**Comment by dmauro** [comment]
> @dmauro Is dotnet.exe in your path and available in the terminal window from VS Code? How did you install .NET?

I have tried adding `C:\Program Files\dotnet` to my path (didn't seem to help after a restart) but left it there. And yes, I got the entries listed above by typing `dotnet.exe --list-sdks` in the VSCode terminal. I installed .NET by downloading the SDK installers and also via the Visual Studio Installer.

**Comment by dmauro** [comment]
> You can send everything to vstusp[at]microsoft[dot]com

Just wanted to flag that I sent csproj files from diesoftgames at gmail (figured with the attachments there's a good chance it wound up in spam).

**Comment by sailro** [comment]
> > You can send everything to vstusp[at]microsoft[dot]com
> 
> Just wanted to flag that I sent csproj files from diesoftgames at gmail (figured with the attachments there's a good chance it wound up in spam).

Yes I reviewed them. All seems good generation-wise. We are targeting explicitly `netstandard2.1` as expected. I have several doubts regarding the `yarnspinner` component because it is importing a bunch of well-known assemblies (System/Roslyn) where it should not. But I don't think that's the root issue. 

Perhaps it is indeed a C# Dev Kit bug. Any chance you can share the whole project with us, to see if we can repro the issue on our computers?

**Comment by dmauro** [comment]
Yeah, I can share the project. What's the best way you'd like to receive that? Access to the repo? Also, if it's helpful I have a secondary computer on which this problem did NOT manifest. If you can think of anything I can compare between the two that would help narrow things down.

**Comment by jbevain** [comment]
@Michael-Eng hey Michael, do we have any form of extended logging? Maybe it would be good to have for those scenarios. If the same project doesn't repro on another of David's computer, it might be specific to this one computer and might not repro even with the project. We'll certainly take a look at the project though, if we're lucky we'll repro.

**Comment by lifengl** [comment]
can you run dotnet --info in the terminal window in VS code, and let us know the result? when C# Dev Kit cannot resolve SDK, i will expect it to run the command automatically, and prints the result in the project output window, instead of a short message in the original thread.  Go further, you might use show extension logs command in VS code, and captured the entire Dev Kit logging, which might help, if we cannot find out the reason from dotnet --info command.

Let's assume that you have the correct dotnet in the PATH environment, which is critical to get the Dev Kit to resolve SDK, and it has 2 versions of SDK installed (not sure why the same version repeated twice for you). The explanation why it tries to find NET 6.0.0 SDK would be that there is a global.json in your system, likely in the root of the folder you opened in vscode, or one of the parent folder. It could be a part of your project, or something left from other works. A global.json may declare the exact version of SDK to be used.

**Comment by dmauro** [comment]
@lifengl Okay, here's the output of that from the terminal in VS Code:
```
> dotnet --info 
.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
  ```
  
The only global.json I could find was in my `~\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64` directory. Contents are:
```
{
  "msbuild-sdks": {
    "Microsoft.Build.NoTargets": "3.7.0"
  }
}
```

**Comment by sailro** [comment]
> @Michael-Eng hey Michael, do we have any form of extended logging? Maybe it would be good to have for those scenarios. If the same project doesn't repro on another of David's computer, it might be specific to this one computer and might not repro even with the project. We'll certainly take a look at the project though, if we're lucky we'll repro.

Just to be sure, I tried the project on several computers, and everything is working as expected (loading, editing, building and debugging using the unity extension). So yes definitively something specific to David's computer.

**Comment by dmauro** [comment]
Please let me know what else I can do to get more details about whatever is wrong on this particular system.

> Go further, you might use show extension logs command in VS code, and captured the entire Dev Kit logging, which might help, if we cannot find out the reason from dotnet --info command.

I'm not totally sure I'm following what this means. If this is referring to the Output dropdown and checking out the logging from C# Dev Kit more specifically, I have looked at that and didn't see anything that looked helpful. (Just standard looking output that suggesting things were going according to plan as I recall).

**Comment by Michael-Eng** [comment]
@dmauro If you can zip up the logs that might shed some light on what's happening. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/18017073/3810e7f8-17b8-4394-9f13-abc342e35efc)

@lifengl can update me if there's anything else we want to collect from you.

**Comment by dmauro** [comment]
I uninstalled and reinstalled VS Code again and launched it (by double clicking the exe from the install dir) when I was sure no Unity processes were running, and I still see `PRJ_BUILD_DOTNET_HOST=C:\Program Files\Unity\Hub\Editor\2020.3.9f1\Editor\Data\NetCore\runtime-317-win-x64\dotnet.exe` in that logfile come up when I open my project folder in VS Code.

When I inspect the PATH from VS Code I do see that directory showing up in there along with many others that do not appear in my PATH if I got into Windows advanced system settings and look at what's added there (in the Windows settings I only have about 4 entries, but VS Code is getting a PATH var that includes about two dozen entries).

**Comment by lifengl** [comment]
It is glad that the problem was resolved, and it turned out to be a setting issue, instead of some code actively manipulating the PATH environment.

Many functions of the C# Dev Kit extension are directly built on the top of the SDK (so it could work different versions automatically, instead of acting like VS, which has more built-in functions but is limited to certain version of the SDK.)  Developers can install SDK/runtime into different folders, on system root, some user folder or even a private one for a repo. They may install SDKs for different hardware platforms on the same machine (one might run on a simulation layer), so the extension would run dotnet command and expect it is resolved correctly through the PATH environment variable, so when there is another dotnet.exe in the path, it could break the function, as it is assumed to be a different private installation to be used. (Each clone doesn't share anything, including runtime or SDK, and only one will be active in one environment.)

Anyway, it is good to hear this problem is resolved, and I will close this bug then.
