### ISSUE TITLE
[BUG] Tests with internal accessor are not discovered

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#725]
### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/6658, originally filed by @sandy081

I have a test with `internal` accessor and this test is not discoverable anywhere. Visual Studio is able to discover it given that `xUnit` supports it.

**Comment by AbhitejJohn** [comment]
@sandy081, could you please help point us to a repro if that is possible? If a repro is hard to share (that's totally understandable) it would be great to see what package references your project uses (where it works in VS).

**Comment by peterwald** [comment]
Does the internal test appear after building in VS Code? 

In VS, the test would be discovered without building first, but in VS Code it does require a build before being discovered.

**Comment by wgrs** [comment]
None of my xunit tests are being discovered. Test Explorer shows nothing. Build test project a zillion times.

**Comment by sandy081** [comment]
>  it would be great to see what package references your project uses (where it works in VS).

Can you please help me in how to share this?

CC @dtivel

**Comment by AbhitejJohn** [comment]
@sandy081 : For instance with the following versions of xunit and Test SDK packages (which is what a new xunit project in VS gives me), I can see tests marked internal show up in the VSCode Test Explorer: as well

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference> 
```

![image](https://github.com/microsoft/vscode-dotnettools/assets/18014426/c13cb87b-41ba-4b14-bdfb-9fde48bb9181)

**Comment by AbhitejJohn** [comment]
@wgrs : Sorry about that. Any chance you have a repro you could share with us please? What version of C# Dev Kit are you using?

**Comment by wgrs** [comment]
I am using the latest one.

**Comment by sandy081** [comment]
@AbhitejJohn Here is my packages

```
<PackageVersion Include="xunit" Version="2.5.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
```

It does not seems to work for me
