### ISSUE TITLE
[BUG] Basic debugging from an existing project does not work

### ISSUE THREAD

**Issue by Mindfulplays** [microsoft/vscode-dotnettools#726]
### Describe the Issue

 Basic debugging from an existing project does not work

### Steps To Reproduce

Open any C# Mac OS project (e.g. the excellent https://github.com/Jorgemagic/Metal-Samples and choose a sub-project - for example, DrawCube.csproj) on VS Code with C# Dev Kit.

Press F5:
"Debugging canceled: Please open a .NET MAUI app project from the Solution Explorer to debug using the .NET MAUI configuration."

I went to Solution Explorer and right-clicked the csproj and tried Debug -> Start new instance: Says there is nothing to debug. (It at least builds the .dll FWIW).

### Expected Behavior

I would expect basic F5 to work out of the box if a single .csproj is present: At the very least, right-click on Solution Explorer -> project -> Debug should work. None of which works.

### Environment Information

macOS 14.1.1 Sonoma
VS Code 1.83.1
Latest C# Dev Kit / Maui extensions (Nov 14, 2023)

**Comment by tmeschter** [comment]
Removing area-maui as the projects in question are not MAUI projects.

**Comment by Mindfulplays** [comment]
Hiya, How does one differentiate `net*-ios` from `maui`? Isn't maui wrapping `net*-*` underneath?
(I saw the scary warning while building too: `workloads net*-ios/net*-android are no longer supported` (!!), so I am completely lost as to the relationship between these things)

**Comment by kvenkatrajan** [comment]
Closing as duplicate of #549 - we will continue tracking there.
