### ISSUE TITLE
[BUG] No MAUI templates after installing .NET 8.0 and all VS Code plugins including .NET MAUI

### ISSUE THREAD

**Issue by lorenzosjb** [microsoft/vscode-dotnettools#727]
### Describe the Issue

No MAUI templates after installing .NET 8.0 and all VSCode plugins including MAUI template.

### Steps To Reproduce

1. Open Visual Studio
2. Select Explorer icon
3. press Create .Net Project
4. There is no MAUI projects options
5. Open new terminal
6. type "dotnet new list" and there no MAUI templates.

### Expected Behavior

Expected MAUI templates to be listed.

### Environment Information

- OS MAC Sodoma 14.0
- NET: 8.0.100
- VS Code 1.84.2 (Universal)
- .NET MAUI v0.5.50 plugin
- C# v2.10.28 plugin
- C# Dev Kit v1.0.14 plugin

**Comment by smitpatel** [comment]
Duplicate of #699 mostly.

**Comment by lorenzosjb** [comment]
Yes, you are right. I also found out by accident reading https://devblogs.microsoft.com/visualstudio/announcing-the-dotnet-maui-extension-for-visual-studio-code/, that using the command `dotnet install workload maui` installed the templates
