### ISSUE TITLE
[BUG] Installing the C# DevKit extension requires reload[s] in Codespaces

### ISSUE THREAD

**Issue by seesharprun** [microsoft/vscode-dotnettools#729]
### Describe the Issue

I have been attempting to use the C# DevKit extension with the universal container image within GitHub Codespaces and ran into an issue where the extension requires you to reload your editor.

On install, the extension attempts to install the C# and .NET Install Tool extensions concurrently. Most of the time, the C# extension installs first and then complains that the .NET Install Tool extension is not installed. This then requires me to reload the Codespace editor to get the extension working.

![image](https://github.com/microsoft/vscode-dotnettools/assets/5067401/63301335-4262-45c4-b837-b8a614be0c52)

In an ideal state, I could just create a simple devcontainer file including the C# devkit extension and it works out of the box without requiring me to reload my online editor. I'm evaluating the universal container image as a way to create a frictionless "start" environment for .NET developers, but installing the extension and reloading slows down how seamless it would normally be.

I should just be able to create a devcontainer config like this and be ready to go for a .NET developer:

```json
{
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-dotnettools.csdevkit"
      ]
    }
  }
}
```

### Steps To Reproduce

1. Open any repository that doesn't have a devcontainer specification in a codespace (should use the universal container image unless one is specified).
1. Install the C# DevKit extension
1. Observe that you will be prompted to reload your environment.

### Alternative Steps To Reproduce

1. Open a devcontainer configuration that specifies that you should install the C# DevKit extension. (Example: https://github.com/seesharprun/codespace-test)
1. Observe that you are prompted to reload your environment after the C# extension is auto-installed as part of the C# DevKit extension.

### Expected Behavior

Ideally, installing the C# DevKit extension shouldn't require an environment reload. I don't know if there's a race condition between the two related extensions, or if there's some more challenging problem under the hood.

### Environment Information

- Environment: GitHub Codespaces
- Extension version: Not specified (latest)

**Comment by timheuer** [comment]
@seesharprun the base codespaces images don't have always configurations that support all platforms/runtimes/languages. It's best to use a devcontainer you know you can configure.  If you are adding a devcontainer image yourself I recommend this one: https://gist.github.com/timheuer/694f8a3ef565b1cb5fbe616c9a1e18cc as a starting point.  If you aren't using .NET Aspire yet, you can remove the postcreate command and other ones.

This will get you a good starting point for Codespaces + .NET
