### ISSUE TITLE
Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK)

### ISSUE THREAD

**Issue by tupelotech** [microsoft/vscode-dotnettools#730]
Type: <b>Bug</b>

Run and debug Maui application - VSCODE MacOS -  tools are located here - % xcode-select -p
/Library/Developer/CommandLineTools - how to configure VSCODE to find 

Extension version: 0.5.50
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|64.00GB (7.17GB free)|
|Process Argv|--crash-reporter-id 7bdfd520-5cdc-45d2-8bbe-e5722a27e40c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

> VS bug [#1921028](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1921028)

**Comment by tupelotech** [comment]
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z (1 wk ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

**Comment by tupelotech** [comment]
Please note we are not running Visual Studio on Mac -  the Update instructions refer to Visual Studio not VSCODE

**Comment by mauroa** [comment]
Hi @tupelotech, we will investigate this issue to get to a proper fix. In the meantime, did you manage to point to the right Xcode path with xcode-select?

Thanks

**Comment by BretJohnson** [comment]
Re updating the error message, also see https://github.com/xamarin/xamarin-macios/issues/19818.

**Comment by thiagolunardi** [comment]
It's my first-time coding in a Mac and I had a challenging time to figure out how to point to the right Xcode path:
1. execute `xcode-select -p` to print the current path
2. verify if the xcode is at `/Applications/Xcode.app`. `cd /Applications` then `ls` to find the `Xcode.app` in the list
3. execute `sudo xcode-select -s /Applications/Xcode.app` to change the Xcode path
4. execute again `xcode-select -p` to print the current path and verify it's updated

**Comment by BretJohnson** [comment]
I believe this is now fixed. See https://github.com/xamarin/xamarin-macios/issues/19818, fixed 2 weeks ago though I'm not sure when that will be released. @mauroa - maybe you can confirm and then close?

**Comment by ext2txe** [comment]
issue is still there.  Clean install of  new macos system with vscode 1.88.1, dotnet 8.0.204, and extensions  with default maui app code - build still broken 
steps given by thiagolunardi Jan/21  provides a fix
