### ISSUE TITLE
[BUG] Microsoft.VisualStudio.Code.ServiceHost loads the CPU constantly by 25%

### ISSUE THREAD

**Issue by timamus** [microsoft/vscode-dotnettools#731]
### Describe the Issue

Microsoft.VisualStudio.Code.ServiceHost loads the CPU constantly by 25%. This happens in all versions of the C# devkit extension above 1.0 when the .net project is open in VS Code.

![tempsnip](https://github.com/microsoft/vscode-dotnettools/assets/48119843/12add209-3a8c-4e15-96ec-fe65fdf1cb5c)

### Environment Information

- Windows 10;
- VS Code 1.84.2
- All version C# devkit extension above 1.0 v.

**Comment by timamus** [comment]
> We would need to identify if Roslyn or project system processes.

How to identify it?

**Comment by dibarbet** [comment]
Microsoft.VisualStudio.Code.ServiceHost is the servicehub host process I believe.  Roslyn does not use service hub, and it doesn't appear to be the project system or CPS processes either.

**Comment by AArnott** [comment]
I can't repro the problem given the instructions in the issue description. 
@timamus Are you still seeing this? If so, can you collect an ETL trace while the process is spinning and share the .zip (that includes symbols) with us? My favorite tool to collect such a trace is [PerfView](https://github.com/microsoft/perfview/releases).

**Comment by MihaPro-CarX** [comment]
I have a problem with Microsoft.VisualStudio.Code.ServiceHost:
![изображение](https://github.com/user-attachments/assets/cd2c94d2-6f8e-4db6-8e8c-8a03c3898ba8)
I have a large Unity project with 301 projects in Solution. There is a very large memory consumption by the process: Microsoft.VisualStudio.Code.ServiceHost.
C# v2.39.28 (pre-release)
C# Dev Kit v1.9.8 (pre-release)

**Comment by AArnott** [comment]
@MihaPro-CarX Wow. 26GB! I can't say whether that's a *bug* for 301 projects, but we can certainly investigate. But can you open a separate issue as that seems distinct from _this_ issue. 

I'm going to close this due to lack of a repro and no response from the OP.

**Comment by MihaPro-CarX** [comment]
@AArnott I opened another issue: https://github.com/microsoft/vscode-dotnettools/issues/1295
