### ISSUE TITLE
[SUGGESTION] Allow multiple solution files

### ISSUE THREAD

**Issue by ultra133** [microsoft/vscode-dotnettools#738]
Type: <b>Feature Request</b>

In **Visual Studio** and **Visual Studio for Mac** it is possible to have multiple solution files (*.sln) side-by-side within one folder.
This is useful, when the developer wants to be able to switch between different configurations or different sets of projects.
Currently it is not possible to maintain these solutions within VS Code, since there is no option to choose which solution file should be used.

Extension version: 1.1.12
VS Code version: Code - Insiders 1.85.0-insider (Universal) (54b8f6a80aaad7489b75e9293b8d7a1700bed815, 2023-11-17T10:50:41.392Z)
OS version: Darwin arm64 23.1.0
Modes:

**Comment by timheuer** [comment]
@ultra133 you can indeed choose which solution file you want to open.  Using the Command Pallette you can use `Open Solution` which will show you different solution files and you can choose which one.  Does this solve for you?

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/21bce690-77e3-47c5-86a8-25043fe3b5ff)

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/80407a80-9c19-4a5f-b66e-32003b12a036)

**Comment by ultra133** [comment]
@timheuer that's exactly what i was looking for. Thank you!
