### ISSUE TITLE
[BUG] Dotnet 8 Not Supported

### ISSUE THREAD

**Issue by BLaZeKiLL** [microsoft/vscode-dotnettools#739]
### Describe the Issue

I have dotnet 8 installed using homebrew on MacOS and set up the following settings to use my installed dotnet

```json
"dotnetAcquisitionExtension.existingDotnetPath": [
    {
        "extensionId": "ms-dotnettools.csharp",
        "path": "/usr/local/share/dotnet/dotnet"
    },
    {
        "extensionId": "ms-dotnettools.csdevkit",
        "path": "/usr/local/share/dotnet/dotnet"
    }
]
```

I get the following error from the c# dev kit, when I try to open an existing solution or create a new project

```
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
Using local .NET runtime at "/usr/local/share/dotnet/dotnet"
Using runtime installed in SDK.
.NET server STDERR: You must install or update .NET to run this application.

App: /Users/codeblaze/.vscode/extensions/ms-dotnettools.csdevkit-1.0.14-darwin-arm64/components/vs-green-server/platforms/darwin-arm64/node_modules/@microsoft/visualstudio-server.darwin-arm64/Microsoft.VisualStudio.Code.Server
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (arm64)
.NET location: /usr/local/share/dotnet

The following frameworks were found:
  8.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=arm64&rid=osx-arm64&os=osx.14

.NET server exited with 150
```

### Steps To Reproduce

1. Install dotnet using homebrew
2. Install C# dev kit
3. Configure dotnet runtime install tool to use the dotnet installed by homebrew
4. Open a solution or try to create a new project

### Expected Behavior

Should be able to use C# dev kit

### Environment Information

- OS: MacOS 14.0
- VsCode: 1.84.2
- C# Dev Kit: 1.0.14

**Comment by aressler38** [comment]
The same error happens on Linux

**Comment by redpiller** [comment]
It seems to be a general problem.
Same happens to me, it is annoying because I need the 8.0
instead  it gives me the following:
`ms-dotnettools.csdevkit requested to download the .NET Runtime.
Downloading .NET version(s) 7.0.14~x64 .................... Done!
.NET 7.0.14~x64 executable path: /home/user/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.14~x64/dotnet`

I used the official .NET debian packages btw.

To whom it concerns: Please fix the issue.

**Comment by ryandever** [comment]
Hi there? can someone solve this bug ?

**Comment by Libitum** [comment]
Got the same issue here.
Seems the reason is that the Microsoft.VisualStudio.Code.Server supports only .NET 7.0.0 now.

**Comment by GlacierFox** [comment]
So has anyone found a solution? Is anyone actually able to develop on linux or mac using DotNET 8? I still haven't managed to get this working and the DotNET install tool keep bringing down version 7 for some reason.

**Comment by eof-milsat** [comment]
Also having same issue _ubuntu 22.04_ Seems like this issue isn't a priority for the microsoft team.

Pending when a fix is made, I'd suggest you disable C# Dev kit so omnisharp can kick in.
Unless there are some specific things you're depending on with the dev kit

**Comment by GlacierFox** [comment]
> Also having same issue _ubuntu 22.04_ Seems like this issue isn't a priority for the microsoft team.
> 
> Pending when a fix is made, I'd suggest you disable C# Dev kit so omnisharp can kick in. Unless there are some specific things you're depending on with the dev kit

I can't disable it unfortunately. The MAUI extension relies on it. Not the end of the world, would have been nice to actually develop on Linux as advertised though.

**Comment by GlacierFox** [comment]
> I'm running into the same issue on macOS Sonoma. No intellisense, no class recognition. My development is dead in the water. ☹️

Yeah I've had to remove the C# Dev Kit and the MAUI extension. I'm having to use the Net Meteor extention to do MAUI development on Linux.

**Comment by AppiePau** [comment]
> Yeah I've had to remove the C# Dev Kit and the MAUI extension. I'm having to use the Net Meteor extention to do MAUI development on Linux.

Wow, that.s horrrible without IDE support. May this be a homebrew issue not registering dotnet properly? I tried the pre-release of the C# tools. Still no luck. Keeps saying:
Using local .NET runtime at "/Users/.../Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.16~arm64/dotnet"

**Comment by GlacierFox** [comment]
> > Yeah I've had to remove the C# Dev Kit and the MAUI extension. I'm having to use the Net Meteor extention to do MAUI development on Linux.
> 
> Wow, that.s horrrible without IDE support. May this be a homebrew issue not registering dotnet properly? I tried the pre-release of the C# tools. Still no luck. Keeps saying:
> Using local .NET runtime at "/Users/.../Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.16~arm64/dotnet" 

I think it might be due to a few errors I mentioned in #902 but AI haven't had any  replies there. I think there's some underlying dependency with the vscode server component or something unique to Linux.

**Comment by AppiePau** [comment]
I tried to install the runtime and SDK directly, but no luck as well. Just fired up my VM with Win 11 ARM to at least be able to code on the same machine. With the price of battery drain....
This really sucks and what I don't get is that the issue surfaced two days ago when the Copilit plugin mentioned it disabled Intellisense in favor of Copilot. That's when it all broke down here and I tried to cleanly install VS Code and noticed Windows machines were fine and macOS (or Linux in your case) not.

**Comment by GlacierFox** [comment]
@AppiePau It's been happing to me ever since I started using the C# Dev kit over a month ago. I've tried it on many different Linux distros and configurations and I'm getting the same result.

**Comment by AppiePau** [comment]
I took a leap of faith and also installed both the dotnet 7 Tuntime and SDK (https://dotnet.microsoft.com/en-us/download/dotnet/7.0). Which seems to have done the trick. 

I guess I cleaned up too much and that's why de dev tools have recently stopped working on my machine. Not sure if this would have any negative effects on your development environment, but it's worth a shot.

Still, this seems to be a workaround. Especially since I received e-mail notifications from Microsoft explaining they will end support of .NET 7 on Azure services per May 14th 2024. 🤷🏻

**Comment by GlacierFox** [comment]
@AppiePau Ive tried myself also but I get a strange result. It does recognise that I've now got a .NET 7 install alongside my 8 but vscode uses 7 as the development version so I'm unable to properly load up and version 8 projects which is weird. I'm having to use a windows machine now as I've just decided to sit tight after receiving no feedback on the issue. Hopefully someone at Microsoft decides to use version 8 on Linux and gets annoyed as I have with it 🤔

**Comment by AppiePau** [comment]
@GlacierFox Bummer. I hope they do and fix it. Also due to end of life (apparently) of NET7 on Azure. It is quiet inconsistent this way.

**Comment by nagilson** [comment]
@lifengl @AArnott @tmeschter  May you take a look at this and see why it is saying it's using the local runtime but then it cannot find .NET after it has found it?

**Comment by webreidi** [comment]
@BLaZeKiLL / @aressler38 The most recent update of C# Dev Kit now uses .NET 8. If you are still experiencing issues with the latest version, please reopen this issue so we can dive in further.

**Comment by BLaZeKiLL** [comment]
Thanks, It's working as expected
