### ISSUE TITLE
[BUG] Visual Studio Code does not detect properly that android licenses are already accepted

### ISSUE THREAD

**Issue by danielAyerra** [microsoft/vscode-dotnettools#740]
### Describe the Issue

I am unable to compile/debug/run MAUI apps because Visual Studio Code is unable to detect properly that android licenses are already accepted. I have tried to do everything about that except running VS on super user, since it is not recommended.

When doing on terminal, I have no issues:
```
$: dotnet build -f:net7.0-android FitnessGUI/FitnessGUI.csproj                    
MSBuild version 17.4.8+6918b863a for .NET                                         
  Determining projects to restore...                                              
  All projects are up-to-date for restore.                                        
  FitnessGUI -> /home/Weinman/git/fitness/FitnessProgrammerGUI/FitnessGUI/bin/Debug/net7.0-android/FitnessGUI.dll                                                   
                                                                                  
Compilación correcta.                                                             
    0 Advertencia(s)                                                              
    0 Errores

Tiempo transcurrido 00:00:45.01
```

While on Visual studio code, I get the following message:
```

ACTION REQUIRED:
	- To enable debugging, the Android SDK licenses needs to be accepted. You can accept them from the command palette by choosing '.NET MAUI: Configurar Android', selecting 'Revisar licencias de Android', and following the instructions.
Depuración cancelada: Android SDK se deben aceptar licencias.

```
When I try to do as required, I am forbidden, because VS Code is unable to execute super user privileges and I have to do it manually. When doing so, even after removing folders and accepting licenses again, I get nothing.

### Environment Information

- OS: Arch Linux
- Code Version: 1.84.1
- MAUI Extension Version: 0.5.50

> VS bug [#1920980](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1920980)

**Comment by timheuer** [comment]
Can you try the steps articultated in the original issue: https://github.com/microsoft/vscode-dotnettools/issues/249#issuecomment-1633052480

**Comment by danielAyerra** [comment]
> Can you try the steps articultated in the original issue: [#249 (comment)](https://github.com/microsoft/vscode-dotnettools/issues/249#issuecomment-1633052480)

I actually already have done that, either from both terminal and VSCode terminal. I did it by 'sudoing' (my user elevated priviledges) and by 'suing' (using root user). Didn't work.

Could it be possible something like giving elevated permissions to VS code (through a group or editing vscode's group permissions)?

**Comment by tondat** [comment]
This is now fixed in the latest prerelease version of the .NET MAUI Dev Kit extension (v0.11.34).
