### ISSUE TITLE
[BUG] .NET MAUI does not reach breakpoints since launch.json is included

### ISSUE THREAD

**Issue by d66ni** [microsoft/vscode-dotnettools#746]
### Describe the Issue

I have included a launch.json for building my .NET MAUI application but in debug mode the application is not stopping at the break points. I am using the .NET MAUI extension.

Am I missing something in the launch.json file?

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug-Develop",
            "configuration": "Debug-Develop",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }
    ]
}`

**Comment by mauroa** [comment]
Hi @d66ni, are you able to hit breakpoints if you don't use the custom debug configuration? Thanls

**Comment by d66ni** [comment]
Hey @mauroa, yes before I was using a custom configuration breakpoints were hit. The information I found in the internet was just to create a configuration and use the default prelaunchtask maui: build and everything should work as before ...

**Comment by d66ni** [comment]
Any update at this topic?

**Comment by jump32** [comment]
@d66ni There appears to be a workaround. See https://developercommunity.visualstudio.com/t/Can-not-deploy-iOS-simulator-build-in-al/10327626?q=Show+html+generated+in+build+pipeline+on+Dashboard

For us, adding the following configuration group to the csproj enabled the breakpoints to work. It is required whenever the configuration name is not 'Debug'.

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug-Develop' ">
        <_BundlerDebug>true</_BundlerDebug>
    </PropertyGroup>

**Comment by mauroa** [comment]
Hi @d66ni,
Could you update the MAUI extension to the latest pre-release? We've recently made some changes that should make this issue disappear, but I would like to get your confirmation.
Thanks

**Comment by mauroa** [comment]
Issue fixed in latest pre-release. Feel free to request a re-opening in case you still reproduce it
