### ISSUE TITLE
Bug can't create project in .NET 8

### ISSUE THREAD

**Issue by PugSingha** [microsoft/vscode-dotnettools#747]
Type: <b>Bug</b>

Now can't create project and run project

Extension version: 0.5.50
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:57.054Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
vscrpc:30673769
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by tmeschter** [comment]
Hi @PugSingha. Can you provide us more information? How are you trying to create the project? Do you see any error messages when you do so?

**Comment by PugSingha** [comment]
@tmeschter  Please help me. I've installed everything I need for .NET MAUI, but I don't have the option to install MAUI. (.NET 8)

**MacBook Information**
- MacBook Air
- CPU M1
- Memory 8 GB
- macOS Sonoms Version 14.1.1

I have installed the latest version of .net 8, macOS Arm64 and Xcode Version 15.0.1

**I installed the extension.**
- .NET Install Tool
- .NET MAUI
- C#
- C# Dev Kit
- IntelliCode For C# Dev Kit

![8002F363-6213-4D1D-B986-0D1A5ECBCBFF](https://github.com/microsoft/vscode-dotnettools/assets/151817494/87eb0c2c-612d-4e97-8142-11dca6150c57)


And I want to create a project, but there is no option for me. (Before it was released, .NET 8 could create projects.)

<img width="1440" alt="Screenshot 2566-11-30 at 09 23 34" src="https://github.com/microsoft/vscode-dotnettools/assets/151817494/2d590637-c8e1-4c97-b9dd-ed0f8fd11b43">

I did a test run of a project that was created from visual studio (.NET 8) in Windows, but it doesn't work, an error alerts up, not found, MAUI SDK. 

<img width="1440" alt="Screenshot 2566-11-30 at 09 52 32" src="https://github.com/microsoft/vscode-dotnettools/assets/151817494/79243b5b-6c1f-4100-aa4e-71661191f2fc">

**Comment by emaf** [comment]
@PugSingha it seems you are missing installing the .NET MAUI SDK related workloads. 

The first few lines in .NET MAUI output window should list the missing required workloads that you need to install. You can then install them from CLI using the `dotnet workload install` command.

If that doesn't work, please share the content of the .NET MAUI output window.

**Comment by PugSingha** [comment]
@emaf Thank you very much. It worked.  But I have a new problem in vscode on windows. I followed all the steps and logged in with my Microsoft account. I have completed all the steps and logged in with my Microsoft account, but there is still Error failed to restore solution. How can I fix this? 
![image](https://github.com/microsoft/vscode-dotnettools/assets/151817494/685fe133-a5f5-4774-a627-d6a1892312e9)

**Comment by emaf** [comment]
@PugSingha Could you share the C# Dev Kit output? I think clicking on `Show Error` will get you there

**Comment by PugSingha** [comment]
@emaf  Sorry 

### After pressing the error button

<img width="1920" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/151817494/f5039bc3-8b33-41af-9f1e-9a337bb7f4e1">


  Determining projects to restore...
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Ref.34.' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-arm' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-arm64' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-x86' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-x64' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]





### This image after the test run.

<img width="1920" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/151817494/ca5482d5-8c55-4821-b844-424f4fe563b4">

**Comment by timheuer** [comment]
@PugSingha on the Windows machine now did you install the workload as well? `dotnet workload install maui`

**Comment by PugSingha** [comment]
@timheuer  I have installed it but I still can't run the project.  *Sorry My English isn’t very good.

<img width="1920" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/151817494/f16b15c8-bade-4e8f-97f6-b967c7b9c941">




This image after the test run. 

<img width="1920" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/151817494/84f1f6a0-db08-443e-9426-f54d129f44d7">

**Comment by timheuer** [comment]
Ok, will need the MAUI folks to chime in here -- can you paste the output of `dotnet --info` here?

**Comment by PugSingha** [comment]
@timheuer  Yes, I appreciate your help.

![image](https://github.com/microsoft/vscode-dotnettools/assets/151817494/9b670284-d9cb-47ac-aa2e-abddbd24ea39)

![image](https://github.com/microsoft/vscode-dotnettools/assets/151817494/424aada9-8448-470d-a832-e1451e812736)


PS D:\MauiApp1> dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.d75fd3e4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.d75fd3e4
 [maui]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    17.0.8490/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8490\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    17.0.8490/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8490\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34330.188
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS D:\MauiApp1>

**Comment by emaf** [comment]
> C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Ref.34.' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
> C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-arm' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
> C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-arm64' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
> C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-x86' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]
> C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Runtime.34..android-x64' was not present in workload manifests. [D:\MauiApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-android]

This looks like a problem with the .NET Android workload installation. The workload is installed, but there is something wrong with it. 

I'll reach out to the Android SDK team internally, but I think it might be easier for you to get more folks involved by reporting an issue directly in their repository to get their support: https://github.com/xamarin/xamarin-android.

**Comment by mauroa** [comment]
Hi @PugSingha.
We are trying to re-activate or cleanup old issues related to the VS Code MAUI extension that were left unattended or into "Need More Info" state and didn't get a response in a while.
I would like to know if you continued working with MAUI projects in VS Code and if you still have any issue related to this ticket, after updating to a newer dotnet SDK version and workloads (ios, android, maui).
We will proceed to close this ticket in case we don't get a new response in a few days.
Thanks in advanced.
