### ISSUE TITLE
Hide Explorer Arrows

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#75]
I'm using popular extension `Material Icon Theme` with settings:

`"material-icon-theme.hidesExplorerArrows": true`

and arrows are hidden in regular `Explorer`. Please add ability to hide the arrows in `Solution Explorer` too.

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/bfcbb0aa-3b6c-4acb-885e-11900164b536)

**Comment by smitpatel** [comment]
We add solution explorer as normal view in VSCode. Since a 3rd party extension is changing arrows, it is up to them to operate on a view other than folder explorer. Please reach out to them.
