### ISSUE TITLE
[BUG] iOS app crashes, Android app is fine, no idea why.

### ISSUE THREAD

**Issue by rogersm-uwosh** [microsoft/vscode-dotnettools#755]
### Describe the Issue

I have an app. it runs fine on Android. I switch to iOS, choosing an iPhone 14 Pro Max, and it crashes, with a long crash report.

### Steps To Reproduce

Launch the app, which runs fine on Android. Here it produces a crash report
[System Crash.txt](https://github.com/microsoft/vscode-dotnettools/files/13462301/System.Crash.txt)

I'm sure this is probably something I'm doing wrong, but I can't tell what it is, and since this is beta software, I figure someone might be interested in taking a look at this.

### Expected Behavior

I expect the app to run (well, tbh, I don't, but I am hopeful 😀)

Note that I can get the template app to run, so this is something wrong with my project, but it's hundreds of lines, and I get hundreds of lines of gibberish from the log.

### Environment Information

macOS
Visual Studio Code: 1.84.2
.NET MAUI 0.5.50, C# Dev Kit 1.0.14

Again, here's the crash report:
[System Crash.txt](https://github.com/microsoft/vscode-dotnettools/files/13462294/System.Crash.txt)

**Comment by mcumming** [comment]
@rogersm-uwosh Does cleaning the project (delete all obj/bin folders)  before running the iOS app resolve the issue?

**Comment by rogersm-uwosh** [comment]
It had something to do with a "Resizeitizer" -- I have no idea what that means, but I ended up commenting out some line in a .csproj file and then it worked, so you can close this.
