### ISSUE TITLE
[BUG] Project that runs in VS Mac doesn't run in VS Code on macOS

### ISSUE THREAD

**Issue by mrlife** [microsoft/vscode-dotnettools#756]
### Describe the Issue

I develop on macOS and deploy to Windows as a Windows service. I'm using the C# Dev Kit.

### Steps To Reproduce

1. Add this to .csproj on macOS: `<DefaultAppHostRuntimeIdentifier>win-x64</DefaultAppHostRuntimeIdentifier>`
2. Debug project and notice that it doesn't start and presents this error:
> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[29491] AlumniAdmissionsReport.exe' has exited with code 1 (0x1).

### Expected Behavior

Project should run successfully

### Environment Information

- VS Code Version: Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
- OS Version: macOS 13.6 (22G120)

**Comment by timheuer** [comment]
I'm confused, are you expecting a RID-based Windows build to work on macOS?

**Comment by mrlife** [comment]
@timheuer, thank you for getting back to me about this. I develop on macOS and publish to Windows, and it runs as a Windows service. This is how Microsoft asked me to set up the csproj. It works on Visual Studio for Mac.

**Comment by timheuer** [comment]
@mrlife on VSMac you are F5(run) the project from within the IDE with that property and it launches? or are you talking about building only? (related convo: https://github.com/dotnet/aspnetcore/issues/41776)

**Comment by mrlife** [comment]
@timheuer I use run, debug, and build within VSMac with `<DefaultAppHostRuntimeIdentifier>win-x64</DefaultAppHostRuntimeIdentifier>` in place without any issues. Maybe it has extra logic to handle this. Thanks for reminding me of the old issue. I will go ahead and remove `DefaultAppHostRuntimeIdentifier`. I think I ended up keeping it until now in case any colleagues developing on Windows couldn't run the project, but it doesn't sound like that's what it's for. Thanks!
