### ISSUE TITLE
[BUG] Debug Test can't capture the stdout/stderr output.

### ISSUE THREAD

**Issue by zhen8838** [microsoft/vscode-dotnettools#757]
### Describe the Issue

when debugging the xunit test, I can't see any stdout/stderr output in the debug console.

### Steps To Reproduce

write any xunit test, and write something to the console:
https://github.com/microsoft/vscode-dotnettools/assets/26156999/6c7d5ac9-8ef2-481a-b7d0-d8a42705c607

### Expected Behavior

will capture the console output in the debug console.

### Environment Information

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

**Comment by AbhitejJohn** [comment]
This is similar to #159

**Comment by ocallesp** [comment]
@ocallesp  verify this is the same as #159
