### ISSUE TITLE
How install this extension without Internet environment?

### ISSUE THREAD

**Issue by jjjhong91** [microsoft/vscode-dotnettools#758]
My work computer doesn't have internet access, so I have to install VS Code extensions through a computer that can connect to the internet. Then, I transfer the extensions directory from the .vscode folder via data exchange to my work computer and paste the extensions into the .vscode folder. However, I've noticed that the C# Dev Kit seems to attempt to connect to the internet for downloads when enabled. Is there a method to use the C# Dev Kit properly in an environment where I can't use the internet?

**Comment by timheuer** [comment]
@jjjhong91 Is the extension non-functional for you as a result? There are some packages that are downloaded on-demand but should be non-blocking.  If you are on a machine that does NOT have .NET 7 runtime installed that's a dependency and we do attempt to help acquire that. Is that something that you can get on your machine?

**Comment by jjjhong91** [comment]
> @jjjhong91 Is the extension non-functional for you as a result? There are some packages that are downloaded on-demand but should be non-blocking. If you are on a machine that does NOT have .NET 7 runtime installed that's a dependency and we do attempt to help acquire that. Is that something that you can get on your machine?

I have installed .NET Core 3.1, .NET 6, and .NET 8 SDK.

**Comment by ecococox** [comment]
> İş bilgisayarımın internet erişimi yok bu yüzden internete bağlanabilen bir bilgisayar üzerinden VS Code uzantılarını kurmam gerekiyor. Daha sonra .vscode klasöründeki extensions dizinini veri alışverişi yoluyla iş bilgisayarıma aktarıyorum ve uzantıları .vscode klasörüne yapıştırıyorum. Ancak, C# Dev Kit'in etkinleştirildiğinde indirmeler için internete bağlanmaya çalıştığını fark ettim. İnterneti kullanamadığım bir ortamda C# Dev Kit'i düzgün kullanmanın bir yöntemi var mı?

### [_****_](url)

**Comment by ecococox** [comment]
> > İş bilgisayarımın internet erişimi yok bu nedenle internete bağlanabilen bir bilgisayar üzerinden VS Code uzantılarını kurmam gerekiyor. Daha sonra .vscode bölgelerindeki uzantılar dizinini veri alışverişi yoluyla iş bilgisayarıma aktarıyorum ve uzantıları .vscode birimlerine yapıştırıyorum. Ancak C# Dev Kit'in indirilmesi için etkinleştirildiğinde internete bağlanmaya çalışılmasında fark uygulandı. İnterneti kullanamadığım bir bağlama C# Dev Kit'i düzgün kullanmanın bir yöntemi var mı?
> 
> ### [_****_](url)

iş bilgisayar kullanırsın

**Comment by timheuer** [comment]
> > My work computer doesn't have internet access, so I need to install VS Code extensions on a computer that can connect to the internet. I then transfer the extensions directory in the .vscode folder to my work computer via data exchange and paste the extensions into the .vscode folder. However, I noticed that the C# Dev Kit tries to connect to the internet for downloads when enabled. Is there a way to properly use the C# Dev Kit in an environment where I can't use the internet?

As noted above there are some things that are downloaded on-demand. Are you experiencing failures as a result of your method here? If so, can you share what specifically is not working?

**Comment by jjjhong91** [comment]
I just want to know what files the C# Dev Kit will actively download from the internet after installation, and where it will place them. This way, I can ensure the complete installation of the C# Dev Kit in an offline environment. The issue I'm currently facing is that even in an offline environment, I encounter missing files, causing the C# Dev Kit to not function properly.

**Comment by timheuer** [comment]
> The issue I'm currently facing is that even in an offline environment, I encounter missing files, causing the C# Dev Kit to not function properly.

Can you share which specifically are not working for you? There are a few things that are downloaded on-demand:
- The extension has a dependency on the .NET 7 runtime (as of this post) and, if not present, will attempt to acquire that for you.  Alternatively this dependency can be satisfied via direct installation otherwise
- The extension downloads a telemetry package for Razor on-demand but that is not required to have the extension function normally. @arkalyanms please correct me if I'm wrong

VS Code extensions are all installed in the same place <userprofile>\.vscode\extensions -- however I'd recommend not trying to replicate outside of the extension installers for managing install state, etc.

Outside of that (having the runtime dependency satisfied) you should be have a working environment. I would love to understand what specifically is not working still.

**Comment by jjjhong91** [comment]
> > The issue I'm currently facing is that even in an offline environment, I encounter missing files, causing the C# Dev Kit to not function properly.
> 
> 
> 
> @jjjhong91 Can you share which specifically are not working for you? There are a few things that are downloaded on-demand:
> 
> - The extension has a dependency on the .NET 7 runtime (as of this post) and, if not present, will attempt to acquire that for you.  Alternatively this dependency can be satisfied via direct installation otherwise
> 
> - The extension downloads a telemetry package for Razor on-demand but that is not required to have the extension function normally. @arkalyanms please correct me if I'm wrong
> 
> 
> 
> VS Code extensions are all installed in the same place <userprofile>\.vscode\extensions -- however I'd recommend not trying to replicate outside of the extension installers for managing install state, etc.
> 
> 
> 
> Outside of that (having the runtime dependency satisfied) you should be have a working environment. I would love to understand what specifically is not working still.

I have a few questions:

1. My environment doesn't have .NET 7 installed, but I do have .NET 8. Is it necessary to install .NET 7 for it to work properly?

2. My project involves MVC, so I need to download the Razor part. You suggest not copying the extensions directory or files, but I don't have an external internet connection. How can I install it properly? Since you mentioned it downloads Razor-related files on-demand, installing via vsix wouldn't work, right?

3. I'd like to ask if you can provide the standard operating procedure (SOP) for installing the C# Dev Kit in VSCode on a computer without an internet connection.

**Comment by timheuer** [comment]
> * My environment doesn't have .NET 7 installed, but I do have .NET 8. Is it necessary to install .NET 7 for it to work properly?

Yes it is.  You don't need the full SDK, just the runtime, hence what you are seeing.

> * My project involves MVC, so I need to download the Razor part. You suggest not copying the extensions directory or files, but I don't have an external internet connection. How can I install it properly? Since you mentioned it downloads Razor-related files on-demand, installing via vsix wouldn't work, right?

No, the on-demand piece that is being downloaded is a telemetry package, the core Razor experience should still be working for you and not blocked.

> * I'd like to ask if you can provide the standard operating procedure (SOP) for installing the C# Dev Kit in VSCode on a computer without an internet connection.

- Ensure your environment has .NET 7 runtime (for your architecture) - https://dotnet.microsoft.com/en-us/download/dotnet/7.0 (runtime only is needed)
- Download the VSIX (from marketplace) for your architecture
- Install the VSIX (from the command pallette "Install from VSIX")
- Whatever SDK you need for your development (e.g., looks like doing .NET 8 so install that .NET 8 SDK as well)

**Comment by jjjhong91** [comment]
> > * My environment doesn't have .NET 7 installed, but I do have .NET 8. Is it necessary to install .NET 7 for it to work properly?
> 
> 
> 
> Yes it is.  You don't need the full SDK, just the runtime, hence what you are seeing.
> 
> 
> 
> > * My project involves MVC, so I need to download the Razor part. You suggest not copying the extensions directory or files, but I don't have an external internet connection. How can I install it properly? Since you mentioned it downloads Razor-related files on-demand, installing via vsix wouldn't work, right?
> 
> 
> 
> No, the on-demand piece that is being downloaded is a telemetry package, the core Razor experience should still be working for you and not blocked.
> 
> 
> 
> > * I'd like to ask if you can provide the standard operating procedure (SOP) for installing the C# Dev Kit in VSCode on a computer without an internet connection.
> 
> 
> 
> - Ensure your environment has .NET 7 runtime (for your architecture) - https://dotnet.microsoft.com/en-us/download/dotnet/7.0 (runtime only is needed)
> 
> - Download the VSIX (from marketplace) for your architecture
> 
> - Install the VSIX (from the command pallette "Install from VSIX")
> 
> - Whatever SDK you need for your development (e.g., looks like doing .NET 8 so install that .NET 8 SDK as well)

@timheuer Ok, I'll give it a try. I'll let you know the results after I finish testing. Thank you.

**Comment by jjjhong91** [comment]
@timheuer I have two requests.

1. When I install the C# Dev Kit through vsix, it automatically downloads dependent extensions. Can you let me know which ones it downloads?
2. It automatically downloads and installs Razor Language Telemetry, but since I don't have internet access, it fails. Without this, I can't switch between controller and view using shortcuts in VSCode, right? Also, could you provide me with a method to install Razor Language Telemetry in an offline environment?

**Comment by timheuer** [comment]
> 1. When I install the C# Dev Kit through vsix, it automatically downloads dependent extensions. Can you let me know which ones it downloads?

It downloads the C# base extension (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp), IntelliCode for C# (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp), and the .NET Install Tool (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime) as dependent extensions. FYI our *extension* doesn't install these, the marketplace does just as a minor technical explanation here.  The dev kit is dependent upon these and thus the marketplace satisfies that dependency graph.

> 2. It automatically downloads and installs Razor Language Telemetry, but since I don't have internet access, it fails. Without this, I can't switch between controller and view using shortcuts in VSCode, right? Also, could you provide me with a method to install Razor Language Telemetry in an offline environment?

You shouldn't be blocked functionally from this not existing.  We do not have a supported means to distribute this.

**Comment by jjjhong91** [comment]
Ok, maybe these issues are happening because of incomplete dependencies. I'll test it after a complete installation. Thank you.

However, even though you mentioned that not having Razor Language Telemetry installed doesn't affect it, every time I open the project, VS Code keeps trying to download it, causing my VS Code to become very slow. Is there a setting to prevent this download, or could you tell me where I can manually download and install it?

**Comment by timheuer** [comment]
> every time I open the project, VS Code keeps trying to download it, causing my VS Code to become very slow

Let's make sure you can get things working, but yes if we don't have some state that just gracefully stops looking for this we should (/cc @arkalyanms - is this in C# extension?)

**Comment by jjjhong91** [comment]
> > every time I open the project, VS Code keeps trying to download it, causing my VS Code to become very slow
> 
> 
> 
> Let's make sure you can get things working, but yes if we don't have some state that just gracefully stops looking for this we should (/cc @arkalyanms - is this in C# extension?)


@timheuer I've installed the necessary dependencies' extension, but I'm having some issues. NuGet automatically restores in the background, and since I'm using a custom registry that doesn't support parallel processing, the automatic restore by the C# Dev Kit causes errors. Is there a way to configure it to pass the `--disable-parallel` parameter?

**Comment by timheuer** [comment]
> Is there a way to configure it to pass the `--disable-parallel` parameter?

There is not presently -- this is good to get to specific issues -- I recommend opening a new specific issue for this one (restore) --  so we can tag NuGet engineers.

**Comment by arkalyanms** [comment]
I suspect the razor telemetry download has a tracking issue already. I dont know if there will be another roadblock after that, but that seems to the first one. So starting with @phil-allen-msft.

**Comment by phil-allen-msft** [comment]
With changes from May, C# Dev Kit should no longer download Razor telemetry pieces.

**Comment by ryzngard** [comment]
Correct. The razor portion of this is done in [2.36.19](https://github.com/dotnet/vscode-csharp/blob/main/CHANGELOG.md#23619)

It looks like the rest of the issues have a workaround for how to install offline or asked to be open as a new issue. I'm going to close but feel free to re-open if you are seeing issues!
