### ISSUE TITLE
Is C# DevKit extension bound to .NET SDK 7.0?

### ISSUE THREAD

**Issue by smartware163** [microsoft/vscode-dotnettools#760]
### Describe the Issue

We have .NET SDK8.0 and the maui workload installed outside VSCode, but when we try to create MAUI projects the MAUI extension will download and install .NET SDK 7.0 automatically, so is .NET SDK 7.0 the only version VSCode MAUI extension supports?

**Comment by guxiaobo** [comment]
Do we have an option to specify the .NET SDK version to use with MAUI extension?

**Comment by emaf** [comment]
The MAUI extension does not download any .NET versions, and it behaves as dotnet CLI, where it uses the latest installed version by default, or the version specified in a global.json file. See [Select the .NET version to use](https://learn.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version).

@smartware163 Could you share what you are seeing that's making you think that the MAUI extension is downloading .NET 7?

**Comment by GlacierFox** [comment]
> The MAUI extension does not download any .NET versions, and it behaves as dotnet CLI, where it uses the latest installed version by default, or the version specified in a global.json file. See [Select the .NET version to use](https://learn.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version).
> 
> @smartware163 Could you share what you are seeing that's making you think that the MAUI extension is downloading .NET 7? This could be some misleading messaging coming from the MAUI or C# Dev Kit extensions.

Probably referring to this.

```
ms-dotnettools.csdevkit requested to download the .NET Runtime.
Downloading .NET version(s) 7.0.15~x64 .......... Done!
.NET 7.0.15~x64 executable path: /home/danny/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.15~x64/dotnet
```

Happens on linux distros I've tried. As soon as I open my project I get the .Net Install tool installing version 7 even though I have 8 installed and it's fully functional for use outside of vs code.

**Comment by emaf** [comment]
@tmeschter Would this be C# Dev Kit project system or CPS?

cc @mauroa

**Comment by ZGMF-X56S** [comment]
I've got the same situation,I already have installed .Net 8, but it still download .Net 7.
<img width="1246" alt="截屏2024-02-03 11 39 27" src="https://github.com/microsoft/vscode-dotnettools/assets/56222366/33abafb6-4872-420f-8007-5e50100ca038">

**Comment by mauroa** [comment]
Ping @tmeschter about this, AFAIK C# DevKit just changed the support to dotnet 8, but just wanted to confirm if this is still an issue and where we should assign it.

**Comment by webreidi** [comment]
Yes, closing this as C# Dev Kit now runs on .NET 8.
