### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Bulo920** [microsoft/vscode-dotnettools#764]
### Describe the Issue

![image](https://github.com/microsoft/vscode-dotnettools/assets/40779722/04f05685-6a46-47b7-8350-33e77ec2bc01)

**Comment by jbevain** [comment]
The Unity extension requires Visual Studio Code 1.76.0. Please update your Visual Studio Code. Thanks!

**Comment by Bulo920** [comment]
> Unity 扩展需要 Visual Studio Code 1.76.0。请更新您的 Visual Studio 代码。谢谢！

Okay, thank you
