### ISSUE TITLE
Cant create a new file in project

### ISSUE THREAD

**Issue by wgrs** [microsoft/vscode-dotnettools#767]
Type: <b>Bug</b>

Error running command csdevkit.addNewFile: Failed with ExitCode(100)
Details
Failed to instatiate template 'Class', the following constraints are not met:
   Project capabiltities: /home/xxx/Dev/Projects/FSBO/src/Api/Api.csproj is not restored. Run 'dotnet restore /home/greg/Dev/Projects/FSBO/src/Api/Api.csproj' to restore the project.

To run the template anyway, use '--force' option:
   dotnet new class -n Class1 --force

For details on the exit code, refer to https://aka.ms/templating-exit-codes#100
. This is likely caused by the extension that contributes csdevkit.addNewFile.

Extension version: 1.0.14
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.0-13-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.66GB (4.69GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 2e58bea4-2abd-486f-ba1a-d660f0ad9c03|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
a247i228:30880122
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by smitpatel** [comment]
Error indicates that project is not restored. Can you restore project manually and try again? There may be possibly restore errors.

**Comment by wgrs** [comment]
What do you mean manually? I have run dotnet restore and that reports all project restored but the error persists. New file command is broken

**Comment by wgrs** [comment]
Yes, and when I run the restore command in the error message, the issue persists

**Comment by smitpatel** [comment]
Can you share a repro project and .NET version you are using.

**Comment by wgrs** [comment]
I can't share the project. Its .net 8, vscode, and Ubuntu. The problems seem to be coming from the dev kit.

**Comment by wgrs** [comment]
I noticed that thus issue only occurs when trying to add a new file from SOLUTION EXPLORER panel

**Comment by smitpatel** [comment]
@wgrs - Can you try to see if you are still seeing the same issue in latest release of C# dev kit. We don't have enough information to investigate here.

**Comment by smitpatel** [comment]
Closing the issue as we haven't heard back in a while, and we don't have enough information to investigate. We can re-open if user responds.
