### ISSUE TITLE
[BUG] Breakpoints not hit in .NET Maui iOS app running on mac

### ISSUE THREAD

**Issue by trampster** [microsoft/vscode-dotnettools#770]
### Describe the Issue

When I launch the iOS .NET Maui app via fn-F5 then the app launches and vscode shows it's debugging but no breakpoints get hit.

### Steps To Reproduce

1. Open .NET MAUI app which targets net8.0-ios with vscode on Mac
2. Add a break point in a location guaranteed to be hit
3. Start debugging on an attached iPhone using fn-f5
-> breakpoints never get hit

### Expected Behavior

Stops on breakpoints

### Environment Information

 - OS: Mac
 - vscode version: 1.84.2
 - .NET MAUI extension version: v0.5.50

> VS bug [#1925508](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1925508), VS bug [#1930938](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1930938)

**Comment by trampster** [comment]
I can reproduce this on a minimal .net maui app created with `dotnet new maui`

**Comment by SteveBush** [comment]
Any updates on fixing this. I would like to debug an IOS application on the Mac.  With Visual Studio for Mac being discontinued, VS Code is my only option for debugging Maui apps.

**Comment by sullivanmj** [comment]
I was able to work around this by adding `<MtouchDebug>true</MtouchDebug>` to my iOS csproj.

**Comment by mauroa** [comment]
Hi everyone. Could you confirm if the first time the app launches, you see a prompt in the iOS device asking for permissions to find and connect to devices in your local network?

Also, if that happens and after clicking allow, can you confirm if the second time you try to debug (with the application already installed), you are able to do it?

Thanks

**Comment by mauroa** [comment]
We created a feature request ticket to fix this known issue and support WiFi debugging: https://github.com/microsoft/vscode-dotnettools/issues/1081

There are specific details of the issue and workaround in there.
I'll proceed to close this, since the only fix for now is to apply the workaround.
Thanks for your help and patience. We'll keep you posted about the feature implementation.

**Comment by vbisbest** [comment]
This is not resolved for maccatalyst apps.  Break points do not hit.   @mauroa
