### ISSUE TITLE
[BUG] Impossible to debug VSCODE

### ISSUE THREAD

**Issue by aspirio187** [microsoft/vscode-dotnettools#773]
### Describe the Issue

When launching the debug of a project by right clicking on it in the solution explorer and selecting start a new instance, in my terminal I see the build result and then nothing. It's just standing there doing nothing.

I see a loading icon with the text _Extension activation_ (something like that, my vscode is in french and it says _Activation des extensions_).

![image](https://github.com/microsoft/vscode-dotnettools/assets/56565073/a8c2d4bc-aacb-4022-bb35-97d3b075e9e7)

![image](https://github.com/microsoft/vscode-dotnettools/assets/56565073/6998ac20-5926-48e3-beb6-6c9216bddb1c)

![image](https://github.com/microsoft/vscode-dotnettools/assets/56565073/685ae05d-d103-4be4-bc7a-0bc017d0b96b)

There is nothing more after the last screenshot except the small _Loading extensions_,

This issue must be linked only to me because my colleague can debug the project while following the same steps.

### Expected Behavior

It should debug

### Environment Information

- OS: Ubuntu (WSL)
- vscode: 1.84.2

**Comment by WardenGnaw** [comment]
Can you go to the `Extensions` tab and check to see if the C# Extension and C# Dev Kit have been activated?

You can hover over each extension and see if has `Activation Time (Startup)`
![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/c34c17f0-9089-4469-9245-f34812685286)

**Comment by aspirio187** [comment]
I fixed it.

**Comment by aspirio187** [comment]
I decided it would be easier to completely remove all C# extensions from vscode and reinstall everything. That's what I did and the issue is fixed (for now). Thanks !
