### ISSUE TITLE
[SUGGESTION] Missing checkForDevCert for launch.json on type="dotnet"

### ISSUE THREAD

**Issue by junalmeida** [microsoft/vscode-dotnettools#774]
### Describe the feature you'd like

In vscode `launch.json` file, for a configuration of type `dotnet`, `checkForDevCert` is missing.

### Alternatives considered

Use `coreclr` type.

**Comment by WardenGnaw** [comment]
@junalmeida Feel free to re-open this issue if you still experience this issue with the useSSL setting being set in your launchSettings profile and that profile is selected for launch.
