### ISSUE TITLE
Clickable link in types' tooltips

### ISSUE THREAD

**Issue by minhtaile2712** [microsoft/vscode-dotnettools#781]
### Describe the feature you'd like

In Visual Studio when I hover over a type (`FullAuditedAggregateRoot` in this screenshot), a tooltip shows up. In this tooltip, I can click on any type that appears to go to the decompiled file or the source code of that type.

![image](https://github.com/microsoft/vscode-dotnettools/assets/53080238/56535b18-70ba-4510-8434-238dd116ea93)

It's not the case in VS Code, in which every tooltip of a type is readonly. Yes its texts can be selected, but no clickable links are provided.

![image](https://github.com/microsoft/vscode-dotnettools/assets/53080238/27498236-d4a2-4b85-b03e-4f7e61a65be4)

Can VS Code have the same behavior as in Visual Studio?

**Comment by dibarbet** [comment]
Tracking on the C# extension side.
https://github.com/dotnet/vscode-csharp/issues/6762
