### ISSUE TITLE
[BUG] Spaces in MacCatalyst path or filename break debugging

### ISSUE THREAD

**Issue by maddymontaquila** [microsoft/vscode-dotnettools#782]
### Describe the Issue

If you have a space in an ApplicationName or build path, MacCatalyst won't launch or debug the app, however the build succeeds and the .app bundle exists in bin/ as expected (and can be launched no problem). This doesn't happen on iOS so is a maccat specific issue.

### Steps To Reproduce

Repro:
1. Create a MAUI App with a space in the app name or path (for example, My App or ~/My App/MyApp.csproj
2. Debug targeting macOS 

### Expected Behavior

Expected: App launches and debugs
Actual: App doesn't launch because it can't find .app file (it truncates at the space in the filepath), however debugging starts even though the app didn't launch. The only error is in Debug Console
![image](https://github.com/microsoft/vscode-dotnettools/assets/12660687/eb77cc6e-948c-4ab6-aad8-318859dcde79)
![image](https://github.com/microsoft/vscode-dotnettools/assets/12660687/47652a4b-af70-4109-8654-50ce58c6bb09)

### Environment Information

Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

.NET MAUI extension v0.5.50
.NET 8
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2032252">2032252</a>

**Comment by tounaobun** [comment]
+1.

**Comment by SamuelJames101** [comment]
This is still an issue!

**Comment by tounaobun** [comment]
The only work around to debug app with space in app name is to delete space, how annoying is that. BTW,  Visual Studio for Mac  had no this issue, Xcode native way also does not have this issue.

**Comment by AllenD-MSFT** [comment]
This issue has been fixed in the latest Prerelease version of MAUI DevKit. The Release channel update in December should contain the fix and is scheduled for next week.
