### ISSUE TITLE
[BUG] One or more errors occurred, Solutions explorer not opening all my files Ubuntu VSCode C# extension pack

### ISSUE THREAD

**Issue by HUNZALAMUSHTAQ** [microsoft/vscode-dotnettools#787]
### Describe the Issue

Apologies for mistake or any incomplete info this is my first time posting an issue ;)

A unexpected issue has occurred while solution explorer is not opening all the files in vs code and giving error like 
![image](https://github.com/microsoft/vscode-dotnettools/assets/75185145/b27e6c68-38da-4fd8-bb4f-8fb39891f038)

One or more errors occurred. (An error occurred trying to start process '/usr/local/bin/dotnet' with working directory '/home/username/Training/dnt'. No such file or directory)

### Steps To Reproduce

Create a simple Console App and run while loop till infinity. The vscode will stop working and rerun project using solutions explorer.

### Environment Information

VSCODE version : 1.84.2
C# extension pack: v1.1.16
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by HUNZALAMUSHTAQ** [comment]
![image](https://github.com/microsoft/vscode-dotnettools/assets/75185145/f88f97f0-647d-436d-bba8-ed62a8e9439b)

**Comment by tmeschter** [comment]
@HUNZALAMUSHTAQ Can you provide the output of `dotnet --info` on the command line?

**Comment by HUNZALAMUSHTAQ** [comment]
> @HUNZALAMUSHTAQ Can you provide the output of `dotnet --info` on the command line?

.NET SDK (reflecting any global.json):
 Version:   6.0.125
 Commit:    e898a826c2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.125/

global.json file:
  Not found

Host:
  Version:      6.0.25
  Architecture: x64
  Commit:       492abbeef0

.NET SDKs installed:
  6.0.125 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by Neshat0** [comment]
Hello this is my first time giving an answer here, I don't know if there are any specific rules.

I had the same issue on my macbook air M1, all I did was go to [/usr/local/bin] and deleted the [dotnet] file and after deleting it run this command [sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin] (without the square brackets).

After creating the new link I reloaded VS Code and the solution opened.

**Comment by tmeschter** [comment]
@HUNZALAMUSHTAQ Can you provide us more information on how you installed the .NET SDK?

**Comment by webreidi** [comment]
@HUNZALAMUSHTAQ please reopen this issue if you are still experiencing problems and provide the information about how you installed the .NET SDK and whether the directories above exist on your machine.
