### ISSUE TITLE
[BUG] C# dev kit should respect the `dotnet.dotnetPath` set by C# extension

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/vscode-dotnettools#792]
### Describe the Issue

If I set a custom path for dotnet SDK and runtime for C# extension using setting `dotnet.dotnetPath` like below. 
```json
    "dotnet.dotnetPath": "C:\\Users\\{username}\\AppData\\Local\\Microsoft\\dotnet"
```
I can see the C# extension uses that to load the base language service. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/95d86f1b-1621-4c16-8731-f0e66890f4dc)

but if I see C# dev kit  (and it's test explorer) logs, it's still loading it's tooling from the SDK found on the path. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/eea9a78c-688c-4f64-bbee-4c0ed3f94c2c)

which I think is incorrect, C# dev kit should respect the SDK chosen by base C# extension.

**Comment by AbhitejJohn** [comment]
@peterwald : Did we already address this?

**Comment by peterwald** [comment]
Test Explorer does not use the dotnet.dotnetPath currently.

**Comment by ShreyasJejurkar** [comment]
1 thing of 100 things.

C# Dev kit components should not deviate from the options set by base C# extension.
This single thing will avoid plethora of bugs and issues.

**Comment by kepiz** [comment]
Any way to fix this in the meantime?

**Comment by peterwald** [comment]
The extension has been updated to set the DOTNET_PATH for child processes to the value of dotnet.dotnetPath when set. The change will ship in the next prerelease version.

**Comment by ShreyasJejurkar** [comment]
Is this even made to pre-release or not yet? I have the below version installed. 
![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/7104f900-1013-4cb2-93ad-e4c1a5981f73)

When I check logs, I still see the C# dev kit loading the runtime from the path variable instead of the configured one in VSCode JSON settings. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/10dec866-486b-45d2-99f4-3a8c4dd8d4d9)

**Comment by peterwald** [comment]
@ShreyasJejurkar Yes, that change should be in pre-release. 

Note that the log message you are seeing there is a different code path than what I updated. I believe that log message is showing which instance of .NET is being used to run the language services.

After my change, child processes of the extension (i.e. your tests) should run with DOTNET_ROOT set in the environment to the value of dotnet.dotnetPath.

Can you describe what you are trying to accomplish here?

**Comment by ShreyasJejurkar** [comment]
> I believe that log message is showing which instance of .NET is being used to run the language services

I don't think that is true, because when I see the base C# extension logs, I can see it's using the `dotnetPath` set by me in `settings.json` which is correct.  

![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/8e2dde36-d494-4aa3-8303-71633bc8613f)

But whereas if you see the C# dev kit and its component, they are still loading their stuff from the dotnet found on the path, instead of using the ones that the user has configured using `dotnet:dotnetPath`. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/8719d76c-6dfe-453d-87ef-92b7b12f3c74)

![image](https://github.com/microsoft/vscode-dotnettools/assets/17148381/ee5986b1-2964-413c-9b07-807fbfba1690)

So the issue, the C# dev kit and its component should not load their components from another dotnet sdk if the user has configured the dotnetpath in settings.

**Comment by peterwald** [comment]
@lifengl @arkalyanms @timheuer Do you have any thoughts on this? This is not a testing issue, it's more core to the dev environment.

**Comment by nagilson** [comment]
Awkwardly, there is another setting for the same thing from the .NET Install Tool extension / runtime extension. C#DK would need an update to respect this setting, and we'd probably want to decide which setting takes precedence.

**Comment by rmarinho** [comment]
Hey, this seems to not be working as expected, and I see more bugs related with this experience. 

The .NET MAUI team has need for this feature to work, because is the only way we could load our custom installation with bits that are not yet release and need some testing. This actually works fine with Visual Studio on windows and it even worked with Visual Studio Mac. 

My understanding is that if we set the correct environment variables, c# dev kit would just load our provisioned dotnet and workloads instead of the global ones

Here' s the workflow.. 

- Provisions the a new .net sdk and custom workloads on a custom folder like `/Users/ruimarinho/dotnet/maui/bin/dotnet`
- Set Enviroment variables like so  and launch VSCOde from the same terminal process

```bass
========================================
VSCode
========================================
Setting environment variable: RestorePackagesPath = '/var/folders/4p/2__p2v8s73q7wgtbhbvchngc0000gn/T/Microsoft.Maui.Cache/NuGet/packages'
Setting environment variable: NUGET_PACKAGES = '/var/folders/4p/2__p2v8s73q7wgtbhbvchngc0000gn/T/Microsoft.Maui.Cache/NuGet/packages'
Setting environment variable: VSDebugger_ValidateDotnetDebugLibSignatures = '0'
Setting environment variable: DOTNET_INSTALL_DIR = '/Users/ruimarinho/dotnet/maui/bin/dotnet'
Setting environment variable: DOTNET_ROOT = '/Users/ruimarinho/dotnet/maui/bin/dotnet'
Setting environment variable: DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR = '/Users/ruimarinho/dotnet/maui/bin/dotnet'
Setting environment variable: DOTNET_MULTILEVEL_LOOKUP = '0'
Setting environment variable: MSBuildEnableWorkloadResolver = 'true'
Setting environment variable: PATH = '/Users/ruimarinho/dotnet/maui/bin/dotnet:/Users/ruimarinho/dotnet/maui/bin/dotnet:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:/Users/ruimarinho/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ruimarinho/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/latest/bin:~/.dotnet/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/emulator:/Users/ruimarinho/Library/Python/3.9/bin'
/Users/ruimarinho/dotnet/maui/bin/dotnet:/Users/ruimarinho/dotnet/maui/bin/dotnet:/Users/ruimarinho/dotnet/maui/bin/dotnet:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:/Users/ruimarinho/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ruimarinho/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/latest/bin:~/.dotnet/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/emulator:/Users/ruimarinho/Library/Python/3.9/bin
```

**Comment by nagilson** [comment]
@rmarinho Per internal discussion, we would like to get a repro of what you're facing and maybe a dump of the .NET Host to see which .NET is being picked up.

**Comment by nagilson** [comment]
dotnetAcquisitionExtension.sharedExistingDotnetPath Is only for the runtime of CDK to run under. @adrianvmsft  is working on changing C# DevKit so that it uses our new API to improve the experience for finding .NET

**Comment by wsilveiranz** [comment]
@nagilson is this issue still being actively worked on? We have a situation where our extension (Logic Apps Standard) uses the C# DevKit for both implementing custom code and unit tests. Our version of support .NET can be behind the previous versions, so we use standard folder to keep the supported versions of .NET. We are hitting this bug now which impacts project load and intelisense. Happy to discuss offline if you want.

**Comment by nagilson** [comment]
The bug fix on our side was completed a long time ago, but there were performance regressions that we have slowly been working out before CDK is turning it on by default. If you search for the 'use legacy dotnet resolution' setting and uncheck it, does this fix it for you? @wsilveiranz

**Comment by wsilveiranz** [comment]
Let me try that, @nagilson and I will report back.

**Comment by wsilveiranz** [comment]
Hi @nagilson - I am receiving an **"unknown setting"** for dotnet.dotnetPath. My workspace settings  looks like this (and I can't find the Dotnet Path property in the C# extension.

```json
{
  "folders": [
    {
      "name": "LogicApps",
      "path": "./LogicApps"
    },
    {
      "path": "SampleCalls"
    }
  ],
  "settings": {
    "terminal.integrated.env.windows": {
      "PATH": "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK;${env:PATH}"
    },
    "debug.internalConsoleOptions": "neverOpen",
    "azurite.location": "C:\\Users\\wsilveira\\.azurelogicapps\\.azurite",
    "omnisharp.dotNetCliPaths": [
      "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK"
    ],
    "dotnet.useLegacyDotnetResolution": false,
    "dotnet.dotnetPath": "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK\\"
  }
}
```
Extension versions:
- .NET Install Tool: 2.3.2
- C#: 2.72.27
- C# Dev Kit: 1.18.23

**Comment by nagilson** [comment]
The setting is technically part of the .net install tool, which is the api surface that c# uses. 
https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime#:~:text=dotnetAcquisitionExtension.sharedExistingDotnetPath.-,Example%3A,-%22dotnetAcquisitionExtension.sharedExistingDotnetPath

The setting should be `dotnetAcquisitionExtension.sharedExistingDotnetPath`.

`useLegacyDotnetResolution` should be turned off by default within the next 1-2 months.

**Comment by nagilson** [comment]
`dotnet.dotnetPath` was deprecated in favor of this setting -- sorry for the confusion. The setting described above has existed for longer than the dotnet.dotnetPath setting and applies to also CDK and not just C#, so it was preferred. Note, that this setting is only for the runtime and not the SDK.

**Comment by wsilveiranz** [comment]
@nagilson - Tried with sharedExistingDotnetPath or existingDotnetPath making it explicit to C# Dev Kit.

It seems like it is not taking that path in consideration. Seems like what you are saying here is that this will only be used to build apps, but not to load the solution? Here is the error I am finding and the latest configuration:

Config:
```json
{
  "folders": [
    {
      "name": "LogicApps",
      "path": "./LogicApps"
    },
    {
      "path": "SampleCalls"
    }
  ],
  "settings": {
    "terminal.integrated.env.windows": {
      "PATH": "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK;${env:PATH}"
    },
    "debug.internalConsoleOptions": "neverOpen",
    "azurite.location": "C:\\Users\\wsilveira\\.azurelogicapps\\.azurite",
    "omnisharp.dotNetCliPaths": [
      "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK"
    ],
    "dotnet.useLegacyDotnetResolution": false,
    "dotnetAcquisitionExtension.existingDotnetPath": [
      {
          "extensionId": "ms-dotnettools.csdevkit",
          "path": "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK\\dotnet.exe"
      }
  ]
  }
}
```

C# Devkit output: **Using existing .NET runtime at "C:\Program Files\dotnet\dotnet.exe" to load Dev Kit processes.**

```text
Starting Spawn .NET server...
Using dotnet resolution provided by ".NET Install Tool".
Starting opening a solution...
Starting processing the solution file "c:\dev\CodefulPOC\LogicApps\LogicApps.sln" in Dev Kit server...
Using existing .NET runtime at "C:\Program Files\dotnet\dotnet.exe" to load Dev Kit processes.
.NET Sdk found: "C:\Program Files\dotnet\dotnet.exe".
.NET server started and IPC established in 1780ms
Completed Spawn .NET server (11660ms)
Completed processing the solution file "c:\dev\CodefulPOC\LogicApps\LogicApps.sln" in Dev Kit server (11598ms)
Starting restoring NuGet packages...
Selected configuration: <Default>, active configuration: Debug|Any CPU
Completed opening a solution (11636ms)
Starting command: "dotnet.exe" restore C:\dev\CodefulPOC\LogicApps\LogicApps.sln --interactive...
Failed at 'command: "dotnet.exe" restore C:\dev\CodefulPOC\LogicApps\LogicApps.sln --interactive' (142ms) with error: ExitCodeError: Failed with ExitCode(2147516561)
Details
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible .NET SDK was not found.

Requested SDK version: 8.0.408
global.json file: c:\dev\CodefulPOC\LogicApps\global.json

Installed SDKs:

Install the [8.0.408] .NET SDK or update [c:\dev\CodefulPOC\LogicApps\global.json] to match an installed SDK.
```

**Comment by nagilson** [comment]
Yes, this setting is only for the runtime that runs the code of C# and C#DevKit themselves, not the project. 
Im guessing this is a 'local' or zip folder SDK install? Is there a reason why you can't add it to your PATH environment variable in the workspace or machine (assuming it isnt added there because I would expect that to work)?

**Comment by wsilveiranz** [comment]
@nagilson - unless I got this wrong, I thought I already had this in the settings:

"terminal.integrated.env.windows": {
      "PATH": "C:\\Users\\wsilveira\\.azurelogicapps\\dependencies\\DotNetSDK;${env:PATH}"
}

Would you recommend another setting for this?

**Comment by nagilson** [comment]
@wsilveiranz I think that should correctly set it for the terminal, but it doesn't set it within the environment that vscode and the machine runs under, which is somewhat separate (the idea that CDK focused on is that the terminal outside of vscode will work the same as how devkit works), but this is helpful in that we might want to revisit that decision and see if we can also respect the terminal env. cc @lifengl as this is an interesting point.

Anyways, this may be a good solution to your issue, in your launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {           
            "env": {
                "ENVVAR": "FOO",
            },
            ...
        }
    ]
}
``` 

Thanks for coordinating, I hope this works. If not, happy to discuss offline.

**Comment by Baltasarq** [comment]
Same here. I'm using Manjaro Linux (Arch derivative), with KDE.


    Linux PC-baltasarq 6.14.0-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed, 26 Mar 2025 07:48:57 +0000 x86_64 GNU/Linux


Before I launch VSCode, this is the terminal configuration:

```bash
$ echo $0
/bin/zsh

$ echo $DOTNET_ROOT
/home/baltasarq/bin/dotnet/

$ which dotnet                                                                                                                                                                                    
/home/baltasarq/bin/dotnet/dotnet

$ dotnet --version                                                                                                                                                                                
9.0.203
```

I have a system-wide dotnet installation in /usr/share, required for an installed program. Anyway, the installation I prefer is in ~/bin/dotnet, as shown.

```bash
$ /usr/share/dotnet/dotnet --info                                                                                                                                                             
Host:
  Version:      9.0.4
  Architecture: x64
  Commit:       b7deac6d42
  RID:          arch-x64
```

My installation is the first one in the path, and it seems to work correctly from command prompt.

```bash
dotnet --info                                                                                                                                                                                    ✔ 
SDK DE .NET:
 Version:           9.0.203
 Commit:            dc7acfa194
 Workload version:  9.0.200-manifests.9df47798
 MSBuild version:   17.13.20+a4ef1e90f

Execution environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/baltasarq/bin/dotnet/sdk/9.0.203/

Host:
  Version:      9.0.4
  Architecture: x64
  Commit:       f57e6dc747

.NET SDKs installed:
  9.0.203 [/home/baltasarq/bin/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.4 [/home/baltasarq/bin/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.4 [/home/baltasarq/bin/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/baltasarq/bin/dotnet]

global.json file:
  /home/baltasarq/Dropbox/Prys/Colorado/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

Then I open VSCode. My settings.json is:

```json
{
    "editor.fontSize": 16,
    "dotnet.useLegacyDotnetResolution": false,
    "dotnetAcquisitionExtension.existingDotnetPath": [
        "/home/baltasarq/bin/dotnet/dotnet",
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "/home/baltasarq/bin/dotnet/dotnet"
        }
    ],
    "dotnetAcquisitionExtension.sharedExistingDotnetPath": "/home/baltasarq/bin/dotnet/dotnet",
    "omnisharp.dotnetPath": "/home/baltasarq/bin/dotnet/",
    "workbench.startupEditor": "none"
}
```

The `global.json` file in the project directory is:

```json
{
  "sdk": {
    "version": "9.0.203",
    "rollForward": "latestFeature",
    "paths": [
        "/home/baltasarq/bin/dotnet"
    ]
  }
}
```

In VSCode's terminal, everything works just fine, as in the system's terminal.

Next I open a C# project, it complains it is not able to find the required C#. I've set the "use legacy find dotnet" setting (or however it is named) to false. The logs for C# are as follows:


```log
2025-05-07 12:58:02.862 [info] Locating .NET runtime version 9.0.1
2025-05-07 12:58:02.974 [info] Dotnet path: /home/baltasarq/bin/dotnet/dotnet
2025-05-07 12:58:02.974 [info] Activating C# + C# Dev Kit...
2025-05-07 12:58:03.550 [info] [stdout] {"pipeName":"/tmp/195e8950.sock"}

2025-05-07 12:58:03.550 [info] received named pipe information from server
2025-05-07 12:58:03.551 [info] client has connected to server
2025-05-07 12:58:03.680 [info] [Info  - 12:58:03 PM] [Program] Language server initialized
```

I don't know what else to try. Any clue?

-- Baltasar

**Comment by nagilson** [comment]
> Same here. I'm using Manjaro Linux (Arch derivative), with KDE.
> 
> ```
> Linux PC-baltasarq 6.14.0-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed, 26 Mar 2025 07:48:57 +0000 x86_64 GNU/Linux
> ```
> 
> Before I launch VSCode, this is the terminal configuration:
> 
> $ echo $0
> /bin/zsh
> 
> $ echo $DOTNET_ROOT
> /home/baltasarq/bin/dotnet/
> 
> $ which dotnet                                                                                                                                                                                    
> /home/baltasarq/bin/dotnet/dotnet
> 
> $ dotnet --version                                                                                                                                                                                
> 9.0.203
> I have a system-wide dotnet installation in /usr/share, required for an installed program. Anyway, the installation I prefer is in ~/bin/dotnet, as shown.
> 
> $ /usr/share/dotnet/dotnet --info                                                                                                                                                             
> Host:
>   Version:      9.0.4
>   Architecture: x64
>   Commit:       b7deac6d42
>   RID:          arch-x64
> My installation is the first one in the path, and it seems to work correctly from command prompt.
> 
> dotnet --info                                                                                                                                                                                    ✔ 
> SDK DE .NET:
>  Version:           9.0.203
>  Commit:            dc7acfa194
>  Workload version:  9.0.200-manifests.9df47798
>  MSBuild version:   17.13.20+a4ef1e90f
> 
> Execution environment:
>  OS Name:     manjaro
>  OS Version:  
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /home/baltasarq/bin/dotnet/sdk/9.0.203/
> 
> Host:
>   Version:      9.0.4
>   Architecture: x64
>   Commit:       f57e6dc747
> 
> .NET SDKs installed:
>   9.0.203 [/home/baltasarq/bin/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 9.0.4 [/home/baltasarq/bin/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 9.0.4 [/home/baltasarq/bin/dotnet/shared/Microsoft.NETCore.App]
> 
> Other architectures found:
>   None
> 
> Environment variables:
>   DOTNET_ROOT       [/home/baltasarq/bin/dotnet]
> 
> global.json file:
>   /home/baltasarq/Dropbox/Prys/Colorado/global.json
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download
> Then I open VSCode. My settings.json is:
> 
> {
>     "editor.fontSize": 16,
>     "dotnet.useLegacyDotnetResolution": false,
>     "dotnetAcquisitionExtension.existingDotnetPath": [
>         "/home/baltasarq/bin/dotnet/dotnet",
>         {
>             "extensionId": "ms-dotnettools.csharp",
>             "path": "/home/baltasarq/bin/dotnet/dotnet"
>         }
>     ],
>     "dotnetAcquisitionExtension.sharedExistingDotnetPath": "/home/baltasarq/bin/dotnet/dotnet",
>     "omnisharp.dotnetPath": "/home/baltasarq/bin/dotnet/",
>     "workbench.startupEditor": "none"
> }
> The `global.json` file in the project directory is:
> 
> {
>   "sdk": {
>     "version": "9.0.203",
>     "rollForward": "latestFeature",
>     "paths": [
>         "/home/baltasarq/bin/dotnet"
>     ]
>   }
> }
> In VSCode's terminal, everything works just fine, as in the system's terminal.
> 
> Next I open a C# project, it complains it is not able to find the required C#. I've set the "use legacy find dotnet" setting (or however it is named) to false. The logs for C# are as follows:
> 
> ```
> 2025-05-07 12:58:02.862 [info] Locating .NET runtime version 9.0.1
> 2025-05-07 12:58:02.974 [info] Dotnet path: /home/baltasarq/bin/dotnet/dotnet
> 2025-05-07 12:58:02.974 [info] Activating C# + C# Dev Kit...
> 2025-05-07 12:58:03.550 [info] [stdout] {"pipeName":"/tmp/195e8950.sock"}
> 
> 2025-05-07 12:58:03.550 [info] received named pipe information from server
> 2025-05-07 12:58:03.551 [info] client has connected to server
> 2025-05-07 12:58:03.680 [info] [Info  - 12:58:03 PM] [Program] Language server initialized
> ```
> 
> I don't know what else to try. Any clue?
> 
> -- Baltasar

Thanks, that provides a lot of context and I can tell you put thought into it. Everything there looks correct....
'Next I open a C# project, it complains it is not able to find the required C#' - What error does it give you?

Note: The existing path setting applies to the runtime that C# and DevKit run their code under (They are extensions written in .NET) but it does not apply to the SDK that gets used. However, it seems to be working fine up to the point in your logs. Past the point of language server start I'm not very knowledgeable about, so I may defer to @lifengl, or @webreidi if she knows someone else since the other contact is out.

**Comment by Baltasarq** [comment]
> Everything there looks correct....
'Next I open a C# project, it complains it is not able to find the required C#' - What error does it give you?

The error in the log is this one:

    2025-05-10 21:00:04.830 [info] A compatible .NET SDK was not found.

Which manifests itself visually as:

![VS Code error about being unable to find the .NET SDK](https://github.com/user-attachments/assets/8174d96c-3627-4a3d-96d7-4c8de002bfe6)

**Comment by Baltasarq** [comment]
I was able to solve it. Since `DOTNET_ROOT` was not respected, I had created a `global.json` file in the directory project.

```json
{
  "sdk": {
    "version": "9.0.203",
    "rollForward": "latestFeature",
    "paths": [
        "/home/baltasarq/bin/dotnet"
    ]
  }
}
```

I modified the `version` field to be 9.0.4 (the "global" version?) instead of 9.0.203 (the SDK version).  This seems to do the trick.
The bug is still there, though. I mean, any other option does not get the desired SDK to be chosen.

**Comment by nagilson** [comment]
```
We need a concise way for this tools to resolve the:
- dotnet CLI (host) used by the VSCode extension's code
```

This exists for finding the runtime, by utilizing the `dotnet.findPath` API.

```
dotnet CLI (host) used to trigger tasks on the user's code
```

The `dotnet.findPath` API also can find SDKs on the disk, though it does not read the `global.json`. The logic of specifying which sdk to use for the user project is not part of this API.

I like the idea of adding an additional setting for the user's code.

**Comment by marcopelegrini** [comment]
>This exists for finding the runtime, by utilizing the dotnet.findPath API.

Is this part of the `.NET Install Tool` ?

> The dotnet.findPath API also can find SDKs on the disk, though it does not read the global.json. The logic of specifying which sdk to use for the user project is not part of this API.

And IMO it shouldn't be. I think there are 2 cases:
- Simple solutions, run of the mill solutions - use whatever cli/SDK the C# SDK found
- Complex solutions / multi solutions - one of the 3 extensions should offer the possibility for the user to specific an override for vscode and per solution

For instance, Rider saves a `Solution.sln.DotSettings` file with a couple of options when you override the defaults:

`<s:String x:Key="/Default/Environment/Hierarchy/Build/BuildTool/CustomBuildToolPath/@EntryValue">/usr/local/share/dotnet/x64/sdk/9.0.300/MSBuild.dll</s:String>
	<s:String x:Key="/Default/Environment/Hierarchy/Build/BuildTool/DotNetCliExePath/@EntryValue">/usr/local/share/dotnet/x64/dotnet</s:String>`

I think we can support something in the `.vscode` folder which I think it's already being used for some things and add support for a file where users can specify the dotnetCliPath (not sure if we need the MSBuild as the build itself runs through dotnet cli, but I'm not 100% sure about this)

**Comment by rmarinho** [comment]
Heres my example, we have cake script that installs for example dotnet net10.0-preview6 and the iOS and android workloads for preview 6 in a maui/.dotnet folder 

then we pass these variables to VS and VSCode, you can see that we pass `DOTNET_ROOT'  and on the pATH the sdk is also there . 

This works as expected on Visual Studio on windows, I can then debug new sdks and new workloads to fix bugs . In also worked on the old Visual Studio For Mac. 
But for months we can debug iOS apps with new workloads since VSCODE doesn t respect this. I did tried change the dotnet.dotnetPath but no luck.


```
Insiders
========================================
Setting environment variable: RestorePackagesPath = '/var/folders/4p/2__p2v8s73q7wgtbhbvchngc0000gn/T/Microsoft.Maui.Cache/NuGet/packages'
Setting environment variable: NUGET_PACKAGES = '/var/folders/4p/2__p2v8s73q7wgtbhbvchngc0000gn/T/Microsoft.Maui.Cache/NuGet/packages'
Setting environment variable: VSDebugger_ValidateDotnetDebugLibSignatures = '0'
Setting environment variable: DOTNET_INSTALL_DIR = '/Users/ruimarinho/dotnet/maui/.dotnet'
Setting environment variable: DOTNET_ROOT = '/Users/ruimarinho/dotnet/maui/.dotnet'
Setting environment variable: DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR = '/Users/ruimarinho/dotnet/maui/.dotnet'
Setting environment variable: DOTNET_MULTILEVEL_LOOKUP = '0'
Setting environment variable: MSBuildEnableWorkloadResolver = 'true'
Setting environment variable: PATH = '/Users/ruimarinho/dotnet/maui/.dotnet:/Users/ruimarinho/dotnet/maui/.dotnet:/Users/ruimarinho/.sdkman/candidates/gradle/current/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:/Users/ruimarinho/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ruimarinho/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/latest/bin:~/.dotnet/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/emulator:/Users/ruimarinho/Library/Python/3.9/bin:/Users/ruimarinho/flutter/flutter:/Users/ruimarinho/.lmstudio/bin'
/Users/ruimarinho/dotnet/maui/.dotnet:/Users/ruimarinho/dotnet/maui/.dotnet:/Users/ruimarinho/dotnet/maui/.dotnet:/Users/ruimarinho/.sdkman/candidates/gradle/current/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:/Users/ruimarinho/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ruimarinho/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/cmdline-tools/latest/bin:~/.dotnet/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/bin:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/tools/emulator:/Users/ruimarinho/Library/Python/3.9/bin:/Users/ruimarinho/flutter/flutter:/Users/ruimarinho/.lmstudio/bin
```

**Comment by Baltasarq** [comment]
> Please see an attached PR which attempts to resolve the issue by adding a setting for the SDK for user projects to run under. [dotnet/vscode-dotnet-runtime#2354](https://github.com/dotnet/vscode-dotnet-runtime/pull/2354)

Great work. I think this is the correct solution.
