### ISSUE TITLE
[BUG] Unable to create project using C# Dev Kit on Apple Silicon Mac

### ISSUE THREAD

**Issue by evgenyKozlov1996** [microsoft/vscode-dotnettools#798]
### Describe the Issue

Receiving error like 
<img width="404" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/29367189/64328e7d-279f-46e2-b17a-ea930fd8b50c">

### Steps To Reproduce

1. Install C# Dev Kit 1.2.2 or 1.1.16.
2. Try to run command .NET: New project

### Expected Behavior

Project creates successfully

### Environment Information

- OS: macOS Sonoma 14.1.2
- VS Code version: Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z (4 days ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

- C# Dev Kit version: 1.1.16, 1.2.2

**Comment by evgenyKozlov1996** [comment]
Unable to run any command from C# Dev Kit for example .NET: Build produces the same error, but for build command: 
<img width="404" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/29367189/4650435b-256b-4851-80da-ad6125e4aaf3">

**Comment by evgenyKozlov1996** [comment]
After selecting existing folder with .csproj extension started working as expected

**Comment by timheuer** [comment]
Everything working now @evgenyKozlov1996 ?

**Comment by evgenyKozlov1996** [comment]
Hello, @timheuer! Yes, it's working now as expected but I think it's not a good solution to open existing directory with .csproj file in order to configure extension.

**Comment by timheuer** [comment]
> Hello, @timheuer! Yes, it's working now as expected but I think it's not a good solution to open existing directory with .csproj file in order to configure extension.

What would you prefer? I think you may be alluding to wanting an experience like CS to browse and open a file? This is a difference to how VSCode works—extensions activate on a workspace (folder) first

**Comment by evgenyKozlov1996** [comment]
If it is possible to make the same behaviour if user opens *.sln file directory?

**Comment by webreidi** [comment]
Closing issue as initial error is resolved, enhancement request to open sln files is duplicated of https://github.com/microsoft/vscode-dotnettools/issues/588.
