### ISSUE TITLE
[BUG] Cant generate project files for build and debug, intellisense autocompletion lost on Unity 3D with vs code

### ISSUE THREAD

**Issue by kepiz** [microsoft/vscode-dotnettools#801]
### Describe the Issue

Could not locate .NET Core project in 'projectName'. Assets were not generated.
There is no autocompletion no intellisense.

### Steps To Reproduce

Ctrl+P-> generate project files
It also happens when changing from laptop to Desktop PC when developing

### Expected Behavior

I should be able to find references in classes get autocompletion...

### Environment Information

Linux
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/c5018fea.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 9:49:07 AM] [Program] Language server initialized

**Comment by sailro** [comment]
Hello, just to double-check, could you share the version of your `Visual Studio Editor` package in Unity, and your `Unity extension` in VSCode ? Those are required for Unity projects as described here:

https://code.visualstudio.com/docs/other/unity

Thank you!

**Comment by jbevain** [comment]
Hi @kepiz, are you still hitting this issue? Could you confirm the version of the `Visual Studio Editor` Unity Package in Unity's Package Manager? Thanks!

**Comment by kepiz** [comment]
Hi, I have tried every last version, and intellisense seems to come and then go when it prints reloading language package . My only work around has been to downgrade C# to 1.26 so that I come back to omnisharp.

**Comment by kepiz** [comment]
Sorry, closed by mistake

**Comment by kepiz** [comment]
Sorry closed by mistake

**Comment by kepiz** [comment]
Hi @jbevain @sailro 
Still having the issue, the version of Visual studio editor I'm using on unity is 2.0.22
And for for unity extension in VScode, this is v0.9.3
As I said before had to downgrade to 1.25.9 C# extension in order to get intellisense and sync working

**Comment by bremea** [comment]
I am also having this issue on the latest version of the extension in VS Code. I'm on Windows 10.

**Comment by jbevain** [comment]
@kepiz I'm not sure I understand your workflow. The Unity extension doesn't support a `Generate Project Files` Visual Studio Code command.

Visual Studio Code needs to be selected as Unity's external editor, and the project files need to be generated by Unity (which is done automatically, but you can also trigger that manually by going into Unity's `External Tools` Preference Panel, and clicking the Regenerate Project Files button.

**Comment by kepiz** [comment]
> @kepiz I'm not sure I understand your workflow. The Unity extension doesn't support a `Generate Project Files` Visual Studio Code command.
> 
> Visual Studio Code needs to be selected as Unity's external editor, and the project files need to be generated by Unity (which is done automatically, but you can also trigger that manually by going into Unity's `External Tools` Preference Panel, and clicking the Regenerate Project Files button.

Ok I'll try that
