### ISSUE TITLE
SRockt[BUG] <title>

### ISSUE THREAD

**Issue by SRockt** [microsoft/vscode-dotnettools#805]

**Comment by timheuer** [comment]
@SRockt Can you provide any detail, this is an empty bug -- will close if no additional info is provided.  Thanks!

**Comment by timheuer** [comment]
Closing as no information to act upon

**Comment by SRockt** [comment]
![box_checked_](https://github.com/microsoft/vscode-dotnettools/assets/137132091/9cfe8deb-d15a-4085-affb-7e2832b9cc61)
