### ISSUE TITLE
[Question] C# Dev Kit License detecting as an individual license rather than an organizational license?

### ISSUE THREAD

**Issue by pratt33k** [microsoft/vscode-dotnettools#809]
### Describe the Issue

I have purchased a Visual Studio Professional Monthly Subscription with my work email and then downloaded the C# Dev Kit extension for VS Code. When I got a notification to sign in to my account for activating benefits for C# Dev Kit, i signed in with my work email but C# Dev Kit then showed that "This software is licensed to <my work email> under an individual license" instead of an organizational license? Why is this happening?

### Steps To Reproduce

1. Download and Install VS Code.
2. Purchase a Visual Studio Professional License from Azure with your work email (admin self-assigned as a subscriber).
3. Download and install the C# Dev Kit Extension pack for VS Code.
4. Click the sign-in button from the notification from the C# Dev kit asking to sign in to claim benefits.
5.  Sign in with the same work email as in step 2.
6.  Another notification pops up saying "This software is licensed to <my work email> under an individual license."

### Expected Behavior

I expect to see something other than an individual license (like an organizational license) as I have purchased the Visual Studio professional license and signed in with the same email.

### Environment Information

- OS: Windows 11
- VS Code Version 1.85
- Extension Version 1.1.16

**Comment by timheuer** [comment]
Thanks for the question @pratt33k -- in Visual Studio itself, what does it say when you log in there in the Help...About...click License Status information?

In your expectation of seeing an organizational license -- are you indicating that you have an enterprise agreement for your organization? or that you've purchased a license for yourself (VS Professional Subscription).  If the latter, then I think it's just terminology, but I will clarify once we get your answer.

**Comment by pratt33k** [comment]
Thanks @timheuer I might have to double check on Monday when I get to work, but yes, when I download VS Professional on my personal computer & sign in with my work account > Help > About ... > License Status Information,  I see a bunch of things, one of which says 
```
License: Visual Studio Professional - monthly
The product is licensed to <my work email>
Check for an updated license
Unlock with a product key
```
And yes, I'm the only developer, so I've purchased it for myself to work for the company. Let me also know if there is a better option for an individual developer in an organization that is classified as enterprise according to the Microsoft License terms for Visual Studio Community 2022.

So, individual is common to have even if you purchased a subscription? As the Microsoft License terms for Visual Studio Community 2022 starts off with terms Individual License and Organization License.

Side questions: 

1. Do i need to unlock with a product key? As I bought it through Visual Studio website > Azure. 

1.1 If I do, will it only be for my personal device and won't be able to for my work device?

**Comment by timheuer** [comment]
Thanks @pratt33k -- most of the identity team is gone for the holidays so I'm just waiting to hear back.  I think this is just a matter of labeling here. Looking at the source and where that message comes from I do have some questions to the team.  May need to take more offline with you.  If you wouldn't mind sending me a mail with the email you're logging in with that will help when they come back.  my email is timheuer at microsoft

Other questions: You do not need to unlock with a key

**Comment by pratt33k** [comment]
> Thanks @pratt33k -- most of the identity team is gone for the holidays so I'm just waiting to hear back.  I think this is just a matter of labeling here. Looking at the source and where that message comes from I do have some questions to the team.  May need to take more offline with you.  If you wouldn't mind sending me a mail with the email you're logging in with that will help when they come back.  my email is timheuer at microsoft
> 
> Other questions: You do not need to unlock with a key

No worries, I've just sent an email to timheuer at microsoft . com

**Comment by pratt33k** [comment]
@timheuer Unfortunately, the email failed to send, is it not "timheuer at microsoft . com" ? (With no spaces, no quotes and at is @)

**Comment by pratt33k** [comment]
Aah it went through the 2nd time. All good.

**Comment by Tarek-khan** [comment]
I am also facing this. Did you find the solution?

**Comment by AndreyTretyak** [comment]
> I am also facing this. Did you find the solution?

Hi @Tarek-khan, would you be open to following the steps decrbed here https://github.com/microsoft/vscode-dotnettools/issues/809#issuecomment-1884069290 to provide as with the logs that would help in investigating and resolving the issue.
