### ISSUE TITLE
Failed at "Spawn .NET server"

### ISSUE THREAD

**Issue by jpringle1** [microsoft/vscode-dotnettools#81]
Type: <b>Bug</b>

Trying to open a solution results in the output:

Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
Failed to launch reliability monitor: Error: spawn EPERM
Failed at 'Spawn .NET server' (52ms) with error: Error: spawn EPERM
Failed at 'Clear environment' (56ms) with error: Error: spawn EPERM
Failed at 'Open a solution with environment service' (56ms) with error: Error: spawn EPERM
Failed at 'Open a solution' (73ms) with error: Error: Exception while opening the solution: Error: spawn EPERM
Failed to open solution Error: Exception while opening the solution: Error: spawn EPERM

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (18.08GB free)|
|Process Argv|--crash-reporter-id 41029e98-5f01-45d3-9eee-d40e23b24740|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705

```

</details>

**Comment by taisbak** [comment]
Probably the same as issue #80

**Comment by arkalyanms** [comment]
Yes this is related to https://github.com/microsoft/vscode-dotnettools/issues/80
