### ISSUE TITLE
Cannot DEBUG on mac using MAUI VS Code

### ISSUE THREAD

**Issue by rupisaini123** [microsoft/vscode-dotnettools#810]
### Describe the Issue

I have installed the MAUI extension on Mac with M1 silicon. After opening a MAUI project, i go to target devise to choose devise from {} on bottom.
![image](https://github.com/microsoft/vscode-dotnettools/assets/47219093/e5f00dc9-cada-4bbe-9e0b-14eb26e4049c)

It only gives me option to build for net7.0-maccatalyst. Where as i should be able to run it as debug session with current Mac, there is no option such as that. I can run the same project in MAC as well as iOS emulator using Visual Studio 2022 for Mac. 

But i am only able to run on Pixel 6 Emulator.

Can someone please help if i am missing anything because of which i might be missing MAC/iOS emulator options.

### Expected Behavior

As i am on mac, should give Current Mac option in devices list

**Comment by emaf** [comment]
Assigning to @jknaudt21.

@rupisaini123 Could you share the content of the .NET MAUI output panel?

**Comment by mauroa** [comment]
Hi @rupisaini123,
We are trying to re-activate or cleanup old issues related to the VS Code MAUI extension that were left unattended or into "Need More Info" state and didn't get a response in a while.
I would like to know if you continued working with MAUI projects in VS Code and if you still have any issue related to this ticket, after installing the latest pre-release version of the extension.
We will proceed to close this ticket in case we don't get a new response in a few days.
Thanks in advanced.
