### ISSUE TITLE
[BUG] Unable to run on Android

### ISSUE THREAD

**Issue by emawby** [microsoft/vscode-dotnettools#811]
### Describe the Issue

There was no runtime pack for Microsoft.Android available for the specified RuntimeIdentifier 'osx-x64'. [/Path/To/App.csproj::TargetFramework=net7.0-android]

### Steps To Reproduce

Open iOS/Android MAUI app in vscode
Select an Android emulator as the build target
Run and Debug

The following command works:
`dotnet build -t:InstallAndroidDependencies -f:net7.0-android -p:AndroidSdkDirectory="$HOME/Library/Android/sdk" -p:AcceptAndroidSDKLicenses=True`
 
adding -t:Build or -t:Run causes the build to fail.

It works fine for iOS builds.

I am not able to reproduce this issue on a fresh Android project, but this existing project that updated from .net6/xamarin tools to .net7 is no longer working.

### Expected Behavior

Build and run for Android

### Environment Information

macOS x86_64 Sonoma 14.0
dotnet sdk 8.0.100
.NET MAUI extension v0.6.54
.NET Install tool v2.0.0
VSCode Version: 1.84.2

**Comment by emawby** [comment]
Removing `<SelfContained>true</SelfContained>` fixed the issue for my project

**Comment by emaf** [comment]
This is probably related to `SelfContained` apps requiring setting a specific `RuntimeIdentifier`. 

If you need guidance about SelfContained Android apps please file an issue on the Android SDK repo so the team can help you: https://github.com/xamarin/xamarin-android/issues.
