### ISSUE TITLE
Attaching debugger makes Unity Editor unresponsive

### ISSUE THREAD

**Issue by MateuszSadowski** [microsoft/vscode-dotnettools#815]
**Type:** `Bug`

- **Unity version:** 2022.3.4f1
- **Unity Visual Studio Editor package version:** 2.0.22

**Steps to Reproduce:**
1. Open a Unity project in the Unity Editor and its solution in VS Code.
2. Add a breakpoint.
3. Attach to the Unity Editor using the "Attach Unity Debugger" VS Code command.
4. Start debugging session in the Unity Editor.
5. Enter play mode in Unity Editor.

**Expected Result:**
- It takes a maximum of 5-10 seconds for the debugger to attach to the Unity Editor and a maximum of 5-10 seconds for the play mode to start.

**Actual Result:**
- It takes up to 1 minute for the debugger to attach and another minute to enter play mode. Sometimes less, sometimes even more. During the loading, Unity Editor is unresponsive and sometimes displays "Reloading domain" or similar progress dialogs.

**Note:**
- When using Visual Studio with the same project, both the debugger attachment and entering play mode is almost instant. This suggests that the issue might be with the extension.

Extension version: 0.9.3
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.93GB free)|
|Process Argv|C:\\Users\\wtsk\\Documents\\Repos\\NNE.XR.Core\\XRcore -g C:\\Users\\wtsk\\Documents\\Repos\\NNE.XR.Core\\XRcore\\Packages\\com.nne.xr.core\\Runtime\\Scripts\\Core\\Infrastructure.Configuration.Abstractions\\RepositoryConfig.cs:1:0 --crash-reporter-id 761d1297-8ad1-4b6f-b28a-80e583d4fdae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by MateuszSadowski** [comment]
Thank you for your response!

> In _Visual Studio_ (not code), do you have `Exception support` enabled in `Tools/Options/Tools for Unity/Debugging` ?

Yes.

Also, I sent the resulting debug log to the e-mail address.

**Comment by sailro** [comment]
Removing all breakpoints solved the issue.

Analyzing the logs, it seems that function breakpoints were used. Even if they are fully supported, they have major negative impact on debugging performance, because we have to disable event-type-filtering. So we can see a dramatic increase of the time needed to attach, given we'll have to process all types in the application domain (whereas for regular location breakpoints we can limit the scope to all types used in a specific source file).

I added a dedicated warning in the output when attaching and using function breakpoints.
