### ISSUE TITLE
[SUGGESTION] Visibility on planned things for community

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/vscode-dotnettools#817]
Hi everyone, 
I know the C# dev kit tooling is closed source, and this GitHub repo is created only to take feedback and report issues for which I can say that is working great, but I would like to put some suggestions to the maintainers of this to bring more visibility to everyone.  

1. The Base C# extension team does expose on what are all the things that they are going to work on in the given iteration (I guess it's monthly there) which we can see here (https://github.com/dotnet/vscode-csharp/issues/6650). I don't see any similar thing here for the C# dev kit, it might be internal to DevDiv Azure DevOps, but I would like to request it to make it public or do planning here on GH for more visibility to the community. 

2. Base C# extension also takes advantage of the Releases feature of GH, to share changelog to the community on what issues and features have been closed, I wish to see the same thing for the C# dev kit so everyone can know what all the bugs/features have been fixed as part of the release. 

cc @timheuer

**Comment by timheuer** [comment]
Hi @ShreyasJejurkar we do have the same thing here: December iteration plan: https://github.com/microsoft/vscode-dotnettools/issues/804 (looks like we forgot to pin the latest one).  In addition the changelog is also published on the extension page as well (which is viewable in the marketplace but also viewable inside VSCode extension manager): https://marketplace.visualstudio.com/items/ms-dotnettools.csdevkit/changelog

Hopefully this helps, sorry we didn't have the issue pinned.  We also use the milestone feature in GH so you can see what we're thinking of some early thoughts beyond the iteration plan, as we plan it.  Admittedly this is a bit more loose.

**Comment by ShreyasJejurkar** [comment]
Thanks @timheuer for the input. What about doing a release on GH side as well? Any plans?

**Comment by timheuer** [comment]
No plans to do that no. We are using the repo here for Issue tracking only
