### ISSUE TITLE
Launch/Debug a project in an external terminal

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#82]
Please add ability to launch/debug a project in external terminal instead of internal terminal.

**Comment by WardenGnaw** [comment]
You can modify which window is used by modifying the `csharp.debug.console` option in your user settings.

For more information: https://code.visualstudio.com/docs/csharp/debugging#_user-settings

**Comment by BachiMjavanadze** [comment]
> You can modify which window is used by modifying the `csharp.debug.console` option in your user settings.
> 
> For more information: https://code.visualstudio.com/docs/csharp/debugging#_user-settings

I think the feature is buggy. Does not support ctrl+F5 (`start without debugging`):

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/44a91cb3-b56a-43df-9197-81b1feb6e852)

and to prevent console closing  you need to explicitly write at the end of script `Console.ReadLine();`

In `Visual Studio IDE` settings I've just uncheckd `Automatically close the console` option and do not need write `Console.ReadLine()` any more.

**Comment by WardenGnaw** [comment]
> I think the feature is buggy. Does not support ctrl+F5 (start without debugging):

Made a bug at https://github.com/microsoft/vscode-dotnettools/issues/87

> to prevent console closing you need to explicitly write at the end of script Console.ReadLine();
In Visual Studio IDE settings I've just uncheckd Automatically close the console option and do not need write Console.ReadLine() any more.

You can use `integratedTerminal` which should keep the output in the VS Code Terminal.

**Comment by BachiMjavanadze** [comment]
> You can use `integratedTerminal` which should keep the output in the VS Code Terminal.

Ok but even with `integratedTerminal` ctrl+F5 (`start without debugging`) does not works and by default `Terminal` window is revealing but output is in `Debug Console` window.

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/8166c7aa-6c1f-47b9-9bbe-c285c7450c79)

It would be better if we have an ability to set which window should revealed in such a situation

**Comment by BachiMjavanadze** [comment]
and if I use `external Terminal` the built in terminal still reveals. it is very annoying

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/cb285346-3359-4a25-98b0-90707da85c32)

**Comment by WardenGnaw** [comment]
> ctrl+F5 (start without debugging) does not works

Yes, this is now tracked at https://github.com/microsoft/vscode-dotnettools/issues/87

> when I click F5 Terminal window is revealing but output is in Debug Console window.

Can you clarify what you are doing here? Are you clicking on the terminal pane then clicking F5 or are you changing your setting. 

The settings option to `integratedTerminal` will change which output window your applicaiton uses for debugging.
![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/e548a18d-b20d-4369-867f-4d4d7e80cac5)

**Comment by BachiMjavanadze** [comment]
@WardenGnaw maybe it will help. To fix the error I used to do this: 

in `.vscode/tasks.json`:

```
"presentation": {
  "reveal": "never"
}
```

in `.vscode/launch.json`:

```
"console": "externalTerminal",
"internalConsoleOptions": "neverOpen",
```

but now I do not want to create extra script and manually manage them.

**Comment by WardenGnaw** [comment]
Using `tasks.json` and `launch.json` is not part of the C# Dev Kit experience. Using those files indicates you want to manually manage how building and debugging works.

If you wish to let the extension handle build and debug, you will want to use the VS Code User Settings for `internalConsoleOptions` and `csharp.debug.console`.

You can find the settings button in File -> Preferences -> Settings. You can also use `Ctrl + ,`.

**Comment by BachiMjavanadze** [comment]
> and if I use `externalTerminal` the built in terminal still reveals. it is very annoying
> 
> ![image](https://user-images.githubusercontent.com/38082501/244603656-cb285346-3359-4a25-98b0-90707da85c32.png)
> 
> I think the built-in terminal should only expand if there are some errors.

@WardenGnaw @arkalyanms 
Should I create new Bug report, or you are tracking it already?

**Comment by Shidouuu** [comment]
> You can modify which window is used by modifying the `csharp.debug.console` option in your user settings.
> 
> For more information: https://code.visualstudio.com/docs/csharp/debugging#_user-settings

I'm not sure if it has to do with the particular project I am working on (a mod for Stardew Valley) but VSCode simply ignores this option when I enable it. I've tried it in both settings.json and the user settings and it does nothing. In Visual Studio the 'debug console' opens in its own window by default so it's interesting that VSCode wants to use its debug console.

In [the docs](https://code.visualstudio.com/docs/csharp/debugger-settings#_console-terminal-window) it says you can also use the `console` setting in launch.json to enable the external terminal however that only applies to the "old way". The `dotnet` type does not support that option. So that may be worth updating.

**Comment by edsheltonorg** [comment]
One observation I've made is the debug console will still opens and focuses when using the C# Dev Kit debug options.

![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/5463913c-cd7d-479a-b76a-7202a3c9eab0)

It still pops up the debug console no matter run / debug:

![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/74d04698-7699-4ef4-8252-e4d7078ff7c0)

However, the traditional `launch.json` way works just as expected:

![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/05586999-c597-48eb-ae17-c6d5c5f0f1f1)

Apologies if I missed something & thank you for this extension, its awesome!

**Comment by edsheltonorg** [comment]
Hey, just tried the new version of the C# extension and it fixed that behavior!

![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/fd87c1db-ba58-47ca-9483-7eaa5c528585)

Working as expected with this config in `.vscode/settings.json`:

```json
{
    "dotnet.defaultSolution": "ConsoleApp1.sln",
    "csharp.debug.console": "integratedTerminal",
    "debug.internalConsoleOptions": "neverOpen",
    "debug.openDebug": "neverOpen",
}
```

![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/6a046716-49ee-472c-9734-a85f4f18807e)

**Comment by edsheltonorg** [comment]
...and it looks like it broke it again `2.4.4`:
![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/cbac0a95-9e69-45d2-b65e-9470b27de5ed)

Oddly enough, `2.4.2` which "fixed it" no longer does as well.

When it was working, VSCode stated it was constantly building (despite running fine):

![image](https://github.com/microsoft/vscode-dotnettools/assets/87239055/6b8e61c1-2f10-4b2f-b499-c49b8eb03c10)

Perhaps that accidentally fixed the behavior? Or perhaps the license trying to always appear in the debug console?

Anyways, thank you guys again, I'll just be using the externalTerminal option & a traditional `launch.json` for now!

**Comment by Qtax** [comment]
Can't get the `csharp.debug.console` setting to work:
the application output is always on the "debug console" tab, no matter what setting is set.

Am I missing something? :/

![settings](https://github.com/microsoft/vscode-dotnettools/assets/1556175/117794fc-e81f-467a-ab1f-b3d3057239c5)

![start](https://github.com/microsoft/vscode-dotnettools/assets/1556175/6bf43761-235c-41fe-b0b4-3a12437a1878)

**Comment by WardenGnaw** [comment]
Closing this ticket as resolved as https://code.visualstudio.com/docs/csharp/debugging#_user-settings `csharp.debug.console` will control how the debug session will either use internal console, integrated terminal, or external terminal.

If you are experiencing issues with this still, please open a new issue with the bug template filled out.
