### ISSUE TITLE
[SUGGESTION] Project template for iOS projects without Maui

### ISSUE THREAD

**Issue by razziefox** [microsoft/vscode-dotnettools#822]
### Describe the feature you'd like

Currently it is only possible to create projects for iOS with Maui within VSCode, as there no option to create one without Maui. it is only possible in the terminal. Pretty much the suggestion is just adding project templates for iOS projects without Maui to VSCode.

![Screenshot 2023-12-20 at 12 36 27 PM](https://github.com/microsoft/vscode-dotnettools/assets/57515252/e228d4ac-d7c0-45c5-b905-0ae91e594c1f)

### Environment Information

OS - macOS Sonoma 14.2
VS Code Version - 1.85.1
Extension Version - v1.1.16

**Comment by tmeschter** [comment]
@razziefox What sort of iOS project would you like to create that doesn't involve MAUI?

**Comment by razziefox** [comment]
> @razziefox What sort of iOS project would you like to create that doesn't involve MAUI?

I'm working on porting over my game to iOS which uses FNA-XNA.

**Comment by kvenkatrajan** [comment]
Unfortunately at this time FNA-XNA is not a supported project type within C# dev kit. Please refer to the support documentation for C# dev kit : https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_what-project-types-are-currently-supported

CC: @webreidi
