### ISSUE TITLE
[BUG] Not working on m1

### ISSUE THREAD

**Issue by forestbaba** [microsoft/vscode-dotnettools#823]
### Describe the Issue

I've installed the c# dev kit on my M1 and a corresponding SDK, but i always get this error
 **Try to use X64 based C# Dev Kit extension with ARM based SDK on an apple computer. This is not a supported scenario. Both C# Dev Kit and SDK should match the CPU architecture of the computer.**

**Comment by lifengl** [comment]
you might check whether the x64 binaries were installed in the extension folder (typically, it is under ~/.vscode/extensions/*devkit*-[platformName]), and the folder name would tell whether the correct binaries were installed.

if vs code keeps installing wrong binaries for you, it is likely a bug on vs code side.

**Comment by webreidi** [comment]
@forestbaba did you get the correct binaries installed and does C# Dev Kit now work for you?
