### ISSUE TITLE
Click add project > nothing happens

### ISSUE THREAD

**Issue by TWolversonReply** [microsoft/vscode-dotnettools#838]
Type: <b>Bug</b>

Open Solution in solution explorer
Click 'add project' + sign
Select 'MSTest Test project' (or any project) from the dropdown
Nothing happens

Extension version: 1.1.16
VS Code version: Code 1.83.1 (a6606b6ca720bca780c2d3c9d4cc3966ff2eca12, 2023-10-27T12:03:04.063Z)
OS version: Windows_NT ia32 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (6.64GB free)|
|Process Argv|--crash-reporter-id c8bf12dc-3239-4bbc-8a2a-0e9d653440fc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
f6dab269:30613381
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by Michael-Eng** [comment]
I realize this was logged a while back. using version v1.5.16 (pre-release) of C# Dev Kit, I'm seeing the MS Test project get created so this appears to be fixed.

**Comment by Michael-Eng** [comment]
Closing this as this is working in latest builds of C# Dev Kit
