### ISSUE TITLE
[BUG] C# Extension (w/ or w/o DevKit) lost "Debug Test" code action

### ISSUE THREAD

**Issue by tthiery** [microsoft/vscode-dotnettools#84]
### Describe the Issue

When working on my projects I used the VS Code C# Extension. For testing I used XUnit and `dotnet test`. But once in a while, I debugged a test case using the "Debug Test" code action above the unit test.

After updating from 1.x to 2.x pre-release I miss the functionality. It seems also not to exist in DevKit.

I am aware of Dev Kit Test Explorer.

### Steps To Reproduce

VS Code with Prerelease 2.x C# Extension (not C# Dev Kit)

### Expected Behavior

The basic C# extension continuous to have the functions it had.

Test Debugging (and debugging) is not a advanced dev kit feature.

The Code Action to be present

### Environment Information

- Windows
- Latest VS Code

**Comment by WardenGnaw** [comment]
I believe what you are asking for is tracked in https://github.com/dotnet/vscode-csharp/issues/5719.

Feel free to open an ticket in https://github.com/dotnet/vscode-csharp/issues for C# Extension only issues.
