### ISSUE TITLE
Cannot disable open of Swagger UI when launching project

### ISSUE THREAD

**Issue by mikekistler** [microsoft/vscode-dotnettools#845]
Type: <b>Bug</b>

I tried to follow the instructions on this page

https://code.visualstudio.com/docs/csharp/debugger-settings#_starting-a-web-browser

to disable open of the Swagger UI when launching my project in VSCode. Specifcially, I set the `launchBrowser` to `false` in the `launchSettings.json` file (for all profiles). But running the project still opens the SwaggerUI.

I have a `launch.json` but it has no configurations (which is odd, since there are three configurations shown in the "Run and Debug" pane, but oh well).

Extension version: 1.1.16
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 6|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv|. --crash-reporter-id 419d896f-7e85-4c21-8845-5a77abdaec9d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
89544117:30613380
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by timheuer** [comment]
Can you show your launchSettings.json file here? and a picture of which profile you are using when you use Run and Debug?

**Comment by mikekistler** [comment]
I quit and restarted VSCode and can no longer recreate the problem. But here's what I had in my launchSettings.json:

![image](https://github.com/microsoft/vscode-dotnettools/assets/85643503/343ffded-f448-43fc-a8d5-3e23f9ec9e85)

Regarding the profile, I'm not sure how to answer that since I'm using the solution explorer to launch:

<img width="574" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/85643503/da500070-74d6-4ced-880b-c0c1a6610af0">

**Comment by timheuer** [comment]
Ok, thanks Mike, will close this now that it's working for you.  Odd it wasn't as the launchSettings looks correct.
