### ISSUE TITLE
[Question] List of WHEN clauses for C# Dev Kit keybinds

### ISSUE THREAD

**Issue by achobanov** [microsoft/vscode-dotnettools#848]
## Question
Is there a place where I can see WHEN clauses added by the extension? 

## Context
I'm trying to setup a keybind that will toggle OFF Solution Explorer only if It specifically is already focused. I find this necessary, because I'm using both Files Explorer and Solution Explorer. The former is better for overall navigation, because it tracks my active file, the latter is necessary for solution-context actions, such as project/directory rename.

**Comment by timheuer** [comment]
Hi @achobanov you may be also interested in upvoting: https://github.com/microsoft/vscode-dotnettools/issues/51

Depending on what specifically you are trying to do maybe I can refine the answer.  the view name for Solution Explorer view is `solutionExplorer` and that's what is used in the extension's manifest on conditional clauses (e.g., view == solutionExplorer)... eg here is some keybindings:

```
"contributes": {
		"keybindings": [
			{
				"command": "csdevkit.rename",
				"key": "f2",
				"when": "focusedView == solutionExplorer && (selectedSolutionExplorerNodeType == Folder || selectedSolutionExplorerNodeType == File || selectedSolutionExplorerNodeType == Project)"
			},
			{
				"command": "csdevkit.renameSolutionFolder",
				"key": "f2",
				"when": "focusedView == solutionExplorer && selectedSolutionExplorerNodeType == SolutionFolder"
			},
			{
				"command": "csdevkit.deleteItem",
				"key": "delete",
				"when": "focusedView == solutionExplorer && (selectedSolutionExplorerNodeType == Folder || selectedSolutionExplorerNodeType == File)"
			}
		]
```

Does that help enough?

**Comment by achobanov** [comment]
@timheuer way ahead of you on upvoting Solution tracking as a built in feature. 

`focusedView == solutionExplorer` works like a charm, I can now open it easily on demand, which is a decent workaround until we get that tracking feature. Thanks a lot!

Is there a document or a way I can see those values from VS Code, rather than asking question here?

**Comment by timheuer** [comment]
> Is there a document or a way I can see those values from VS Code, rather than asking question here?

Not really...we don't consider the extension right now 'extensible' so haven't really documented anything.  But if you spelunk the package.json from your installed location you can see things like this as far as command conditionals, etc. (keeping in mind may be subject to change)

**Comment by timheuer** [comment]
Closing this for now since provided a specific answer. If we offer extensibility, we can document this more in the future.
