### ISSUE TITLE
Wrong project template

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#857]
When I choose `Blazor Web App` template in `Visual Studio IDE` it creates 2 projects:

![image](https://github.com/rsaz/csharp-snippet-productivity/assets/38082501/6b4d4c64-5c9f-4d94-a504-3daef8fed23f)

but when I do it with `C# Dev Kit` it creates only one project:

![image](https://github.com/rsaz/csharp-snippet-productivity/assets/38082501/b15da0b5-e263-452c-a095-e534eef0b021)

**Comment by smitpatel** [comment]
In v1.8.14 you can configure parameters for project to create 2 projects. (interactive render mode parameter)
