### ISSUE TITLE
Unable to add existing shared project (.shproj) to solution from solution explorer.

### ISSUE THREAD

**Issue by GalaxiaGuy** [microsoft/vscode-dotnettools#858]
Type: <b>Bug</b>

Have an existing shared project (.shproj).

Create a new solution.

Right click on the solution in solution explorer and select "Add Existing Project..."

Find the .shproj. Notice it is greyed out.

Extension version: 1.2.7
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 10, 13|
|Memory (System)|32.00GB (0.79GB free)|
|Process Argv|--crash-reporter-id 119ac296-e6c6-445f-a734-55dbd6568098|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by Michael-Eng** [comment]
Thanks for the report. C# Dev Kit does not support adding shared projects to a solution at this time.

**Comment by Michael-Eng** [comment]
We do not have plans to add this feature at this time but we may consider it in the future.
