### ISSUE TITLE
C# DevKit doesn't add Play button to tests

### ISSUE THREAD

**Issue by Buthrakaur** [microsoft/vscode-dotnettools#859]
Type: <b>Bug</b>

C# DevKit should add Play button to run tests according to docs but it doesn't happen in my case https://code.visualstudio.com/docs/csharp/testing#_rundebug-test-cases

> C# Dev Kit will generate shortcuts (the green play button) on the left side of the class and method definition. To run the target test cases, select the green play button. You can also right-click on it to see more options.

I'm using NUnit and .NET 7 and can see all my tests listed in Testing tab in VSC. There's no problem in launching the tests from the Testing tab but I don't have an option to launch the test using the play button on test class or test method directly from the *.cs file.

Extension version: 1.2.7
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (1.34GB free)|
|Process Argv|--folder-uri file:///c%3A/Develop/SmartGuide/api --crash-reporter-id 9bc3a1a1-7c59-43aa-a64a-b8f37d0c1be8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30928863
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019acf:30933242

```

</details>

**Comment by webreidi** [comment]
@Buthrakaur Can you tell me what you see in the margin of the editor on your test files? I have a project with NUnit tests and .NET 7 and I have these X and checkmarks that allow me to rerun my tests directly from the .cs file.

![image](https://github.com/microsoft/vscode-dotnettools/assets/55603905/1010247a-e072-40d6-b76e-1fb896df6c65)

**Comment by Buthrakaur** [comment]
Hi @webreidi , I don't see anything like that in my VSC. I can run the test from the Testing tab but there's no indication the test passed displayed in the margin so it's not even possible to use it to re-run the test.
![image](https://github.com/microsoft/vscode-dotnettools/assets/126757/72f903eb-ff20-4bc6-8747-fcfbef6c4b4e)

**Comment by peterwald** [comment]
@Buthrakaur This is expected when there is no symbol information available for your test. In this case, the test explorer cannot map the test to its location in the source code. Please make sure that symbols are being generated by your build.

See: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/symbols

**Comment by Buthrakaur** [comment]
@peterwald the symbol information should be availably - the build process generates PDB files. I just completely cleaned the solution build artifacts and rebuilt it => the PDB is there but the play button is still not visible. Do I need to configure anything like `launch.json`? The project was developed in the Visual Studio before and now I try to use VSC for development - could there be anything missing because of that?
![image](https://github.com/microsoft/vscode-dotnettools/assets/126757/dd0b9883-3599-4499-a962-8e4aaad8ba43)

**Comment by Buthrakaur** [comment]
Thanks for your support @peterwald . Unfortunately I don't have neither `.runsettings` nor the `DebugType` setting in csproj file. I tried to create a completely new test project in an empty folder (`dotnet new nunit`) and I get at least the checkmark in the margin when I run the test from Testing tab but I don't have the green play button next to my test method and class and "Run test at cursor/in current file" commands don't work. There must be something wrong in my VSC configuration...
![image](https://github.com/microsoft/vscode-dotnettools/assets/126757/8398f2b7-3ff1-47d3-8332-57dd8041a41b)

**Comment by peterwald** [comment]
Just curious. What happens if you remove the hashtag symbol from the sln and csproj file names?

**Comment by peterwald** [comment]
> @peterwald I renamed everything to not contain the `#` character (filesystem directory, project name, solution name) and it really partially resolved the issue. I have the play buttons per test method but there's still no play button on the class level.

We would not expect to see a play button on the class level in the editor, only in the test explorer tree. 

It seems like at least part of the issue is related to file name processing and having unexpected characters in the path. Could be due to url encoding....
