### ISSUE TITLE
[BUG] F12 brings you always to decompiled source instead to the symbols that it should be use

### ISSUE THREAD

**Issue by paule96** [microsoft/vscode-dotnettools#861]
### Describe the Issue

> Disclaimer: I guess this bug exists before in the issue #40 that was closed half a year ago

Their are two things that `F12` (aka go to definition) can do:
- go to decompiled source
- go to symbols 

This behavior is configurable with the setting ` dotnet.navigation.navigateToDecompiledSources`. If it false I expect that it will use the symbols. Right now it uses always the decompiled source.

### Steps To Reproduce

1. Open a `csharp` project with vscode
2. Set the following settings: 
   ```json
   {
       "dotnet.navigation.navigateToDecompiledSources": false,
       "csharp.debug.justMyCode": false,
       "csharp.debug.symbolOptions.searchMicrosoftSymbolServer": true,
       "csharp.debug.symbolOptions.searchNuGetOrgSymbolServer": true
   }
   ```
3. Restart VsCode (I do it to make it sure. None of these settings requires a restart if we trust documentation)
4. Go to some `csharp` code and hit F12
5. you see the following:
<img width="1403" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/11291885/f1cd83bd-1201-4c2d-a9e2-69a64fa151ff">

That is clearly decompiled.

### Expected Behavior

It should use the symbols. Maybe it would be even better to have two different commands for the two cases.

### Environment Information

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z (1 mo ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

all dotnet settings:

```json
{
    "dotnet.completion.showCompletionItemsFromUnimportedNamespaces": true,
    "csharp.debug.justMyCode": false,
    "csharp.debug.symbolOptions.searchMicrosoftSymbolServer": true,
    "csharp.debug.symbolOptions.searchNuGetOrgSymbolServer": true,
    "csharp.experimental.debug.hotReload": true,
    "dotnet.backgroundAnalysis.analyzerDiagnosticsScope": "fullSolution",
    "dotnet.backgroundAnalysis.compilerDiagnosticsScope": "fullSolution",
    "csharp.inlayHints.enableInlayHintsForImplicitObjectCreation": true,
    "csharp.inlayHints.enableInlayHintsForImplicitVariableTypes": true,
    "csharp.inlayHints.enableInlayHintsForLambdaParameterTypes": true,
    "csharp.inlayHints.enableInlayHintsForTypes": true,
    "dotnet.inlayHints.enableInlayHintsForIndexerParameters": true,
    "dotnet.inlayHints.enableInlayHintsForLiteralParameters": true,
    "dotnet.inlayHints.enableInlayHintsForObjectCreationParameters": true,
    "dotnet.inlayHints.enableInlayHintsForOtherParameters": true,
    "dotnet.inlayHints.enableInlayHintsForParameters": true,
    "dotnet.inlayHints.suppressInlayHintsForParametersThatDifferOnlyBySuffix": true,
    "dotnet.inlayHints.suppressInlayHintsForParametersThatMatchArgumentName": true,
    "dotnet.inlayHints.suppressInlayHintsForParametersThatMatchMethodIntent": true,
    "dotnet.navigation.navigateToDecompiledSources": false
}
```

**Comment by dibarbet** [comment]
The behavior you're seeing currently is expected.  What you're seeing is not the decompiled source, but is instead just the metadata.  That is why there is no implementation of the method in your screenshot.

I think what you're asking for though is sourcelink support - where go to definition will take you to the real, non-decompiled source.  Support for that is tracked by https://github.com/dotnet/vscode-csharp/issues/6784 and is planned.
