### ISSUE TITLE
Support .NET Aspire inner-loop development in C# Dev Kit

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dotnettools#863]
### Describe the feature you'd like

Ensure that an Aspire solution (AppHost project types) can have similar inner-loop experiences within the Dev Kit:

- [x] Expose and enable templates to be created
- [x] Debug the solution (e.g., F5/debug on AppHost and launches all other apps under debugger
- [x] Automatically launch dashboard if enabled
- [ ] Easier add aspire components to projects/app host via searching NuGet from VSC

### Alternatives considered

Alternatives today are to use `dotnet run` and attach scenarios on non-Visual Studio scenarios

**Comment by tmeschter** [comment]
@timheuer @webreidi @kvenkatrajan While the last item has not been done ("Easier add aspire components to projects/app host via searching NuGet from VSC") I'm going to close this issue as the initial iteration of Aspire support for C# Dev Kit is complete.
