### ISSUE TITLE
Problems pane doesn't display the correct error when build fails

### ISSUE THREAD

**Issue by BethMassi** [microsoft/vscode-dotnettools#866]
Type: <b>Bug</b>

When trying to build and debug a MacCatalyst MAUI app, the Problems pane reported the following error:

"Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false."

This led me to try to disable trimming in the .csproj only to then report in the next build that trimming could not be disabled for MacCatalyst builds. After phoning a friend, they were able to see that the Terminal was displaying an error that indicated that I had an outdated version of XCode. 

The Problems pane should have displayed the correct error. 

Extension version: 0.7.10
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id e7947c08-ff95-44ab-ab97-4c78585bb265|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1975722">1975722</a>

**Comment by mauroa** [comment]
Assigning to @jknaudt21 to take a first look

**Comment by mauroa** [comment]
This issue has been fixed on latest .NET MAUI release version. Please ensure to also update C# and C# DevKit to latest pre-release versions as well. Thanks
