### ISSUE TITLE
[BUG] Conditional Breakpoints not working with .NET 8.0 MAUI when run on android device

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-dotnettools#869]
### Describe the Issue

Conditional breakpoints in VS Code are not behaving as expected. Breakpoints always get hit, regardless of conditions set in the VS Code IDE. This is happening on Windows Machine with `maui-android` when debugging on physical hardware.

### Steps To Reproduce

1. Debug a .NET MAUI project (VS Code + local device)
2. Set conditional breakpoints
3. Observe breaking

### Expected Behavior

Only break when condition in breakpoint is evaluated to true.

### Environment Information

Versions involved:

```
OS: Windows 11 Enterprise:      23H2
VS Code:                        1.85.2
VS Code Extension: C# Dev Kit:  v1.3.4
VS Code Extension: .NET MAUI:   v0.7.10
Dotnet version:                 8.0.101
Dotnet Workload: maui-android:  8.0.3
Android Version:                8.1.0
Android: Build Number:          86.00.10-(0089)
```
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1999745">1999745</a>

**Comment by mauroa** [comment]
This issue has been fixed in the latest pre-release of VS Code MAUI. Please note that you should have .NET 8.0.200 or higher in order to get this fix, since it's only available for the new feature that integrates the MAUI debug experience into the .NET Core Debugger Backend (vsdbg).
