### ISSUE TITLE
Dev-C++ : The program ends after clicking "run".Nothing works.

### ISSUE THREAD

**Issue by Milkshake-wsx** [microsoft/vscode-dotnettools#872]
### In the program ,there are some variables need to input.But the program ends without letting me input.
Here's the prgram:
 #include <bits/stdc++.h>
using namespace std;
int main() {
    int T;
    cin >> T;
    	while (T--) {
        int n,m,r,c,mx,ans=0;
        cin >> n >> m >>r>>c;
        mx=max(r,c);
        int a[1000000],b[1000000];
        for (int i=1;i<=n;i++) {
            cin >> a[i];
        }
        for (int i=1;i<=m;i++) {
            cin >> b[i];
        }
        for (int time=0;time<=mx;time++) {
            for(int i=1;i<=n;i++) {
                if(time==a[i]) {
                    for (int k=1;k<=m;k++) {
                        if (time==b[k])
                            ans++;
                    }
                }	
            }	
        }
        cout << ans;
    }
        return 0;
}

**Comment by timheuer** [comment]
Hi @Milkshake-wsx this does not appear to be a C# question but rather for the C++ extension, can you please open that at https://github.com/Microsoft/vscode-cpptools/issues
