### ISSUE TITLE
[BUG] Cannot start debugging on Ubuntu

### ISSUE THREAD

**Issue by berkesandras** [microsoft/vscode-dotnettools#873]
### Describe the Issue

When starting a debug instance the Debug Console says that no .NET runtime found - even if it is installed correctly.

Debug Console output:

```
You must install .NET to run this application.

App: ...
Architecture: x64
App host version: 8.0.1
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed 
```

dotnet --info output:

```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

Workarounds I tried so far:

 - Added `/usr/share/dotnet` to PATH variable
 - Set the dotnetAcquisitionExtension.existingDotnetPath values explicitly for both `ms-dotnettools.csharp` and `ms-dotnettools.csdevkit`
 - Closed VS Code, then reinstalled dotnet sdk, then reopened VS Code
 - Closed the actual folder in VS Code, then reopened
 - Deleted the .dotnet folder (in user's home folder)
 - Deleted the contents on .config/Code/User/globalStorage folder

### Steps To Reproduce

1. Right-click on the project in the Solution explorer and click Debug --> Start new instance
2. Wait for debugging to start

Debugging will not start.

### Expected Behavior

Debugging instance should start up without the described errors.

### Environment Information

 - OS: Ubuntu Linux 23.10
 - VS Code: 1.85.2
 - C# Dev Kit extension: 1.2.7

**Comment by berkesandras** [comment]
As a workaround, attaching the debugger to a running process seems to be working.

**Comment by aboimpinto** [comment]
I have the same issue.
I tried to use the development version of the add-on, and I had the same issue.

What do I do to work?
* Close the VSCode and open it again. This will work a few times until I have the same error.
* Stop and start again until the debug works

Unfortunately, this new C# addon is not in good shape compared with the initial one from Omnisharp, but I believe Microsoft is working hard to reach a reasonable level.

Keep up the good work

**Comment by WardenGnaw** [comment]
@nagilson FYI, Not sure if this would be resolved by the SDK installation side of things.

**Comment by nagilson** [comment]
It is definitely possible, but it does require manual user intervention (clicking to install the SDK), so it is more of an available workaround in a sense. That's available in prerelease right now.

**Comment by nagilson** [comment]
We believe this issue has been fixed, if not, please let us know.

**Comment by Wholteza** [comment]
Hi @nagilson i'm experiencing this  same on 2 machines running ubuntu 23.04.
I have installed the dotnet sdk v8.0.4 using the install script from MS site, symlinked the dotnet binary to /usr/local/bin which is in my path variable AND set the path in my vs code settings to that binary but still when trying to debug through the solution explorer or from a generated launch.json entry i get the same issue as above.

I don't seem to be able to event successfully attach the debugger to an already running instance.

Any idea of what could be at fault here?

```
You must install .NET to run this application.

App: /home/wholteza/repos/vem/bin/Debug/net8.0/vem
Architecture: x64
App host version: 8.0.8
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:

```
```
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/wholteza/.dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/home/wholteza/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/home/wholteza/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/home/wholteza/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by nagilson** [comment]
I'm glad you were able to resolve the issue :)

**Comment by nagilson** [comment]
Btw, you can install the SDK within vs code itself now if you ever need it again. Try using the command pallete to look for ways to do so!
