### ISSUE TITLE
The current workspace is using a new version of .NET SDK '8.0.100', which is not supported by current .NET runtime used by the extension 

### ISSUE THREAD

**Issue by chandlerdale21** [microsoft/vscode-dotnettools#884]
Type: <b>Feature Request</b>

Unable to use the c# devkit due to the following error

The current workspace is using a new version of .NET SDK '8.0.100', which is not supported by current .NET runtime used by the extension. Some functions may not work correctly. This may happen when global.json is changed, or new SDK installation after the workspace is opened. Reloading the workspace may fix the problem.

////the output logs

2024-01-25 12:10:00.334 [error] (C:\Users\chand\workspace\mssa\mslearn\2-2\testProject\testProject.csproj): SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""
2024-01-25 12:10:00.367 [error] Failed to load project 'C:\Users\chand\workspace\mssa\mslearn\2-2\testProject\testProject.csproj'. One or more errors occurred. (SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""  C:\Users\chand\workspace\mssa\mslearn\2-2\testProject\testProject.csproj)
2024-01-25 12:10:00.371 [info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load.

Extension version: 1.2.7
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by lifengl** [comment]
@chandlerdale21 : have you tried to reload the workspace to see whether this problem goes away? Based on this error message, it is likely that the project system is loaded on NET 7 runtime, which cannot work with NET 8 SDK.

**Comment by lifengl** [comment]
Hey @chandlerdale21:  I wonder another possibility is that there is no solution file in the workspace and you have turned off "Automatically Create Solution In Workspace" option. If that is the case, please turn on this option, or create a solution file manually in this workspace.

**Comment by chandlerdale21** [comment]
> Hey @chandlerdale21: I wonder another possibility is that there is no solution file in the workspace, and you have turned off "Automatically Create Solution In Workspace" option. If that is the case, please turn on this option, or create a solution file manually in this workspace. A hidden solution file doesn't support all scenarios.

Hi @lifengl , thankyou for responding! I have reloaded the workspace and even created entirely new ones, and this error message persists. I also have the option checked, and that unfortunately didn't fix it.

**Comment by lifengl** [comment]
> Hi @lifengl , thankyou for responding! I have reloaded the workspace and even created entirely new ones, and this error message persists. I also have the option checked, and that unfortunately didn't fix it.

That is unfortunate. I guess we need dig further on why it happens on your machine/project:
1, first, can we check whether we have any global.json file in any parent folder of your project "C:\Users\chand\workspace\mssa\mslearn\2-2\testProject\testProject.csproj", especially multiple global.json files in nested folders.

2, we need check more detailed log files through "open extension logs folder" command in VS code (use the session which runs into the failure, don't close the workspace).  This will bring you to the folder for extension log files, then dig into ms-dotnettools.csdevkit\ServiceHub, you may see multiple log files, and the one we want to take a look first is named like ***-Microsoft.VisualStudio.ProjectSystem.CompositionService-***-***-1.log

This file captures mostly internal logging messages, but does have some environment variables in your system. You can review it and share with us if you feel comfortable. Or check a few important pieces:

at the beginning, it should log the runtime used to load the project system, like: 
ProjectSystem server process started. PID=40628. Runtime=8.0.1

it dumps a few critical environment variables, including PATH, DOTNET_ROOT, DOTNET_ROOT_USER, PRJ_BUILD_DOTNET_HOST etc. The path might be long, more important, you can start a terminal window in your VS code session, and executes "where dotnet.exe".  The result is interesting, and we should compare with PRJ_BUILD_DOTNET_HOST, DOTNET_ROOT, DOTNET_ROOT_USER. 

Further down, there is a message how we started BuildHost.exe, like:

PID=28228 CMD=[Path to dotnet.exe] [Path to Microsoft.VisualStudio.ProjectSystem.Server.BuildHost.dll]

The path to dotnet.exe is important. 

Further down, there is a message where we resolve the SDK:
!!Resolve NET Core SDK: Successful:[Folder to the SDK with version number]

Based on the error you saw, the SDK version number is higher than the project server process is using, so it cannot be loaded. But the extension should precompute what runtime is required to load your project. However, things could be messed up, when there are multiple dotnet installation on your machine, which we may be able to tell by the path you found through the 'where' command and some other environment variables dumped out here.  Another possibility is that we have many different global.json in various folders, as I said earlier, we need check that.

Based on what we can find here, we see what we should do next.

Thanks

**Comment by RednibCoding** [comment]
I have the same issue on Windows 11 with VSCode C# DevKit extension: 
The **Microsoft.VisualStudio.ProjectSystem.CompositionService--***-1.log** sais the following:

```
...
SDK Resolver is started.
...
DOTNET_ROOT=c:\Users\user\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.15~x64
DOTNET_ROOT_USER=EMPTY
...
Error : 14672 :The resolved SDK (8.0.101) is incompatible with the version of runtime (7.0.15) hosting the project system.
...
!!Resolve NET Core SDK: Successful:C:\Program Files\dotnet\sdk\8.0.101
...
SDK folder is resolved to 'C:\Program Files\dotnet\sdk\8.0.101' based on path 'C:\Users\user\Documents\DEV\TMP\ConsoleApp1.
...
 SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
```

I created a .NET 8 project and it looks like, when i open the project in VSCode, it starts the .NET 7 runtime for the language server or something.
I can do `dotnet build` or `dotnet run` and it builds or runs just fine.
When i open the project in Visual Studio 2022 it also works just fine. 

I did not perform any unusual actions; I just installed the SDKs, runtimes, and everything else through the Visual Studio Installer, along with Visual Studio 2022 and Visual Studio Build Tools 2019. Despite this, the settings appear to be incorrect (see the log snipped above).

![image](https://github.com/microsoft/vscode-dotnettools/assets/28296119/e0d6f565-b00a-46b2-a55a-64d64cfb54ed)
![image](https://github.com/microsoft/vscode-dotnettools/assets/28296119/1361ebc2-3aaa-49da-bbc7-3d375ce0e256)

**Comment by aman402** [comment]
Hi, I have the same issue, did you manage to solve the issue and if yes how?

**Comment by aman402** [comment]
> Hi, I have the same issue in visual studio code, did you manage to solve the issue and if yes how? ![QCKiQ](https://private-user-images.githubusercontent.com/76691136/304634269-afca0428-cc5d-4971-ab70-db3e985e58e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTE3NDEsIm5iZiI6MTcwNzg5MTQ0MSwicGF0aCI6Ii83NjY5MTEzNi8zMDQ2MzQyNjktYWZjYTA0MjgtY2M1ZC00OTcxLWFiNzAtZGIzZTk4NWU1OGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA2MTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NTUyZTdjOWFmZDRhMTBkOWI2YWVmZjkyNDFjMDhhMTcxNTZlYjJkNzk3YTg1ZTExMDE0NGMxMTc3NTA0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3U0n-SfUXsVWjlcoNxgkR0j-48UjRQERs5n8zXsfwHg)

The only workaround I have found to fix this issue is to simple uninstall c# dev kit extension, hit reload and then install it again, now you will see a popup saying "restart language server", click that and c# intellisense starts working again

**Comment by RednibCoding** [comment]
Yes, but i have to do this every time i start vscode.

**Comment by lifengl** [comment]
if you saw this pop-up every time after loading your workspace, it is unexpected. (it is expected, when you switch branches after opening the workspace, and the repo has its own global.json, and between the two branches, it wants to use different versions of SDK, one for NET 8, one for NET 7).  In that case, reloading workspace is necessary.

The log from @RednibCoding clearly indicates that the project system is loaded with NET 7 runtime. It needs to switch to use NET 8 when NET 8 SDK is being used. When the workspace is using a NET 7 or older SDK, the project system would use NET 7 runtime as the default choice.  (It prefers NET 7, as assemblies were pre-compiled (ready to run) with NET 7 runtime, so the loading speed with NET 8 would be slower. )

To make the choice, the extension runs some detection logic before starting its processes, so maybe we ran into a problem there. It didn't appear to impact most other people who works with NET 8 SDKs, so we need more information on what might go wrong.

One possibility is that there are multiple global.json files, especially when they are nested.  Can we do a few checks first?
1, start a command line shell (in the same way you start the vscode session -- some people starts vscode under special command line shell with customized environment variables.  That is more critical for people who installed SDKs in multiple locations).  
2,Go to the root folder of your workspace (this is critical, because the dotnet SDK behavior is different in different folder)
3, run command.  (if you are using multiple root workspace, do it on every root folders of the workspace, not the folder containing the workspace file)
dotnet --info

4, now go to the folder containing the solution file you opened,
run command
dotnet --info

It would be great if you can share them with us.  (If they are the same, no need to share both).

While this issue could be gone soon when the extension is updated to run with NET 8 runtime, but it could come back during the NET 9 SDK transition a year later.

**Comment by lifengl** [comment]
I realize one possibility,

if you turned on this option

<img width="623" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/11638466/2cf2ed99-fcf9-4845-ba99-c1c9bf4e15d7">

Please turn it back on or create a solution in the workspace running into this problem, to see whether the problem goes away.

Unfortunately, as the option said, it didn't work in all cases, especially when a global.json file is being used.

Also, if your solution file is in a child folder inside the workspace, keep the global.json file in the workspace root. Here is the problem:  dotnet resolves global.json file based on the current working directory. Generally, the workspace root folder is being used.  However, some msbuild tasks would resolve global.json based on the folder containing the solution file. When they happen to pick different global.json files, things would be broken.

**Comment by RednibCoding** [comment]
There were no `global.json` files at all in the project (i created a fresh console project).
I did not change any settings regarding dotnet in vscode and the option you mentioned above was set all the time.

Unfortunately i tried to reproduce the issue, but i am not able to. I deleted the error causing project 3 days ago (since it was just a freshly created console project created via `dotnet new console`).

Now when i create a new console project, everything works as expected (again, without any global.json files) just the default files that get generated when using the `dotnet new console` command:


![image](https://github.com/microsoft/vscode-dotnettools/assets/28296119/6cdb00eb-b4d5-4c8f-a885-22c5742c80a4)

**Comment by lifengl** [comment]
I guess one possibility is that the workspace is opened, and somehow triggers the extension to be loaded, before NET 8 SDK is installed. Then the solution is opened after the installation.

**Comment by lifengl** [comment]
@aman402 : that pops-up means you need reload the workspace (or use vscode reload window command). There is no reason to reinstall the extension. did you find the problem didn't go away after a simple reload?

> Hi, I have the same issue in visual studio code, did you manage to solve the issue and if yes how? !

**Comment by aman402** [comment]
> @aman402 : that pops-up means you need reload the workspace (or use vscode reload window command). There is no reason to reinstall the extension. did you find the problem didn't go away after a simple reload?
> 
> > Hi, I have the same issue in visual studio code, did you manage to solve the issue and if yes how? !

Reloading the language server does solve the problem, but when I restart vscode, the issue reappears and the language server needs to be reloaded again, but sometimes the "reload language server" popup does not come up and the extension has be reinstalled for the popup to appear again. I uninstalled the C# dev kit extension and everything works just fine.

**Comment by lifengl** [comment]
I believe this issue should be gone since the extension is updated to NET 8 runtime. Please make sure update to the latest extension release. If you still run into this problem, please let us know. In the case other issues are brought up in this long thread and if you still run into them (but not the original problem), please report them as separated issues.

**Comment by lifengl** [comment]
I haven't heard anything after the extension was updated to NET 8 runtime, and consider this issue fixed.
