### ISSUE TITLE
No suggestion to add member field to the constructor.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode-dotnettools#890]
### Describe the Issue

In the following code example, a readonly member variable is not be initialized.

In Visual Studio, the suggestion is provided "Initialize 'someString' from the constructor".

In Visual Studio Code with the C# dev kit, not suggestions are given to fix this issue.

### Steps To Reproduce

```
public class MyClass {
    private readonly string someString;

    public MyClass()
    {
        
    }
}
```

### Expected Behavior

A suggestion should display as follows "Initialize 'someString' from the constructor".

### Environment Information

Version: 1.85.2 (system setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by timheuer** [comment]
@safield can you show a screenshot of what you are seeing in VS for that suggestion? Is this in a lightbulb?

**Comment by safield** [comment]
Closing this issue, as this discrepancy only existed because I have Resharper installed on Visual Studio proper.

Sidenote: It will be hard for VSCode to replace Visual Studio for C# for me, since Resharper is so valuable.

**Comment by timheuer** [comment]
Thanks for confirming @safield -- with regard to the analyzers/helpers for C#, it's an area we continually invest in for Roslyn release over release. It might be worthwhile to take a look at what exists for VS over the past releases without Resharper enabled to see if it is meeting your needs.  That said, we also hear a LOT about muscle memory with Resharper and still some gaps in analyzers that it provides.  If you see some missing (like this one) feel free to log suggestions here: https://github.com/dotnet/roslyn-analyzers
