### ISSUE TITLE
Unable to accept Android licences / 'compiled by a more recent version of the Java Runtime'

### ISSUE THREAD

**Issue by BillFulton** [microsoft/vscode-dotnettools#892]
Type: <b>Bug</b>

I am unable to accept Android SDK licences, despite trying all suggestions.

On startup I get ‘Android SDK: Unaccepted licences’ and on clicking ‘Accept licenses…’ I get the following error message:

```
Picked up JAVA_TOOL_OPTIONS: -Dcom.android.sdklib.toolsdir="/Users/bill/Library/Android/sdk/cmdline-tools/latest"
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
        java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

 *  The terminal process "/bin/zsh '-l', '-c', '/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/bin/java com.android.sdklib.tool.sdkmanager.SdkManagerCli --licenses --verbose'" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Earlier, I had used Android Studio to ensure Android API 34 and  Android SDK Command line Tools (latest) were installed. I accepted the licence in Android Studio (but then noticed at there was no licences folder in /Users/bill/Library/Android/sdk/cmdline-tools/11.0/bin/). Android Studio shows the Android SDK location is indeed at /Users/bill/Library/Android/sdk.

I saw the following status:

```
Java SDK path to be used: /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home
 
ANDROID_HOME value found: /Users/bill/Library/Android/sdk
Android SDK path to be used: /Users/bill/Library/Android/sdk
 
Android components:
    - Java SDK (version: '11.0.22'): installed.
 
    Android SDK recommended required components:
    - platforms/android-34 (version: '2'): installed.
    - build-tools/34.0.0 (version: '34.0.0'): installed.
    - platform-tools (version: '34.0.5'): installed.
    - cmdline-tools/11.0 (version: '11.0'): installed.
 
    Android SDK recommended optional components:
    - emulator (version: '31.2.7'): installed.
    x system-images/android-34/google_apis/arm64-v8a: not installed.

ACTION REQUIRED:
    - To enable debugging, the Android SDK licenses need to be accepted. You can accept them from the command palette by choosing '.NET MAUI: Configure Android', selecting 'Review Android licenses', and following the instructions.
```

The JDK is indeed in /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home.

java -version and java -version both show 11.0.22.

Navigating to /Users/bill/Library/Android/sdk/cmdline-tools/11.0/bin and executing 
sdkmanager —licenses —verbose gives the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 5 more
```

FWIW, I get a similar error when executing sdkmanager "system-images;android-34;google_apis;arm64-v8a" :

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 5 more
```

Running on MacBook M2 Pro, Sonoma 14.1.2 in a Parallels VM.

------------------------------

Extension version: 0.7.10
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:11.430Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (3.62GB free)|
|Process Argv|--crash-reporter-id bfd17b27-cf2b-4648-abe6-187c8ead1fbe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929

```

</details>

**Comment by bmclane** [comment]
I used Homebrew to fix this issue:
brew install --cask microsoft-openjdk

**Comment by fossbrandon** [comment]
I'm experiencing similar issues in Windows. I first setup a .NET MAUI project/emulator in Visual Studio which works just fine, but moving to VS Code I'm unable to do anything because I can't accept the Android SDK licenses. Here is my .NET MAUI output when trying to accept the licenses using the popup:

```text
An error occurred trying to accept Android SDK licenses.
Insufficient privileges: Please try accepting licenses again by opening a Terminal as administrator, navigating to directory 'C:\Program Files (x86)\Android\android-sdk\cmdline-tools\11.0\bin' and then running: 'sdkmanager --licenses --verbose'. After that, please verify if the android-sdk-license file exist into the licenses directory on 'C:\Program Files (x86)\Android\android-sdk'. If this keeps failing, please try deleting the licenses folder and accepting the licenses again.
 
JAVA_HOME value found: C:\Program Files\Microsoft\jdk-11.0.22.7-hotspot\
Java SDK path to be used: C:\Program Files\Microsoft\jdk-11.0.22.7-hotspot
 
Android SDK path to be used: C:\Program Files (x86)\Android\android-sdk
 
Android components:
	- Java SDK (version: '11.0.22'): installed.
 
	Android SDK recommended required components:
	- platforms/android-34 (version: '2'): installed.
	- build-tools/34.0.0 (version: '34.0.0'): installed.
	- platform-tools (version: '34.0.5'): installed.
	- cmdline-tools/11.0 (version: '11.0'): installed.
 
	Android SDK recommended optional components:
	- emulator (version: '32.1.15'): installed.
	- system-images/android-34/google_apis/x86_64 (version: '8'): installed.

ACTION REQUIRED:
	- To enable debugging, the Android SDK licenses need to be accepted. You can accept them from the command palette by choosing '.NET MAUI: Configure Android', selecting 'Review Android licenses', and following the instructions.
```

And here is my command line output when trying to accept the licenses manually:

```text
C:\Program Files (x86)\Android\android-sdk\cmdline-tools\11.0\bin>sdkmanager --licenses --verbose
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
        java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by umcas** [comment]
I have solved this issue by downloading Microsoft JDK 17 rather than JDK 11 at [https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-17](https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-17 )
After changing env variables and reopening the project with vscode, I have been asked to accept android licenses, and it worked.

**Comment by mauroa** [comment]
As mentioned by @umcas, the JDK 17 should be installed in order to accept the licenses correctly, in case you are experiencing the errors mentioned above.
@BillFulton and @fossbrandon could you please try it and let us know if that worked? Thanks

**Comment by jonathanpeppers** [comment]
Should we update this doc to recommend JDK 17 now?

* https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code#android

**Comment by jamesmontemagno** [comment]
https://github.com/dotnet/docs-maui/pull/2166

**Comment by fossbrandon** [comment]
> As mentioned by @umcas, the JDK 17 should be installed in order to accept the licenses correctly, in case you are experiencing the errors mentioned above. @BillFulton and @fossbrandon could you please try it and let us know if that worked? Thanks

@mauroa I went ahead and installed version 17 of the JDK via winget and after restarting VS Code I was able to accept the license. Thanks for your help.

**Comment by mauroa** [comment]
Closing this since the docs are updated and also the user has been unblocked by updating the JDK.
Thanks for your feedback and help.
