### ISSUE TITLE
.NET 8 iOS Project Always Launches on iPad 10th Gen Simulator Instead of Selected Device in Visual Studio Code

### ISSUE THREAD

**Issue by himanshudwd765** [microsoft/vscode-dotnettools#893]
### Describe the Issue

I am currently working on migrating a Xamarin.iOS native project to .NET 8 for iOS. As part of this migration, I created a blank native iOS project using the command `dotnet new ios` in the Visual Studio Code terminal. After setting up the project and attempting to debug it, I encountered an issue with the simulator selection.

**VSCode, Xcode simulator screenshot:**

<img width="1501" alt="Screenshot 2024-02-01 at 4 43 04 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/16178794/5a132a05-bce0-4258-86f0-757ea49a13b4">

### Steps To Reproduce

Create a new .NET 8 iOS project in Visual Studio Code using `dotnet new ios`
Open the project in Visual Studio Code.
Select an iOS simulator for debugging (e.g., iPhone 15 Pro Max).
Start the debugging process.

### Expected Behavior

**Expected behaviour:** The application should launch in the selected iOS simulator (iPhone 15 Pro Max).

**Actual behaviour:** Despite selecting the iPhone 15 Pro Max simulator, the application consistently launches on an iPad 10 simulator. This iPad simulator is at the top of the simulator list in Visual Studio Code as well as in Xcode simulator list, and the issue occurs every time regardless of the selected simulator.

### Environment Information

Development Framework: C# Developement Kit for .NET iOS
IDE: Visual Studio Code version: 1.85.2(Universal)
Operating System: Mac OS Sonoma version 14.1.1
Xcode: version 15.0.1
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2012515">2012515</a>

**Comment by JaneySprings** [comment]
Hi! It seems to me that you are using two extensions (`.NET Meteor` and `MAUI`) together. If you want to use `MAUI` extension, check the readme for the device select guide: https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=visual-studio-code&pivots=devices-android#choose-your-target-device

If you want to use `.NET Meteor` extension, create a different configuration in the `launch.json` file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Meteor Debugger",
            "type": "dotnet-meteor.debugger",
            "request": "launch",
            "preLaunchTask": "dotnet-meteor: Build"
        }
    ]
}
```

**Comment by himanshudwd765** [comment]
> Hi @himanshudwd765. Could you please confirm if your scenario works by using the .NET MAUI extension and selecting the debug target from the language status item ('{}' icon) at the bottom right of VS Code? As mentioned above, you can't use both extensions at the same time so please ensure the .NET MAUI path works correctly and let us know. Thanks

Indeed, I uninstalled the other extension, .NET Meteor Debugger, and reverted to the default option. However, the issue persists :(
