### ISSUE TITLE
Unable to Debug .NET MAUI in VS CODE for Mac

### ISSUE THREAD

**Issue by FlexFitByNat** [microsoft/vscode-dotnettools#896]
Type: <b>Bug</b>

When trying to Debug, I get an error when the launch.json file is being created. "launch.json file creation failed: Please open a .NET MAUI app project from the Solution Explorer to debug using the .NET MAUI configuration." Moreover, the File Explorer is giving me the following error when I try to expand: "One or more errors occurred. (An error occurred trying to start process '/usr/local/bin/dotnet with working directory ''. No such file ot directory) ".

Extension version: 0.7.10
VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 6d97e4a6-e46f-4d57-8734-27ca6a366866|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30951795
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928
bg6jg535:30956215

```

</details>

**Comment by mauroa** [comment]
Hi @FlexFitByNat. Are you selecting the .NET MAUI debug option when doing F5? Also, are you using any custom launch configuration or launch.json file? Thanks

**Comment by FlexFitByNat** [comment]
> Hi @FlexFitByNat. Are you selecting the .NET MAUI debug option when doing F5? Also, are you using any custom launch configuration or launch.json file? Thanks

Yes, I was. However, I was able to resolved the issue by restating the machine, for some reason it was stuck and there was a version update done prior to it. Thank you very much for replying.

**Comment by mauroa** [comment]
Thanks for your confirmation @FlexFitByNat. I'll proceed to close the issue then, let us know if you experience any other issue in the future.
