### ISSUE TITLE
Don't know how to launch profile 'IIS Express'; the commandName 'IISExpress' is not supported.

### ISSUE THREAD

**Issue by hoangitk** [microsoft/vscode-dotnettools#90]
Type: <b>Feature Request</b>

Issue:
 Project > Debug > Start new Instance
 ==> Don't know how to launch profile 'IIS Express'; the commandName 'IISExpress' is not supported.

Root cause:
 - launchsettings.json: there are many profiles, and first profile is IISExpress, it does not support.

Suggestions:
- Allow to pick a profile to Start like Visual Studio

Extension version: 0.1.83
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by thrandale** [comment]
Is there plans to support IIS Express in the future?

**Comment by tmeschter** [comment]
@thrandale We're going to track IIS Express support in #248.

Closing this bug as the filtering issue was fixed in version 0.3.2.
