### ISSUE TITLE
February Iteration Plan

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#900]
### Describe the Issue

Below is the list of items being worked on during February 2024 sprint. Not all items listed below will finish and release in February.

- https://github.com/microsoft/vscode-dotnettools/issues/138
- https://github.com/microsoft/vscode-dotnettools/issues/49
- https://github.com/microsoft/vscode-dotnettools/issues/650
- https://github.com/microsoft/vscode-dotnettools/issues/793
- https://github.com/microsoft/vscode-dotnettools/issues/788
- https://github.com/microsoft/vscode-dotnettools/issues/761
- https://github.com/microsoft/vscode-dotnettools/issues/725
- https://github.com/microsoft/vscode-dotnettools/issues/599
- https://github.com/microsoft/vscode-dotnettools/issues/305
- https://github.com/microsoft/vscode-dotnettools/issues/650
- https://github.com/microsoft/vscode-dotnettools/issues/72
- https://github.com/microsoft/vscode-dotnettools/issues/149
- https://github.com/microsoft/vscode-dotnettools/issues/159
- https://github.com/microsoft/vscode-dotnettools/issues/546
- https://github.com/microsoft/vscode-dotnettools/issues/716
- https://github.com/microsoft/vscode-dotnettools/issues/757

See also, [C# extension February 2024 Iteration Plan](https://github.com/dotnet/vscode-csharp/milestone/41)

**Comment by ShreyasJejurkar** [comment]
Where I can find the March iteration plan? I guess it looks like it will be the same as this, as none of this has been fixed/closed!? 

Not sure then what the value generated out of this planning. :(

**Comment by webreidi** [comment]
@ShreyasJejurkar The March iteration plan is currently being looked at and will be published soon. Our C# Dev Kit release is happening a week later than usual this month and so you won't yet see any issues we've been working on fixed/closed until we do our monthly release.
