### ISSUE TITLE
Intellisense works for auto generated solution, but not when selecting existing one

### ISSUE THREAD

**Issue by DigitalFlow** [microsoft/vscode-dotnettools#906]
### Describe the Issue

We have a solution containing around 100 .NET Core Projects at root level of our repository.
Inside each single project, we have a .vscode/settings.json that points towards it, like this:

```JSON
{
    "dotnet.server.trace": "Trace",
    "dotnet.defaultSolution": "/workspaces/CRM/CRM.SDK.sln"
}
```

When entering a project, IntelliSense does not work most of the time, we don't get the correct functions as suggestions for our classes, only generic stuff:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4287938/873ea91b-54d0-4168-a1dd-9fce02226900)

The C# log output during that time is as follows:
[IntelliSense_Broken.txt](https://github.com/microsoft/vscode-dotnettools/files/14218175/IntelliSense_Broken.txt)

Now when we remove the dotnet.defaultSolution property from settings.json, a local .sln file is generated automatically in the project's folder and IntelliSense starts to work as wanted:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4287938/29f8d35f-ab13-463b-b708-9bd5c3dc940c)

The C# output looks differently as well:
[IntelliSense_Working.txt](https://github.com/microsoft/vscode-dotnettools/files/14218174/IntelliSense_Working.txt)

In the setting where IntelliSense worked, the log contained:
`Using model CsharpDL_$base$_2.0.0. 0 models loaded: `

In the setting where it did not work, the CsharpDL model line is missing. Instead, a little further above we can see:
`Requesting pipe to "vs-intellicode-base-models (0.1)"`

This seems an incorrect model is loaded when it does not work, how can this be fixed?
When opening the project root containg the sln file in VS Code, IntelliSense does not work as in the first case.

Kind regards,
Florian

### Steps To Reproduce

- In a DevContainer that uses dotnet/sdk:7.0-jammy
- Create a new project folder with a .sln file at its root using "dotnet new sln --name MySolution"
- Create two (or more?) subfolders, each having a project inside using "dotnet new console"
- In each folder, add a settings.json that points to the solution in the parent folder, like this: `{ "dotnet.server.trace": "Trace", "dotnet.defaultSolution": "/workspaces/CRM/CRM.SDK.sln" }`
- Open a project in VS Code using "Open Folder".
- IntelliSense should now break
- Remove dotnet.defaultSolution from settings.json
- Reload Window in VS Code
- A new solution file inside the project's directory will be created
- Suddenly IntelliSense starts working

### Expected Behavior

IntelliSense should be functional also when importing defaultSolution from parent folder.

### Environment Information

- DevContainer based on dotnet/sdk:7.0-jammy (Ubuntu Linux)
- Project structure:
- dotnet --info
.NET SDK:
 Version:   7.0.405
 Commit:    b563db86f8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.405/

Host:
  Version:      7.0.15
  Architecture: x64
  Commit:       8f4568cdaa

.NET SDKs installed:
  7.0.405 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by lifengl** [comment]
Make sure all of your projects are added to the solution. Any project which is not referenced by the solution would not get any intellisense experience.

**Comment by lifengl** [comment]
oh, I think you provide an invalid path to your solution file.  It should be a relative path from the root of the workspace to the location of the solution. You use an absolute path there. Although I cannot see your folder structure, I doubt you want an absolute path there.

**Comment by Michael-Eng** [comment]
Given no response and the fact that this is working for us, I'm closing this bug
