### ISSUE TITLE
[BUG] does not open solution offline

### ISSUE THREAD

**Issue by vhusnullin** [microsoft/vscode-dotnettools#907]
### Describe the Issue

ersion 1.3.10
When opening a solution,
in the bottom right-hand corner error:  Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.
It happens offline or with slow internet.
Can it not go online for opening a solution ?  Like Visual Studio.

### Steps To Reproduce

Open vscode
from code menu - open folder with sln file in it
wait for solution explorer to appear
appears with nothing in it
in the bottom right-hand corner error:  Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed

### Expected Behavior

Showing solution explorer with all projects in it without going to any services online.

### Environment Information

MXLinux 23.01, extension version 1.3.10
.net 6

**Comment by kvenkatrajan** [comment]
If you are offline, you probably need to install .NET 7 runtime prior to opening up your solution offline. 

CC: @webreidi

**Comment by vhusnullin** [comment]
I installed dotnet 8.0 sdk on my MX Linux 23.01. I open a solution with all projects having "<TargetFramework>net8.0</TargetFramework>" in csproj. I can build it.
But if I open the same solution offline - I wait wait wait, but no Solution Explorer ever appears in the left pane.

**Comment by sweetgun** [comment]
同样的问题，运行环境win11。
期待解决。

**Comment by lifengl** [comment]
It requires NET 7 runtime, installing NET 8 SDK would not help, not until the extension moves to NET 8 runtime (soon). 

The reason behind it is that the extension was built to ready to run binaries (basically machine bound code). Ready to run is not compatible between major versions of the NET core runtime.  (It might run if it were forced to be loaded with NET 8 runtime, but would be much slower)

**Comment by lifengl** [comment]
The recent pre-release version will use NET 8 runtime. Can you give a try to see whether it resolves your problem?

**Comment by vhforte** [comment]
I installed .Net 7 and looks like it solved my problem

**Comment by lifengl** [comment]
I believe the new pre-release build is not targeting NET 8 SDK, and when it is finally released, it would not require NET 7 SDK anymore.
