### ISSUE TITLE
[BUG] MAUI uses the internalConsole even if the user's config is set to a different setting

### ISSUE THREAD

**Issue by IsraelSoto-Improving** [microsoft/vscode-dotnettools#908]
Type: <b>Bug</b>

1. Set the following launch.json configuration for MAUI:

        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }

2. Seet the following VSCode setting:

       "csharp.debug.console": "integratedTerminal"

3. Open a MAUI project with VSCode
4. Hit F5

The MAUI extension keeps using the internalConsole option even when I have a different option in my settings

Extension version: 0.7.10
VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 9, 11|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 7b2187a5-07e0-42f1-bc62-cca1bf4148b4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
dsvsc019b:30953937
3ef8e399:30949928
bg6jg535:30958357
ccp2r6:30958158

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1999764">1999764</a>

**Comment by IsraelSoto-Improving** [comment]
Any update on this one?

**Comment by mauroa** [comment]
This behavior is by design since the C# setting only applies to console projects. We can't forward the debug console content to anywhere else since the MAUI apps runs on emulator/simulator or devices and we don't have an external or integrated console for them to redirect the output.
