### ISSUE TITLE
[BUG] Test output is not rendering properly in the 'Test Results View'

### ISSUE THREAD

**Issue by asilverman** [microsoft/vscode-dotnettools#915]
## Overview

See below image on the test results view, its not really readable

![image](https://github.com/microsoft/vscode-dotnettools/assets/9611108/f3a41cab-eb3e-478a-9146-5f0fd77e536a)

### Steps To Reproduce

1. Clone azure/bicep
2. Run any test and inspect the output in the 'Test Results View'

### Expected Behavior

Readable output

### Environment Information

- OS: MacOs
- `ms-dotnettools.csdevkit` Version:  v1.4.2 (pre-release)
- VSCode Version: 
```
Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:57.920Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0
```

**Comment by ocallesp** [comment]
@ocallesp  need to reproduce

**Comment by ocallesp** [comment]
I found System.Console.WriteLine() is not respecting new line.

**Comment by ocallesp** [comment]
Moving this issue to VSCode https://github.com/microsoft/vscode/issues/224211

**Comment by asilverman** [comment]
@ocallesp please reopen since vscode is saying its the dotnet tools extension, see below:
![image](https://github.com/user-attachments/assets/44da4fb9-0062-408e-92aa-dfbb87b6c030)

**Comment by AbhitejJohn** [comment]
Re-opening based on additional details Connor shared offline:
"If the console output from their program is using LF, they should normalize it to CRLF for display in the terminal. This is a common stumbling block, so we mentioned this in the method docs for run.appendOutput as well as in our testing API guide [https://code.visualstudio.com/api/extension-guides/testing#test-output](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Fapi%2Fextension-guides%2Ftesting%23test-output&data=05%7C02%7Caajohn%40microsoft.com%7Cc4e13b62d2664e436e5908dcb33515c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638582287850449028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=8YpmgffIKJDUykUKqDirOuQQ6ai3HmEhcV7dj2lp0lc%3D&reserved=0)"

**Comment by ocallesp** [comment]
Fixed. It will be released in next extension release.

**Comment by ocallesp** [comment]
Fix inserted into C# Dev KIt today. 

It should be available in the next release.

**Comment by asilverman** [comment]
Thank you
