### ISSUE TITLE
[BUG] Can't Open unity project

### ISSUE THREAD

**Issue by RedSray** [microsoft/vscode-dotnettools#916]
### Describe the Issue

VS Code is stuck on processing workspace information in the background. The unity project have multiple csproj and it seems that they don't get loaded as the c# output only log 1 project being loaded. 

> Using dotnet configured on PATH
>Dotnet path: C:\Program Files\dotnet\dotnet.exe
>Activating C# + C# Dev Kit + C# IntelliCode...
>waiting for named pipe information from server...
>[stdout] {"pipeName":"\\\\.\\pipe\\849a4a0c"}
>received named pipe information from server
>attempting to connect client to server...
>client has connected to server
>[Info  - 8:09:34 AM] [Program] Language server initialized
>[Info  - 8:09:40 AM] [WorkspaceProjectFactoryService] Project D:\Projects\xxxx\StreamingRuntime.csproj loaded by C# Dev Kit

### Steps To Reproduce

1. In Unity right click in the project panel
2. Click on open C# project
3. See visual studio code loading indefinitely the solution

### Expected Behavior

The solution is fully loaded

### Environment Information

VS Code unity package : 1.2.5
Visual studio unity package: 2.0.22

C# v2.15.30
C# Dev Kit  v1.3.10
.NET Install Tool  v2.0.1
IntelliCode for C# Dev Kit v0.1.26
Unity v0.9.4
VSCode Unity Debugger  v3.0.13

**Comment by jbevain** [comment]
Can you confirm that VS Code is selected as the External Editor in Unity's preferences?
Can you delete all `csproj` and `sln` files from your project folder and in Unity's External Editor preferences panel click “Regenerate Project Files”? Thanks!

**Comment by RedSray** [comment]
Yes VS Code is selected as the external editor. 
I tried this manipulation multiple times but it did not changed anything.
Looking at the c# logs. VS Code stop loading projects at some point. Sometime it loads 2 project an stops, some times it load 15 before stopping. There something like 67 csproj.

**Comment by RedSray** [comment]
There was something in my workspace (I use perforce) that was preventing the loading of the csproj. I don't know what it was but  deleting the project and getting a fresh one solved my issue.
