### ISSUE TITLE
[BUG] Error while loading extension

### ISSUE THREAD

**Issue by Viitaminium** [microsoft/vscode-dotnettools#92]
### Describe the Issue

After installing the extension, every time I open any solution it displays a message:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-c:\Users\Mateusz does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I have all the necessary SDKs installed, everything works from the terminal. The problem only occurs when the C# Dev Kit extension is loaded.

In Solution Explorer, after expanding the project, it displays the message: A compatible .NET SDK was not found.

### Steps To Reproduce

1. Install C# Dev Kit.
2. Open or create solution.
3. Wait for the extension to load.

### Environment Information

Windows 11 Pro  22H2
Operating system compilation 22621.1778
Windows Feature Experience Pack 1000.22642.1000.0

C# Dev Kit v0.1.83
VS Code v1.79 (user setup)

**Comment by arkalyanms** [comment]
This looks to be a dup of https://github.com/microsoft/vscode-dotnettools/issues/24#issuecomment-1584859202. The underlying issue seems to be a space in the user profile. 

@Viitaminium would you confirm if your user profile has a space or special characters in it?

**Comment by Vitaminium** [comment]
@arkalyanms yes, my user profile has space. Unfortunately I do not have permission to create new profiles to confirm if a one-word username will solve the problem

**Comment by arkalyanms** [comment]
> @arkalyanms yes, my user profile has space. Unfortunately I do not have permission to create new profiles to confirm if a one-word username will solve the problem

Not a problem, this is still a scenario we want to fix. Thanks for confirming! 

We ll track this via https://github.com/microsoft/vscode-dotnettools/issues/24#issuecomment-1584859202
