### ISSUE TITLE
[BUG] vscode crashes all mac windows after hit stop button for a hanging unit test debugging

### ISSUE THREAD

**Issue by bytewayio** [microsoft/vscode-dotnettools#920]
### Describe the Issue

In one of my solutions, all unit tests are not able to run, If I click the green "Run" button, nothing happened after a build. If I choose "Debug", the test is hanging forever after a build, then if I goto test explorer, click the "Stop" button on the top, then it crashes all my mac windows (M3 Pro Max). 
I have tried the followings,
1. Open another solution, which only has two projects, debugging and running unit tests works just fine.
2. For the problematic solution, run "dotnet test", which works just fine.
3. Cleanup all bin/obj files and retry, no luck

I am using mstest for my unit tests

### Steps To Reproduce

1. Open solution folder
2. Pick any unit test
3. Right click on the green play button and choose Debug
4. Go to Test Explorer, on the top bar, there is a "Stop" button, click it, all windows are crashed (looks like Dock process was restarted)

### Expected Behavior

The test should be run in debugging mode

### Environment Information

Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:57.920Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
C# Dev Kit: v1.3.10

**Comment by bytewayio** [comment]
duplicate of https://github.com/microsoft/vscode-dotnettools/issues/910

**Comment by ocallesp** [comment]
Closing this issue since https://github.com/microsoft/vscode-dotnettools/issues/910 was fixed
