### ISSUE TITLE
[BUG] IntelliSense / XML Documentation not showing line breaks

### ISSUE THREAD

**Issue by iJungleboy** [microsoft/vscode-dotnettools#923]
### Describe the Issue

When hovering over objects which come from a DLL (with xml file in the bin folder) the intellisense correctly shows line breaks:

![image](https://github.com/microsoft/vscode-dotnettools/assets/5321186/8a5c4880-a181-4673-8508-b9ac4350dd1d)

But when IntelliSense shows the help for code files in VS code, the line breaks are not there. So in this example, the documentation in C# is this:

```c#
  /// <summary>
  /// AppResources data object
  /// 
  /// Default properties such as `.Title` or `.Id` are provided in the base class.
  /// Most properties have a simple access, such as `.DefaultFormResources`.
  /// For other properties or uses, the common method such as
  /// `IsNotEmpty("FieldName")`, `String("FieldName")`, `Children(...)`, `Picture(...)`, `.Html(...)` and more can be used.
  /// 
  /// Generated 2024-02-15 17:51:20Z - if you change the content type, remember to re-generate.
  /// </summary>
  public partial class AppResources: AppResourcesAutoGenerated
  {  }
```

But the hover "collapses" the text into one hard to consume blurb (arrows show where line breaks would be expected):

![image](https://github.com/microsoft/vscode-dotnettools/assets/5321186/c7129d95-722e-49da-839f-16dffe6a0736)

### Steps To Reproduce

1. Create a C# file containing the following contents
2. Hover over the class `Newsletter` below, the problem is immediately visible

```c#
namespace ThisApp.Data
{
  /// <summary>
  /// Newsletter data object
  /// 
  /// Default properties such as `.Title` or `.Id` are provided in the base class.
  /// Most properties have a simple access, such as `.Email`.
  /// For other properties or uses, the common method such as
  /// `IsNotEmpty("FieldName")`, `String("FieldName")`, `Children(...)`, `Picture(...)`, `.Html(...)` and more can be used.
  /// 
  /// Generated 2024-02-15 17:51:20Z - if you change the content type, remember to re-generate.
  /// </summary>
  public partial class Newsletter
  {  }

}
```

![image](https://github.com/microsoft/vscode-dotnettools/assets/5321186/9b98846f-b000-4b9a-a40b-bd5aa182452e)

### Expected Behavior

New lines in XML Docs should be respected - just like they are when the XML docs have been converted to an XML file after compile. 

### Environment Information

- OS: Windows
- VS Code: 1.86.2
- C# Dev Kit v1.3.10
- C# v2.15.30

**Comment by iJungleboy** [comment]
Additional findings

This doesn't show line breaks (as weuld be expected, and as happens if the DLL was compiled)

```c#
  /// <summary>
  /// FormData data object
  /// 
  /// Generated 2024-02-15 17:51:20Z - if you change the content type, remember to re-generate.
  /// </summary>
```

This works - but is different from normal compile behavior - note the additional `<br/>`

```c#
  /// <summary>
  /// FormData data object <br/>
  /// 
  /// Generated 2024-02-15 17:51:20Z - if you change the content type, remember to re-generate.
  /// </summary>
```

This breaks intellisense completely (`<br>` without closing `/`)
```c#
  /// <summary>
  /// FormData data object <br>
  /// 
  /// Generated 2024-02-15 17:51:20Z - if you change the content type, remember to re-generate.
  /// </summary>
```

**Comment by iJungleboy** [comment]
keep-alive...

**Comment by dibarbet** [comment]
This is by design and the same behavior that you get in visual studio.  

![image](https://github.com/microsoft/vscode-dotnettools/assets/5749229/756dad83-94ea-47d3-a0fa-857ddec76013)

Rendering in quick info can generally be controlled by html tags (e.g. using `<br/>` as you mention above).

**Comment by iJungleboy** [comment]
@dibarbet thanks - even if it's `wontfix`, I still appreciate you looking at it and comparing it to Visual Studio.
