### ISSUE TITLE
No launchable target found MAUI ios

### ISSUE THREAD

**Issue by tpitman** [microsoft/vscode-dotnettools#925]
Type: <b>Bug</b>

I am porting a Xamarin Forms app to MAUI. I was using Visual Studio 2022 for Mac.

I created a new project in the same solution and have ported everything to the point it builds.

If I open this project in Parallals in Visual Studio 2022 for Windows it builds and deploys to my iOS phone using the Mac connection system.

If I open the same app using the C# Dev Kit and MAUI extensions on my Mac in VSCode it builds without errors, but I can't debug it.

I get the error: ...[appname].csproj does not support debugging. No launchable target found.

Please advise.

Extension version: 1.3.10
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 12, 14|
|Memory (System)|64.00GB (12.33GB free)|
|Process Argv|--crash-reporter-id c904e3e7-115d-4534-addc-f9feddc53b52|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
edj9j583:30958191
7j2b6412:30964151
e3gdj431:30958358

```

</details>

**Comment by hugebug4ever** [comment]
Yes. I have to roll back to the older version (0.7.10) then all works again

**Comment by tpitman** [comment]
> Yes. In my case it's caused by the ".NET MAUI extension for VS Code" The latest 0.8.44 could not launch with ios (or find the connected device) I have to roll back to the older version (0.7.10) then all works again

Thank you

**Comment by tpitman** [comment]
I was able to select the target by clicking on the {} at the bottom left, but the device itself doesn't show up.

Once I did that I was able to F5 and have it launch.

I will have to check on Simulator. I know i got it to work on a real device.

**Comment by mauroa** [comment]
Thanks for the confirmation @tpitman. Take into account that for now, .NET MAUI only supports debugging by doing F5 (or Run >Start Debugging), and selecting .NET MAUI as the debugger.

That should work fine for any device, simulator or emulator.

Given you confirmed it worked for your device, I'll consider this as a working scenario since we also don't have a repro.
If you have any other related problem, please feel free to reopen it.

**Comment by tpitman** [comment]
There is the side bug that still exists and that is that the currently selected target does not show up between the {} on the status bar. Is that a know bug that is being worked on?
