### ISSUE TITLE
[BUG] Big massive dumps

### ISSUE THREAD

**Issue by glen-84** [microsoft/vscode-dotnettools#926]
### Describe the Issue

The extension is creating enormous dump files on Linux (WSL).

![image](https://github.com/microsoft/vscode-dotnettools/assets/261509/87a2ccc6-a994-4121-8477-bead3cc55679)

### Steps To Reproduce

No idea ... they are just there.

### Expected Behavior

Dumps should not be written without user consent, or they should at least be periodically cleaned up. Also, why are they so huge?

### Environment Information

OS: Windows 11 Home + Debian on WSL
VS Code Version: 1.86.2
Extension version: 1.3.10

**Comment by corsjune** [comment]
Also experiencing this problem, I see these errors in Output for C# dev kit

Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using local .NET runtime at "/home/wayne/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.16~x64/dotnet"
Using runtime installed in SDK.
.NET server STDERR: malloc(): unaligned tcache chunk detected

.NET server STDERR: malloc(): unaligned tcache chunk detected

.NET server exited with null

**Comment by blushingpenguin** [comment]
```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "/usr/share/dotnet/dotnet"
.NET server STDOUT: [createdump] Gathering state for process 27450 Microsoft.Visua
[createdump] Crashing thread 6b92 signal 11 (000b)

.NET server STDOUT: [createdump] Writing crash report to file /home/mark/.cache/Microsoft/csdevkit/dumps/Microsoft.Visua.27450.dmp.crashreport.json

.NET server STDOUT: [createdump] Crash report successfully written

.NET server STDOUT: [createdump] Writing minidump with heap to file /home/mark/.cache/Microsoft/csdevkit/dumps/Microsoft.Visua.27450.dmp

.NET server STDOUT: [createdump] Written 224858112 bytes (54897 pages) to core file
[createdump] Target process is alive

.NET server STDOUT: [createdump] Dump successfully written in 4424ms

.NET server exited with null
```

over and over

**Comment by MichaelMaio** [comment]
It looks like some users are encountering a relatively frequent crash in C# Dev Kit, though the dumps should be getting cleaned up periodically. Has anyone encountered the situation where they've noticed these dumps getting created, and then when you restart C# Dev Kit hours later, the dumps don't get cleaned up?

**Comment by glen-84** [comment]
@MichaelMaio

I have this at the moment:

```
$ ls -lsh /home/glen/.cache/Microsoft/csdevkit/dumps
total 695M
208M -rw------- 1 glen glen 208M Mar 26 10:24 dotnet.1743.dmp
104K -rw------- 1 glen glen 102K Mar 26 10:24 dotnet.1743.dmp.crashreport.json
237M -rw------- 1 glen glen 237M Mar 23 13:14 dotnet.5035.dmp
124K -rw------- 1 glen glen 121K Mar 23 13:14 dotnet.5035.dmp.crashreport.json
250M -rw------- 1 glen glen 250M Mar 20 17:46 dotnet.7793.dmp
104K -rw------- 1 glen glen 104K Mar 20 17:46 dotnet.7793.dmp.crashreport.json
```

Is it supposed to clean up all of these files, or leave the last _n_ files?

**Comment by MichaelMaio** [comment]
OK I double-checked and we currently wait 7 days before cleaning up the dumps. Has anyone noticed a dump older than that? If the component responsible for doing the clean-up hits a problem too soon in its execution, that could delay the clean-up. I'm looking into making a change in a future release that will make that less likely to happen.

**Comment by jpda** [comment]
None of my current ones are more than 7 days old. Previously I don't remember noticing their age

**Comment by glen-84** [comment]
> Has anyone noticed a dump older than that?

No, it seems to be behaving itself now.

```
$ ls -lsh /home/glen/.cache/Microsoft/csdevkit/dumps
total 256M
255M -rw------- 1 glen glen 255M Apr  2 20:12 dotnet.2455.dmp
112K -rw------- 1 glen glen 111K Apr  2 20:12 dotnet.2455.dmp.crashreport.json
```

**Comment by arkalyanms** [comment]
Closing based on recent comments. @MichaelMaio if we want to revisit the 7 day cleanup policy, feel free to reopen or open a internal tracking bug.

**Comment by MichaelMaio** [comment]
I did decide to reduce the dump retention to 2 days in order to help reduce the disk space usage for high-frequency crashes. So that should be noticeable in a future release.
