### ISSUE TITLE
[BUG] MSBUILD : error MSB1006: Property is not valid.

### ISSUE THREAD

**Issue by chungsavi** [microsoft/vscode-dotnettools#934]
### Describe the Issue

dotnet publish "PATH/*.csproj" -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64  -p:CodesignKey=@"iPhone Distribution: NAME., Ltd. (Code)" -p:CodesignProvision="ProvisionName"

=>
MSBuild version 17.9.4+90725d08d for .NET
MSBUILD : error MSB1006: Property is not valid.
Switch:  Ltd. (525P9MKHKJ)

There is "," character in CodesignKey that is cause of error.

**Comment by tmeschter** [comment]
@chungsavi You see this error when running `dotnet publish` on the command line, correct? It isn't specific to C# Dev Kit?

**Comment by kirankumar4vr** [comment]
This issue still persists when running dotnet publish

**Comment by kirankumar4vr** [comment]
> @chungsavi You see this error when running `dotnet publish` on the command line, correct? It isn't specific to C# Dev Kit?

Yes, the error is occurring when runniing 'dotnet publish' for publishing .net MAUI iOS app on the terminal.

**Comment by FranRDev** [comment]
I have the same issue.

**Comment by softlion** [comment]
> I have the same issue.
> 
> Edit: This could help > [dotnet/msbuild#471 (comment)](https://github.com/dotnet/msbuild/issues/471#issuecomment-337938272)

Yes this is the exact same issue. See my solution there.

**Comment by pekichan11** [comment]
if anybody have this problem I use Bash job and put in the script like this 
-p:CodesignKey="\"$(APPLE_CERTIFICATE_SIGNING_IDENTITY)\""
and it is working for me :)
