### ISSUE TITLE
[BUG] Break on exception not available in MAUI projects

### ISSUE THREAD

**Issue by zwikk** [microsoft/vscode-dotnettools#936]
### Describe the Issue

While debugging a MAUI project, the Breakpoints ```All Exceptions``` and ```User-Unhandled Exceptions``` are not available in the Breakpoints section. The Breakpoints section is simply empty

### Observations
- Normal breakpoints work fine.
- Break on exceptions works great for other .NET project types such as a Console app.

I'm on MacOS, I really love VSCode and want to love building MAUI apps in it. Bugs like these keep forcing me back to VS for Mac which i really don't want.

### Steps To Reproduce

1. Create a new or open an existing MAUI project
2. Press F5 to start debugging
3. Observable that the Breakpoints section is empty

### Expected Behavior

The breakpoints section should provide break-on-exception options like so:

<img width="304" alt="Screenshot 2024-02-21 at 11 08 03" src="https://github.com/microsoft/vscode-dotnettools/assets/123168199/af415947-0176-41a4-8861-f1a4d9432aff">

### Environment Information

- OS: MacOS (on Apple Silicon)
- VSCode 1.86.2
- Extensions:
  - C# v2.18.15 (pre-release)
  - C# Dev Kit v1.4.2 (pre-release)
  - .NET MAUI v0.9.3 (pre-release)
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1978129">1978129</a>

**Comment by JeroenBer** [comment]
I also really miss this feature a lot...

**Comment by MarkiianKhylynskyi** [comment]
I have the same issue

**Comment by mauroa** [comment]
Hi @zwikk, @JeroenBer, @MarkiianKhylynskyi. This issue should be already fixed if you update .NET MAUI to latest pre-release and also .NET SDK to at least 8.0.202.
We've introduced a new debug engine for MAUI apps (the same used by other C# projects), but it's available only from .NET 8.0.3 runtime (which is include from .NET SDK 8.0.202).

Please give it a try and let me know if that fixes your issues.
Thanks

**Comment by zwikk** [comment]
After upgrading my sdk, break on exception seems to work. This is a welcome fix.

**Comment by gkarabin** [comment]
> Hi @zwikk, @JeroenBer, @MarkiianKhylynskyi. This issue should be already fixed if you update .NET MAUI to latest pre-release and also .NET SDK to at least 8.0.202. We've introduced a new debug engine for MAUI apps (the same used by other C# projects), but it's available only from .NET 8.0.3 runtime (which is include from .NET SDK 8.0.202).
> 
> Please give it a try and let me know if that fixes your issues. Thanks

Will the preview work with 8.0.4 runtime / SDK 8.0.204? With the preview and 8.0.4 installed, I don't see the break-on-exception option.

**Comment by MarkiianKhylynskyi** [comment]
@mauroa The issue is fixed after the update. Thanks

**Comment by dingxiaolong** [comment]
I still can not see UI like the image that the OP provided in the issue.

<img width="565" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/21192107/c7a45e14-37ab-4a77-a0f1-128fbdffd010">

My dotnet version is 8.0.300.

Is anyone know how to configuge it please ?

**Comment by dingxiaolong** [comment]
> Switch your .NET MAUI Extension to prerelease version and check the experimental option '_Use the .NET Core Debugger backend to debug MAUI apps_' in the Extension settings of VSCode

Thanks for your feedback . I already try that ,still can not see the option on my side ..   it is empty in the breakpoints section.
![image](https://github.com/microsoft/vscode-dotnettools/assets/21192107/0ae8a094-7835-43a6-8cbc-bc52935efeb1)

MAUI extension is prerelease version , and dotnet version is 8.0.300,   I don't know whether there is extra setting.  
![image](https://github.com/microsoft/vscode-dotnettools/assets/21192107/40732e5a-fb98-4a94-8ce4-0e266b93b280)
