### ISSUE TITLE
[BUG] Connection is Disposed

### ISSUE THREAD

**Issue by g4rc1ss** [microsoft/vscode-dotnettools#939]
### Describe the Issue

Lately I get this message a lot when I try to open the project in Solution Explorer view

![image](https://github.com/microsoft/vscode-dotnettools/assets/28193994/fbe059b9-1028-4a44-9a7c-a87d098c7a2e)

I have not been able to see a pattern, it happens sometimes when it is in the background and I also see that it does not finish loading the projects.
![image](https://github.com/microsoft/vscode-dotnettools/assets/28193994/ad52af7a-643c-4951-9cd2-2a427c61681a)
> It takes about 10 minutes

### Environment Information

- OS: Windows
- Vscode Version: 1.86.2
- C# Dev Kit Version: 1.4.2(pre-release)

**Comment by lifengl** [comment]
can you provide extension log file (use viscose command to open extension log folder), and try to find log files inside DevKit logging folder, under. serviceHub folder.

**Comment by g4rc1ss** [comment]
It's not happening anymore since the last updates, I tried to recover the logs, but they are more than 1 month old 

@lifengl I close issue and if it happens again, I open a new one and I attach the logs.
