### ISSUE TITLE
[BUG] .NET Core SDK cannot be located on Linux

### ISSUE THREAD

**Issue by inflop** [microsoft/vscode-dotnettools#94]
### Describe the Issue

The .NET SDKs are manually installed from the tar archives and are recognized properly in the command line (bash, zsh), but are not visible for the C# extension on the project loading.
Before upgrading to the newest C# Dev Kit all worked fine.
![obraz](https://github.com/microsoft/vscode-dotnettools/assets/7738902/d8d43deb-1aab-49e8-9a6d-6fd2e910dd86)

### Environment Information

- Arch Linux (rolling, Gnome 44.2, X11, kernel-6.1.32-1-lts)
- VS Code 1.79.0 (Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302)
- Extensions:
 - C# Dev Kit v0.1.83 (Preview),
 - C# v2.0.206 (Pre-Release)

**Comment by timheuer** [comment]
Hi @inflop can you confirm how the .NET SDKs were installed on your linux instance? throught the distro packages or via install scripts, etc?

**Comment by inflop** [comment]
Hi, all SDKs were downloaded from https://dotnet.microsoft.com and installed from archives, ex. dotnet-sdk-X.Y.ZZZ-linux-x64.tar.gz using the below commands:

```bash
mkdir -p $HOME/.dotnet && tar zxf dotnet-sdk-X.Y.ZZZ-linux-x64.tar.gz -C $HOME/.dotnet
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$HOME/.dotnet
```
The directory `$HOME/.dotnet` is a symlink to `/mnt/sdb1/rk/.dotnet/` on the mounted disk where is my `/home` partition shared by multiple Linux distros.
I would like to note that from the terminal/command line (bash, zsh), everything works fine, projects build properly and all SDKs are recognized correctly as well.

**Comment by WardenGnaw** [comment]
Can you use the setting `dotNetCliPaths` and does that fix it for you?

![image](https://github.com/microsoft/vscode-dotnettools/assets/3953714/e7d59bde-0fe0-4a46-85b5-c6731e0f978f)

This should be resolved when we centralize the SDK acquisition for C# Extension and C# Dev Kit.

**Comment by inflop** [comment]
Hi, I've added path `/home/rk/.dotnet/dotnet` to this settings and it looks like it works fine now. Thanks.
![image](https://github.com/microsoft/vscode-dotnettools/assets/7738902/83a88563-bb10-4eba-953c-e74d680f17df)

**Comment by timheuer** [comment]
I think I'd like to keep this open to see how we can improve this.  It affects some WSL/remote scenarios also.

**Comment by nagilson** [comment]
Once global installs are added, we will automatically do the install using the distro feed if we can, and if we can't, we will attempt to add and use the microsoft feeds.

**Comment by nagilson** [comment]
Closing this since the new api has been released to do this automatically for the user
