### ISSUE TITLE
cuurent version availability

### ISSUE THREAD

**Issue by Harbaksh1** [microsoft/vscode-dotnettools#948]
Type: <b>Feature Request</b>

my vs code is not showing the latest C#  version 12 

Extension version: 1.3.10
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by nagilson** [comment]
@arkalyanms Does CDK support C# 12 features? Who would know that timeline?

**Comment by arkalyanms** [comment]
The SDK pulled in would likely be decided between CPS and SDK. cc: @lifengl

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
