### ISSUE TITLE
[BUG] Debugger fails when using Slashes instead of Back-Slashes in launch.json projectPath 

### ISSUE THREAD

**Issue by markusroessler** [microsoft/vscode-dotnettools#950]
### Describe the Issue

On Windows the debugger fails  with message
`.../XXX.csproj' does not support debugging. No launchable target found.` when using slashes instead of back-slashes in the launch.json projectPath property. This took me quite some time to figure out (not a very meaning-full message for this case).

### Steps To Reproduce

1. create a new dotnet console project
2. create launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C#: Debug",
            "type": "dotnet",
            "request": "launch",
            "projectPath": "${workspaceFolder}/xxx/xxx.csproj"
        }
    ]
}
```
3. start debugging
4. error "No launchable target found." occurs
5. replace "/" with "\\" in the launch.json projectPath
6. start debugging
7. the console app starts as expected

### Expected Behavior

Devkit should automatically translate slashes to back-slashes as needed (as it does with other properties)

### Environment Information

- OS: Windows 10
- VSCode: 1.86.2
- Devkit: 1.3.10

**Comment by IEvangelist** [comment]
This issue still exists, and I can confirm that I'm experiencing it too, and that it's easily reproduceable.

**Comment by tmeschter** [comment]
This was completed in the June milestone.
