### ISSUE TITLE
[BUG] Click F5 button doesn't run browser if builder.Logging.ClearProviders(); has been called

### ISSUE THREAD

**Issue by vad-bond** [microsoft/vscode-dotnettools#952]
### Describe the Issue

I am trying to debug webapi application. By default when new project is created F5 button click should run browser on swagger page. But seems like builder.Logging.ClearProviders(); affect this behaviour. 

### Steps To Reproduce

1. dotnet new webapi
2. Open VS Code 
3. add builder.Logging.ClearProviders() statement
![image](https://github.com/microsoft/vscode-dotnettools/assets/81078859/ce5ead9f-2ad8-4ba0-9c62-68994af6070e)

5. Click F5 button

### Expected Behavior

New browser window on swagger page

### Environment Information

- OS: Windows
- dotnet: 8.0.101
- VS Code: 1.86.2
- C# dev kit: 1.3.10

**Comment by WardenGnaw** [comment]
I believe `builder.Logging.ClearProviders()` will remove the console logger that will output the browser uri pattern that is used by VS Code to determine the server is ready to connect.

See https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program

Unless the URI is written to the debug console, this wont work. If you need this scenario to work, you will need VS Code to implement a way to support launching a browser via a different method at https://github.com/microsoft/vscode/issues
