### ISSUE TITLE
[BUG] Unable to create project using C# Dev Kit on Apple M1

### ISSUE THREAD

**Issue by leventym** [microsoft/vscode-dotnettools#955]
### Describe the Issue

When I try to create a new .NET project in my existing folder via the command palette nothing happens.

I click in the + icon inside the Solution Explorer and the command palette dropdown is shown, there I click .NET new project and pick a type of project to create. Next, nothing happens.

If I try to navigate among my folders VS Code sort of freezes..

https://github.com/microsoft/vscode-dotnettools/assets/89446917/a9ae55b8-82ad-4017-b369-b434ad3bb1af

### Steps To Reproduce

In existing .NET project I create a new Solution folder, within that folder I try to create a new project.

### Expected Behavior

Create a Console App

### Environment Information

- OS: macOS Sonoma 14.3.1
- VS Code version: Version: 1.86.2
                                  Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
                                  Date: 2024-02-13T19:42:12.210Z (1 wk ago)
                                  Electron: 27.2.3
                                  ElectronBuildId: 26908389
                                  Chromium: 118.0.5993.159
                                  Node.js: 18.17.1
                                  V8: 11.8.172.18-electron.0
                                  OS: Darwin arm64 23.3.0
- C# Dev Kit version: v1.3.10

**Comment by smitpatel** [comment]
@leventym - Can you try latest version of C# dev kit and see if you are seeing the same behavior?

**Comment by smitpatel** [comment]
@leventym - Following up on this if you are still seeing the issue?

**Comment by leventym** [comment]
Hi @smitpatel the issue seem to have resolved itself.
