### ISSUE TITLE
[BUG] Contextual UI for test results doesn't render correctly

### ISSUE THREAD

**Issue by asilverman** [microsoft/vscode-dotnettools#956]
### Describe the Issue

See below rendering of right click on the red X icon near LOC 226
![image](https://github.com/microsoft/vscode-dotnettools/assets/9611108/ad544bc6-0851-4897-9848-cbc9b34d2bb7)

### Steps To Reproduce

1. Spin up a codespaces for this repo https://github.com/Azure/bicep
2. Run the test: `TryAddProperty_adds_object_properties`

### Expected Behavior

You can see the test results in the UI

### Environment Information

- OS: Host: Windows, Codespace: Linux 
- VSCode Version:
```
Version: 1.87.0-insider (user setup)
Commit: e73419bef379f7956f024557cbf40bd3755a0645
Date: 2024-02-26T14:31:00.814Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```
- Extension Version: v1.3.10

**Comment by ocallesp** [comment]
Moving this issue to vscode https://github.com/microsoft/vscode/issues/208714

**Comment by AbhitejJohn** [comment]
Tagging @asilverman for the migration @ocallesp made here. We believe this is an issue in VS Code itself, hence the move.
