### ISSUE TITLE
[BUG] Install extension on remote Ubuntu server that has a self-signed certificate fails to install

### ISSUE THREAD

**Issue by xendren** [microsoft/vscode-dotnettools#969]
### Describe the Issue

We have been using VS Code and C# extension with remote extensions to a remote Ubuntu server with a self-signed certificate for 4 years now without any issues.  Our devs recently cleared their remote vs code server cache on the dev server to clean up the cache.  When they remote back into the dev server with VS Code, they have to reinstall the C# Dev Kit as expected.  During the install they receive **ERROR:  self-signed certificate in certificate chain.**

The dev team is completely dead in the water at this point.

We found some older posts with Vs Code about NODE need the NODE_EXTRA_CA_CERTS pointing to the self-signed CA file, but that isn't working.  We tried NODE_TLS_REJECT_UNAUTHORIZED=0, and that did not work either.

### Steps To Reproduce

Use Remove SSH into an Ubuntu server that has a self-signed certificate.
Try to install version 1.3.10 of the C# Dev Kit on the remove server.
Error occurs about the self-signed certificate.

### Expected Behavior

It should work as it has been for many years and not fail to install the extension.

### Environment Information

- OS:  Ubuntu 20.04.6 LTS
- VS Code:  1.87

**Comment by xendren** [comment]
Ok.  It seems top be occurring for all extensions now.  I'll file a bug with the base VS Code project.  Trying to set the NODE_EXTRA_CA_CERTS environment variable does not appear to change any behavior.  Confusing why this just suddenly stopped working recently if it is base vs code.

**Comment by DomoniqueSells** [comment]
Any update?

**Comment by xendren** [comment]
> Any update?

Nope.  It is now happening for all extensions, so we are opening a Bug at the top level VS Code project and seeing if our Microsoft Support contact can help.  None of the suggested fixes for telling node.js where the extra self-signed CA file is working.

**Comment by AbhitejJohn** [comment]
@xendren : That does not sound great. Please let us know if you already have a bug on VS Code tracking this.

**Comment by xendren** [comment]
> @xendren : That does not sound great. Please let us know if you already have a bug on VS Code tracking this.

Our admins were able to get a consolidated CA file with full self-signed chain, and setting the NODE_EXTRA_CA_CERTS at the system level did make it work.  No idea why that was suddenly necessary in the past 6 months.

**Comment by xendren** [comment]
Closing this since it has been resolved for us.
