### ISSUE TITLE
Don't silently swap out ms-dotnettools.csharp versions.

### ISSUE THREAD

**Issue by cmacfarl** [microsoft/vscode-dotnettools#970]
### Describe the Issue

At times unknown to the developer, something associated with .net will download newer versions of

```
.vscode-server/extensions/ms-dotnettools.csharp-<major>.<minor>.<point>-linux-x64
```

And will point vscode at the newer version.

I have some custom changes to my ms-dotnettools.csharp and every time this happens software breaks.

For example, I have custom changes to 
```
.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64
```
and unbeknowest to me, on Feb 26 
```
.vscode-server/extensions/ms-dotnettools.csharp-2.18.16-linux-x64
```
showed up and vscode decided to start using it instead causing software to break, and thrashing around while the change to 2.15.30 was ported to 2.18.16.

Please either stop this behavior, or document how to prevent it.

### Steps To Reproduce

Use vscode for a few months and observe how your ms-dotnettools.csharp installations will change with no notification or input from the user.

### Expected Behavior

I expect that .net will not silently change the tooling that I am using to develop software.

### Environment Information

VSCode running on Windows using the remote SSH feature to develop and debug on a Linux box.

**Comment by timheuer** [comment]
Thanks for the feedback ehre -- this however is not a .NET extension capability, but rather you are seeing the behavior of VS Code default settings that can be user-controlled per the documentation: https://code.visualstudio.com/docs/editor/extension-marketplace#_extension-autoupdate.  By default the VS Code setting is set to auto-update.

You can change this setting to be per-extension, none, or other settings from the VS Code settings:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/a7c3774c-d740-42c7-91b8-ff5a0eec6dc4)

And then with this example (using 'only selected') then a new option shows in VS Code extension manager per extension to declare if you want it to auto-update or not:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/1e7684b6-0948-4407-bdcb-bfc7a2311631)

If you have sync settings per extension or anything this may affect it as well, or in remotes (as it appears you may) you would also need to ensure your settings in the remote are matched to your desires as well.

I hope this helps understand the settings you can modify to lock to a version for your liking.  I'll close this as it isn't something this extension delivers, but rather the VS Code extension management capabilities.

**Comment by cmacfarl** [comment]
Thank you very much for this documentation.  It looks like what I was looking for, but couldn't find.
