### ISSUE TITLE
[BUG] Test runner failing to report test results

### ISSUE THREAD

**Issue by DavidMartynWood** [microsoft/vscode-dotnettools#974]
### Describe the Issue

vscode does not report the results of dotnet tests consistently. The Test Results window very frequently indicates that the tests didn't run (with a grey circle next to the test run).

I've tried with nunit and xunit, both in Windows and in WSL, and I'm getting the same result.

### Steps To Reproduce

Using the code from this repo, which was created using the vscode xunit template: https://github.com/DavidMartynWood/xunittest

1. Start vscode
2. `dotnet build` from the terminal
3. (wait for tests to appear in Testing window)
4. Right-click on each test in the Testing Windows and run them
5. Some tests will run, but others will report "The test run did not record any output"

![image](https://github.com/microsoft/vscode-dotnettools/assets/9726004/eded9907-0c21-41c1-bab9-50fb9508dcc1)

### Expected Behavior

Tests should report "Success", "Failed", "Inconclusive".

I thought this might be the dotnet test runner refusing to run the tests because it thought the code hadn't changed, but even when I change the code the tests can very frequently fail to run.

### Environment Information

Windows 10 (10.0.19045)
Vscode: 1.87.0

Extensions:
C# Dev Kit: 1.3.10
C# (base language support for C#): 2.18.16
.NET Install Tool: 2.0.2
(all other extensions disabled)

Additionally, tried on this same platform in WSL (Ubuntu) but had the same issue.

I have tried updating the nunit/xunit NuGet packages but this didn't help.

I get the same problem when debugging tests.

**Comment by peterwald** [comment]
I believe this is a duplicate of #927, which has already been fixed and is pending release. The fix should be available in the most recent pre-release.

**Comment by DavidMartynWood** [comment]
Yes I agree this is very likely the same issue. Thank you for the quick response.

**Comment by DavidMartynWood** [comment]
Verified with the latest pre-release and it's working well. I swear I tried the pre-release yesterday before I reported this, but I must have messed something up. Thank you again.

**Comment by hornta** [comment]
I'm getting the same issue in version 1.89.1
