### ISSUE TITLE
'dotnet' is not recognized 

### ISSUE THREAD

**Issue by WilfredBridges** [microsoft/vscode-dotnettools#979]
### Describe the Issue

in vscode terminal The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Although it is installed and works in powershell.

### Steps To Reproduce

1. Open terminal
2. Enter dotnet --version
3. The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Expected Behavior

8.0.201

### Environment Information

VS Code on Windows

**Comment by nagilson** [comment]
Do you have output from the .NET Install tool or its logs in

Linux: ~/.config/Code/logs
Mac: ~/Library/Application Support/Code/logs/
Windows: c:\Users\USER\AppData\Roaming\Code\logs\?

**Comment by nagilson** [comment]
If you are still facing this issue, please let us know and add the necessary details for us to help you.
