### ISSUE TITLE
[SUGGESTION] code interpreter not work when symbol not defined

### ISSUE THREAD

**Issue by 37wjy** [microsoft/vscode-dotnettools#983]
### Describe the feature you'd like

enable  interpreter in block where symbol not defined
<img width="526" alt="截屏2024-03-13 11 51 01" src="https://github.com/microsoft/vscode-dotnettools/assets/34015616/b966deb4-32f3-4af3-b493-4f8398efc46e">
<img width="458" alt="截屏2024-03-13 11 51 16" src="https://github.com/microsoft/vscode-dotnettools/assets/34015616/bcda258f-474d-403a-a5ea-cf793efe4fe4">

**Comment by dibarbet** [comment]
This is by design.  Providing language features in in-active preprocessor regions is too costly for the benefit received.  
See also https://github.com/dotnet/roslyn/issues/13282
