### ISSUE TITLE
CAN'T INSTALL THIS .NET SHIT

### ISSUE THREAD

**Issue by Brynana-LBX** [microsoft/vscode-dotnettools#984]
Type: <b>Bug</b>

I WAS WORKING IWTH UNITY AND SUDDENLY THESE TWO EXTENSIONS CALLED C# AND C# DEV KIT SUDDENLY STARTED INSTALLING EVEN THOUGH I ALREADY HAVE IT AND THEN IT TOLD ME TO INSTALL THIS SHIT .NET WHICH WORKS BEFORE BUT NOT NOW, AND IT JUST KEEPS GIVING ME TIMEOUTS FUCK YOU FIX THIS PIECE OF SHIT AND GET A LIFE, HOW DO I EVEN INSTALL THIS SHIT MANUALLY, CAN ANYONE WITH A BRAIN GIVE MORE INFORMATION ON THIS SHIT? WHY DID IT SUDDENLY NOT WORK?!!??!?!?!?!?!?!?!?!?!?!?

Extension version: 1.3.10
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13650HX (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (4.64GB free)|
|Process Argv|C:\\Users\\bryan\\Documents\\Bryan\\OHNO Games\\Unity Projects\\Argon Assault - Udemy Section 4 -g C:\\Users\\bryan\\Documents\\Bryan\\OHNO Games\\Unity Projects\\Argon Assault - Udemy Section 4\\Assets\\Scripts\\PlayerControls.cs:1:0 --crash-reporter-id 9cd4e22f-df53-4aaa-856b-71f8c0f81ee4|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30986170
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by jbevain** [comment]
This is absolutely not the way to report an issue here. Let me remind you that contributing to this repository should follow our [code of conduct](https://github.com/microsoft/vscode-dotnettools/blob/d22de373166b7a02ee175da949c66b3a58291b40/CODE_OF_CONDUCT.md).

I'm inviting you to edit your issue and provide a constructive report, otherwise I'm simply going to close this.

Thank you!
