### ISSUE TITLE
Display test output for successful tests

### ISSUE THREAD

**Issue by dstrijbos** [microsoft/vscode-dotnettools#989]
Type: <b>Feature Request</b>

Currently, when I run tests using the C# Dev Kit, the output is only shown in the Test Results when the test fails. When the test succeeds, no output is shown. This behavior is different from the Visual Studio Professional Test Explorer where the standard output is shown even if a test succeeds. 

In my case, I'm writing Behavior Driven Development tests (using SpecFlow and xUnit) wherein some values are generated which I would like to verify after the test runs, even on success, but this minor discrepancy forces me to use VS Professional where I would rather use VS Code.

Extension version: 1.4.29
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by AbhitejJohn** [comment]
@dstrijbos : Curious, does the pane Output-> C# Dev Kit - Test Explorer have what you are looking for?

**Comment by peterwald** [comment]
This is now fixed and will be in an upcoming pre-release.
