### ISSUE TITLE
[SUGGESTION] Prevent opening `*.csproj` file on mouse left button click

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#991]
Very annoying when you accidentally click on a `Project` in `Visual Studio IDE` explorer and the `*.csproj` file opens. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/ba472cf9-1c7f-45be-838d-0f571cdb8a13)

Please give the optional  opportunity in `C# Dev Kit explorer` to open `*.csproj` fils from the context menu instead of mouse left button click. Please do for `.sln` files too.

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/b2c9812b-1107-48be-ad31-96e33fe556e7)

**Comment by jbevain** [comment]
Hello @BachiMjavanadze,

Thanks for reaching out. As your suggestion is about the Visual Studio IDE, please use the [Report a problem with the Visual Studio product](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) guide.

Thank you!
