### ISSUE TITLE
Unable to run debug

### ISSUE THREAD

**Issue by gdmec07131049** [microsoft/vscode-dotnettools#994]
Type: <b>Bug</b>

All configuration is normal, when I press F5, it will display a debugging bar for about 2 seconds, but then it will automatically shut down and automatically stop debugging, the following is the configuration of launch.jsong:    
"type": "vstuc",
            "name": "Unity Editor",
            "request": "attach"

Extension version: 1.0.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (0.89GB free)|
|Process Argv|E:\\UnityProject\\Git\\pofi3\\pofi3 -g E:\\UnityProject\\Git\\pofi3\\pofi3\\Assets\\pofi3\\Test\\JH_Test\\BoneSyncTool.cs:1:0 --crash-reporter-id 24003f0e-858c-41cf-91cc-0fb863dce932|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30958156
dsvsc020:30976470

```

</details>

**Comment by sailro** [comment]
Hello, do you reproduce the same issue when using the "Attach Unity Debugger" command ? (CTRL+Shift+P)

Anything interesting in the `output` window, `Unity` tab?

Thanks!

**Comment by gdmec07131049** [comment]
.net版本不一致导致的，重新匹配就行
&nbsp;


军魂科技
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sebastien ***@***.***&gt;; 
发送时间: 2024年3月15日(星期五) 凌晨0:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vscode-dotnettools] Unable to run debug (Issue #994)





 
您好，您在使用“附加 Unity 调试器”命令时是否重现了相同的问题？（CTRL+Shift+P）
 
窗口中有什么有趣的东西吗？outputUnity
 
谢谢！
 
-
 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by jbevain** [comment]
It's unclear from your answer if you're still running an issue or not. If so, please clarify and add the requested information so we can help you. Thanks!

**Comment by jbevain** [comment]
Closing as we've not heard back. Feel free to add more details if you still need help. Thanks!
