### ISSUE TITLE
[BUG] C# Testing build task can't be configured?

### ISSUE THREAD

**Issue by srockdavew** [microsoft/vscode-dotnettools#995]
### Describe the Issue

When I attempt to refresh the "Testing" extension in vscode, a build process is run in order to find the unit tests.  However, the dotnet build command that it runs by default is not configured correctly as it needs a /p:configuration parameter for my solution to build correctly.  My solution's default "Debug" configuration only builds correctly on Windows and so I use a special "Linux-Debug" configuration for the Linux build which removes the projects that won't build on that platform.  As a result, the build step of the "Testing" extension build fails on Linux and the "Testing" tab is useless to me.  I cannot find where or how to add my custom task settings for this build step or even verify that its possible to customize this step.

### Steps To Reproduce

1. Have a solution where the "Debug" configuration is not buildable on Linux, but where there is another configuration that does work on Linux
2. Refresh the "Testing" extension and have it try and build the wrong configuration
3. The build fails because that's expected
4. Get frustrated that you cannot figure out how to configure this one build task in the same fashion that all other build tasks can be configured

### Expected Behavior

I expect a clear way to assign a build task in tasks.json to the "Testing" refresh step in the testing extension.

### Environment Information

OS: Linux, though I expect this is an issue across the board for all platforms

**Comment by tverboon** [comment]
As a workaround you could consider to create a solution file for Linux, containing only the projects you need to work on Linux. This probably would simplify your build task also. But I agree more configuration would be welcome: #365

**Comment by srockdavew** [comment]
Thanks for your reply!

**Comment by arkalyanms** [comment]
This is not related to the C# Dev Kit extension.
