### ISSUE TITLE
Can't build when project open in both VS Code and VS

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-dotnettools#998]
Type: <b>Bug</b>

When I have the same project open in both VS Code and VS, something gets locked and I can't build/run the project in either product.

Extension version: 1.5.4
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (50.58GB free)|
|Process Argv|--crash-reporter-id 1daef53e-ac9f-4f1a-a090-a5396df29903|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
gee8j676:30988843

```

</details>

**Comment by Michael-Eng** [comment]
This is unsupported. Remember that we keep a lot of components loaded, running, building while your solution is open. Keeping them open in 2 instances of VS isn't really supported, Keeping them open in both VS Code and VS at the same time is also won't fix.

**Comment by svrooij** [comment]
@Michael-Eng In my personal opinion then you might need an "unload" button in VSCode. The support for bicep is much better in VSCode then in VS. So my project might be opened in VSCode to change the bicep part and in VS to do the actual coding.

Saying it's "unsupported" will just make me disable/remove the C# part from VSCode, while sometimes I do want to work in VSCode to do my C# work, (GitHub Copilot works there better).
